import { app_g_bless_door_skipped_is } from "./app_g_bless_door_skipped_is.mjs";
import { property_get } from "./property_get.mjs";
import { app_g_bless_overlay_begun } from "./app_g_bless_overlay_begun.mjs";
import { app_g_bless_overlay_turned } from "./app_g_bless_overlay_turned.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { app_g_bless_transfer_overlay } from "./app_g_bless_transfer_overlay.mjs";
export async function app_g_bless_overlay(container_map) {
  arguments_assert(arguments, 1);
  ("The praying game: a world seen from above and filling the screen, the player standing in");
  ("the middle of it, the ground they are looking across washed pale, and a prayer for");
  ("anybody in it they tap.");
  ("Three verbs, and one of them is the prayer. Turning swings the cone, from four small");
  ("arrows along the bottom where a thumb already is. Walking carries it, from a tap on");
  ("empty ground - the player walks there a step at a time and what they can see changes the");
  ("whole way, so a walk is not travel between two screens, it is the game.");
  ("A tap on somebody prays for them, and only if they are inside the cone. Sight is the");
  ("cost: a person standing behind the player is not somebody they are looking at, so that");
  ("tap walks them round instead - the same wish answered the way this game answers it.");
  ("The prayer goes up on a panel of its own with nothing to press until it has been read,");
  ("so the player says the words rather than passing over them. Reading the prayer is the");
  ("player's part of this game; a label they skipped would leave the game praying by itself,");
  ("which is the one thing it must never do.");
  ("How far a prayer reaches is never displayed and is the whole of what there is to");
  ("discover. It shows up in the words of the prayer itself and nowhere else - the day a");
  ("player reads their block into it is the day they find out they had earned it.");
  ("The map is drawn once and never again. Only the wash, the readout and the button are");
  ("redrawn, because rebuilding the map would replace the very picture that is sliding and");
  ("the player would jump rather than walk.");
  let r = app_g_bless_overlay_turned(container_map);
  ("The dev way in goes up as soon as there is a street under it, and the address is asked");
  ("what it wants straight after. Both are done HERE because this is the first place the");
  ("world exists, and every dev screen in this game reports on the world - asked earlier");
  ("they would have to build one of their own, and a screen describing a street the player");
  ("is not standing in would be believed rather than doubted.");
  let world = property_get(r, "world");
  app_g_bless_dev_entry();
  let drawn = await app_g_bless_dev_if(world);
  let r2 = await app_g_bless_overlay_begun(r, container_map);
  let begun = property_get(r2, "begun");
  let transfer = property_get(r2, "transfer");
  ("The door is put up unless the address asked to open past it. The skip is taken HERE,");
  ("where the door is put up, rather than inside the door itself, because a door that");
  ("sometimes builds nothing is a screen with two meanings; here there is one line saying");
  ("which of two things this visit is, and the door below stays the one thing it always was.");
  ("A dev screen counts as asking past it, and it is ORed in here rather than folded into");
  ("the question next door, because the two are different kinds of asking: one is a word");
  ("this game reserved for exactly this, the other is any word that turned out to name a");
  ("screen. Folded together, adding a dev route would quietly change what the door does.");
  let asked = app_g_bless_door_skipped_is();
  let skipped = or(asked, drawn);
  if (skipped) {
    begun();
    return transfer;
  }
  app_g_bless_transfer_overlay(transfer, begun);
  return transfer;
}
