import { fn_name } from "./fn_name.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
export function app_code_lesson_ids_short() {
  arguments_assert(arguments, 0);
  ("The id every code lesson is stored and linked under, one per lesson, written down here rather than worked out from anything.");
  ("An id used to be built out of the lesson's category word and the words handed to its title maker, which made it a consequence of two decisions that were never about it. Rewording a title moved it. Recategorising a lesson moved it. Both are edits a person makes for how a page reads, and neither looks like it touches a key a learner's finished work is stored under. Written down, an id moves when somebody moves it and at no other time.");
  ("★ THE KEY IS THE LESSON'S OWN FUNCTION NAME, NOT ITS TITLE. That is the one name for a lesson that this repo already keeps honest: it is unique because two functions cannot share a name, and a rename carries every reference to it. Spelled out as plain words rather than through the name-reader, because there are a hundred and thirty-three of them and that many imports would cost every page that loads this more than the whole table saves. The price of the plain spelling is that renaming a lesson stops it being found here - which throws, loudly, next door.");
  ("They are short because they are read by people in two places where length is the whole cost: the address bar of a link somebody is passing to somebody else, and a record on a learner's own device. They are not shortened past recognition - a person who has done the lesson should know which one a link names.");
  ("The shape follows the function name rather than the sentence a learner reads, so a lesson that chooses which operator to solve first opens with order, one about brackets opens with brackets, and one that gives a value a name opens with name. That grouping is what makes a hundred and thirty-three of them scannable at all.");
  let short = {
    app_code_lesson_symbols_digits_numbered: "digits_numbered",
    app_code_lesson_symbols_digit_number: "digits_in_number",
    app_code_lesson_symbols_digits: "digits",
    app_code_lesson_symbols_letters: "letters",
    app_code_lesson_symbols_space: "space",
    app_code_lesson_identifiers_letters_spaces: "name_letters",
    app_code_lesson_identifiers_underscores: "name_underscores",
    app_code_lesson_identifiers_dollar_signs: "name_dollars",
    app_code_lesson_identifiers_symbol_first: "name_symbol_first",
    app_code_lesson_identifiers_symbol_first_unseparated: "name_symbol_run",
    app_code_lesson_operators_addition: "add",
    app_code_lesson_operators_subtraction: "subtract",
    app_code_lesson_operators_multiplication: "multiply",
    app_code_lesson_operators_division: "divide",
    app_code_lesson_operators_minus: "minus",
    app_code_lesson_operators_asterisk: "asterisk",
    app_code_lesson_operators_slash_forward: "slash",
    app_code_lesson_operators_dot_numbers: "dot_numbers",
    app_code_lesson_operators_dot_missing: "dot_missing",
    app_code_lesson_expression_string_hello: "string",
    app_code_lesson_expression_string_spaces: "string_spaces",
    app_code_lesson_expression_string_concat: "string_join",
    app_code_lesson_expression_less_than: "less",
    app_code_lesson_expression_greater_than: "greater",
    app_code_lesson_expression_less_than_equal: "less_equal",
    app_code_lesson_expression_greater_than_equal: "greater_equal",
    app_code_lesson_expression_equals: "equal",
    app_code_lesson_expression_not_equal: fn_name("not_equal"),
    app_code_lesson_expression_number_trichotomy: "number_three_ways",
    app_code_lesson_expression_string_equality: "string_equal",
    app_code_lesson_expression_string_order: "string_order",
    app_code_lesson_expression_string_trichotomy: "string_three_ways",
    app_code_lesson_expression_string_order_equal: "string_order_equal",
    app_code_lesson_expression_true_false: "true_false",
    app_code_lesson_expression_not: "not",
    app_code_lesson_expression_or: "or",
    app_code_lesson_expression_and: "and",
    app_code_lesson_expression_nested_add: "nested_add",
    app_code_lesson_expression_nested_subtract: "nested_subtract",
    app_code_lesson_expression_multiply: "times",
    app_code_lesson_expression_nested_multiply: "nested_multiply",
    app_code_lesson_expression_nested_divide: "nested_divide",
    app_code_lesson_expression_plus_minus: "plus_minus",
    app_code_lesson_expression_times_divide: "times_divide",
    app_code_lesson_expression_choose_order: "order",
    app_code_lesson_expression_choose_order_solve: "order_solve",
    app_code_lesson_expression_choose_order_operators: "order_minus_divide",
    app_code_lesson_expression_plus_times: "plus_times",
    app_code_lesson_expression_plus_divide: "plus_divide",
    app_code_lesson_expression_minus_times: "minus_times",
    app_code_lesson_expression_minus_divide: "minus_divide",
    app_code_lesson_expression_which_part_first: "which_first",
    app_code_lesson_expression_exponent: "power",
    app_code_lesson_expression_parentheses_arithmetic: "brackets_math",
    app_code_lesson_expression_parentheses_minus_divide:
      "brackets_minus_divide",
    app_code_lesson_expression_parentheses_moved: "brackets_moved",
    app_code_lesson_expression_arithmetic_less_than: "math_less",
    app_code_lesson_functions_arithmetic: "fn_math",
    app_code_lesson_functions_invalid: "fn_invalid",
    app_code_lesson_functions_console_log: "log",
    app_code_lesson_functions_console_log_statement: "log_line",
    app_code_lesson_functions_console_log_arithmetic: "log_math",
    app_code_lesson_functions_console_log_string: "log_string",
    app_code_lesson_expression_remainder_2: "rem_2",
    app_code_lesson_expression_remainder_3: "rem_3",
    app_code_lesson_expression_remainder_4: "rem_4",
    app_code_lesson_expression_remainder_subtract: "rem_subtract",
    app_code_lesson_expression_round_down: "round_down",
    app_code_lesson_expression_integer_division: "int_divide",
    app_code_lesson_expression_dividend: "dividend",
    app_code_lesson_expression_divisor: "divisor",
    app_code_lesson_expression_quotient: "quotient",
    app_code_lesson_expression_remainder: "remainder",
    app_code_lesson_expression_whole_part_formula: "whole_formula",
    app_code_lesson_expression_whole_part: "whole",
    app_code_lesson_expression_whole_part_both: "whole_one_step",
    app_code_lesson_expression_remainder_divide: "rem_divide",
    app_code_lesson_expression_remainder_divide_solve: "rem_formula",
    app_code_lesson_expression_remainder_any: "rem_any",
    app_code_lesson_expression_round_up: "round_up",
    app_code_lesson_expression_round_nearest: "round_near",
    app_code_lesson_expression_absolute_value: "absolute",
    app_code_lesson_expression_smaller: "smaller",
    app_code_lesson_expression_larger: "larger",
    app_code_lesson_expression_min_max_of_three: "min_max_three",
    app_code_lesson_expression_equal_true_false: "equal_true_false",
    app_code_lesson_expression_not_equal_true_false: "not_equal_true_false",
    app_code_lesson_expression_equal_number_string_true_false: "equal_kinds",
    app_code_lesson_expression_choose_order_compare: "order_compare",
    app_code_lesson_expression_comparing_a_comparison: "compare_compare",
    app_code_lesson_expression_parentheses_one_side: "brackets_one_side",
    app_code_lesson_expression_choose_order_three: "order_three",
    app_code_lesson_expression_either_first: "either_first",
    app_code_lesson_expression_choose_order_both_sides: "order_both_sides",
    app_code_lesson_expression_choose_order_both_sides_any_comparison:
      "order_both_any",
    app_code_lesson_expression_arithmetic_equality: "math_both_sides",
    app_code_lesson_expression_swapping_add: "swap_plus_times",
    app_code_lesson_expression_swapping_divide: "swap_divide_power",
    app_code_lesson_expression_swapping_order: "swap_order",
    app_code_lesson_expression_choose_order_pair: "order_pair",
    app_code_lesson_expression_parentheses_both_sides: "brackets_both_sides",
    app_code_lesson_expression_swapping_equal: "swap_equal",
    app_code_lesson_expression_choose_order_and: "order_and",
    app_code_lesson_expression_comparison_and: "and_compare",
    app_code_lesson_expression_in_between: "in_between",
    app_code_lesson_expression_choose_order_or: "order_or",
    app_code_lesson_expression_comparison_or: "or_compare",
    app_code_lesson_expression_choose_order_and_before_or:
      "order_and_before_or",
    app_code_lesson_expression_and_before_or: "and_or_line",
    app_code_lesson_expression_choose_order_brackets: "order_brackets",
    app_code_lesson_expression_brackets_or: "brackets_or",
    app_code_lesson_expression_choose_order_brackets_moved:
      "order_brackets_moved",
    app_code_lesson_expression_brackets_moved: "brackets_pair",
    app_code_lesson_expression_not_twice: "not_twice",
    app_code_lesson_expression_choose_order_not: "order_not",
    app_code_lesson_expression_not_comparison: "not_compare",
    app_code_lesson_expression_not_equal_same: "not_equal_same",
    app_code_lesson_expression_choose_order_not_pair: "order_not_pair",
    app_code_lesson_expression_not_pair: "not_and_or",
    app_code_lesson_statement_name_value: "name_value",
    app_code_lesson_statement_name_identifier: "name_any",
    app_code_lesson_statement_name_two: "name_two",
    app_code_lesson_statement_name_again: "name_again",
    app_code_lesson_statement_name_copy: "name_copy",
    app_code_lesson_statement_name_sum: "name_sum",
    app_code_lesson_statement_name_total: "name_total",
    app_code_lesson_statement_name_itself_sum: "name_add_self",
    app_code_lesson_statement_name_one_more: "name_one_more",
    app_code_lesson_statement_name_copy_kept: "name_copy_kept",
    app_code_lesson_statement_name_compare: "name_compare",
    app_code_lesson_comment_note: "comment",
    app_code_lesson_log_twice: "log_twice",
    app_code_lesson_comment_skip_line: "comment_skip",
  };
  return short;
}
