import { app_code_expression_node } from "./app_code_expression_node.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { list_get } from "./list_get.mjs";
import { list_shuffle_take } from "./list_shuffle_take.mjs";
import { range_from } from "./range_from.mjs";
import { js_operator_asterisk_symbol } from "./js_operator_asterisk_symbol.mjs";
import { js_operator_plus_symbol } from "./js_operator_plus_symbol.mjs";
export function app_code_lesson_expression_either_first_expression() {
  arguments_assert(arguments, 0);
  ("four numbers and three operators, a times on each side of a plus, built as a shape rather than typed as text so the quiz can work one operator out at a time: 2 * 3 + 4 * 5");
  ("A times on BOTH sides of the plus is what makes the choice free - both of them have a number standing on each side, so both may be worked out first, while the plus still holds a times on either side and may not. With a times on one side only there is a single operator ready and the order is forced, which is the lesson before this one.");
  ("There is no side to choose here, and so no argument to choose it with. The line is the same shape read from either end, which is the point of it: a learner cannot be right by taking the leftmost or by taking the rightmost, because both are right.");
  ("Numbers up to seven rather than up to nine, because two products are added here instead of one. Seven times six plus five times four is sixty-two, where nine times eight plus seven times six lands past a hundred and puts arithmetic in front of a learner whose only question is the order.");
  ("All four numbers differ. The lesson names each multiplication by what is written in it - Take 4 * 2 first - so a number standing in both of them, or twice in one, leaves the two times looking alike at a glance and the learner counting symbols to tell which row means which. Four numbers drawn without repeats is also stricter than only keeping the two sides unalike, which let 3 * 3 and 3 * 2 through.");
  let times = js_operator_asterisk_symbol();
  let plus = js_operator_plus_symbol();
  let smallest = 2;
  let largest = 7;
  let choices = range_from(smallest, largest);
  let count = 4;
  let numbers = list_shuffle_take(choices, count);
  let left_index = 0;
  let left_number = list_get(numbers, left_index);
  let left_other_index = 1;
  let left_other = list_get(numbers, left_other_index);
  let left = app_code_expression_node(left_number, times, left_other);
  let right_index = 2;
  let right_number = list_get(numbers, right_index);
  let right_other_index = 3;
  let right_other = list_get(numbers, right_other_index);
  let right = app_code_expression_node(right_number, times, right_other);
  let tree = app_code_expression_node(left, plus, right);
  return tree;
}
