import { arguments_assert } from "./arguments_assert.mjs";
import { g_tile_wall } from "./g_tile_wall.mjs";
import { bless_block_faces } from "./bless_block_faces.mjs";
import { property_get } from "./property_get.mjs";
import { app_g_bless_tiles_pave } from "./app_g_bless_tiles_pave.mjs";
import { bless_building_face } from "./bless_building_face.mjs";
import { each_index } from "./each_index.mjs";
export function app_g_bless_buildings_raise(rows, buildings, block) {
  arguments_assert(arguments, 3);
  ("Writes a whole row of buildings into the ground - each one roofed the same, walled in");
  ("its own material, and the doorways along the front of it left in that same material for");
  ("a door to be drawn on, one for every family inside.");
  ("The roof is a DIFFERENT material from the wall, and the same one on every building. Seen");
  ("from above a house is mostly roof with one row of wall showing, and painting the two");
  ("alike leaves a solid oblong of colour that reads as ground of an odd shade rather than");
  ("as something standing up - the doors then look like marks lying on the floor. Giving the");
  ("roof its own material puts an edge along the front of every house, and that edge is what");
  ("says the wall is a wall.");
  ("Common to every building because a roof is not how a player tells one house from");
  ("another. The wall is, and it can only do that job while everything around it holds");
  ("still. Vary both and the street is noise.");
  ("The roof goes down FIRST and the wall over it, which is the order somebody would build");
  ("in. Nothing here paints a door - the doors are drawn later, onto a layer of their own");
  ("above the ground, so no ordering inside this function can rub one out.");
  ("Which material a building wears comes from where it stands in the row, so neighbours");
  ("never match and the same street is built every time. WHICH SET it is drawn from comes");
  ("from the block, which is what makes one street a different place from the next rather");
  ("than a second copy of it.");
  ("The block's materials are asked for ONCE and handed to every building in it, rather");
  ("than each house asking on its own behalf. Asked per house, a street could not be told");
  ("apart from a street that happened to agree with it - the set would be an accident of");
  ("five separate answers instead of a fact about the road.");
  ("A doorway is paved in the building's OWN face material, the same as the wall either side");
  ("of it. It used to be a square of WOOD, so that the way in differed from the wall in");
  ("material; the door is drawn over the front row now, and a wooden square under a drawn");
  ("door is only a patch showing around the edges of it.");
  ("So the front of a building is ONE material all the way along and the doors on it are");
  ("drawn. Which squares are doorways is still known - it is what the drawing is placed on -");
  ("and it stays a fact about the building rather than something read back off the picture.");
  ("A low building does not fill its slot, and the row it leaves over is PAVED here in the");
  ("block's own pavement. It has to be covered by somebody: it was under a building before,");
  ("so whatever the world generated there was buried, and left alone now it comes out as");
  ("whatever the ground happened to be - which on a fresh world is as readily a lake behind");
  ("the houses as grass. Paved, it reads as the yard or the forecourt of the house beside");
  ("it, and it joins the alleys either side of it, which are paved in the same thing.");
  ("It is done HERE, where the building is, rather than with the rest of the block's ground.");
  ("Which row a house leaves over depends on how tall it is and how far back it stands, and");
  ("both of those are facts about the building - worked out again anywhere else, they would");
  ("be a second copy free to disagree with the first, and disagreeing quietly, since a yard");
  ("nobody paved looks like scenery until somebody walks into the water.");
  let item_roof = g_tile_wall();
  let item_ground = bless_block_pavement(block);
  let faces = bless_block_faces(block);
  function building_raise(building, index) {
    let yard = property_get(building, "yard");
    app_g_bless_tiles_pave(rows, yard, item_ground);
    let roof = property_get(building, "roof");
    app_g_bless_tiles_pave(rows, roof, item_roof);
    let walls = property_get(building, "walls");
    let item_wall = bless_building_face(faces, index);
    app_g_bless_tiles_pave(rows, walls, item_wall);
    let doorways = property_get(building, "doorways");
    app_g_bless_tiles_pave(rows, doorways, item_wall);
  }
  each_index(buildings, building_raise);
}
