import { arguments_assert } from "./arguments_assert.mjs";
export function app_code_note_name_colors_light() {
  arguments_assert(arguments, 0);
  ("the same three name colours as the code chips use, remade to be read on a pale background - the blue cards the cups are drawn on");
  ("THE HUE IS WHAT CARRIES ACROSS A CHANGE OF BACKGROUND, NOT THE COLOUR ITSELF. A name written on a cup and the same name inside a black code chip have to be seen as one name, and what a reader recognises between them is that both are blue. The exact colour cannot come with it: a mint green chosen to sit bright against black is all but invisible on a pale blue card, so a list shared between the two surfaces would have made one of the three unreadable on one of them.");
  ("So this is the same three hues in the same order, each given the lightness its own background needs. A red, a green and a blue, one of each and no second member of any - which is what makes the hue enough to carry a name between the two surfaces, because a reader matching a cup to a chip is only ever asking which of three plain colours this is.");
  ("THE BLUE IS KEPT WELL CLEAR OF THE BLUE THE CUP ITSELF IS DRAWN IN, and it was not at first. A deep navy was chosen here for contrast alone, and it landed a few steps from the blue of the glass, the stem and the foot - so the letter on the third cup read as part of the cup rather than as the name's colour, which is the one thing it was there to say. A reader caught it straight away. The lightness a letter needs is not a free choice on a card that already has a colour of its own: a name colour has to differ from its background AND from whatever is drawn beside it.");
  ("So the blue is the lightest of the three here, and it is about three to one against the card. That is under what small writing wants, and it is taken knowingly: this letter is bold, larger than the writing around it, and standing alone inside a drawing, and a blue dark enough to pass the usual bar was the blue that disappeared into the cup.");
  ("THE THREE ARE NOT SPREAD AS FAR APART HERE AS THEY ARE ON THE CHIPS, AND DO NOT NEED TO BE. On a chip the brightness is what pairs a name in a note with the same name in the code, and it has the whole range from black to white to do it in. On a cup the letter IS the name - a reader who can tell no two of these apart still reads a, b and c - so the colour here is only ever joining a cup to a chip, and what does that joining is the hue. A card this pale leaves about thirty steps of lightness that stay readable, and three colours were fitted into them rather than three being forced apart until one went unreadable.");
  ("The green was a deep forest before and a reader said it was not light enough. It sits about six steps under the blue now, which is thin and is the right trade: the two are far apart in hue, and behind the hue stands the letter itself.");
  ("The red took the slot an orange held, and took it at the same lightness the orange had - a little under five to one against the card, the strongest contrast of the three. Nothing had to be traded to say red here: the difficulty that pushed the first chip colour off red was the brightness it needed against black, and on a pale card a red is asked to be dark rather than light, which is the direction a red is already going.");
  ("The three sit about six and about six of lightness apart, all of them darker than the card they are written on. The order is not the same as the other list's, and does not have to be: each surface ranks its own three by what its own background allows, and nothing reads across from one list to the other except the hue.");
  let red = "#c62828";
  let green = "#0f8a4b";
  let blue = "#3b82f6";
  let colors = [red, green, blue];
  return colors;
}
