import { g_genders_without_img } from "./g_genders_without_img.mjs";
import { random } from "./random.mjs";
import { bless_pace_ms } from "./bless_pace_ms.mjs";
import { g_directions } from "./g_directions.mjs";
import { list_get_property } from "./list_get_property.mjs";
import { bless_places_ensure } from "./bless_places_ensure.mjs";
import { g_npcs_ids_ensure } from "./g_npcs_ids_ensure.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { each_index } from "./each_index.mjs";
import { list_random_item } from "./list_random_item.mjs";
import { list_remove_end } from "./list_remove_end.mjs";
import { list_size } from "./list_size.mjs";
import { mod } from "./mod.mjs";
import { property_set } from "./property_set.mjs";
import { app_g_bless_people_count } from "./app_g_bless_people_count.mjs";
export function app_g_bless_people(player_img, coordinates_land) {
  arguments_assert(arguments, 2);
  ("The people standing about the world - a tile to stand on, a picture, a way they are");
  ("facing, a speed of their own and a way they are trying to go, and nothing else at all.");
  ("The gospel game's own people carry a name, a gender, a conversation and a record of");
  ("what has been said to them, because that game is a conversation. Nobody is spoken to");
  ("here. A person you pray for needs only to be somewhere and be seen, so giving them a");
  ("scripted conversation would be generating content the game can never reach.");
  ("Their pictures come from the same list the walking art is drawn from, so a person here");
  ("looks exactly like a person there - and the player's own picture is taken out of it, so");
  ("nobody in the crowd is the player's twin.");
  ("A speed and a heading are given out here, one draw each, because they are what a person");
  ("IS rather than what they are doing - two people side by side walking at different rates");
  ("in different directions is the whole of what makes this a street. Drawn later, at the");
  ("moment of a step, everybody would walk at the same average speed and wander rather than");
  ("go anywhere.");
  ("Heading is where somebody is trying to go and is not the same thing as the way they are");
  ("facing, which is wherever they last stepped. Everybody is set down facing south so the");
  ("crowd is looking at the player when the game opens; where each of them is going is their");
  ("own business from the first step.");
  let genders = g_genders_without_img(player_img);
  let gender_count = list_size(genders);
  let count = app_g_bless_people_count();
  let people = list_remove_end(coordinates_land, count);
  function person_initialize(person, index) {
    let r = mod(index, gender_count);
    let imgs = list_get_property(genders, r, "imgs");
    let img = list_random_item(imgs);
    property_set(person, "img", img);
    property_set(person, "direction", "south");
    let fraction = random();
    let pace = bless_pace_ms(fraction);
    property_set(person, "pace", pace);
    let directions = g_directions();
    let heading = list_random_item(directions);
    property_set(person, "heading", heading);
  }
  each_index(people, person_initialize);
  ("Everybody is given the gospel game's own id before they are handed over, because that is");
  ("what a person's picture is filed under, and a person whose picture cannot be found again");
  ("is a person the crowd can never take a step for. The tile they were set down on is what");
  ("becomes the id, which is why this is asked here and not later: once they start walking,");
  ("where they are standing is no longer where they began.");
  g_npcs_ids_ensure(people);
  ("They are also given somewhere to belong, and for the same reason it is done HERE: an");
  ("address is worked out from a person's place in this line, so it has to be asked while");
  ("this is still the line the world was made from. It is what every rung above the lowest");
  ("is prayed over.");
  bless_places_ensure(people);
  return people;
}
