import { app_g_hero_fx_settled } from "./app_g_hero_fx_settled.mjs";
import { app_g_hero_face_off } from "./app_g_hero_face_off.mjs";
import { app_g_hero_taller } from "./app_g_hero_taller.mjs";
import { app_g_hero_clash } from "./app_g_hero_clash.mjs";
import { list_random_item } from "./list_random_item.mjs";
import { bless_person_replace } from "./bless_person_replace.mjs";
import { property_path_get_2 } from "./property_path_get_2.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { property_get } from "./property_get.mjs";
import { property_set } from "./property_set.mjs";
import { app_shared_game_npc_img_get } from "./app_shared_game_npc_img_get.mjs";
import { app_g_hero_burn_charge } from "./app_g_hero_burn_charge.mjs";
import { app_g_hero_fx_point } from "./app_g_hero_fx_point.mjs";
import { app_g_hero_impact } from "./app_g_hero_impact.mjs";
import { app_g_hero_engulf } from "./app_g_hero_engulf.mjs";
import { app_g_hero_ash } from "./app_g_hero_ash.mjs";
import { list_remove_if_exists } from "./list_remove_if_exists.mjs";
import { app_g_hero_evil_spawn } from "./app_g_hero_evil_spawn.mjs";
import { app_g_hero_evil_spawn_wait_ms } from "./app_g_hero_evil_spawn_wait_ms.mjs";
export async function app_g_hero_burn(hero) {
  arguments_assert(arguments, 1);
  ("The player stops the evil person with fire, in five acts: she gathers the fire, throws it, it strikes, it engulfs them, and they are burned to ash.");
  ("They stop hunting the moment the fire is called, not when it lands, so the one the fireball was aimed at is still standing there when it arrives.");
  ("Once it is over nobody is evil, and a little while later somebody else in the crowd turns. Somebody new walks into the street in the place of the one burned, so the crowd never thins.");
  let evil = property_get(hero, "evil");
  let fx = property_get(hero, "fx");
  let player_img_c = property_get(hero, "player_img_c");
  let npcs = property_path_get_2(hero, "world", "npcs");
  let render = property_get(hero, "render");
  app_g_hero_face_off(hero, evil);
  property_set(evil, "burning", true);
  let evil_img = app_shared_game_npc_img_get(evil);
  await app_g_hero_burn_charge(hero);
  let from = app_g_hero_fx_point(fx, player_img_c);
  let to = app_g_hero_fx_point(fx, evil_img);
  await app_g_hero_clash(hero, evil_img, from, to);
  ("Where the fire LANDS is asked again, and not taken from where it was aimed. The throw and");
  ("the struggle in the middle of the street last seconds, and a point asked before them");
  ("answers about where the killer was rather than where they are - so the burning, the smoke");
  ("and the ash were drawn over the square they set off from while the killer stood somewhere");
  ("else entirely. Asking again costs one reading and cannot be wrong, whatever moved.");
  let struck = app_g_hero_fx_point(fx, evil_img);
  app_g_hero_impact(hero, struck);
  await app_g_hero_engulf(hero, struck, evil_img);
  await app_g_hero_ash(hero, struck, evil);
  ("The camera waits for the smoke to clear before it comes in. The fire is drawn on a sheet");
  ("over the SCREEN rather than in the street, so it cannot follow a street that moves under");
  ("it: a camera setting off while the last puffs were still rising left them hanging in the");
  ("air, at the size they were drawn at, over ground that had zoomed away beneath them. It is");
  ("also the moment this was always meant to be - the fire out, nothing chasing her, and");
  ("nothing else on the screen to look at.");
  await app_g_hero_fx_settled(fx);
  await app_g_hero_taller(hero);
  list_remove_if_exists(npcs, evil);
  let world = property_get(hero, "world");
  let div_map = property_get(hero, "div_map");
  let graves = property_get(hero, "graves");
  let neighbour = list_random_item(npcs);
  bless_person_replace(world, div_map, neighbour, graves);
  property_set(hero, "evil", null);
  render();
  function spawned() {
    app_g_hero_evil_spawn(hero);
  }
  let wait = app_g_hero_evil_spawn_wait_ms();
  setTimeout(spawned, wait);
}
