import { arguments_assert } from "./arguments_assert.mjs";
import { app_shared_color_code_background } from "./app_shared_color_code_background.mjs";
import { html_font_color_set } from "./html_font_color_set.mjs";
import { app_code_note_name_halo_width } from "./app_code_note_name_halo_width.mjs";
import { html_text_halo_set } from "./html_text_halo_set.mjs";
export function app_code_note_name_tag(component, color) {
  arguments_assert(arguments, 2);
  ("writes a name as its own colour, ringed in the very black that the same name is read against inside a run of code, which is how a name wears its colour on a pale card");
  ("★ THE NAME ITSELF IS THE COLOURED THING HERE, WHICH IS THE WHOLE DIFFERENCE FROM THE PATCH. On a black code chip a name is written in its colour and read against the black, and the same name on a pale card could not be: a colour bright enough to read as ink on black is invisible on a card this light - the green measured about 1.2 to 1 against it, where 4.5 is the floor. So the card was given the colour behind the name instead, and the name went dark. That worked and cost something, because the two grounds then said the name different ways round, and a reader comparing the cup with the program was comparing a green block against a green letter.");
  ("★ THE RING IS NOT A COLOUR THIS FUNCTION PICKS, IT IS THE CODE CHIP'S OWN BACKGROUND ASKED FOR BY NAME. So the cup and the program now show the same two colours in the same two roles - a coloured letter read against black - and the only difference left between them is what the black is cut to: a box on the chip, the letter's own outline on the cup. There is no second colour anywhere in this, which is the condition the whole thing had to meet. A separate palette for pale grounds is exactly what was tried early on and what a reader caught, saying the green on the cup was not the green in the code; they were right, because somebody had picked it separately. Here nobody picks it, and if the chip's black is ever changed the ring changes with it rather than drifting away from it.");
  ("★ THE BLACK IS A RING ROUND THE LETTER AND NOT A BOX BEHIND IT. Both put the same colour immediately against the letter and both measure well, because what a reader is helped by is the colour touching the letter and not the shape the rest of it is cut to. What the box cost was the picture: a filled rectangle standing inside a drawn cup reads as something that was put in the cup, and it was narrowed twice trying to stop it reading that way before it was clear that no width would - the shape was wrong and not the size.");
  ("The reading rejected last, and the one this replaced: ring the letter in the name's own colour scaled down dark, so that the cup carries a single hue and nothing else. That is legible - the worst pair measured 4.9 to 1 for the letter against its ring and 9.4 to 1 for the ring against the card - and black beats it on both, at 7.1 and 18.3. It was preferred for a while because it looked like the stricter reading of one colour, and that was the mistake: black was never a second colour competing with the name, it was already the colour the name is read against in every run of code on the page. Scaling the hue down made the cup its own arrangement again, which is the very thing being argued against everywhere else here.");
  ("The reading rejected before that: a box outline round the letter with the card showing through, and the letter left bright. That is the drawing that has no colour next to the letter at all, and the measurement is the same one that started all of this - bright green on this card is 1.2 to 1 against a floor of 4.5. An outline a little way off the letter cannot help the letter; only what touches it can.");
  ("The reading rejected next to that: the same box outline with the letter written dark enough to read on the card. That one is legible and it breaks the single colour, because the cup would then show a dark green letter where the program shows a bright green one - which is precisely the drift a reader already caught once.");
  ("The reading rejected before all of them: putting the colour behind the letter as a bright patch and writing the letter dark, which is what the code chip still does. Legible, one colour, and it costs the correspondence - the cup shows a green block where the program shows a green letter.");
  let ground = app_shared_color_code_background();
  html_font_color_set(component, color);
  let width = app_code_note_name_halo_width();
  html_text_halo_set(component, width, ground);
  return component;
}
