export function app_replace_abbreviations() {
  "Every short word the replacing app teaches, against the words it stands for - one entry each, for the whole app rather than for one exercise.";
  "The exercises are met in order and each leans on the last, so a short word learned in one is carried into the next. Held here, a short word cannot mean one thing in one exercise and another in the next, because there is only one place to say what it means - which is a stronger thing than checking afterwards that the places agree.";
  "The parts are the words with the bolding written into them: a part at an odd position is drawn bold, and the bold parts read in order spell the short word itself. That is the whole of how one is remembered, so an entry whose bold letters spell something else is teaching a word that is not there.";
  "In the order a learner meets them rather than in the order they sort, because that is the order the words were chosen in and it is the only reading that shows a later one being built out of an earlier one. What is shown beside a set of rules is sorted when it is drawn.";
  let r = {
    bo: ["", "bo", "olean literal"],
    di: ["", "di", "git"],
    ig: ["", "i", "nteger ", "g", "rower"],
    in: ["", "in", "teger (non-negative whole number)"],
    pi: ["", "p", "ositive ", "i", "nteger digit (numbers 1-9)"],
    de: ["", "de", "cimal number"],
    eE: [
      "lowercase ",
      "e",
      " or uppercase ",
      "E",
      ", the letter that marks an exponent",
    ],
    ep: ["", "e", "x", "p", "onent"],
    se: ["", "s", "cientific notation number ", "e", "nding"],
    sn: ["", "s", "cientific ", "n", "otation number"],
    idg: ["", "id", "entifier ", "g", "rower"],
    idf: [
      "",
      "id",
      "entifier ",
      "f",
      "irst: symbol that can be used as the first symbol of an identifier",
    ],
    ida: [
      "",
      "id",
      "entifier ",
      "a",
      "ny: symbol that can be used as any symbol of an identifier",
    ],
    id: ["", "id", "entifier"],
    st: ["", "st", "ring"],
    stg: ["", "st", "ring ", "g", "rower"],
    ex: ["", "ex", "pression"],
    pe: ["", "p", "rimary ", "e", "xpression"],
    li: ["", "li", "teral"],
    nu: ["", "nu", "mber"],
    mae: ["", "m", "ember ", "a", "ccess ", "e", "xpression"],
    mle: ["", "m", "ember access ", "l", "eft-hand ", "e", "xpression"],
    ce: ["", "c", "all ", "e", "xpression"],
    ag: ["", "a", "rguments ", "g", "rower"],
    ue: ["", "u", "nary ", "e", "xpression"],
    uo: ["", "u", "nary ", "o", "perator"],
    mue: ["", "mu", "ltiplicative ", "e", "xpression"],
    mo: ["", "m", "ultiplicative ", "o", "perator"],
    ade: ["", "ad", "ditive ", "e", "xpression"],
    ao: ["", "a", "dditive ", "o", "perator"],
    re: ["", "r", "elational ", "e", "xpression"],
    ro: ["", "r", "elational ", "o", "perator"],
    ee: ["", "e", "quality ", "e", "xpression"],
    le: ["", "l", "ogical ", "e", "xpression"],
    lo: ["", "l", "ogical ", "o", "perator"],
    ase: ["", "as", "signment ", "e", "xpression"],
    lh: ["", "l", "eft-", "h", "and expression"],
    sm: ["", "s", "tate", "m", "ent"],
    vs: ["", "v", "ariable ", "s", "tatement"],
    vk: ["", "v", "ariable ", "k", "eyword"],
    vdg: ["", "v", "ariable ", "d", "eclaration ", "g", "rower"],
    vd: ["", "v", "ariable ", "d", "eclaration"],
    smg: ["", "s", "tate", "m", "ent ", "g", "rower"],
    bs: ["", "b", "lock ", "s", "tatement"],
    is: ["", "i", "f ", "s", "tatement"],
    ws: ["", "w", "hile ", "s", "tatement"],
    fs: ["", "f", "or ", "s", "tatement"],
    fd: ["", "f", "unction ", "d", "eclaration"],
    fdm: ["", "f", "unction ", "d", "eclaration ", "m", "iddle"],
    fpg: ["", "f", "unction ", "p", "arameter ", "g", "rower"],
  };
  return r;
}
