import { arguments_assert } from "./arguments_assert.mjs";
import { fn_name } from "./fn_name.mjs";
import { app_code_lesson_chip_colors } from "./app_code_lesson_chip_colors.mjs";
import { app_code_highlight_colors } from "./app_code_highlight_colors.mjs";
import { app_code_note_name_colors } from "./app_code_note_name_colors.mjs";
export function app_code_color_tones() {
  arguments_assert(arguments, 0);
  ("the colours of this app's three palettes, sorted into the two tones they have - the dark ones, which carry white lettering, and the light ones, which carry near-black lettering");
  ("THIS IS NOT EVERY COLOUR THE APP DRAWS, AND IT SAID THAT IT WAS UNTIL 2026-09-20. It reads three palette functions and holds ten colours. Nine other files of this app spell eleven more, and every claim below was written without them. They are listed in the paragraph beginning WHAT THE ELEVEN ARE, with a reading for each, so that nobody else reasons from ten again by accident.");
  ("THE PALETTES ARE THREE BUT THEIR TONES ARE TWO, AND THAT IS THE WHOLE OF WHAT THIS EXISTS TO SAY. Measured 2026-09-20: the four chip colours stand at 0.500, 0.500, 0.509 and 0.580 of perceptual lightness, and the three pointing colours at 0.546, 0.549 and 0.551 - one band, 0.500 to 0.580, seven colours in it. The three name colours stand at 0.725, 0.780 and 0.880, which is the other band and no colour of these three palettes is in between. So the three palettes are not three sets of colours at three tones. They are two tones, and the dark one is written down twice.");
  ("THE TWO BANDS ARE A FACT ABOUT THESE TEN AND NOT ABOUT THE APP. Of the eleven colours the three palettes do not reach, two stand in the space between the bands - the quiz-wrong red at 0.605 and the placeholder grey at 0.703 - two stand below the dark band at 0.160 and 0.337, and three stand above the light band at 1.000. So seven of the twenty-one stand in neither band, and two of those seven stand in the gap the paragraph below calls empty. The tidiness of the reading above is partly a consequence of which colours were being read.");
  ("EVERY WAY A COLOUR IS DRAWN ASKS FOR ONE TONE OR THE OTHER, WHICH IS WHY TWO IS ENOUGH. A colour behind white lettering must be dark, or the white does not show on it. A colour behind near-black lettering must be light, for the same reason the other way round. A coloured word read on the black code line must be light. A coloured word read on the pale card must be dark. Those are four jobs and they ask two questions, and a colour that answers one of them answers the other in its pair - which is what makes a tone a real thing rather than a way of speaking.");
  ("A FIFTH JOB ASKS NEITHER, AND IT IS THE ONE THAT HURTS. A colour can also be a shape with no lettering on it at all - the black fill of a code chip told apart from the pale card around it, or a chip lifted off a black tile by a ring. A shape only has to be seen, so its rule asks three where lettering asks four and a half. But it asks to be far from what is behind it, and on the black code line that means far in the light direction - so it pulls a dark colour back up while its other two jobs pull it down. That squeeze is not a fault in any one colour; it is what a single tone serving two grounds costs.");
  "THE SPLIT IS BY TONE AND NOT BY GROUND, AND THE OTHER READING IS WRITTEN DOWN NEXT DOOR, SO THIS SAYS WHY IT LOST. " +
    fn_name("app_code_lesson_chip_colors") +
    " reasons that what separates a palette is the ground a colour is drawn on, pale card against black line. The chip colours and the pointing colours refute that between them: they share a ground, they share a tone, and they are still two lists. Ground is not what divides them - nothing does. Tone divides the name colours from both of the others, and across these three palettes it divides them cleanly, with a gap of 0.145 of lightness between the bands and none of the ten standing in it. Read over the whole app that last clause is false - the quiz-wrong red and the placeholder grey both stand in that gap - so what the gap shows is that the three palettes were each drawn for one tone, not that the app has a boundary nothing crosses.";
  ("WHAT STANDS BETWEEN THESE TEN AND FOUR HUES AT TWO TONES EACH IS FOUR THINGS, AND ONLY ONE OF THEM IS A REASON. Eight colours would be a red, a green, a blue and an amber, each with a dark and a light. There are ten, because three darks are spare and one light is missing. Count the other eleven in and the shortfall is much larger than four: the red hue carries five colours, the blue carries eight, and neither is anywhere near one dark and one light. The four below are still the four faults among these ten; they are no longer the whole list.");
  "The first spare dark is the pointing green against the chip green - hue 150.0 against 149.9, lightness 0.551 against 0.509. Those are one colour written twice, and the near-miss check already reports the pair as a fault, so nothing new is being claimed here. The second is the pointing red at hue 15 against the chip red at 25, moved on purpose so the three pointing colours stay clear of one another - a real choice, but one made for a set of three rather than for the palette. The third is the pointing blue, which is not an app colour at all: it is the blue the whole site leads with, reached through " +
    fn_name("app_shared_color_brand_blue") +
    ", and its chroma of 0.215 and hue of 262.9 were never a decision taken here. That one is the only genuine reason of the three, because it is not this app's to change.";
  ("The missing light is the amber. The red, the green and the blue each have both tones; the amber has a dark and nothing else. So a fourth name colour cannot be an amber today without one being invented, and the amber is also the colour every known contrast fault in the chip palette belongs to. Those two facts are probably one fact.");
  ("THE NUMBERS THE TWO TONES ACTUALLY REACH, measured the same day, so whoever revises them starts from readings rather than from this argument. Each light colour on the near-black ink it carries: 7.20 to one for the red, 9.48 for the blue, 13.91 for the green. Each dark colour under white lettering: 6.65 for the chip red, 6.07 for the chip blue, 5.40 for the chip green, 5.41 for the pointing red, 5.17 for the brand blue, and then 4.51 for the pointing green and 4.48 for the chip amber - the last of those being under the four and a half that lettering asks for, which is one of the amber's known faults.");
  "THE CHECK THIS WAS WRITTEN FOR NOW EXISTS AND ASKS IT. " +
    fn_name("app_code_color_hue_groups") +
    " stands the colours in order round the wheel and cuts them into hues, " +
    fn_name("app_code_color_tone_faults") +
    " asks each hue for exactly one dark and one light, and " +
    fn_name("app_code_color_tone_gate_run") +
    " holds the answer still against what is already known. The four faults it reports are the four written out in the paragraph above. That was once described here as independent confirmation. It is not, and the correction is worth more than the claim was: the gate reads the palettes through this function, so it is handed the same ten colours this argument was made from and cannot reach a different subject. It can catch a colour changed inside one of the three palettes, which is a real job. It cannot catch a colour the app draws from somewhere else, and that is exactly what was wrong here.";
  ("IT IS WORKED OUT FROM THE THREE PALETTE FUNCTIONS RATHER THAN WRITTEN OUT HERE, so a colour added to any of them arrives in the right band the day it is added, and this cannot drift from those three. It drifts freely from everything else, because a colour spelled in a file that is not a palette is not reached from here at all. That is the whole of the gap: the mechanism that keeps this honest about the three is the same mechanism that made it silent about the other nine.");
  ("WHAT THE ELEVEN ARE, measured 2026-09-20 as lightness, hue and chroma, so the next reader starts from readings rather than from this. A light blue at 0.864, 251.9, 0.069 and a near-black tile at 0.160, 271.1, 0.035, both for lifting a chip off the code line. A running-count grey at 0.337 with no chroma at all. A quiz-wrong red at 0.605, 28.5, 0.240 and its darker twin for a code line at 0.534, 21.2, 0.105. A placeholder grey at 0.703, 248.0, 0.011. A string-value blue at 0.739, 249.2, 0.141 and its twin for a pale ground at 0.499, 262.8, 0.203. And three translucent whites, at 1.000 with no chroma, which are the same white drawn at three strengths.");
  ("STOOD ROUND THE WHEEL WITH THE OTHER TEN AT THE TWELVE DEGREE GAP THE GROUPING USES, the twenty-one fall into five runs and not four: a red of five colours from 15.1 to 28.5, the amber alone at 56.6, a run of four at a nominal 89.9 which is the grey and the three whites and is not a hue at all, a green of three from 149.9 to 154.0, and a blue of eight from 248.0 to 271.1. The blue run is eight because the gap rule has nothing to cut on - the nearest neighbours in it are 0.1 apart and the widest step is 7.7.");
  ("TWO QUESTIONS ARE LEFT OPEN HERE ON PURPOSE, BECAUSE THEY ARE CHOICES AND NOT READINGS. Whether a colour with no chroma belongs in a census of hues, given that four of the eleven have none and a fifth has 0.011 - their hue is what the arithmetic returns when there is almost nothing to take a direction from, not a decision anybody made. And whether a fill that never carries lettering answers a tone question at all, which the paragraph on the fifth job above already doubts. Both answers change which of the twenty-one should be read here, so neither was taken while only correcting what was false.");
  let chip = app_code_lesson_chip_colors();
  let pointing = app_code_highlight_colors();
  let dark = chip.concat(pointing);
  let light = app_code_note_name_colors();
  let tones = {
    dark,
    light,
  };
  return tones;
}
