import { app_g_bless_person_step_boxed } from "./app_g_bless_person_step_boxed.mjs";
import { app_g_bless_person_slide } from "./app_g_bless_person_slide.mjs";
import { divide } from "./divide.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { equal } from "./equal.mjs";
import { property_get } from "./property_get.mjs";
import { property_set } from "./property_set.mjs";
import { app_shared_game_npc_move } from "./app_shared_game_npc_move.mjs";
import { g_direction_opposite } from "./g_direction_opposite.mjs";
export function app_g_bless_person_step(world, person) {
  arguments_assert(arguments, 2);
  ("One person takes one step - onward if they can, round whoever is in the way if they");
  ("cannot, back the way they came if there is nowhere else, and nowhere at all when they");
  ("are boxed in.");
  ("They keep a HEADING, which is where they are trying to go, and it is not the same");
  ("thing as the way they are facing. Facing is where their picture is looking, which is");
  ("wherever they last stepped; heading survives a step round somebody and is what makes");
  ("them carry on the same way afterwards. A crowd of people who each pick a fresh");
  ("direction every step has no forward and no backward in it, and a pavement with no");
  ("forward and backward on it is not a pavement.");
  ("Stepping round is therefore NOT a change of mind, and the heading is left alone for");
  ("it. Turning back IS one, so that one is written down - otherwise somebody who reached");
  ("a shore would turn round, immediately try their old heading again, and stand there");
  ("bouncing off the water for the rest of the game.");
  ("Where a person may step is the gospel game's own answer, asked again for each person");
  ("rather than once for the crowd. That question reads where everybody is standing right");
  ("now, so asking it once and reusing the answer would let two people who were both");
  ("offered the same empty tile both take it, and they would end the step standing inside");
  ("each other.");
  ("The player's tile is taken out by hand, because the crowd is what that question knows");
  ("about and the player is not one of them. Left in, somebody would eventually walk onto");
  ("the square the player is standing on and the player would be inside the crowd instead");
  ("of among it.");
  ("Nobody walks out of their own life. A tile too far from home is refused before the");
  ("directions are even looked at, which is what keeps the people who live at a door near");
  ("that door and the people out walking on the pavement. Without it every address in the");
  ("game would be true for about a minute and then be a lie, because the handful of people");
  ("the prayer calls one building would each have wandered off their own way.");
  ("Somebody standing outside their own reach is let go anywhere instead, because that");
  ("person can only have got there by being set down there when their doorstep was full -");
  ("and held to a rule they already break, they would never take a step again. Loose, they");
  ("wander until they meet the street they belong to, and are kept from then on.");
  let r = app_g_bless_person_step_boxed(world, person);
  let boxed = property_get(r, "boxed");
  let way = property_get(r, "way");
  let tiles = property_get(r, "tiles");
  let heading = property_get(r, "heading");
  if (boxed) {
    return;
  }
  let back = g_direction_opposite(heading);
  let turned = equal(way, back);
  if (turned) {
    property_set(person, "heading", back);
  }
  let to = property_get(tiles, way);
  app_shared_game_npc_move(person, to, 0);
  ("The step is then made to LAST as long as the wait before their next one, so the");
  ("picture is still crossing the tile when the following step is asked for and the person");
  ("is walking rather than appearing a tile further on.");
  ("It is set here, after the move, because the move writes the map's own quick length");
  ("over whatever was there - so this is not a setting a person keeps, it is part of");
  ("taking a step and has to be said again every time one is taken.");
  ("No delay is wanted with it. A delay staggers a line of people who were all sent at the");
  ("same instant, and nobody here is: everybody on this street already keeps their own");
  ("clock, so there is nothing to spread out.");
  let pace = property_get(person, "pace");
  let seconds = divide(pace, 1000);
  app_g_bless_person_slide(person, seconds);
}
