import { arguments_assert } from "./arguments_assert.mjs";
import { app_code_lesson_statement_name_value_name } from "./app_code_lesson_statement_name_value_name.mjs";
import { app_code_lesson_statement_name_value_word } from "./app_code_lesson_statement_name_value_word.mjs";
import { app_code_string_code } from "./app_code_string_code.mjs";
import { js_code_console_log_statement } from "./js_code_console_log_statement.mjs";
import { app_code_container_light_blue } from "./app_code_container_light_blue.mjs";
import { html_div_cycle_code } from "./html_div_cycle_code.mjs";
import { js_code_let_statement } from "./js_code_let_statement.mjs";
import { app_code_code_lines_writes_out } from "./app_code_code_lines_writes_out.mjs";
import { app_code_lesson_link } from "./app_code_lesson_link.mjs";
import { app_code_lesson_statement_name_value } from "./app_code_lesson_statement_name_value.mjs";
import { js_keyword_true } from "./js_keyword_true.mjs";
import { js_keyword_false } from "./js_keyword_false.mjs";
export function app_code_lesson_statement_name_true_false_above(root, context) {
  arguments_assert(arguments, 2);
  ("the boxes read before the first question: a name holding a word, the program the lesson on giving a value a name was about, then one line saying a name can hold true or false too");
  ("The word comes first because the learner has already seen it, and the new value is met against it.");
  ("The second box is the sentence alone, with no program of its own, at the human's request. The examples right below it are the programs it talks about, both of them, so a program here would show one of them twice.");
  let name = app_code_lesson_statement_name_value_name();
  let word = app_code_lesson_statement_name_value_word();
  let quoted = app_code_string_code(word);
  let logged = js_code_console_log_statement(name);
  let box_word = app_code_container_light_blue(root);
  html_div_cycle_code(box_word, ["A variable can hold a word:"]);
  let held_word = js_code_let_statement(name, quoted);
  app_code_code_lines_writes_out(box_word, [held_word, logged], word);
  ("the box shows a program an earlier lesson taught, so it links to that lesson, for a learner who wants to see it again");
  html_div_cycle_code(box_word, ["From this lesson:"]);
  app_code_lesson_link(box_word, context, app_code_lesson_statement_name_value);
  let t = js_keyword_true();
  let f = js_keyword_false();
  let box_true = app_code_container_light_blue(root);
  html_div_cycle_code(box_true, ["A variable can also hold ", t, " or ", f]);
}
