import { fn_name } from "./fn_name.mjs";
export function app_replace_rule_sets_fns_rules_used_rows() {
  ("Which of an exercise's rules each of its goals actually leant on, by exercise name, three words to a rule: what it matches, what it puts there instead, and the line the author wrote it on. Read back into whole records by ",
    fn_name("app_replace_rule_sets_fns_rules_used_from_rows"),
    " - an edit made here is thrown away the next time ",
    fn_name("app_replace_rule_sets_fns_rules_used_generate"),
    " runs.");
  let v = {
    "Binary Numbers Simple": [
      [
        ["0", "1", "0 > 1"],
        ["0", "0 0", "0 > 0 0"],
      ],
      [
        ["0", "1", "0 > 1"],
        ["0", "0 0", "0 > 0 0"],
      ],
      [
        ["0", "0 0", "0 > 0 0"],
        ["0", "1", "0 > 1"],
      ],
      [
        ["0", "1", "0 > 1"],
        ["0", "0 0", "0 > 0 0"],
      ],
      [
        ["0", "0 0", "0 > 0 0"],
        ["0", "1", "0 > 1"],
      ],
      [
        ["0", "0 0", "0 > 0 0"],
        ["0", "1", "0 > 1"],
      ],
    ],
    "Binary Numbers Simple 2": [
      [
        ["b", "0", "b > 0"],
        ["b", "b b", "b > b b"],
        ["b", "1", "b > 1"],
      ],
      [
        ["b", "1", "b > 1"],
        ["b", "b b", "b > b b"],
        ["b", "0", "b > 0"],
      ],
      [
        ["b", "b b", "b > b b"],
        ["b", "0", "b > 0"],
        ["b", "1", "b > 1"],
      ],
      [
        ["b", "0", "b > 0"],
        ["b", "b b", "b > b b"],
        ["b", "1", "b > 1"],
      ],
      [
        ["b", "b b", "b > b b"],
        ["b", "1", "b > 1"],
        ["b", "0", "b > 0"],
      ],
      [
        ["b", "1", "b > 1"],
        ["b", "0", "b > 0"],
        ["b", "b b", "b > b b"],
      ],
    ],
    "Binary Numbers": [
      [
        ["b", "0", "b > 0"],
        ["g", "b g", "g > b g"],
        ["g", "b", "g > b"],
      ],
      [
        ["b", "1", "b > 1"],
        ["g", "b", "g > b"],
        ["b", "0", "b > 0"],
      ],
      [
        ["b", "0", "b > 0"],
        ["g", "b", "g > b"],
        ["b", "1", "b > 1"],
        ["g", "b g", "g > b g"],
      ],
      [
        ["b", "1", "b > 1"],
        ["g", "b g", "g > b g"],
        ["g", "b", "g > b"],
      ],
      [
        ["b", "0", "b > 0"],
        ["b", "1", "b > 1"],
        ["g", "b", "g > b"],
        ["g", "b g", "g > b g"],
      ],
      [
        ["b", "0", "b > 0"],
        ["g", "b", "g > b"],
        ["b", "1", "b > 1"],
        ["g", "b g", "g > b g"],
      ],
    ],
    "Three Different Grow Same": [
      [["e = b", "c e = b c", "e = b > c e = b c"]],
      [["e = b", "c e = b c", "e = b > c e = b c"]],
    ],
    "Shrink Same Three Different": [
      [["c e = b c", "e = b", "c e = b c > e = b"]],
      [["c e = b c", "e = b", "c e = b c > e = b"]],
    ],
    "Two Different Grow Same": [
      [["e b", "c e b c", "e b > c e b c"]],
      [["e b", "c e b c", "e b > c e b c"]],
    ],
    "Boolean Literal": [
      [
        ["bo", "true", "bo > true"],
        ["bo", "false", "bo > false"],
      ],
      [
        ["bo", "true", "bo > true"],
        ["bo", "false", "bo > false"],
      ],
    ],
    "Grow Different": [
      [["a", "b c", "a > b c"]],
      [["a", "b c", "a > b c"]],
      [["a", "b c", "a > b c"]],
    ],
    "Shrink Different": [
      [["b c", "a", "b c > a"]],
      [["b c", "a", "b c > a"]],
      [["b c", "a", "b c > a"]],
    ],
    Double: [
      [["a", "a a", "a > a a"]],
      [["a", "a a", "a > a a"]],
      [["a", "a a", "a > a a"]],
    ],
    Half: [
      [["a a", "a", "a a > a"]],
      [["a a", "a", "a a > a"]],
      [["a a", "a", "a a > a"]],
    ],
    "Same Replace Right": [
      [["a a", "a b", "a a > a b"]],
      [["a a", "a b", "a a > a b"]],
      [["a a", "a b", "a a > a b"]],
    ],
    "Same Replace Left": [
      [["a a", "b a", "a a > b a"]],
      [["a a", "b a", "a a > b a"]],
      [["a a", "b a", "a a > b a"]],
    ],
    "Replace Right Same": [
      [["a b", "a a", "a b > a a"]],
      [["a b", "a a", "a b > a a"]],
      [["a b", "a a", "a b > a a"]],
    ],
    "Right Change": [
      [["a b", "a c", "a b > a c"]],
      [["a b", "a c", "a b > a c"]],
      [["a b", "a c", "a b > a c"]],
    ],
    "Replace Left Same": [
      [["b a", "a a", "b a > a a"]],
      [["b a", "a a", "b a > a a"]],
      [["b a", "a a", "b a > a a"]],
    ],
    "Grow Triple": [
      [["a", "a a a", "a > a a a"]],
      [["a", "a a a", "a > a a a"]],
      [["a", "a a a", "a > a a a"]],
    ],
    "Shrink Triple": [
      [["a a a", "a", "a a a > a"]],
      [["a a a", "a", "a a a > a"]],
      [["a a a", "a", "a a a > a"]],
    ],
    "Unary Equations": [
      [["=", "1 = 1", "= > 1 = 1"]],
      [["=", "1 = 1", "= > 1 = 1"]],
      [["=", "1 = 1", "= > 1 = 1"]],
    ],
    "Shrink Both Same": [
      [["a b a", "b", "a b a > b"]],
      [["a b a", "b", "a b a > b"]],
      [["a b a", "b", "a b a > b"]],
    ],
    "Grow Between": [
      [["a a", "a b a", "a a > a b a"]],
      [["a a", "a b a", "a a > a b a"]],
      [["a a", "a b a", "a a > a b a"]],
    ],
    "Shrink Between": [
      [["a b a", "a a", "a b a > a a"]],
      [["a b a", "a a", "a b a > a a"]],
      [["a b a", "a a", "a b a > a a"]],
    ],
    "Grow Different 2": [
      [
        ["a", "b c", "a > b c"],
        ["b", "d e", "b > d e"],
      ],
      [
        ["a", "b c", "a > b c"],
        ["b", "d e", "b > d e"],
      ],
      [
        ["b", "d e", "b > d e"],
        ["a", "b c", "a > b c"],
      ],
    ],
    "Shrink Different 2": [
      [
        ["d e", "b", "d e > b"],
        ["b c", "a", "b c > a"],
      ],
      [
        ["b c", "a", "b c > a"],
        ["d e", "b", "d e > b"],
      ],
      [
        ["d e", "b", "d e > b"],
        ["b c", "a", "b c > a"],
      ],
    ],
    "Swap 2": [
      [
        ["a b", "b a", "a b > b a"],
        ["a c", "c a", "a c > c a"],
      ],
      [
        ["a c", "c a", "a c > c a"],
        ["a b", "b a", "a b > b a"],
      ],
      [
        ["a b", "b a", "a b > b a"],
        ["a c", "c a", "a c > c a"],
      ],
    ],
    "Swap 3": [
      [
        ["a b", "b a", "a b > b a"],
        ["a d", "d a", "a d > d a"],
        ["a c", "c a", "a c > c a"],
      ],
      [
        ["a d", "d a", "a d > d a"],
        ["a b", "b a", "a b > b a"],
        ["a c", "c a", "a c > c a"],
      ],
      [
        ["a c", "c a", "a c > c a"],
        ["a b", "b a", "a b > b a"],
        ["a d", "d a", "a d > d a"],
      ],
    ],
    "Binary Counting Prepare 2": [
      [
        ["0 a", "1", "0 a > 1"],
        ["1 a", "a 0", "1 a > a 0"],
        ["1", "1 1", "1 > 1 1"],
      ],
      [
        ["1", "1 1", "1 > 1 1"],
        ["1 a", "a 0", "1 a > a 0"],
        ["0 a", "1", "0 a > 1"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["1", "1 1", "1 > 1 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
    ],
    "Grow Right": [
      [["g", "g s", "g > g s"]],
      [["g", "g s", "g > g s"]],
      [["g", "g s", "g > g s"]],
      [["g", "g s", "g > g s"]],
    ],
    "Grow Left": [
      [["g", "s g", "g > s g"]],
      [["g", "s g", "g > s g"]],
      [["g", "s g", "g > s g"]],
      [["g", "s g", "g > s g"]],
    ],
    "Shrink Right": [
      [["a b", "a", "a b > a"]],
      [["a b", "a", "a b > a"]],
      [["a b", "a", "a b > a"]],
      [["a b", "a", "a b > a"]],
    ],
    "Shrink Left": [
      [["b a", "a", "b a > a"]],
      [["b a", "a", "b a > a"]],
      [["b a", "a", "b a > a"]],
      [["b a", "a", "b a > a"]],
    ],
    "Replace 2": [
      [
        ["a", "b", "a > b"],
        ["c", "d", "c > d"],
      ],
      [
        ["c", "d", "c > d"],
        ["a", "b", "a > b"],
      ],
      [
        ["a", "b", "a > b"],
        ["c", "d", "c > d"],
      ],
      [
        ["a", "b", "a > b"],
        ["c", "d", "c > d"],
      ],
    ],
    Swap: [
      [["a b", "b a", "a b > b a"]],
      [["a b", "b a", "a b > b a"]],
      [["a b", "b a", "a b > b a"]],
      [["a b", "b a", "a b > b a"]],
    ],
    "Replace Flow": [
      [
        ["b", "c", "b > c"],
        ["a", "b", "a > b"],
      ],
      [
        ["b", "c", "b > c"],
        ["a", "b", "a > b"],
      ],
      [
        ["b", "c", "b > c"],
        ["a", "b", "a > b"],
      ],
      [
        ["a", "b", "a > b"],
        ["b", "c", "b > c"],
      ],
    ],
    Slide: [
      [["1 a", "a 0", "1 a > a 0"]],
      [["1 a", "a 0", "1 a > a 0"]],
      [["1 a", "a 0", "1 a > a 0"]],
      [["1 a", "a 0", "1 a > a 0"]],
    ],
    "Add One": [
      [
        ["c", "a c", "c > a c"],
        ["0 a", "1", "0 a > 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
        ["0 a", "1", "0 a > 1"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
    ],
    "Binary Counting": [
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["b a", "b 1", "b a > b 1"],
        ["c", "a c", "c > a c"],
      ],
      [
        ["b a", "b 1", "b a > b 1"],
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["c", "a c", "c > a c"],
        ["1 a", "a 0", "1 a > a 0"],
        ["b a", "b 1", "b a > b 1"],
      ],
    ],
    "Statements Simple": [
      [
        ["ex", "update ( )", "ex > update ( )"],
        ["sm", "ex ;", "sm > ex ;"],
        ["sm", ";", "sm > ;"],
      ],
      [
        ["ex", "update ( )", "ex > update ( )"],
        ["sm", "return ;", "sm > return ;"],
        ["sm", "ex ;", "sm > ex ;"],
      ],
      [
        ["ex", "update ( )", "ex > update ( )"],
        ["sm", "ex ;", "sm > ex ;"],
        ["sm", "return ex ;", "sm > return ex ;"],
      ],
      [
        ["ex", "true", "ex > true"],
        ["sm", "return ex ;", "sm > return ex ;"],
        ["sm", "ex ;", "sm > ex ;"],
      ],
    ],
    "Statements Block": [
      [
        ["bs", "{ }", "bs > { }"],
        ["sm", ";", "sm > ;"],
        ["bs", "{ smg }", "bs > { smg }"],
      ],
      [
        ["smg", "sm", "smg > sm"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["sm", ";", "sm > ;"],
      ],
      [
        ["smg", "sm", "smg > sm"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["sm", "ex ;", "sm > ex ;"],
        ["ex", "update ( )", "ex > update ( )"],
      ],
      [
        ["smg", "smg sm", "smg > smg sm"],
        ["smg", "sm", "smg > sm"],
        ["sm", "ex ;", "sm > ex ;"],
        ["ex", "update ( )", "ex > update ( )"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["ex", "true", "ex > true"],
        ["sm", "return ex ;", "sm > return ex ;"],
      ],
    ],
    "Statements While": [
      [
        ["ws", "while ( ex ) sm", "ws > while ( ex ) sm"],
        ["ex", "x < 3", "ex > x < 3"],
        ["ex", "x = x + 1", "ex > x = x + 1"],
        ["sm", "ex ;", "sm > ex ;"],
      ],
      [
        ["ex", "y > 0", "ex > y > 0"],
        ["ws", "while ( ex ) sm", "ws > while ( ex ) sm"],
        ["sm", "bs", "sm > bs"],
        ["smg", "sm", "smg > sm"],
        ["ex", "y = y - 1", "ex > y = y - 1"],
        ["sm", "ex ;", "sm > ex ;"],
        ["bs", "{ smg }", "bs > { smg }"],
      ],
      [
        ["bs", "{ smg }", "bs > { smg }"],
        ["ex", "! found ( door )", "ex > ! found ( door )"],
        ["smg", "smg sm", "smg > smg sm"],
        ["smg", "sm", "smg > sm"],
        ["sm", "bs", "sm > bs"],
        ["ws", "while ( ex ) sm", "ws > while ( ex ) sm"],
      ],
      [
        ["ex", "seek ( )", "ex > seek ( )"],
        ["ex", "ask ( )", "ex > ask ( )"],
        ["sm", "ex ;", "sm > ex ;"],
      ],
    ],
    "Statements For": [
      [
        ["ex", "i = 0", "ex > i = 0"],
        ["fs", "for ( ex ; ex ; ex ) sm", "fs > for ( ex ; ex ; ex ) sm"],
        ["ex", "i = i + 1", "ex > i = i + 1"],
        ["ex", "i < 12", "ex > i < 12"],
      ],
      [
        ["sm", "ex ;", "sm > ex ;"],
        ["ex", "log ( apostle [ i ] )", "ex > log ( apostle [ i ] )"],
        ["sm", "bs", "sm > bs"],
      ],
      [
        ["ex", "i = 0", "ex > i = 0"],
        ["ex", "i = i + 1", "ex > i = i + 1"],
        ["fs", "for ( ex ; ex ; ex ) sm", "fs > for ( ex ; ex ; ex ) sm"],
        ["ex", "i < list . length", "ex > i < list . length"],
      ],
      [
        ["smg", "smg sm", "smg > smg sm"],
        ["ex", "copy [ i ] = list [ i ]", "ex > copy [ i ] = list [ i ]"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["smg", "sm", "smg > sm"],
        ["ex", "log ( i )", "ex > log ( i )"],
        ["sm", "bs", "sm > bs"],
        ["sm", "ex ;", "sm > ex ;"],
      ],
    ],
    "Swap Change Right": [
      [["a b", "b c", "a b > b c"]],
      [["a b", "b c", "a b > b c"]],
      [["a b", "b c", "a b > b c"]],
      [["a b", "b c", "a b > b c"]],
      [["a b", "b c", "a b > b c"]],
    ],
    "Swap Change Left": [
      [["b c", "a b", "b c > a b"]],
      [["b c", "a b", "b c > a b"]],
      [["b c", "a b", "b c > a b"]],
      [["b c", "a b", "b c > a b"]],
      [["b c", "a b", "b c > a b"]],
    ],
    "Binary Counting Prepare 1": [
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["1", "1 1", "1 > 1 1"],
      ],
      [
        ["1", "1 1", "1 > 1 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["1", "1 1", "1 > 1 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["1", "1 1", "1 > 1 1"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["1", "1 1", "1 > 1 1"],
      ],
    ],
    "Expand Collapse": [
      [
        ["a", "b b", "a > b b"],
        ["b b", "c", "b b > c"],
      ],
      [
        ["a", "b b", "a > b b"],
        ["b b", "c", "b b > c"],
      ],
      [
        ["b b", "c", "b b > c"],
        ["a", "b b", "a > b b"],
      ],
      [
        ["a", "b b", "a > b b"],
        ["b b", "c", "b b > c"],
      ],
      [
        ["b b", "c", "b b > c"],
        ["a", "b b", "a > b b"],
      ],
      [
        ["a", "b b", "a > b b"],
        ["b b", "c", "b b > c"],
      ],
    ],
    "Shrink Left Pair Replace Right Same": [
      [
        ["b a", "a", "b a > a"],
        ["b c", "b b", "b c > b b"],
      ],
      [
        ["b a", "a", "b a > a"],
        ["b c", "b b", "b c > b b"],
      ],
      [
        ["b a", "a", "b a > a"],
        ["b c", "b b", "b c > b b"],
      ],
      [
        ["b a", "a", "b a > a"],
        ["b c", "b b", "b c > b b"],
      ],
      [
        ["b c", "b b", "b c > b b"],
        ["b a", "a", "b a > a"],
      ],
      [
        ["b c", "b b", "b c > b b"],
        ["b a", "a", "b a > a"],
      ],
    ],
    "Grow Left Pair Change Right": [
      [
        ["b b", "b c", "b b > b c"],
        ["a", "b a", "a > b a"],
      ],
      [
        ["b b", "b c", "b b > b c"],
        ["a", "b a", "a > b a"],
      ],
      [
        ["a", "b a", "a > b a"],
        ["b b", "b c", "b b > b c"],
      ],
      [
        ["a", "b a", "a > b a"],
        ["b b", "b c", "b b > b c"],
      ],
      [
        ["b b", "b c", "b b > b c"],
        ["a", "b a", "a > b a"],
      ],
      [
        ["a", "b a", "a > b a"],
        ["b b", "b c", "b b > b c"],
      ],
    ],
    "Unary Equations Adding": [
      [
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
        ["=", "1 = 1", "= > 1 = 1"],
      ],
      [
        ["=", "1 = 1", "= > 1 = 1"],
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
      ],
      [
        ["=", "1 = 1", "= > 1 = 1"],
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
      ],
      [
        ["=", "1 = 1", "= > 1 = 1"],
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
      ],
      [
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
        ["=", "1 = 1", "= > 1 = 1"],
      ],
      [
        ["=", "1 = 1", "= > 1 = 1"],
        ["1 1", "1 + 1", "1 1 > 1 + 1"],
      ],
    ],
    "Marker Convert": [
      [
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
      ],
    ],
    "Exponent Part": [
      [
        ["sn", "ig se", "sn > ig se"],
        ["eE", "e", "eE > e"],
        ["se", "eE ep", "se > eE ep"],
        ["ep", "ig", "ep > ig"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["in", "di", "in > di"],
        ["pi", "8", "pi > 8"],
      ],
      [
        ["pi", "2", "pi > 2"],
        ["pi", "5", "pi > 5"],
        ["di", "pi", "di > pi"],
      ],
      [
        ["se", "eE ep", "se > eE ep"],
        ["eE", "e", "eE > e"],
        ["ep", "+ ig", "ep > + ig"],
        ["sn", "ig se", "sn > ig se"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["pi", "3", "pi > 3"],
        ["pi", "4", "pi > 4"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["eE", "E", "eE > E"],
        ["sn", "ig se", "sn > ig se"],
        ["se", "eE ep", "se > eE ep"],
        ["ep", "- ig", "ep > - ig"],
      ],
      [
        ["pi", "6", "pi > 6"],
        ["pi", "1", "pi > 1"],
        ["di", "pi", "di > pi"],
        ["ig", "di", "ig > di"],
      ],
    ],
    Replace: [
      [["a", "b", "a > b"]],
      [["a", "b", "a > b"]],
      [["a", "b", "a > b"]],
      [["a", "b", "a > b"]],
      [["a", "b", "a > b"]],
    ],
    "Statements Variable": [
      [
        ["vk", "let", "vk > let"],
        ["vdg", "vd", "vdg > vd"],
        ["vd", "id", "vd > id"],
        ["id", "i", "id > i"],
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
      ],
      [
        ["ex", "0", "ex > 0"],
        ["vd", "id = ex", "vd > id = ex"],
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
        ["id", "j", "id > j"],
        ["vk", "let", "vk > let"],
        ["vdg", "vd", "vdg > vd"],
      ],
      [
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
        ["id", "y", "id > y"],
        ["vdg", "vd", "vdg > vd"],
        ["id", "x", "id > x"],
        ["vdg", "vdg , vd", "vdg > vdg , vd"],
        ["vk", "var", "vk > var"],
        ["vd", "id", "vd > id"],
      ],
      [
        ["vdg", "vd", "vdg > vd"],
        ["vk", "var", "vk > var"],
        ["vd", "id", "vd > id"],
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
        ["vdg", "vdg , vd", "vdg > vdg , vd"],
        ["id", "a", "id > a"],
      ],
      [
        ["id", "b", "id > b"],
        ["vd", "id", "vd > id"],
        ["id", "c", "id > c"],
      ],
      [
        ["vd", "id = ex", "vd > id = ex"],
        ["vk", "const", "vk > const"],
        ["vdg", "vdg , vd", "vdg > vdg , vd"],
        ["id", "y", "id > y"],
        ["ex", "2", "ex > 2"],
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
      ],
      [
        ["vdg", "vd", "vdg > vd"],
        ["vd", "id = ex", "vd > id = ex"],
        ["id", "x", "id > x"],
        ["ex", "1", "ex > 1"],
      ],
    ],
    "Statements If": [
      [
        ["is", "if ( ex ) sm", "is > if ( ex ) sm"],
        ["ex", "y === null", "ex > y === null"],
        ["sm", "return ;", "sm > return ;"],
      ],
      [
        ["sm", "bs", "sm > bs"],
        ["ex", "x < 0", "ex > x < 0"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["is", "if ( ex ) sm", "is > if ( ex ) sm"],
      ],
      [
        ["sm", "ex ;", "sm > ex ;"],
        ["smg", "sm", "smg > sm"],
        ["ex", "x = 1", "ex > x = 1"],
      ],
      [
        ["is", "if ( ex ) sm", "is > if ( ex ) sm"],
        ["ex", "y > max", "ex > y >> max"],
        ["sm", "bs", "sm > bs"],
        ["bs", "{ smg }", "bs > { smg }"],
      ],
      [
        ["smg", "smg sm", "smg > smg sm"],
        ["sm", "ex ;", "sm > ex ;"],
        ["smg", "sm", "smg > sm"],
        ["ex", "y = 0", "ex > y = 0"],
        ["ex", 'log ( "reset" )', 'ex > log ( "reset" )'],
      ],
      [
        ["ex", "x > 0", "ex > x > 0"],
        ["is", "if ( ex ) sm else sm", "is > if ( ex ) sm else sm"],
        ["is", "if ( ex ) sm", "is > if ( ex ) sm"],
      ],
      [
        ["sm", "ex ;", "sm > ex ;"],
        ["ex", "positive = true", "ex > positive = true"],
        ["ex", "positive = false", "ex > positive = false"],
      ],
    ],
    "Unary To Binary Equations Preparation": [
      [
        ["d e =", "= d", "d e = > = d"],
        ["d", "d d", "d > d d"],
        ["= d", "d f =", "= d > d f ="],
      ],
      [
        ["d d", "d e d", "d d > d e d"],
        ["= d", "d f =", "= d > d f ="],
        ["d", "d d", "d > d d"],
      ],
      [
        ["d d", "d e d", "d d > d e d"],
        ["e d", "e =", "e d > e ="],
        ["d", "d d", "d > d d"],
      ],
      [
        ["d d", "d e d", "d d > d e d"],
        ["d e =", "= d", "d e = > = d"],
        ["= d", "d f =", "= d > d f ="],
      ],
      [
        ["d d", "d e d", "d d > d e d"],
        ["d e =", "= d", "d e = > = d"],
        ["= d", "d f =", "= d > d f ="],
      ],
      [
        ["d e =", "= d", "d e = > = d"],
        ["= d", "d f =", "= d > d f ="],
        ["d", "d d", "d > d d"],
      ],
      [
        ["= d", "d f =", "= d > d f ="],
        ["d", "d d", "d > d d"],
        ["d d", "d e d", "d d > d e d"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["d d", "d e d", "d d > d e d"],
        ["d e =", "= d", "d e = > = d"],
        ["= d", "d f =", "= d > d f ="],
        ["d", "d d", "d > d d"],
        ["e d", "e =", "e d > e ="],
      ],
    ],
    "Expressions Unary": [
      [
        ["mae", "pe", "mae > pe"],
        ["ue", "uo ue", "ue > uo ue"],
        ["pe", "li", "pe > li"],
        ["ue", "ce", "ue > ce"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["in", "2", "in > 2"],
        ["uo", "-", "uo > -"],
        ["li", "nu", "li > nu"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["bo", "true", "bo > true"],
        ["uo", "!", "uo > !"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["uo", "+", "uo > +"],
        ["nu", "de", "nu > de"],
        ["li", "nu", "li > nu"],
        ["de", "3.14", "de > 3.14"],
      ],
      [
        ["uo", "typeof", "uo > typeof"],
        ["li", "null", "li > null"],
        ["ue", "uo ue", "ue > uo ue"],
      ],
      [
        ["pe", "( ex )", "pe > ( ex )"],
        ["mae", "pe", "mae > pe"],
        ["uo", "-", "uo > -"],
        ["ue", "uo ue", "ue > uo ue"],
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["uo", "-", "uo > -"],
        ["pe", "li", "pe > li"],
        ["ex", "ue", "ex > ue"],
        ["mae", "pe", "mae > pe"],
        ["ue", "ce", "ue > ce"],
        ["ue", "uo ue", "ue > uo ue"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["in", "1", "in > 1"],
        ["li", "nu", "li > nu"],
      ],
    ],
    "Integer Digits": [
      [
        ["di", "0", "di > 0"],
        ["ig", "di", "ig > di"],
        ["di", "6", "di > 6"],
      ],
      [
        ["di", "2", "di > 2"],
        ["ig", "di", "ig > di"],
        ["di", "4", "di > 4"],
      ],
      [
        ["ig", "di ig", "ig > di ig"],
        ["di", "3", "di > 3"],
        ["ig", "di", "ig > di"],
        ["di", "0", "di > 0"],
      ],
      [
        ["di", "9", "di > 9"],
        ["ig", "di", "ig > di"],
        ["ig", "di ig", "ig > di ig"],
        ["di", "8", "di > 8"],
      ],
      [
        ["ig", "di ig", "ig > di ig"],
        ["di", "2", "di > 2"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["di", "3", "di > 3"],
        ["di", "4", "di > 4"],
        ["di", "7", "di > 7"],
      ],
      [
        ["di", "4", "di > 4"],
        ["di", "5", "di > 5"],
        ["di", "6", "di > 6"],
      ],
      [
        ["di", "8", "di > 8"],
        ["ig", "di ig", "ig > di ig"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["di", "1", "di > 1"],
        ["di", "2", "di > 2"],
        ["di", "0", "di > 0"],
      ],
      [
        ["di", "4", "di > 4"],
        ["di", "2", "di > 2"],
        ["di", "3", "di > 3"],
      ],
    ],
    Integers: [
      [
        ["di", "0", "di > 0"],
        ["pi", "7", "pi > 7"],
        ["in", "di", "in > di"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["in", "di", "in > di"],
        ["pi", "2", "pi > 2"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["ig", "di", "ig > di"],
        ["pi", "1", "pi > 1"],
        ["in", "pi ig", "in > pi ig"],
        ["pi", "3", "pi > 3"],
      ],
      [
        ["pi", "7", "pi > 7"],
        ["ig", "di", "ig > di"],
        ["di", "pi", "di > pi"],
        ["in", "pi ig", "in > pi ig"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["di", "0", "di > 0"],
        ["pi", "4", "pi > 4"],
        ["in", "pi ig", "in > pi ig"],
      ],
      [
        ["ig", "di ig", "ig > di ig"],
        ["in", "pi ig", "in > pi ig"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["pi", "9", "pi > 9"],
        ["di", "pi", "di > pi"],
        ["pi", "6", "pi > 6"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["in", "pi ig", "in > pi ig"],
        ["ig", "di ig", "ig > di ig"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["pi", "6", "pi > 6"],
        ["pi", "5", "pi > 5"],
      ],
      [
        ["pi", "7", "pi > 7"],
        ["di", "pi", "di > pi"],
        ["pi", "8", "pi > 8"],
      ],
    ],
    Decimals: [
      [
        ["in", "di", "in > di"],
        ["di", "0", "di > 0"],
        ["de", "in .", "de > in ."],
      ],
      [
        ["di", "pi", "di > pi"],
        ["de", ". ig", "de > . ig"],
        ["ig", "di", "ig > di"],
        ["pi", "5", "pi > 5"],
      ],
      [
        ["pi", "2", "pi > 2"],
        ["in", "di", "in > di"],
        ["de", "in .", "de > in ."],
        ["di", "pi", "di > pi"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["ig", "di ig", "ig > di ig"],
        ["de", "in . ig", "de > in . ig"],
      ],
      [
        ["pi", "4", "pi > 4"],
        ["pi", "1", "pi > 1"],
        ["di", "pi", "di > pi"],
        ["pi", "3", "pi > 3"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["de", "in . ig", "de > in . ig"],
        ["in", "pi ig", "in > pi ig"],
      ],
      [
        ["ig", "di ig", "ig > di ig"],
        ["in", "pi ig", "in > pi ig"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["pi", "7", "pi > 7"],
        ["pi", "9", "pi > 9"],
      ],
      [
        ["pi", "8", "pi > 8"],
        ["di", "pi", "di > pi"],
        ["pi", "5", "pi > 5"],
      ],
      [
        ["pi", "6", "pi > 6"],
        ["pi", "7", "pi > 7"],
        ["di", "pi", "di > pi"],
      ],
    ],
    "Identifiers Simple": [
      [
        ["id", "idf", "id > idf"],
        ["idf", "_", "idf > _"],
        ["di", "0", "di > 0"],
      ],
      [
        ["id", "idf idg", "id > idf idg"],
        ["idg", "ida", "idg > ida"],
        ["idf", "t", "idf > t"],
      ],
      [
        ["ida", "di", "ida > di"],
        ["di", "1", "di > 1"],
        ["idf", "$", "idf > $"],
      ],
      [
        ["id", "idf idg", "id > idf idg"],
        ["ida", "di", "ida > di"],
        ["idg", "ida", "idg > ida"],
        ["idf", "t", "idf > t"],
        ["di", "3", "di > 3"],
      ],
      [
        ["id", "idf idg", "id > idf idg"],
        ["idg", "ida", "idg > ida"],
        ["idg", "ida idg", "idg > ida idg"],
      ],
      [
        ["idf", "v", "idf > v"],
        ["idf", "u", "idf > u"],
        ["ida", "idf", "ida > idf"],
        ["idf", "l", "idf > l"],
      ],
      [
        ["idg", "ida idg", "idg > ida idg"],
        ["id", "idf idg", "id > idf idg"],
        ["idg", "ida", "idg > ida"],
      ],
      [
        ["idf", "l", "idf > l"],
        ["ida", "idf", "ida > idf"],
        ["idf", "B", "idf > B"],
      ],
      [
        ["di", "0", "di > 0"],
        ["idf", "A", "idf > A"],
        ["idf", "B", "idf > B"],
      ],
      [
        ["ida", "di", "ida > di"],
        ["idf", "$", "idf > $"],
        ["ida", "idf", "ida > idf"],
      ],
      [
        ["idf", "J", "idf > J"],
        ["idf", "$", "idf > $"],
        ["di", "0", "di > 0"],
        ["idf", "h", "idf > h"],
      ],
    ],
    "Expressions Multiplicative": [
      [
        ["mue", "ue", "mue > ue"],
        ["mue", "mue mo ue", "mue > mue mo ue"],
        ["ue", "ce", "ue > ce"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["pe", "li", "pe > li"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["in", "1", "in > 1"],
        ["in", "2", "in > 2"],
        ["mo", "/", "mo > /"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["in", "2", "in > 2"],
        ["nu", "in", "nu > in"],
        ["mo", "*", "mo > *"],
        ["nu", "de", "nu > de"],
        ["de", "3.14", "de > 3.14"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["mo", "*", "mo > *"],
        ["pe", "( ex )", "pe > ( ex )"],
      ],
      [
        ["ex", "mue", "ex > mue"],
        ["mue", "mue mo ue", "mue > mue mo ue"],
        ["bo", "true", "bo > true"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["mue", "ue", "mue > ue"],
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["id", "list", "id > list"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["de", "3.14", "de > 3.14"],
        ["nu", "in", "nu > in"],
        ["mo", "*", "mo > *"],
        ["nu", "de", "nu > de"],
        ["in", "2", "in > 2"],
        ["mo", "/", "mo > /"],
      ],
    ],
    "Function Declarations": [
      [
        ["fd", "function id ( fdm bs", "fd > function id ( fdm bs"],
        ["id", "empty", "id > empty"],
        ["bs", "{ }", "bs > { }"],
        ["fdm", ")", "fdm > )"],
      ],
      [
        ["fd", "function id ( fdm bs", "fd > function id ( fdm bs"],
        ["sm", "return ex ;", "sm > return ex ;"],
        ["fdm", ")", "fdm > )"],
        ["id", "tautology", "id > tautology"],
        ["smg", "sm", "smg > sm"],
        ["bs", "{ smg }", "bs > { smg }"],
        ["ex", "true", "ex > true"],
      ],
      [
        ["fdm", "fpg )", "fdm > fpg )"],
        ["fpg", "id", "fpg > id"],
        ["fd", "function id ( fdm bs", "fd > function id ( fdm bs"],
      ],
      [
        ["id", "i", "id > i"],
        ["ex", "i", "ex > i"],
        ["id", "identity", "id > identity"],
      ],
      [
        ["id", "f", "id > f"],
        ["id", "invoke", "id > invoke"],
        ["ex", "f ( )", "ex > f ( )"],
      ],
      [
        ["bs", "{ smg }", "bs > { smg }"],
        ["fd", "function id ( fdm bs", "fd > function id ( fdm bs"],
        ["fdm", "fpg )", "fdm > fpg )"],
      ],
      [
        ["id", "x", "id > x"],
        ["id", "y", "id > y"],
        ["fpg", "fpg , id", "fpg > fpg , id"],
        ["fpg", "id", "fpg > id"],
      ],
      [
        ["sm", "return ex ;", "sm > return ex ;"],
        ["ex", "x + y", "ex > x + y"],
        ["smg", "sm", "smg > sm"],
        ["id", "add", "id > add"],
      ],
      [
        ["sm", "return ex ;", "sm > return ex ;"],
        ["smg", "sm", "smg > sm"],
        ["sm", "vs", "sm > vs"],
        ["smg", "smg sm", "smg > smg sm"],
      ],
      [
        ["vdg", "vd", "vdg > vd"],
        ["vk", "let", "vk > let"],
        ["vd", "id = ex", "vd > id = ex"],
        ["vs", "vk vdg ;", "vs > vk vdg ;"],
      ],
      [
        ["ex", "add ( x , y )", "ex > add ( x , y )"],
        ["ex", "sum / 2", "ex > sum / 2"],
        ["id", "sum", "id > sum"],
        ["id", "average", "id > average"],
      ],
    ],
    "Scientific Notation Numbers": [
      [
        ["eE", "e", "eE > e"],
        ["ep", "ig", "ep > ig"],
        ["sn", "de se", "sn > de se"],
        ["de", "in .", "de > in ."],
        ["se", "eE ep", "se > eE ep"],
        ["ig", "di", "ig > di"],
      ],
      [
        ["in", "di", "in > di"],
        ["di", "0", "di > 0"],
        ["di", "pi", "di > pi"],
        ["pi", "1", "pi > 1"],
      ],
      [
        ["de", "in .", "de > in ."],
        ["eE", "E", "eE > E"],
        ["ep", "+ ig", "ep > + ig"],
        ["sn", "de se", "sn > de se"],
        ["se", "eE ep", "se > eE ep"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["di", "pi", "di > pi"],
        ["pi", "2", "pi > 2"],
        ["ig", "di ig", "ig > di ig"],
        ["in", "di", "in > di"],
      ],
      [
        ["pi", "3", "pi > 3"],
        ["di", "pi", "di > pi"],
        ["pi", "9", "pi > 9"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["sn", "de se", "sn > de se"],
        ["se", "eE ep", "se > eE ep"],
        ["eE", "e", "eE > e"],
        ["de", ". ig", "de > . ig"],
        ["ep", "- ig", "ep > - ig"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["ig", "di ig", "ig > di ig"],
        ["di", "0", "di > 0"],
      ],
      [
        ["pi", "8", "pi > 8"],
        ["di", "pi", "di > pi"],
        ["pi", "1", "pi > 1"],
        ["pi", "5", "pi > 5"],
      ],
      [
        ["sn", "de se", "sn > de se"],
        ["ep", "ig", "ep > ig"],
        ["de", "in . ig", "de > in . ig"],
        ["ig", "di", "ig > di"],
        ["eE", "E", "eE > E"],
        ["se", "eE ep", "se > eE ep"],
      ],
      [
        ["ig", "di", "ig > di"],
        ["ig", "di ig", "ig > di ig"],
        ["di", "0", "di > 0"],
      ],
      [
        ["di", "pi", "di > pi"],
        ["in", "di", "in > di"],
        ["pi", "1", "pi > 1"],
        ["pi", "3", "pi > 3"],
      ],
      [
        ["pi", "4", "pi > 4"],
        ["di", "pi", "di > pi"],
        ["pi", "9", "pi > 9"],
      ],
    ],
    "Strings Simple": [
      [
        ["di", "0", "di > 0"],
        ["stg", "ida", "stg > ida"],
        ["st", '" stg "', 'st > " stg "'],
      ],
      [
        ["idf", "_", "idf > _"],
        ["ida", "idf", "ida > idf"],
        ["di", "0", "di > 0"],
      ],
      [
        ["st", '" stg "', 'st > " stg "'],
        ["stg", "ida", "stg > ida"],
        ["stg", "ida stg", "stg > ida stg"],
      ],
      [
        ["idf", "$", "idf > $"],
        ["di", "1", "di > 1"],
        ["ida", "idf", "ida > idf"],
        ["ida", "di", "ida > di"],
      ],
      [
        ["ida", "di", "ida > di"],
        ["ida", "idf", "ida > idf"],
        ["di", "3", "di > 3"],
        ["idf", "t", "idf > t"],
      ],
      [
        ["stg", "ida stg", "stg > ida stg"],
        ["st", '" stg "', 'st > " stg "'],
        ["stg", "ida", "stg > ida"],
      ],
      [
        ["idf", "u", "idf > u"],
        ["idf", "v", "idf > v"],
        ["idf", "l", "idf > l"],
        ["ida", "idf", "ida > idf"],
      ],
      [
        ["stg", "ida", "stg > ida"],
        ["st", '" stg "', 'st > " stg "'],
        ["stg", "ida stg", "stg > ida stg"],
      ],
      [
        ["stg", "ida", "stg > ida"],
        ["ida", "di", "ida > di"],
        ["ida", "idf", "ida > idf"],
      ],
      [
        ["idf", "B", "idf > B"],
        ["idf", "A", "idf > A"],
        ["idf", "t", "idf > t"],
      ],
      [
        ["di", "0", "di > 0"],
        ["ida", "idf", "ida > idf"],
        ["ida", "di", "ida > di"],
      ],
      [
        ["idf", "$", "idf > $"],
        ["idf", "J", "idf > J"],
        ["di", "0", "di > 0"],
        ["idf", "h", "idf > h"],
      ],
    ],
    "Expressions Logical": [
      [
        ["le", "ee", "le > ee"],
        ["le", "le lo ee", "le > le lo ee"],
        ["ee", "re", "ee > re"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["re", "ade", "re > ade"],
        ["st", '"luv"', 'st > "luv"'],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
        ["mue", "ue", "mue > ue"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["pe", "id", "pe > id"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["bo", "true", "bo > true"],
        ["bo", "false", "bo > false"],
        ["lo", "&&", "lo > &&"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["lo", "||", "lo > ||"],
        ["bo", "false", "bo > false"],
        ["bo", "true", "bo > true"],
        ["pe", "li", "pe > li"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["pe", "( ex )", "pe > ( ex )"],
        ["bo", "true", "bo > true"],
        ["li", "bo", "li > bo"],
        ["ex", "le", "ex > le"],
        ["lo", "&&", "lo > &&"],
      ],
      [
        ["ee", "re", "ee > re"],
        ["lo", "||", "lo > ||"],
        ["le", "ee", "le > ee"],
        ["le", "le lo ee", "le > le lo ee"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["id", "knock", "id > knock"],
        ["re", "ade", "re > ade"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["mue", "ue", "mue > ue"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["li", "bo", "li > bo"],
        ["bo", "true", "bo > true"],
        ["bo", "false", "bo > false"],
      ],
    ],
    "Expressions Primary": [
      [
        ["pe", "id", "pe > id"],
        ["in", "2", "in > 2"],
        ["de", "3.14", "de > 3.14"],
      ],
      [
        ["id", "x", "id > x"],
        ["pe", "li", "pe > li"],
        ["pe", "id", "pe > id"],
      ],
      [
        ["li", "bo", "li > bo"],
        ["pe", "li", "pe > li"],
        ["bo", "true", "bo > true"],
      ],
      [
        ["bo", "false", "bo > false"],
        ["pe", "li", "pe > li"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["in", "1", "in > 1"],
        ["li", "nu", "li > nu"],
        ["nu", "in", "nu > in"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["nu", "de", "nu > de"],
        ["de", "3.14", "de > 3.14"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["st", '"luv"', 'st > "luv"'],
        ["li", "st", "li > st"],
      ],
      [
        ["li", "bo", "li > bo"],
        ["li", "null", "li > null"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["st", '"luv"', 'st > "luv"'],
        ["ex", "pe", "ex > pe"],
        ["pe", "( ex )", "pe > ( ex )"],
      ],
      [
        ["bo", "true", "bo > true"],
        ["pe", "( ex )", "pe > ( ex )"],
        ["ex", "pe", "ex > pe"],
      ],
      [
        ["ex", "pe", "ex > pe"],
        ["pe", "id", "pe > id"],
        ["pe", "( ex )", "pe > ( ex )"],
      ],
      [
        ["pe", "( ex )", "pe > ( ex )"],
        ["id", "y", "id > y"],
        ["pe", "id", "pe > id"],
        ["ex", "pe", "ex > pe"],
      ],
      [
        ["pe", "( ex )", "pe > ( ex )"],
        ["li", "nu", "li > nu"],
        ["ex", "pe", "ex > pe"],
      ],
    ],
    "Expressions Member And Access": [
      [
        ["pe", "li", "pe > li"],
        ["nu", "in", "nu > in"],
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["id", "x", "id > x"],
        ["mae", "mle", "mae > mle"],
        ["mle", "mae . id", "mle > mae . id"],
        ["pe", "id", "pe > id"],
        ["id", "y", "id > y"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["mae", "mle", "mae > mle"],
        ["id", "prop", "id > prop"],
        ["pe", "( ex )", "pe > ( ex )"],
        ["mle", "mae . id", "mle > mae . id"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["pe", "id", "pe > id"],
        ["ex", "mae", "ex > mae"],
        ["mae", "mle", "mae > mle"],
        ["mle", "mae . id", "mle > mae . id"],
      ],
      [
        ["id", "human", "id > human"],
        ["id", "last", "id > last"],
        ["id", "name", "id > name"],
      ],
      [
        ["pe", "id", "pe > id"],
        ["mle", "mae . id", "mle > mae . id"],
        ["mae", "pe", "mae > pe"],
        ["mae", "mle", "mae > mle"],
      ],
      [
        ["id", "birthdate", "id > birthdate"],
        ["id", "year", "id > year"],
        ["id", "human", "id > human"],
      ],
      [
        ["mle", "mae [ ex ]", "mle > mae [ ex ]"],
        ["pe", "id", "pe > id"],
        ["mae", "mle", "mae > mle"],
        ["mae", "pe", "mae > pe"],
        ["ex", "mae", "ex > mae"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["st", '"luv"', 'st > "luv"'],
        ["li", "st", "li > st"],
      ],
      [
        ["ex", "mae", "ex > mae"],
        ["mae", "mle", "mae > mle"],
        ["mle", "mae [ ex ]", "mle > mae [ ex ]"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["ex", "mae", "ex > mae"],
        ["mae", "pe", "mae > pe"],
        ["mae", "mle", "mae > mle"],
        ["mle", "mae [ ex ]", "mle > mae [ ex ]"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["pe", "li", "pe > li"],
        ["li", "nu", "li > nu"],
        ["in", "2", "in > 2"],
      ],
    ],
    "Expressions Equality": [
      [
        ["ade", "mue", "ade > mue"],
        ["ee", "ee === re", "ee > ee === re"],
        ["re", "ade", "re > ade"],
        ["ee", "re", "ee > re"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["ee", "ee === re", "ee > ee === re"],
        ["de", "3.14", "de > 3.14"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["li", "st", "li > st"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["li", "bo", "li > bo"],
        ["mo", "/", "mo > /"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["de", "3.14", "de > 3.14"],
        ["in", "1", "in > 1"],
      ],
      [
        ["ee", "re", "ee > re"],
        ["ex", "ee", "ex > ee"],
        ["re", "ade", "re > ade"],
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["pe", "( ex )", "pe > ( ex )"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["id", "x", "id > x"],
        ["mue", "ue", "mue > ue"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["id", "fn", "id > fn"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["id", "x", "id > x"],
        ["id", "y", "id > y"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["pe", "li", "pe > li"],
        ["id", "y", "id > y"],
      ],
      [
        ["re", "ade", "re > ade"],
        ["id", "add", "id > add"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["in", "2", "in > 2"],
        ["in", "1", "in > 1"],
        ["ao", "+", "ao > +"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["ao", "-", "ao > -"],
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["in", "2", "in > 2"],
      ],
    ],
    "Expressions Relational": [
      [
        ["ade", "mue", "ade > mue"],
        ["ro", "<", "ro > <"],
        ["re", "re ro ade", "re > re ro ade"],
        ["re", "ade", "re > ade"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ag", "ex", "ag > ex"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["li", "nu", "li > nu"],
        ["in", "0", "in > 0"],
      ],
      [
        ["in", "2", "in > 2"],
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["re", "re ro ade", "re > re ro ade"],
        ["ro", ">", "ro > >>"],
        ["re", "ade", "re > ade"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["ce", "mae", "ce > mae"],
        ["mue", "ue", "mue > ue"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["ce", "ce ( ag )", "ce > ce ( ag )"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["re", "re ro ade", "re > re ro ade"],
        ["de", "3.14", "de > 3.14"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["de", "3.14", "de > 3.14"],
        ["in", "1", "in > 1"],
        ["nu", "de", "nu > de"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["pe", "( ex )", "pe > ( ex )"],
        ["pe", "li", "pe > li"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["ex", "re", "ex > re"],
        ["re", "ade", "re > ade"],
        ["nu", "in", "nu > in"],
        ["in", "1", "in > 1"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["mue", "ue", "mue > ue"],
        ["ao", "+", "ao > +"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["id", "refresh", "id > refresh"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["li", "null", "li > null"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["bo", "true", "bo > true"],
        ["ade", "mue", "ade > mue"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["in", "2", "in > 2"],
        ["de", "3.14", "de > 3.14"],
        ["nu", "de", "nu > de"],
      ],
    ],
    "Expressions Function Calls": [
      [
        ["ce", "mae", "ce > mae"],
        ["pe", "id", "pe > id"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["mae", "pe", "mae > pe"],
        ["id", "fn", "id > fn"],
        ["pe", "id", "pe > id"],
        ["ce", "ce ( )", "ce > ce ( )"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["pe", "id", "pe > id"],
        ["mle", "mae . id", "mle > mae . id"],
        ["mae", "mle", "mae > mle"],
        ["mae", "pe", "mae > pe"],
        ["ce", "ce ( )", "ce > ce ( )"],
      ],
      [
        ["bo", "true", "bo > true"],
        ["id", "refresh", "id > refresh"],
        ["id", "page", "id > page"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["ag", "ex", "ag > ex"],
        ["ce", "ce ( ag )", "ce > ce ( ag )"],
        ["pe", "id", "pe > id"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ex", "ce", "ex > ce"],
      ],
      [
        ["nu", "de", "nu > de"],
        ["li", "nu", "li > nu"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["ag", "ex", "ag > ex"],
        ["ce", "ce ( )", "ce > ce ( )"],
        ["ag", "ex , ag", "ag > ex , ag"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["ex", "ce", "ex > ce"],
        ["pe", "li", "pe > li"],
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["ex", "ce", "ex > ce"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["id", "add", "id > add"],
        ["in", "2", "in > 2"],
      ],
      [
        ["mae", "mle", "mae > mle"],
        ["mle", "mae . id", "mle > mae . id"],
        ["mae", "pe", "mae > pe"],
        ["pe", "id", "pe > id"],
        ["ce", "mae", "ce > mae"],
        ["ex", "ce", "ex > ce"],
      ],
      [
        ["id", "building", "id > building"],
        ["id", "door", "id > door"],
        ["id", "knock", "id > knock"],
      ],
      [
        ["mae", "mle", "mae > mle"],
        ["mae", "pe", "mae > pe"],
        ["pe", "id", "pe > id"],
        ["ce", "mae", "ce > mae"],
        ["mle", "mae [ ex ]", "mle > mae [ ex ]"],
        ["ex", "ce", "ex > ce"],
      ],
      [
        ["ex", "ce", "ex > ce"],
        ["li", "nu", "li > nu"],
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["id", "list", "id > list"],
        ["id", "double", "id > double"],
        ["in", "0", "in > 0"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["ce", "mae", "ce > mae"],
        ["pe", "id", "pe > id"],
        ["ex", "ce", "ex > ce"],
        ["ce", "ce ( )", "ce > ce ( )"],
      ],
      [
        ["id", "all", "id > all"],
        ["id", "double", "id > double"],
        ["id", "love", "id > love"],
      ],
    ],
    "Expressions Assignment": [
      [
        ["lh", "id", "lh > id"],
        ["ase", "lh = ase", "ase > lh = ase"],
        ["ase", "le", "ase > le"],
        ["re", "ade", "re > ade"],
        ["ee", "re", "ee > re"],
        ["id", "x", "id > x"],
        ["le", "ee", "le > ee"],
      ],
      [
        ["id", "x", "id > x"],
        ["mue", "ue", "mue > ue"],
        ["ade", "mue", "ade > mue"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["ase", "lh = ase", "ase > lh = ase"],
        ["le", "ee", "le > ee"],
        ["re", "ade", "re > ade"],
        ["lh", "mle", "lh > mle"],
        ["ee", "re", "ee > re"],
        ["ase", "le", "ase > le"],
      ],
      [
        ["id", "x", "id > x"],
        ["id", "y", "id > y"],
        ["mle", "mae . id", "mle > mae . id"],
        ["pe", "id", "pe > id"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ade", "mue", "ade > mue"],
        ["id", "fn", "id > fn"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["nu", "in", "nu > in"],
        ["li", "nu", "li > nu"],
        ["in", "2", "in > 2"],
      ],
      [
        ["ase", "le", "ase > le"],
        ["mle", "mae [ ex ]", "mle > mae [ ex ]"],
        ["ex", "ase", "ex > ase"],
        ["le", "ee", "le > ee"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["re", "ade", "re > ade"],
        ["ee", "re", "ee > re"],
      ],
      [
        ["ee", "re", "ee > re"],
        ["ade", "mue", "ade > mue"],
        ["mue", "mue mo ue", "mue > mue mo ue"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["mue", "ue", "mue > ue"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ce", "mae", "ce > mae"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["mo", "/", "mo > /"],
        ["mae", "pe", "mae > pe"],
        ["in", "2", "in > 2"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["li", "nu", "li > nu"],
        ["pe", "id", "pe > id"],
      ],
      [
        ["in", "0", "in > 0"],
        ["id", "y", "id > y"],
        ["nu", "in", "nu > in"],
        ["id", "z", "id > z"],
      ],
      [
        ["lh", "id", "lh > id"],
        ["in", "1", "in > 1"],
        ["ase", "lh = ase", "ase > lh = ase"],
      ],
      [
        ["id", "y", "id > y"],
        ["bo", "false", "bo > false"],
        ["id", "x", "id > x"],
      ],
      [
        ["le", "ee", "le > ee"],
        ["re", "ade", "re > ade"],
        ["ase", "le", "ase > le"],
        ["ee", "re", "ee > re"],
      ],
      [
        ["mo", "*", "mo > *"],
        ["ade", "mue", "ade > mue"],
        ["mue", "ue", "mue > ue"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["in", "0", "in > 0"],
        ["ue", "ce", "ue > ce"],
        ["li", "nu", "li > nu"],
        ["nu", "in", "nu > in"],
      ],
    ],
    "Expressions Additive": [
      [
        ["mue", "ue", "mue > ue"],
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["ade", "mue", "ade > mue"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
        ["mae", "pe", "mae > pe"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["in", "1", "in > 1"],
        ["ao", "-", "ao > -"],
        ["nu", "in", "nu > in"],
        ["in", "2", "in > 2"],
      ],
      [
        ["in", "2", "in > 2"],
        ["de", "3.14", "de > 3.14"],
        ["ao", "+", "ao > +"],
        ["nu", "in", "nu > in"],
        ["nu", "de", "nu > de"],
      ],
      [
        ["pe", "( ex )", "pe > ( ex )"],
        ["ce", "mae", "ce > mae"],
        ["mae", "pe", "mae > pe"],
      ],
      [
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["mae", "pe", "mae > pe"],
        ["ex", "ade", "ex > ade"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["ce", "mae", "ce > mae"],
        ["ade", "mue", "ade > mue"],
        ["mue", "ue", "mue > ue"],
      ],
      [
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
        ["ue", "ce", "ue > ce"],
        ["mae", "pe", "mae > pe"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["nu", "de", "nu > de"],
        ["de", "3.14", "de > 3.14"],
        ["nu", "in", "nu > in"],
        ["in", "2", "in > 2"],
        ["ao", "+", "ao > +"],
        ["ao", "-", "ao > -"],
      ],
      [
        ["mue", "mue mo ue", "mue > mue mo ue"],
        ["mue", "ue", "mue > ue"],
        ["ue", "ce", "ue > ce"],
        ["ade", "mue", "ade > mue"],
        ["ade", "ade ao mue", "ade > ade ao mue"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["mue", "ue", "mue > ue"],
        ["mle", "mae . id", "mle > mae . id"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["li", "nu", "li > nu"],
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["pe", "li", "pe > li"],
        ["mae", "pe", "mae > pe"],
        ["li", "nu", "li > nu"],
        ["ce", "mae", "ce > mae"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["li", "nu", "li > nu"],
        ["mae", "pe", "mae > pe"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["pe", "li", "pe > li"],
        ["mae", "pe", "mae > pe"],
        ["ao", "-", "ao > -"],
        ["li", "nu", "li > nu"],
      ],
      [
        ["mo", "/", "mo > /"],
        ["ue", "ce", "ue > ce"],
        ["nu", "in", "nu > in"],
      ],
      [
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["in", "2", "in > 2"],
        ["de", "3.14", "de > 3.14"],
        ["nu", "de", "nu > de"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ade", "mue", "ade > mue"],
        ["ue", "ce", "ue > ce"],
      ],
      [
        ["ce", "ce ( ag )", "ce > ce ( ag )"],
        ["ex", "ade", "ex > ade"],
        ["ag", "ex", "ag > ex"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["ce", "mae", "ce > mae"],
        ["pe", "id", "pe > id"],
      ],
      [
        ["mue", "ue", "mue > ue"],
        ["ade", "ade ao mue", "ade > ade ao mue"],
        ["ade", "mue", "ade > mue"],
      ],
      [
        ["ue", "ce", "ue > ce"],
        ["mle", "mae . id", "mle > mae . id"],
        ["li", "bo", "li > bo"],
      ],
      [
        ["ce", "mae", "ce > mae"],
        ["li", "nu", "li > nu"],
        ["id", "knock", "id > knock"],
      ],
      [
        ["mae", "pe", "mae > pe"],
        ["mue", "ue", "mue > ue"],
        ["pe", "li", "pe > li"],
      ],
      [
        ["ade", "mue", "ade > mue"],
        ["li", "nu", "li > nu"],
        ["pe", "( ex )", "pe > ( ex )"],
      ],
      [
        ["in", "1", "in > 1"],
        ["nu", "in", "nu > in"],
        ["id", "double", "id > double"],
        ["in", "2", "in > 2"],
        ["ao", "+", "ao > +"],
      ],
    ],
    "Unary To Binary Equations": [
      [
        ["b a", "b 1", "b a > b 1"],
        ["d e =", "= d", "d e = > = d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
        ["d c", "a d", "d c > a d"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
        ["b a", "b 1", "b a > b 1"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["b a", "b 1", "b a > b 1"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["e = b", "c e = b c", "e = b > c e = b c"],
        ["d b", "b d", "d b > b d"],
        ["c c", "c + b c", "c c > c + b c"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d e =", "= d", "d e = > = d"],
        ["e = b", "c e = b c", "e = b > c e = b c"],
      ],
      [
        ["e = b", "c e = b c", "e = b > c e = b c"],
        ["d e =", "= d", "d e = > = d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["e = b", "c e = b c", "e = b > c e = b c"],
        ["1 a", "a 0", "1 a > a 0"],
        ["d +", "+ d", "d + > + d"],
      ],
      [
        ["c c", "c + b c", "c c > c + b c"],
        ["d c", "a d", "d c > a d"],
        ["e = b", "c e = b c", "e = b > c e = b c"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d +", "+ d", "d + > + d"],
        ["c c", "c + b c", "c c > c + b c"],
      ],
      [
        ["e = b", "c e = b c", "e = b > c e = b c"],
        ["c c", "c + b c", "c c > c + b c"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["b a", "b 1", "b a > b 1"],
        ["c c", "c + b c", "c c > c + b c"],
        ["d +", "+ d", "d + > + d"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["c c", "c + b c", "c c > c + b c"],
        ["e = b", "c e = b c", "e = b > c e = b c"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
        ["c c", "c + b c", "c c > c + b c"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["d +", "+ d", "d + > + d"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d +", "+ d", "d + > + d"],
        ["d c", "a d", "d c > a d"],
      ],
      [
        ["d b", "b d", "d b > b d"],
        ["d c", "a d", "d c > a d"],
        ["d +", "+ d", "d + > + d"],
      ],
      [
        ["d +", "+ d", "d + > + d"],
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["d b", "b d", "d b > b d"],
        ["d e =", "= d", "d e = > = d"],
      ],
      [
        ["d e =", "= d", "d e = > = d"],
        ["d c", "a d", "d c > a d"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["b a", "b 1", "b a > b 1"],
        ["1 a", "a 0", "1 a > a 0"],
        ["c c", "c + b c", "c c > c + b c"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["1 a", "a 0", "1 a > a 0"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["b a", "b 1", "b a > b 1"],
        ["1 a", "a 0", "1 a > a 0"],
        ["0 a", "1", "0 a > 1"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["0 a", "1", "0 a > 1"],
        ["b a", "b 1", "b a > b 1"],
      ],
      [
        ["1 a", "a 0", "1 a > a 0"],
        ["b a", "b 1", "b a > b 1"],
        ["0 a", "1", "0 a > 1"],
      ],
      [
        ["d c", "a d", "d c > a d"],
        ["b a", "b 1", "b a > b 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
      [
        ["0 a", "1", "0 a > 1"],
        ["c c", "c + b c", "c c > c + b c"],
        ["e = b", "c e = b c", "e = b > c e = b c"],
      ],
      [
        ["d +", "+ d", "d + > + d"],
        ["0 a", "1", "0 a > 1"],
        ["1 a", "a 0", "1 a > a 0"],
      ],
    ],
  };
  return v;
}
