import { fn_name } from "./fn_name.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { app_shared_color_red_pointer } from "./app_shared_color_red_pointer.mjs";
export function app_code_highlight_color_third() {
  "the third pointing colour, for a screen where three different words are each pointing at a different piece of the same line of code";
  ("CHOSEN HERE, AND SO IS ",
    fn_name("app_code_highlight_color_second"),
    ". The four colours this app tells numbers apart with were the obvious place to shop, and they are the wrong shape for this: they only have to differ from each other, where these three have also to sit evenly round the wheel and to stand at the same distance off a black line. Two colours picked for one job rarely fit another without being moved.");
  ("THE MOVING TURNED OUT TO BE SMALL, AND THE PARAGRAPH ABOVE GIVES THE WRONG REASON FOR IT. Measured 2026-09-20, each of these three sits close to one of those four: the second pointer is 0.043 from the chip green, this red is 0.060 from the chip red, the first pointer is 0.083 from the chip blue. The second pointer and the chip green are the same hue and the same chroma and differ in lightness alone, 0.55 against 0.51. So this is not a different set of colours; it is that set, lifted to stand off a black line.");
  ("Standing off black was never what ruled them out either - the chip red, green and blue measure 3.16, 3.89 and 3.46 against it, and a shape needs 3. What actually rules them out is the amber, which measures 4.48 under white lettering where lettering needs 4.5, and a pointer is a patch of colour with white code written on it. The real answer is that three of the four would serve and the fourth would not, and that the lightness had to move anyway.");
  ("WHICH MAKES THIS A NEAR MISS BY THE APP'S OWN RULE AND IT IS LEFT STANDING. Colours here are meant to be the same colour or plainly different ones, never almost the same, and 0.043 apart is almost the same. Collapsing it means choosing one lightness for both a black line and a pale card, which is a judgment about colour, and every such judgment in this app is waiting on somebody who has worked in colour. Note also that the gate for that rule cannot see this pair at all: it reads colours written out as text, and every colour on both sides of this comparison is built by a call.");
  "THE HUE, THE LIGHTNESS AND WHAT THEY MEASURE AGAINST ARE WRITTEN WITH THE VALUE, IN " +
    fn_name("app_shared_color_red_pointer") +
    " - including the reasoning that first put the hue at 340 degrees and the eye that moved it to 15. Those are facts about the colour. What stays here is why this app needed a third pointer, and what it cost to find one.";
  ("A RED, AND RED LOOKED SPOKEN FOR. The reds that mean a wrong answer land on a whole button or a whole block after the learner has pressed something, and a colour covering that much of the page after a press reads as a verdict. This lands on two brackets inside a line nobody has pressed yet, so it has nothing to answer and is read as a place to look. It is also a crimson rather than either of those reds, which are a pure red.");
  ("THREE COLOURS CANNOT ALL SURVIVE A READER WHO CANNOT TELL RED FROM GREEN, and this is the one that gives way. Blue against green is the pair that survives THAT reader - measured 2026-09-20 it stands at 0.363 with no red cone and 0.374 with no green cone, against 0.051 for this red and that green - and it is the pair carrying the two ! that must never be confused. This red may collapse into that green for such a reader, and it is survivable here and only here: what this colour marks is a bracket, and a bracket is not shaped like a !, so the character still tells them apart. A screen wanting a third pointer where all three are the same character has no business using this.");
  ("BUT THE PAIR THAT SURVIVES RED-GREEN IS THE PAIR THAT DIES OF SOMETHING ELSE, and the sentence above said survives without saying which reader. To someone with no BLUE cone the first pointer and the second stand at 0.011 - the same colour, well under the 0.02 where two colours stop being tellable apart at all - so on a screen carrying the two ! there is a reader for whom they are one colour and the safety argued for above is not there. That way of seeing is far rarer, perhaps one person in ten thousand against one man in twelve, which is why the trade is still the right one; it is written down because the earlier sentence read as a guarantee and it is not one. The four colours this app tells numbers apart with have the identical fault between their green and their blue, found the same day and by the same mistake - only the common ways of seeing had been simulated.");
  arguments_assert(arguments, 0);
  let color = app_shared_color_red_pointer();
  return color;
}
