import { arguments_assert } from "./arguments_assert.mjs";
import { app_g_map_generate } from "./app_g_map_generate.mjs";
import { g_coordinates } from "./g_coordinates.mjs";
import { g_coordinates_land_reachable_get } from "./g_coordinates_land_reachable_get.mjs";
import { g_player_img_get } from "./g_player_img_get.mjs";
import { g_player_initialize } from "./g_player_initialize.mjs";
import { app_g_bless_people } from "./app_g_bless_people.mjs";
import { app_g_bless_street } from "./app_g_bless_street.mjs";
import { app_g_bless_street_pave } from "./app_g_bless_street_pave.mjs";
import { app_g_bless_world } from "./app_g_bless_world.mjs";
export function app_g_bless_world_new() {
  arguments_assert(arguments, 0);
  ("A fresh world to walk about in - ground, a street, a player standing on it, and a crowd.");
  ("Nearly every step of it is the gospel game's own generator. The ground it makes, the way");
  ("it works out which land is actually reachable, and the way it sets somebody down on it");
  ("are not opinions about that game; they are what a walkable world is. Writing a second");
  ("set would have given this game a world that walked slightly differently, and every later");
  ("fix to walking would then have to be made twice.");
  ("Only the crowd and the street are this game's own, because only those differ: those");
  ("people are here to be seen and prayed for rather than talked to, and the street is the");
  ("first place a prayer can climb to.");
  ("The land list is consumed as it is handed out - the player takes a tile off it and the");
  ("crowd takes the rest they need - so nobody is ever set down on top of anybody else.");
  ("The coordinates are worked out AFTER the street is paved rather than before. Paving");
  ("turns whatever it crosses into path, and a list made first would still be calling those");
  ("squares water - so the player would be refused a walk down the street they can see.");
  let rows = app_g_map_generate();
  let coordinates_unpaved = g_coordinates(rows);
  let coordinates_land = g_coordinates_land_reachable_get(coordinates_unpaved);
  let player_img = g_player_img_get();
  let player = g_player_initialize(player_img, coordinates_land);
  let npcs = app_g_bless_people(player_img, coordinates_land);
  let street = app_g_bless_street(rows, player);
  app_g_bless_street_pave(rows, street);
  let coordinates = g_coordinates(rows);
  let world = app_g_bless_world(rows, coordinates, player, npcs, street);
  return world;
}
