import { arguments_assert } from "./arguments_assert.mjs";
export function app_code_lesson_id_length_ceiling() {
  arguments_assert(arguments, 0);
  ("How many characters one code lesson's id may be.");
  ("An id is read by a person in two places, and length is the whole of what it costs in both. It sits in the address of the lesson, which is the thing somebody sends to somebody else; and it is the key a learner's finished work is written down under on their own device, where a record with a hundred and thirty three long keys in it is what a person reads when they go looking for why their progress is gone.");
  ("★ THIS NUMBER IS A MEASUREMENT AND NOT A JUDGMENT. It is the longest id that exists today, so it says nothing about what a good length is - it says only that no id may be worse than the worst one already here. That is deliberate, because any number chosen as a judgment would have been invented by whoever wanted to get past it.");
  ("So the only direction it may move is down. It comes down by somebody shortening the id that is sitting at it and then writing the new longest here, which is a measurement again rather than a decision.");
  ("Raising it is the wrong move, and the reason is not the usual one. A page's byte ceiling is sometimes raised because the growth is real - a list got longer because more languages are offered. Nothing of the kind can happen to an id. An id is not the title and does not have to say what the lesson teaches; it only has to be unique and recognisable, and there is always a shorter spelling of it. A lesson that seems to need seventeen characters needs a better id, not a bigger ceiling.");
  ("It has already come down once, from twenty one, when eighteen ids were shortened in one pass. A second pass shortened thirteen more, every id that had arrived above the number since - four lessons that watch a name to the end of a line, the four that pair an operator with an equals sign, the two that compare with an equals sign, two averages and a grid column. The same reason applied both times: all thirteen were still behind the release cut, so nobody was holding one of them as a key.");
  ("Nine ids sit at the number now, and that is a change in kind from the two that sat there before, because a reader taking it lower has nine to move rather than one. They are digits inside a number, underscores in a name, four that open with the order word, one copy, one count watched to the end, and one digit split. Every one of them is long because the English words are long rather than because the id says too much, so the way down is a shorter word for each - and the two oldest of them, digits and underscores, are still the ones to start with.");
  ("It was checked that the gate reading this can actually fail rather than only pass, on this table rather than on the one before it: at fifteen it named the ids then sitting at sixteen, with their sizes and the remedy, and at sixteen it names nothing.");
  let count = 16;
  return count;
}
