import { arguments_assert } from "./arguments_assert.mjs";
import { app_shared_container_base } from "./app_shared_container_base.mjs";
import { html_style_background_color_set } from "./html_style_background_color_set.mjs";
import { app_shared_color_white } from "./app_shared_color_white.mjs";
import { html_border } from "./html_border.mjs";
import { app_shared_spaced_frame_gap } from "./app_shared_spaced_frame_gap.mjs";
import { app_shared_color_blue_medium } from "./app_shared_color_blue_medium.mjs";
import { html_div_text_centered } from "./html_div_text_centered.mjs";
import { html_font_color_set } from "./html_font_color_set.mjs";
import { app_shared_color_blue_dark } from "./app_shared_color_blue_dark.mjs";
import { html_bold } from "./html_bold.mjs";
import { html_div } from "./html_div.mjs";
import { html_style_set } from "./html_style_set.mjs";
export function app_receipts_day_card(parent, title) {
  "$plain parent";
  "$plain title";
  "A card holding one day's purchases under the day's name, handing back the part below the name to put them in.";
  "The card is white with a blue edge, a colour none of the purchases can be marked with, so a purchase in any colour stands out against it rather than disappearing into it. What is put in it is spaced apart, so each purchase reads as a button of its own.";
  arguments_assert(arguments, 2);
  let card = app_shared_container_base(parent);
  let background = app_shared_color_white();
  html_style_background_color_set(card, background);
  let border_width = app_shared_spaced_frame_gap();
  let border_color = app_shared_color_blue_medium();
  html_border(card, border_width, border_color);
  let header = html_div_text_centered(card, title);
  let color = app_shared_color_blue_dark();
  html_font_color_set(header, color);
  html_bold(header);
  let body = html_div(card);
  html_style_set(body, "display", "flex");
  html_style_set(body, "flex-direction", "column");
  html_style_set(body, "gap", "0.6em");
  html_style_set(body, "margin-top", "0.4em");
  return body;
}
