import { text_rtl_is } from "./text_rtl_is.mjs";
import { ternary } from "./ternary.mjs";
import { html_style_set } from "./html_style_set.mjs";
import { html_text_align } from "./html_text_align.mjs";
import { html_attribute_set } from "./html_attribute_set.mjs";
import { app_shared_color_red } from "./app_shared_color_red.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { html_hr } from "./html_hr.mjs";
import { html_div } from "./html_div.mjs";
import { property_get } from "./property_get.mjs";
import { html_span_text } from "./html_span_text.mjs";
import { html_bold_mild } from "./html_bold_mild.mjs";
import { html_font_color_set } from "./html_font_color_set.mjs";
import { html_span_colon_2 } from "./html_span_colon_2.mjs";
import { app_shared_color_gray } from "./app_shared_color_gray.mjs";
export function app_shared_gloss_bible_word_row(e, p, word_property) {
  arguments_assert(arguments, 3);
  html_hr(p);
  let div = html_div(p);
  let word = property_get(e, word_property);
  let gloss = property_get(e, "gloss");
  let explain = property_get(e, "explain");
  ("the row runs the way the explanation runs, because the explanation is the reader's own language and the rest of the row is what they came here not knowing. read right to left an urdu row gives the english word first, then what it means, then why - the same three steps an english row gives read left to right.");
  ("without this the row ran left to right whatever was in it, and the browser gathered every urdu piece into one backwards run: the meaning came out AFTER the explanation of it, so the one word a beginner needed first was the last thing on the line.");
  html_text_direction_set(div, explain);
  let span = html_span_text(div, word);
  html_bold_mild(span);
  ("each piece is held in its own run, detected from itself, so an english word inside an urdu row reads forwards and does not turn the row around it");
  html_attribute_set(span, "dir", "auto");
  let color3 = app_shared_color_red();
  html_font_color_set(span, color3);
  let c = html_span_colon_2(div);
  let color = app_shared_color_gray();
  html_font_color_set(c, color);
  let span2 = html_span_text(div, gloss);
  html_attribute_set(span2, "dir", "auto");
  html_font_color_set(span2, "#1d4ed8ff");
  let c2 = html_span_colon_2(div);
  let color2 = app_shared_color_gray();
  html_font_color_set(c2, color2);
  let span3 = html_span_text(div, explain);
  html_attribute_set(span3, "dir", "auto");
  html_font_color_set(span3, "#a21cafff");
}
