import { arguments_assert } from "./arguments_assert.mjs";
import { fn_name } from "./fn_name.mjs";
import { color_oklch } from "./color_oklch.mjs";
export function app_code_lesson_chip_colors() {
  arguments_assert(arguments, 0);
  ("the categorical chip colours - a red, a green, a blue and an amber - hand-picked to be as distinct and familiar as possible, NOT an even-hue formula, so a learner tells one number from another at a glance");
  ("THE WHOLE LIST IS ANSWERED RATHER THAN ONE OF THEM, SO THAT WHATEVER COUNTS THEM CANNOT DISAGREE WITH WHATEVER USES THEM. A gate checking this palette has to know how many there are; told four, it would go on checking four the day a fifth arrived, and would pass while saying nothing at all about the colour that was actually added. Asked for the list, it checks whatever is here.");
  ("They are spelled together because nothing outside asks for one of them by itself. The amber was lifted out under its own name for a while, when the second of the colours that point at a piece of code was taken from this list; that pointer is a green of its own now and the name went back where it came from. Lift one out again the moment a second reader wants exactly one of these - never by its place in the list, because the order these happen to be written in is not a name for what sits there.");
  "FIVE THINGS ARE KNOWN TO BE WRONG HERE AND ARE ALL LEFT STANDING ON PURPOSE, BECAUSE EVERY FIX IS A JUDGMENT ABOUT COLOUR AND NOBODY WHO HAS WORKED IN COLOUR HAS LOOKED AT THEM YET. Measured 2026-09-19 and 2026-09-20, and written down so whoever does look arrives holding the numbers rather than having to find them again. None of them is a reason to change anything today; every one of them is a reason not to let the palette change quietly while the question waits, which is what " +
    fn_name("app_code_lesson_chip_color_gate_run") +
    " is for.";
  ("THREE OF THE FIVE ARE THE AMBER, WHICH IS THE FINDING AND NOT A COINCIDENCE. It is the lightest member by a clear margin - the red and the blue sit at 0.500, the green at 0.510 and the amber at 0.580 - and every one of its faults is a shortfall of contrast that a darker amber would clear at once. The whole of what is wrong with it is that one number being 0.08 above the others. So a reader arriving at this list should not read those three as three separate problems: there is one weak member, and the question waiting for someone is what to do about it.");
  ("The amber is short in all three of the ways a chip colour is drawn. As the ground under the white lettering of a number chip it measures 4.48 where lettering needs 4.5 - barely short, but short. As coloured lettering itself on the pale blue card it measures 3.91 against that same 4.5. And the light ring that lifts a chip off a black code tile measures 2.98 against it where a shape needs 3, so on amber alone that ring nearly disappears. Pulling the amber darker clears all three together; it also changes a colour somebody chose by looking, which is the part that is not arithmetic.");
  ("The fourth is not about contrast at all. A reader with no green cone, about one man in twelve, sees hue collapse onto a single blue-yellow line, and the red at 25 lands on that line beside the amber at 56. As a distance in the perceptual space that pair stands at 0.070, against 0.135 for the same pair to a normal eye and 0.15 or better for every other pair here. So the dot grid, whose whole promise is that the eye can follow any single row, hands that reader two colours where it says four.");
  ("The fifth is the worst number anywhere in the palette and was found only by refusing to decide in advance whose eyes count. To a reader with no BLUE cone the green at 150 and the blue at 255 stand at 0.011 apart - not hard to tell apart, but the same colour, well under the 0.02 where two colours stop being reliably distinguishable side by side at all. That is a rarer way to see than the missing green cone, perhaps one person in ten thousand, and it is the only reading here that fails completely rather than narrowly. It was missed on the first pass because only the common cases were simulated, which is the whole lesson: the pair that collapsed was the one nobody had asked about.");
  ("Three readings are already ruled out, so nobody need spend them again. Hues spread evenly were tried and revised away as not distinct enough, so an even formula is a rejected answer rather than an unconsidered one. Moving the red round to 345 nearly doubles the worst pair, to 0.186 - but 345 renders as a magenta and the course loses a red. And keeping the red while making the FOURTH colour a magenta measures 0.032, worse than changing nothing at all, because a magenta lands on top of the blue for that same reader. True red, amber, green and blue cannot all be told apart on that one line; one of the red and the amber has to leave, and only the red has anywhere to go.");
  ("THERE IS A SECOND SET OF COLOURS IN THIS APP AND IT IS NOT A COPY OF THIS ONE, WHICH TOOK TWO MEASUREMENTS TO ESTABLISH AND IS WRITTEN DOWN SO NOBODY ESTABLISHES IT A THIRD TIME. The three pointing colours, led by ",
    fn_name("app_code_highlight_color"),
    ", sit on a black code line where these sit on a pale card, and the one thing the two sets genuinely share is a step in lightness: every pointer lands at about 0.55 and every colour here at about 0.50. Lighter to stand off black, darker to stand off a pale card, arrived at separately on both sides and agreeing.");
  ("Beyond that step they are three different stories. The pointing green is this green and nothing else - same hue at 150, same chroma at 0.15, lightness 0.55 against 0.51 - and at 0.043 apart it is a near miss of the kind this app forbids. The pointing red moved its hue as well, 15 against 25, because it had to be plainly warm and well clear of that green. The pointing blue is not a chosen colour at all but the brand blue the whole site leads with, at chroma 0.215 and hue 262.9 against 0.15 and 255 here, so its numbers were never a palette decision to begin with. One hue list at two lightnesses would therefore serve the green, bend the red and break the blue, which is why these are two sets and not one.");
  ("The written chroma of the amber and the green asks for more colourfulness than sRGB can show, 0.16 and 0.15 against the 0.1413 and 0.1405 that actually appear. That is not a sixth fault: the squashed colour is the one that was looked at and approved. Rewriting the numbers to what shows would be honest and would render identically here, and it is left alone anyway, so that the person who revises these is revising the numbers that were revised before.");
  let red = color_oklch(0.5, 0.2, 25);
  let green = color_oklch(0.51, 0.15, 150);
  let blue = color_oklch(0.5, 0.15, 255);
  let amber = color_oklch(0.58, 0.16, 56.38);
  let colors = [red, green, blue, amber];
  return colors;
}
