export function app_en_learn_bible_gloss_urdu_noun_explains() {
  "The wording every explanation of a named ordinary English noun is given in the store that teaches English to an Urdu reader, for the everyday things the passages keep naming.";
  "These are words whose meaning does not move from one verse to the next. A hand is a hand in every chapter it appears in, so one wording written once is truer than a sentence guessed afresh at each place, and a reader meeting the word again meets the same sentence and knows it.";
  "Each wording says what kind of word it is and then hands over the Urdu word for the thing, because the reader already has Urdu and is being handed English. That is the whole of what a beginner needs from an ordinary noun, and it is exactly what the bare label reading ‘noun’ withholds.";
  "A second sentence is added only where a beginner would go wrong without it: a plural that does not take an s, a word English uses for two things Urdu keeps apart, a word that looks like another word already met. Where there is nothing of that kind to say, one sentence is the whole entry, because a sentence written to fill a space teaches nothing and costs the reader the same attention as one that does.";
  "A handful of words are written down twice, once in small letters and once with a capital, because in these passages the two spellings mean different things. The lookup asks for the word exactly as it stands before it folds a capital away, so the two entries do not collide and each spelling gets its own sentence. That was read out of the lookup rather than assumed: the first draft of this left every capitalised word out, on the belief that the folding would hand ‘Father’ the sentence written for ‘father’, and it would not have.";
  "What a capitalised entry may say is narrower than what its small-letter twin may say, and the reason is that a capital has two causes. It falls on a word standing for God, and it falls on any word at all standing at the head of its sentence - and a man addressing his own father as ‘Father, I have sinned’ carries one while meaning the other. So a capitalised entry names both causes and leaves the reader to see which is in front of them, rather than announcing an answer that would be wrong wherever the second cause is the true one.";
  "‘Spirit’ is still absent, and so is every other pair where nobody has written the second sentence yet. Being able to write two spellings apart is not the same as having written them, and a word with only its small-letter entry has its capitalised places left exactly as they are.";
  let r = {
    man: "اِسم ہے: آدمی، مرد۔ اِس کی جمع بےقاعدہ ہے: 'man' سے 'men' بنتا ہے، 's' لگا کر نہیں۔",
    woman:
      "اِسم ہے: عورت۔ اِس کی جمع بھی بےقاعدہ ہے: 'woman' سے 'women' بنتا ہے۔",
    child:
      "اِسم ہے: بچّہ۔ اِس کی جمع بھی بےقاعدہ ہے: 'child' سے 'children' بنتا ہے۔",
    boy: "اِسم ہے: لڑکا۔",
    girl: "اِسم ہے: لڑکی۔",
    mother: "اِسم ہے: ماں۔",
    father: "اِسم ہے: باپ۔",
    Father:
      "اِسم ہے: باپ۔ انگریزی میں یہ لفظ بڑے حرف سے دو وجہ سے لکھا جاتا ہے: یا تو یہ خُدا کے لیٔے آیا ہے، یا یہ جُملے کے شُروع میں کھڑا ہے۔ دیکھیٔے کہ اِس سے پہلے کویٔی لفظ ہے یا نہیں۔",
    son: "اِسم ہے: بیٹا۔",
    Son: "اِسم ہے: بیٹا۔ بڑا حرف یا تو خُدا کے بیٹے کے لیٔے آتا ہے، یا اِس لیٔے کہ لفظ جُملے کے شُروع میں کھڑا ہے۔",
    king: "اِسم ہے: بادشاہ۔",
    King: "اِسم ہے: بادشاہ۔ بڑا حرف یا تو اِس لیٔے ہے کہ یہ کِسی کے نام کے ساتھ لگا ہے، جیسے 'King Herod'، یا اِس لیٔے کہ لفظ جُملے کے شُروع میں کھڑا ہے۔",
    God: "اِسم ہے: خُدا۔ انگریزی میں جب یہ ایک ہی سچّے خُدا کے لیٔے آتا ہے تو ہمیشہ بڑے حرف سے لکھا جاتا ہے۔",
    Sabbath:
      "اِسم ہے: سبت، یعنی آرام کا دِن۔ یہ ہمیشہ بڑے حرف سے لکھا جاتا ہے، کیونکہ یہ ایک خاص دِن کا نام ہے۔",
    brother:
      "اِسم ہے: بھایٔی۔ انگریزی میں بڑے اَور چھوٹے بھایٔی کے لیٔے ایک ہی لفظ آتا ہے۔",
    sister: "اِسم ہے: بہن۔",
    daughter: "اِسم ہے: بیٹی۔",
    wife: "اِسم ہے: بیوی۔ اِس کی جمع 'wives' ہے، 'f' بدل کر 'v' ہو جاتا ہے۔",
    teacher: "اِسم ہے: اُستاد، سِکھانے والا۔",
    disciple: "اِسم ہے: شاگِرد، پیچھے چلنے والا۔",
    servant: "اِسم ہے: نوکر، خِدمت کرنے والا۔",
    master: "اِسم ہے: مالِک، آقا۔",
    prophet: "اِسم ہے: نبی، خُدا کی طرف سے بولنے والا۔",
    crowd: "اِسم ہے: بھیڑ، لوگوں کا جمگھٹا۔",
    enemy: "اِسم ہے: دُشمن۔",
    generation: "اِسم ہے: نسل، ایک ہی زمانے کے لوگ۔",
    heaven: "اِسم ہے: آسمان۔",
    sky: "اِسم ہے: آسمان، وہ جو سر کے اُوپر دِکھایٔی دیتا ہے۔",
    earth: "اِسم ہے: زمین، یعنی یہ پُوری دُنیا۔",
    ground: "اِسم ہے: زمین، یعنی وہ جگہ جِس پر پاؤں پڑتا ہے۔",
    soil: "اِسم ہے: مِٹّی، وہ زمین جِس میں بیج بویا جاتا ہے۔",
    world: "اِسم ہے: دُنیا، یعنی سب لوگ اَور سب جگہیں۔",
    sea: "اِسم ہے: سمُندر۔",
    mountain: "اِسم ہے: پہاڑ۔",
    field: "اِسم ہے: کھیت۔",
    tree: "اِسم ہے: درخت۔",
    grass: "اِسم ہے: گھاس۔",
    root: "اِسم ہے: جڑ۔",
    seed: "اِسم ہے: بیج۔",
    grain: "اِسم ہے: اناج، دانہ۔",
    wheat: "اِسم ہے: گیہُوں۔",
    fruit: "اِسم ہے: پھل۔",
    bread: "اِسم ہے: روٹی۔",
    food: "اِسم ہے: کھانا۔",
    wine: "اِسم ہے: مَے، انگُور کا رس جو پُرانا ہو چُکا ہو۔",
    oil: "اِسم ہے: تیل۔",
    leaven: "اِسم ہے: خمِیر، وہ تھوڑی سی چیز جو سارے آٹے کو پُھلا دیتی ہے۔",
    water: "اِسم ہے: پانی۔",
    fire: "اِسم ہے: آگ۔",
    wind: "اِسم ہے: ہَوا، یعنی چلتی ہویٔی ہَوا۔",
    cloud: "اِسم ہے: بادل۔",
    stone: "اِسم ہے: پتّھر۔",
    pearl: "اِسم ہے: موتی۔",
    treasure: "اِسم ہے: خزانہ۔",
    cup: "اِسم ہے: پیالہ۔",
    table: "اِسم ہے: میز۔",
    bed: "اِسم ہے: بِستر، چارپایٔی۔",
    door: "اِسم ہے: دروازہ۔",
    wall: "اِسم ہے: دِیوار۔",
    house: "اِسم ہے: گھر، یعنی وہ عِمارت جِس میں لوگ رہتے ہیں۔",
    home: "اِسم ہے: گھر، مگر یہ عِمارت سے زیادہ اُس جگہ کو کہتا ہے جہاں کویٔی اپنا ہے۔",
    town: "اِسم ہے: قصبہ، چھوٹی بستی۔",
    city: "اِسم ہے: شہر۔ 'city' بڑی بستی ہے اَور 'town' چھوٹی۔",
    region: "اِسم ہے: عِلاقہ۔",
    place: "اِسم ہے: جگہ۔",
    way: "اِسم ہے: راستہ۔",
    path: "اِسم ہے: پگڈنڈی، تنگ راستہ۔",
    boat: "اِسم ہے: کشتی۔",
    donkey: "اِسم ہے: گدھا۔",
    prison: "اِسم ہے: قَید خانہ۔",
    church: "اِسم ہے: کلِیسیا، یعنی اِیمان لانے والوں کی جماعت۔",
    body: "اِسم ہے: بدن، جِسم۔",
    head: "اِسم ہے: سر۔",
    hand: "اِسم ہے: ہاتھ۔",
    foot: "اِسم ہے: پاؤں۔ اِس کی جمع بےقاعدہ ہے: 'foot' سے 'feet' بنتا ہے۔",
    eye: "اِسم ہے: آنکھ۔",
    ear: "اِسم ہے: کان۔",
    mouth: "اِسم ہے: مُنہ۔",
    face: "اِسم ہے: چہرہ۔",
    hair: "اِسم ہے: بال۔",
    blood: "اِسم ہے: خُون۔",
    flesh: "اِسم ہے: گوشت، یعنی بدن کا مادّہ۔",
    voice: "اِسم ہے: آواز۔",
    name: "اِسم ہے: نام۔",
    word: "اِسم ہے: لفظ، بات۔",
    parable: "اِسم ہے: تمثِیل، یعنی وہ چھوٹی کہانی جو ایک بات سمجھاتی ہے۔",
    greeting: "اِسم ہے: سلام، مِلتے وقت کہی جانے والی بات۔",
    kiss: "اِسم ہے: بوسہ۔",
    tradition: "اِسم ہے: رِوایت، پُرانے لوگوں سے چلی آتی ہویٔی بات۔",
    reason: "اِسم ہے: وجہ، سبب۔",
    understanding: "اِسم ہے: سمجھ۔",
    mind: "اِسم ہے: ذہن، سوچنے کی جگہ۔",
    heart: "اِسم ہے: دِل۔",
    soul: "اِسم ہے: جان، یعنی اِنسان کے اَندر کی زِندگی۔",
    life: "اِسم ہے: زِندگی۔ اِس کی جمع 'lives' ہے، 'f' بدل کر 'v' ہو جاتا ہے۔",
    death: "اِسم ہے: موت۔",
    sin: "اِسم ہے: گُناہ۔",
    blasphemy: "اِسم ہے: کُفر، خُدا کے خِلاف بُری بات۔",
    faith: "اِسم ہے: اِیمان، بھروسا۔",
    hope: "اِسم ہے: اُمّید۔",
    joy: "اِسم ہے: خُوشی۔",
    peace: "اِسم ہے: سلامتی، چَین۔",
    comfort: "اِسم ہے: تسلّی، دِل کو آرام دینے والی بات۔",
    patience: "اِسم ہے: صبر۔",
    honor: "اِسم ہے: عِزّت۔",
    power: "اِسم ہے: قُوّت، طاقت۔",
    trouble: "اِسم ہے: مُصیبت، تکلِیف۔",
    woe: "اِسم ہے: افسوس، یعنی وہ بات جو آنے والی مُصیبت پر کہی جاتی ہے۔",
    sign: "اِسم ہے: نِشان۔",
    part: "اِسم ہے: حِصّہ۔",
    end: "اِسم ہے: اِنتہا، آخِر۔",
    age: "اِسم ہے: زمانہ، ایک لمبا وقت۔",
    year: "اِسم ہے: سال۔",
    day: "اِسم ہے: دِن۔",
    night: "اِسم ہے: رات۔",
    morning: "اِسم ہے: صُبح۔",
    evening: "اِسم ہے: شام۔",
    hour: "اِسم ہے: گھنٹہ، یعنی دِن کا ایک حِصّہ۔",
    time: "اِسم ہے: وقت۔",
    tax: "اِسم ہے: محصُول، وہ پیسہ جو حاکِم کو دینا پڑتا ہے۔",
    divorce: "اِسم ہے: طلاق۔",
    store: "اِسم ہے: ذخِیرہ، جمع کِیا ہُوا سامان۔",
    kingdom: "اِسم ہے: بادشاہی، یعنی وہ سب جِس پر کویٔی بادشاہ حُکومت کرتا ہے۔",
  };
  return r;
}
