import { arguments_assert } from "./arguments_assert.mjs";
import { property_get } from "./property_get.mjs";
import { list_middle } from "./list_middle.mjs";
import { list_first_property } from "./list_first_property.mjs";
import { property_set } from "./property_set.mjs";
export function app_g_bless_player_place(player, block) {
  arguments_assert(arguments, 2);
  ("Stands the player on the pavement outside the middle door of the middle building of a");
  ("block, looking at it.");
  ("Which block is the caller's to say, and it is always the first. The crowd is numbered");
  ("from the beginning of the line and the first forty-five of them live on the first block,");
  ("so that is where the ladder starts; the blocks further along are what the reach earned");
  ("there is spent on.");
  ("The game opens on a street with people on it, rather than on a field with a street");
  ("somewhere in it. Set down at random the player's first minute would be spent walking to");
  ("find anybody, and the first thing this game asks of them - look at a person and pray for");
  ("them - would not be possible from where they were standing.");
  ("The MIDDLE building, so the block runs away in both directions and the player can see it");
  ("is a row rather than an end. At either end half the world would be behind them.");
  ("Then the MIDDLE of that building's three doors, which is a second question because a");
  ("building has a door per family rather than one door. Standing off the middle door puts");
  ("the building's other two families to the left and right of the player instead of all");
  ("three to one side, so the first thing they look at is a whole building rather than the");
  ("end of one.");
  ("On the PAVEMENT, which is where a person stands who has come to a street to look at it.");
  ("The doorsteps and the front gardens are the row above, so the household the player has");
  ("come to pray for is in front of them with nobody standing on it, and the road is two");
  ("rows below and behind their shoulder.");
  ("The pavement row is asked of the BLOCK rather than counted down from the door, and that");
  ("is the whole reason the block is carried in here. A house may be set back in its slot, so");
  ("counting rows from a door lands somewhere different for a set-back house than for a flush");
  ("one - and the pavement is one straight line along the whole block whichever house you are");
  ("standing outside. Asked of the block it also cannot fall out of step with where the");
  ("pavement was actually laid.");
  ("Facing north, which is the way the fronts look. Everything the game is about - the");
  ("doors, the people outside them, and the people walking past - is then in front of them");
  ("the moment the world appears, and none of it has to be explained.");
  let doors = property_get(block, "doors");
  let doorsteps = list_middle(doors);
  let door = list_middle(doorsteps);
  let sidewalk = property_get(block, "sidewalk");
  let y = list_first_property(sidewalk, "y");
  let x = property_get(door, "x");
  property_set(player, "x", x);
  property_set(player, "y", y);
  property_set(player, "direction", "north");
}
