export function app_code_note_name_halo_width() {
  "how far the black ring reaches out from a name written on a cup, as a number of em";
  "MEASURED AGAINST THE LETTER'S OWN STROKE RATHER THAN PICKED BY EYE. The name is set bold, and a bold letter of this kind is drawn with strokes about a seventh of its height across. A ring reaching out about seven hundredths of that height is plainly there beside the stroke it is ringing and still narrower than the gaps inside the letter, so the hole in an a stays a hole.";
  "★ WIDENED TO THE DISTANCE THE RING ALREADY REACHED AT ITS CORNERS, WHICH IS WHY IT COSTS NOTHING. It was seven hundredths when the ring was eight copies standing round a square, and a square's corners are half as far again as its sides - so the ring was already reaching just under a tenth of an em, on the diagonals only. Now that the copies stand round a circle the radius is the same in every direction, and setting it to that tenth thickens every thin part of the ring up to what its thickest part had been all along. The corner was reaching 0.0990 and this asks 0.1000, so the deepest the ring goes into the letter grows by one part in a hundred - a thousandth of an em, which is below a pixel on any screen the app is read on - while the ring along the axes grows by nearly half. A hole still open at the old corners is still open at these.";
  "That is also the honest ceiling for widening it again. Past here the ring starts eating gaps that were open, and a letter whose holes have filled in is a blob of the darker colour - which is the same thing as losing the letter, and worse than no ring, because a ring that wide has replaced the very shape it was added to make readable. A wider one has to be checked against a drawn a rather than argued for from the stroke.";
  "Counted in em rather than pixels, so the ring keeps its share of the letter at every size. Fixed in pixels it would be a smudge on a large screen and a sliver on a small one, and the letter's readability would depend on the device.";
  let v = 0.1;
  return v;
}
