import { app_g_bless_amen } from "./app_g_bless_amen.mjs";
import { html_style_background_color_black } from "./html_style_background_color_black.mjs";
import { html_flex_column_stretch } from "./html_flex_column_stretch.mjs";
import { html_style_margin_y } from "./html_style_margin_y.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { app_shared_game_container_player } from "./app_shared_game_container_player.mjs";
import { app_shared_game_p_text } from "./app_shared_game_p_text.mjs";
import { bless_prayer_transfer } from "./bless_prayer_transfer.mjs";
import { bless_prayer_transfer_shown } from "./bless_prayer_transfer_shown.mjs";
export function app_g_bless_transfer_overlay(overlay, on_amen) {
  arguments_assert(arguments, 2);
  ("The prayer that gives the whole session to real people, asked BEFORE the game begins.");
  ("It sits here, at the door, rather than at the end, because most players never reach an");
  ("end. Held back as a reward for finishing, it would be the one prayer that everybody who");
  ("stopped early never prayed - and they are the majority. Prayed first, it is already true");
  ("of every blessing that follows while that blessing is being said, and a player who closes");
  ("the tab after two minutes has still prayed for the world they live in.");
  ("The world is standing behind it, and is covered over solid rather than dimmed. The panel");
  ("every other g screen puts up is a see-through wash, because those panels interrupt a game");
  ("the player is already inside and the world showing through is what says the game is still");
  ("there. This one is not an interruption; it is the door. A street and a crowd and a row of");
  ("arrows glowing faintly through the prayer would be the game asking to be played while the");
  ("player is being asked to pray, and the prayer would lose - so the first thing on the");
  ("screen is the player's own words and nothing else at all.");
  ("The prayer stands in the MIDDLE of the screen, and that is not decoration. Covered over");
  ("solid, everything the door does not use is one flat colour - so a prayer sitting along the");
  ("top edge leaves a whole screen of blank underneath it, and a page that is blank below a");
  ("thin band is what a page that failed to load looks like. Somebody who reads it that way");
  ("closes the tab before praying anything, which is the one outcome praying at the door was");
  ("meant to prevent. In the middle, the same emptiness reads as room around the words.");
  ("It is centred with automatic margins above and below rather than by asking the column to");
  ("justify its contents, because those two agree until the words are taller than the screen");
  ("and then part company: a justified column pushes its overflow off the top edge, where the");
  ("overlay's own scrolling cannot reach it. Automatic margins collapse to nothing instead, so");
  ("a long prayer on a short phone starts at the top and scrolls, which is what it should do.");
  ("The flat colour is BLACK, and not the off-white every other page in the family sits on.");
  ("Off-white is the colour of a page - a document with something written on it, which is");
  ("what the reading apps are and what this screen is not. Black is the colour of nothing");
  ("else being there. It takes away not only the game behind the prayer but the page around");
  ("it, so the only lit thing on the phone is the words the player is about to say.");
  ("It also marks the threshold in the one way a player cannot miss. The street is bright;");
  ("the door is dark; stepping through is a visible change of place rather than a panel");
  ("being taken down. And a game that is often opened at night opens gently instead of");
  ("filling the screen with white.");
  html_style_background_color_black(overlay);
  html_flex_column_stretch(overlay);
  let container = app_shared_game_container_player(overlay);
  html_style_margin_y(container, "auto");
  ("The amen is not there when the door opens and arrives a moment later, timed from the");
  ("length of the words - the same rule every prayer in this game is under, met here first");
  ("because this is the screen that teaches it. A door that opens the instant it is touched");
  ("teaches that amen is the way in, and the waiting on every prayer after it then reads as");
  ("the game being slow. Learned here, the waiting is simply how praying works, and nothing");
  ("later has to argue for it.");
  ("It is also the prayer that most deserves it. Everything prayed in this game is real to");
  ("real people only because this one was said, so it is the single worst prayer to let a");
  ("player click past without reading.");
  ("Praying hands stand in front of the words and the world stands behind them. On a black");
  ("screen holding one paragraph and nothing else, they are the only thing that is not");
  ("text - and between them they say the whole of what the door is for to somebody who has");
  ("not read a word yet.");
  ("The screen prints the shown form and times its amen from the bare prayer, so the two");
  ("pictures are not counted as words the player has to get through.");
  let prayer = bless_prayer_transfer();
  let shown = bless_prayer_transfer_shown(prayer);
  app_shared_game_p_text(container, shown);
  app_g_bless_amen(container, prayer, on_amen);
}
