import { arguments_assert } from "./arguments_assert.mjs";
import { list_first } from "./list_first.mjs";
import { list_size } from "./list_size.mjs";
import { math_max } from "./math_max.mjs";
import { math_min } from "./math_min.mjs";
import { property_get } from "./property_get.mjs";
import { subtract } from "./subtract.mjs";
import { bless_street } from "./bless_street.mjs";
import { app_g_bless_street_length } from "./app_g_bless_street_length.mjs";
export function app_g_bless_street(rows, player) {
  arguments_assert(arguments, 2);
  ("The one street laid into the world so far - a run of path going east, three tiles north");
  ("of wherever the player is first set down.");
  ("Its length is not decoration. A cone three tiles deep is exactly that many tiles wide at");
  ("its far edge, so standing where you began and facing north puts the whole street in");
  ("sight and nothing else does. The place rung is therefore reachable, and reachable only");
  ("by aiming, which is the thing the rung is meant to cost.");
  ("Placed against the player rather than against the world's corner, because the world is");
  ("generated now and the player is set down somewhere different every time. A street at a");
  ("fixed corner would be a street most players never find.");
  ("Kept inside the world, which is why the rows are asked for. A player set down near an");
  ("edge would otherwise be given a street running off the map: those tiles are written");
  ("nowhere and drawn as nothing, so the game would announce a whole street in sight while");
  ("part of it was never on the screen. Nudged in, the street is a step or two off instead");
  ("of exactly in front - and a place you have to walk a little to see is the rung working,");
  ("not the rung broken.");
  let x = property_get(player, "x");
  let y = property_get(player, "y");
  let length = app_g_bless_street_length();
  let row_first = list_first(rows);
  let width = list_size(row_first);
  let height = list_size(rows);
  let last_x = subtract(width, length);
  let last_y = subtract(height, 1);
  let wanted_x = subtract(x, 3);
  let wanted_y = subtract(y, 3);
  let inside_x = math_max(0, math_min(wanted_x, last_x));
  let inside_y = math_max(0, math_min(wanted_y, last_y));
  let street = bless_street(inside_x, inside_y, "east", length);
  return street;
}
