import { arguments_assert } from "./arguments_assert.mjs";
import { fn_name } from "./fn_name.mjs";
import { color_oklch } from "./color_oklch.mjs";
export function app_code_lesson_chip_colors() {
  arguments_assert(arguments, 0);
  ("the categorical chip colours - a red, a green, a blue and an amber - hand-picked to be as distinct and familiar as possible, NOT an even-hue formula, so a learner tells one number from another at a glance");
  ("THE WHOLE LIST IS ANSWERED RATHER THAN ONE OF THEM, SO THAT WHATEVER COUNTS THEM CANNOT DISAGREE WITH WHATEVER USES THEM. A gate checking this palette has to know how many there are; told four, it would go on checking four the day a fifth arrived, and would pass while saying nothing at all about the colour that was actually added. Asked for the list, it checks whatever is here.");
  ("They are spelled together because nothing outside asks for one of them by itself. The amber was lifted out under its own name for a while, when the second of the colours that point at a piece of code was taken from this list; that pointer is a green of its own now and the name went back where it came from. Lift one out again the moment a second reader wants exactly one of these - never by its place in the list, because the order these happen to be written in is not a name for what sits there.");
  "FIVE THINGS ARE KNOWN TO BE WRONG HERE AND ARE ALL LEFT STANDING ON PURPOSE, BECAUSE EVERY FIX IS A JUDGMENT ABOUT COLOUR AND NOBODY WHO HAS WORKED IN COLOUR HAS LOOKED AT THEM YET. Measured 2026-09-19 and 2026-09-20, and written down so whoever does look arrives holding the numbers rather than having to find them again. None of them is a reason to change anything today; every one of them is a reason not to let the palette change quietly while the question waits, which is what " +
    fn_name("app_code_lesson_chip_color_gate_run") +
    " is for.";
  ("THREE OF THE FIVE ARE THE AMBER, WHICH IS THE FINDING AND NOT A COINCIDENCE. It is the lightest member by a clear margin - the red and the blue sit at 0.500, the green at 0.510 and the amber at 0.580 - and every one of its faults is a shortfall of contrast that a darker amber would clear at once. The whole of what is wrong with it is that one number being 0.08 above the others. So a reader arriving at this list should not read those three as three separate problems: there is one weak member, and the question waiting for someone is what to do about it.");
  ("The amber is short in all three of the ways a chip colour is drawn. As the ground under the white lettering of a number chip it measures 4.48 where lettering needs 4.5 - barely short, but short. As coloured lettering itself on the pale blue card it measures 3.91 against that same 4.5. And the light ring that lifts a chip off a black code tile measures 2.98 against it where a shape needs 3, so on amber alone that ring nearly disappears. Pulling the amber darker clears all three together; it also changes a colour somebody chose by looking, which is the part that is not arithmetic.");
  ("The fourth is not about contrast at all. A reader with no green cone, about one man in twelve, sees hue collapse onto a single blue-yellow line, and the red at 25 lands on that line beside the amber at 56. As a distance in the perceptual space that pair stands at 0.070, against 0.135 for the same pair to a normal eye and 0.15 or better for every other pair here. So the dot grid, whose whole promise is that the eye can follow any single row, hands that reader two colours where it says four.");
  ("The fifth is the worst number anywhere in the palette and was found only by refusing to decide in advance whose eyes count. To a reader with no BLUE cone the green at 150 and the blue at 255 stand at 0.011 apart - not hard to tell apart, but the same colour, well under the 0.02 where two colours stop being reliably distinguishable side by side at all. That is a rarer way to see than the missing green cone, perhaps one person in ten thousand, and it is the only reading here that fails completely rather than narrowly. It was missed on the first pass because only the common cases were simulated, which is the whole lesson: the pair that collapsed was the one nobody had asked about.");
  ("Three readings are already ruled out, so nobody need spend them again. Hues spread evenly were tried and revised away as not distinct enough, so an even formula is a rejected answer rather than an unconsidered one. Moving the red round to 345 nearly doubles the worst pair, to 0.186 - but 345 renders as a magenta and the course loses a red. And keeping the red while making the FOURTH colour a magenta measures 0.032, worse than changing nothing at all, because a magenta lands on top of the blue for that same reader. True red, amber, green and blue cannot all be told apart on that one line; one of the red and the amber has to leave, and only the red has anywhere to go.");
  ("THERE IS A SECOND SET OF COLOURS IN THIS APP AND IT IS NOT A COPY OF THIS ONE, WHICH TOOK TWO MEASUREMENTS TO ESTABLISH AND IS WRITTEN DOWN SO NOBODY ESTABLISHES IT A THIRD TIME. The three pointing colours, led by ",
    fn_name("app_code_highlight_color"),
    ", sit on a black code line where these sit on a pale card, and the one thing the two sets genuinely share is a step in lightness: every pointer lands at about 0.55 and every colour here at about 0.50. Lighter to stand off black, darker to stand off a pale card, arrived at separately on both sides and agreeing.");
  ("Beyond that step they are three different stories. The pointing green is this green and nothing else - same hue at 150, same chroma at 0.15, lightness 0.55 against 0.51 - and at 0.043 apart it is a near miss of the kind this app forbids. The pointing red moved its hue as well, 15 against 25, because it had to be plainly warm and well clear of that green. The pointing blue is not a chosen colour at all but the brand blue the whole site leads with, at chroma 0.215 and hue 262.9 against 0.15 and 255 here, so its numbers were never a palette decision to begin with. One hue list at two lightnesses would therefore serve the green, bend the red and break the blue, which is why these are two sets and not one.");
  ("WHAT THESE COLOURS ACTUALLY DO WAS READ OFF THE CALLERS ON 2026-09-20, BECAUSE THE FAULTS ABOVE WERE BEING PRICED AGAINST A GUESS. Almost every one of them is a tile carrying white lettering, on one of two grounds - the pale card or the black code line - and not a font colour at all; the pointing colours are the same, since both of the things that wear one set a background and write white on it. Coloured lettering is real but rare, and there are three places: the phrase naming the first digit after the decimal point, the word remainder where a lesson says what that word means, and the last of the running counts. Those three are what make the 4.5 lettering floor bite here at all. Anyone repricing this palette should check that list again rather than assume it, because every window below moves if it changes.");
  ("THE FOUR JOBS ARE FOUR WINDOWS IN LUMINANCE, AND WRITING THEM AS WINDOWS IS WHAT MAKES THE CHOICE VISIBLE. To letter the pale card at 4.5 a colour must stay at or under 0.1536. To be a tile on the card under white lettering it must stay at or under 0.1833. To be a tile on the black code line and still read as a shape at 3 it must reach 0.1000. And to letter that black line at 4.5 - which nothing here does today - it would have to reach 0.1750. The first and the last cannot both be met by one colour, ever: 0.1536 is below 0.1750 and the gap is 0.0214. The app escapes that only by never writing a coloured word on black, putting a tile there instead, which is exactly what the lift ring is paying for.");
  ("SO EVERY COLOUR HERE IS SERVING BOTH GROUNDS AT ONCE AND LIVING IN A BAND 0.054 TALL - between 0.1000 and 0.1536 - WHICH IS THE ONE FINDING THE AMBER FAULTS ARE THREE FACES OF. The red sits at 0.1079 and nearly falls out of the dark end, the blue at 0.1229, the green at 0.1443 near the light end, and the amber at 0.1843 is outside altogether. Read that way nothing is wrong with the amber as a colour: it is a light-ground value standing in a set that has to letter a pale card.");
  ("GIVING EACH HUE TWO TONES, ONE PER GROUND, IS THEREFORE A REAL PROPOSAL AND NOT A WASTEFUL ONE, AND IT IS WRITTEN DOWN HERE BECAUSE IT DISSOLVES THREE OF THE FIVE FAULTS RATHER THAN PATCHING ONE. A dark tone owes nothing to the black line, so it loses the 0.1000 floor entirely and may go as dark as the hue stays itself; the 0.054 band stops existing for it. A light tone gets 0.1000 to 0.1833 to itself. The amber then keeps the value somebody chose, on black, while a darker amber letters the card. The two greens stop being 0.043 apart by accident and become a step on purpose. And the lift ring becomes a choice instead of a rescue. What it costs is eight colours to hold apart instead of four, checked on two grounds, with the cone-blindness pairs measured in both sets - so the green and blue collapsing to 0.011 for a missing blue cone is a reading to take twice, not once. Whether the tones are worth that, and what they should be, is still the colour judgment everything here is waiting on.");
  ("One argument against eight is worth recording because it is true and answers a different question. Asked whether the split should be four backgrounds and four font colours, the arithmetic says no: the contrast a colour reaches under white lettering, divided by the contrast the same colour reaches as lettering on the pale card, is 1.1460 for every one of these four, because that figure is 1.05 over the card's own luminance plus 0.05 and the colour cancels clean out of it. Those two jobs are one constraint wearing two numbers, both wanting the colour darker. The split that pays is by GROUND, not by whether the colour is behind the text or is the text.");
  ("THAT LAST SENTENCE IS WRONG AND THE BETTER READING IS BY TONE, WHICH THIS PALETTE AND THE POINTING ONE SETTLE BETWEEN THEM. Measured 2026-09-20: these four stand at 0.500, 0.500, 0.509 and 0.580 of lightness and the three pointing colours at 0.546, 0.549 and 0.551 - one band. They share a ground as well, so ground is not what keeps them two lists; nothing does. What genuinely divides a colour here from a colour there is whether it carries white lettering or near-black lettering, and that is a question about the colour itself rather than about where it is put. Read by tone the app holds two tones and not three, with the dark one written down twice, and the argument above survives as what it really was: a reason the two jobs WITHIN this tone do not need splitting.");
  "The whole of that reading, the four ways a colour is drawn and the four things standing between the app and one hue list at two tones, is in " +
    fn_name("app_code_color_tones") +
    " rather than here, because it is about all three palettes and this is one of them. Everything above about the amber, the cone-blindness pairs and the rejected hues stays true and stays the reason this list is what it is.";
  ("The written chroma of the amber and the green asks for more colourfulness than sRGB can show, 0.16 and 0.15 against the 0.1413 and 0.1405 that actually appear. That is not a sixth fault: the squashed colour is the one that was looked at and approved. Rewriting the numbers to what shows would be honest and would render identically here, and it is left alone anyway, so that the person who revises these is revising the numbers that were revised before.");
  let red = color_oklch(0.5, 0.2, 25);
  let green = color_oklch(0.51, 0.15, 150);
  let blue = color_oklch(0.5, 0.15, 255);
  let amber = color_oklch(0.58, 0.16, 56.38);
  let colors = [red, green, blue, amber];
  return colors;
}
