export function bible_glyph_language_written_mark() {
  "The sentence every generated reveal-language file carries, by which such a file can be told from one somebody wrote.";
  "IT IS HERE SO THAT THE WRITER AND THE GATE CANNOT DISAGREE. The writer stamps it into each file it produces and the gate finds those files by looking for it, which is two places spelling one sentence - and a sentence spelled twice drifts silently, because the file still parses, the gate still runs, and it simply finds nothing to check.";
  "FINDING THEM BY THIS MARK IS WHY THERE IS NO LIST. A hand-kept list of which languages have been written is exactly the thing that went wrong next door: twelve Rosetta chapters were on disk, the list named three, nothing threw and nothing went red, and the only symptom was a reader being shown less than the repo held. A file that announces what it is cannot fall off a list nobody remembered to add it to.";
  "THE FINDER HAS TO LEAVE THIS ONE OUT AND IT LEAVES IT OUT BY NAME. Holding the sentence is what the search looks for, so the function that holds it for safekeeping matches the search as surely as a generated file does - and it is the only such function, because nowhere else spells the sentence at all. Excluding it by name rather than by where it sits means a rename carries the exclusion with it.";
  "IT SAYS NOTHING ABOUT WHOSE TEXT IT IS, AND IT USED TO. This sentence read 'It is a public-domain bible' for as long as there were files carrying it, and that was never true of either of them: both were fetched from translations offered under Creative Commons Attribution Share-Alike, which is a licence with an attribution condition rather than no licence at all. A claim spelled once for every language is a claim nobody checked against any language, and the terms are a property of the translation that was fetched - so they are read off that translation now and stamped beside this, and this says only the thing that is true of every generated file whatever it was fetched from.";
  "CHANGING THIS SENTENCE ORPHANS EVERY FILE ALREADY CARRYING THE OLD ONE, because the finder matches on it exactly. Whoever edits it has to run the writer again for every language in the same breath, and then ask the finder what it can see - a file that has fallen out of its answer is invisible rather than broken, which is the failure this whole arrangement was built to make impossible.";
  let mark =
    "THIS FILE IS WRITTEN BY A COMMAND AND NOT BY HAND. It is one translation read once, at authoring time, for the chapters the pictures have reached.";
  return mark;
}
