export function bible_glyph_chapter_lev13() {
  "The thirteenth chapter of Leviticus, drawn in pictures. Fifty nine verses of one procedure, run over and over on skin, on hair, on a burn, on a bald head, and at the end on a piece of cloth. It is the longest chapter in the book and the least like a story.";
  "GOD IS NAMED ONCE, IN VERSE ONE, AND NEVER AGAIN. The name of the LORD is used a single time in the whole chapter, and Moses is named once with it. After that opening line nobody speaks and nothing is prayed. What is left is a method.";
  "THE PRIEST IS NAMED FIFTY SIX TIMES, IN FORTY OF THE FIFTY NINE VERSES. No other chapter drawn here leans on one person like this. He is the subject of almost every sentence, and the picture for priest is on nearly every line of the page.";
  "WHAT THE PRIEST DOES IS LOOK, AND THE WORD FOR IT IS USED THIRTY TWO TIMES. He examines, he looks again on the seventh day, he looks after the washing. The word for healing appears twice in the whole chapter, and never as something the priest does. He is not a doctor here. He is a witness.";
  "THREE WORDS CARRY THE THING BEING LOOKED AT. The word for the mark is used forty seven times, the word for skin forty six, and the word for flesh seventeen. The chapter has almost no other nouns, and it repeats these three until they stop sounding like words.";
  "WHITE IS SAID TWENTY TIMES, AND WHEN THE COLOUR IS NOT ENOUGH THE ANSWER IS SEVEN DAYS. The verb for shutting someone away is used nine times. Every one of those is a case the priest could not settle by looking once, so the rule is to wait and look again. Not knowing is given a procedure of its own.";
  "THE LAST THIRTEEN VERSES RUN THE WHOLE PROCEDURE ON A PIECE OF CLOTH. The word for garment is used fourteen times, and from verse forty seven the same verbs come back: look, shut away seven days, look again, wash, look again, burn. A chapter about a body ends by treating wool and linen exactly the same way.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV13",
    reference: "Leviticus 13",
    verses: [
      {
        verse_number: 1,
        words: ["$mouth", "$name_tag", "to", "Moses", "and Aaron,", "$speech"],
      },
      {
        verse_number: 2,
        words: [
          "$person",
          "When",
          "has",
          "on his skin",
          "$meat",
          "a swelling",
          "or",
          "rash",
          "or",
          "bright spot",
          "that may be",
          "skin",
          "$meat",
          "disease",
          "an infectious,",
          "$footprints",
          "to",
          "Aaron",
          "$priest",
          "or",
          "to",
          "one",
          "$son",
          "$priest.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$eye",
          "$priest",
          "the infection",
          "on his skin,",
          "$meat",
          "$hair",
          "in the infection",
          "has turned",
          "white",
          "appears",
          "and the sore",
          "to be deeper",
          "than the skin,",
          "$meat",
          "is a skin disease",
          "it.",
          "$eye",
          "$priest",
          "he must pronounce him unclean.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "If, however",
          "the spot",
          "is white",
          "on his skin,",
          "$meat",
          "to be deeper",
          "and does not",
          "appear",
          "$tray_out",
          "the skin,",
          "$hair",
          "$no_entry",
          "turned",
          "white,",
          "shall isolate",
          "$priest",
          "the infected person",
          "for seven",
          "$sun.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$eye",
          "$priest",
          "$sun",
          "On the seventh,",
          "and if",
          "that the infection",
          "is unchanged",
          "$eyes",
          "$no_entry",
          "spread",
          "on the skin,",
          "must isolate him",
          "$priest",
          "seven",
          "$sun",
          "for another.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$eye",
          "$priest",
          "$sun",
          "on the seventh",
          "again,",
          "and if",
          "has faded",
          "the sore",
          "$no_entry",
          "spread",
          "on the skin,",
          "shall pronounce him clean",
          "$priest",
          "is a rash",
          "it.",
          "The person must wash",
          "$garment",
          "and be clean.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "But if",
          "spreads further",
          "the rash",
          "on his skin",
          "after",
          "$eye",
          "to",
          "$priest",
          "for his cleansing,",
          "$eye",
          "again",
          "to",
          "$priest.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "has spread",
          "the rash",
          "on the skin,",
          "must pronounce him unclean",
          "$priest.",
          "is a skin disease",
          "it.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "a skin disease",
          "When",
          "develops",
          "$person,",
          "$footprints",
          "to",
          "$priest.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "swelling",
          "there is a white",
          "on the skin",
          "that",
          "has turned",
          "$hair",
          "white,",
          "$meat",
          "$sprout",
          "in the swelling,",
        ],
      },
      {
        verse_number: 11,
        words: [
          "skin disease",
          "is a chronic",
          "it,",
          "$meat",
          "must pronounce him unclean",
          "$priest.",
          "$no_entry",
          "isolate him,",
          "for",
          "is unclean",
          "he.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "But if",
          "breaks out",
          "the skin disease",
          "all over his skin",
          "covers",
          "so that it",
          "all",
          "the skin",
          "of the infected person",
          "from head",
          "to",
          "$foot,",
          "can see",
          "$eyes",
          "$priest,",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "has covered",
          "the disease",
          "his entire",
          "$meat,",
          "clean",
          "he is to pronounce the infected person.",
          "Since it has all turned",
          "white,",
          "is clean",
          "he.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "$sun",
          "$eye",
          "on someone,",
          "$meat",
          "$sprout,",
          "he will be unclean.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "$eye",
          "$priest",
          "$meat",
          "$sprout,",
          "he must pronounce him unclean.",
          "$meat",
          "$sprout",
          "is unclean",
          "it;",
          "is a skin disease.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "But",
          "if",
          "$turn_back",
          "$meat",
          "$sprout",
          "and turns",
          "white,",
          "$footprints",
          "to",
          "$priest.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "has turned",
          "the infection",
          "white,",
          "clean",
          "$priest",
          "is to pronounce the infected person;",
          "is clean",
          "then he.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "$meat",
          "When",
          "appears",
          "on the skin of someone",
          "a boil",
          "and it heals,",
        ],
      },
      {
        verse_number: 19,
        words: [
          "develops",
          "$place",
          "the boil was",
          "swelling",
          "and a white",
          "or",
          "spot",
          "a reddish-white,",
          "$eye",
          "to",
          "$priest.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "it appears",
          "to be beneath",
          "$tray_out",
          "the skin",
          "$hair",
          "has turned",
          "white,",
          "shall pronounce him unclean",
          "$priest.",
          "is a diseased infection",
          "it",
          "in the boil",
          "that has broken out.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "But when",
          "$eye",
          "$priest,",
          "if",
          "there is no",
          "in it",
          "$hair",
          "white,",
          "beneath",
          "and it is not",
          "$tray_out",
          "the skin",
          "and has faded,",
          "shall isolate him",
          "$priest",
          "for seven",
          "$sun.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "If",
          "it spreads any further",
          "on the skin,",
          "must pronounce him unclean",
          "$priest.",
          "is an infection",
          "it.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "But if",
          "unchanged",
          "remains",
          "the spot",
          "$no_entry",
          "spread,",
          "is only the scar",
          "from the boil",
          "it,",
          "shall pronounce him clean",
          "$priest.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "$meat",
          "When",
          "there is",
          "on the skin of someone",
          "a burn,",
          "becomes",
          "and the raw",
          "area of the burn",
          "reddish-white",
          "or",
          "white,",
        ],
      },
      {
        verse_number: 25,
        words: [
          "$eye",
          "$priest.",
          "If",
          "has turned",
          "$hair",
          "white",
          "in the spot,",
          "and the spot appears",
          "to be deeper",
          "$tray_out",
          "the skin,",
          "is a disease",
          "it",
          "in the burn",
          "that has broken out.",
          "must pronounce him unclean",
          "$priest;",
          "is a diseased infection",
          "it.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "But if",
          "$eye",
          "$priest",
          "and there is",
          "no",
          "in the spot",
          "$hair",
          "white,",
          "beneath",
          "and it is not",
          "$tray_out",
          "the skin",
          "but has faded,",
          "shall isolate him",
          "$priest",
          "for seven",
          "$sun.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "$eye",
          "$priest",
          "$sun",
          "On the seventh,",
          "and if",
          "it has spread further",
          "on the skin,",
          "must pronounce him unclean",
          "$priest.",
          "is a diseased infection",
          "it.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "But if",
          "is unchanged",
          "the spot",
          "$no_entry",
          "spread",
          "on the skin",
          "it,",
          "but has faded,",
          "is a swelling",
          "from the burn",
          "it,",
          "is to pronounce him clean",
          "$priest,",
          "for",
          "is only the scar",
          "from the burn.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "$man_beard",
          "or",
          "$woman,",
          "If",
          "has",
          "an infection",
          "on the head",
          "or",
          "$beard,",
        ],
      },
      {
        verse_number: 30,
        words: [
          "$eye",
          "$priest",
          "the infection,",
          "and if",
          "it appears",
          "to be deeper",
          "$tray_out",
          "the skin,",
          "and",
          "$hair",
          "is yellow",
          "and thin,",
          "must pronounce him unclean",
          "$priest.",
          "is a scaly outbreak",
          "it,",
          "an infectious disease",
          "of the head",
          "or",
          "$beard.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "But if",
          "$eye",
          "$priest",
          "infection",
          "the scaly,",
          "and",
          "it does not",
          "appear",
          "to be deeper",
          "$tray_out",
          "the skin,",
          "$hair",
          "black",
          "and there is no",
          "in it,",
          "shall isolate",
          "$priest",
          "the infected person",
          "for seven",
          "$sun.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "$eye",
          "$priest",
          "the infection",
          "$sun",
          "On the seventh,",
          "and if",
          "$no_entry",
          "spread",
          "the scaly outbreak",
          "$no_entry",
          "and there is",
          "in it",
          "$hair",
          "yellow,",
          "appear",
          "and it",
          "does not",
          "to be deeper",
          "$tray_out",
          "the skin,",
        ],
      },
      {
        verse_number: 33,
        words: [
          "then the person must shave himself",
          "except for",
          "the scaly area,",
          "$no_entry",
          "shall isolate",
          "$priest",
          "him",
          "seven",
          "$sun",
          "for another.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "$eye",
          "$priest",
          "the scaly outbreak",
          "$sun",
          "On the seventh,",
          "and if",
          "$no_entry",
          "spread",
          "it",
          "on the skin",
          "appear to be",
          "and does not",
          "deeper",
          "$tray_out",
          "the skin,",
          "is to pronounce him clean",
          "$priest.",
          "He must wash",
          "$garment",
          "and he will be clean.",
        ],
      },
      {
        verse_number: 35,
        words: [
          "If, however",
          "spreads further",
          "the scaly outbreak",
          "on the skin",
          "after",
          "his cleansing,",
        ],
      },
      {
        verse_number: 36,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "has spread",
          "the scaly outbreak",
          "on the skin,",
          "$no_entry",
          "look for",
          "$priest",
          "$hair",
          "yellow;",
          "is unclean",
          "the person.",
        ],
      },
      {
        verse_number: 37,
        words: [
          "If, however",
          "$eyes",
          "is unchanged",
          "the scaly outbreak",
          "$hair",
          "and black",
          "has grown",
          "in it,",
          "has healed",
          "then it;",
          "is clean",
          "he,",
          "is to pronounce him clean",
          "$priest.",
        ],
      },
      {
        verse_number: 38,
        words: [
          "$man_beard",
          "or",
          "$woman,",
          "When",
          "on the skin",
          "$meat",
          "spots",
          "has white,",
        ],
      },
      {
        verse_number: 39,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "$meat",
          "the spots",
          "are dull",
          "white,",
          "is a harmless rash",
          "it",
          "that has broken out",
          "on the skin;",
          "is clean",
          "the person.",
        ],
      },
      {
        verse_number: 40,
        words: [
          "$man_beard",
          "Now if",
          "loses his hair",
          "and is bald,",
          "clean",
          "he is still.",
        ],
      },
      {
        verse_number: 41,
        words: [
          "Or if",
          "his hairline",
          "recedes",
          "and is bald on his forehead,",
          "and he",
          "clean",
          "he is still.",
        ],
      },
      {
        verse_number: 42,
        words: [
          "But if",
          "there is",
          "on the bald head",
          "or",
          "forehead",
          "sore",
          "a reddish-white,",
          "is an infectious disease",
          "breaking out",
          "it",
          "on it.",
        ],
      },
      {
        verse_number: 43,
        words: [
          "$eye",
          "$priest,",
          "and if",
          "the swelling",
          "of the infection",
          "is reddish-white",
          "on his bald head",
          "or",
          "forehead,",
          "like",
          "disease",
          "a skin,",
          "$meat",
        ],
      },
      {
        verse_number: 44,
        words: [
          "$man_beard",
          "is diseased",
          "he,",
          "is unclean,",
          "must pronounce him unclean",
          "$priest",
          "on his head",
          "because of the infection.",
        ],
      },
      {
        verse_number: 45,
        words: [
          "A diseased person",
          "$garment,",
          "and let his hair",
          "hang loose,",
          "his mouth",
          "and he must cover,",
          "Unclean,",
          "unclean,",
          "and cry out.",
        ],
      },
      {
        verse_number: 46,
        words: [
          "As",
          "$sun",
          "he has the infection",
          "he remains",
          "unclean.",
          "He must live alone,",
          "outside",
          "$camp",
          "in a place.",
        ],
      },
      {
        verse_number: 47,
        words: [
          "$garment",
          "If",
          "is",
          "contaminated",
          "with mildew,",
          "$garment",
          "any wool",
          "or",
          "$garment",
          "linen,",
        ],
      },
      {
        verse_number: 48,
        words: [
          "any weave",
          "or",
          "knit",
          "of linen",
          "or wool,",
          "or",
          "any article of leather,",
          "$tools",
        ],
      },
      {
        verse_number: 49,
        words: [
          "is",
          "and if the mark",
          "green",
          "or",
          "red",
          "$garment,",
          "leather,",
          "weave,",
          "knit,",
          "or",
          "article",
          "leather,",
          "contaminated",
          "with mildew",
          "then it is,",
          "$eye",
          "$priest.",
        ],
      },
      {
        verse_number: 50,
        words: [
          "$eye",
          "$priest",
          "the mildew",
          "and isolate",
          "the contaminated fabric",
          "for seven",
          "$sun.",
        ],
      },
      {
        verse_number: 51,
        words: [
          "$eye",
          "it",
          "the mildew",
          "$sun",
          "On the seventh,",
          "and if",
          "has spread",
          "$garment",
          "or",
          "weave",
          "knit",
          "leather,",
          "then regardless of",
          "how",
          "$hammer",
          "it,",
          "$tools",
          "mildew",
          "is a harmful,",
          "is unclean",
          "the article.",
        ],
      },
      {
        verse_number: 52,
        words: [
          "He is to burn",
          "$garment,",
          "whether",
          "weave",
          "or",
          "knit,",
          "wool",
          "or",
          "or linen,",
          "leather,",
          "the contaminated item is.",
          "Since",
          "the mildew",
          "is harmful,",
          "the article",
          "must be burned up.",
        ],
      },
      {
        verse_number: 53,
        words: [
          "But when",
          "$eye",
          "$priest,",
          "if",
          "$no_entry",
          "spread",
          "the mildew",
          "$garment,",
          "weave",
          "or",
          "knit,",
          "article",
          "leather,",
        ],
      },
      {
        verse_number: 54,
        words: [
          "is to order",
          "$priest",
          "to be washed",
          "the contaminated article,",
          "and isolated",
          "seven",
          "$sun",
          "for another.",
        ],
      },
      {
        verse_number: 55,
        words: [
          "$eye",
          "$priest",
          "After",
          "it has been washed",
          "the mildewed,",
          "and if",
          "$no_entry",
          "changed",
          "article",
          "$eyes,",
          "Even though the mildew",
          "$no_entry",
          "spread,",
          "is unclean",
          "it;",
          "you must burn it,",
          "the rot is",
          "whether",
          "back",
          "or",
          "on the front.",
        ],
      },
      {
        verse_number: 56,
        words: [
          "If",
          "$eye",
          "$priest,",
          "has faded",
          "and the mildew",
          "after",
          "it has been washed,",
          "he must cut the contaminated section out",
          "$tray_out",
          "$garment",
          "$tray_out",
          "leather",
          "or",
          "$tray_out",
          "weave",
          "$tray_out",
          "knit.",
        ],
      },
      {
        verse_number: 57,
        words: [
          "But if",
          "$eye",
          "$garment",
          "or",
          "weave",
          "or",
          "knit,",
          "on any",
          "article",
          "leather,",
          "is spreading",
          "it.",
          "You must burn",
          "article",
          "the contaminated.",
        ],
      },
      {
        verse_number: 58,
        words: [
          "$garment",
          "or",
          "weave",
          "or",
          "knit,",
          "any",
          "article",
          "leather,",
          "after",
          "washing",
          "disappears",
          "from,",
          "If the mildew",
          "then it is to be washed",
          "again",
          "and it will be clean.",
        ],
      },
      {
        verse_number: 59,
        words: [
          "This",
          "$scroll",
          "contamination",
          "concerning a mildew",
          "$garment",
          "in wool",
          "or",
          "linen,",
          "weave",
          "or",
          "knit,",
          "or",
          "any",
          "article",
          "leather,",
          "for pronouncing it clean",
          "or",
          "unclean.",
        ],
      },
    ],
  };
  return chapter;
}
