import { ebible_folder_korean } from "./ebible_folder_korean.mjs";
import { bible_interlinear_verses_upload_folder } from "./bible_interlinear_verses_upload_folder.mjs";
export function bible_folders_sentence_end_unmarked() {
  "The bibles whose sentences cannot be told apart by what they end on, so nothing may wait for one of them to finish.";
  "Every other bible this repo ships writes a mark where a sentence stops, and the ones it writes are gathered next door. These write nothing there. So a reading that asks whether this verse finished a sentence is asking a question its text has no way of answering, and the honest answer is that it cannot be asked rather than no.";
  "That distinction is the whole reason this list exists apart from the marks. Answered as no, a page looking for the end of a sentence would keep reaching for one more verse until whatever bound it holds ran out, every single time. Named here, the bible simply takes no part in the question, and a reader of it gets the verses they asked for and nothing added.";
  "The interlinear is here for a different reason and by the same rule. It is not a translation into a language that lost its punctuation; it is the Greek and Hebrew as they were written, and they were written without any. So a verse of it ends on a letter, always, and a page waiting for it to finish a sentence would wait until whatever bound it holds ran out.";
  "Measured rather than assumed, and by a command rather than by hand: what each of these ends on is written down beside them, and a bible added to the list without being measured turns a gate red. The first hand measurement got this wrong in both directions - it read Urdu under a folder name that does not exist and so filed a language that does mark its sentences as one that does not, and it never read the interlinear at all.";
  "KOREAN JOINED ON 2026-08-20 AND IT IS THE FIRST ONE HERE THAT COULD HAVE MARKED ITS SENTENCES AND DOES NOT. Thai had no full stop to write and the interlinear was written before anyone wrote one. Korean has the same full stop English has, and this edition simply carries none: sixteen verses of Luke 1 end on sixteen Korean syllables and not one mark of punctuation appears anywhere in them.";
  "THE ENDING IT WRITES INSTEAD IS GRAMMAR, WHICH IS EXACTLY WHY IT CANNOT BE USED HERE. Korean closes a statement with a syllable, and its verses do end on those - so a reader who knows the language can see where the sentences stop. That is not a mark, and the same syllables also fall in the middle of a sentence, so naming one of them next door would end sentences that had not ended. A language whose sentence ends are real and unfindable belongs on this list just as squarely as one that has none.";
  "THAI LEFT ON 2026-08-20 BECAUSE THE BIBLE LEFT, and not because it started marking its sentences. It was dropped from the languages on 2026-08-19 on its licence: the indexes call the Thai King James public domain by inheritance, the translator's own page says Creative Commons Attribution-Noncommercial-No Derivatives, and the translator's terms are the ones that bind. That is written up whole in the sources note. Its name stayed here a day longer than the bible did, which is how a gate came to be refusing a word about nobody's reading.";
  "SO A NAME HERE THAT NAMES NO SHIPPED BIBLE IS USUALLY A LICENCE, and that is the first place to look rather than the last. This list is the second referrer to a bible folder after the language roster, so it is what still points at a translation after the roster has let go of one - and a translation gets let go of for its terms far more often than for anything else.";
  let original = bible_interlinear_verses_upload_folder();
  let korean = ebible_folder_korean();
  let bible_folders = [original, korean];
  return bible_folders;
}
