export function bible_verse_end_suffixes() {
  "The marks a finished sentence ends on, gathered from every language this repo ships a bible in rather than from the one this was first written for.";
  "It began as the three an English sentence ends on, which was right while the only reader of it was working through an English bible. A page that has to stop on a finished sentence in whatever languages a reader chose cannot use that set: a language whose sentences end on something else has no sentence that ever ends, so the page keeps reaching for one more verse and never finds it.";
  "The rest were measured rather than guessed. On 2026-08-12 the first sixteen verses of Luke 1 were read in all thirty-nine bibles this repo lists, and what each verse ended on was counted. Four marks did the work of a full stop and nothing else did: the one Latin script writes, the upright bar of Hindi, Bengali, Punjabi and Oriya, the round stop of Chinese, and the two dots of Amharic. Chinese also asks and exclaims with wider twins of the two Latin marks, so those are here beside them.";
  "Marks that only look like an ending are deliberately out. Amharic's own colon and semicolon end a clause rather than a sentence, and Arabic's comma leans the other way from the Latin one - each of those would have cut a sentence in half every time it appeared.";
  "One language ends on nothing at all. Thai writes a space where other languages write a stop, so no mark in any set could find the end of one of its sentences - which is why the folders that cannot be read this way are named separately rather than pretended about here.";
  "Urdu's full stop was added afterwards and is worth the sentence it takes. That first measurement was done by hand and it read Urdu under a folder name that did not exist, so every verse of it came back as nothing and Urdu was written down as a language without sentences. It is not: it ends them on a small upright stroke, which sits here now. What found the mistake was this being measured by a command that asks the list of bibles for their folder names instead of by somebody typing them, and that is the whole argument for the record beside this file.";
  let suffixes = ".?!।。።？！۔";
  return suffixes;
}
