export function bible_glyph_chapter_pro04() {
  "Proverbs 4, drawn in pictures, so that a person who cannot read the letters can still follow it. It is a father telling his son what his own father told him, and the whole of it is one plea to get wisdom and hold on to it. Twenty seven lines.";
  "THE CHAPTER IS ABOUT WISDOM AND WISDOM HAS NO PICTURE. The word wisdom stands in this chapter four times, in the fifth line, twice in the seventh and once in the eleventh, and not one of them is drawn. Understanding stands three times, in the first line, the fifth and the seventh, and none of those is drawn either. Instruction is undrawn, teaching is undrawn, the sayings are undrawn. What that does to the page can be read off the seventh and eighth lines, which are the two that carry the argument: Wisdom is supreme, so acquire wisdom, and whatever you may acquire, gain understanding. Prize her and she will exalt you. Both lines come out with no picture at all, and they are the only two blank lines on the page. A reader who cannot read the letters gets twenty five drawn lines about a thing they cannot see named once.";
  "THREE BODY PARTS ARE DRAWN HERE AND NOT ONE OF THEM IS A BODY PART. The ear is the picture for listening, so it opens the first line and the tenth. Then the twentieth line says incline your ear, and that ear, the only real ear in the chapter, is left as plain letters, because the picture for it is already spent on the verb. The mouth is the same: the mouth picture means to speak, so the twenty fourth line, put away deception from your mouth, has no mouth in it. The crown is the same again: the crown picture means lord, and the ninth line, she will present you with a crown of beauty, has no crown. Three pictures of body parts and clothing, all three seated on things that are not objects, all three unavailable on the one page that needs them literally.";
  "AND THAT IS NOT THREE ACCIDENTS, IT IS HOW THE ALPHABET WAS BUILT. The ear picture is used in a hundred and eighty five chapters and a plain undrawn ear turns up in twenty of them, Mark 4 among them, where he who has ears to hear draws the hearing and leaves the ears blank in the same breath. The mouth picture is used in a hundred and eight chapters and a plain undrawn mouth turns up in forty four, Isaiah 53 among them, where he did not open his mouth is said three times and the mouth is invisible every time. The crown picture is used in sixty eight chapters and a plain undrawn crown turns up in six. Add the lampstand that means the Jews, the star that means glory, the lightning bolt that means strength and the anchor that means believing, and this is eight pictures named after objects that no longer draw those objects. The largest ones are the marks the whole collection leans on hardest.";
  "TWELVE OF THE FIFTY NINE MARKS ON THIS PAGE ARE THE CROSSED OUT CIRCLE. The most drawn thing in a chapter about getting wisdom is do not. Do not abandon, do not forget, do not forsake, do not let go, do not set foot, do not travel, do not swerve. That is not the chapter being negative, it is the picture set being fuller on the side of refusing than on the side of the thing refused, and it tilts the page.";
  "TWO KINDS OF WALKING AND TWO KINDS OF WORDS, AND THE PAGE IS RIGHT TO LOOK WRONG. The twelfth line draws a walking figure on when you walk and the fourteenth leaves walk plain, because they are two different Hebrew words. The fourth line draws the speech mark on my words and the fifth leaves my words plain, for the same reason. A reader who trusts the pictures will think the page is careless twice. It is not: it is being faithful to the language underneath, and there is no way for it to say so.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PRO04",
    reference: "Proverbs 4",
    verses: [
      {
        verse_number: 1,
        words: [
          "$ear,",
          "my",
          "$son,",
          "to",
          "the",
          "instruction",
          "of",
          "a",
          "$father;",
          "pay",
          "attention",
          "and",
          "$lightbulb",
          "understanding.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "For",
          "I",
          "$hands_giving",
          "you",
          "$thumbs_up",
          "teaching;",
          "$no_entry",
          "abandon",
          "my",
          "$scroll.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "When",
          "I",
          "was",
          "a",
          "$son",
          "to",
          "my",
          "$father,",
          "tender",
          "and",
          "the",
          "only",
          "child",
          "of",
          "my",
          "mother,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "he",
          "taught",
          "me",
          "and",
          "$speech,",
          "Let",
          "your",
          "$heart_organ",
          "lay",
          "hold",
          "of",
          "my",
          "$speech;",
          "keep",
          "my",
          "$scroll",
          "and",
          "you",
          "will",
          "$sprout.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Get",
          "wisdom,",
          "get",
          "understanding;",
          "$no_entry",
          "forget",
          "my",
          "words",
          "or",
          "turn",
          "from",
          "them.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$no_entry",
          "forsake",
          "wisdom,",
          "and",
          "she",
          "will",
          "preserve",
          "you;",
          "$heart_red",
          "her,",
          "and",
          "she",
          "will",
          "guard",
          "you.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Wisdom",
          "is",
          "supreme;",
          "so",
          "acquire",
          "wisdom.",
          "And",
          "whatever",
          "you",
          "may",
          "acquire,",
          "gain",
          "understanding.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Prize",
          "her,",
          "and",
          "she",
          "will",
          "exalt",
          "you;",
          "if",
          "you",
          "embrace",
          "her,",
          "she",
          "will",
          "honor",
          "you.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "She",
          "will",
          "$hands_giving",
          "a",
          "garland",
          "of",
          "grace",
          "on",
          "your",
          "head;",
          "she",
          "will",
          "present",
          "you",
          "with",
          "a",
          "crown",
          "of",
          "beauty.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$ear,",
          "my",
          "$son,",
          "and",
          "$hand_receiving",
          "my",
          "words,",
          "and",
          "the",
          "years",
          "of",
          "your",
          "$sprout",
          "will",
          "be",
          "many.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "I",
          "will",
          "guide",
          "you",
          "in",
          "the",
          "$road",
          "of",
          "wisdom;",
          "I",
          "will",
          "lead",
          "you",
          "on",
          "straight",
          "paths.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "When",
          "you",
          "$walking,",
          "your",
          "steps",
          "will",
          "$no_entry",
          "be",
          "impeded;",
          "when",
          "you",
          "run,",
          "you",
          "will",
          "$no_entry",
          "stumble.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Hold",
          "on",
          "to",
          "instruction;",
          "$no_entry",
          "let",
          "go.",
          "Guard",
          "it,",
          "for",
          "it",
          "is",
          "your",
          "$sprout.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "$no_entry",
          "set",
          "$footprints",
          "on",
          "the",
          "path",
          "of",
          "the",
          "$thumbs_down,",
          "or",
          "walk",
          "in",
          "the",
          "$road",
          "of",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Avoid",
          "it;",
          "$no_entry",
          "travel",
          "on",
          "it.",
          "Turn",
          "from",
          "it",
          "and",
          "pass",
          "on",
          "by.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "For",
          "they",
          "$no_entry",
          "sleep",
          "unless",
          "they",
          "do",
          "evil;",
          "they",
          "are",
          "deprived",
          "of",
          "slumber",
          "until",
          "they",
          "make",
          "someone",
          "fall.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "For",
          "they",
          "eat",
          "the",
          "$bread",
          "of",
          "wickedness",
          "and",
          "drink",
          "the",
          "wine",
          "of",
          "violence.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "The",
          "path",
          "of",
          "the",
          "$ruler",
          "is",
          "like",
          "the",
          "first",
          "$light",
          "of",
          "dawn,",
          "$walking",
          "brighter",
          "and",
          "brighter",
          "until",
          "midday.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "But",
          "the",
          "$road",
          "of",
          "the",
          "$thumbs_down",
          "is",
          "like",
          "the",
          "darkest",
          "gloom;",
          "they",
          "$no_entry",
          "$lightbulb",
          "what",
          "makes",
          "them",
          "stumble.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "My",
          "$son,",
          "pay",
          "attention",
          "to",
          "my",
          "$speech;",
          "incline",
          "your",
          "ear",
          "to",
          "my",
          "sayings.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$no_entry",
          "let",
          "them",
          "out",
          "of",
          "your",
          "$eyes;",
          "keep",
          "them",
          "within",
          "your",
          "$heart_organ.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "For",
          "they",
          "are",
          "$sprout",
          "to",
          "those",
          "who",
          "find",
          "them,",
          "and",
          "health",
          "to",
          "the",
          "whole",
          "$meat.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Guard",
          "your",
          "$heart_organ",
          "with",
          "all",
          "diligence,",
          "for",
          "from",
          "it",
          "$tray_out",
          "the",
          "springs",
          "of",
          "$sprout.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "$tray_out",
          "deception",
          "from",
          "your",
          "mouth;",
          "keep",
          "perverse",
          "speech",
          "far",
          "from",
          "your",
          "lips.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Let",
          "your",
          "$eyes",
          "look",
          "forward;",
          "fix",
          "your",
          "gaze",
          "straight",
          "ahead.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "Make",
          "a",
          "level",
          "path",
          "for",
          "your",
          "feet,",
          "and",
          "all",
          "your",
          "$road",
          "will",
          "be",
          "sure.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "$no_entry",
          "swerve",
          "to",
          "the",
          "right",
          "or",
          "to",
          "the",
          "left;",
          "turn",
          "your",
          "feet",
          "away",
          "from",
          "$thumbs_down.",
        ],
      },
    ],
  };
  return chapter;
}
