export function bible_glyph_chapter_pro31() {
  "Proverbs 31, drawn in pictures. A mother tells her son what a king must not do, then the book closes with a poem about a woman who works from before dawn until after dark and is worth more than jewels. Thirty one lines.";
  "THIRTY ONE LINES AND GOD IS NAMED ONCE, IN THE SECOND TO LAST ONE. There is no flame anywhere on this page. The whole poem is work you can touch, and God is not mentioned in any of it until the thirtieth verse says charm is deceptive and beauty is fleeting, but a woman who fears the LORD is to be praised. The one name mark on the page arrives in the sentence that says everything praised before it was the wrong thing to praise.";
  "THE SON MARK IS DRAWN THREE TIMES AND NOT ONE OF THEM IS THE KINGS SON. The second verse says son three times over, to the boy this whole speech is addressed to, and draws none of them. The mark turns up instead on the ones Hebrew calls sons of affliction in the fifth verse, and on the ones left with nothing in the eighth, and finally on her own children in the twenty eighth. The page gives the picture for a child to the people nobody is looking after.";
  "THE POEM IS MADE OF OBJECTS AND THE PAGE CAN DRAW ALMOST NONE OF THEM. Wool, flax, merchant ships, a field, a vineyard, a distaff, a spindle, a lamp, snow, scarlet, fine linen, purple, sashes, rubies. Not one of those has a seat in the root table. Bread is the only thing in the whole household the page can show, and it shows it twice, once being carried in from far away and once as the bread of idleness she refuses to eat.";
  "THE PICTURE FOR MAKING IS DRAWN FOUR TIMES AND ALL FOUR ARE HOUSEWORK. It is the same hammer this Bible puts on God in Genesis 6, where He had made man on the earth and was grieved about it. Here it is her working with eager hands, making the coverings for her bed, making linen garments to sell, and the noble things many women have done. Nothing on this page marks that as a smaller kind of making, because the page has only the one mark for it.";
  "THE CROWN IS DRAWN FOUR TIMES AND THEN NEVER AGAIN. King Lemuel in the first line, the kings who are ruined by women in the third, and twice in the fourth line where it is not for kings to drink wine. After that the chapter turns to the woman and the crown does not come back for twenty seven lines. The book of Proverbs ends on a page where the king has left and the picture is somebody else entirely.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PRO31",
    reference: "Proverbs 31",
    verses: [
      {
        verse_number: 1,
        words: [
          "These",
          "are",
          "the",
          "$speech",
          "of",
          "$king",
          "Lemuel,",
          "the",
          "burden",
          "that",
          "his",
          "mother",
          "taught",
          "him.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "What,",
          "O",
          "my",
          "son?",
          "What,",
          "O",
          "son",
          "of",
          "my",
          "womb?",
          "What,",
          "O",
          "son",
          "of",
          "my",
          "vows?",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Do",
          "$no_entry",
          "$hands_giving",
          "your",
          "strength",
          "to",
          "$woman,",
          "or",
          "your",
          "$road",
          "to",
          "those",
          "who",
          "ruin",
          "$king.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "It",
          "is",
          "$no_entry",
          "for",
          "$king,",
          "O",
          "Lemuel,",
          "it",
          "is",
          "$no_entry",
          "for",
          "$king",
          "to",
          "drink",
          "wine,",
          "or",
          "for",
          "rulers",
          "to",
          "crave",
          "strong",
          "drink,",
        ],
      },
      {
        verse_number: 5,
        words: [
          "lest",
          "they",
          "drink",
          "and",
          "forget",
          "what",
          "is",
          "decreed,",
          "depriving",
          "all",
          "the",
          "$son",
          "of",
          "affliction",
          "of",
          "justice.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$hands_giving",
          "strong",
          "drink",
          "to",
          "one",
          "who",
          "is",
          "perishing,",
          "and",
          "wine",
          "to",
          "the",
          "bitter",
          "in",
          "$person_other.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Let",
          "him",
          "drink",
          "and",
          "forget",
          "his",
          "poverty,",
          "and",
          "remember",
          "his",
          "misery",
          "$no_entry",
          "more.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Open",
          "your",
          "mouth",
          "for",
          "those",
          "with",
          "no",
          "voice,",
          "for",
          "the",
          "cause",
          "of",
          "all",
          "the",
          "$son",
          "who",
          "are",
          "left",
          "with",
          "nothing.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Open",
          "your",
          "mouth,",
          "judge",
          "$ruler,",
          "and",
          "defend",
          "the",
          "cause",
          "of",
          "the",
          "poor",
          "and",
          "needy.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "A",
          "$woman",
          "of",
          "noble",
          "character,",
          "who",
          "can",
          "find?",
          "She",
          "is",
          "far",
          "more",
          "precious",
          "than",
          "rubies.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "The",
          "$heart_organ",
          "of",
          "her",
          "husband",
          "trusts",
          "in",
          "her,",
          "and",
          "he",
          "lacks",
          "$no_entry",
          "of",
          "value.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "She",
          "brings",
          "him",
          "$thumbs_up",
          "and",
          "$no_entry",
          "$thumbs_down",
          "all",
          "the",
          "$sun",
          "of",
          "her",
          "$sprout.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "She",
          "selects",
          "wool",
          "and",
          "flax,",
          "and",
          "$hammer",
          "with",
          "eager",
          "hands.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "She",
          "is",
          "like",
          "the",
          "merchant",
          "ships,",
          "$footprints",
          "her",
          "$bread",
          "from",
          "afar.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "She",
          "rises",
          "while",
          "it",
          "is",
          "still",
          "night",
          "to",
          "$hands_giving",
          "food",
          "for",
          "her",
          "$house,",
          "and",
          "portions",
          "for",
          "her",
          "maidservants.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "She",
          "appraises",
          "a",
          "field",
          "and",
          "$hand_receiving",
          "it;",
          "from",
          "her",
          "earnings",
          "she",
          "plants",
          "a",
          "vineyard.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "She",
          "girds",
          "herself",
          "with",
          "strength",
          "and",
          "shows",
          "that",
          "her",
          "arms",
          "are",
          "strong.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "She",
          "sees",
          "that",
          "her",
          "gain",
          "is",
          "$thumbs_up,",
          "and",
          "her",
          "lamp",
          "is",
          "$no_entry",
          "extinguished",
          "at",
          "night.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "She",
          "stretches",
          "out",
          "her",
          "$hand",
          "to",
          "the",
          "distaff,",
          "and",
          "grasps",
          "the",
          "spindle",
          "with",
          "her",
          "fingers.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "She",
          "opens",
          "her",
          "arms",
          "to",
          "the",
          "poor,",
          "and",
          "reaches",
          "out",
          "her",
          "$hand",
          "to",
          "the",
          "needy.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "She",
          "has",
          "$no_entry",
          "fear",
          "for",
          "her",
          "$house",
          "when",
          "it",
          "snows,",
          "for",
          "they",
          "are",
          "all",
          "clothed",
          "in",
          "scarlet.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "She",
          "$hammer",
          "coverings",
          "for",
          "her",
          "bed;",
          "her",
          "clothing",
          "is",
          "fine",
          "linen",
          "and",
          "purple.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Her",
          "husband",
          "is",
          "$lightbulb",
          "at",
          "the",
          "city",
          "gates,",
          "where",
          "he",
          "sits",
          "among",
          "the",
          "elders",
          "of",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "She",
          "$hammer",
          "linen",
          "garments",
          "and",
          "sells",
          "them;",
          "she",
          "$hands_giving",
          "sashes",
          "to",
          "the",
          "merchants.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Strength",
          "and",
          "honor",
          "are",
          "her",
          "clothing,",
          "and",
          "she",
          "can",
          "laugh",
          "at",
          "the",
          "$sun",
          "to",
          "come.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "She",
          "opens",
          "her",
          "mouth",
          "with",
          "wisdom,",
          "and",
          "the",
          "$scroll",
          "of",
          "$gift",
          "is",
          "on",
          "her",
          "tongue.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "She",
          "watches",
          "over",
          "the",
          "affairs",
          "of",
          "her",
          "$house,",
          "and",
          "does",
          "$no_entry",
          "eat",
          "the",
          "$bread",
          "of",
          "idleness.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "Her",
          "$son",
          "rise",
          "up",
          "and",
          "call",
          "her",
          "blessed;",
          "her",
          "husband",
          "praises",
          "her",
          "as",
          "well.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "Many",
          "$woman",
          "have",
          "$hammer",
          "noble",
          "things,",
          "but",
          "you",
          "surpass",
          "them",
          "all.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "Charm",
          "is",
          "deceptive",
          "and",
          "beauty",
          "is",
          "fleeting,",
          "but",
          "a",
          "$woman",
          "who",
          "fears",
          "the",
          "$name_tag",
          "is",
          "to",
          "be",
          "praised.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "$hands_giving",
          "her",
          "the",
          "fruit",
          "of",
          "her",
          "$hand,",
          "and",
          "let",
          "her",
          "works",
          "praise",
          "her",
          "at",
          "the",
          "gates.",
        ],
      },
    ],
  };
  return chapter;
}
