export function bible_glyph_chapter_exo01() {
  "Exodus 1, drawn in pictures, so that a person who cannot read the letters can still follow it. Joseph dies, a new king who never knew him puts Israel to forced labor, and two midwives refuse to kill the baby boys. Twenty two lines.";
  "THREE LINES IN A ROW ON THIS PAGE HAVE NOTHING ON THEM AT ALL. The second, third and fourth are the roll call of the brothers, eleven names one after another, and a name is the one thing this collection never draws. It is the longest run of empty lines anywhere in these chapters. A reader following pictures sees the family arrive in Egypt in the first line and then meets three blank rows before anything happens again, and those three rows are the entire nation being listed by name.";
  "AND THE TWO PEOPLE THE CHAPTER IS ACTUALLY ABOUT ARE NEVER DRAWN ONCE. The word midwife or midwives turns up seven times in eight lines, and there is no picture for a midwife. Shiphrah and Puah get a name tag on the line that names them, which says these are names, not which names. Everything they do is drawn around them: the fear of God gets a flame, the refusing gets a crossing-out, the boys get a child. The women themselves are plain letters every single time, in the one chapter of Exodus where the whole story turns on what two women decided.";
  "AND THE ORDER TO DROWN THE BABIES IS THE ONE VIOLENT LINE WITH NO VIOLENCE IN IT. The sixteenth line says if it is a son, kill him, and that gets a skull. The twenty second line says every son born to the Hebrews you must throw into the Nile, and it gets a family, a son, a woman and a sprouting shoot, and not one of those is the throwing or the river or the baby. There is no picture for a river, no picture for a baby, and no picture for drowning. So the mildest reading of the page is the last line, and the last line is the worst thing in the chapter.";
  "AND THE SLAVERY IS ALMOST ENTIRELY INVISIBLE TOO. Taskmasters, forced labor, brick, mortar, work in the fields, Pithom and Rameses are all plain. The eleventh line keeps one picture, a city, out of a sentence that is otherwise the whole machinery of Egyptian state labor. The twelfth keeps one and the fourteenth keeps one. Four lines about a nation being worked to death carry five pictures between them.";
  "AND THE HAMMER FOR MAKING HAD TO COME OFF THE ONE KIND THING GOD DOES HERE. The twenty first line says because the midwives feared God, He gave them families of their own, and the Hebrew verb under gave is asah, to make. A hammer on the word gave would teach a reader that a hammer means give, and the reader has already met that hammer twice in this chapter meaning do. The same line lost a house as well, because a house sitting on the word families would teach that a house means a family, and this collection already has a separate picture for a family. That picture came off the first line for the same reason.";
  "WHAT THE PAGE DOES CARRY IS A COUNT OF PEOPLE AND A COUNT OF REFUSALS. Fifty two marks over twenty two lines. The commonest are the son at seven and the sprouting shoot that means alive at five. Four of those five shoots are somebody being allowed to live, and two of those four are the girls Pharaoh does not care about. Read off the pictures alone the chapter says: sons, sons, a king, a king, alive, alive, alive.";
  "Thirteen marks were dropped from sixty five. Seven sat on pieces of Hebrew this English swallows. Two were a house on the word family. One was a hammer on the word gave. One was a kneeling servant on the word imposed, which is what is done to a servant and not what a servant does. One sat on the words for us. One was a name tag with no name under it.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "EXO01",
    reference: "Exodus 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "These",
          "are",
          "the",
          "$name_tag",
          "of",
          "the",
          "$son",
          "of",
          "Israel",
          "who",
          "$footprints",
          "to",
          "Egypt",
          "with",
          "Jacob,",
          "$man_beard",
          "with",
          "his",
          "family:",
        ],
      },
      {
        verse_number: 2,
        words: ["Reuben,", "Simeon,", "Levi,", "and", "Judah;"],
      },
      {
        verse_number: 3,
        words: ["Issachar,", "Zebulun,", "and", "Benjamin;"],
      },
      {
        verse_number: 4,
        words: ["Dan", "and", "Naphtali;", "Gad", "and", "Asher."],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$person_other",
          "of",
          "Jacob",
          "numbered",
          "seventy",
          "in",
          "all,",
          "including",
          "Joseph,",
          "who",
          "was",
          "already",
          "in",
          "Egypt.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Now",
          "Joseph",
          "and",
          "all",
          "his",
          "$brother",
          "and",
          "all",
          "that",
          "generation",
          "$skull,",
        ],
      },
      {
        verse_number: 7,
        words: [
          "but",
          "the",
          "$son",
          "were",
          "fruitful",
          "and",
          "increased",
          "rapidly;",
          "they",
          "multiplied",
          "and",
          "became",
          "exceedingly",
          "numerous,",
          "so",
          "that",
          "the",
          "$earth",
          "was",
          "filled",
          "with",
          "them.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Then",
          "a",
          "new",
          "$king,",
          "who",
          "did",
          "$no_entry",
          "$lightbulb",
          "Joseph,",
          "came",
          "to",
          "power",
          "in",
          "Egypt.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Look,",
          "he",
          "$speech",
          "to",
          "his",
          "$family,",
          "the",
          "$son",
          "have",
          "become",
          "too",
          "numerous",
          "and",
          "too",
          "powerful",
          "for",
          "us.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Come,",
          "let",
          "us",
          "deal",
          "shrewdly",
          "with",
          "them,",
          "or",
          "they",
          "will",
          "increase",
          "even",
          "more;",
          "and",
          "if",
          "a",
          "war",
          "breaks",
          "out,",
          "they",
          "may",
          "join",
          "our",
          "enemies,",
          "fight",
          "against",
          "us,",
          "and",
          "leave",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "So",
          "the",
          "Egyptians",
          "appointed",
          "taskmasters",
          "over",
          "the",
          "Israelites",
          "to",
          "oppress",
          "them",
          "with",
          "forced",
          "labor.",
          "As",
          "a",
          "result,",
          "they",
          "built",
          "Pithom",
          "and",
          "Rameses",
          "as",
          "store",
          "$city",
          "for",
          "Pharaoh.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "But",
          "the",
          "more",
          "they",
          "were",
          "oppressed,",
          "the",
          "more",
          "they",
          "multiplied",
          "and",
          "flourished;",
          "so",
          "the",
          "Egyptians",
          "came",
          "to",
          "dread",
          "the",
          "$son.",
        ],
      },
      {
        verse_number: 13,
        words: ["They", "$kneeling", "the", "$son", "ruthlessly"],
      },
      {
        verse_number: 14,
        words: [
          "and",
          "made",
          "their",
          "$sprout",
          "bitter",
          "with",
          "hard",
          "labor",
          "in",
          "brick",
          "and",
          "mortar,",
          "and",
          "with",
          "all",
          "kinds",
          "of",
          "work",
          "in",
          "the",
          "fields.",
          "Every",
          "service",
          "they",
          "imposed",
          "was",
          "harsh.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Then",
          "the",
          "$king",
          "of",
          "Egypt",
          "$speech",
          "to",
          "the",
          "Hebrew",
          "midwives,",
          "whose",
          "$name_tag",
          "were",
          "Shiphrah",
          "and",
          "Puah,",
        ],
      },
      {
        verse_number: 16,
        words: [
          "When",
          "you",
          "help",
          "the",
          "Hebrew",
          "women",
          "give",
          "birth,",
          "$eye",
          "them",
          "on",
          "the",
          "birthstools.",
          "If",
          "the",
          "child",
          "is",
          "a",
          "$son,",
          "$skull",
          "him;",
          "but",
          "if",
          "it",
          "is",
          "a",
          "$woman,",
          "let",
          "her",
          "$sprout.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "The",
          "midwives,",
          "however,",
          "feared",
          "$fire",
          "and",
          "did",
          "$no_entry",
          "$hammer",
          "as",
          "the",
          "$king",
          "of",
          "Egypt",
          "had",
          "$mouth;",
          "they",
          "let",
          "the",
          "$child",
          "$sprout.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "So",
          "the",
          "$king",
          "of",
          "Egypt",
          "summoned",
          "the",
          "midwives",
          "and",
          "$speech",
          "them,",
          "Why",
          "have",
          "you",
          "$hammer",
          "this?",
          "Why",
          "have",
          "you",
          "let",
          "the",
          "$child",
          "$sprout?",
        ],
      },
      {
        verse_number: 19,
        words: [
          "The",
          "midwives",
          "$speech",
          "Pharaoh,",
          "The",
          "Hebrew",
          "women",
          "are",
          "$no_entry",
          "like",
          "the",
          "Egyptian",
          "$woman;",
          "they",
          "are",
          "vigorous",
          "and",
          "give",
          "birth",
          "before",
          "a",
          "midwife",
          "$footprints.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "So",
          "$fire",
          "was",
          "good",
          "to",
          "the",
          "midwives,",
          "and",
          "the",
          "$family",
          "multiplied",
          "and",
          "became",
          "even",
          "more",
          "numerous.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "And",
          "because",
          "the",
          "midwives",
          "feared",
          "$fire,",
          "He",
          "gave",
          "them",
          "families",
          "of",
          "their",
          "own.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Then",
          "Pharaoh",
          "commanded",
          "all",
          "his",
          "$family,",
          "Every",
          "$son",
          "born",
          "to",
          "the",
          "Hebrews",
          "you",
          "must",
          "throw",
          "into",
          "the",
          "Nile,",
          "but",
          "every",
          "$woman",
          "you",
          "may",
          "allow",
          "to",
          "$sprout.",
        ],
      },
    ],
  };
  return chapter;
}
