export function bible_glyph_chapter_built_samples() {
  "A handful of picture Bible chapters BUILT from the interlinear, each word its Strong's number and its English, for a page to show beside the hand-written chapters.";
  "Generated by bible_glyph_chapter_built_samples_write - never edit it by hand, run that again.";
  let r = [
 {
  "chapter_code": "GEN01",
  "verses": [
   {
    "verse_number": 1,
    "words": [
     [
      7225,
      "In the beginning"
     ],
     [
      430,
      "God"
     ],
     [
      853,
      ""
     ],
     [
      1254,
      "created"
     ],
     [
      8064,
      "the heavens"
     ],
     [
      853,
      "and"
     ],
     [
      776,
      "the earth"
     ]
    ]
   },
   {
    "verse_number": 2,
    "words": [
     [
      776,
      "Now the earth"
     ],
     [
      1961,
      "was"
     ],
     [
      8414,
      "formless"
     ],
     [
      922,
      "and void"
     ],
     [
      2822,
      "and darkness"
     ],
     [
      5921,
      "was over"
     ],
     [
      6440,
      "the surface"
     ],
     [
      8415,
      "of the deep"
     ],
     [
      7307,
      "And the Spirit"
     ],
     [
      430,
      "of God"
     ],
     [
      7363,
      "was hovering"
     ],
     [
      5921,
      "over"
     ],
     [
      6440,
      "the surface"
     ],
     [
      4325,
      "of the waters"
     ]
    ]
   },
   {
    "verse_number": 3,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      1961,
      "Let there be"
     ],
     [
      216,
      "light"
     ],
     [
      1961,
      "and there was"
     ],
     [
      216,
      "light"
     ]
    ]
   },
   {
    "verse_number": 4,
    "words": [
     [
      430,
      "And God"
     ],
     [
      853,
      ""
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      216,
      "the light"
     ],
     [
      2896,
      "[was] good"
     ],
     [
      430,
      "and [He]"
     ],
     [
      914,
      "separated"
     ],
     [
      216,
      "the light"
     ],
     [
      996,
      "from"
     ],
     [
      996,
      ""
     ],
     [
      2822,
      "the darkness"
     ]
    ]
   },
   {
    "verse_number": 5,
    "words": [
     [
      430,
      "God"
     ],
     [
      7121,
      "called"
     ],
     [
      216,
      "the light"
     ],
     [
      3117,
      "day"
     ],
     [
      2822,
      "and the darkness"
     ],
     [
      7121,
      "He called"
     ],
     [
      3915,
      "night"
     ],
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      259,
      "the first"
     ],
     [
      3117,
      "day"
     ]
    ]
   },
   {
    "verse_number": 6,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      1961,
      "Let there be"
     ],
     [
      7549,
      "an expanse"
     ],
     [
      8432,
      "between"
     ],
     [
      4325,
      "the waters"
     ],
     [
      1961,
      "to"
     ],
     [
      914,
      "separate"
     ],
     [
      996,
      ""
     ],
     [
      4325,
      "the waters"
     ],
     [
      4325,
      "from the waters"
     ]
    ]
   },
   {
    "verse_number": 7,
    "words": [
     [
      430,
      "So God"
     ],
     [
      853,
      ""
     ],
     [
      6213,
      "made"
     ],
     [
      7549,
      "the expanse"
     ],
     [
      914,
      "and separated"
     ],
     [
      996,
      ""
     ],
     [
      4325,
      "the waters"
     ],
     [
      834,
      ""
     ],
     [
      8478,
      "beneath"
     ],
     [
      7549,
      "[it]"
     ],
     [
      996,
      "from"
     ],
     [
      4325,
      "the waters"
     ],
     [
      834,
      ""
     ],
     [
      5921,
      "above"
     ],
     [
      7549,
      ""
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 8,
    "words": [
     [
      430,
      "God"
     ],
     [
      7121,
      "called"
     ],
     [
      7549,
      "the expanse"
     ],
     [
      8064,
      "sky"
     ],
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      8145,
      "the second"
     ],
     [
      3117,
      "day"
     ]
    ]
   },
   {
    "verse_number": 9,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      4325,
      "Let the waters"
     ],
     [
      8478,
      "under"
     ],
     [
      8064,
      "the sky"
     ],
     [
      6960,
      "be gathered"
     ],
     [
      413,
      "into"
     ],
     [
      259,
      "one"
     ],
     [
      4725,
      "place"
     ],
     [
      3004,
      "so that the dry [land]"
     ],
     [
      7200,
      "may appear"
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 10,
    "words": [
     [
      430,
      "God"
     ],
     [
      7121,
      "called"
     ],
     [
      3004,
      "the dry [land]"
     ],
     [
      776,
      "earth"
     ],
     [
      4723,
      "and the gathering"
     ],
     [
      4325,
      "of waters"
     ],
     [
      7121,
      "He called"
     ],
     [
      3220,
      "seas"
     ],
     [
      430,
      "And God"
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      2896,
      "[it was] good"
     ]
    ]
   },
   {
    "verse_number": 11,
    "words": [
     [
      430,
      "Then God"
     ],
     [
      559,
      "said"
     ],
     [
      776,
      "Let the earth"
     ],
     [
      1876,
      "bring forth"
     ],
     [
      1877,
      "vegetation"
     ],
     [
      2232,
      "seed-bearing"
     ],
     [
      2233,
      ""
     ],
     [
      6212,
      "plants"
     ],
     [
      6529,
      "and fruit"
     ],
     [
      6086,
      "trees"
     ],
     [
      6213,
      "each bearing"
     ],
     [
      6529,
      "fruit"
     ],
     [
      2233,
      "with seed"
     ],
     [
      4327,
      "according to its kind"
     ],
     [
      834,
      ""
     ],
     [
      "",
      ""
     ],
     [
      5921,
      ""
     ],
     [
      776,
      ""
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 12,
    "words": [
     [
      776,
      "The earth"
     ],
     [
      3318,
      "produced"
     ],
     [
      1877,
      "vegetation"
     ],
     [
      2232,
      "seed-bearing"
     ],
     [
      2233,
      ""
     ],
     [
      6212,
      "plants"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      6086,
      "and trees"
     ],
     [
      6213,
      "bearing"
     ],
     [
      6529,
      "fruit"
     ],
     [
      834,
      ""
     ],
     [
      2233,
      "with seed"
     ],
     [
      "",
      ""
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      430,
      "And God"
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      2896,
      "it was good"
     ]
    ]
   },
   {
    "verse_number": 13,
    "words": [
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      7992,
      "the third"
     ],
     [
      3117,
      "day"
     ]
    ]
   },
   {
    "verse_number": 14,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      1961,
      "Let there be"
     ],
     [
      3974,
      "lights"
     ],
     [
      7549,
      "in the expanse"
     ],
     [
      8064,
      "of the sky"
     ],
     [
      914,
      "to distinguish"
     ],
     [
      996,
      "between"
     ],
     [
      3117,
      "the day"
     ],
     [
      996,
      "and"
     ],
     [
      3915,
      "the night"
     ],
     [
      1961,
      "and let them be"
     ],
     [
      226,
      "signs to mark"
     ],
     [
      4150,
      "[the] seasons"
     ],
     [
      3117,
      "and days"
     ],
     [
      8141,
      "and years"
     ]
    ]
   },
   {
    "verse_number": 15,
    "words": [
     [
      1961,
      "And let them serve"
     ],
     [
      3974,
      "as lights"
     ],
     [
      7549,
      "in the expanse"
     ],
     [
      8064,
      "of the sky"
     ],
     [
      215,
      "to shine"
     ],
     [
      5921,
      "upon"
     ],
     [
      776,
      "the earth"
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 16,
    "words": [
     [
      430,
      "God"
     ],
     [
      853,
      ""
     ],
     [
      6213,
      "made"
     ],
     [
      8147,
      "two"
     ],
     [
      1419,
      "great"
     ],
     [
      853,
      ""
     ],
     [
      3974,
      "lights"
     ],
     [
      1419,
      "the greater"
     ],
     [
      3974,
      "light"
     ],
     [
      4475,
      "to rule"
     ],
     [
      3117,
      "the day"
     ],
     [
      853,
      "and"
     ],
     [
      6996,
      "the lesser"
     ],
     [
      3974,
      "light"
     ],
     [
      4475,
      "to rule"
     ],
     [
      3915,
      "the night"
     ],
     [
      853,
      "And [He made]"
     ],
     [
      3556,
      "the stars {as well}"
     ]
    ]
   },
   {
    "verse_number": 17,
    "words": [
     [
      430,
      "God"
     ],
     [
      5414,
      "set"
     ],
     [
      853,
      "[these lights]"
     ],
     [
      7549,
      "in the expanse"
     ],
     [
      8064,
      "of the sky"
     ],
     [
      215,
      "to shine"
     ],
     [
      5921,
      "upon"
     ],
     [
      776,
      "the earth"
     ]
    ]
   },
   {
    "verse_number": 18,
    "words": [
     [
      4910,
      "to preside over"
     ],
     [
      3117,
      "the day"
     ],
     [
      3915,
      "and the night"
     ],
     [
      914,
      "and to separate"
     ],
     [
      216,
      "the light"
     ],
     [
      996,
      "from"
     ],
     [
      996,
      ""
     ],
     [
      2822,
      "the darkness"
     ],
     [
      430,
      "And God"
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      2896,
      "[it was] good"
     ]
    ]
   },
   {
    "verse_number": 19,
    "words": [
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      7243,
      "the fourth"
     ],
     [
      3117,
      "day"
     ]
    ]
   },
   {
    "verse_number": 20,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      4325,
      "Let the waters"
     ],
     [
      8317,
      "teem"
     ],
     [
      5315,
      "with living"
     ],
     [
      2416,
      ""
     ],
     [
      8318,
      "creatures"
     ],
     [
      5775,
      "and let birds"
     ],
     [
      5774,
      "fly"
     ],
     [
      5921,
      "above"
     ],
     [
      776,
      "the earth"
     ],
     [
      5921,
      "in"
     ],
     [
      6440,
      "the open"
     ],
     [
      7549,
      "expanse"
     ],
     [
      8064,
      "of the sky"
     ]
    ]
   },
   {
    "verse_number": 21,
    "words": [
     [
      853,
      "So"
     ],
     [
      430,
      "God"
     ],
     [
      1254,
      "created"
     ],
     [
      1419,
      "the great"
     ],
     [
      853,
      ""
     ],
     [
      8577,
      "sea creatures"
     ],
     [
      3605,
      "and every"
     ],
     [
      2416,
      "living"
     ],
     [
      5315,
      "thing"
     ],
     [
      7430,
      "that moves"
     ],
     [
      834,
      "[with] which"
     ],
     [
      4325,
      "the waters"
     ],
     [
      8317,
      "teemed"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      853,
      "and"
     ],
     [
      3605,
      "every"
     ],
     [
      3671,
      "winged"
     ],
     [
      5775,
      "bird"
     ],
     [
      4327,
      "after its kind"
     ],
     [
      430,
      "And God"
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      2896,
      "[it was] good"
     ]
    ]
   },
   {
    "verse_number": 22,
    "words": [
     [
      430,
      "Then God"
     ],
     [
      1288,
      "blessed"
     ],
     [
      853,
      "them"
     ],
     [
      559,
      "[and] said"
     ],
     [
      6509,
      "Be fruitful"
     ],
     [
      7235,
      "and multiply"
     ],
     [
      4390,
      "and fill"
     ],
     [
      853,
      ""
     ],
     [
      4325,
      "the waters"
     ],
     [
      3220,
      "of the seas"
     ],
     [
      5775,
      "and let birds"
     ],
     [
      7235,
      "multiply"
     ],
     [
      776,
      "on the earth"
     ]
    ]
   },
   {
    "verse_number": 23,
    "words": [
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      2549,
      "the fifth"
     ],
     [
      3117,
      "day"
     ]
    ]
   },
   {
    "verse_number": 24,
    "words": [
     [
      430,
      "And God"
     ],
     [
      559,
      "said"
     ],
     [
      776,
      "Let the earth"
     ],
     [
      3318,
      "bring forth"
     ],
     [
      2416,
      "living"
     ],
     [
      5315,
      "creatures"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      929,
      "livestock"
     ],
     [
      7431,
      "land crawlers"
     ],
     [
      2416,
      "and beasts"
     ],
     [
      776,
      "of the earth"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 25,
    "words": [
     [
      853,
      ""
     ],
     [
      430,
      "God"
     ],
     [
      6213,
      "made"
     ],
     [
      2416,
      "the beasts"
     ],
     [
      776,
      "of the earth"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      853,
      ""
     ],
     [
      929,
      "the livestock"
     ],
     [
      4327,
      "according to their kinds"
     ],
     [
      853,
      "and"
     ],
     [
      3605,
      "everything"
     ],
     [
      7431,
      "that crawls"
     ],
     [
      127,
      "upon the earth"
     ],
     [
      4327,
      "according to its kind"
     ],
     [
      430,
      "And God"
     ],
     [
      7200,
      "saw"
     ],
     [
      3588,
      "that"
     ],
     [
      2896,
      "[it was] good"
     ]
    ]
   },
   {
    "verse_number": 26,
    "words": [
     [
      430,
      "Then God"
     ],
     [
      559,
      "said"
     ],
     [
      6213,
      "Let Us make"
     ],
     [
      120,
      "man"
     ],
     [
      6754,
      "in Our image"
     ],
     [
      1823,
      "after Our likeness"
     ],
     [
      7287,
      "to rule"
     ],
     [
      1710,
      "over the fish"
     ],
     [
      3220,
      "of the sea"
     ],
     [
      5775,
      "and the birds"
     ],
     [
      8064,
      "of the air"
     ],
     [
      929,
      "over the livestock"
     ],
     [
      3605,
      "and over all"
     ],
     [
      776,
      "the earth itself"
     ],
     [
      3605,
      "and every"
     ],
     [
      7431,
      "creature"
     ],
     [
      7430,
      "that crawls"
     ],
     [
      5921,
      "upon"
     ],
     [
      776,
      "[it]"
     ]
    ]
   },
   {
    "verse_number": 27,
    "words": [
     [
      430,
      "So God"
     ],
     [
      853,
      ""
     ],
     [
      1254,
      "created"
     ],
     [
      120,
      "man"
     ],
     [
      6754,
      "in His [own] image"
     ],
     [
      6754,
      "in the image"
     ],
     [
      430,
      "of God"
     ],
     [
      1254,
      "He created"
     ],
     [
      853,
      "him"
     ],
     [
      2145,
      "male"
     ],
     [
      5347,
      "and female"
     ],
     [
      1254,
      "He created"
     ],
     [
      853,
      "them"
     ]
    ]
   },
   {
    "verse_number": 28,
    "words": [
     [
      430,
      "God"
     ],
     [
      1288,
      "blessed"
     ],
     [
      853,
      "them"
     ],
     [
      430,
      "and"
     ],
     [
      559,
      "said"
     ],
     [
      "",
      "to them"
     ],
     [
      6509,
      "Be fruitful"
     ],
     [
      7235,
      "and multiply"
     ],
     [
      4390,
      "and fill"
     ],
     [
      853,
      ""
     ],
     [
      776,
      "the earth"
     ],
     [
      3533,
      "and subdue it"
     ],
     [
      7287,
      "rule"
     ],
     [
      1710,
      "over the fish"
     ],
     [
      3220,
      "of the sea"
     ],
     [
      5775,
      "and the birds"
     ],
     [
      8064,
      "of the air"
     ],
     [
      3605,
      "and every"
     ],
     [
      2416,
      "creature"
     ],
     [
      7430,
      "that crawls"
     ],
     [
      5921,
      "upon"
     ],
     [
      776,
      "the earth"
     ]
    ]
   },
   {
    "verse_number": 29,
    "words": [
     [
      430,
      "Then God"
     ],
     [
      559,
      "said"
     ],
     [
      2009,
      "Behold"
     ],
     [
      5414,
      "I have given"
     ],
     [
      "",
      "you"
     ],
     [
      853,
      ""
     ],
     [
      3605,
      "every"
     ],
     [
      2232,
      ""
     ],
     [
      2233,
      "seed-bearing"
     ],
     [
      834,
      ""
     ],
     [
      6212,
      "plant"
     ],
     [
      5921,
      "on"
     ],
     [
      6440,
      "the face"
     ],
     [
      3605,
      "of all"
     ],
     [
      776,
      "the earth"
     ],
     [
      853,
      "and"
     ],
     [
      3605,
      "every"
     ],
     [
      6086,
      "tree"
     ],
     [
      834,
      "whose"
     ],
     [
      6529,
      "fruit"
     ],
     [
      2232,
      "contains"
     ],
     [
      "",
      ""
     ],
     [
      6086,
      ""
     ],
     [
      2233,
      "seed"
     ],
     [
      1961,
      "They will be"
     ],
     [
      "",
      "yours"
     ],
     [
      402,
      "for food"
     ]
    ]
   },
   {
    "verse_number": 30,
    "words": [
     [
      3605,
      "And to every"
     ],
     [
      2416,
      "beast"
     ],
     [
      776,
      "of the earth"
     ],
     [
      3605,
      "and every"
     ],
     [
      5775,
      "bird"
     ],
     [
      8064,
      "of the air"
     ],
     [
      3605,
      "and every"
     ],
     [
      7430,
      "creature that crawls"
     ],
     [
      5921,
      "upon"
     ],
     [
      776,
      "the earth"
     ],
     [
      834,
      "everything that has"
     ],
     [
      5315,
      "the breath"
     ],
     [
      2416,
      "of life"
     ],
     [
      853,
      ""
     ],
     [
      "",
      "in it"
     ],
     [
      3605,
      "[I have given] every"
     ],
     [
      3418,
      "green"
     ],
     [
      6212,
      "plant"
     ],
     [
      402,
      "for food"
     ],
     [
      1961,
      "And it was"
     ],
     [
      3651,
      "so"
     ]
    ]
   },
   {
    "verse_number": 31,
    "words": [
     [
      430,
      "And God"
     ],
     [
      853,
      ""
     ],
     [
      7200,
      "looked upon"
     ],
     [
      3605,
      "all"
     ],
     [
      834,
      "that"
     ],
     [
      6213,
      "He had made"
     ],
     [
      2009,
      "and indeed"
     ],
     [
      3966,
      "[it was] very"
     ],
     [
      2896,
      "good"
     ],
     [
      1961,
      "And there was"
     ],
     [
      6153,
      "evening"
     ],
     [
      1961,
      "and there was"
     ],
     [
      1242,
      "morning"
     ],
     [
      8345,
      "the sixth"
     ],
     [
      3117,
      "day"
     ]
    ]
   }
  ]
 },
 {
  "chapter_code": "PSA023",
  "verses": [
   {
    "verse_number": 1,
    "words": [
     [
      4210,
      "A Psalm"
     ],
     [
      1732,
      "of David"
     ],
     [
      3068,
      "The LORD"
     ],
     [
      7462,
      "is my shepherd"
     ],
     [
      3808,
      "I shall not"
     ],
     [
      2637,
      "want"
     ]
    ]
   },
   {
    "verse_number": 2,
    "words": [
     [
      7257,
      "He makes me lie down"
     ],
     [
      1877,
      "in green"
     ],
     [
      4999,
      "pastures"
     ],
     [
      5095,
      "He leads me"
     ],
     [
      5921,
      "beside"
     ],
     [
      4496,
      "quiet"
     ],
     [
      4325,
      "waters"
     ]
    ]
   },
   {
    "verse_number": 3,
    "words": [
     [
      7725,
      "He restores"
     ],
     [
      5315,
      "my soul"
     ],
     [
      5148,
      "He guides me"
     ],
     [
      4570,
      "in the paths"
     ],
     [
      6664,
      "of righteousness"
     ],
     [
      4616,
      "for the sake"
     ],
     [
      8034,
      "of His name"
     ]
    ]
   },
   {
    "verse_number": 4,
    "words": [
     [
      1571,
      "Even"
     ],
     [
      3588,
      "though"
     ],
     [
      1980,
      "I walk"
     ],
     [
      1516,
      "through the valley"
     ],
     [
      6757,
      "of the shadow of death"
     ],
     [
      3372,
      "I will fear"
     ],
     [
      3808,
      "no"
     ],
     [
      7451,
      "evil"
     ],
     [
      3588,
      "for"
     ],
     [
      859,
      "You"
     ],
     [
      5978,
      "are with me"
     ],
     [
      7626,
      "Your rod"
     ],
     [
      4938,
      "and Your staff"
     ],
     [
      1992,
      "they"
     ],
     [
      5162,
      "comfort me"
     ]
    ]
   },
   {
    "verse_number": 5,
    "words": [
     [
      6186,
      "You prepare"
     ],
     [
      7979,
      "a table"
     ],
     [
      6440,
      "before me"
     ],
     [
      5048,
      "in the presence of"
     ],
     [
      6887,
      "my enemies"
     ],
     [
      1878,
      "You anoint"
     ],
     [
      7218,
      "my head"
     ],
     [
      8081,
      "with oil"
     ],
     [
      3563,
      "my cup"
     ],
     [
      7310,
      "overflows"
     ]
    ]
   },
   {
    "verse_number": 6,
    "words": [
     [
      389,
      "Surely"
     ],
     [
      2896,
      "goodness"
     ],
     [
      2617,
      "and mercy"
     ],
     [
      7291,
      "will follow me"
     ],
     [
      3605,
      "all"
     ],
     [
      3117,
      "the days"
     ],
     [
      2416,
      "of my life"
     ],
     [
      7725,
      "and I will dwell"
     ],
     [
      1004,
      "in the house"
     ],
     [
      3068,
      "of the LORD"
     ],
     [
      753,
      "forever"
     ],
     [
      3117,
      ""
     ]
    ]
   }
  ]
 },
 {
  "chapter_code": "JHN14",
  "verses": [
   {
    "verse_number": 1,
    "words": [
     [
      3361,
      "{Do} not {let}"
     ],
     [
      4771,
      "your"
     ],
     [
      3588,
      ""
     ],
     [
      2588,
      "hearts"
     ],
     [
      5015,
      "be troubled"
     ],
     [
      4100,
      "You believe"
     ],
     [
      1519,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      4100,
      "believe"
     ],
     [
      1519,
      "in"
     ],
     [
      1473,
      "Me"
     ],
     [
      2532,
      "as well"
     ]
    ]
   },
   {
    "verse_number": 2,
    "words": [
     [
      1722,
      "In"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3962,
      "Father’s"
     ],
     [
      3588,
      ""
     ],
     [
      3614,
      "house"
     ],
     [
      1510,
      "are"
     ],
     [
      4183,
      "many"
     ],
     [
      3438,
      "rooms"
     ],
     [
      1161,
      ""
     ],
     [
      1487,
      "If"
     ],
     [
      3361,
      "[it were] not"
     ],
     [
      302,
      "so"
     ],
     [
      2036,
      "would I have told"
     ],
     [
      4771,
      "you"
     ],
     [
      3754,
      "that"
     ],
     [
      4198,
      "I am going [there]"
     ],
     [
      2090,
      "to prepare"
     ],
     [
      5117,
      "a place"
     ],
     [
      4771,
      "for you"
     ]
    ]
   },
   {
    "verse_number": 3,
    "words": [
     [
      2532,
      "And"
     ],
     [
      1437,
      "if"
     ],
     [
      4198,
      "I go"
     ],
     [
      2532,
      "and"
     ],
     [
      2090,
      "prepare"
     ],
     [
      5117,
      "a place"
     ],
     [
      4771,
      "for you"
     ],
     [
      2064,
      "I will come"
     ],
     [
      3825,
      "back"
     ],
     [
      2532,
      "and"
     ],
     [
      3880,
      "welcome"
     ],
     [
      4771,
      "you"
     ],
     [
      4314,
      "into"
     ],
     [
      1683,
      "My presence"
     ],
     [
      2443,
      "so that"
     ],
     [
      4771,
      "you"
     ],
     [
      2532,
      "also"
     ],
     [
      1510,
      "may be"
     ],
     [
      3699,
      "where"
     ],
     [
      1473,
      "I"
     ],
     [
      1510,
      "am"
     ]
    ]
   },
   {
    "verse_number": 4,
    "words": [
     [
      2532,
      ""
     ],
     [
      1492,
      "You know"
     ],
     [
      3588,
      "the"
     ],
     [
      3598,
      "way"
     ],
     [
      3699,
      "to the place where"
     ],
     [
      1473,
      "I"
     ],
     [
      5217,
      "am going"
     ]
    ]
   },
   {
    "verse_number": 5,
    "words": [
     [
      2962,
      "Lord"
     ],
     [
      3004,
      "said"
     ],
     [
      2381,
      "Thomas"
     ],
     [
      846,
      ""
     ],
     [
      3756,
      ""
     ],
     [
      1492,
      "we do not know"
     ],
     [
      4226,
      "where"
     ],
     [
      5217,
      "You are going"
     ],
     [
      4459,
      "[so] how"
     ],
     [
      1410,
      "can we"
     ],
     [
      3588,
      "the"
     ],
     [
      3598,
      "way"
     ]
    ]
   },
   {
    "verse_number": 6,
    "words": [
     [
      2424,
      "Jesus"
     ],
     [
      3004,
      "answered"
     ],
     [
      846,
      ""
     ],
     [
      1473,
      "I"
     ],
     [
      1510,
      "am"
     ],
     [
      3588,
      "the"
     ],
     [
      3598,
      "way"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      225,
      "truth"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      2222,
      "life"
     ],
     [
      3762,
      "No one"
     ],
     [
      2064,
      "comes"
     ],
     [
      4314,
      "to"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1487,
      "except"
     ],
     [
      3361,
      ""
     ],
     [
      1223,
      "through"
     ],
     [
      1473,
      "Me"
     ]
    ]
   },
   {
    "verse_number": 7,
    "words": [
     [
      1487,
      "If"
     ],
     [
      1097,
      "you had known"
     ],
     [
      1473,
      "Me"
     ],
     [
      2532,
      ""
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3962,
      "Father"
     ],
     [
      575,
      "From"
     ],
     [
      737,
      "now on"
     ],
     [
      1097,
      "you do know"
     ],
     [
      846,
      "Him"
     ],
     [
      2532,
      "and"
     ],
     [
      3708,
      "have seen"
     ]
    ]
   },
   {
    "verse_number": 8,
    "words": [
     [
      5376,
      "Philip"
     ],
     [
      3004,
      "said"
     ],
     [
      846,
      "to Him"
     ],
     [
      2962,
      "Lord"
     ],
     [
      1166,
      "show"
     ],
     [
      1473,
      "us"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      2532,
      "and"
     ],
     [
      714,
      "that will be enough"
     ],
     [
      1473,
      "for us"
     ]
    ]
   },
   {
    "verse_number": 9,
    "words": [
     [
      3588,
      ""
     ],
     [
      2424,
      "Jesus"
     ],
     [
      3004,
      "replied"
     ],
     [
      846,
      ""
     ],
     [
      5376,
      "Philip"
     ],
     [
      1510,
      "I have been"
     ],
     [
      3326,
      "with"
     ],
     [
      4771,
      "you"
     ],
     [
      5118,
      "all this"
     ],
     [
      5550,
      "time"
     ],
     [
      2532,
      "and"
     ],
     [
      3756,
      ""
     ],
     [
      1097,
      "still you do not know"
     ],
     [
      1473,
      "Me"
     ],
     [
      3588,
      "Anyone who"
     ],
     [
      3708,
      "has seen"
     ],
     [
      1473,
      "Me"
     ],
     [
      3708,
      "has seen"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      4459,
      "How"
     ],
     [
      4771,
      "{can} you"
     ],
     [
      3004,
      "say"
     ],
     [
      1166,
      "Show"
     ],
     [
      1473,
      "us"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ]
    ]
   },
   {
    "verse_number": 10,
    "words": [
     [
      3756,
      ""
     ],
     [
      4100,
      "Do you not believe"
     ],
     [
      3754,
      "that"
     ],
     [
      1473,
      "I [am]"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1510,
      "is"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "Me"
     ],
     [
      3588,
      "The"
     ],
     [
      4487,
      "words"
     ],
     [
      3739,
      ""
     ],
     [
      1473,
      "I"
     ],
     [
      3004,
      "say"
     ],
     [
      4771,
      "to you"
     ],
     [
      3756,
      ""
     ],
     [
      2980,
      "I do not speak"
     ],
     [
      575,
      "on"
     ],
     [
      1683,
      "My own"
     ],
     [
      1161,
      "Instead"
     ],
     [
      3588,
      "{it is} the"
     ],
     [
      3962,
      "Father"
     ],
     [
      3306,
      "dwelling"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "Me"
     ],
     [
      4160,
      "performing"
     ],
     [
      846,
      "His"
     ],
     [
      3588,
      ""
     ],
     [
      2041,
      "works"
     ]
    ]
   },
   {
    "verse_number": 11,
    "words": [
     [
      4100,
      "Believe"
     ],
     [
      1473,
      "Me"
     ],
     [
      3754,
      "that"
     ],
     [
      1473,
      "I [am]"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1722,
      "[is] in"
     ],
     [
      1473,
      "Me"
     ],
     [
      1161,
      "or at least"
     ],
     [
      1487,
      ""
     ],
     [
      3361,
      ""
     ],
     [
      4100,
      "believe"
     ],
     [
      1223,
      "on account of"
     ],
     [
      3588,
      "the"
     ],
     [
      2041,
      "works"
     ],
     [
      846,
      "themselves"
     ]
    ]
   },
   {
    "verse_number": 12,
    "words": [
     [
      281,
      "Truly"
     ],
     [
      281,
      "truly"
     ],
     [
      3004,
      "I tell"
     ],
     [
      4771,
      "you"
     ],
     [
      3588,
      "whoever"
     ],
     [
      4100,
      "believes"
     ],
     [
      1519,
      "in"
     ],
     [
      1473,
      "Me"
     ],
     [
      2548,
      ""
     ],
     [
      4160,
      "will also do"
     ],
     [
      3588,
      "the"
     ],
     [
      2041,
      "works"
     ],
     [
      3739,
      "that"
     ],
     [
      1473,
      "I"
     ],
     [
      4160,
      "am doing"
     ],
     [
      4160,
      "He will do"
     ],
     [
      2532,
      "even"
     ],
     [
      3173,
      "greater [things]"
     ],
     [
      3778,
      "than these"
     ],
     [
      3754,
      "because"
     ],
     [
      1473,
      "I"
     ],
     [
      4198,
      "am going"
     ],
     [
      4314,
      "to"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ]
    ]
   },
   {
    "verse_number": 13,
    "words": [
     [
      2532,
      "And"
     ],
     [
      3778,
      ""
     ],
     [
      4160,
      "I will do"
     ],
     [
      3754,
      "whatever"
     ],
     [
      302,
      ""
     ],
     [
      154,
      "you ask"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      1473,
      "My"
     ],
     [
      3686,
      "name"
     ],
     [
      2443,
      "so that"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1392,
      "may be glorified"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      "the"
     ],
     [
      5207,
      "Son"
     ]
    ]
   },
   {
    "verse_number": 14,
    "words": [
     [
      1437,
      "If"
     ],
     [
      154,
      "you ask"
     ],
     [
      1473,
      "Me"
     ],
     [
      5100,
      "for anything"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3686,
      "name"
     ],
     [
      1473,
      "I"
     ],
     [
      4160,
      "will do [it]"
     ]
    ]
   },
   {
    "verse_number": 15,
    "words": [
     [
      1437,
      "If"
     ],
     [
      25,
      "you love"
     ],
     [
      1473,
      "Me"
     ],
     [
      5083,
      "you will keep"
     ],
     [
      3588,
      ""
     ],
     [
      1699,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      1785,
      "commandments"
     ]
    ]
   },
   {
    "verse_number": 16,
    "words": [
     [
      "2532",
      "And"
     ],
     [
      "1473",
      "I"
     ],
     [
      2065,
      "will ask"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      2532,
      "and"
     ],
     [
      1325,
      "He will give"
     ],
     [
      4771,
      "you"
     ],
     [
      243,
      "another"
     ],
     [
      3875,
      "Advocate"
     ],
     [
      2443,
      "to"
     ],
     [
      1510,
      "be"
     ],
     [
      3326,
      "with"
     ],
     [
      4771,
      "you"
     ],
     [
      1519,
      ""
     ],
     [
      3588,
      ""
     ],
     [
      165,
      "forever"
     ]
    ]
   },
   {
    "verse_number": 17,
    "words": [
     [
      3588,
      "the"
     ],
     [
      4151,
      "Spirit"
     ],
     [
      3588,
      ""
     ],
     [
      225,
      "of truth"
     ],
     [
      3588,
      "The"
     ],
     [
      2889,
      "world"
     ],
     [
      3756,
      ""
     ],
     [
      1410,
      "cannot"
     ],
     [
      2983,
      "receive"
     ],
     [
      3739,
      "[Him]"
     ],
     [
      3754,
      "because"
     ],
     [
      3756,
      ""
     ],
     [
      2334,
      "it neither sees"
     ],
     [
      846,
      "Him"
     ],
     [
      3761,
      "nor"
     ],
     [
      1097,
      "knows [Him]"
     ],
     [
      4771,
      "But you"
     ],
     [
      1097,
      "do know"
     ],
     [
      846,
      "Him"
     ],
     [
      3754,
      "for"
     ],
     [
      3306,
      "He abides"
     ],
     [
      3844,
      "with"
     ],
     [
      4771,
      "you"
     ],
     [
      2532,
      "and"
     ],
     [
      1510,
      "will be"
     ],
     [
      1722,
      "in"
     ],
     [
      4771,
      "you"
     ]
    ]
   },
   {
    "verse_number": 18,
    "words": [
     [
      3756,
      ""
     ],
     [
      863,
      "I will not leave"
     ],
     [
      4771,
      "you"
     ],
     [
      3737,
      "as orphans"
     ],
     [
      2064,
      "I will come"
     ],
     [
      4314,
      "to"
     ],
     [
      4771,
      "you"
     ]
    ]
   },
   {
    "verse_number": 19,
    "words": [
     [
      2089,
      "In"
     ],
     [
      3398,
      "a little while"
     ],
     [
      2532,
      ""
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      2334,
      "will see"
     ],
     [
      1473,
      "Me"
     ],
     [
      3765,
      "no more"
     ],
     [
      1161,
      "but"
     ],
     [
      4771,
      "you"
     ],
     [
      2334,
      "will see"
     ],
     [
      1473,
      "Me"
     ],
     [
      3754,
      "Because"
     ],
     [
      1473,
      "I"
     ],
     [
      2198,
      "live"
     ],
     [
      4771,
      "you"
     ],
     [
      2532,
      "also"
     ],
     [
      2198,
      "will live"
     ]
    ]
   },
   {
    "verse_number": 20,
    "words": [
     [
      1722,
      "On"
     ],
     [
      1565,
      "that"
     ],
     [
      3588,
      ""
     ],
     [
      2250,
      "day"
     ],
     [
      4771,
      "you"
     ],
     [
      1097,
      "will know"
     ],
     [
      3754,
      "that"
     ],
     [
      1473,
      "I [am]"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3962,
      "Father"
     ],
     [
      2532,
      "and"
     ],
     [
      4771,
      "you [are]"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "Me"
     ],
     [
      "2532",
      "and"
     ],
     [
      "1473",
      "I [am]"
     ],
     [
      1722,
      "in"
     ],
     [
      4771,
      "you"
     ]
    ]
   },
   {
    "verse_number": 21,
    "words": [
     [
      3588,
      "Whoever"
     ],
     [
      2192,
      "has"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      1785,
      "commandments"
     ],
     [
      2532,
      "and"
     ],
     [
      5083,
      "keeps"
     ],
     [
      846,
      "them"
     ],
     [
      1565,
      ""
     ],
     [
      1510,
      "is"
     ],
     [
      3588,
      "the [one who]"
     ],
     [
      25,
      "loves"
     ],
     [
      1473,
      "Me"
     ],
     [
      1161,
      ""
     ],
     [
      3588,
      "The [one who]"
     ],
     [
      25,
      "loves"
     ],
     [
      1473,
      "Me"
     ],
     [
      25,
      "will be loved"
     ],
     [
      5259,
      "by"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3962,
      "Father"
     ],
     [
      "2532",
      "and"
     ],
     [
      "1473",
      "I"
     ],
     [
      25,
      "will love"
     ],
     [
      846,
      "him"
     ],
     [
      2532,
      "and"
     ],
     [
      1718,
      "reveal"
     ],
     [
      1683,
      "Myself"
     ],
     [
      846,
      "to him"
     ]
    ]
   },
   {
    "verse_number": 22,
    "words": [
     [
      2455,
      "Judas"
     ],
     [
      3756,
      "(not"
     ],
     [
      3588,
      ""
     ],
     [
      2469,
      "Iscariot)"
     ],
     [
      3004,
      "asked"
     ],
     [
      846,
      "Him"
     ],
     [
      2962,
      "Lord"
     ],
     [
      2532,
      ""
     ],
     [
      5101,
      "why"
     ],
     [
      1096,
      ""
     ],
     [
      3754,
      ""
     ],
     [
      3195,
      "are You going"
     ],
     [
      1718,
      "to reveal"
     ],
     [
      4572,
      "Yourself"
     ],
     [
      1473,
      "to us"
     ],
     [
      2532,
      "and"
     ],
     [
      3780,
      "not"
     ],
     [
      3588,
      "to the"
     ],
     [
      2889,
      "world"
     ]
    ]
   },
   {
    "verse_number": 23,
    "words": [
     [
      2424,
      "Jesus"
     ],
     [
      611,
      "replied"
     ],
     [
      2532,
      ""
     ],
     [
      2036,
      ""
     ],
     [
      846,
      ""
     ],
     [
      1437,
      "If"
     ],
     [
      5100,
      "anyone"
     ],
     [
      25,
      "loves"
     ],
     [
      1473,
      "Me"
     ],
     [
      5083,
      "he will keep"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3056,
      "word"
     ],
     [
      2532,
      ""
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3962,
      "Father"
     ],
     [
      25,
      "will love"
     ],
     [
      846,
      "him"
     ],
     [
      2532,
      "and"
     ],
     [
      2064,
      "We will come"
     ],
     [
      4314,
      "to"
     ],
     [
      846,
      "him"
     ],
     [
      2532,
      "and"
     ],
     [
      4160,
      "make"
     ],
     [
      3438,
      "Our home"
     ],
     [
      3844,
      "with"
     ],
     [
      846,
      "him"
     ]
    ]
   },
   {
    "verse_number": 24,
    "words": [
     [
      3588,
      "Whoever"
     ],
     [
      3361,
      ""
     ],
     [
      25,
      "does not love"
     ],
     [
      1473,
      "Me"
     ],
     [
      3756,
      ""
     ],
     [
      5083,
      "does not keep"
     ],
     [
      1473,
      "My"
     ],
     [
      3588,
      ""
     ],
     [
      3056,
      "words"
     ],
     [
      2532,
      ""
     ],
     [
      3588,
      "The"
     ],
     [
      3056,
      "word"
     ],
     [
      3739,
      "that"
     ],
     [
      191,
      "you hear"
     ],
     [
      1510,
      "is"
     ],
     [
      3756,
      "not"
     ],
     [
      1699,
      "My own"
     ],
     [
      235,
      "but"
     ],
     [
      3588,
      "[it is ] from the"
     ],
     [
      3962,
      "Father"
     ],
     [
      3992,
      "who sent"
     ],
     [
      1473,
      "Me"
     ]
    ]
   },
   {
    "verse_number": 25,
    "words": [
     [
      3778,
      "All this"
     ],
     [
      2980,
      "I have spoken"
     ],
     [
      4771,
      "to you"
     ],
     [
      3306,
      "[while] I am still"
     ],
     [
      3844,
      "with"
     ],
     [
      4771,
      "you"
     ]
    ]
   },
   {
    "verse_number": 26,
    "words": [
     [
      1161,
      "But"
     ],
     [
      3588,
      "the"
     ],
     [
      3875,
      "Advocate"
     ],
     [
      3588,
      "the"
     ],
     [
      3588,
      ""
     ],
     [
      40,
      "Holy"
     ],
     [
      4151,
      "Spirit"
     ],
     [
      3739,
      "whom"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      3992,
      "will send"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      1473,
      "My"
     ],
     [
      3686,
      "name"
     ],
     [
      1565,
      ""
     ],
     [
      1321,
      "will teach"
     ],
     [
      4771,
      "you"
     ],
     [
      3956,
      "all things"
     ],
     [
      2532,
      "and"
     ],
     [
      4771,
      ""
     ],
     [
      5279,
      "will remind you of"
     ],
     [
      3956,
      "everything"
     ],
     [
      3739,
      ""
     ],
     [
      1473,
      "I"
     ],
     [
      2036,
      "have told"
     ],
     [
      4771,
      "you"
     ]
    ]
   },
   {
    "verse_number": 27,
    "words": [
     [
      1515,
      "Peace"
     ],
     [
      863,
      "I leave"
     ],
     [
      4771,
      "with you"
     ],
     [
      3588,
      ""
     ],
     [
      1699,
      "My"
     ],
     [
      1515,
      "peace"
     ],
     [
      1325,
      "I give"
     ],
     [
      4771,
      "to you"
     ],
     [
      1473,
      "I {do}"
     ],
     [
      3756,
      "not"
     ],
     [
      1325,
      "give"
     ],
     [
      4771,
      "to you"
     ],
     [
      2531,
      "as"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      1325,
      "gives"
     ],
     [
      3361,
      "{Do} not {let}"
     ],
     [
      4771,
      "your"
     ],
     [
      3588,
      ""
     ],
     [
      2588,
      "hearts"
     ],
     [
      5015,
      "be troubled"
     ],
     [
      3366,
      "{do} not"
     ],
     [
      1168,
      "be afraid"
     ]
    ]
   },
   {
    "verse_number": 28,
    "words": [
     [
      191,
      "You heard"
     ],
     [
      3754,
      ""
     ],
     [
      1473,
      "Me"
     ],
     [
      2036,
      "say"
     ],
     [
      4771,
      ""
     ],
     [
      5217,
      "I am going away"
     ],
     [
      2532,
      "and"
     ],
     [
      2064,
      "I am coming [back]"
     ],
     [
      4314,
      "to"
     ],
     [
      4771,
      "you"
     ],
     [
      1487,
      "If"
     ],
     [
      25,
      "you loved"
     ],
     [
      1473,
      "Me"
     ],
     [
      302,
      ""
     ],
     [
      5463,
      "you would rejoice"
     ],
     [
      3754,
      "that"
     ],
     [
      4198,
      "I am going"
     ],
     [
      4314,
      "to"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      3754,
      "because"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1510,
      "is"
     ],
     [
      3173,
      "greater than"
     ],
     [
      1473,
      "I"
     ]
    ]
   },
   {
    "verse_number": 29,
    "words": [
     [
      2532,
      "And"
     ],
     [
      3568,
      "now"
     ],
     [
      2046,
      "I have told"
     ],
     [
      4771,
      "you"
     ],
     [
      4250,
      "before"
     ],
     [
      1096,
      "it happens"
     ],
     [
      2443,
      "so that"
     ],
     [
      3752,
      "when"
     ],
     [
      1096,
      "it does happen"
     ],
     [
      4100,
      "you will believe"
     ]
    ]
   },
   {
    "verse_number": 30,
    "words": [
     [
      2980,
      "I will {not} speak"
     ],
     [
      3326,
      "with"
     ],
     [
      4771,
      "you"
     ],
     [
      4183,
      "much"
     ],
     [
      3765,
      "[longer]"
     ],
     [
      1063,
      "for"
     ],
     [
      3588,
      "the"
     ],
     [
      758,
      "prince"
     ],
     [
      3588,
      "of this"
     ],
     [
      2889,
      "world"
     ],
     [
      2064,
      "is coming"
     ],
     [
      2532,
      "and"
     ],
     [
      2192,
      "he has"
     ],
     [
      3756,
      "no claim"
     ],
     [
      3762,
      ""
     ],
     [
      1722,
      "on"
     ],
     [
      1473,
      "Me"
     ]
    ]
   },
   {
    "verse_number": 31,
    "words": [
     [
      235,
      "But"
     ],
     [
      4160,
      "I do"
     ],
     [
      3779,
      ""
     ],
     [
      2532,
      ""
     ],
     [
      2531,
      "exactly what"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1781,
      "has commanded"
     ],
     [
      1473,
      "Me"
     ],
     [
      2443,
      "so that"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      1097,
      "may know"
     ],
     [
      3754,
      "that"
     ],
     [
      25,
      "I love"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      1453,
      "Get up"
     ],
     [
      71,
      "Let us go on"
     ],
     [
      1782,
      "from here"
     ]
    ]
   }
  ]
 },
 {
  "chapter_code": "1JN04",
  "verses": [
   {
    "verse_number": 1,
    "words": [
     [
      27,
      "Beloved"
     ],
     [
      3361,
      ""
     ],
     [
      4100,
      "do not believe"
     ],
     [
      3956,
      "every"
     ],
     [
      4151,
      "spirit"
     ],
     [
      235,
      "but"
     ],
     [
      1381,
      "test"
     ],
     [
      3588,
      "the"
     ],
     [
      4151,
      "spirits"
     ],
     [
      1487,
      "[to see] whether"
     ],
     [
      1510,
      "they are"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3754,
      "For"
     ],
     [
      4183,
      "many"
     ],
     [
      5578,
      "false prophets"
     ],
     [
      1831,
      "have gone out"
     ],
     [
      1519,
      "into"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ]
    ]
   },
   {
    "verse_number": 2,
    "words": [
     [
      1722,
      "By"
     ],
     [
      3778,
      "this"
     ],
     [
      1097,
      "you will know"
     ],
     [
      3588,
      "the"
     ],
     [
      4151,
      "Spirit"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "of God"
     ],
     [
      3956,
      "Every"
     ],
     [
      4151,
      "spirit"
     ],
     [
      3739,
      "that"
     ],
     [
      3670,
      "confesses [that]"
     ],
     [
      2424,
      "Jesus"
     ],
     [
      5547,
      "Christ"
     ],
     [
      2064,
      "has come"
     ],
     [
      1722,
      "in"
     ],
     [
      4561,
      "[the] flesh"
     ],
     [
      1510,
      "is"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ]
    ]
   },
   {
    "verse_number": 3,
    "words": [
     [
      2532,
      "and"
     ],
     [
      3956,
      "every"
     ],
     [
      4151,
      "spirit"
     ],
     [
      3739,
      "that"
     ],
     [
      3361,
      ""
     ],
     [
      3670,
      "does not confess"
     ],
     [
      3588,
      ""
     ],
     [
      2424,
      "Jesus"
     ],
     [
      1510,
      "is"
     ],
     [
      3756,
      "not"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      ""
     ],
     [
      3778,
      "This"
     ],
     [
      1510,
      "is"
     ],
     [
      3588,
      "the [spirit]"
     ],
     [
      3588,
      "of the"
     ],
     [
      500,
      "antichrist"
     ],
     [
      3739,
      "which"
     ],
     [
      191,
      "you have heard"
     ],
     [
      3754,
      ""
     ],
     [
      2064,
      "is coming"
     ],
     [
      2532,
      "and"
     ],
     [
      1510,
      "[which] is"
     ],
     [
      2235,
      "already"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      3568,
      "at this time"
     ]
    ]
   },
   {
    "verse_number": 4,
    "words": [
     [
      4771,
      "You"
     ],
     [
      5040,
      "little children"
     ],
     [
      1510,
      "are"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      "and"
     ],
     [
      3528,
      "have overcome"
     ],
     [
      846,
      "them"
     ],
     [
      3754,
      "because"
     ],
     [
      3173,
      "greater"
     ],
     [
      1510,
      "is"
     ],
     [
      3588,
      "He who [is]"
     ],
     [
      1722,
      "in"
     ],
     [
      4771,
      "you"
     ],
     [
      2228,
      "than"
     ],
     [
      3588,
      "he who [is]"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ]
    ]
   },
   {
    "verse_number": 5,
    "words": [
     [
      846,
      "They"
     ],
     [
      1510,
      "are"
     ],
     [
      1537,
      "of"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      1223,
      "That is why"
     ],
     [
      3778,
      ""
     ],
     [
      2980,
      "they speak"
     ],
     [
      3588,
      "from the"
     ],
     [
      2889,
      "world’s"
     ],
     [
      1537,
      "perspective"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      191,
      "listens to"
     ],
     [
      846,
      "them"
     ]
    ]
   },
   {
    "verse_number": 6,
    "words": [
     [
      1473,
      "We"
     ],
     [
      1510,
      "are"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3588,
      "Whoever"
     ],
     [
      1097,
      "knows"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      191,
      "listens to"
     ],
     [
      1473,
      "us"
     ],
     [
      3739,
      "whoever"
     ],
     [
      1510,
      "is"
     ],
     [
      3756,
      "not"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3756,
      ""
     ],
     [
      191,
      "does not listen to"
     ],
     [
      1473,
      "us"
     ],
     [
      1537,
      "That is how"
     ],
     [
      3778,
      ""
     ],
     [
      1097,
      "we know"
     ],
     [
      3588,
      "the"
     ],
     [
      4151,
      "Spirit"
     ],
     [
      3588,
      ""
     ],
     [
      225,
      "of truth"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      "the"
     ],
     [
      4151,
      "spirit"
     ],
     [
      3588,
      ""
     ],
     [
      4106,
      "of deception"
     ]
    ]
   },
   {
    "verse_number": 7,
    "words": [
     [
      27,
      "Beloved"
     ],
     [
      25,
      "let us love"
     ],
     [
      240,
      "one another"
     ],
     [
      3754,
      "because"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      1510,
      "comes"
     ],
     [
      1537,
      "from"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      ""
     ],
     [
      3956,
      "Everyone"
     ],
     [
      3588,
      "who"
     ],
     [
      25,
      "loves"
     ],
     [
      1080,
      "has been born"
     ],
     [
      1537,
      "of"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      "and"
     ],
     [
      1097,
      "knows"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ]
    ]
   },
   {
    "verse_number": 8,
    "words": [
     [
      3588,
      "Whoever"
     ],
     [
      3361,
      ""
     ],
     [
      25,
      "does not love"
     ],
     [
      3756,
      ""
     ],
     [
      1097,
      "does not know"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3754,
      "because"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      1510,
      "is"
     ],
     [
      26,
      "love"
     ]
    ]
   },
   {
    "verse_number": 9,
    "words": [
     [
      1722,
      "This is how"
     ],
     [
      3778,
      ""
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God’s"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      5319,
      "was revealed"
     ],
     [
      1722,
      "among"
     ],
     [
      1473,
      "us"
     ],
     [
      3754,
      ""
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      649,
      "sent"
     ],
     [
      846,
      "His"
     ],
     [
      3588,
      ""
     ],
     [
      3439,
      "one and only"
     ],
     [
      3588,
      ""
     ],
     [
      5207,
      "Son"
     ],
     [
      1519,
      "into"
     ],
     [
      3588,
      "the"
     ],
     [
      2889,
      "world"
     ],
     [
      2443,
      "so that"
     ],
     [
      2198,
      "we might live"
     ],
     [
      1223,
      "through"
     ],
     [
      846,
      "Him"
     ]
    ]
   },
   {
    "verse_number": 10,
    "words": [
     [
      3588,
      ""
     ],
     [
      26,
      "[And] love"
     ],
     [
      1510,
      "consists"
     ],
     [
      1722,
      "in"
     ],
     [
      3778,
      "this"
     ],
     [
      3756,
      "not"
     ],
     [
      3754,
      "that"
     ],
     [
      1473,
      "we"
     ],
     [
      25,
      "loved"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      235,
      "but"
     ],
     [
      3754,
      "that"
     ],
     [
      846,
      "He"
     ],
     [
      25,
      "loved"
     ],
     [
      1473,
      "us"
     ],
     [
      2532,
      "and"
     ],
     [
      649,
      "sent"
     ],
     [
      846,
      "His"
     ],
     [
      3588,
      ""
     ],
     [
      5207,
      "Son"
     ],
     [
      2434,
      "[as the] atoning sacrifice"
     ],
     [
      4012,
      "for"
     ],
     [
      1473,
      "our"
     ],
     [
      3588,
      ""
     ],
     [
      266,
      "sins"
     ]
    ]
   },
   {
    "verse_number": 11,
    "words": [
     [
      27,
      "Beloved"
     ],
     [
      1487,
      "if"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3779,
      "so"
     ],
     [
      25,
      "loved"
     ],
     [
      1473,
      "us"
     ],
     [
      1473,
      "we"
     ],
     [
      2532,
      "also"
     ],
     [
      3784,
      "ought"
     ],
     [
      25,
      "to love"
     ],
     [
      240,
      "one another"
     ]
    ]
   },
   {
    "verse_number": 12,
    "words": [
     [
      3762,
      "No one"
     ],
     [
      2300,
      "has ever seen"
     ],
     [
      4455,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      1437,
      "[but] if"
     ],
     [
      25,
      "we love"
     ],
     [
      240,
      "one another"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3306,
      "remains"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "us"
     ],
     [
      2532,
      "and"
     ],
     [
      846,
      "His"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      1510,
      "is"
     ],
     [
      5048,
      "perfected"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "us"
     ]
    ]
   },
   {
    "verse_number": 13,
    "words": [
     [
      1722,
      "By"
     ],
     [
      3778,
      "this"
     ],
     [
      1097,
      "we know"
     ],
     [
      3754,
      "that"
     ],
     [
      3306,
      "we remain"
     ],
     [
      1722,
      "in"
     ],
     [
      846,
      "Him"
     ],
     [
      2532,
      "and"
     ],
     [
      846,
      "He"
     ],
     [
      1722,
      "in"
     ],
     [
      1473,
      "us"
     ],
     [
      3754,
      ""
     ],
     [
      1325,
      "He has given"
     ],
     [
      1473,
      "us"
     ],
     [
      1537,
      "of"
     ],
     [
      846,
      "His"
     ],
     [
      3588,
      ""
     ],
     [
      4151,
      "Spirit"
     ]
    ]
   },
   {
    "verse_number": 14,
    "words": [
     [
      2532,
      "And"
     ],
     [
      1473,
      "we"
     ],
     [
      2300,
      "have seen"
     ],
     [
      2532,
      "and"
     ],
     [
      3140,
      "testify"
     ],
     [
      3754,
      "that"
     ],
     [
      3588,
      "the"
     ],
     [
      3962,
      "Father"
     ],
     [
      649,
      "has sent"
     ],
     [
      3588,
      "[His]"
     ],
     [
      5207,
      "Son [to be]"
     ],
     [
      4990,
      "[the] Savior"
     ],
     [
      3588,
      "of the"
     ],
     [
      2889,
      "world"
     ]
    ]
   },
   {
    "verse_number": 15,
    "words": [
     [
      1437,
      "If"
     ],
     [
      3739,
      "anyone"
     ],
     [
      3670,
      "confesses"
     ],
     [
      3754,
      "that"
     ],
     [
      2424,
      "Jesus"
     ],
     [
      1510,
      "is"
     ],
     [
      3588,
      "the"
     ],
     [
      5207,
      "Son"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "of God"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3306,
      "abides"
     ],
     [
      1722,
      "in"
     ],
     [
      846,
      "him"
     ],
     [
      2532,
      "and"
     ],
     [
      846,
      "he"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ]
    ]
   },
   {
    "verse_number": 16,
    "words": [
     [
      2532,
      "And"
     ],
     [
      1473,
      "we"
     ],
     [
      1097,
      "have come to know"
     ],
     [
      2532,
      "and"
     ],
     [
      4100,
      "believe"
     ],
     [
      3588,
      "the"
     ],
     [
      26,
      "love"
     ],
     [
      3739,
      "that"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2192,
      "has"
     ],
     [
      1722,
      "for"
     ],
     [
      1473,
      "us"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      1510,
      "is"
     ],
     [
      26,
      "love"
     ],
     [
      2532,
      ""
     ],
     [
      3588,
      "whoever"
     ],
     [
      3306,
      "abides"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      3306,
      "abides"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      "and"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3306,
      ""
     ],
     [
      1722,
      "in"
     ],
     [
      846,
      "him"
     ]
    ]
   },
   {
    "verse_number": 17,
    "words": [
     [
      1722,
      "In"
     ],
     [
      3778,
      "this [way]"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      5048,
      "has been perfected"
     ],
     [
      3326,
      "among"
     ],
     [
      1473,
      "us"
     ],
     [
      2443,
      "so that"
     ],
     [
      2192,
      "we may have"
     ],
     [
      3954,
      "confidence"
     ],
     [
      1722,
      "on"
     ],
     [
      3588,
      "the"
     ],
     [
      2250,
      "day"
     ],
     [
      3588,
      ""
     ],
     [
      2920,
      "of judgment"
     ],
     [
      3754,
      "for"
     ],
     [
      1722,
      "in"
     ],
     [
      3778,
      "this"
     ],
     [
      3588,
      ""
     ],
     [
      2889,
      "world"
     ],
     [
      2532,
      ""
     ],
     [
      1473,
      "we"
     ],
     [
      1510,
      "are"
     ],
     [
      2531,
      "just like"
     ],
     [
      1565,
      "Him"
     ],
     [
      1510,
      ""
     ]
    ]
   },
   {
    "verse_number": 18,
    "words": [
     [
      1510,
      "There is"
     ],
     [
      3756,
      "no"
     ],
     [
      5401,
      "fear"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ],
     [
      235,
      "but"
     ],
     [
      3588,
      ""
     ],
     [
      5046,
      "perfect"
     ],
     [
      26,
      "love"
     ],
     [
      906,
      "drives"
     ],
     [
      1854,
      "out"
     ],
     [
      3588,
      ""
     ],
     [
      5401,
      "fear"
     ],
     [
      3754,
      "because"
     ],
     [
      3588,
      ""
     ],
     [
      5401,
      "fear"
     ],
     [
      2192,
      "involves"
     ],
     [
      2851,
      "punishment"
     ],
     [
      1161,
      ""
     ],
     [
      3588,
      "The [one who]"
     ],
     [
      5399,
      "fears"
     ],
     [
      3756,
      ""
     ],
     [
      5048,
      "has not been perfected"
     ],
     [
      1722,
      "in"
     ],
     [
      3588,
      ""
     ],
     [
      26,
      "love"
     ]
    ]
   },
   {
    "verse_number": 19,
    "words": [
     [
      1473,
      "We"
     ],
     [
      25,
      "love"
     ],
     [
      3754,
      "because"
     ],
     [
      846,
      "He"
     ],
     [
      4413,
      "first"
     ],
     [
      25,
      "loved"
     ],
     [
      1473,
      "us"
     ]
    ]
   },
   {
    "verse_number": 20,
    "words": [
     [
      1437,
      "If"
     ],
     [
      5100,
      "anyone"
     ],
     [
      2036,
      "says"
     ],
     [
      3754,
      ""
     ],
     [
      25,
      "I love"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      2532,
      "[but]"
     ],
     [
      3404,
      "hates"
     ],
     [
      846,
      "his"
     ],
     [
      3588,
      ""
     ],
     [
      80,
      "brother"
     ],
     [
      1510,
      "he is"
     ],
     [
      5583,
      "a liar"
     ],
     [
      1063,
      "For"
     ],
     [
      3588,
      "anyone who"
     ],
     [
      3361,
      ""
     ],
     [
      25,
      "does not love"
     ],
     [
      846,
      "his"
     ],
     [
      3588,
      ""
     ],
     [
      80,
      "brother"
     ],
     [
      3739,
      "whom"
     ],
     [
      3708,
      "he has seen"
     ],
     [
      3756,
      ""
     ],
     [
      1410,
      "cannot"
     ],
     [
      25,
      "love"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      3739,
      "whom"
     ],
     [
      3756,
      ""
     ],
     [
      3708,
      "he has not seen"
     ]
    ]
   },
   {
    "verse_number": 21,
    "words": [
     [
      2532,
      "And"
     ],
     [
      2192,
      "we have"
     ],
     [
      3778,
      "this"
     ],
     [
      3588,
      ""
     ],
     [
      1785,
      "commandment"
     ],
     [
      575,
      "from"
     ],
     [
      846,
      "Him"
     ],
     [
      2443,
      ""
     ],
     [
      3588,
      "Whoever"
     ],
     [
      25,
      "loves"
     ],
     [
      3588,
      ""
     ],
     [
      2316,
      "God"
     ],
     [
      25,
      "must love"
     ],
     [
      846,
      "his"
     ],
     [
      3588,
      ""
     ],
     [
      80,
      "brother"
     ],
     [
      2532,
      "as well"
     ]
    ]
   }
  ]
 }
];
  return r;
}
