export function bible_glyph_chapter_psa085() {
  "The forty ninth picture Bible chapter written by hand: the whole of the eighty fifth psalm, a prayer that God would turn back to a people He has already turned back once, in the shorthand a person types.";
  "IT IS THE FIFTH OF THE OLD TESTAMENT SURVEY AND THE FIRST TAKEN FROM BELOW THE TOP FOUR. Forty five in a hundred - ninety six words, forty three of them drawn, across thirteen verses. The four ahead of it are all now on this list, and the gap to the best remaining New Testament chapter is down to four, so this is close to the last entry that can be argued for on its share alone.";
  "THE WHOLE PSALM IS BUILT ON ONE WORD AND THE MARK FOR IT FALLS FIVE TIMES. The Hebrew word means to turn back, and English needs a different verb almost every time: You turned back the captivity, You turned back from Your anger, turn us back, will You not turn again and revive us, let them not turn back to folly. Five sentences that look unrelated in English are one sentence said five ways underneath, and the mark is what makes that visible. This is the plainest demonstration on the whole list of what a picture Bible is for.";
  "THE BOW IS THE MARK FOR SIN BECAUSE THE WORD MEANS TO MISS. The Hebrew word covered by the second verse is what an archer does when the arrow does not land - not a stain, not a debt, not a crime, a shot that went wide. English has no word that says it, so English says sin and leaves the reader to be told later what that means. The mark says it immediately and says it to someone who cannot read either language.";
  "THE TENTH AND ELEVENTH VERSES PUT FOUR THINGS TOGETHER AND ONLY THREE OF THEM ARE DRAWN. Loving devotion and faithfulness have joined together; righteousness and peace have kissed. Faithfulness springs up from the earth and righteousness looks down from heaven. Peace stands in letters because the table has not seated it, and the gap is visible on the page - the verse is built to pair them off two by two and one of the four is missing its picture. That is a thing to fix, and this page is where a reader can see the reason to.";
  "THE EYE IN THE SEVENTH VERSE MEANS SHOW AND NOT SEE. Hebrew turns a verb into its causative by changing the shape of the word rather than by adding another word, so one root gives both to see and to cause someone to see. The mark is seated on the root, so it stands here where English has to reach for a different verb entirely - show us Your loving devotion. A reader who has met the eye standing for seeing will meet it here standing for showing, and both are the same word.";
  "THE SPROUT STANDS FOR REVIVE, AND THE VERSE WHERE SOMETHING ACTUALLY SPROUTS HAS NO MARK AT ALL. The sixth verse asks whether God will revive us, and the word underneath is the ordinary word for living, which this table draws as a sprout. The eleventh verse says faithfulness springs up out of the ground, and that is a different Hebrew word which the table has not seated, so it stays in letters. The picture that looks like growing is on the abstract verse and absent from the literal one, which is exactly backwards from what a reader would guess, and it is worth knowing that the marks follow the roots and not the imagery.";
  "THE LAST VERSE IS ALREADY A PICTURE BEFORE ANY MARK IS PUT ON IT. Righteousness walks ahead of Him and prepares a road for His steps. Three of its words are drawn - the ruler, the walking and the road - and they are the three that carry the sentence, so this is the one verse in the chapter a reader could take without the English around it. A psalm that has spent twelve verses asking for something ends by drawing what the answer looks like arriving.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA085",
    reference: "Psalm 85",
    verses: [
      {
        verse_number: 1,
        words: [
          "You",
          "showed",
          "favor",
          "to",
          "Your",
          "$earth,",
          "O",
          "$name_tag;",
          "You",
          "$turn_back",
          "Jacob",
          "from",
          "captivity.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "You",
          "forgave",
          "the",
          "iniquity",
          "of",
          "Your",
          "$family;",
          "You",
          "covered",
          "all",
          "their",
          "$bow.",
          "Selah",
        ],
      },
      {
        verse_number: 3,
        words: [
          "You",
          "withheld",
          "all",
          "Your",
          "fury;",
          "You",
          "$turn_back",
          "from",
          "Your",
          "burning",
          "anger.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$turn_back",
          "us,",
          "O",
          "$fire",
          "of",
          "our",
          "salvation,",
          "and",
          "put",
          "away",
          "Your",
          "displeasure",
          "toward",
          "us.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Will",
          "You",
          "be",
          "angry",
          "with",
          "us",
          "$hourglass?",
          "Will",
          "You",
          "draw",
          "out",
          "Your",
          "anger",
          "to",
          "all",
          "generations?",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Will",
          "You",
          "$no_entry",
          "$turn_back",
          "and",
          "$sprout",
          "us,",
          "that",
          "Your",
          "$family",
          "may",
          "rejoice",
          "in",
          "You?",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$eye",
          "us",
          "Your",
          "$gift,",
          "O",
          "$name_tag,",
          "and",
          "$hands_giving",
          "us",
          "Your",
          "salvation.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "I",
          "will",
          "$ear",
          "what",
          "$fire",
          "the",
          "$name_tag",
          "will",
          "$mouth,",
          "for",
          "He",
          "will",
          "$mouth",
          "peace",
          "to",
          "His",
          "$family",
          "and",
          "His",
          "saints;",
          "but",
          "let",
          "them",
          "$no_entry",
          "$turn_back",
          "to",
          "folly.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Surely",
          "His",
          "salvation",
          "is",
          "near",
          "to",
          "those",
          "who",
          "fear",
          "Him,",
          "that",
          "$star",
          "may",
          "dwell",
          "in",
          "our",
          "$earth.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$gift",
          "and",
          "$check",
          "have",
          "joined",
          "together;",
          "$ruler",
          "and",
          "peace",
          "have",
          "kissed.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$check",
          "springs",
          "up",
          "from",
          "the",
          "$earth,",
          "and",
          "$ruler",
          "looks",
          "down",
          "from",
          "$sky.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "The",
          "$name_tag",
          "will",
          "indeed",
          "$hands_giving",
          "what",
          "is",
          "$thumbs_up,",
          "and",
          "our",
          "$earth",
          "will",
          "$hands_giving",
          "its",
          "increase.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$ruler",
          "$walking",
          "before",
          "Him",
          "to",
          "prepare",
          "the",
          "$road",
          "for",
          "His",
          "steps.",
        ],
      },
    ],
  };
  return chapter;
}
