export function bible_speech_attributions() {
  "Who speaks each of the thirty quotations in the Berean that no rule can attribute - the hand rulings that finish the cast, one row per quotation, with the reason the machine could not reach it.";
  "★ THIS IS THE HAND WORK ITSELF AND IT IS THIRTY ROWS LONG, WHICH IS THE WHOLE OF WHAT A PERSON OWES THE ENTIRE BIBLE. Six thousand and eighty-eight quotations were parsed; five rules answered six thousand and fifty-eight of them; these are the remainder. Every one was read with the narration on both sides before it was ruled on, and the reason field says which of four situations it was.";
  "★ THE PROPHETS DO NOT ANSWER THEMSELVES, WHICH IS THE THING MOST EASILY GOT WRONG HERE. The default speaker for Isaiah is ISAIAH and for Jeremiah is JEREMIAH, on purpose - most divine speech in a prophet sits inside a quotation the prophet opens after a formula, so the prophet is the fallback and God is the marked voice. That makes an unannounced divine speech exactly the case the default CANNOT cover: falling back would put the LORD's words in the prophet's mouth. Seventeen of these thirty are that, and they are the reason this table has to exist rather than being folded into the book defaults.";
  "★ THE QUOTATION IS IDENTIFIED BY ITS OPENING WORDS AND NOT BY A POSITION, BECAUSE THE POSITION IS THE PARSER'S AND THE WORDS ARE SCRIPTURE'S. A verse can hold several quotations, so a verse number alone does not name one; an ordinal within the verse would name one until the day a rule changes what counts as a quotation, and would then silently name a different one. The opening words move only if the translation changes, which is a thing somebody does on purpose.";
  "★ TWO ROWS ARE ENTERED AS UNDECIDED RATHER THAN GUESSED, AND THAT IS THE POINT OF HAVING A REASON FIELD. First Chronicles 16:41 quotes the refrain HIS LOVING DEVOTION ENDURES FOREVER as the content of what the singers were appointed to give thanks with, which is either the singers singing or the narrator citing a line; and Jeremiah 51:9 says WE TRIED TO HEAL BABYLON without ever saying who WE is - the exiles living in her, or the nations that traded with her. Both change how the line is read aloud, so a table that quietly picked one would be hiding a decision inside data.";
  "★ A SPLIT QUOTATION IS NAMED ON ITS SIBLING AND NOT ON ITSELF, AND NINE OF THESE ARE THAT. First Samuel 27:10 reads AGAINST THE NEGEV OF JUDAH, or THE NEGEV OF JERAHMEEL, or THE NEGEV OF THE KENITES - one answer of David's, closed and reopened twice around the word OR. The narration between the pieces is that one word, so nothing near the second and third pieces says who is talking while the first piece is fully attributed. This is a translator's typography rather than anything about the text, and it is why the pieces are ruled rather than a rule being written for them.";
  let attributions = [
    {
      chapter_code: "DEU02",
      verse_number: "13",
      opening: "Now arise and cross over the Brook of Zered.",
      speaker: "the LORD",
      reason: "resumed after the narrator's aside",
    },
    {
      chapter_code: "DEU32",
      verse_number: "34",
      opening: "Have I not stored up these things",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "1SA27",
      verse_number: "10",
      opening: "The Negev of Jerahmeel,",
      speaker: "David",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "1SA27",
      verse_number: "10",
      opening: "The Negev of the Kenites.",
      speaker: "David",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "1CH16",
      verse_number: "36",
      opening: "Praise the LORD!",
      speaker: "all the people",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "1CH16",
      verse_number: "41",
      opening: "His loving devotion endures forever.",
      speaker: "the appointed singers",
      reason: "a quoted refrain, sung by the men the verse appoints",
    },
    {
      chapter_code: "NEH10",
      verse_number: "28",
      opening: "The rest of the people",
      speaker: "those who sealed the covenant",
      reason: "the covenant text quoted with no attribution",
    },
    {
      chapter_code: "PSA046",
      verse_number: "10",
      opening: "Be still and know that I am God",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "PSA091",
      verse_number: "14",
      opening: "Because he loves Me, I will deliver him",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ECC02",
      verse_number: "2",
      opening: "What does it accomplish?",
      speaker: "the Preacher",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "ISA03",
      verse_number: "4",
      opening: "I will make mere lads their leaders",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA05",
      verse_number: "3",
      opening: "And now, O dwellers of Jerusalem",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA30",
      verse_number: "16",
      opening: "We will ride swift horses,",
      speaker: "the men of Judah",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "ISA41",
      verse_number: "1",
      opening: "Be silent before Me, O islands",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA46",
      verse_number: "3",
      opening: "Listen to Me, O house of Jacob",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA47",
      verse_number: "5",
      opening: "Sit in silence and go into darkness",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA51",
      verse_number: "1",
      opening: "Listen to Me, you who pursue righteousness",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA63",
      verse_number: "1",
      opening: "It is I, proclaiming vindication",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ISA63",
      verse_number: "3",
      opening: "I have trodden the winepress alone",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "JER04",
      verse_number: "22",
      opening: "For My people are fools",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "JER06",
      verse_number: "27",
      opening: "I have appointed you to examine My people",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "JER09",
      verse_number: "11",
      opening: "And I will make Jerusalem a heap of rubble",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "JER51",
      verse_number: "9",
      opening: "We tried to heal Babylon",
      speaker: "the foreigners in Babylon",
      reason: "an unnamed voice, narrowed by its own words",
    },
    {
      chapter_code: "HOS10",
      verse_number: "8",
      opening: "Fall on us!",
      speaker: "the people of Israel",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "HAB01",
      verse_number: "5",
      opening: "Look at the nations and observe",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "ZEP02",
      verse_number: "12",
      opening: "You too, O Cushites",
      speaker: "the LORD",
      reason: "divine speech opened with no formula",
    },
    {
      chapter_code: "MAL02",
      verse_number: "17",
      opening: "Where is the God of justice?",
      speaker: "the people",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "LUK07",
      verse_number: "31",
      opening: "To what, then, can I compare",
      speaker: "Jesus",
      reason: "resumed after the narrator's aside",
    },
    {
      chapter_code: "JHN04",
      verse_number: "27",
      opening: "Why are You talking with her?",
      speaker: "the disciples",
      reason: "split quotation named on its sibling",
    },
    {
      chapter_code: "REV16",
      verse_number: "15",
      opening: "Behold, I am coming like a thief.",
      speaker: "Jesus",
      reason: "resumed after the narrator's aside",
    },
  ];
  return attributions;
}
