export function bible_glyph_chapter_psa034() {
  "Psalm 34, drawn in pictures, so that a person who cannot read the letters can still follow it. David wrote it after escaping a foreign king by pretending to be mad, and it turns from thanking God into teaching children how to live. Twenty two lines.";
  "THE LINE THAT SAYS LET US EXALT HIS NAME TOGETHER ARRIVES COMPLETELY BLANK. One picture in this collection, a luggage tag, carries two different Hebrew words: the covenant name of God, and the ordinary word for a name. When a single line uses both, a reader cannot tell which tag means which, so every tag in that line has to come off. The third line says magnify the LORD with me, let us exalt His name together, and it holds both words. It therefore loses both marks, and since it has no other words with pictures, it is the only line here with nothing on it at all. This is now the fourth book where that collision has been found, after Exodus 33, Exodus 34 and Isaiah 43, and every single time it has landed on the line the passage exists for.";
  "TWO DIFFERENT BLESSINGS GET TWO DIFFERENT PICTURES, WHICH IS BETTER THAN ENGLISH MANAGES. The first line says I will bless the LORD, and the eighth says blessed is the man who takes refuge in Him. English uses one word twice; Hebrew uses two entirely unrelated ones. The first means to speak well of somebody and is drawn as a speaking mark joined to a thumb up. The second means how happy, and is drawn as a gift joined to a smile. Both survive here, because neither line happens to contain a plain speaking mark, a plain thumb, a plain gift or a plain smile beside them. So a reader with only the pictures can see that the man blessing God and the man who is blessed are doing two different things, which a reader of the English cannot.";
  "TASTE AND SEE THAT THE LORD IS GOOD, EXCEPT THE PAGE CANNOT TASTE. Seeing is drawn, good is drawn as a thumb up, and the name is drawn. Tasting has no picture, so the most quoted sentence in the psalm arrives with its first and stranger half missing, and what is left is only look and see. There is a mouth in this collection, but on this page it is already spending itself on the thirteenth line, where it stands for speech. The picture that would be closest to a taste is busy being a word.";
  "NOT ONE OF HIS BONES WILL BE BROKEN, AND THERE IS NO PICTURE FOR A BONE. The twentieth line is the one the gospel of John quotes at the cross, and the only mark it can put down is the refusal. The bone itself is invisible. This is the second time in one night that a chapter has turned on bones and been unable to draw them, after Ezekiel 37, where the word is said eleven times.";
  "THE BROKEN HEART HAD TO BE DUG OUT OF THE ENGLISH BEFORE IT COULD BE DRAWN. The eighteenth line says the LORD is near to the brokenhearted. In Hebrew that is two words, broken and heart, and the heart is a real word with a real picture. English welds them into one, and a machine reading the English word by word finds nothing to hang the heart on. So the line here is written as those broken of heart, which is what the Hebrew actually says, and the picture goes back on. Nothing else in the verse changes. It is worth noticing how close this psalm came to losing its tenderest sentence to a hyphen.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA034",
    reference: "Psalm 34",
    verses: [
      {
        verse_number: 1,
        words: [
          "Of",
          "David,",
          "when",
          "he",
          "pretended",
          "to",
          "be",
          "insane",
          "before",
          "Abimelech,",
          "so",
          "that",
          "the",
          "king",
          "drove",
          "him",
          "$walking.",
          "I",
          "will",
          "$speech+thumbs_up",
          "the",
          "$name_tag",
          "at",
          "all",
          "times;",
          "His",
          "praise",
          "will",
          "always",
          "be",
          "on",
          "my",
          "lips.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "My",
          "$person_other",
          "boasts",
          "in",
          "the",
          "$name_tag;",
          "let",
          "the",
          "oppressed",
          "$ear",
          "and",
          "rejoice.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Magnify",
          "the",
          "LORD",
          "with",
          "me;",
          "let",
          "us",
          "exalt",
          "His",
          "name",
          "together.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "sought",
          "the",
          "$name_tag,",
          "and",
          "He",
          "answered",
          "me;",
          "He",
          "delivered",
          "me",
          "from",
          "all",
          "my",
          "fears.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Those",
          "who",
          "look",
          "to",
          "Him",
          "are",
          "radiant",
          "with",
          "joy;",
          "their",
          "faces",
          "shall",
          "$no_entry",
          "be",
          "ashamed.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "This",
          "poor",
          "man",
          "called",
          "out,",
          "and",
          "the",
          "$name_tag",
          "$ear",
          "him;",
          "He",
          "saved",
          "him",
          "from",
          "all",
          "his",
          "troubles.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$angel",
          "of",
          "the",
          "$name_tag",
          "encamps",
          "around",
          "those",
          "who",
          "fear",
          "Him,",
          "and",
          "he",
          "delivers",
          "them.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Taste",
          "and",
          "$eye",
          "that",
          "the",
          "$name_tag",
          "is",
          "$thumbs_up;",
          "$gift+smile",
          "is",
          "the",
          "man",
          "who",
          "takes",
          "refuge",
          "in",
          "Him.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Fear",
          "the",
          "$name_tag,",
          "you",
          "His",
          "$sparkle",
          "ones,",
          "for",
          "those",
          "who",
          "fear",
          "Him",
          "lack",
          "nothing.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Young",
          "lions",
          "go",
          "lacking",
          "and",
          "hungry,",
          "but",
          "those",
          "who",
          "seek",
          "the",
          "$name_tag",
          "will",
          "$no_entry",
          "lack",
          "any",
          "$thumbs_up",
          "thing.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$walking,",
          "$son,",
          "$ear",
          "to",
          "me;",
          "I",
          "will",
          "teach",
          "you",
          "the",
          "fear",
          "of",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Who",
          "is",
          "the",
          "$man_beard",
          "who",
          "delights",
          "in",
          "$sprout,",
          "who",
          "$heart_red",
          "many",
          "$sun",
          "so",
          "that",
          "he",
          "may",
          "$eye",
          "$thumbs_up?",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Keep",
          "your",
          "tongue",
          "from",
          "$thumbs_down",
          "and",
          "your",
          "lips",
          "from",
          "deceitful",
          "$mouth.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Turn",
          "away",
          "from",
          "$thumbs_down",
          "and",
          "$hammer",
          "$thumbs_up;",
          "seek",
          "peace",
          "and",
          "pursue",
          "it.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "The",
          "$eyes",
          "of",
          "the",
          "$name_tag",
          "are",
          "on",
          "the",
          "$ruler,",
          "and",
          "His",
          "ears",
          "are",
          "inclined",
          "to",
          "their",
          "cry.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "The",
          "face",
          "of",
          "the",
          "$name_tag",
          "is",
          "$hammer",
          "those",
          "who",
          "do",
          "$thumbs_down,",
          "to",
          "wipe",
          "out",
          "their",
          "memory",
          "from",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "The",
          "righteous",
          "cry",
          "out,",
          "and",
          "the",
          "$name_tag",
          "$ear;",
          "He",
          "delivers",
          "them",
          "from",
          "all",
          "their",
          "troubles.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "The",
          "$name_tag",
          "is",
          "near",
          "to",
          "those",
          "broken",
          "of",
          "$heart_organ,",
          "and",
          "He",
          "saves",
          "the",
          "contrite",
          "in",
          "$wind.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Many",
          "are",
          "the",
          "$thumbs_down",
          "of",
          "the",
          "$ruler,",
          "but",
          "the",
          "$name_tag",
          "delivers",
          "him",
          "from",
          "them",
          "all.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "He",
          "protects",
          "all",
          "his",
          "bones;",
          "$no_entry",
          "one",
          "of",
          "them",
          "will",
          "be",
          "broken.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$thumbs_down",
          "will",
          "$skull",
          "the",
          "$thumbs_down,",
          "and",
          "the",
          "haters",
          "of",
          "the",
          "$ruler",
          "will",
          "be",
          "condemned.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "The",
          "$name_tag",
          "redeems",
          "His",
          "$kneeling,",
          "and",
          "$no_entry",
          "who",
          "take",
          "refuge",
          "in",
          "Him",
          "will",
          "be",
          "condemned.",
        ],
      },
    ],
  };
  return chapter;
}
