export function bible_glyph_chapter_job38() {
  "Job 38, drawn in pictures. After thirty seven chapters of men arguing about why Job is suffering, God finally speaks, and He does not answer the question. He asks question after question of His own instead - where were you when I laid the foundations, have you been to the storehouses of the snow, can you feed a lion. Forty one lines, almost all of them questions.";
  "THIS BIBLE OWNS A PICTURE OF A STAR AND CANNOT SPEND IT ON A SINGLE STAR IN THIS CHAPTER. The star is seated on the Hebrew word for glory, not on the thing in the sky, so it is unavailable here on principle rather than by accident. The seventh verse has the morning stars singing together, the thirty first has the Pleiades and the belt of Orion, and the thirty second has the Bear and her cubs led out in their seasons. Four star names in a chapter about the sky, and every one of them is in plain letters while the picture of a star sits in the table meaning something else. It is the sharpest example in this project of a mark being worth more as a meaning than as a likeness.";
  "THE MARK FOR A VOICE IS DRAWN ONCE IN FORTY ONE VERSES AND IT IS NOT GODS. God does the talking for the whole chapter and the page carries that with the mark for speaking, three times. The separate mark for a voice, the sound itself, lands in the twenty fifth verse on the thunder, because the Hebrew word for a voice and the Hebrew word for thunder are the same word. So in a speech delivered out of a storm, the only sound the page draws is the storm.";
  "THE WEATHER IS THE SUBJECT AND ALMOST NONE OF IT CAN BE DRAWN. The whirlwind God speaks out of in the first verse has no picture. Neither do the clouds, which are named three times, nor the snow, the hail, the rain, the dew, the ice or the frost. The page can draw water once it is water and it can draw the sky it falls out of, but every form the water takes on the way down is in plain letters. A reader following the pictures gets the earth, the sea and the sky and has to take the whole middle of the weather on trust.";
  "THE QUESTIONS ARE ABOUT KNOWING AND THE KNOWING MARK IS THE ONE THAT KEEPS COMING BACK. Seven times God asks whether Job knows, understands or can tell Him, and the same little picture goes down each time - the third verse, the fourth, the fifth, the twelfth, the eighteenth, the twenty first and the thirty third. Nothing else in the chapter is repeated as an idea that often. It is the closest the page comes to showing that these are not a heap of separate questions but one question asked over and over.";
  "THE MARK THIS BIBLE USES FOR ALIVE IS DRAWN ON A LIONS HUNGER. The chapter ends by leaving the sky and going to two animals, and the only picture in the thirty ninth verse is the one for a living thing, sitting on the appetite of young lions waiting in a thicket. The last verse gives the raven chicks a picture too, the one for a child, and has them crying out to God. So a book that spends thirty seven chapters on whether God is paying attention closes its first answer on Him feeding something that cannot ask.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "JOB38",
    reference: "Job 38",
    verses: [
      {
        verse_number: 1,
        words: [
          "Then",
          "the",
          "$name_tag",
          "answered",
          "Job",
          "$tray_out",
          "the",
          "whirlwind",
          "and",
          "$speech:",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Who",
          "is",
          "this",
          "who",
          "obscures",
          "My",
          "counsel",
          "by",
          "words",
          "without",
          "knowledge?",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Now",
          "brace",
          "yourself",
          "like",
          "a",
          "man;",
          "I",
          "will",
          "question",
          "you,",
          "and",
          "you",
          "shall",
          "$lightbulb",
          "Me.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Where",
          "were",
          "you",
          "when",
          "I",
          "laid",
          "the",
          "foundations",
          "of",
          "the",
          "$earth?",
          "Tell",
          "Me,",
          "if",
          "you",
          "have",
          "$lightbulb.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Who",
          "fixed",
          "its",
          "measurements?",
          "Surely",
          "you",
          "$lightbulb!",
          "Or",
          "who",
          "stretched",
          "a",
          "measuring",
          "line",
          "across",
          "it?",
        ],
      },
      {
        verse_number: 6,
        words: [
          "On",
          "what",
          "were",
          "its",
          "foundations",
          "set,",
          "or",
          "who",
          "laid",
          "its",
          "cornerstone,",
        ],
      },
      {
        verse_number: 7,
        words: [
          "while",
          "the",
          "morning",
          "stars",
          "sang",
          "together",
          "and",
          "all",
          "the",
          "$son",
          "of",
          "$fire",
          "shouted",
          "for",
          "joy?",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Who",
          "enclosed",
          "the",
          "$sea",
          "behind",
          "doors",
          "when",
          "it",
          "burst",
          "forth",
          "from",
          "the",
          "womb,",
        ],
      },
      {
        verse_number: 9,
        words: [
          "when",
          "I",
          "made",
          "the",
          "clouds",
          "its",
          "garment",
          "and",
          "thick",
          "darkness",
          "its",
          "blanket,",
        ],
      },
      {
        verse_number: 10,
        words: [
          "when",
          "I",
          "fixed",
          "its",
          "boundaries",
          "and",
          "set",
          "in",
          "place",
          "its",
          "bars",
          "and",
          "doors,",
        ],
      },
      {
        verse_number: 11,
        words: [
          "and",
          "I",
          "$speech,",
          "You",
          "may",
          "$footprints",
          "this",
          "far,",
          "but",
          "$no_entry",
          "farther;",
          "here",
          "your",
          "proud",
          "waves",
          "must",
          "stop?",
        ],
      },
      {
        verse_number: 12,
        words: [
          "In",
          "your",
          "$sun",
          "have",
          "you",
          "commanded",
          "the",
          "morning",
          "or",
          "$lightbulb",
          "the",
          "dawn",
          "its",
          "place,",
        ],
      },
      {
        verse_number: 13,
        words: [
          "that",
          "it",
          "might",
          "spread",
          "to",
          "the",
          "ends",
          "of",
          "the",
          "$earth",
          "and",
          "shake",
          "the",
          "$thumbs_down",
          "$tray_out",
          "it?",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "$earth",
          "takes",
          "shape",
          "like",
          "clay",
          "under",
          "a",
          "seal;",
          "its",
          "hills",
          "stand",
          "out",
          "like",
          "the",
          "folds",
          "of",
          "a",
          "garment.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "$light",
          "is",
          "withheld",
          "from",
          "the",
          "$thumbs_down,",
          "and",
          "their",
          "upraised",
          "arm",
          "is",
          "broken.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "Have",
          "you",
          "$footprints",
          "to",
          "the",
          "vents",
          "of",
          "the",
          "$sea",
          "or",
          "$walking",
          "in",
          "the",
          "trenches",
          "of",
          "the",
          "deep?",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Have",
          "the",
          "gates",
          "of",
          "$skull",
          "been",
          "revealed",
          "to",
          "you?",
          "Have",
          "you",
          "$eye",
          "the",
          "gates",
          "of",
          "the",
          "shadow",
          "of",
          "death?",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Have",
          "you",
          "surveyed",
          "the",
          "extent",
          "of",
          "the",
          "$earth?",
          "Tell",
          "Me,",
          "if",
          "you",
          "$lightbulb",
          "all",
          "this.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Where",
          "is",
          "the",
          "$road",
          "to",
          "the",
          "home",
          "of",
          "$light?",
          "And",
          "where",
          "does",
          "$darkness",
          "reside,",
        ],
      },
      {
        verse_number: 20,
        words: [
          "so",
          "that",
          "you",
          "can",
          "$hand_receiving",
          "it",
          "to",
          "its",
          "border?",
          "Do",
          "you",
          "know",
          "the",
          "paths",
          "to",
          "its",
          "$house?",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Surely",
          "you",
          "$lightbulb,",
          "for",
          "you",
          "were",
          "already",
          "born!",
          "And",
          "the",
          "number",
          "of",
          "your",
          "$sun",
          "is",
          "great!",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Have",
          "you",
          "$footprints",
          "the",
          "storehouses",
          "of",
          "snow,",
          "or",
          "$eye",
          "the",
          "storehouses",
          "of",
          "hail,",
        ],
      },
      {
        verse_number: 23,
        words: [
          "which",
          "I",
          "hold",
          "in",
          "reserve",
          "for",
          "times",
          "of",
          "trouble,",
          "for",
          "the",
          "$sun",
          "of",
          "war",
          "and",
          "battle?",
        ],
      },
      {
        verse_number: 24,
        words: [
          "In",
          "which",
          "$road",
          "is",
          "the",
          "$light",
          "dispersed,",
          "or",
          "the",
          "east",
          "wind",
          "scattered",
          "over",
          "the",
          "$earth?",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Who",
          "cuts",
          "a",
          "channel",
          "for",
          "the",
          "flood,",
          "or",
          "clears",
          "a",
          "$road",
          "for",
          "the",
          "$voice",
          "of",
          "the",
          "thunderbolt,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "to",
          "bring",
          "rain",
          "on",
          "a",
          "barren",
          "$earth,",
          "$no_entry",
          "inhabited,",
          "on",
          "a",
          "desert",
          "where",
          "$no_entry",
          "$person",
          "lives,",
        ],
      },
      {
        verse_number: 27,
        words: [
          "to",
          "satisfy",
          "the",
          "parched",
          "wasteland",
          "and",
          "make",
          "the",
          "tender",
          "grass",
          "sprout?",
        ],
      },
      {
        verse_number: 28,
        words: [
          "Does",
          "the",
          "rain",
          "have",
          "a",
          "$father?",
          "Who",
          "has",
          "begotten",
          "the",
          "drops",
          "of",
          "dew?",
        ],
      },
      {
        verse_number: 29,
        words: [
          "From",
          "whose",
          "womb",
          "does",
          "the",
          "ice",
          "emerge?",
          "Who",
          "gives",
          "birth",
          "to",
          "the",
          "frost",
          "from",
          "$sky,",
        ],
      },
      {
        verse_number: 30,
        words: [
          "when",
          "the",
          "$water",
          "become",
          "hard",
          "as",
          "stone",
          "and",
          "the",
          "surface",
          "of",
          "the",
          "deep",
          "is",
          "frozen?",
        ],
      },
      {
        verse_number: 31,
        words: [
          "Can",
          "you",
          "bind",
          "the",
          "chains",
          "of",
          "the",
          "Pleiades",
          "or",
          "loosen",
          "the",
          "belt",
          "of",
          "Orion?",
        ],
      },
      {
        verse_number: 32,
        words: [
          "Can",
          "you",
          "bring",
          "forth",
          "the",
          "constellations",
          "in",
          "their",
          "seasons,",
          "or",
          "lead",
          "out",
          "the",
          "Bear",
          "and",
          "her",
          "$son?",
        ],
      },
      {
        verse_number: 33,
        words: [
          "Do",
          "you",
          "$lightbulb",
          "the",
          "laws",
          "of",
          "$sky?",
          "Can",
          "you",
          "set",
          "their",
          "dominion",
          "over",
          "the",
          "$earth?",
        ],
      },
      {
        verse_number: 34,
        words: [
          "Can",
          "you",
          "command",
          "the",
          "clouds",
          "so",
          "that",
          "a",
          "flood",
          "of",
          "$water",
          "covers",
          "you?",
        ],
      },
      {
        verse_number: 35,
        words: [
          "Can",
          "you",
          "send",
          "the",
          "lightning",
          "bolts",
          "on",
          "their",
          "$walking?",
          "Do",
          "they",
          "$speech",
          "to",
          "you,",
          "Here",
          "we",
          "are?",
        ],
      },
      {
        verse_number: 36,
        words: [
          "Who",
          "has",
          "put",
          "wisdom",
          "in",
          "the",
          "heart,",
          "or",
          "$hands_giving",
          "understanding",
          "to",
          "the",
          "mind?",
        ],
      },
      {
        verse_number: 37,
        words: [
          "Who",
          "has",
          "the",
          "wisdom",
          "to",
          "count",
          "the",
          "clouds?",
          "Or",
          "who",
          "can",
          "tilt",
          "the",
          "water",
          "jars",
          "of",
          "$sky,",
        ],
      },
      {
        verse_number: 38,
        words: [
          "when",
          "the",
          "dust",
          "hardens",
          "into",
          "a",
          "mass",
          "and",
          "the",
          "clods",
          "of",
          "earth",
          "stick",
          "together?",
        ],
      },
      {
        verse_number: 39,
        words: [
          "Can",
          "you",
          "hunt",
          "the",
          "prey",
          "for",
          "a",
          "lioness",
          "or",
          "satisfy",
          "the",
          "$sprout",
          "of",
          "young",
          "lions",
        ],
      },
      {
        verse_number: 40,
        words: [
          "when",
          "they",
          "crouch",
          "in",
          "their",
          "dens",
          "and",
          "lie",
          "in",
          "wait",
          "in",
          "the",
          "thicket?",
        ],
      },
      {
        verse_number: 41,
        words: [
          "Who",
          "provides",
          "food",
          "for",
          "the",
          "raven",
          "when",
          "its",
          "$child",
          "cry",
          "out",
          "to",
          "$fire",
          "as",
          "they",
          "wander",
          "about",
          "for",
          "lack",
          "of",
          "food?",
        ],
      },
    ],
  };
  return chapter;
}
