export function bible_glyph_chapter_psa023() {
  "The eighteenth picture Bible chapter written by hand: the whole of the twenty third psalm, in the shorthand a person types.";
  "THIS IS THE PSALM THAT BOUGHT THE SHEEP AND THE WORD SHEEP IS NOT IN IT. Tson does not occur here once; what occurs is raah, the shepherd, and the shepherd is the human and the sheep drawn together. So the picture this chapter is responsible for arrives in the very first line as half of a group, and the half it needs was bought by counting a word that appears somewhere else entirely. That is the ordinary way a vocabulary grows and it looks backwards written down: the chapter asks, the count answers about a different word, and the answer is what makes the chapter readable.";
  "THE FIRST VERSE IS THE WHOLE ARGUMENT AND IT IS FOUR MARKS LONG. The name tag, the human beside the sheep, the no entry sign, and then a plain English want. A reader who has met the sheep in the hundredth psalm as a flock and the standing human anywhere at all reads shepherd here without being told, which is the entire claim the group was seated on. If it fails here it fails everywhere, because there is no easier sentence in the Bible to read it in.";
  "AND THE SOUL IS A DIFFERENT FIGURE ON PURPOSE. The third verse draws nephesh as the other human, and the shepherd's human is the plain standing one - two figures, not one. Had they been the same character the third verse would have said He restores my shepherd, which is not a sentence anybody meant. The table already separated them long before this chapter needed it, and that is what a seated vocabulary is for: the hazard was gone before the chapter that would have hit it was written.";
  "THE ROD AND THE STAFF STAY IN ENGLISH AND THAT WAS SETTLED BY COUNTING, NOT BY TASTE. Shebet is glossed the tribe seventy one times against the rod and the scepter nine, so a picture on it would draw a stick over Judah and Benjamin through most of the Old Testament - the identical trap matteh was refused for. Mishenah, the staff, is twelve occurrences in the whole Hebrew Bible, which is under the size anything else in this table was bought at. Both refusals were reached before this chapter was written and neither was reached by looking at this chapter.";
  "THE FIFTH VERSE IS THE MOST PAINTED SENTENCE IN THE PSALM AND IT DRAWS NOTHING AT ALL. A table, enemies, oil, a head, a cup running over - and every one of those words is unseated, so the whole verse is plain English between two heavily marked ones. That is worth leaving visible rather than hiding: a picture Bible that drew wherever the imagery was vivid would be illustrating, and this one draws where a word is seated and nowhere else. The verse a reader remembers is the verse with no marks in it.";
  "AND THE OIL IN IT IS EXACTLY THE OIL THAT WAS REFUSED. Shemen is the substance and it was kept unseated on purpose when mashach was seated, because the drop of oil in this table means anointed one and drawing it on shemen would put the Messiah over every jar of cooking oil in Leviticus. The verb here is not mashach either - it is dashen, to make fat, and it is glossed You anoint. So the one verse in this psalm that an English reader would call the anointing contains neither of the two words the anointing was seated on.";
  "THE RETURNING IS DRAWN IN THE THIRD VERSE AND LEFT IN ENGLISH IN THE SIXTH, AND IT IS ONE WORD BOTH TIMES. Shuv is He restores my soul and it is also the last clause, where the interlinear keys the word to shuv and glosses it and I will dwell - the consonants read return and the reading handed down is dwell, which is the second textual crux this Bible has met after the hundredth psalm's not and to Him. The arrow is drawn on the first and refused on the second, because a reader who has just learned the arrow means turn back in verse three would be told in verse six that it means stay. One mark cannot say both in one chapter.";
  "THE DAYS ARE DRAWN TWICE AND EVERY TRANSLATION CALLS THE SECOND ONE FOREVER. Yom is all the days of my life and yom again in the final phrase, which is literally for length of days, and English turns the second into an adverb so the repetition disappears. The English here follows the Hebrew instead, so the sun is drawn at both ends of the verse and the reader can see that the psalm closes by saying days a second time. Forever would have been the smoother word and it would have cost the only thing this Bible exists to show.";
  let chapter = {
    chapter_code: "PSA023",
    reference: "Psalm 23",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "$name_tag",
          "is",
          "my",
          "$person+sheep;",
          "I",
          "shall",
          "$no_entry",
          "want.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "He",
          "makes",
          "me",
          "lie",
          "down",
          "in",
          "green",
          "pastures;",
          "He",
          "leads",
          "me",
          "beside",
          "quiet",
          "$water.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "He",
          "$turn_back",
          "my",
          "$person_other;",
          "He",
          "guides",
          "me",
          "in",
          "the",
          "paths",
          "of",
          "righteousness",
          "for",
          "the",
          "sake",
          "of",
          "His",
          "$name_tag.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Even",
          "though",
          "I",
          "$walking",
          "through",
          "the",
          "valley",
          "of",
          "the",
          "shadow",
          "of",
          "death,",
          "I",
          "will",
          "$no_entry",
          "fear",
          "$thumbs_down,",
          "for",
          "You",
          "are",
          "with",
          "me;",
          "Your",
          "rod",
          "and",
          "Your",
          "staff,",
          "they",
          "comfort",
          "me.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "prepare",
          "a",
          "table",
          "before",
          "me",
          "in",
          "the",
          "presence",
          "of",
          "my",
          "enemies;",
          "You",
          "anoint",
          "my",
          "head",
          "with",
          "oil;",
          "my",
          "cup",
          "overflows.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Surely",
          "$thumbs_up",
          "and",
          "$gift",
          "will",
          "follow",
          "me",
          "all",
          "the",
          "$sun",
          "of",
          "my",
          "$sprout,",
          "and",
          "I",
          "will",
          "dwell",
          "in",
          "the",
          "$house",
          "of",
          "the",
          "$name_tag",
          "for",
          "the",
          "length",
          "of",
          "$sun.",
        ],
      },
    ],
  };
  return chapter;
}
