export function bible_glyph_chapter_lev12() {
  "The twelfth chapter of Leviticus, drawn in pictures. Eight verses about a woman who has just given birth, how long she waits, and what she brings at the end of the waiting. It is the shortest chapter in the book and almost all of it is counting.";
  "THE WORD FOR DAY IS USED NINE TIMES IN EIGHT VERSES. Nothing else in the chapter comes close. The chapter is not describing a state so much as counting off a length of time, and the counting is the content.";
  "THE NUMBERS FOR A DAUGHTER ARE EXACTLY DOUBLE THE NUMBERS FOR A SON. Seven days and then thirty three at verses two and four. Two weeks and then sixty six at verse five. Fourteen is twice seven and sixty six is twice thirty three. The chapter sets the two side by side and never says why.";
  "THE WORD FOR SON IS USED FIVE TIMES AND ONLY ONCE IS IT A CHILD. At verse two it is the sons of Israel. At verse six it is a son, and then twice more in the same verse it is not: a lamb a son of its year, and a pigeon a son of a dove. At verse eight it is sons of a dove again. Hebrew says son of to give an age and to give a kind.";
  "VERSE THREE IS THE ONLY THING IN THE CHAPTER THE CHILD DOES. One sentence, the eighth day, circumcision. The word for circumcise and the word for eighth are each used once and never again. Everything on either side of that verse is about the mother.";
  "UNCLEAN IS SAID THREE TIMES AND CLEAN IS SAID SIX, WHICH IS THE REVERSE OF THE CHAPTER BEFORE. Leviticus eleven said unclean thirty four times against four. Here the word for purification is used four times and the verb for becoming clean twice, and it is the last word of the chapter.";
  "THE WOMAN WHO CANNOT AFFORD A LAMB GETS THE SAME SENTENCE AS THE ONE WHO CAN. Verse six brings a lamb and a bird. Verse eight brings two birds instead. The words for the burnt offering, the sin offering and the atonement are the same words in both verses, and both end with her being clean.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV12",
    reference: "Leviticus 12",
    verses: [
      {
        verse_number: 1,
        words: ["$mouth", "$name_tag", "to", "Moses,", "$speech"],
      },
      {
        verse_number: 2,
        words: [
          "$mouth",
          "to",
          "$son",
          "of Israel,",
          "$speech",
          "$woman",
          "becomes pregnant",
          "and gives birth to",
          "a son",
          "will be unclean",
          "for seven",
          "$sun,",
          "$sun",
          "of her menstruation.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$sun",
          "And on the eighth",
          "is to be circumcised",
          "$meat",
          "of the foreskin of the boy.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "for thirty-three",
          "$sun",
          "$sun",
          "The woman shall continue",
          "$blood",
          "in purification.",
          "anything",
          "$sparkle",
          "$no_entry",
          "touch",
          "into",
          "the sanctuary",
          "$no_entry",
          "$footprints",
          "until",
          "are complete",
          "$sun",
          "of her purification.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "If, however",
          "a daughter",
          "she gives birth to,",
          "the woman will be unclean",
          "for two weeks",
          "as she is during her menstruation,",
          "for sixty-six",
          "$sun",
          "$sun",
          "Then she must continue",
          "in",
          "$blood",
          "purification.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "are complete",
          "$sun",
          "of her purification,",
          "$son",
          "or",
          "$woman",
          "$footprints",
          "$lamb",
          "$son",
          "$burnt_offering",
          "$son",
          "$dove",
          "or",
          "a turtledove",
          "$bow",
          "at",
          "the entrance",
          "$tent",
          "of Meeting,",
          "to",
          "$priest.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "And the priest will present them",
          "before",
          "$name_tag",
          "and make atonement",
          "for her,",
          "and she shall be ceremonially cleansed",
          "from her flow",
          "$blood.",
          "This",
          "$scroll",
          "for a woman giving birth,",
          "whether to a male",
          "or",
          "to a female.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "But if",
          "$no_entry",
          "afford",
          "$hand",
          "a lamb,",
          "$hand_receiving",
          "two",
          "turtledoves",
          "or",
          "two",
          "$son",
          "$dove,",
          "one",
          "$burnt_offering",
          "and the other",
          "$bow.",
          "will make atonement",
          "for her",
          "$priest,",
          "and she will be clean.",
        ],
      },
    ],
  };
  return chapter;
}
