export function bible_glyph_chapter_psa029() {
  "The ninth picture Bible chapter written by hand: the whole of the twenty ninth psalm, in the shorthand a person types.";
  "IT COST NOTHING AT ALL, and that is the thing to notice about it. The sixth chapter cost one new picture against the fifth's three; the eighth cost one and picked up two that were already drawn elsewhere; this one cost none. Every word it draws was bought by a chapter before it, and three of the pictures it leans on hardest were bought by the psalm written immediately before it. A table keyed by root was argued for on exactly this ground years of chapters ago, and here is the first chapter that pays nothing to open.";
  "THE WATERS ARE THE CLEAREST CASE OF IT. The water was added to the Hebrew table for the hundred and thirty sixth psalm, where it stands once and was taken only because we were already in the table. It stands twice in the third verse here, in the line the whole psalm is built on. A picture bought as small change for one chapter turned out to be load-bearing in the next, which is what a shared table does and what a per-chapter table could never do.";
  "THE VOICE OF THE LORD IS SAID SEVEN TIMES AND IS TWO PICTURES EVERY TIME. Six verses open with it and the fourth says it twice, so a reader meets the same pair seven times in eleven verses. This is the same argument the eighth chapter was chosen on and it is worth making twice: a symbol language is not explained, it is drilled, and a psalm that repeats its own subject is a psalm that teaches the reader the marks for free while they read it for its own sake.";
  "THE FIRE IN THE SEVENTH VERSE IS NOT DRAWN AND THE FIRE IN THE FIRST VERSE IS. The picture of fire is seated on el, which is God; the seventh verse's fire is esh, which is fire, and has no seat. So the line reads that the voice strikes with flames of fire in plain letters while a picture of flames sits two lines above it meaning something else entirely. It looks like an oversight and it is the lesson: the marks sit on the Hebrew words and never on the English ones. Drawing the flames here would have handed the reader a picture that means God on a word that means burning, which is the largest wrong claim available in this psalm.";
  "THE GLORY IS THE STAR, FOUR TIMES, AND THE EIGHTH CHAPTER PAID FOR THAT. The hundred and thirty sixth psalm had the stars of the sky in its ninth verse and left them in English on purpose, because the star is seated on kabod and spending it on the sky would have cost the reader the word. This psalm is what that refusal was saving it for: glory opens the psalm, is ascribed twice, thunders in the third verse, and is the one word the whole temple cries at the end of the ninth. A picture kept clean in one chapter is a picture that can carry a whole chapter later.";
  "THE NAME AND THE LORD ARE ONE PICTURE AND THAT IS DELIBERATE. The second verse asks for the glory due His name, and the tag drawn on the name is the same tag drawn on the LORD in the line above it, because the covenant name and the word for a name are two Hebrew words seated under one mark. Two words sharing a picture is allowed everywhere in this Bible; here it happens to say something true, which an English reader gets no help seeing.";
  "THE SONS OF THE MIGHTY AND THE YOUNG WILD OX ARE THE SAME WORD. The first verse calls on what English renders heavenly beings and the Hebrew calls sons of God; the sixth verse has what English renders a young wild ox and the Hebrew calls a son of wild oxen. Both are ben, and both are drawn as the son. The sixth verse reads oddly in English because of it, and it is left that way: a reader who notices the same mark in two unlike places has been shown a fact about Hebrew that no translation on the shelf would have told them.";
  "THE BLESSING AT THE END WAS NOT DRAWN WHEN THIS CHAPTER WAS WRITTEN, AND IT IS DRAWN NOW. The last verse has the LORD giving strength and blessing His people with peace, and for a while only the giving had a picture - blessing is one of the commonest verbs in the psalter and had no seat, which was named here rather than hidden, because a psalm whose last word is peace and whose last verb is blank was a fair measure of how much of this language was still unbuilt. The table has since seated barak on the mouth and the thumb, and this verse was brought up to it.";
  "WHICH IS THE FAULT THIS CHAPTER WAS SITTING IN, WRITTEN DOWN BY THE CHAPTER ITSELF. A chapter is authored once out of whatever the table held that day, and nothing rebuilds it when the table grows; the paragraph above sat here saying a word could not be drawn for as long as it took somebody to read it again. Nothing went red and nothing could - the survey next door asks what the table draws, and the table drew it. What found this was a reading that compares the two, and what closed it was a person opening the verse.";
  "THE PROPER NAMES ARE LEFT IN ENGLISH - David, Lebanon, Sirion, Kadesh. That is the same rule every chapter here keeps and never a gap to fill later. A name points at one person or one place, and a picture of it would be a portrait.";
  let chapter = {
    chapter_code: "PSA029",
    reference: "Psalm 29",
    verses: [
      {
        verse_number: 1,
        words: [
          "Ascribe",
          "to",
          "the",
          "$name_tag,",
          "O",
          "$son",
          "of",
          "$fire,",
          "ascribe",
          "to",
          "the",
          "$name_tag",
          "$star",
          "and",
          "strength.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Ascribe",
          "to",
          "the",
          "$name_tag",
          "the",
          "$star",
          "due",
          "His",
          "$name_tag;",
          "$bowing",
          "to",
          "the",
          "$name_tag",
          "in",
          "the",
          "splendor",
          "of",
          "His",
          "$sparkle.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "is",
          "over",
          "the",
          "$water;",
          "the",
          "$fire",
          "of",
          "$star",
          "thunders;",
          "the",
          "$name_tag",
          "is",
          "over",
          "many",
          "$water.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "is",
          "$lightning;",
          "the",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "is",
          "majestic.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "breaks",
          "the",
          "cedars;",
          "the",
          "$name_tag",
          "shatters",
          "the",
          "cedars",
          "of",
          "Lebanon.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "makes",
          "Lebanon",
          "skip",
          "like",
          "a",
          "calf,",
          "and",
          "Sirion",
          "like",
          "a",
          "$son",
          "wild",
          "ox.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "strikes",
          "with",
          "flames",
          "of",
          "fire.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "shakes",
          "the",
          "wilderness;",
          "the",
          "$name_tag",
          "shakes",
          "the",
          "Wilderness",
          "of",
          "Kadesh.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "$voice",
          "of",
          "the",
          "$name_tag",
          "twists",
          "the",
          "oaks",
          "and",
          "strips",
          "the",
          "forests",
          "bare.",
          "And",
          "in",
          "His",
          "temple",
          "all",
          "$speech,",
          "$star!",
        ],
      },
      {
        verse_number: 10,
        words: [
          "The",
          "$name_tag",
          "sits",
          "enthroned",
          "over",
          "the",
          "flood;",
          "the",
          "$name_tag",
          "is",
          "enthroned",
          "as",
          "$king",
          "$hourglass.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "The",
          "$name_tag",
          "$hands_giving",
          "strength",
          "to",
          "His",
          "$family;",
          "the",
          "$name_tag",
          "$speech+thumbs_up$es",
          "His",
          "$family",
          "with",
          "peace.",
        ],
      },
    ],
  };
  return chapter;
}
