export function bible_cast_brief() {
  "The whole brief for giving the read Bible more than one voice - what it would cost, measured rather than guessed; which translation can be parsed and which cannot; the one rule that removes most of the apparent work; and the two decisions that are not this brief's to make.";
  "★ THE COST IS NOW A NUMBER AND THE NUMBER IS THIRTY. Every quotation in the Berean was found by walking the double quotation marks, and every one was asked whether anything nearby says who is talking. Six thousand and eighty-eight quotations; five thousand seven hundred and thirty-six attributed by a speaking verb or a colon; two hundred and thirty-four citations inside letters, which want no cast; seventy speeches continuing from the previous chapter, which the previous chapter attributes; thirteen inside chapter headings, which are never read aloud; five translation glosses, which are the narrator saying what a foreign word means; thirty left over. That last figure is the hand work for the entire Bible, and it is an hour rather than a project.";
  "★ THE FIRST ANSWER WAS FOUR HUNDRED AND TEN AND FOUR FIFTHS OF THAT WAS THE INSTRUMENT RATHER THAN THE TEXT. The verb list had been written in the past tense, so it could read narrative and not poetry; the colon, which attributes speech in English with no verb at all, was not asked about; letters, superscriptions and speeches crossing a chapter boundary were all being counted as work. Fixing the instrument moved the Psalms from forty-five to two, Isaiah from forty-three to ten, and Job from fourteen to none at all. Nothing about the Bible changed. This is the reason to read the misses rather than to price the total.";
  "★ THE MEASUREMENT LEANS THE SAFE WAY, WHICH IS WHY IT CAN BE ACTED ON. The verb list is deliberately generous, so a quotation counted as attributed may still turn out to need a person; but a quotation counted as UNATTRIBUTED has nothing anywhere near it saying who speaks, and is certainly hand work. The thirty is therefore a floor that is nearly the ceiling, and not a hopeful estimate.";
  "★ ATTRIBUTION SITS ON EITHER SIDE OF THE SPEECH AND LOOKING ONLY BACKWARDS TRIPLED THE APPARENT COST. Mark measured forty-one unattributed quotations while only the narration in front was read, and fourteen once the narration behind it was read too. Mark 1:17 is why - Come, follow Me, then Jesus said, then and I will make you fishers of men - the speaker named in the middle of his own sentence. Nothing about the text changed; a wrong measurement had been about to price the work at three times what it costs.";
  "★ THE LETTERS ARE STRUCK FROM THE COUNT ALTOGETHER, BECAUSE A QUOTATION IN A LETTER IS A CITATION AND NOT A CHANGE OF SPEAKER. When Paul writes that it is written and then quotes Isaiah, Paul is still the one speaking - he is citing, exactly as Jesus cites the commandment inside his own speech, and the settled rule already says a quoter keeps his voice. Two hundred and thirty-four quotations across the letters are citations of that kind and every one of them wants no cast at all. The book kind in the speaker table already carries the word LETTER, so this is a rule the data applies rather than a judgement anyone has to repeat.";
  "★ A QUOTATION IN A CHAPTER HEADING IS THE ONE ERROR THAT WOULD HAVE REACHED THE EARS, AND IT WAS FOUND ONLY BY READING THE MISSES. Psalms 9, 22 and 45 open with For the choirmaster. To the tune of and then a quoted tune name - The Death of the Son, The Doe of the Dawn, The Lilies. The parser calls that a quotation because it is one, typographically. A cast built from the parser would have given a piece of manuscript apparatus to a voice and said it out loud. Thirteen of these exist and all of them sit in verse zero, which is where this reader keeps everything printed before verse one, so the rule is about the verse number rather than about the words.";
  "★ A SPEECH THAT CROSSES A CHAPTER BOUNDARY IS ATTRIBUTED BY THE CHAPTER BEFORE IT, AND THAT ONE RULE EMPTIED JOB COMPLETELY. Job 4 announces Eliphaz and the translators never close his quotation, because he is still talking in Job 5; so Job 5 opens inside a quotation with nothing at all in front of it. The previous chapter ending unclosed is a FACT rather than a guess - it is a count of marks - so the speaker carries over with no judgement involved. Seventy quotations across thirteen books are this shape, and all fourteen of Job's were. What looked like the largest block of hand work in the Bible was a parser resetting its depth at a chapter boundary.";
  "★ SCATTERING WAS READ AS A SIGN THE RULES WERE DONE AND IT WAS NOT ONE, WHICH IS THE MISTAKE MOST WORTH KEEPING IN THIS BRIEF. At eighty-five the misses were spread over thirty-two books with no block bigger than Isaiah's ten, and that was written down here as proof no shape remained. Then the eighty-five were actually read, and more than half of them were one thing: a speaking verb the list did not hold. Shout, shouts and shouted were all in it while SHOUTING was not, and shouting is the form the New Testament uses. The spread of a residue across books says nothing at all about whether it has a shape, because the shape is in the WORDS and not in the table of contents. Only reading them tells you, and reading them has now beaten guessing five times running.";
  "★ THE INSTRUMENT WAS FIXED THREE MORE TIMES AND THE NUMBER FELL FROM EIGHTY-FIVE TO THIRTY. About a hundred and thirty missing verb forms were added; the window in front of a quotation was widened from twelve words to twenty-five, because what stands between the verb and the speech is the person being addressed and that can be a list of names - Luke 22 puts SAID fourteen words back and Daniel 1 puts it sixteen; and a fifth class was struck out, the translator's gloss, where the narrator says in brackets that Immanuel means God with us or that Boanerges means Sons of Thunder. Five of those exist and every one of them would have been an English dictionary entry spoken in a character's voice.";
  "★ WHAT FINALLY REMAINED WAS READ AND ALL THIRTY ARE NOW ATTRIBUTED. Seventeen are unannounced divine speech in the prophets and the Psalms. Two are Jesus, both resumed after the narrator breaks in with an aside. Nine are a quotation the translator split in half - David listing where he had raided, the people crying out to the hills - where the speaker is named on the sibling piece and not on this one. One is the covenant oath of Nehemiah 10, quoted to the end of the chapter with nobody named. The last two are the refrain of First Chronicles 16:41 and the WE of Jeremiah 51:9, and both were settled from Scripture in the end rather than from a commentator.";
  "★ THE SEVENTEEN DIVINE SPEECHES ARE THE ONES THE BOOK DEFAULTS CANNOT COVER, AND THIS BRIEF SAID THE OPPOSITE AND WAS WRONG. The default speaker for Isaiah is ISAIAH and for Jeremiah is JEREMIAH, deliberately, because most divine speech in a prophet sits inside a quotation the prophet opens after a formula - so the prophet is the fallback and God is the marked voice. An unannounced divine speech is therefore exactly the case where falling back puts the LORD's words in the prophet's mouth. It is the single most dangerous error available here, it would be silent, and it is the reason the thirty are stored as data with a gate over them rather than being folded into the defaults.";
  "★ THE QUOTATION MARKS ARE NOT IN SCRIPTURE, AND THAT IS THE FINDING THE PARSER WAS NOT BUILT TO MAKE. Greek and Hebrew have no such marks. Every one of them in an English bible is a translator saying where he judges the speech to begin and end, so a cast derived from them is derived from editorial judgement rather than from the text. That does not make it wrong - the judgement is a scholar's and is usually obvious - but it is the reason a cast is a reading of Scripture rather than a fact about it, and it should be said out loud rather than discovered later.";
  "★ THE TRANSLATIONS DISAGREE, AND THE DISAGREEMENT IS SMALL WHERE IT IS ABOUT MEANING AND LARGE WHERE IT IS ABOUT PUNCTUATION. Mark holds two hundred and seventy-three quotations in the Berean, two hundred and fifty-nine in the New English Translation and two hundred and forty-seven in the World English Bible - a spread of about ten percent, and reading the misses shows it is nearly all about where a long speech is broken rather than about who is speaking. Nobody disagrees that Jesus said the words; they disagree about which sentence closes the quotation.";
  "★ YOUNG'S LITERAL CANNOT BE PARSED AT ALL AND SAID SO BY ANSWERING NOTHING. It writes every quotation with the plain typewriter apostrophe, which is also the possessive, so no stack can tell an opening from a contraction. Asked for the speech in Mark it returns zero quotations - not an error, not a warning, a confident empty answer that looks exactly like a correct one. That is the reason a mark counter exists beside the parser: the emptiness had to be measured on purpose or it would never have been noticed.";
  "★ THE BEREAN IS THE ONE TO PARSE, AND THE PROOF IS THAT ITS MARKS BALANCE. Across Mark it opens three hundred and five double quotations and closes three hundred and five. The World English Bible opens two hundred and seventy-eight and closes two hundred and sixty-seven, and the New English Translation two hundred and sixty-nine against two hundred and sixty-three, so both leave quotations hanging that a stack would carry forward into the wrong verses. This is not an argument about translation quality; it is that one of these files is typographically consistent and the others are not.";
  "★ THE SINGLE MARKS ARE IGNORED ON PURPOSE AND IT COSTS NOTHING. In the Berean the right single mark is also the apostrophe - the Song of Songs opens on Solomon's Song of Songs - so a stack counting them starts wrong on the first verse of that book. It never needs to: a quotation inside a quotation keeps the quoter's voice, so the inner marks were never going to change a voice. The unreliable character is exactly the character nobody needs, which is luck rather than design and is worth knowing before someone spends a day fixing it.";
  "★ TWO DECISIONS ARE NOT THIS BRIEF'S AND BOTH ARE ABOUT PEOPLE RATHER THAN PARSING. Who reads Jesus and who reads the Father are the highest-stakes choices in the product, and the only rule that survives from the argument is narrow: the voice given to Jesus must not also be a voice the product uses editorially, or the product ends up speaking with his voice. Everything else about who reads was settled the other way - waiting for the right person is the same error as waiting for certainty.";
  "★ THE SONG OF SONGS IS THE ONE BOOK NO AMOUNT OF PARSING WILL REACH. Four quotations in eight chapters, three of them unattributed, and the speakers change between bride and groom and the daughters of Jerusalem with nothing in the text saying which is which. The headings printed in some editions are an editor's judgement rather than Scripture. So its cast has to be supplied from outside the text by somebody willing to say so, and the speaker table enters it as ALTERNATING rather than naming a voice, so that nobody mistakes it for solved.";
  "★ THE CAST MUST BE DECIDED BEFORE GENERATION AND CANNOT BE SPLICED ON AFTERWARDS, WHICH IS WHAT MAKES THIS URGENT RATHER THAN INTERESTING. A voice is a property of the sound, so changing who speaks a line means generating that line again. The thousands of files already on this disk were made from a chapter flattened into one voice with the verse boundaries thrown away, so none of them can be cast and none of them can even be indexed. They are a proof that the pipeline works rather than an asset to protect.";
  "★ THAT LAST CLAIM IS NOW MEASURED RATHER THAN ASSERTED, AND LEVITICUS 1 IS THE PROOF. The chapter has seventeen verses and the recording has six pieces, so the note written over it says ALIGNED FALSE and shows the first piece running from verse one to verse five in one breath. Nothing was missing and nothing had failed - the files are all there and they play. The generation was flattening the chapter into a single string before handing it over, so the engine cut it wherever its own chunking landed, and a recording cut at the wrong places is silently useless in a way that only counting can reveal.";
  let brief = {
    step: "cast",
    what: "whether the read Bible gets more than one voice, what that costs, and what has to be decided by a person",
    measured:
      "6088 quotations in the Berean; 5736 attributed; 234 citations inside letters, wanting no cast; 70 continuing from the previous chapter, which attributes them; 13 inside chapter headings, never read aloud; 5 translation glosses in brackets; 30 left, all now ruled by hand and stored, of which 17 are unannounced divine speech the book defaults cannot reach, 2 are Jesus resumed after an aside, 9 are a split quotation named on its sibling piece, 1 is the covenant oath of Nehemiah 10, and 2 needed a reading of Scripture to settle",
    settled:
      "the parse walks double quotation marks over a whole chapter and ignores single ones, because a quoter keeps his voice; what is unmarked is the book's own speaker, which the speaker table supplies; attribution is looked for on both sides of a quotation and a closing colon counts as attribution; a quotation in a letter is a citation, a quotation in verse zero is apparatus, and a quotation opening a chapter whose predecessor ended unclosed is the same speech continuing; the Berean is the translation to parse because its marks balance; Young's Literal cannot be parsed at all",
    open: "who reads Jesus and who reads the Father; how the Song of Songs is cast; whether a sung book is chanted on the Bible's own words or sung to a metrical paraphrase, which is a question about the words rather than about the music",
    forbidden:
      "giving Jesus a voice the product also uses editorially; treating a quotation mark as if it were in the manuscripts; casting a recording after it is generated; reading a zero result from a parser as a fact about a translation without counting its marks first",
    done: "every quotation in the Berean names a speaker, and a chapter can be generated in more than one voice with the verse boundaries recorded",
  };
  return brief;
}
