export function bible_glyph_chapter_job03() {
  "Job 3, drawn in pictures, so that a person who cannot read the letters can still follow it. Job breaks his silence and curses the day he was born. He asks why he did not die at birth, and says the grave would have been rest. Twenty six lines.";
  "THIS IS THE CHAPTER THAT ASKS FOR DARKNESS, AND DARKNESS IS ONE OF THE FEW THINGS HERE THAT CAN BE SEEN. The dark lands twice and the light three times, and between them they carry the argument of the whole page. That is rare. Most chapters written here lose the thing they are about, and this one keeps it.";
  "BUT THE NIGHT IS BLANK, ALL FOUR TIMES. Job says night in the third line, the sixth, the seventh and the tenth, and it is the half of the pair that has no picture, so a reader watching the marks sees the darkness he asks for and never sees the night he asks it of. There are also two different Hebrew words for dark on this page and only one of them has a picture, so the sixth line asks darkness to carry the night away and comes out with a receiving hand and no dark at all.";
  "AND GOD IS NAMED TWICE AND THE FLAME NEVER LANDS. The fourth line asks God above to pass the day by, and the twenty third asks why God hedges a man in. Job uses the poetic form of the name that belongs almost only to this book, and the root table seats the flame on the two ordinary forms and not on that one, so the one chapter here where a man argues straight at God has no God in it anywhere. This is not a judgment made on the page. It is a seat the table does not have.";
  "AND THE MORNING STARS IN THE NINTH LINE ARE PLAIN, THOUGH THERE IS A STAR. The star picture is seated on the Hebrew word for glory, so it is already spoken for, and an actual star in the sky cannot have it. This chapter is the clean case for that: it names stars once, it names them as the last light Job wants put out, and the drawing that would show them is holding a different word.";
  "THE THREE EMPTY LINES ARE THE THREE PICTURES OF THE DEATH JOB WISHED HE HAD HAD. The twelfth is the knees that received him and the breasts that nursed him. The thirteenth is lying down asleep and at rest. The twenty second is rejoicing and reaching the grave. Knees, breasts, nursing, peace, sleep, rest, rejoicing and a grave, and there is a picture for none of the eight. Everything Job wanted instead of his life comes out as plain letters.";
  "NOTHING WAS DROPPED FROM THIS PAGE. Fifty five marks were offered and fifty five were kept, which has not happened often here. Nine of them were kept only by putting the Hebrew back in place of the smoother English. Five were marks the draft had left with no English word of their own, and four sat on English that did not hold what the picture says. The seventeenth line says the weary find rest, and the Hebrew says the weary of strength, so the strength mark got a word to stand on. The twenty fourth says food is put before me, and the Hebrew says my sighing comes before my bread, so the walking came back. The twenty sixth is three flat denials in Hebrew and English had folded them into two, so writing all three out gave the third one a word.";
  "Fifty five marks over twenty six lines, which is thin for a chapter this long. The sixth is the fullest at five, and three lines are empty.";
  "Nothing stood down here, so there is no list of marks put away.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "JOB03",
    reference: "Job 3",
    verses: [
      {
        verse_number: 1,
        words: [
          "After",
          "this,",
          "Job",
          "opened",
          "his",
          "mouth",
          "and",
          "$speech+thumbs_down",
          "the",
          "$sun",
          "of",
          "his",
          "birth.",
        ],
      },
      {
        verse_number: 2,
        words: ["And", "this", "is", "what", "he", "$speech:"],
      },
      {
        verse_number: 3,
        words: [
          "May",
          "the",
          "$sun",
          "of",
          "my",
          "birth",
          "perish,",
          "and",
          "the",
          "night",
          "it",
          "was",
          "$speech,",
          "A",
          "boy",
          "is",
          "conceived.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "If",
          "only",
          "that",
          "$sun",
          "had",
          "turned",
          "to",
          "$darkness.",
          "May",
          "God",
          "above",
          "$no_entry",
          "seek",
          "it,",
          "and",
          "may",
          "$no_entry",
          "light",
          "shine",
          "upon",
          "it.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "May",
          "$darkness",
          "and",
          "gloom",
          "reclaim",
          "it.",
          "May",
          "a",
          "cloud",
          "settle",
          "over",
          "it.",
          "May",
          "the",
          "blackness",
          "of",
          "the",
          "$sun",
          "overwhelm",
          "it.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "If",
          "only",
          "darkness",
          "had",
          "$hand_receiving",
          "that",
          "night",
          "away.",
          "May",
          "it",
          "$no_entry",
          "appear",
          "among",
          "the",
          "$sun",
          "of",
          "the",
          "year,",
          "may",
          "it",
          "$no_entry",
          "$footprints",
          "into",
          "the",
          "number",
          "of",
          "the",
          "months.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Behold,",
          "may",
          "that",
          "night",
          "be",
          "barren.",
          "May",
          "$no_entry",
          "joyful",
          "voice",
          "$footprints",
          "into",
          "it.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "May",
          "it",
          "be",
          "$speech+thumbs_down",
          "by",
          "those",
          "who",
          "curse",
          "the",
          "$sun,",
          "those",
          "prepared",
          "to",
          "rouse",
          "Leviathan.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "May",
          "its",
          "morning",
          "stars",
          "grow",
          "dark.",
          "May",
          "it",
          "wait",
          "for",
          "$light",
          "in",
          "vain,",
          "may",
          "it",
          "$no_entry",
          "$eye",
          "the",
          "breaking",
          "of",
          "dawn.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "For",
          "that",
          "night",
          "did",
          "$no_entry",
          "shut",
          "the",
          "doors",
          "of",
          "the",
          "womb",
          "to",
          "hide",
          "the",
          "sorrow",
          "from",
          "my",
          "$eyes.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Why",
          "did",
          "I",
          "$no_entry",
          "$skull",
          "at",
          "birth,",
          "why",
          "did",
          "I",
          "not",
          "die",
          "as",
          "I",
          "came",
          "from",
          "the",
          "womb?",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Why",
          "were",
          "there",
          "knees",
          "to",
          "receive",
          "me,",
          "and",
          "breasts",
          "that",
          "I",
          "should",
          "be",
          "nursed?",
        ],
      },
      {
        verse_number: 13,
        words: [
          "For",
          "now",
          "I",
          "would",
          "be",
          "lying",
          "down",
          "in",
          "peace,",
          "I",
          "would",
          "be",
          "asleep",
          "and",
          "at",
          "rest,",
        ],
      },
      {
        verse_number: 14,
        words: [
          "with",
          "$king",
          "and",
          "counselors",
          "of",
          "the",
          "$earth,",
          "who",
          "built",
          "for",
          "themselves",
          "cities",
          "now",
          "in",
          "ruins,",
        ],
      },
      {
        verse_number: 15,
        words: [
          "or",
          "with",
          "princes",
          "who",
          "had",
          "gold,",
          "who",
          "filled",
          "their",
          "$house",
          "with",
          "silver.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "Or",
          "why",
          "was",
          "I",
          "$no_entry",
          "hidden",
          "like",
          "a",
          "stillborn",
          "child,",
          "like",
          "an",
          "infant",
          "who",
          "$no_entry",
          "$eye",
          "$light?",
        ],
      },
      {
        verse_number: 17,
        words: [
          "There",
          "the",
          "$thumbs_down",
          "cease",
          "from",
          "raging,",
          "and",
          "there",
          "the",
          "weary",
          "of",
          "$lightning",
          "find",
          "rest.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "The",
          "captives",
          "enjoy",
          "their",
          "ease.",
          "They",
          "do",
          "$no_entry",
          "$ear",
          "the",
          "$voice",
          "of",
          "the",
          "oppressor.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Both",
          "small",
          "and",
          "great",
          "are",
          "there,",
          "and",
          "the",
          "$kneeling",
          "is",
          "freed",
          "from",
          "his",
          "$crown.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Why",
          "is",
          "$light",
          "$hands_giving",
          "to",
          "the",
          "miserable,",
          "and",
          "$sprout",
          "to",
          "the",
          "bitter",
          "of",
          "$person_other?",
        ],
      },
      {
        verse_number: 21,
        words: [
          "who",
          "long",
          "for",
          "$skull",
          "that",
          "does",
          "not",
          "come,",
          "and",
          "search",
          "for",
          "it",
          "like",
          "hidden",
          "treasure,",
        ],
      },
      {
        verse_number: 22,
        words: [
          "who",
          "rejoice",
          "and",
          "greatly",
          "exult",
          "when",
          "they",
          "reach",
          "the",
          "grave?",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Why",
          "is",
          "life",
          "given",
          "to",
          "a",
          "man",
          "whose",
          "$road",
          "is",
          "hidden,",
          "whom",
          "God",
          "has",
          "hedged",
          "in?",
        ],
      },
      {
        verse_number: 24,
        words: [
          "For",
          "my",
          "sighing",
          "$footprints",
          "before",
          "my",
          "$bread,",
          "and",
          "my",
          "groans",
          "pour",
          "out",
          "like",
          "$water.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "For",
          "the",
          "thing",
          "I",
          "feared",
          "has",
          "overtaken",
          "me,",
          "and",
          "what",
          "I",
          "dreaded",
          "has",
          "$footprints",
          "to",
          "me.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "I",
          "am",
          "$no_entry",
          "at",
          "ease,",
          "I",
          "am",
          "$no_entry",
          "quiet,",
          "I",
          "have",
          "$no_entry",
          "rest,",
          "but",
          "trouble",
          "has",
          "$footprints.",
        ],
      },
    ],
  };
  return chapter;
}
