export function bible_glyph_chapter_psa090() {
  "The ninetieth psalm, drawn in pictures. A prayer of Moses about how short a life is and what to ask for because of it. It is seventeen lines long and it contains the line teach us to number our days, which is the sentence the rest of the psalm exists to earn.";
  "THE SAME MARK FALLS SIX TIMES AND EVERY ONE OF THEM IS THE WORD DAYS. A thousand years are but a day. All our days decline. The length of our days is seventy years. Teach us to number our days. Be glad all our days. Make us glad for as many days as You have afflicted us. Six identical pictures spread down the page, and the poem is about counting exactly that thing. A reader who cannot read one English word can still count six marks and see that the psalm keeps coming back to the same object. The famous line is the fourth of them, which is to say the psalm has already shown you three days before it asks you to number them.";
  "WHO KNOWS AND TEACH US ARE ONE HEBREW WORD. The eleventh verse asks who knows the power of Your anger. The twelfth asks God to teach us. In Hebrew the second is the first with a causative turn on it - who knows, so make us know. The picture is the same mark twice, in consecutive lines, and English cannot show it because English has to use two unrelated verbs. It matters, because it means the request in verse twelve is not a change of subject. It is the answer to the question just asked.";
  "THE TURNING GOES BOTH WAYS. The third verse says You return man to dust, and then, in the same line, Return, O sons of mortals. The thirteenth says Return, O LORD. Three marks, one word, and the direction reverses: in the third verse God sends a man back to the ground, and in the thirteenth a man asks God to come back. There are no other turnings on the page, so the two are impossible to mistake for anything else.";
  "THE ONLY TWO FOREVER MARKS IN THE PSALM ARE IN ONE LINE. The second verse says from everlasting to everlasting You are God, and both halves of that carry the mark. Every other line in the poem is about something short - a day, a watch of the night, grass that springs up in the morning and withers by evening, seventy years. So the whole of the psalm's long time is spent in one sentence at the top, and the rest of the page is spent in the short time underneath it. That is the argument laid out as a picture before it is made as a sentence.";
  "THE PSALM OPENS AND CLOSES ON THE SAME TWO MARKS, AND THE LAST LINE ASKS TWICE. The first line has the Lord mark and the God mark; so does the seventeenth, and nowhere in between do they stand together. Inside that frame the last verse says the work of our hands twice, and both are drawn, so the poem that has spent seventeen lines saying how quickly a life passes ends by asking, in duplicate, that what a person makes with their hands be made to stand. The seeing mark does something similar across the last three lines: we have seen evil, and may Your work be shown to Your servants - the same word for both.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA090",
    reference: "Psalm 90",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "$hands_praying",
          "of",
          "Moses",
          "the",
          "$man_beard",
          "of",
          "$fire.",
          "$crown,",
          "You",
          "have",
          "been",
          "our",
          "dwelling",
          "place",
          "through",
          "all",
          "generations.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Before",
          "the",
          "$mountain",
          "were",
          "born",
          "or",
          "You",
          "brought",
          "forth",
          "the",
          "$earth",
          "and",
          "the",
          "$globe,",
          "from",
          "$hourglass",
          "to",
          "$hourglass",
          "You",
          "are",
          "$fire.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "You",
          "$turn_back",
          "man",
          "to",
          "dust,",
          "$speech,",
          "$turn_back,",
          "O",
          "$son",
          "of",
          "$person.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "For",
          "a",
          "thousand",
          "years",
          "in",
          "Your",
          "$eyes",
          "are",
          "but",
          "a",
          "$sun",
          "that",
          "passes,",
          "or",
          "a",
          "watch",
          "of",
          "the",
          "night.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "sweep",
          "men",
          "away",
          "in",
          "their",
          "sleep;",
          "they",
          "are",
          "like",
          "the",
          "new",
          "grass",
          "of",
          "the",
          "morning",
          "-",
        ],
      },
      {
        verse_number: 6,
        words: [
          "in",
          "the",
          "morning",
          "it",
          "springs",
          "up",
          "new,",
          "but",
          "by",
          "evening",
          "it",
          "fades",
          "and",
          "withers.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "For",
          "we",
          "are",
          "consumed",
          "by",
          "Your",
          "anger,",
          "and",
          "terrified",
          "by",
          "Your",
          "wrath.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "You",
          "have",
          "set",
          "our",
          "iniquities",
          "before",
          "You,",
          "our",
          "secret",
          "sins",
          "in",
          "the",
          "light",
          "of",
          "Your",
          "presence.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "For",
          "all",
          "our",
          "$sun",
          "decline",
          "in",
          "Your",
          "fury;",
          "we",
          "finish",
          "our",
          "years",
          "with",
          "a",
          "sigh.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "The",
          "length",
          "of",
          "our",
          "$sun",
          "is",
          "seventy",
          "years",
          "-",
          "or",
          "eighty",
          "if",
          "we",
          "are",
          "strong",
          "-",
          "yet",
          "their",
          "pride",
          "is",
          "but",
          "labor",
          "and",
          "sorrow,",
          "for",
          "they",
          "quickly",
          "pass,",
          "and",
          "we",
          "fly",
          "away.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Who",
          "$lightbulb",
          "the",
          "power",
          "of",
          "Your",
          "anger?",
          "Your",
          "wrath",
          "matches",
          "the",
          "fear",
          "You",
          "are",
          "due.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "So",
          "$lightbulb",
          "us",
          "to",
          "number",
          "our",
          "$sun,",
          "that",
          "we",
          "may",
          "$footprints",
          "a",
          "$heart_organ",
          "of",
          "wisdom.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$turn_back,",
          "O",
          "$name_tag!",
          "How",
          "long",
          "will",
          "it",
          "be?",
          "Have",
          "compassion",
          "on",
          "Your",
          "$kneeling.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Satisfy",
          "us",
          "in",
          "the",
          "morning",
          "with",
          "Your",
          "$gift,",
          "that",
          "we",
          "may",
          "sing",
          "for",
          "joy",
          "and",
          "be",
          "glad",
          "all",
          "our",
          "$sun.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Make",
          "us",
          "glad",
          "for",
          "as",
          "many",
          "$sun",
          "as",
          "You",
          "have",
          "afflicted",
          "us,",
          "for",
          "as",
          "many",
          "years",
          "as",
          "we",
          "have",
          "$eye",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "May",
          "Your",
          "work",
          "be",
          "$eye",
          "to",
          "Your",
          "$kneeling,",
          "and",
          "Your",
          "splendor",
          "to",
          "their",
          "$son.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "May",
          "the",
          "favor",
          "of",
          "the",
          "$crown",
          "our",
          "$fire",
          "rest",
          "upon",
          "us;",
          "establish",
          "for",
          "us",
          "the",
          "work",
          "of",
          "our",
          "$hand",
          "-",
          "yes,",
          "establish",
          "the",
          "work",
          "of",
          "our",
          "$hand.",
        ],
      },
    ],
  };
  return chapter;
}
