export function bible_glyph_chapter_num12() {
  "The twelfth chapter of Numbers, drawn in pictures. Sixteen verses. Miriam and Aaron speak against Moses over the woman he married, and then say the thing they really mean: does God speak only through him? God comes down in a cloud, answers, and leaves. Miriam turns white with disease, Aaron begs, Moses prays for her, and the whole nation stops walking for a week.";
  "MIRIAM AND AARON ARE NAMED TOGETHER FOUR TIMES AND THEN THE CHAPTER SEPARATES THEM. Both names are in verses one, four, five and ten. After verse ten Aaron is named once more, in verse eleven, asking for mercy, and Miriam is named once more, in verse fifteen, shut outside the camp. They said the same thing. Only one of them carries it.";
  "THE LORD IS NAMED NINE TIMES AND MOSES NINE TIMES. Exactly the same count, in a chapter that is an argument about how close those two are.";
  "THE WORD FOR SPEAK IS SAID SIX TIMES AND THE WHOLE QUARREL IS ABOUT IT. Verses one, two, six and eight. The charge in verse two is that God does not speak only through Moses. The answer in verses six to eight is not about who is right; it is about how God speaks, in a vision and a dream to a prophet, and face to face with this one man.";
  "VERSE THREE STOPS THE STORY TO SAY WHAT MOSES WAS LIKE. It calls him more humble than any man on the face of the earth. He is accused in verse one and verse two, and he does not answer either time.";
  "THE ONLY WORDS MOSES SAYS IN THE CHAPTER ARE A PRAYER FOR THE ONE WHO ACCUSED HIM. Verse thirteen, and it is four words long: God, please heal her.";
  "SEVEN DAYS IS SAID TWICE AND THE WHOLE NATION WAITS OUT BOTH OF THEM. Day is said three times and all three are in verses fourteen and fifteen. Verse fifteen says the people did not move on until she was brought in again.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "NUM12",
    reference: "Numbers 12",
    verses: [
      {
        verse_number: 1,
        words: [
          "Then",
          "Miriam",
          "and",
          "Aaron",
          "$mouth",
          "against",
          "Moses",
          "because",
          "of",
          "the",
          "Cushite",
          "$woman",
          "he",
          "$hand_receiving,",
          "for",
          "he",
          "$hand_receiving",
          "a",
          "Cushite",
          "$woman.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "They",
          "$speech,",
          "Has",
          "$name_tag",
          "$mouth",
          "only",
          "through",
          "Moses?",
          "Has",
          "He",
          "$no_entry",
          "$mouth",
          "through",
          "us",
          "also?",
          "And",
          "$name_tag",
          "$ear",
          "this.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Now",
          "Moses",
          "was",
          "a",
          "very",
          "humble",
          "$man_beard,",
          "more",
          "so",
          "than",
          "any",
          "$person",
          "on",
          "the",
          "face",
          "of",
          "the",
          "earth.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "And",
          "suddenly",
          "$name_tag",
          "$speech",
          "to",
          "Moses,",
          "Aaron",
          "and",
          "Miriam,",
          "You",
          "three",
          "come",
          "out",
          "to",
          "the",
          "$tent",
          "of",
          "Meeting.",
          "So",
          "the",
          "three",
          "of",
          "them",
          "went",
          "out.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Then",
          "$name_tag",
          "came",
          "down",
          "in",
          "a",
          "pillar",
          "of",
          "$cloud,",
          "stood",
          "at",
          "the",
          "entrance",
          "to",
          "the",
          "$tent,",
          "and",
          "summoned",
          "Aaron",
          "and",
          "Miriam.",
          "When",
          "both",
          "of",
          "them",
          "had",
          "stepped",
          "forward,",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "$speech,",
          "$ear",
          "now",
          "$speech.",
          "If",
          "there",
          "is",
          "a",
          "$megaphone",
          "among",
          "you,",
          "I,",
          "$name_tag,",
          "$lightbulb",
          "to",
          "him",
          "in",
          "a",
          "vision;",
          "I",
          "$mouth",
          "to",
          "him",
          "in",
          "a",
          "$dream.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "But",
          "this",
          "is",
          "$no_entry",
          "so",
          "with",
          "My",
          "$kneeling",
          "Moses.",
          "He",
          "is",
          "$anchor",
          "in",
          "all",
          "My",
          "$house.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "I",
          "$mouth",
          "with",
          "him",
          "face",
          "to",
          "face,",
          "clearly",
          "and",
          "$no_entry",
          "in",
          "riddles;",
          "he",
          "sees",
          "the",
          "form",
          "of",
          "$name_tag.",
          "Why",
          "then",
          "were",
          "you",
          "$no_entry",
          "afraid",
          "to",
          "$mouth",
          "against",
          "My",
          "$kneeling",
          "Moses?",
        ],
      },
      {
        verse_number: 9,
        words: [
          "So",
          "the",
          "anger",
          "of",
          "$name_tag",
          "burned",
          "against",
          "them,",
          "and",
          "He",
          "$walking.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "As",
          "the",
          "$cloud",
          "lifted",
          "from",
          "above",
          "the",
          "$tent,",
          "suddenly",
          "Miriam",
          "became",
          "leprous,",
          "as",
          "white",
          "as",
          "$snow.",
          "Aaron",
          "turned",
          "toward",
          "her",
          "and",
          "saw",
          "that",
          "she",
          "was",
          "leprous.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Aaron",
          "$speech",
          "to",
          "Moses,",
          "$crown,",
          "please",
          "$no_entry",
          "hold",
          "against",
          "us",
          "this",
          "$bow",
          "that",
          "we",
          "have",
          "so",
          "foolishly",
          "$bow.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Please",
          "$no_entry",
          "let",
          "her",
          "be",
          "like",
          "a",
          "$skull",
          "whose",
          "$meat",
          "is",
          "half",
          "consumed",
          "when",
          "he",
          "comes",
          "out",
          "of",
          "the",
          "womb",
          "of",
          "his",
          "$mother.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "So",
          "Moses",
          "cried",
          "out",
          "to",
          "$name_tag,",
          "$speech",
          "$fire,",
          "please",
          "heal",
          "her.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "But",
          "$name_tag",
          "$speech",
          "to",
          "Moses,",
          "If",
          "her",
          "$father",
          "had",
          "but",
          "spit",
          "in",
          "her",
          "face,",
          "would",
          "she",
          "$no_entry",
          "have",
          "been",
          "in",
          "disgrace",
          "for",
          "seven",
          "$sun?",
          "Let",
          "her",
          "be",
          "confined",
          "outside",
          "the",
          "$camp",
          "for",
          "seven",
          "$sun,",
          "and",
          "after",
          "that",
          "she",
          "may",
          "be",
          "brought",
          "back",
          "in.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "So",
          "Miriam",
          "was",
          "confined",
          "outside",
          "the",
          "$camp",
          "for",
          "seven",
          "$sun,",
          "and",
          "the",
          "$family",
          "did",
          "$no_entry",
          "move",
          "on",
          "until",
          "she",
          "was",
          "brought",
          "in",
          "again.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "After",
          "that,",
          "the",
          "$family",
          "set",
          "out",
          "from",
          "Hazeroth",
          "and",
          "camped",
          "in",
          "the",
          "$wilderness",
          "of",
          "Paran.",
        ],
      },
    ],
  };
  return chapter;
}
