export function bible_glyph_chapter_1th01() {
  "The fortieth picture Bible chapter written by hand: the whole of the first chapter of First Thessalonians, Paul thanking God for a church whose faith had already travelled further than his own report of it, in the shorthand a person types.";
  "IT IS THE FIRST LETTER OF PAUL IN A COLLECTION OF FORTY CHAPTERS, AND THAT IS THE ARGUMENT THAT TOOK IT. Thirty nine chapters were written before one of them was Pauline. Four gospels are here, six books of the Old Testament, all three letters of John, the first letter under his name five times over, and Jude - and not one page of the thirteen books that are Paul's, nor of Acts, Hebrews, James, Peter or Revelation. The thirty fifth entry took Matthew five over a chapter that measured higher because a whole gospel was missing and no share can measure a missing book. The same argument is thirteen books wide here.";
  "AND IT WAS TAKEN AT THIRTY NINE OVER THREE CHAPTERS AT FORTY ONE, BECAUSE THE SHARE NARROWS AND THE READING DECIDES. The survey was run over all two hundred and thirty two unwritten chapters of the testament and came back topped by first Corinthians two, which was refused on reading it: the word wisdom stands undrawn there six times, with mind, spiritual and discern beside it, so that chapter's blanks are the argument it is making. Second Thessalonians one measured highest as well and has the cleanest blanks yet recorded on this list - not one drawable content word above a single occurrence - and it is deferred rather than refused, because opening the largest missing block in this collection with a chapter about flaming vengeance would introduce Paul by his hardest page. Advocating a soul is the work; the warning is real and it is not the doorway.";
  "THIS CHAPTER'S BLANKS ARE THE DASH, THE PRONOUNS, THE ARTICLE, AND TWO PLACE NAMES. Macedonia and Achaia are the only words above a single occurrence that the table cannot draw and that a picture ever could, and this Bible does not draw place names at all - Jerusalem stood in letters through the whole of the chapter before this one. So the profile is the one the fourth entry set down and every entry since has used: thin in grammar, not in vocabulary. It cost no new picture.";
  "IT IS TEN VERSES, AND THAT IS A REASON RATHER THAN AN APOLOGY. The fifth entry above was the first chosen partly for being short, on the ground that what gets finished is what gets read. Ten verses is the shortest chapter on the current shortlist, and it is a whole chapter rather than an extract, so a reader who opens it finishes it.";
  "AND IT FOLLOWS LUKE TWENTY FOUR ON PURPOSE. The chapter before this one ends with the risen Christ carried up into the sky and eleven men told to wait in the city until they are clothed with power. This one is a church standing on the far side of that waiting: they turned from idols to serve the living and true God, and they are waiting for His Son from heaven, whom He raised from the dead. This list keeps the order things were written in rather than the order of the Bible, so a reader meeting the two in sequence meets the waiting and then the waiting kept.";
  "SEVEN PICTURES CARRY THIS PAGE THAT NO GOSPEL CHAPTER EVER NEEDED, AND EVERY ONE WAS ALREADY BOUGHT. The church, the gift, the praying hands, the brother, the sparkle, the hammer and the turning back were seated by earlier chapters against gospel words, and this is the first letter they have ever had to carry. A letter is a different kind of sentence from a narrative - it thanks, it recalls, it argues where a gospel walks and points - and the table met it without one new picture. That is the strongest form of the argument for a table keyed by root, and it arrives as a measurement: the words a letter needs turn out to be the words the gospels already paid for.";
  "THE NEGATION FALLS THREE TIMES AND EVERY ONE OF THEM REPLACES THE ENGLISH WORD NOT. The gospel came not in word only, it rang out not only in Macedonia, and there is no need for us to speak - all three are ou standing on its own, so the sign stands exactly where the word not would. Where English carries the negative inside some other word the mark is left off, which is the rule the fourteenth of John wrote down and the entry before this one had to apply twice in a single chapter.";
  "THE HOLY SPIRIT IS TWO MARKS AND THEY ARE WRITTEN IN THE ENGLISH ORDER. Greek says the spirit the holy and English says the Holy Spirit, and a picture reader has no word order of their own to fall back on - they are reading the carrier language's. So the sparkle goes in front of the wind here, in the fifth verse and again in the sixth, because the sentence around the marks is English and a mark that fought its own sentence would be read twice.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "1TH01",
    reference: "1 Thessalonians 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "Paul,",
          "$plus",
          "Silvanus,",
          "$plus",
          "Timothy,",
          "To",
          "the",
          "$church",
          "of",
          "the",
          "Thessalonians",
          "$tray_in",
          "$fire",
          "the",
          "$father",
          "$plus",
          "the",
          "$crown",
          "$cross",
          "$oil:",
          "$gift",
          "to",
          "you",
          "$plus",
          "peace.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "We",
          "always",
          "thank",
          "$fire",
          "for",
          "all",
          "of",
          "you,",
          "$hammer",
          "mention",
          "of",
          "you",
          "in",
          "our",
          "$hands_praying.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "continually",
          "recalling",
          "your",
          "$tools",
          "of",
          "$anchor,",
          "$plus",
          "your",
          "labor",
          "of",
          "$heart_red,",
          "$plus",
          "your",
          "enduring",
          "hope",
          "in",
          "our",
          "$crown",
          "$cross",
          "$oil,",
          "before",
          "our",
          "$fire",
          "$plus",
          "$father.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "We",
          "$lightbulb,",
          "$brother",
          "$heart_red",
          "by",
          "$fire,",
          "that",
          "He",
          "has",
          "chosen",
          "you.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$pointing",
          "our",
          "gospel",
          "came",
          "to",
          "you",
          "$no_entry",
          "$tray_in",
          "$speech",
          "only,",
          "but",
          "$plus",
          "$tray_in",
          "$lightning,",
          "$plus",
          "$tray_in",
          "the",
          "$sparkle",
          "$wind,",
          "$plus",
          "great",
          "conviction.",
          "You",
          "$lightbulb",
          "how",
          "we",
          "lived",
          "$tray_in",
          "you",
          "for",
          "your",
          "sake.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$plus",
          "you",
          "became",
          "imitators",
          "of",
          "us",
          "$plus",
          "of",
          "the",
          "$crown,",
          "when",
          "you",
          "welcomed",
          "the",
          "$speech",
          "$tray_in",
          "great",
          "suffering",
          "with",
          "the",
          "$smile",
          "of",
          "the",
          "$sparkle",
          "$wind.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "As",
          "a",
          "result",
          "you",
          "have",
          "become",
          "an",
          "example",
          "to",
          "all",
          "the",
          "$anchor",
          "$tray_in",
          "Macedonia",
          "$plus",
          "$tray_in",
          "Achaia.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "For",
          "the",
          "$speech",
          "of",
          "the",
          "$crown",
          "has",
          "rung",
          "out",
          "from",
          "you,",
          "$no_entry",
          "only",
          "$tray_in",
          "Macedonia",
          "$plus",
          "Achaia,",
          "but",
          "$tray_in",
          "every",
          "place",
          "your",
          "$anchor",
          "in",
          "$fire",
          "has",
          "gone",
          "out,",
          "so",
          "that",
          "we",
          "do",
          "$no_entry",
          "need",
          "to",
          "$mouth",
          "anything",
          "more.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "For",
          "$pointing_back",
          "themselves",
          "report",
          "what",
          "kind",
          "of",
          "welcome",
          "you",
          "gave",
          "us,",
          "$plus",
          "how",
          "you",
          "$turn_back",
          "to",
          "$fire",
          "from",
          "idols",
          "to",
          "serve",
          "the",
          "$sprout",
          "$plus",
          "true",
          "$fire.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$plus",
          "to",
          "await",
          "$pointing_back",
          "$son",
          "$tray_out",
          "$sky,",
          "whom",
          "He",
          "raised",
          "$tray_out",
          "the",
          "$skull,",
          "$cross",
          "our",
          "deliverer",
          "$tray_out",
          "the",
          "wrath",
          "that",
          "is",
          "$footprints.",
        ],
      },
    ],
  };
  return chapter;
}
