export function bible_glyph_chapter_lev11() {
  "The eleventh chapter of Leviticus, drawn in pictures. A long list of animals sorted into what may be eaten and what may not, and then a longer list of what happens when a dead one is touched. It ends with the reason, which is that God is holy.";
  "UNCLEAN IS SAID THIRTY FOUR TIMES AND CLEAN IS SAID FOUR. The verb for becoming or making unclean is used twenty times and the adjective fourteen. Against that, the adjective for clean is used three times and the verb once. The chapter is not a balance between two states. It is almost all one direction of travel.";
  "A LAND ANIMAL IS TESTED IN TWO HALVES, AND FOUR ANIMALS FAIL ONE HALF EACH. The hoof must be split and the cud must come back up. The word for hoof is used nine times and the word for cud seven. Verses four to seven walk through the camel, the rock badger and the rabbit, which chew but do not divide, and then the pig, which divides but does not chew. Passing one half is not passing.";
  "THE WORD FOR A DEAD BODY AND THE WORD FOR TOUCHING ARRIVE IN THE SAME VERSE. Both are first used at verse eight, at the end of the land animal list. The dead body word is then used twelve more times and touching six more, and every one of those comes from verse twenty four onward. The first half of the chapter is about eating and the second half is about handling.";
  "NINE TIMES A CASE IS CLOSED THE SAME WAY, AND THE WORD IS EVENING. Unclean until the evening, again and again, from verse twenty four to verse forty. Washing the clothes is said four times inside that run. The chapter keeps giving the same short sentence back, which is what makes it a rule rather than a story.";
  "THE THINGS THAT CRAWL GET A WORD OF THEIR OWN, USED FIFTEEN TIMES. The noun for a swarming thing is used ten times and the verb for swarming five. Alongside it runs the word for detestable, eight times as a noun and three as a verb. These are the creatures the chapter comes back to last, at verses forty one to forty four, just before the reason is given.";
  "HOLY IS SAID ONLY IN THE LAST TWO VERSES OF THE SPEECH, AND SO IS THE NAME. All four uses of holy are at verses forty four and forty five, twice in each, and two of the three uses of the name of the LORD are in those same two verses. Then the last verse of the chapter is the word for separating one thing from another, which is the same word Leviticus ten used to say what a priest is for.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV11",
    reference: "Leviticus 11",
    verses: [
      {
        verse_number: 1,
        words: [
          "$mouth",
          "$name_tag",
          "to",
          "Moses",
          "and to Aaron,",
          "$speech",
          "them:",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$mouth",
          "to",
          "$son",
          "of Israel,",
          "$speech",
          "$sprout",
          "you may eat",
          "of all",
          "the beasts",
          "of",
          "$earth.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "any",
          "hoof",
          "completely divided",
          "that has a split",
          "and that chews",
          "the cud",
          "animal,",
          "you may eat.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "But of those",
          "the following",
          "$no_entry",
          "to eat",
          "that only chew",
          "the cud",
          "or only have a divided",
          "hoof:",
          "$camel,",
          "though",
          "chews",
          "the cud",
          "it,",
          "hoof",
          "does not",
          "have a divided,",
          "is unclean",
          "it",
          "for you.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The rock badger,",
          "though",
          "chews",
          "the cud",
          "it,",
          "hoof",
          "$no_entry",
          "have a divided,",
          "is unclean",
          "it",
          "for you.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The rabbit,",
          "though",
          "chews",
          "the cud",
          "it,",
          "hoof",
          "$no_entry",
          "have a divided,",
          "is unclean",
          "it",
          "for you.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "And",
          "the pig,",
          "though",
          "completely divided",
          "hoof",
          "it has,",
          "a split,",
          "the cud",
          "$no_entry",
          "chew,",
          "unclean",
          "it is",
          "for you.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$meat",
          "$no_entry",
          "you must not eat,",
          "their carcasses",
          "$no_entry",
          "or touch;",
          "are unclean",
          "they",
          "for you.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "you may eat",
          "of all the creatures",
          "that live",
          "$water",
          "anything",
          "with fins",
          "and scales,",
          "$water",
          "$sea",
          "or in the streams.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "everything",
          "that",
          "does not",
          "have fins",
          "and scales",
          "$sea",
          "or streams,",
          "among all",
          "the teeming",
          "$water",
          "$person_other",
          "$sprout",
          "$water",
          "are detestable,",
          "but the following",
          "to you.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "an abomination",
          "they shall be",
          "to you;",
          "$meat",
          "$no_entry",
          "eat,",
          "their carcasses",
          "and you must detest.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "everything",
          "that",
          "does not",
          "have",
          "fins",
          "and scales",
          "$water",
          "shall be detestable",
          "to you.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Additionally,",
          "the following",
          "you are to detest",
          "$tray_out",
          "$bird,",
          "$no_entry",
          "be eaten,",
          "are detestable",
          "because they:",
          "$eagle,",
          "the bearded vulture,",
          "the black vulture,",
        ],
      },
      {
        verse_number: 14,
        words: ["the kite,", "of falcon", "any kind,"],
      },
      {
        verse_number: 15,
        words: ["any", "$raven", "kind,"],
      },
      {
        verse_number: 16,
        words: [
          "$woman",
          "the ostrich,",
          "the screech owl,",
          "the gull,",
          "of hawk",
          "any kind,",
        ],
      },
      {
        verse_number: 17,
        words: ["$cup,", "the cormorant,", "the great owl,"],
      },
      {
        verse_number: 18,
        words: ["the white owl,", "the desert owl,", "the osprey,"],
      },
      {
        verse_number: 19,
        words: [
          "the stork,",
          "of heron",
          "any kind,",
          "the hoopoe,",
          "and",
          "the bat.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "All",
          "insects",
          "$bird",
          "$walking",
          "on",
          "all fours",
          "are detestable",
          "to you.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "However,",
          "the following",
          "you may eat",
          "kinds of",
          "insects",
          "$bird",
          "$walking",
          "on",
          "all fours:",
          "those",
          "$no_entry",
          "having jointed legs",
          "above",
          "$foot",
          "for hopping",
          "on",
          "$earth.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Of these",
          "you may eat",
          "$locusts",
          "any kind,",
          "katydid,",
          "cricket,",
          "or grasshopper.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "All other",
          "insects",
          "$bird",
          "that",
          "have",
          "four",
          "$foot",
          "are detestable",
          "to you.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "These creatures",
          "will make you unclean.",
          "Whoever",
          "touches",
          "their carcasses",
          "will be unclean",
          "until",
          "evening,",
        ],
      },
      {
        verse_number: 25,
        words: [
          "and whoever",
          "picks up",
          "one of their carcasses",
          "must wash",
          "$garment,",
          "and he will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "Every",
          "animal",
          "with",
          "completely divided",
          "hooves",
          "not",
          "the cud",
          "or that does not",
          "chew",
          "is unclean",
          "for you.",
          "Whoever",
          "touches",
          "any of them",
          "will be unclean.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "All",
          "$walking",
          "their paws",
          "$sprout",
          "$walking",
          "on,",
          "are unclean",
          "for you;",
          "whoever",
          "touches",
          "their carcasses",
          "will be unclean",
          "until",
          "evening,",
        ],
      },
      {
        verse_number: 28,
        words: [
          "and anyone who picks up",
          "a carcass",
          "must wash",
          "$garment,",
          "and he will be unclean",
          "until",
          "evening.",
          "are unclean",
          "They",
          "for you.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "The following",
          "for you",
          "are unclean",
          "creatures",
          "that move",
          "along",
          "$earth:",
          "the mole,",
          "the mouse,",
          "of great lizard",
          "any kind,",
        ],
      },
      {
        verse_number: 30,
        words: [
          "the gecko,",
          "$lightning,",
          "the common lizard,",
          "the skink,",
          "and the chameleon.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "These animals",
          "are unclean",
          "for you",
          "among all",
          "the crawling creatures.",
          "Whoever",
          "touches",
          "them",
          "$skull",
          "shall be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "When",
          "one of them",
          "and falls",
          "on",
          "something",
          "$skull,",
          "that article becomes unclean,",
          "any",
          "article",
          "$tree,",
          "$garment,",
          "leather,",
          "$sackcloth,",
          "or any",
          "implement",
          "$hammer",
          "$tools",
          "$water",
          "$footprints",
          "and will remain unclean",
          "until",
          "evening;",
          "then it will be clean.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "a",
          "pot",
          "clay,",
          "falls",
          "if any of them",
          "into,",
          "everything",
          "in",
          "it will be unclean;",
          "you must break the pot.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "Any",
          "food",
          "$footprints",
          "into contact",
          "$water",
          "will be unclean,",
          "and any",
          "drink",
          "in such a",
          "container",
          "will be unclean.",
        ],
      },
      {
        verse_number: 35,
        words: [
          "Anything",
          "upon which",
          "falls",
          "one of their carcasses",
          "will be unclean.",
          "If it is an oven",
          "or cooking pot,",
          "it must be smashed;",
          "is unclean",
          "it,",
          "unclean",
          "and will remain",
          "for you.",
        ],
      },
      {
        verse_number: 36,
        words: [
          "Nevertheless,",
          "$spring",
          "or cistern",
          "containing",
          "$water",
          "will remain",
          "clean,",
          "but one who touches",
          "a carcass in it",
          "will be unclean.",
        ],
      },
      {
        verse_number: 37,
        words: [
          "If",
          "falls",
          "a carcass",
          "on",
          "any",
          "$seed",
          "for sowing,",
          "is clean",
          "the seed.",
        ],
      },
      {
        verse_number: 38,
        words: [
          "but if",
          "$hands_giving",
          "$water",
          "on",
          "$seed",
          "falls",
          "and a carcass",
          "on it,",
          "is unclean",
          "it",
          "for you.",
        ],
      },
      {
        verse_number: 39,
        words: [
          "If",
          "$skull",
          "$tray_out",
          "animal",
          "that",
          "you",
          "may eat,",
          "anyone who touches",
          "the carcass",
          "will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 40,
        words: [
          "Whoever eats",
          "from the carcass",
          "must wash",
          "$garment",
          "and will be unclean",
          "until",
          "evening,",
          "and anyone who picks up",
          "the carcass",
          "must wash",
          "$garment",
          "and will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 41,
        words: [
          "Every",
          "creature",
          "that moves",
          "along",
          "$earth",
          "is detestable;",
          "it",
          "$no_entry",
          "be eaten.",
        ],
      },
      {
        verse_number: 42,
        words: [
          "whether",
          "$walking",
          "on",
          "its belly",
          "or",
          "$walking",
          "on",
          "four",
          "or",
          "more",
          "$foot,",
          "any creature",
          "that moves",
          "along",
          "$earth,",
          "$no_entry",
          "eat,",
          "for",
          "are detestable",
          "such creatures.",
        ],
      },
      {
        verse_number: 43,
        words: [
          "$no_entry",
          "defile",
          "$person_other",
          "by any",
          "crawling creature,",
          "$no_entry",
          "become unclean",
          "or defiled",
          "by them.",
        ],
      },
      {
        verse_number: 44,
        words: [
          "For",
          "I",
          "$name_tag",
          "$fire.",
          "$sparkle,",
          "and be",
          "$sparkle,",
          "because",
          "$sparkle",
          "I.",
          "$no_entry",
          "defile",
          "$person_other",
          "by any",
          "creature",
          "that crawls",
          "along",
          "$earth.",
        ],
      },
      {
        verse_number: 45,
        words: [
          "For",
          "I",
          "$name_tag",
          "who brought you up",
          "$earth",
          "of Egypt,",
          "so that I would be",
          "your",
          "$fire;",
          "therefore be",
          "$sparkle,",
          "because",
          "$sparkle",
          "I.",
        ],
      },
      {
        verse_number: 46,
        words: [
          "This",
          "$scroll",
          "regarding animals,",
          "$bird,",
          "all",
          "$person_other",
          "$sprout",
          "that move",
          "$water,",
          "and all",
          "$person_other",
          "that crawl",
          "along",
          "$earth,",
        ],
      },
      {
        verse_number: 47,
        words: [
          "You must distinguish",
          "between",
          "the unclean",
          "between",
          "and the clean,",
          "$sprout",
          "that may be eaten,",
          "$sprout",
          "that",
          "$no_entry",
          "be.",
        ],
      },
    ],
  };
  return chapter;
}
