export function bible_glyph_roots_hebrew_drafted() {
  "The Old Testament words seated in bulk by the AI rather than one at a time in the hand-written table, one row each: the Strong's number, the root family it is filed under, its picture and a short gloss. The hand-written table merges these in, so every reader sees one table.";
  "THE HUMAN ASKED FOR THE WHOLE BIBLE ON 2026-10-07, names first and then everything else, with the AI deciding and readers correcting later. Seating thirteen thousand words one paragraph at a time would never finish, so the reasons are written once per rule here instead of once per word, and a word that needs a reason of its own goes in the hand-written table instead.";
  "NAMES ARE DRAWN BY WHAT STRONG'S SAYS THEY MEAN. A name made of a root and God is the two pictures in the order the name says them, with no tag, the way Joshua is I AM and the lifebuoy: Isaiah, Jah has saved, is the lifebuoy and I AM, and Jehoshaphat, Jehovah judged, is I AM and the scales. Yah, Yeho and the -iah ending are I AM; El is the burning heart. A name made of one root is that root's picture and the name tag. Where the root's picture is two parts, the part that carries the meaning stands, so hearing is the ear without the loudspeaker.";
  "A NAME IS FILED UNDER THE ROOT IT IS MADE FROM, so Samuel and Ishmael, both God hears, are one family and may share one picture without colliding; the letters under the picture still tell them apart.";
  "A NAME WAITS rather than half-drawn when Strong's calls it uncertain, when the root it names has no picture yet, or when the meaning Strong's gives is not what that root's picture shows. Saul and Judas wait by the human's choice.";
  "EACH ROW IS WRITTEN AS FOUR WORDS IN A LIST, number, root, picture, gloss, because thousands of rows spelled as objects would bury the decisions in their own punctuation.";
  "A TWO-PART PICTURE KEEPS THE PART THAT SAYS THE NAME. Benjamin, son of the right hand, is the son and the right arrow, because the hand alone loses which hand and son, hand and arrow is three parts; Hezekiah keeps the flexed arm without the up arrow. Where both parts carry the meaning, as in blessing, which is speech and a thumbs up, the name waits.";
  "A NAME ALSO WAITS WHEN ONE OF ITS PICTURES WOULD ARRIVE AS LETTERS OR IN THE READER'S OWN FONT. The artwork set has no brother and no family, so Ahab, Ahijah, Ammon and Amram wait, and sabbath, calf, sacrifice, iron and fruit are still English words, so Shabbethai, Eglon, Zebah, Barzillai and Ephrath wait with them; half a name drawn and half spelled stops reading as one name.";
  "A NAME WAITS WHEN ITS TWO PICTURES ARE A COMMON PHRASE ON THEIR OWN. The last picture of one word and the first of the next can be read as one name, so Adonijah, the crown and I AM, would be read wherever the Lord GOD is said, eighty four times, against twenty six real ones; Hor is every mount before a name, and Shem every name before one. Where the false readings rival the real ones the name waits; Jonathan stays, read falsely twenty five times against eighty two, because the false reading is I AM giving, which is what those verses say.";
  let rows = [
    ["4124", "ab", "father+proper_name", "Moab, from father"],
    ["1144", "ben", "son+right_arrow", "Benjamin, son of the right hand"],
    ["3414", "rum", "up_arrow+i_am", "Jeremiah, Jah will rise"],
    ["8050", "shama", "ear+heart_on_fire", "Samuel, heard of God"],
    ["2396", "chazaq", "might+i_am", "Hezekiah, strengthened of Jah"],
    ["53", "ab", "father+peace", "Absalom, father of peace"],
    ["8111", "shamar", "guard+proper_name", "Samaria, watch-station"],
    ["3092", "mishpat", "i_am+scales", "Jehoshaphat, Jehovah-judged"],
    ["3083", "nathan", "i_am+hands_giving", "Jonathan, Jehovah-given"],
    ["7205", "raah", "eyes+son", "Reuben, see ye a son"],
    ["40", "ab", "father+king", "Abimelech, father of the king"],
    ["6667", "tsedeq", "ruler+i_am", "Zedekiah, right of Jah"],
    ["74", "ab", "father+lamp", "Abner, father of light"],
    ["3058", "hu", "i_am+pointing_back", "Jehu, Jehovah is He"],
    ["6659", "tsedeq", "ruler+proper_name", "Zadok, just"],
    ["3077", "yada", "i_am+lightbulb", "Jehoiada, Jehovah-known"],
    ["3458", "shama", "ear+heart_on_fire", "Ishmael, God will hear"],
    ["623", "asaph", "crowd+proper_name", "Asaph, collector"],
    ["8095", "shama", "ear+proper_name", "Simeon, hearing"],
    ["2148", "zakar", "reminder_ribbon+i_am", "Zechariah, Jah has remembered"],
    ["5416", "nathan", "hands_giving+proper_name", "Nathan, given"],
    ["1141", "banah", "brick+i_am", "Benaiah, Jah has built"],
    ["8098", "shama", "ear+i_am", "Shemaiah, Jah has heard"],
    ["3470", "yasha", "rescue+i_am", "Isaiah, Jah has saved"],
    ["3079", "qum", "i_am+pointing_up", "Jehoiakim, Jehovah will raise"],
    ["3612", "keleb", "dog+proper_name", "Caleb"],
    ["2574", "chomah", "wall+proper_name", "Hamath, walled"],
    ["5941", "alah", "pointing_up+proper_name", "Eli, lofty"],
    ["1436", "gadal", "top+i_am", "Gedaliah, Jah has become great"],
    ["3316", "pathach", "unlocked+proper_name", "Jephthah, he will open"],
    ["3442", "yehoshua", "i_am+rescue", "Jeshua, he will save"],
    ["3088", "rum", "i_am+up_arrow", "Jehoram, Jehovah-raised"],
    ["550", "aman", "anchor+proper_name", "Amnon, faithful"],
    ["895", "babel", "face_spiral", "Babel"],
    ["29", "ab", "father+i_am", "Abijah, father of Jah"],
    ["4641", "asah", "hammer+i_am", "Maaseiah, work of Jah"],
    ["446", "ab", "heart_on_fire+father", "Eliab, God of father"],
    ["5662", "ebed", "kneeling+i_am", "Obadiah, serving Jah"],
    ["5418", "nathan", "hands_giving+i_am", "Nethaniah, given of Jah"],
    ["3124", "yonah", "dove+proper_name", "Jonah, dove"],
    ["3100", "yhwh", "i_am+heart_on_fire", "Joel, Jehovah is his God"],
    ["2900", "tob", "thumbs_up+i_am", "Tobiah, goodness of Jehovah"],
    ["8297", "sar", "military_medal+proper_name", "Sarai, dominative"],
    ["1968", "aman", "anchor+proper_name", "Heman, faithful"],
    ["476", "shama", "heart_on_fire+ear", "Elishama, God of hearing"],
    ["475", "shub", "heart_on_fire+turn_back", "Eliashib, God will restore"],
    ["5369", "ner", "lamp+proper_name", "Ner, lamp"],
    ["4441", "melek", "king+i_am", "Malchiah, king of Jah"],
    ["1954", "yasha", "rescue+proper_name", "Hoshea, deliverer"],
    ["568", "amar", "speech+i_am", "Amariah, Jah has said"],
    ["7237", "rabab", "multiply+proper_name", "Rabbah, great"],
    ["5417", "nathan", "hands_giving+heart_on_fire", "Nethanel, given of God"],
    ["3406", "rum", "up_arrow+proper_name", "Jerimoth, elevations"],
    ["3171", "chayah", "sprout+heart_on_fire", "Jehiel, God will live"],
    ["1137", "banah", "brick+proper_name", "Bani, built"],
    ["8203", "mishpat", "scales+i_am", "Shephatiah, Jah has judged"],
    ["4266", "machaneh", "camp+proper_name", "Mahanaim, double camp"],
    ["2544", "chamor", "donkey+proper_name", "Hamor, donkey"],
    ["1712", "dag", "fish+proper_name", "Dagon, the fish-god"],
    ["6943", "qadash", "sparkle+proper_name", "Kedesh, a sanctum"],
    ["2147", "zakar", "reminder_ribbon+proper_name", "Zichri, memorable"],
    ["471", "qum", "heart_on_fire+pointing_up", "Eliakim, God of raising"],
    ["30", "hu", "father+pointing_back", "Abihu, father of Him"],
    ["4435", "malkah", "queen+proper_name", "Milcah, queen"],
    ["3048", "yada", "lightbulb+i_am", "Jedaiah, Jah has known"],
    ["1283", "ra", "thumbs_down+proper_name", "Beriah, in trouble"],
    ["453", "hu", "heart_on_fire+pointing_back", "Elihu, God of him"],
    ["121", "adam", "person+proper_name", "Adam"],
    ["48", "ab", "father+up_arrow", "Abiram, father of height"],
    ["7935", "shakan", "tent+i_am", "Shechaniah, Jah has dwelt"],
    ["7652", "sheba", "seven+proper_name", "Sheba, seven"],
    ["5374", "ner", "lamp+i_am", "Neriah, light of Jah"],
    ["2139", "zakar", "reminder_ribbon+proper_name", "Zaccur, mindful"],
    ["7597", "shaal", "question+heart_on_fire", "Shealtiel, I have asked God"],
    ["5176", "nachash", "snake+proper_name", "Nahash"],
    [
      "494",
      "nathan",
      "heart_on_fire+hands_giving",
      "Elnathan, God is the giver",
    ],
    ["583", "ish", "man_beard+proper_name", "Enosh"],
    ["6144", "ir", "city+proper_name", "Ar, a city"],
    ["3043", "yada", "lightbulb+heart_on_fire", "Jediael, knowing God"],
    ["2062", "zeeb", "wolf+proper_name", "Zeeb, wolf"],
    ["501", "asah", "heart_on_fire+hammer", "Elasah, God has made"],
    ["460", "yasaph", "heart_on_fire+plus", "Eliasaph, God is gatherer"],
    ["458", "melek", "heart_on_fire+king", "Elimelech, God of the king"],
    ["8017", "shalom", "peace+heart_on_fire", "Shelumiel, peace of God"],
    ["7509", "rapha", "bandage+i_am", "Rephaiah, Jah has cured"],
    ["6698", "tsur", "rock+proper_name", "Zur, rock"],
    ["3469", "yasha", "rescue+proper_name", "Ishi, saving"],
    ["468", "tsur", "heart_on_fire+rock", "Elizur, God of the rock"],
    ["171", "ohel", "tent+father", "Oholiab, tent of his father"],
    ["170", "ohel", "tent+proper_name", "Oholah, her tent"],
    ["126", "adamah", "brown_square+proper_name", "Admah, earthy"],
    ["38", "ab", "father+sea", "Abiam, father of the sea"],
    ["8114", "shamar", "guard+i_am", "Shemariah, Jah has guarded"],
    ["7211", "raah", "eyes+i_am", "Reaiah, Jah has seen"],
    ["6611", "pathach", "unlocked+i_am", "Pethahiah, Jah has opened"],
    ["1845", "yada", "heart_on_fire+lightbulb", "Eliada, God is knowing"],
    ["3065", "yehudi", "menorah", "Jehudi"],
    ["8061", "shem", "name_tag+lightbulb", "Shemida, name of knowing"],
    ["7055", "qum", "pointing_up+heart_on_fire", "Kemuel, raised of God"],
    ["6981", "qara", "waving_hand+proper_name", "Kore, crier"],
    ["5752", "ed", "witness+proper_name", "Oded, reiteration"],
    ["4439", "melek", "king+heart_on_fire", "Malchiel, king of God"],
    ["4105", "tob", "thumbs_up+heart_on_fire", "Mehetabel, bettered of God"],
    ["3437", "shub", "turn_back+proper_name", "Jashub, he will return"],
    ["3359", "qum", "pointing_up+i_am", "Jekamiah, Jah will rise"],
    ["3168", "chazaq", "might+heart_on_fire", "Ezekiel, God will strengthen"],
    ["3037", "yada", "lightbulb+proper_name", "Jaddua, knowing"],
    ["2984", "bachar", "check_box+proper_name", "Ibhar, choice"],
    ["1955", "yasha", "rescue+i_am", "Hoshaiah, Jah has saved"],
    ["140", "adon", "crown+pointing_up", "Adonikam, lord of rising"],
    ["22", "ab", "father+heart_on_fire", "Abiel, father of God"],
    ["8616", "tiqvah", "crossed_fingers+proper_name", "Tikvah, hope"],
    ["2897", "tob", "thumbs_up+proper_name", "Tob, good"],
    ["3479", "yisrael", "wrestling+heart_on_fire", "Israel"],
    ["3481", "yisrael", "wrestling+heart_on_fire", "Israelite"],
    ["3061", "yadah", "hands_raised+proper_name", "Judah"],
  ];
  let drafted = [];
  for (let row of rows) {
    drafted.push({
      strong: row[0],
      root: row[1],
      glyph: row[2],
      gloss: row[3],
    });
  }
  return drafted;
}
