export function bible_interpolation_brief() {
  "The whole brief for what a played piece may add that a passage did not give - whether playing licenses more than watching does, what the player's hand may do to given material, and the one form in which a gap may be approached openly rather than filled.";
  "★ THE MEDIUM IS NOT THE BOUNDARY, AND IT IS WORTH SAYING BECAUSE IT LOOKS LIKE ONE. The rule already settled asks what an addition is MADE OF and WHERE IT CAME FROM - events, causes and motives from nobody are invention; look, sound, movement and pace are manner. Nothing in that test asks whether the thing is watched or played. So a cutscene may interpolate manner as freely as a game may, and a game may invent story no more freely than a cutscene may.";
  "The proof that a cutscene already interpolates is in the depiction brief itself. MAT16:14 reports that people said John the Baptist, Elijah, Jeremiah, one of the prophets, and putting three men on screen disagreeing depicts a scene the verse only summarised. That was allowed there, in a scene nobody plays. So the argument-made-into-an-argument is not a licence the game gets and the cutscene lacks; it is the same allowance in both.";
  "★ WHAT ACTUALLY DIFFERS IS THAT PLAYING COSTS TIME THE PASSAGE DID NOT ALLOCATE, AND PUTS THE PLAYER'S HAND IN THE MATERIAL. A reading crosses seven years in a sentence; a player cannot. So a played piece has to be operable and has to fit inside one unbroken stretch, and those are constraints rather than freedoms. The game is the harder case, not the looser one.";
  "★ THE GAME'S INTERPOLATION IS SELECTION AND ARRANGEMENT, NEVER COMPOSITION, AND THE WORD STEP ALREADY FORBIDS THE OTHER THING OUTRIGHT. It rules out any paraphrase and any choice of wording offered to the player, because a messenger who improves a message is a false messenger. So the argument is played by putting the verse's own four answers in place, not by writing what the crowd said. A player arranging given material is carrying it; a player supplying material is authoring it, and only the first is a mechanic here.";
  "That corrects a line written elsewhere in this conversation, which said Pilate's wife could be shown choosing which passage to send. Choosing between two things to say IS a choice of wording, and the word brief forbids it by name. The picture-choosing that is allowed is the opposite arrangement: the pictures carry the order and the given words are put under them.";
  "★ A BRIEF DREAM IS ALLOWED EXACTLY WHERE A DREAM WAS GIVEN, WHICH IS MOST OF THEM AND NOT ALL. GEN41 hands over seven fat cows, seven lean ones, seven full ears and seven thin ones, so a short showing of that is the passage at its own magnification. MAT27:19 hands over no picture at all, so a brief dream there is not a shortening of anything - it is the invention that was ruled out, and only a marked quotation gets round it.";
  "★ THE WHAT-IF IS A THIRD MARKED FORM AND SCRIPTURE WARRANTS IT AT HEB11:19. Abraham, offering Isaac, accounted that God was able to raise him up even from the dead, from whence also he received him in a figure. No resurrection happened - nobody died - so the receiving back was a figure and Abraham's reasoning was not what occurred. Scripture calls it faith anyway. A question about what God might do is therefore not a lapse in faith and not a departure from the text; it is one of the few interior movements Scripture stops to report.";
  "★ THE DISCRIMINATOR IS WHAT THE QUESTION CHANGES: A WHAT-IF THAT CHANGES WHAT YOU DO IS FAITH, AND A WHAT-IF THAT CHANGES WHAT YOU CLAIM HAPPENED IS FICTION. Abraham's made him climb the mountain and say at GEN22:5 that he and the lad would come again, and at GEN22:8 that God would provide himself a lamb. It never once became a story about Isaac being raised. The moment a what-if is depicted as an event it has stopped being a question and has answered itself.";
  "★ IT WORKS BY THE SAME MECHANISM AS THE MARKED QUOTATION, WHICH IS WHY BOTH ARE SAFE AND AN UNMARKED IMAGE IS NOT. A question asserts nothing. Marking is not decoration on the addition, it IS the addition's whole difference from a claim - the same picture presented as what somebody saw, and presented as what somebody might have wondered, are two different acts, and only one of them says something Scripture does not.";
  "★ AN EARLIER DRAFT HERE SAID A WHAT-IF MAY NEVER BE ANSWERED, AND THAT IS WRONG. Abraham's was answered, by Abraham, before he ever climbed. Isaac is promised descendants at GEN21:12; a dead and childless Isaac has none; therefore Isaac is raised. That is not a wondering, it is a deduction, and HEB11:19 uses the word for reckoning something up. So where Scripture supplies the premises, reaching the conclusion is arithmetic rather than invention, and the reasoning is the part most worth showing.";
  "★ WHAT MAY NEVER HAPPEN IS DEPICTING THE CONCLUSION AS AN EVENT, AND ABRAHAM IS THE PROOF, BECAUSE HIS REASONING WAS SOUND AND WHAT IT CONCLUDED DID NOT OCCUR. God provided a ram. Nobody died and nobody was raised. The deduction was not falsified either - HEB11:19 says he received Isaac back in a figure, so it was answered in a way he had not calculated - but a scene showing Isaac raised would be a scene of something that never happened. The reasoning may be shown, the conclusion may be reached, and the event stays where Scripture put it.";
  "The unexplained step is a different rule and is untouched by this. The angel does not get told what the cows meant, because GEN40:8 and DAN2:27-28 put interpretation with God - that forbids a MEANING being handed to the messenger, not a reader reasoning from premises he was already given. And the outcome is still never a score, for its own reason at GEN40:23.";
  "The ground matters as much as the marking. Abraham did not wonder freely; he reasoned from two things he had been given - GEN21:12, that in Isaac shall thy seed be called, and that God raises the dead - toward a gap between them. That is the same shape as asking how Uriah's name came to be known and finding him among the thirty at 2SA23:39. A what-if reasons FROM Scripture TOWARD a gap. It does not fill a gap with something nothing anywhere supplies.";
  "★ THE READING IS THE WHOLE OF WHAT IS HEARD, WHICH IS A TIGHTER RULE THAN THE ONE ON WHAT IS SEEN. A cutscene is somebody reading the passage over a picture. Where the passage gives direct speech the speaker may say their own words and be seen saying them, because those words ARE the passage and a reader saying them instead is a rendering choice rather than a difference in content. Everything else audible is a marked gloss from another passage. Nothing composed is ever heard.";
  "That is the cleanest split anybody has drawn here: invention lives in the picture and never in the ear. It gives a plain test a person can apply without consulting any of these briefs - write out everything the cutscene says aloud, and every word of it should be findable in a Bible.";
  "★ THE BEST WHAT-IF NEEDS NO INVENTED WORDS AT ALL, AND ABRAHAM IS THE PROOF A SECOND TIME. HEB11:19 states his reckoning outright, so that question is DELIVERED BY READING IT. Where no verse states the question, two verses read in succession will often produce it - GEN21:12, that in Isaac shall thy seed be called, then GEN22:2, to offer him there for a burnt offering - and a listener does the arithmetic without anybody having asked anything aloud. That is the marked gloss doing the work, and it leaves the audio rule whole.";
  "So a what-if that can be reached neither way is probably not grounded enough to show. If no verse states it and no pair of verses produces it, what is left is somebody's phrasing, and phrasing is exactly what the audio rule refuses.";
  "★ TRADITION AND COMMENTARY ARE FOR FINDING THE QUESTION AND NEVER FOR ANSWERING IT, WHICH IS ALSO WHY THEIR LICENCES MATTER MUCH LESS HERE THAN THEY LOOK LIKE THEY WOULD. The five rules put tradition fourth and a lower rule never buys a higher one, so no commentator can supply a premise Scripture does not. What a commentary is genuinely good for is three things: it shows which questions the church already thought worth asking, it hands over cross-references somebody has already done the work of assembling, and it reports readings that were tried and judged wrong - which is the cheapest way there is to avoid re-treading a settled error.";
  "That shrinks the licensing question rather than answering it. A commentary is prose, and prose is exactly what may never be heard, so none of it is ever redistributed - it feeds the SEARCH and never the OUTPUT, and what comes out the far end is a list of verse references. Anything old enough is public domain in any case; the point is that even a copyrighted one could be read for research without a word of it reaching a viewer. Where a source is quoted rather than consulted, the licence question is real again and belongs with the rest of them in the sources note.";
  "So Scripture plus a what-if is accepted as a form, and it is narrower than it sounds. The what-if is grounded in passages rather than in invention, is answered only so far as those passages answer it, is marked so plainly that nobody could mistake it for narration, and is never depicted as a thing that happened.";
  let brief = {
    step: "interpolation",
    what: "what a piece may add beyond what the passage gives, and how a gap may be approached without being filled",
    passages: [
      "HEB11:19",
      "GEN22:5",
      "GEN22:8",
      "GEN21:12",
      "MAT16:14",
      "GEN41",
      "MAT27:19",
    ],
    settled:
      "the bound is on kind and source and not on medium, so a cutscene interpolates manner as freely as a game does and invents story no more freely; every word heard aloud is Scripture, the passage read or a marked gloss, so invention lives in the picture only; the game's addition is selection and arrangement and never composition; a dream may be shown briefly wherever a dream was given; a what-if is warranted at HEB11:19, is reasoned from passages, may be answered where Scripture supplies the premises, and is never depicted as an event; a what-if is carried by reading the verse that states it or the pair of verses that produce it, so tradition and commentary feed the search and never the output",
    open: "which public-domain commentaries and traditions are worth searching, and who searches them; how a what-if and a gloss are marked on screen and in audio; whether a player may raise one or only ever hear one; how many a scene can carry before the scene is about the questions; whether a character's own words are spoken by the character or by the reader",
    forbidden:
      "any word heard aloud that is not Scripture; offering the player a choice of wording or letting them supply any; depicting a what-if or its conclusion as an event that happened; answering one whose premises no passage supplies; letting play succeed or fail by a what-if's answer; a brief dream where the passage gave no dream",
    done: "everything a cutscene says aloud can be found in a Bible, a played piece adds nothing a cutscene of the same passage could not add, and every question raised either follows from passages or is left standing",
  };
  return brief;
}
