export function bible_glyph_chapter_hos06() {
  "Hosea 6, drawn in pictures. The people say a beautiful thing about coming back to God, and God answers that their loyalty burns off like morning mist. It holds the line Jesus quoted twice - I desire mercy, not sacrifice - and it ends with a harvest and a promise. Eleven lines.";
  "THE LINE JESUS QUOTED TWICE DRAWS THREE PICTURES AND THAT IS THE WHOLE SENTENCE. For I desire mercy, not sacrifice, and the knowledge of God rather than burnt offerings. A gift, a refusal sign, and the flame that means God. Read only the marks and you get: gift - no - God. That is close to what the verse says, in three pictures, with nothing needed in between. Sacrifice and burnt offerings both arrive in plain letters, which leaves the refusal sign standing alone between the gift and God, exactly where the sentence puts it.";
  "THE SAME PICTURE IS DRAWN FOR WHAT GOD ASKS FOR AND FOR WHAT ISRAEL HAS, AND THE POINT IS THAT THEY DO NOT MATCH. The fourth verse says your loyalty is like a morning mist, like the early dew that vanishes. The sixth verse says I desire mercy. Both of those are the same Hebrew word, and this Bible draws it as a gift both times. So a reader with no English sees the gift picture appear, evaporate, and then be asked for again two lines later. The vanishing is drawn too - the word for it carries the walking mark, which is the picture of something going.";
  "THE SUN IS DRAWN TWICE ON THE WORD DAY AND NOT AT ALL ON THE SUNRISE. The second verse says after two days He will revive us, on the third day He will raise us up, and both of those days carry a sun. The very next verse says as surely as the sun rises, He will appear, and there is no sun on it. The picture is seated on the Hebrew word for a day, not on the burning thing in the sky, and here the two land one line apart, which is close enough together to see what is happening. A mark in this Bible belongs to a word, not to a thing.";
  "THE TURN BACK ARROW OPENS THE CHAPTER AND CLOSES IT, AND THE SECOND TIME GOD IS THE ONE TURNING. Come, let us return to the LORD, in the first verse. When I restore My people from captivity, in the eleventh. Same Hebrew root, same arrow, first said by the people about themselves and then by God about them. Between those two arrows the chapter turns from hope to indictment, so the picture makes an argument the words take eleven verses to make: they said they would turn, and in the end He is the one who turns them.";
  "THE SECOND VERSE DRAWS LIFE TWICE AS A GROWING PLANT. He will revive us, and that we may live in His presence. Two green shoots in one line, either side of on the third day He will raise us up. Christians have read that verse as resurrection for a very long time, and the page happens to draw it as two plants coming out of the ground with a raising between them.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "HOS06",
    reference: "Hosea 6",
    verses: [
      {
        verse_number: 1,
        words: [
          "$walking,",
          "let",
          "us",
          "$turn_back",
          "to",
          "the",
          "$name_tag.",
          "For",
          "He",
          "has",
          "torn",
          "us",
          "to",
          "pieces,",
          "but",
          "He",
          "will",
          "heal",
          "us;",
          "He",
          "has",
          "wounded",
          "us,",
          "but",
          "He",
          "will",
          "bind",
          "up",
          "our",
          "wounds.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "After",
          "two",
          "$sun",
          "He",
          "will",
          "$sprout",
          "us;",
          "on",
          "the",
          "third",
          "$sun",
          "He",
          "will",
          "raise",
          "us",
          "up,",
          "that",
          "we",
          "may",
          "$sprout",
          "in",
          "His",
          "presence.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "So",
          "let",
          "us",
          "$lightbulb",
          "-",
          "let",
          "us",
          "press",
          "on",
          "to",
          "$lightbulb",
          "the",
          "$name_tag.",
          "As",
          "surely",
          "as",
          "the",
          "sun",
          "rises,",
          "He",
          "will",
          "appear;",
          "He",
          "will",
          "$footprints",
          "to",
          "us",
          "like",
          "the",
          "rain,",
          "like",
          "the",
          "spring",
          "showers",
          "that",
          "water",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "What",
          "shall",
          "I",
          "$hammer",
          "with",
          "you,",
          "O",
          "Ephraim?",
          "What",
          "shall",
          "I",
          "$hammer",
          "with",
          "you,",
          "O",
          "Judah?",
          "For",
          "your",
          "$gift",
          "is",
          "like",
          "a",
          "morning",
          "mist,",
          "like",
          "the",
          "early",
          "dew",
          "that",
          "$walking.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Therefore",
          "I",
          "have",
          "hewn",
          "them",
          "by",
          "the",
          "$megaphone;",
          "I",
          "have",
          "slain",
          "them",
          "by",
          "the",
          "words",
          "of",
          "My",
          "mouth,",
          "and",
          "My",
          "$scales",
          "go",
          "forth",
          "like",
          "$light.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "For",
          "I",
          "desire",
          "$gift,",
          "$no_entry",
          "sacrifice,",
          "and",
          "the",
          "knowledge",
          "of",
          "$fire",
          "rather",
          "than",
          "burnt",
          "offerings.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "But",
          "they,",
          "like",
          "Adam,",
          "have",
          "transgressed",
          "the",
          "covenant;",
          "there",
          "they",
          "were",
          "unfaithful",
          "to",
          "Me.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Gilead",
          "is",
          "a",
          "city",
          "of",
          "evildoers,",
          "tracked",
          "with",
          "footprints",
          "of",
          "$blood.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Like",
          "raiders",
          "who",
          "lie",
          "in",
          "ambush,",
          "so",
          "does",
          "a",
          "band",
          "of",
          "$priest;",
          "they",
          "murder",
          "on",
          "the",
          "$road",
          "to",
          "Shechem;",
          "surely",
          "they",
          "have",
          "$hammer",
          "atrocities.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "I",
          "have",
          "$eye",
          "a",
          "horrible",
          "thing",
          "in",
          "the",
          "$house",
          "of",
          "Israel;",
          "there",
          "Ephraim",
          "practices",
          "prostitution",
          "and",
          "Israel",
          "is",
          "defiled.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Also,",
          "O",
          "Judah,",
          "a",
          "harvest",
          "is",
          "appointed",
          "for",
          "you,",
          "when",
          "I",
          "$turn_back",
          "My",
          "$family",
          "from",
          "captivity.",
        ],
      },
    ],
  };
  return chapter;
}
