export function bible_glyph_chapter_num17() {
  "The seventeenth chapter of Numbers, drawn in pictures. Thirteen verses. Twelve leaders each bring a wooden staff with his name written on it, and they are left overnight in the Tent. In the morning one of them has buds, blossoms and ripe almonds on it, and it is the one belonging to Aaron. The chapter ends with the people frightened, asking a question that nobody answers.";
  "THE WORD FOR STAFF IS SAID SEVENTEEN TIMES IN THIRTEEN VERSES. It is the most repeated word in the chapter, said more often than the name of the LORD. It has no picture in the table yet, so it stands here in plain letters. Every one of those staffs is a dead piece of cut wood, and by morning one of them has fruit on it.";
  "THE STAFFS ARE NAMED IN VERSES TWO TO TEN AND NEVER AGAIN. After verse ten the word is not used once. The last three verses are about people, not wood.";
  "MOSES IS NAMED EIGHT TIMES AND DOES EVERY SINGLE THING HE IS TOLD. Verses one, six, seven, eight, nine, ten, eleven and twelve. He is absent from verses two to five, which are God speaking, and from verse thirteen, which is the people speaking.";
  "THE TESTIMONY IS SAID FOUR TIMES AND IT IS ALWAYS A PLACE. Verses four, seven, eight and ten. The staffs are laid in front of it, the Tent is named after it, and at the end the one living staff is carried back and left there.";
  "THE PEOPLE DO NOT SPEAK UNTIL VERSE TWELVE. The word for saying is used four times and the first three belong to God and to Moses. Through the whole test the people say nothing. The first thing they say is that they are all going to die.";
  "THE CHAPTER ENDS ON A QUESTION AND NOBODY ANSWERS IT. The word for dying is used twice, at verse ten and verse thirteen. The first is God warning that the grumbling must stop or they will die. The second is the people asking whether they are all going to die anyway.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "NUM17",
    reference: "Numbers 17",
    verses: [
      {
        verse_number: 1,
        words: ["$name_tag", "$mouth", "to", "Moses,", "$speech"],
      },
      {
        verse_number: 2,
        words: [
          "$mouth",
          "to",
          "the",
          "$son",
          "of",
          "Israel",
          "and",
          "$hand_receiving",
          "from",
          "them",
          "twelve",
          "staffs,",
          "one",
          "from",
          "the",
          "leader",
          "of",
          "each",
          "$house",
          "of",
          "the",
          "$father,",
          "one",
          "for",
          "every",
          "$house",
          "of",
          "the",
          "$father.",
          "Write",
          "the",
          "$name_tag",
          "of",
          "each",
          "$man_beard",
          "on",
          "his",
          "staff.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "And",
          "write",
          "the",
          "$name_tag",
          "of",
          "Aaron",
          "on",
          "the",
          "staff",
          "of",
          "Levi,",
          "because",
          "there",
          "must",
          "be",
          "one",
          "staff",
          "for",
          "the",
          "head",
          "of",
          "each",
          "$house",
          "of",
          "the",
          "$father.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Place",
          "the",
          "staffs",
          "in",
          "the",
          "$tent",
          "of",
          "Meeting",
          "in",
          "front",
          "of",
          "the",
          "$witness,",
          "where",
          "I",
          "meet",
          "with",
          "you.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "staff",
          "belonging",
          "to",
          "the",
          "$man_beard",
          "I",
          "choose",
          "will",
          "sprout,",
          "and",
          "I",
          "will",
          "rid",
          "Myself",
          "of",
          "the",
          "constant",
          "grumbling",
          "of",
          "the",
          "$son",
          "of",
          "Israel",
          "against",
          "you.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "So",
          "Moses",
          "$mouth",
          "to",
          "the",
          "$son",
          "of",
          "Israel,",
          "and",
          "each",
          "of",
          "their",
          "leaders",
          "$hands_giving",
          "him",
          "a",
          "staff,",
          "one",
          "for",
          "each",
          "$house",
          "of",
          "the",
          "$father,",
          "twelve",
          "staffs",
          "in",
          "all.",
          "And",
          "the",
          "staff",
          "of",
          "Aaron",
          "was",
          "among",
          "them.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Then",
          "Moses",
          "placed",
          "the",
          "staffs",
          "before",
          "$name_tag",
          "in",
          "the",
          "$tent",
          "of",
          "the",
          "$witness.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "next",
          "day",
          "Moses",
          "$footprints",
          "the",
          "$tent",
          "of",
          "the",
          "$witness",
          "and",
          "saw",
          "that",
          "the",
          "staff",
          "of",
          "Aaron,",
          "which",
          "stood",
          "for",
          "the",
          "$house",
          "of",
          "Levi,",
          "had",
          "sprouted.",
          "It",
          "had",
          "put",
          "forth",
          "buds,",
          "blossomed,",
          "and",
          "produced",
          "almonds.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Then",
          "Moses",
          "brought",
          "out",
          "all",
          "the",
          "staffs",
          "from",
          "the",
          "presence",
          "of",
          "$name_tag",
          "to",
          "all",
          "the",
          "$son",
          "of",
          "Israel.",
          "They",
          "$eye",
          "them,",
          "and",
          "each",
          "$man_beard",
          "$hand_receiving",
          "his",
          "own",
          "staff.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$name_tag",
          "$speech",
          "to",
          "Moses,",
          "$turn_back",
          "the",
          "staff",
          "of",
          "Aaron",
          "in",
          "front",
          "of",
          "the",
          "$witness,",
          "to",
          "be",
          "kept",
          "as",
          "a",
          "sign",
          "for",
          "the",
          "rebellious",
          "$son,",
          "so",
          "that",
          "you",
          "may",
          "put",
          "an",
          "end",
          "to",
          "their",
          "grumbling",
          "against",
          "Me",
          "and",
          "they",
          "will",
          "$no_entry",
          "$skull.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "So",
          "Moses",
          "$hammer",
          "as",
          "$name_tag",
          "had",
          "commanded",
          "him;",
          "so",
          "he",
          "$hammer.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Then",
          "the",
          "$son",
          "of",
          "Israel",
          "$speech",
          "to",
          "Moses,",
          "$speech,",
          "Look,",
          "we",
          "are",
          "perishing.",
          "We",
          "are",
          "lost;",
          "we",
          "are",
          "all",
          "lost.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Anyone",
          "who",
          "comes",
          "near",
          "the",
          "tabernacle",
          "of",
          "$name_tag",
          "will",
          "$skull.",
          "Are",
          "we",
          "all",
          "going",
          "to",
          "perish?",
        ],
      },
    ],
  };
  return chapter;
}
