export function bible_glyph_chapter_psa101() {
  "The fifty seventh picture Bible chapter written by hand: the whole of the hundred and first psalm, a king promising who he will and will not let near him, in the shorthand a person types.";
  "IT IS EIGHT VERSES AND IT IS A JOB DESCRIPTION. Forty three in a hundred. David is not praying for anything here and not describing God either; he is saying out loud what kind of household he intends to run, and almost every line is either a promise to do something or a refusal to put up with someone. That makes it an unusually plain page for a reader with few words: the shape of a vow survives translation better than the shape of a poem does.";
  "THE NEGATION MARK FALLS SIX TIMES IN EIGHT VERSES AND IT IS WHAT THE PSALM IS MADE OF. Nothing worthless before his eyes, nothing clinging to him, nothing known of evil, no proud heart endured, no deceit dwelling in the house, no liar standing in front of him. Longer pages carry the mark more times, but only three anywhere on this list carry it more thickly per verse: the first psalm, the eighteenth of Ezekiel and the second letter of John. A reader who knows only that one picture can tell what sort of page this is before knowing a single other word on it.";
  "THE FAITHFUL GET THE ANCHOR MARK AND THIS IS THE FIRST HEBREW PAGE TO CARRY IT. Twenty four chapters here use that picture and every one of them until now was Greek, where it stands for believing. In the sixth verse it stands on the Hebrew for the trustworthy of the land - the people the king wants living with him. Same picture, and it has moved from something you do in your head to something other people can rely on you for. That is one root table doing what it was built to do.";
  "THE HEART MARK IS WHAT IS ACTUALLY BEING TESTED. It falls three times: walking in the house with integrity of heart in the second verse, the perverse heart sent away in the fourth, the proud heart not endured in the fifth. The king is not sorting people by what they have done but by what they are, and the mark lands on that word each time. Set beside the eyes mark, which falls four times and is always his own looking, the page reads as one man watching for one thing.";
  "TWO WORDS IN THE FIRST VERSE PAY FOR THE WHOLE PSALM. He will sing of loving devotion and of justice, and after that neither word is written again. Everything from the second verse on is one or the other being spent: the loyalty in who he keeps close, the justice in who he turns out. The gift mark and the scales mark each appear exactly once, at the top, and a reader who notices they never come back has understood the structure of the thing.";
  "THE LAST VERSE IS THE ONLY PLACE THE CITY MARK APPEARS AND IT CHANGES WHO IS SPEAKING. Up to the seventh verse the house is his own and so is the trouble. In the eighth the ground widens to the whole land and the city belongs to the LORD, not to him, which is the quiet admission the psalm has been walking toward. He is not clearing his own hall. He is a caretaker of a town that is not his.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA101",
    reference: "Psalm 101",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "will",
          "sing",
          "of",
          "$gift",
          "and",
          "$scales;",
          "to",
          "You,",
          "O",
          "$name_tag,",
          "I",
          "will",
          "sing",
          "praises.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "I",
          "will",
          "ponder",
          "the",
          "$road",
          "that",
          "is",
          "blameless.",
          "When",
          "will",
          "You",
          "$footprints",
          "to",
          "me?",
          "I",
          "will",
          "$walking",
          "with",
          "integrity",
          "of",
          "$heart_organ",
          "in",
          "my",
          "$house.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "I",
          "will",
          "set",
          "$no_entry",
          "worthless",
          "$speech",
          "before",
          "my",
          "$eyes.",
          "I",
          "hate",
          "the",
          "$hammer",
          "of",
          "those",
          "who",
          "fall",
          "away;",
          "it",
          "shall",
          "$no_entry",
          "cling",
          "to",
          "me.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "A",
          "perverse",
          "$heart_organ",
          "shall",
          "depart",
          "$tray_out",
          "me;",
          "I",
          "will",
          "$no_entry",
          "$lightbulb",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Whoever",
          "slanders",
          "his",
          "neighbor",
          "in",
          "secret,",
          "I",
          "will",
          "put",
          "to",
          "silence;",
          "the",
          "one",
          "with",
          "haughty",
          "$eyes",
          "and",
          "a",
          "proud",
          "$heart_organ",
          "I",
          "will",
          "$no_entry",
          "endure.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "My",
          "$eyes",
          "favor",
          "the",
          "$anchor",
          "of",
          "the",
          "$earth,",
          "that",
          "they",
          "may",
          "dwell",
          "with",
          "me;",
          "he",
          "who",
          "$walking",
          "in",
          "the",
          "$road",
          "of",
          "integrity",
          "shall",
          "minister",
          "to",
          "me.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$no_entry",
          "one",
          "who",
          "$hammer",
          "deceit",
          "shall",
          "dwell",
          "in",
          "my",
          "$house;",
          "$no_entry",
          "one",
          "who",
          "$mouth",
          "lies",
          "shall",
          "stand",
          "before",
          "my",
          "$eyes.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Every",
          "morning",
          "I",
          "will",
          "remove",
          "all",
          "the",
          "$thumbs_down",
          "of",
          "the",
          "$earth,",
          "that",
          "I",
          "may",
          "cut",
          "off",
          "every",
          "evildoer",
          "from",
          "the",
          "$city",
          "of",
          "the",
          "$name_tag.",
        ],
      },
    ],
  };
  return chapter;
}
