export function bible_verse_end_suffixes() {
  "The marks a finished sentence ends on, gathered from every language this repo ships a bible in rather than from the one this was first written for.";
  "It began as the three an English sentence ends on, which was right while the only reader of it was working through an English bible. A page that has to stop on a finished sentence in whatever languages a reader chose cannot use that set: a language whose sentences end on something else has no sentence that ever ends, so the page keeps reaching for one more verse and never finds it.";
  "The rest were measured rather than guessed. On 2026-08-12 the first sixteen verses of Luke 1 were read in all thirty-nine bibles this repo lists, and what each verse ended on was counted. Four marks did the work of a full stop and nothing else did: the one Latin script writes, the upright bar of Hindi, Bengali, Punjabi and Oriya, the round stop of Chinese, and the two dots of Amharic. Chinese also asks and exclaims with wider twins of the two Latin marks, so those are here beside them.";
  "Marks that only look like an ending are deliberately out. Amharic's own colon and semicolon end a clause rather than a sentence, and Arabic's comma leans the other way from the Latin one - each of those would have cut a sentence in half every time it appeared.";
  "One language ends on nothing at all. Thai writes a space where other languages write a stop, so no mark in any set could find the end of one of its sentences - which is why the folders that cannot be read this way are named separately rather than pretended about here.";
  "Urdu's full stop was added afterwards and is worth the sentence it takes. That first measurement was done by hand and it read Urdu under a folder name that did not exist, so every verse of it came back as nothing and Urdu was written down as a language without sentences. It is not: it ends them on a small upright stroke, which sits here now. What found the mistake was this being measured by a command that asks the list of bibles for their folder names instead of by somebody typing them, and that is the whole argument for the record beside this file.";
  "THEY ARE LISTED ONE BY ONE RATHER THAN SPELLED INTO ONE WORD, and the reason is that a full stop is not always one character long. Written as a word, this could only ever be cut back into single characters, so a language whose sentence ends on two of them had no way of being written down here at all - and the one reader of this list was already asking whether a verse ends on any of several suffixes, so nothing but this line had to change to let it say so.";
  "THREE MORE WERE MEASURED ON 2026-08-20 and each of them had a bible sitting at none out of sixteen until it arrived. Hebrew ends a verse on a mark whose name is end of verse. Burmese, Danu and Rakhine end a sentence on the section sign and a clause on the little section sign beside it, so only the first of that pair is here. Amharic ends one on its word separator written twice.";
  "THE DOUBLED AMHARIC SEPARATOR IS WHY THE LIST STOPPED BEING A WORD, and it does not take back the line above about the single one. One separator ends a word, and that is still true - the reading of it that refused it has not been overturned. Two of them together are a full stop, and an Amharic bible that types it that way rather than as the two dots reads with sentences again. A set of single characters could not tell those two apart, so it had to answer for the pair with the answer it had for one, and the answer it had for one was no.";
  let suffixes = [".", "?", "!", "।", "。", "።", "？", "！", "۔", "׃", "။", "፡፡"];
  return suffixes;
}
