export function bible_glyph_chapter_psa145() {
  "Psalm 145, drawn in pictures, so that a person who cannot read the letters can still follow it. David blesses God every day, one generation hands the account on to the next, and the psalm turns to what God is actually like, gracious and slow to anger and near to everyone who calls. It ends with every living thing blessing His holy name. Twenty one lines.";
  "THE LAST LINE LOSES BOTH NAME PICTURES, AND IT IS THE LINE THE WHOLE PSALM IS WALKING TOWARD. My mouth will declare the praise of the LORD, and let every creature bless His holy name forever and ever. One artwork here stands for the LORD and also for the Hebrew word meaning a name, so a line holding both would draw the same thing for two different words. Both tags come off. That is now the third chapter running where this has landed on exactly the sentence the passage is built on.";
  "THE KINGDOM IS NAMED FOUR TIMES HERE AND HAS NO PICTURE, AND THE SAME ENGLISH WORD WAS DRAWN IN ANOTHER CHAPTER. The eleventh, twelfth and thirteenth lines speak of the glory of Your kingdom and Your kingdom is an everlasting kingdom, and every one of them is plain letters. In 1 Chronicles 29 the word kingdom is drawn as a castle three times over. The reason is that Hebrew has more than one word for it, and the root table has an entry for the one that book uses and none for the one this psalm uses. So a reader following the pictures across the two chapters would think the second one had stopped talking about a kingdom.";
  "GREAT AND GREATNESS ARE SAID FOUR TIMES AND NEVER DRAWN EITHER. Great is the LORD and greatly to be praised, and His greatness is unsearchable, all in one line, then Your greatness again in the sixth. The psalm opens by saying God is too big to measure and there is no picture for the bigness.";
  "AND THE FOURTH LINE IS COMPLETELY BLANK. One generation will commend Your works to the next, and will proclaim Your mighty acts. It is the only line in the psalm with nothing on it, and it is the line about handing the whole thing on to somebody who has not heard it yet, which is what this Bible is for.";
  "THE ONE MARK FOR GOD BEING KIND IS DRAWN ONCE. The eighth line has abounding in loving devotion and that phrase carries a picture of a wrapped gift, seated on the Hebrew word for steadfast love. It is the only time it appears. The ninth line says the LORD is good and gets the thumb, and the seventeenth says He is righteous and gets the straight edge, and after that the kindness in the thirteenth and seventeenth lines is plain letters both times.";
  "Forty nine marks over twenty one lines. The first and the last tie for the fullest at five each, five lines carry one mark, and one carries none. Marks were kept in three places by putting the plainer English back. The fifth line meditates on the words of Your wondrous works, which is what the Hebrew says. The twelfth makes it known to the sons of men, so both the son and the human being are honest. And the nineteenth does the desire of those who fear Him rather than fulfilling it, because the Hebrew verb there is the ordinary one for doing and making.";
  "Two marks the draft offered were put away, and they were the two name tags in the last line.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA145",
    reference: "Psalm 145",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "Psalm",
          "of",
          "praise.",
          "Of",
          "David.",
          "I",
          "will",
          "exalt",
          "You,",
          "my",
          "$fire",
          "and",
          "$king,",
          "and",
          "I",
          "will",
          "$speech+thumbs_up",
          "Your",
          "$name_tag",
          "$hourglass",
          "and",
          "ever.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Every",
          "$sun",
          "I",
          "will",
          "$speech+thumbs_up",
          "You,",
          "and",
          "I",
          "will",
          "praise",
          "Your",
          "$name_tag",
          "$hourglass",
          "and",
          "ever.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Great",
          "is",
          "the",
          "$name_tag,",
          "and",
          "greatly",
          "to",
          "be",
          "praised,",
          "and",
          "His",
          "greatness",
          "is",
          "unsearchable.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "One",
          "generation",
          "will",
          "commend",
          "Your",
          "works",
          "to",
          "the",
          "next,",
          "and",
          "will",
          "proclaim",
          "Your",
          "mighty",
          "acts.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "They",
          "will",
          "speak",
          "of",
          "the",
          "$star",
          "splendor",
          "of",
          "Your",
          "majesty,",
          "and",
          "I",
          "will",
          "meditate",
          "on",
          "the",
          "$speech",
          "of",
          "Your",
          "wondrous",
          "works.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "They",
          "will",
          "$speech",
          "of",
          "the",
          "power",
          "of",
          "Your",
          "awesome",
          "deeds,",
          "and",
          "I",
          "will",
          "declare",
          "Your",
          "greatness.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "They",
          "will",
          "extol",
          "the",
          "fame",
          "of",
          "Your",
          "abundant",
          "goodness",
          "and",
          "sing",
          "joyfully",
          "of",
          "Your",
          "$ruler.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$name_tag",
          "is",
          "gracious",
          "and",
          "compassionate,",
          "slow",
          "to",
          "anger",
          "and",
          "abounding",
          "in",
          "$gift.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "$name_tag",
          "is",
          "$thumbs_up",
          "to",
          "all,",
          "and",
          "His",
          "compassion",
          "rests",
          "on",
          "all",
          "He",
          "has",
          "made.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "All",
          "You",
          "have",
          "made",
          "will",
          "$hands_raised",
          "You,",
          "O",
          "$name_tag,",
          "and",
          "Your",
          "saints",
          "will",
          "$speech+thumbs_up",
          "You.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "They",
          "will",
          "$speech",
          "of",
          "the",
          "$star",
          "of",
          "Your",
          "kingdom,",
          "and",
          "$mouth",
          "of",
          "Your",
          "might,",
        ],
      },
      {
        verse_number: 12,
        words: [
          "to",
          "$lightbulb",
          "to",
          "the",
          "$son",
          "of",
          "$person",
          "Your",
          "mighty",
          "acts",
          "and",
          "the",
          "$star",
          "splendor",
          "of",
          "Your",
          "kingdom.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Your",
          "kingdom",
          "is",
          "an",
          "$hourglass",
          "kingdom,",
          "and",
          "Your",
          "dominion",
          "endures",
          "through",
          "all",
          "generations.",
          "The",
          "LORD",
          "is",
          "faithful",
          "in",
          "all",
          "His",
          "words",
          "and",
          "kind",
          "in",
          "all",
          "His",
          "actions.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "$name_tag",
          "upholds",
          "all",
          "who",
          "fall,",
          "and",
          "lifts",
          "up",
          "all",
          "who",
          "are",
          "bowed",
          "down.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "The",
          "$eyes",
          "of",
          "all",
          "look",
          "to",
          "You,",
          "and",
          "You",
          "$hands_giving",
          "them",
          "their",
          "food",
          "in",
          "season.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "You",
          "open",
          "Your",
          "$hand",
          "and",
          "satisfy",
          "the",
          "desire",
          "of",
          "every",
          "$sprout",
          "thing.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "The",
          "$name_tag",
          "is",
          "$ruler",
          "in",
          "all",
          "His",
          "$road",
          "and",
          "kind",
          "in",
          "all",
          "His",
          "deeds.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "The",
          "$name_tag",
          "is",
          "near",
          "to",
          "all",
          "who",
          "call",
          "on",
          "Him,",
          "to",
          "all",
          "who",
          "call",
          "out",
          "to",
          "Him",
          "in",
          "$check.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "He",
          "will",
          "$hammer",
          "the",
          "desire",
          "of",
          "those",
          "who",
          "fear",
          "Him.",
          "He",
          "$ear",
          "their",
          "cry",
          "and",
          "saves",
          "them.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "The",
          "$name_tag",
          "preserves",
          "all",
          "who",
          "$heart_red",
          "Him,",
          "but",
          "all",
          "the",
          "$thumbs_down",
          "He",
          "will",
          "destroy.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "My",
          "$mouth",
          "will",
          "declare",
          "the",
          "praise",
          "of",
          "the",
          "LORD.",
          "Let",
          "every",
          "$meat",
          "$speech+thumbs_up",
          "His",
          "$sparkle",
          "name",
          "$hourglass",
          "and",
          "ever.",
        ],
      },
    ],
  };
  return chapter;
}
