export function bible_glyph_chapter_zec04() {
  "Zechariah 4, drawn in pictures, so that a person who cannot read the letters can still follow it. An angel wakes the prophet and shows him a golden lampstand with two olive trees standing beside it, and will not explain it until he has asked twice. Fourteen lines.";
  "THE CHAPTER IS NAMED FOR A LAMPSTAND, AND THE PICTURE OF A LAMPSTAND IN THIS COLLECTION MEANS THE JEWISH PEOPLE. There is a menorah among these pictures. It is not free. It is what this Bible draws for the Jews, and it is used that way in Esther 4 and across seven chapters of John. So in the one chapter that is genuinely about a menorah, the word menorah is said twice and drawn neither time, and it could not be drawn even if somebody wanted to, because putting it there would tell the reader Jews. This is a different kind of gap from all the others found so far. Nothing is missing. A picture was named after one thing and given to another, and the first thing can now never have it.";
  "THE VISION ITSELF IS INVISIBLE, AND TWO LINES GO COMPLETELY BARE BECAUSE OF IT. A lampstand, a bowl, seven lamps, seven spouts, two olive trees, two branches, two gold pipes and the oil running through them: that is the whole of what the prophet is shown, and not one of those words carries a mark. So the third line and the eleventh line, which are nothing but the description of the thing seen, arrive on the page with no pictures at all. What does survive is the talking about it, the asking and the not knowing and the answering. A reader with only the marks watches two people discuss something that is not there.";
  "THE ONE LINE EVERYBODY KNOWS COMES THROUGH INTACT, AND IT IS THE BEST DRAWN THING ON THE PAGE. Not by might, nor by power, but by My Spirit. The two refusals are drawn, power is drawn as lightning, and Spirit is drawn as wind, so the sentence arrives as two crossings-out and then a storm answered by a breath. Might is the only word in it with nothing, and losing that one costs least, because the picture beside it already carries the sense. This is the opposite of what usually happens: the famous line is normally the one the collision empties.";
  "THE MARK FOR A SON LANDS ON THE ANOINTED, AND THE OIL THEY ARE NAMED AFTER CANNOT BE DRAWN EITHER. The last line calls the two men sons of the oil, which is how Hebrew says anointed, so the family picture arrives on two grown officials for the same reason it arrived on a calf in Genesis 18 and an ostrich in Isaiah 43. And the oil in their title is a second Hebrew word again with no picture, even though an oil picture exists here as well. The twelfth line, where the English speaks of golden oil pouring through the pipes, is a translator adding the word to make the sentence work, because the Hebrew there says only the gold. So the picture could not have been used there in any case.";
  "TWO PICTURES SPEND THIS CHAPTER DOING SOMETHING OTHER THAN THEIR OWN JOB. The crown appears four times. Three of them are the prophet saying my lord to the angel, an ordinary polite address to somebody standing in front of him, and only the fourth is God. And in the twelfth line a hand is drawn where the English says beside, because the Hebrew word for a hand is also the word for the side of a thing. Neither is wrong and both are misleading, which is the shape this collection keeps running into: the picture is faithful to the word and the word was not being used in its picture sense.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "ZEC04",
    reference: "Zechariah 4",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "$angel",
          "who",
          "was",
          "$mouth",
          "with",
          "me",
          "$turn_back",
          "and",
          "woke",
          "me,",
          "as",
          "a",
          "$man_beard",
          "is",
          "awakened",
          "from",
          "his",
          "sleep.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "He",
          "$speech",
          "to",
          "me,",
          "What",
          "do",
          "you",
          "$eye?",
          "I",
          "$speech,",
          "I",
          "$eye",
          "a",
          "solid",
          "gold",
          "lampstand",
          "with",
          "a",
          "bowl",
          "at",
          "the",
          "top",
          "and",
          "seven",
          "lamps",
          "on",
          "it,",
          "with",
          "seven",
          "spouts",
          "to",
          "the",
          "lamps.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "There",
          "are",
          "also",
          "two",
          "olive",
          "trees",
          "beside",
          "it,",
          "one",
          "on",
          "the",
          "right",
          "of",
          "the",
          "bowl",
          "and",
          "the",
          "other",
          "on",
          "its",
          "left.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "asked",
          "the",
          "$angel",
          "who",
          "was",
          "$mouth",
          "with",
          "me,",
          "What",
          "are",
          "these,",
          "my",
          "$crown?",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$angel",
          "replied,",
          "Do",
          "you",
          "$no_entry",
          "$lightbulb",
          "what",
          "they",
          "are?",
          "I",
          "answered,",
          "$no_entry,",
          "my",
          "$crown.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "So",
          "he",
          "$speech",
          "to",
          "me,",
          "This",
          "is",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag",
          "to",
          "Zerubbabel:",
          "$no_entry",
          "by",
          "might,",
          "$no_entry",
          "by",
          "$lightning,",
          "but",
          "by",
          "My",
          "$wind,",
          "$speech",
          "the",
          "$name_tag",
          "of",
          "Hosts.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "What",
          "are",
          "you,",
          "O",
          "great",
          "$mountain?",
          "Before",
          "Zerubbabel",
          "you",
          "will",
          "become",
          "a",
          "plain.",
          "Then",
          "he",
          "will",
          "bring",
          "forth",
          "the",
          "capstone",
          "accompanied",
          "by",
          "shouts",
          "of",
          "Grace,",
          "grace",
          "to",
          "it.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Then",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag",
          "came",
          "to",
          "me,",
          "$speech,",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "$hand",
          "of",
          "Zerubbabel",
          "have",
          "laid",
          "the",
          "foundation",
          "of",
          "this",
          "$house,",
          "and",
          "his",
          "$hand",
          "will",
          "complete",
          "it.",
          "Then",
          "you",
          "will",
          "$lightbulb",
          "that",
          "the",
          "$name_tag",
          "of",
          "Hosts",
          "has",
          "sent",
          "me",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "For",
          "who",
          "has",
          "despised",
          "the",
          "$sun",
          "of",
          "small",
          "things?",
          "But",
          "these",
          "seven",
          "will",
          "rejoice",
          "when",
          "they",
          "$eye",
          "the",
          "plumb",
          "line",
          "in",
          "the",
          "$hand",
          "of",
          "Zerubbabel.",
          "They",
          "are",
          "the",
          "$eyes",
          "of",
          "the",
          "$name_tag,",
          "which",
          "scan",
          "the",
          "whole",
          "$earth.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Then",
          "I",
          "asked,",
          "What",
          "are",
          "the",
          "two",
          "olive",
          "trees",
          "on",
          "the",
          "right",
          "of",
          "the",
          "lampstand",
          "and",
          "on",
          "the",
          "left?",
        ],
      },
      {
        verse_number: 12,
        words: [
          "And",
          "I",
          "questioned",
          "him",
          "further,",
          "$speech,",
          "What",
          "are",
          "the",
          "two",
          "olive",
          "branches",
          "$hand",
          "the",
          "two",
          "gold",
          "pipes",
          "from",
          "which",
          "the",
          "golden",
          "oil",
          "pours?",
        ],
      },
      {
        verse_number: 13,
        words: [
          "He",
          "$speech,",
          "Do",
          "you",
          "$no_entry",
          "$lightbulb",
          "what",
          "these",
          "are?",
          "I",
          "$speech,",
          "$no_entry,",
          "my",
          "$crown.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "So",
          "he",
          "$speech,",
          "These",
          "are",
          "the",
          "two",
          "$son",
          "of",
          "the",
          "oil,",
          "the",
          "anointed",
          "ones,",
          "who",
          "stand",
          "beside",
          "the",
          "$crown",
          "of",
          "all",
          "the",
          "$earth.",
        ],
      },
    ],
  };
  return chapter;
}
