export function bible_glyph_chapter_psa118() {
  "The sixty first picture Bible chapter written by hand: the whole of the hundred and eighteenth psalm, the thanksgiving of a man who was surrounded and lived, in the shorthand a person types.";
  "IT IS THE PSALM THE CROWD SHOUTED WHEN JESUS RODE INTO JERUSALEM AND THE ONE PETER PREACHED FROM AFTERWARDS. Twenty nine verses, forty one in a hundred. The twenty sixth verse is the line about the one who comes in the name of the LORD, and the twenty second is the line about the stone the builders threw away. Both of those turn up again in the New Testament, and two chapters already on this list quote this one outright - the eleventh chapter of Mark takes the twenty sixth verse and the twelfth takes the twenty second. Entering it gives a reader somewhere to go back to when the marks he already knows turn up in a Gospel.";
  "THE SHORT NAME OF GOD IS ON THIS PAGE SIX TIMES AND NOT ONE OF THEM IS DRAWN. Hebrew has a long form of the divine name and a short one, and the root table seats the long form only. The long one falls twenty two times here and gets the mark every time. The short one falls in the fifth verse twice, in the fourteenth, the seventeenth, the eighteenth and the nineteenth, and every one of those comes through in plain letters. The fifth verse is the worst of it, because that is the hinge of the whole psalm - I called and He answered - and a reader following pictures sees no God in it at all, then watches the mark switch on again in the very next line. This is the same hole the hundred and fifteenth psalm showed, and here it is six holes instead of two.";
  "THE MOST FAMOUS VERSE ON THE PAGE HAS NO PICTURE IN IT ANYWHERE. The stone the builders rejected has become the cornerstone: stone, builders, rejected, become, cornerstone. Not one of those words is seated in the root table, so the verse arrives as a line of plain English in the middle of a page that is otherwise thick with marks. That is worth seeing rather than fixing. A picture reader gets no help at the one place he most needs it, and the blank tells the truth about how far this table currently reaches.";
  "THE PSALM SAYS IN THE NAME OF THE LORD FOUR TIMES AND FOUR TIMES THE NAME MARK HAD TO BE PUT BACK IN THE BOX BY HAND. The Hebrew word for a name and the divine name are seated on the same picture, so in the name of the LORD would come out as the same mark twice in a row, and a reader would have no way to see that those are two different words. It is stood down here in the tenth, eleventh, twelfth and twenty sixth verses. Seven other chapters written so far have needed the same stand-down, at fifteen places between them, and this page adds four more at once, which is the second most on any one page, behind the five in the second chapter of Genesis. Eight pages and nineteen hand-made exceptions is not a run of coincidences. The table wants that seat split in two.";
  "THE FIRST VERSE AND THE LAST VERSE ARE THE SAME AND THE MARKS SHOW IT FROM ARM'S LENGTH. Give thanks to the LORD, for He is good, His loving devotion endures forever - five pictures in the same order at both ends. A reader who cannot read a word of it can still see that the psalm comes back to where it started, and that is a real piece of the meaning delivered without any language at all.";
  "THE OPENING REFRAIN IS SAID FOUR TIMES BY THREE DIFFERENT GROUPS AND THE THIRD GROUP LETS EVERYONE IN. Israel, then the house of Aaron, then those who fear the LORD. The first two are a nation and a priesthood and a person is born into them or not; the third is a description of anybody. The hundred and fifteenth psalm widens in exactly the same three steps, and now both are on this list, so a reader can put them side by side and see the shape twice.";
  "DEATH AND LIFE STAND TOGETHER IN TWO VERSES AND EACH ONE HAS ITS OWN PICTURE. The skull falls twice, in the seventeenth verse and the eighteenth, and the sprout once between them. Both skulls are under the negation - I will not die, and He has not given me over to death - so the mark that means an ending appears only in sentences that refuse it. That is the whole argument of the middle of the psalm compressed into three pictures.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA118",
    reference: "Psalm 118",
    verses: [
      {
        verse_number: 1,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$name_tag,",
          "for",
          "He",
          "is",
          "$thumbs_up;",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Let",
          "Israel",
          "$speech:",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Let",
          "the",
          "$house",
          "of",
          "Aaron",
          "$speech:",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Let",
          "those",
          "who",
          "fear",
          "the",
          "$name_tag",
          "$speech:",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$tray_out",
          "my",
          "distress",
          "I",
          "called",
          "to",
          "the",
          "LORD;",
          "the",
          "LORD",
          "answered",
          "and",
          "set",
          "me",
          "free.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "$name_tag",
          "is",
          "on",
          "my",
          "side;",
          "I",
          "will",
          "$no_entry",
          "be",
          "afraid.",
          "What",
          "can",
          "$person",
          "$hammer",
          "to",
          "me?",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$name_tag",
          "is",
          "on",
          "my",
          "side;",
          "He",
          "is",
          "my",
          "helper.",
          "Therefore",
          "I",
          "will",
          "$eye",
          "in",
          "triumph",
          "on",
          "those",
          "who",
          "hate",
          "me.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "to",
          "take",
          "refuge",
          "in",
          "the",
          "$name_tag",
          "than",
          "to",
          "trust",
          "in",
          "$person.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "to",
          "take",
          "refuge",
          "in",
          "the",
          "$name_tag",
          "than",
          "to",
          "trust",
          "in",
          "princes.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "All",
          "the",
          "$map",
          "surrounded",
          "me,",
          "but",
          "in",
          "the",
          "name",
          "of",
          "the",
          "$name_tag",
          "I",
          "cut",
          "them",
          "off.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "They",
          "surrounded",
          "me,",
          "yes,",
          "they",
          "surrounded",
          "me",
          "on",
          "every",
          "side,",
          "but",
          "in",
          "the",
          "name",
          "of",
          "the",
          "$name_tag",
          "I",
          "cut",
          "them",
          "off.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "They",
          "swarmed",
          "around",
          "me",
          "like",
          "bees,",
          "but",
          "they",
          "were",
          "extinguished",
          "like",
          "burning",
          "thorns;",
          "in",
          "the",
          "name",
          "of",
          "the",
          "$name_tag",
          "I",
          "cut",
          "them",
          "off.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "I",
          "was",
          "pushed",
          "so",
          "hard",
          "I",
          "was",
          "falling,",
          "but",
          "the",
          "$name_tag",
          "helped",
          "me.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "LORD",
          "is",
          "my",
          "strength",
          "and",
          "my",
          "song,",
          "and",
          "He",
          "has",
          "become",
          "my",
          "salvation.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "$voice",
          "of",
          "joy",
          "and",
          "salvation",
          "resound",
          "in",
          "the",
          "tents",
          "of",
          "the",
          "$ruler:",
          "The",
          "right",
          "hand",
          "of",
          "the",
          "$name_tag",
          "$hammer",
          "with",
          "valor!",
        ],
      },
      {
        verse_number: 16,
        words: [
          "The",
          "right",
          "hand",
          "of",
          "the",
          "$name_tag",
          "is",
          "exalted!",
          "The",
          "right",
          "hand",
          "of",
          "the",
          "$name_tag",
          "$hammer",
          "with",
          "valor!",
        ],
      },
      {
        verse_number: 17,
        words: [
          "I",
          "will",
          "$no_entry",
          "$skull,",
          "but",
          "I",
          "will",
          "$sprout",
          "and",
          "proclaim",
          "what",
          "the",
          "LORD",
          "has",
          "done.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "The",
          "LORD",
          "disciplined",
          "me",
          "severely,",
          "but",
          "He",
          "has",
          "$no_entry",
          "$hands_giving",
          "me",
          "over",
          "to",
          "$skull.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Open",
          "to",
          "me",
          "the",
          "gates",
          "of",
          "$ruler,",
          "that",
          "I",
          "may",
          "$footprints",
          "and",
          "$hands_raised",
          "to",
          "the",
          "LORD.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "This",
          "is",
          "the",
          "gate",
          "of",
          "the",
          "$name_tag;",
          "the",
          "$ruler",
          "shall",
          "$footprints",
          "through",
          "it.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$hands_raised",
          "to",
          "You,",
          "for",
          "You",
          "have",
          "answered",
          "me,",
          "and",
          "You",
          "have",
          "become",
          "my",
          "salvation.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "The",
          "stone",
          "the",
          "builders",
          "rejected",
          "has",
          "become",
          "the",
          "cornerstone.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "This",
          "is",
          "from",
          "the",
          "$name_tag,",
          "and",
          "it",
          "is",
          "marvelous",
          "in",
          "our",
          "$eyes.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "This",
          "is",
          "the",
          "$sun",
          "the",
          "$name_tag",
          "$hammer;",
          "we",
          "will",
          "rejoice",
          "and",
          "be",
          "glad",
          "in",
          "it.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "O",
          "$name_tag,",
          "save",
          "us,",
          "we",
          "pray.",
          "O",
          "$name_tag,",
          "cause",
          "us",
          "to",
          "prosper,",
          "we",
          "pray.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "$speech+thumbs_up",
          "is",
          "he",
          "who",
          "$footprints",
          "in",
          "the",
          "name",
          "of",
          "the",
          "$name_tag.",
          "From",
          "the",
          "$house",
          "of",
          "the",
          "$name_tag",
          "we",
          "$speech+thumbs_up",
          "you.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "The",
          "$name_tag",
          "is",
          "$fire;",
          "He",
          "has",
          "made",
          "His",
          "light",
          "to",
          "shine",
          "upon",
          "us.",
          "Bind",
          "the",
          "festal",
          "sacrifice",
          "with",
          "cords",
          "to",
          "the",
          "horns",
          "of",
          "the",
          "altar.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "You",
          "are",
          "my",
          "$fire,",
          "and",
          "$hands_raised",
          "to",
          "You.",
          "You",
          "are",
          "my",
          "$fire;",
          "I",
          "will",
          "exalt",
          "You.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$name_tag,",
          "for",
          "He",
          "is",
          "$thumbs_up;",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
    ],
  };
  return chapter;
}
