export function bible_audio_brief() {
  "The whole brief for the recorded reading - whether one voice or a cast, what a voice is allowed to add, what can generate the audio, what the free engines are worth against the paid ones, and which licence governs the sound that comes out.";
  "★ A CAST IS PERMITTED, AND THE REASON IS THAT THE AUDIO RULE BINDS THE WORDS AND NEVER THE VOICE. Every word heard aloud must be Scripture, the passage read or a marked gloss. Who says it, in what timbre, at what pace, is manner - the same category as look, sound, movement and pace, which the interpolation brief already settles as free. So a distinct voice for Herod is not an addition to the text any more than a distinct face for him is.";
  "★ AN EARLIER DRAFT HERE SAID A VOICE MAY NEVER SAY WHAT ANYONE FELT, AND THAT WAS TOO STRONG. It read the depiction brief's magnification bound - a limp and a scar the passage never gave are invention - straight across into sound, and sound does not take it. A face can be drawn without a scar. A sentence cannot be said without a tone, so there is no neutral reading to fall back to, and a rule requiring one forbids every reading there is.";
  "★ 1COR4:4 IS WHY WAITING FOR CERTAINTY IS THE WRONG STANDARD, AND THE PROOF IS THAT PAUL WROTE IT INSIDE SCRIPTURE. He knew nothing against himself, yet was not thereby justified; he that judgeth him is the Lord. So a man proclaiming the word of God, in the act of writing the word of God, said outright that he could not certify his own blamelessness - and proclaimed anyway. Nobody gets to demand of a reading a certainty the apostle did not claim for himself.";
  "★ AND A MONOTONE IS NOT THE SAFE OPTION, IT IS A DIFFERENT ERROR WITH A COST. Flatness is a choice too, and it misreports - it says of a lament and a rebuke and a promise that they are the same kind of thing, which is false. The purpose is that the hearer is helped, so a reading that helps less to buy a safety that was never available has paid for nothing. Where the text says he marvelled, marvel.";
  "★ SO THE RULE IS DIRECTIONAL AND NOT A THRESHOLD: READ TOWARD WHAT THE PASSAGE MEANS, EXPECT TO BE WRONG SOMEWHERE, AND STAY CORRECTABLE. What is still forbidden is narrow - performing a motive the passage denies, or one it pointedly withholds, AS THOUGH THE TEXT SUPPLIED IT. That is a claim. An honest attempt at the sense is not a claim, it is the only way to read at all.";
  "★ THAT RULE ONLY WORKS BECAUSE THE PIPELINE IS RE-RUNNABLE, WHICH IS WHERE THIS JOINS THE COST FINDING BELOW. Correctable is a promise nobody can keep if fixing one line means booking a studio. Generated audio can be regenerated the day somebody says that verse was read wrong, so cheap regeneration is not a convenience here - it is the mechanism that makes proceeding without certainty responsible rather than careless.";
  "★ NARRATION AND DIRECT SPEECH SHOULD BE RECORDED AS SEPARATE TAKES FROM THE FIRST DAY, WHICH IS THE ONE DECISION THAT CANNOT BE DEFERRED. One voice or a cast then stops being a decision at all: record the two streams apart, ship one voice reading both, and a cast can be added later by replacing only the speech spans. Record them as one continuous file and casting means re-recording everything, so the cheap ordering is the one that keeps the expensive option open.";
  "★ WHAT A CAST ACTUALLY COSTS IS NOT THE VOICES, IT IS KNOWING WHERE THE SPEECH IS, AND THIS REPO DOES NOT KNOW. Nothing here records who says what: no speaker annotation, no red-letter marking, no quotation spans. That corpus would have to be built, and it is the real price of the idea. A single voice needs none of it, which is why a single voice ships first and a cast is a later rung rather than a competing plan.";
  "★ GENERATED SPEECH REVERSES THE COST STRUCTURE THE PRODUCTION BRIEF ASSUMED, AND THAT CORRECTION IS THE MOST USEFUL THING HERE. That brief calls the audio the most expensive thing a machine cannot decide. For a person reading, true - the whole Bible is on the order of seventy-five hours of studio time and every correction costs a session. For synthesis it is false: the text is roughly four and a quarter million characters, and commodity neural voices are priced around fifteen dollars a million, so the entire Bible is tens of dollars and can be regenerated after a fix.";
  "★ SO THE ASSET IS THE PIPELINE AND NOT THE RECORDING, WHICH CHANGES WHAT IS WORTH BEING CAREFUL ABOUT. If the audio is cheap and repeatable, the thing that carries between rungs is the code that turns a verse into a file, the choice of voice, and the corrections list - not the files themselves. Getting the pipeline right is worth days; getting one take right is worth minutes, because it can be run again.";
  "★ THE INVARIANT IS THAT VERSE BOUNDARIES ARE KNOWN, NOT THAT THEY ARE FILE BOUNDARIES, AND AN EARLIER DRAFT HERE CONFLATED THE TWO. One file per verse gives verse timing for free, which is what an audio Bible showing the words needs - but it also forces every verse to be read as though it were a sentence, and a human reader cannot work that way at all. So what must be recorded is a list of verse start times beside the audio. Generated and human readings then have identical shape, and one can replace the other.";
  "★ THIS REPO CURRENTLY DESTROYS THOSE BOUNDARIES BEFORE GENERATION, WHICH IS THE ONE REAL DEFECT IN AN OTHERWISE WORKING PIPELINE. The chapter's verses are joined with spaces into a single string and handed over, and the engine then splits on its own sentence boundaries, so the numbered files that come out are chunks and not verses. The graphemes for each chunk are written beside it, so the boundaries are recoverable by matching text - but recovering them later is work that recording them now would not cost.";
  "Word-level highlighting is a further step and needs forced alignment or an engine that hands back timestamps. It should be treated as a later feature rather than a property of the recording, because a verse-timed recording is already enough for the text-on-screen product.";
  "★ THE ENGINE'S LICENCE GOVERNS THE GENERATED AUDIO, AND THE BEREAN'S LICENCE DOES NOT REACH IT. A freely licensed text read by a restrictively licensed voice produces a restricted file - some engines forbid commercial use, some forbid redistribution of output, and voice-cloning models are the worst offenders. So the engine has to be chosen for its output terms first and its quality second, and the terms belong in the sources note with the rest of them.";
  "★ THIS IS ALREADY BUILT AND ALREADY RUN, WHICH CONTRADICTS A CLAIM MADE ELSEWHERE IN THESE BRIEFS. The production brief says the recorded voice is the one thing that does not exist. It does exist: Kokoro is wired in through a python script, a chapter and a book have named functions, and thousands of generated files are on this disk across three versions - the World English Bible twice at two speeds, and Leviticus complete in the Berean, joined into a book-length video. So the rung below pictures is not unstarted, it is partly built and undocumented, and that is a worse state to be in than unstarted because the next person plans around a blank that is not blank.";
  "★ REPLACING GENERATED READINGS WITH HUMAN ONES IS CHEAP TO PLAN AND EXPENSIVE TO RETROFIT, AND THE WHOLE PLAN IS THREE RULES. Key every recording by passage rather than by chunk number, so a file has an address a human recording can claim. Keep the verse start times beside the audio rather than baked into a joined track, so a swap changes a number and not a build. And note beside each recording where it came from - which engine at which version, or which reader on which date - so it is answerable which parts are still machine-read. None of that costs anything today. All of it is unaffordable once thousands of files exist without it, which is roughly now.";
  "The one thing that does not follow a per-verse rule is where a listener notices the seam. A chapter half machine-read and half human sounds broken, so replacement should happen at whatever a listener hears without a break - a whole cutscene, a whole chapter, a whole book - even though the addressing underneath is finer than that.";
  "★ THE FREE ENGINES ARE GOOD ENOUGH THAT PAYING IS A PREFERENCE RATHER THAN A NECESSITY, WHICH WAS NOT TRUE TWO YEARS AGO. The permissively licensed ones worth trying are Kokoro, which is the best quality for its size, is Apache licensed and is the one already installed here, Piper, which is fast on a plain processor and audibly synthetic, and Chatterbox under MIT. StyleTTS2 and F5-TTS are research-grade and their licences vary by checkpoint rather than by project, so each one has to be read separately. XTTS clones voices well and is the licence hazard - its terms lean non-commercial, so it should not be reached for casually.";
  "★ KOKORO'S VOICE COUNT IS EXACTLY WHERE THE WORRY SAID IT WOULD BE: AMPLE FOR A NARRATOR, THIN FOR A CAST. Its released pack holds twenty-seven English voices - eleven American women, eight American men, four British women, four British men - and the one this repo already uses is am_adam. For one reader that is more choice than anybody needs. For a cast it is short of the Gospels alone once narrator, Jesus, several disciples, Pharisees, Herod and a crowd all want distinguishing, and the voices within an accent and sex are not strongly distinct from each other, so the usable number is smaller than the count. Blending voice vectors makes more, of unpredictable quality.";
  "So the cast question probably resolves to a different engine rather than to more Kokoro. Cloud vendors offer hundreds of English neural voices at a price that is negligible for the amount of direct speech in the Bible, which is a small fraction of the text. That is a second reason a cast is a later rung: it is not the same pipeline, and committing to it now would be committing on the strength of a voice count nobody had checked.";
  "The paid ones sort the same way. ElevenLabs is the best sounding and the most expensive at this scale. The cloud vendors' neural voices - Azure, Google, Amazon - are cheap, dull and completely reliable, which for a narrator is closer to what the bound above wants than an expressive voice is. So the paid case is strongest for a cast, where character is the point, and weakest for narration, where character is the thing being avoided.";
  "★ A HUMAN VOLUNTEER IS A REAL OPTION HERE IN A WAY IT WOULD NOT BE ON ANOTHER PROJECT. Seventy-five hours read by somebody who wants it read is free, better than any synthesis, and slow. It is not exclusive with the rest: generate the whole thing now so the product exists, and replace books with human readings as they arrive. That is the same ordering as the separate takes - ship the cheap version in a shape that lets the good version land later.";
  "The recommendation, stated plainly so it can be disagreed with: one voice, generated, one file per verse, narration and speech recorded apart, on an engine whose output terms permit commercial redistribution. Everything else on this page is a later rung.";
  let brief = {
    step: "audio",
    what: "who reads, how the reading is produced, and what the produced sound is licensed for",
    passages: ["1COR4:4"],
    settled:
      "a cast is permitted because the audio rule binds words and not voices; the reading is read toward the passage's sense and expected to be wrong somewhere, because 1COR4:4 has Paul proclaiming without certifying himself, and a monotone is a different error rather than the safe option; what is still forbidden is performing a motive the passage denies or withholds as though the text supplied it; verse boundaries must be known and stored beside the audio, which is not the same as one file per verse; narration and direct speech are recorded apart so a cast can be added without re-recording; generated speech puts the whole Bible in tens of dollars rather than hundreds of hours, so the pipeline is the asset and every recording is regenerable, which is what makes proceeding without certainty correctable rather than careless; Kokoro is already installed here and thousands of files are already generated; its twenty-seven English voices are ample for a narrator and thin for a cast; the engine's licence governs the generated audio independently of the text's",
    open: "which engine for a cast, once its output terms are read; whether a human volunteer reading is sought now or later; how the speaker annotation corpus would be built if a cast is wanted; whether word-level highlighting is wanted enough to pay for forced alignment; whether the existing generated chapters are kept or regenerated once boundaries are recorded",
    forbidden:
      "performing a motive the passage denies or withholds as though it were given; demanding a certainty before reading that Paul did not claim before writing; generating audio that does not record where its verses begin; baking verse times into a joined track, which makes a human recording unswappable; shipping audio whose engine terms forbid the use it is shipped for; treating a generated recording as an asset too costly to redo",
    done: "every verse of the Berean has audio with its start time recorded and its source named, the whole of it can be regenerated from the text by one command, and nothing heard in it is outside the passage",
  };
  return brief;
}
