export function bible_glyph_chapter_psa138() {
  "The tenth picture Bible chapter written by hand: the whole of the hundred and thirty eighth psalm, in the shorthand a person types.";
  "IT HOLDS BOTH OF THE TWO WORDS THE TABLE REFUSED TO MERGE, and that is the thing to notice about it. When the raised hands were bought for the eighth chapter, a note was written beside them saying that yadah, to throw out the hand and give thanks, and yada, to know, are one letter apart in Hebrew and are not related - and that anyone merging them would silently redraw every act of praise in the psalter as an act of knowing. Nothing tested that. This psalm gives thanks three times in its first four verses and says in its sixth that the proud He knows from afar, so the raised hands and the lightbulb stand eight lines apart in one chapter. The refusal was written as an argument and is now a page a reader can look at.";
  "THE RAISED HANDS WERE BOUGHT FOR ANOTHER PSALM AND THIS ONE IS BUILT ON THEM. They were the single picture the eighth chapter paid for, where they open the psalm three times and close it once. Here they are the psalm's whole subject: the first verse, the second, and the fourth, where every king of the earth is finally doing it too. Two chapters running have now leaned hardest on the thing the chapter before them bought, which is the argument for a shared table arriving twice as a measurement.";
  "AND THE LAST VERSE QUOTES THE EIGHTH CHAPTER'S REFRAIN. The gift and the hourglass, in that order, are the four words the hundred and thirty sixth psalm ends all twenty six of its verses with; they arrive here once, in the last verse, saying the same thing. A reader who was drilled by that psalm meets the pair again as something they already know, in a chapter that never explains it. That is what the drilling was for, and it is the first time in this Bible that the pay-off can be pointed at.";
  "THE HAND IS DRAWN AND THE RIGHT HAND IS NOT, in the seventh verse, and this is the third chapter in a row to have a verse like it. The eighth chapter had the sun beside the day and drew only the day; the ninth had the flames of fire beside a picture of fire meaning God and drew neither; here English says hand twice and only the first is yad. It is no longer a curiosity worth one note per chapter - it is what this Bible is, said three ways: the marks sit on the Hebrew words and never on the English ones, and the places where that shows are the places a reader learns it.";
  "THE GODS OF THE FIRST VERSE ARE THE SAME PICTURE AS THE GOD OF GODS. Elohim is drawn as fire wherever it stands, so the psalmist singing before the gods gets the mark the eighth chapter put on the God of gods and the ninth put on the God of glory. A reader is not told that the Hebrew uses one word in all three places; they are shown it, three chapters apart, and no translation on the shelf makes it visible at all.";
  "THE PRESERVING IN THE SEVENTH VERSE IS DRAWN AS A SPROUT. The Hebrew is chayah, to live and to keep alive, and the table seats it on the shoot coming up. Walking in the midst of trouble and being kept alive is not a picture of a plant, and a reader could take it for one. It is left as the table has it, because the author does not get to pick a different picture for one passage - a word drawn one way here and another way in the next chapter breaks the only promise a reader learning these pictures has.";
  "THE PROPER NAME IS LEFT IN ENGLISH - David, in the heading. That is the same rule every chapter here keeps and never a gap to fill later. A name points at one person, and a picture of it would be a portrait.";
  "AND THE PSALTER IS NOW THREE OF THE TEN, which is worth naming rather than drifting into. The survey is not fond of psalms; it ranks by what the table can draw, and the table was built out of covenant words - the name, the gift, the glory, the fire - which is what a psalm is made of. So the psalter will keep coming top until the table grows the vocabulary of narrative and law. That is a fact about what has been built so far, not a preference, and the way to change it is to seat the words the other books are made of.";
  let chapter = {
    chapter_code: "PSA138",
    reference: "Psalm 138",
    verses: [
      {
        verse_number: 1,
        words: [
          "$hands_raised",
          "with",
          "all",
          "my",
          "$heart_organ;",
          "before",
          "the",
          "$fire",
          "I",
          "sing",
          "Your",
          "praises.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "I",
          "bow",
          "down",
          "toward",
          "Your",
          "$sparkle",
          "temple",
          "and",
          "$hands_raised",
          "to",
          "Your",
          "$name_tag",
          "for",
          "Your",
          "$gift",
          "and",
          "Your",
          "$check;",
          "You",
          "have",
          "exalted",
          "Your",
          "$name_tag",
          "and",
          "Your",
          "word",
          "above",
          "all",
          "else.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "On",
          "the",
          "$sun",
          "I",
          "called,",
          "You",
          "answered",
          "me;",
          "You",
          "emboldened",
          "me",
          "and",
          "strengthened",
          "my",
          "$person_other.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "All",
          "the",
          "$king",
          "of",
          "the",
          "$earth",
          "will",
          "$hands_raised",
          "You,",
          "O",
          "$name_tag,",
          "when",
          "they",
          "$ear",
          "the",
          "words",
          "of",
          "Your",
          "mouth.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "They",
          "will",
          "sing",
          "of",
          "the",
          "$road",
          "of",
          "the",
          "$name_tag,",
          "for",
          "the",
          "$star",
          "of",
          "the",
          "$name_tag",
          "is",
          "great.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Though",
          "the",
          "$name_tag",
          "is",
          "on",
          "high,",
          "He",
          "$eye",
          "the",
          "lowly;",
          "but",
          "the",
          "proud",
          "He",
          "$lightbulb",
          "from",
          "afar.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "If",
          "I",
          "$walking",
          "in",
          "the",
          "midst",
          "of",
          "trouble,",
          "You",
          "$sprout",
          "me",
          "from",
          "the",
          "anger",
          "of",
          "my",
          "foes.",
          "You",
          "extend",
          "Your",
          "$hand,",
          "and",
          "Your",
          "right",
          "hand",
          "saves",
          "me.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$name_tag",
          "will",
          "fulfill",
          "His",
          "purpose",
          "for",
          "me.",
          "Your",
          "$gift,",
          "O",
          "$name_tag,",
          "endures",
          "$hourglass",
          "-",
          "do",
          "not",
          "abandon",
          "the",
          "works",
          "of",
          "Your",
          "$hand.",
        ],
      },
    ],
  };
  return chapter;
}
