import { fn_name } from "./fn_name.mjs";
export function bible_glyph_roots_greek_drafted() {
  ("The New Testament words seated in bulk by the AI rather than one at a time in the hand-written table, one row each: the Strong's number, the root family it is filed under, its picture and a short gloss. The hand-written table merges these in, so every reader sees one table. The rules for choosing are written once, beside the Old Testament rows in ",
    fn_name("bible_glyph_roots_hebrew_drafted"),
    ".");
  ("A GREEK NAME OF HEBREW ORIGIN WEARS ITS HEBREW NAME'S PICTURE, copied rather than chosen again, and is filed under the same root word, so Isaiah, Samuel and Jonah are drawn alike in both testaments and a reader meets one picture for one person. Judas waits by the human's choice, and with him the patriarch Judah and Jude, since Greek gives all three one number.");
  let rows = [
    ["1636", "elaia", "olive", "olive"],
    ["3789", "ophis", "snake", "snake"],
    ["4071", "peteinon", "bird+all", "birds"],
    ["3088", "luchnos", "lamp", "lamp"],
    ["3087", "luchnos", "lamp+seat", "lampstand"],
    ["1404", "drakon", "snake+fire", "dragon"],
    ["173", "akantha", "thorns", "thorns"],
    ["1350", "diktuon", "net", "net"],
    ["4537", "salpizo", "trumpet+doing", "sound a trumpet"],
    ["1763", "eniautos", "year+one", "year"],
    ["1623", "hex", "six+describing", "sixth"],
    ["5151", "treis", "three+repeat", "three times"],
    ["4578", "seismos", "earth+collision", "earthquake"],
    ["3358", "metron", "triangular_ruler", "measure"],
    ["2806", "klao", "bread+collision", "break"],
    ["2813", "klepto", "hand+lying_face", "steal"],
    ["5180", "tupto", "fist+doing", "beat"],
    ["1194", "dero", "fist+repeat", "beat"],
    ["4084", "piazo", "hand+clamp", "seize"],
    ["726", "harpazo", "hand+fast_forward", "snatch"],
    ["5035", "tachu", "fast_forward+manner", "quickly"],
    ["4404", "proi", "morning", "early, morning"],
    ["3798", "opsios", "sunset", "evening"],
    ["2586", "kapnos", "fire+cloud", "smoke"],
    ["1027", "bronte", "cloud+loudspeaker", "thunder"],
    ["1119", "gonu", "kneeling+thing", "knee"],
    ["4454", "polos", "donkey+child", "colt"],
    ["5357", "phiale", "cup+hollow_circle", "bowl"],
    ["1089", "geuomai", "tongue+doing", "taste"],
    ["1131", "gumnos", "garment+no_entry", "naked"],
    ["5560", "cholos", "foot+bandage", "lame"],
    ["2974", "kophos", "ear+locked", "deaf, mute"],
    ["3474", "moros", "brain+no_entry", "foolish"],
    ["5429", "phronimos", "brain+describing", "wise"],
    ["3115", "makrothumia", "timer_clock+heart_red", "patience"],
    ["994", "boao", "loudspeaker+mouth", "cry out"],
    ["4697", "splanchnizomai", "heart_red+pleading", "have compassion"],
    ["2165", "euphraino", "beaming+doing", "rejoice"],
    ["928", "basanizo", "weary_face+doing", "torment"],
    ["2853", "kollao", "link+doing", "join"],
    ["3307", "merizo", "scissors+doing", "divide"],
    ["5563", "chorizo", "scissors+away", "separate"],
    ["4464", "rhabdos", "white_cane+thing", "staff"],
    ["2563", "kalamos", "sprout+white_cane", "reed"],
    ["5553", "chrusion", "coin+crown", "gold"],
    ["3042", "limos", "eating+hollow_circle", "famine"],
    ["3507", "nephele", "cloud", "cloud"],
    ["1186", "dendron", "tree", "tree"],
    ["3586", "xulon", "tree+thing", "wood, tree"],
    ["2486", "ichthus", "fish", "fish"],
    ["2462", "hippos", "horse", "horse"],
    ["3376", "men", "new_moon", "month"],
    ["4582", "selene", "moon", "moon"],
    ["2808", "kleio", "locked+doing", "shut"],
    ["3129", "manthano", "learner+doing", "learn"],
    ["3403", "mimnesko", "reminder_ribbon+doing", "remember"],
    ["3421", "mimnesko", "reminder_ribbon+doing", "remember"],
    ["3563", "nous", "brain", "mind"],
    ["2749", "keimai", "bed+doing", "lie"],
    ["769", "astheneo", "thermometer_face+thing", "weakness"],
    ["772", "astheneo", "thermometer_face+describing", "weak"],
    ["2836", "koilia", "baby+house", "womb, belly"],
    ["2226", "zoe", "sprout+thing", "living creature"],
    ["571", "pistis", "anchor+no_entry", "unbelieving"],
    ["5062", "tessares", "four+zero", "forty"],
    ["4453", "poleo", "coin+hands_giving", "sell"],
    ["4127", "plege", "fist+thing", "blow, plague"],
    ["50", "ginosko", "lightbulb+no_entry", "not know"],
    ["5143", "trecho", "running", "run"],
    ["4633", "skene", "tent", "tent"],
    ["694", "argurion", "coin", "money"],
    ["2923", "krino", "scales+doer", "judge"],
    ["4215", "potamos", "national_park", "river"],
    ["1033", "broma", "eating+thing", "food"],
    ["5259", "hupo", "down_arrow", "under, by"],
    ["5228", "huper", "up_arrow", "over, on behalf of"],
    ["3306", "meno", "pin+doing", "remain, abide"],
    ["3123", "mallon", "more", "more, rather"],
    ["615", "apokteino", "fist+skull", "kill"],
    ["3319", "mesos", "radio_button", "middle"],
    ["2334", "theoreo", "eye+doing", "look at, see"],
    ["1188", "dexios", "hand+right_arrow", "right hand"],
    ["1377", "dioko", "running+toward", "pursue"],
    ["4219", "pote", "question+clock", "when"],
    ["3842", "pantote", "all+clock", "always"],
    ["3694", "opiso", "back", "behind"],
    ["3340", "metanoeo", "brain+turn_back", "repent"],
    ["3341", "metanoeo", "brain+turn_back", "repentance"],
    ["2246", "helios", "sun_with_face", "sun"],
    ["2511", "katharos", "soap+doing", "cleanse"],
    ["2513", "katharos", "soap+describing", "clean"],
    ["2512", "katharos", "soap+thing", "cleansing"],
    ["169", "katharos", "soap+no_entry", "unclean"],
    ["417", "anemos", "wind+dashing_away", "wind"],
    ["59", "agorazo", "coin+hand_receiving", "buy"],
    ["5343", "pheugo", "dashing_away", "flee"],
    ["4624", "skandalon", "snare+doing", "cause to stumble"],
    ["4625", "skandalon", "snare", "trap, stumbling block"],
    ["5055", "telos", "end_arrow+doing", "finish, fulfil"],
    ["2479", "ischus", "might", "strength"],
    ["2480", "ischus", "might+doing", "be able"],
    ["2478", "ischus", "might+describing", "strong"],
    ["2364", "thugater", "girl", "daughter"],
    ["1060", "gamos", "ring+doing", "marry"],
    ["1062", "gamos", "ring+thing", "wedding"],
    ["2968", "kome", "houses", "village"],
    ["2917", "krino", "scales+thing", "judgment"],
    ["4613", "shama", "ear+proper_name", "Simon"],
    ["2501", "yoseph", "i_am+plus", "Joseph"],
    ["2268", "yasha", "rescue+i_am", "Isaiah"],
    ["2464", "tsachaq", "laughing+proper_name", "Isaac"],
    ["4672", "shalom", "peace+proper_name", "Solomon"],
    ["4540", "shamar", "guard+proper_name", "Samaria"],
    ["2197", "zakar", "reminder_ribbon+i_am", "Zechariah"],
    ["2448", "yadah", "hands_raised+proper_name", "Judah, the town"],
    ["2495", "yonah", "dove+proper_name", "Jonah"],
    ["76", "adam", "person+proper_name", "Adam"],
    ["3482", "nathan", "hands_giving+heart_on_fire", "Nathanael, given of God"],
    ["5328", "paroh", "house+proper_name", "Pharaoh"],
    ["3017", "levi", "handshake+proper_name", "Levi"],
    ["958", "ben", "son+right_arrow", "Benjamin"],
    ["4545", "shama", "ear+heart_on_fire", "Samuel"],
    ["4528", "shaal", "question+heart_on_fire", "Shealtiel"],
    ["2408", "rum", "up_arrow+i_am", "Jeremiah"],
    ["1662", "qum", "heart_on_fire+pointing_up", "Eliakim"],
    ["7", "ab", "father+i_am", "Abijah"],
    ["4524", "tsedeq", "ruler+proper_name", "Zadok"],
    ["2498", "mishpat", "i_am+scales", "Jehoshaphat"],
    ["1478", "chazaq", "might+i_am", "Hezekiah"],
    ["5617", "yasha", "rescue+proper_name", "Hosea"],
    ["4502", "raah", "eyes+son", "Reuben"],
    ["4488", "rapha", "bandage+i_am", "Rhesa, Rephaiah"],
    ["3518", "ner", "lamp+i_am", "Neri, Neriah"],
    ["2493", "yhwh", "i_am+heart_on_fire", "Joel"],
    ["2422", "pathach", "unlocked+proper_name", "Jephthah"],
    ["2242", "alah", "pointing_up+proper_name", "Heli, Eli"],
    ["1800", "ish", "man_beard+proper_name", "Enosh"],
    ["1697", "chamor", "donkey+proper_name", "Hamor"],
    ["1666", "elisha", "heart_on_fire+rescue", "Elisha"],
    ["5502", "kerub", "cherub", "cherubim"],
    ["4519", "tsaba", "military_helmet", "sabaoth, hosts"],
    ["2581", "qanna", "face_steam+describing", "Cananaean, zealot"],
  ];
  let drafted = [];
  for (let row of rows) {
    drafted.push({
      strong: row[0],
      root: row[1],
      glyph: row[2],
      gloss: row[3],
    });
  }
  return drafted;
}
