import { fn_name } from "./fn_name.mjs";
export function bible_glyph_chapter_1jn04() {
  "The first picture Bible chapter written by hand: first John four, seven to twelve, in the shorthand a person types.";
  "The passage was chosen because it is the densest love passage in the New Testament, so the one glyph the whole project started from - a red heart for agape - appears fourteen times in six verses. If a picture Bible is going to be readable anywhere it is here, and if it is unreadable here it is unreadable everywhere.";
  "GRAMMAR IS LEFT IN ENGLISH, and that is the honest state of the project rather than a decision that has been made. The ten most common words in the New Testament are a third of the page and every one of them is grammar - the, and, he, you, in - so a Bible that draws only content words is an ENGLISH Bible with pictures in it. That is genuinely useful and it is not the wordless Bible the project is aiming at. This chapter is what the first lane looks like, written out so it can be read rather than argued about.";
  ("What is stored is the SHORTHAND and what ships is the parsed form; ",
    fn_name("bible_glyph_chapter"),
    " is the one place the parsing happens, so no reader of this Bible ever writes a parser.");
  ("A verse is its words in order, one shorthand word per entry, and a word may hold English and glyphs together - Beloved is written as Be, the heart, and d, which draws as Be with a heart and a d. That is what lets the root stay visible through an English ending.");
  let chapter = {
    chapter_code: "1JN04",
    verses: [
      {
        verse_number: 7,
        words: [
          "Be$heart_redx$d,",
          "let",
          "us",
          "$heart_red",
          "one",
          "another,",
          "because",
          "$heart_red",
          "comes",
          "from",
          "$fire.",
          "Everyone",
          "who",
          "$heart_red$s",
          "has",
          "been",
          "born",
          "of",
          "$fire",
          "and",
          "$lightbulb$s",
          "$fire.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Whoever",
          "does",
          "not",
          "$heart_red",
          "does",
          "not",
          "$lightbulb",
          "$fire,",
          "because",
          "$fire",
          "is",
          "$heart_red.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "This",
          "is",
          "how",
          "$fire$’s",
          "$heart_red",
          "was",
          "revealed",
          "among",
          "us:",
          "$fire",
          "sent",
          "His",
          "one",
          "and",
          "only",
          "$son",
          "into",
          "the",
          "$globe,",
          "so",
          "that",
          "we",
          "might",
          "$sprout",
          "through",
          "Him.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "In",
          "this",
          "is",
          "$heart_red:",
          "not",
          "that",
          "we",
          "$heart_red$ed",
          "$fire,",
          "but",
          "that",
          "He",
          "$heart_red$ed",
          "us",
          "and",
          "sent",
          "His",
          "$son",
          "as",
          "the",
          "atoning",
          "sacrifice",
          "for",
          "our",
          "$bow$s.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Be$heart_red$d,",
          "if",
          "$fire",
          "so",
          "$heart_red$ed",
          "us,",
          "we",
          "also",
          "ought",
          "to",
          "$heart_red",
          "one",
          "another.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "No",
          "one",
          "has",
          "ever",
          "seen",
          "$fire.",
          "If",
          "we",
          "$heart_red",
          "one",
          "another,",
          "$fire",
          "remains",
          "in",
          "us,",
          "and",
          "His",
          "$heart_red",
          "is",
          "perfected",
          "in",
          "us.",
        ],
      },
    ],
  };
  return chapter;
}
