export function bible_glyph_chapter_psa146() {
  "The forty seventh picture Bible chapter written by hand: the whole of the hundred and forty sixth psalm, a list of the things God does for people nobody else is doing them for, in the shorthand a person types.";
  "IT IS THE THIRD OF THE THREE HIGHEST MEASURING CHAPTERS IN THE OLD TESTAMENT AND ALL THREE ARE NOW ON THIS LIST. Forty six in a hundred, behind the hundred and thirty fourth psalm at sixty and the sixty seventh at forty nine. Ten verses, which makes it the longest of the three and the one that carries the most. Taking the top three in order is a thing this list has not done before and probably will not do again; it happened because the survey of the Old Testament had never been run at all until the forty fourth entry, so three obvious chapters were sitting unclaimed at once.";
  "THE EIGHTH VERSE BEGINS WITH THE NAME THREE TIMES RUNNING AND THE MARKS MAKE THAT VISIBLE. The Name opens the blind, the Name lifts those bent double, the Name loves the righteous. Hebrew builds the middle of this psalm out of that repetition and English translations keep it, but a reader has to be paying attention to notice. Three identical pictures starting three clauses in a row cannot be missed, and this is the second page on this list where the drawing shows the shape of the poem better than the letters do.";
  "THE NAME FALLS NINE TIMES IN TEN VERSES. Only the third and the fourth verses are without it, and those two are the ones about princes - do not trust a prince, his breath goes out, his plans die with him. The psalm withholds the Name for exactly as long as it is talking about the help that fails, and gives it back the moment it turns to the help that does not.";
  "THE WITNESS MARK STANDS FOR UPHOLDS HERE AND THAT IS NOT A MISTAKE. The Hebrew root behind it means to bear witness, and in another form it means to hold something up - to prop, to restore, to keep a thing standing. English needs two different words and Hebrew uses one, so the mark that a reader met standing for a witness stands here for what God does for the fatherless and the widow. The table seats a mark on a root, not on an English word, and this is the clearest case on the list of what that costs and what it buys.";
  "THE WIND IN THE FOURTH VERSE IS THE SAME MARK THAT STANDS FOR THE SPIRIT. One Hebrew word and one Greek word both cover breath, wind and spirit, and this Bible draws all of them with the wind. So the mark that stands for the Spirit of God on the Greek pages stands here for the last breath going out of a dying prince. Nothing in the mark distinguishes them because nothing in the language underneath does either, and a reader who learns that has learned something real about how the Bible talks.";
  "THE SOUL IS DRAWN AS A PERSON. The first verse is a man telling himself to praise the Name, and the word he uses for himself is the one English renders soul. The mark for it is the plain figure, neither a man nor a woman nor a child, because that is what the word means - a living self, the whole of someone. It is not a ghost inside a body and the picture does not draw one.";
  "THE MIDDLE OF THIS PSALM IS A LIST OF PEOPLE AND ALMOST NONE OF THEM ARE DRAWN. The oppressed, the hungry, the prisoners, the blind, those bent double, the foreigners, the fatherless, the widow - eight kinds of person, and the pictures reach the scales, the bread and the road but not one of the people. That is the honest shape of this table so far: it was seated on what God is and what God does before it was seated on who God does it for, and this page is where a reader can see the gap.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA146",
    reference: "Psalm 146",
    verses: [
      {
        verse_number: 1,
        words: [
          "Hallelujah!",
          "Praise",
          "the",
          "$name_tag,",
          "O",
          "my",
          "$person_other!",
        ],
      },
      {
        verse_number: 2,
        words: [
          "I",
          "will",
          "praise",
          "the",
          "$name_tag",
          "while",
          "I",
          "$sprout;",
          "I",
          "will",
          "sing",
          "praises",
          "to",
          "my",
          "$fire",
          "while",
          "I",
          "have",
          "my",
          "being.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Put",
          "$no_entry",
          "your",
          "trust",
          "in",
          "princes,",
          "in",
          "a",
          "$son",
          "of",
          "$person",
          "who",
          "cannot",
          "save.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "His",
          "$wind",
          "departs,",
          "he",
          "$turn_back",
          "to",
          "the",
          "ground;",
          "on",
          "that",
          "$sun",
          "his",
          "plans",
          "perish.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$gift+smile",
          "is",
          "he",
          "whose",
          "help",
          "is",
          "the",
          "$fire",
          "of",
          "Jacob,",
          "whose",
          "hope",
          "is",
          "in",
          "the",
          "$name_tag",
          "his",
          "$fire,",
        ],
      },
      {
        verse_number: 6,
        words: [
          "who",
          "$hammer",
          "$sky",
          "and",
          "$earth,",
          "the",
          "$sea,",
          "and",
          "everything",
          "in",
          "them,",
          "who",
          "remains",
          "$check",
          "$hourglass.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "$hammer",
          "$scales",
          "for",
          "the",
          "oppressed",
          "and",
          "$hands_giving",
          "$bread",
          "to",
          "the",
          "hungry.",
          "The",
          "$name_tag",
          "sets",
          "the",
          "prisoners",
          "free.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$name_tag",
          "opens",
          "the",
          "eyes",
          "of",
          "the",
          "blind.",
          "The",
          "$name_tag",
          "lifts",
          "those",
          "who",
          "are",
          "weighed",
          "down.",
          "The",
          "$name_tag",
          "$heart_red",
          "the",
          "$ruler.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "$name_tag",
          "protects",
          "the",
          "foreigners;",
          "the",
          "fatherless",
          "and",
          "the",
          "widow",
          "He",
          "$witness,",
          "but",
          "the",
          "$road",
          "of",
          "the",
          "$thumbs_down",
          "He",
          "frustrates.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "The",
          "$name_tag",
          "will",
          "$castle",
          "$hourglass,",
          "your",
          "$fire,",
          "O",
          "Zion,",
          "for",
          "all",
          "generations.",
          "Hallelujah!",
        ],
      },
    ],
  };
  return chapter;
}
