export function bible_speech_attribution_verbs() {
  "The verbs that, standing in the narration just before a quotation, say that what follows is somebody speaking - which is how a reading finds out who to put the quotation in the mouth of.";
  "★ THIS IS A LIST OF WORDS AND NOT A GRAMMAR, WHICH MAKES IT A MEASURING INSTRUMENT RATHER THAN A PARSER. It is here to answer one question - how often is a quotation attributed at all - and a rough answer to that decides whether casting is an afternoon or a year. A wrong answer about one verse costs nothing at this stage; a wrong answer about the proportion costs the whole plan.";
  "★ SAYS IS IN THE LIST FOR THE PROPHETS AND NOT FOR THE GOSPELS. This is what the LORD says is the formula that opens most prophetic speech, and without that one word every quotation in Isaiah, Jeremiah and Amos reads as unattributed, which would put the largest and easiest block of speech in the Bible on the wrong side of the count.";
  "★ SOME OF THESE ARE NOISY ON PURPOSE - BEGAN, ADDED, THOUGHT AND CONTINUED ALL HAVE ORDINARY NON-SPEAKING SENSES. They are kept because the measurement is of whether attribution is FINDABLE, and a list that admitted only unambiguous verbs would report a shortage that is an artefact of the list. The noise runs one way and should be remembered when reading the number: the count is an upper bound on attribution rather than an exact figure.";
  let verbs = [
    "said",
    "says",
    "saying",
    "say",
    "replied",
    "answered",
    "answering",
    "asked",
    "asking",
    "told",
    "spoke",
    "speaking",
    "declares",
    "declared",
    "cried",
    "crying",
    "called",
    "calling",
    "commanded",
    "ordered",
    "warned",
    "rebuked",
    "prayed",
    "sang",
    "shouted",
    "exclaimed",
    "responded",
    "wrote",
    "written",
    "taught",
    "proclaimed",
    "announced",
    "insisted",
    "added",
    "began",
    "continued",
    "testified",
    "confessed",
    "blessed",
    "greeted",
    "urged",
    "begged",
    "questioned",
    "protested",
    "whispered",
    "muttered",
    "grumbled",
    "complained",
    "boasted",
    "swore",
    "promised",
    "thought",
    "reasoned",
    "wondered",
    "instructed",
    "prophesied",
    "sent",
    "word",
    "vision",
  ];
  return verbs;
}
