export function bible_glyph_chapter_psa067() {
  "The forty sixth picture Bible chapter written by hand: the whole of the sixty seventh psalm, a harvest prayer that the whole earth would know the way of God, in the shorthand a person types.";
  "IT IS THE SECOND HIGHEST MEASURING CHAPTER IN THE OLD TESTAMENT AND IT FOLLOWS THE HIGHEST. Forty nine in a hundred, behind the hundred and thirty fourth psalm at sixty and ahead of everything else surveyed across nine hundred and eighteen chapters. Taking the top two in order is not a rule this list has followed before - the door of the Psalter was taken at forty three over both of them - but with the two highest sitting together and both of them short, there was no argument for splitting them up.";
  "THE THIRD AND THE FIFTH VERSES ARE THE SAME VERSE, MARK FOR MARK. Let the peoples praise You, O God; let all the peoples praise You. Nothing in it is different the second time, and the psalm is built so that the refrain falls on either side of its middle. A reader who cannot read the letters can still see that shape, because the marks make the repeat visible from across the page - which is the first thing on this list that a picture Bible does better than a printed one rather than merely as well.";
  "THE HANDS RAISED MARK IS ON FOUR PAGES NOW AND ALL FOUR ARE PSALMS. It stands nowhere in any Greek chapter written for this list, and nowhere in any of the other Hebrew ones either. That is not a decision anyone made about it; it is the word for the kind of praise that lifts its hands, and the psalms are where that word lives. A mark that clusters like this is telling a reader something true about the book it is standing in.";
  "GOD IS THE FIRE AND IT FALLS SIX TIMES IN SEVEN VERSES, TWICE IN ONE OF THEM. The sixth verse says God, our own God, has blessed us - the same word twice with a possessive between them, and the doubling is the point of the verse. English translations sometimes smooth one of them away. This page keeps both, because a mark costs nothing to repeat and the repetition is what the psalm is doing.";
  "THE PEOPLES ARE DRAWN AND THE NATIONS ARE NOT, AND THE FOURTH VERSE HAS BOTH. They are two different words underneath and only one of them is seated, so a reader sees a mark and a plain word standing for near enough the same thing in one sentence. That is the third page on this list to show it. The rule behind it has not changed: a mark stands for one root of the language underneath, never for one word of the English on top.";
  "SELAH IS LEFT IN LETTERS BECAUSE NOBODY KNOWS WHAT IT MEANS. It is probably a direction to the musicians - a pause, or a lift - and it has never been translated into English either. A picture for it would be a guess dressed up as a reading, and this Bible does not draw guesses. It stands twice here, at the end of the first verse and the end of the fourth.";
  "THE PSALM ASKS FOR ONE THING AND IT IS NOT A HARVEST. The harvest is already in by the sixth verse; what is asked for is that the way of God be known on earth, among all nations. The blessing at the start is asked so that the knowing can happen, and the blessing at the end is asked so that the ends of the earth will fear Him. A reader following the marks alone can see that arc, because the road and the lightbulb sit in the second verse and the earth closes the last one.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA067",
    reference: "Psalm 67",
    verses: [
      {
        verse_number: 1,
        words: [
          "May",
          "$fire",
          "be",
          "gracious",
          "to",
          "us",
          "and",
          "$speech+thumbs_up",
          "us,",
          "and",
          "cause",
          "His",
          "face",
          "to",
          "shine",
          "upon",
          "us.",
          "Selah",
        ],
      },
      {
        verse_number: 2,
        words: [
          "that",
          "Your",
          "$road",
          "may",
          "be",
          "$lightbulb",
          "on",
          "$earth,",
          "Your",
          "salvation",
          "among",
          "all",
          "$map.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Let",
          "the",
          "$family",
          "$hands_raised",
          "You,",
          "O",
          "$fire;",
          "let",
          "all",
          "the",
          "$family",
          "$hands_raised",
          "You.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Let",
          "the",
          "nations",
          "be",
          "glad",
          "and",
          "sing",
          "for",
          "joy,",
          "for",
          "You",
          "judge",
          "the",
          "$family",
          "justly",
          "and",
          "lead",
          "the",
          "nations",
          "upon",
          "$earth.",
          "Selah",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Let",
          "the",
          "$family",
          "$hands_raised",
          "You,",
          "O",
          "$fire;",
          "let",
          "all",
          "the",
          "$family",
          "$hands_raised",
          "You.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "$earth",
          "has",
          "$hands_giving",
          "its",
          "harvest;",
          "$fire,",
          "our",
          "own",
          "$fire,",
          "has",
          "$speech+thumbs_up",
          "us.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "May",
          "$fire",
          "$speech+thumbs_up",
          "us,",
          "and",
          "may",
          "all",
          "the",
          "ends",
          "of",
          "the",
          "$earth",
          "fear",
          "Him.",
        ],
      },
    ],
  };
  return chapter;
}
