export function bible_glyph_chapter_jon03() {
  "The third chapter of Jonah, drawn in pictures. The same command is given a second time, the prophet goes this time, and a whole city changes its mind in eight verses. Ten lines.";
  "THEIR EVIL AND GOD DISASTER ARE THE SAME HEBREW WORD, AND THE TENTH VERSE HAS BOTH OF THEM. The eighth verse says let each one turn from his evil ways. The tenth says God saw they had turned from their evil ways, and He relented from the disaster He had threatened. English needs evil for the first and disaster for the second, so the sentence reads as two different things being weighed against each other. In Hebrew it is one word twice in one line, and the picture shows it: what they turned away from and what God turned away from are the same mark. That is the argument of the whole book, sitting in a single verse.";
  "THE TURNING MARK FALLS FOUR TIMES IN THREE LINES. Let each one turn from his evil ways, in the eighth. God may turn and relent, He may turn from His fierce anger, in the ninth. They had turned from their evil ways, in the tenth. Nothing else on the page is repeated anywhere near that hard, and the four marks are not four different ideas - they are the same motion asked of a city, hoped for from God, and then reported as done. A reader with no Hebrew can count them and see where the chapter turns, because it turns on the word turn.";
  "THE COVENANT NAME STOPS AFTER THE THIRD VERSE AND ONLY THE GOD MARK EVER REACHES NINEVEH. The name mark falls exactly twice, in the first verse and the third, and both times it is about Jonah being spoken to and Jonah obeying. From the fifth verse on the page says God four times and never the name again: the Ninevites believed God, call out to God, God may relent, God saw. They are not given the covenant name, they are given the general word, and the picture keeps that difference visible without a footnote.";
  "THE THIRD VERSE SAYS NINEVEH WAS GREAT TO GOD, AND ENGLISH SAYS EXCEEDINGLY GREAT. The Hebrew idiom for enormous is to call a thing great to God, so the word God is actually sitting there in the description of the pagan city, and the mark is drawn where it stands. English flattens it into an adverb, which is fair translation and total loss: the reader never learns that the city God is about to spare is measured, in the sentence that introduces it, against God Himself.";
  "ONE GROUP MARK IS PUT AWAY IN THE SEVENTH VERSE. The word for eating is drawn in this Bible with a picture built out of a person and a sheep, and the seventh verse already draws a person and a flock in plain sight, in the line let no man or beast, herd or flock, taste anything. Putting the group beside its own two halves would read as three different things instead of one, so the group is stood down and eat stays in plain letters. That rule costs a mark here and it is worth it: a picture that can be misread as a list is worse than no picture.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "JON03",
    reference: "Jonah 3",
    verses: [
      {
        verse_number: 1,
        words: [
          "Then",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag",
          "came",
          "to",
          "Jonah",
          "a",
          "second",
          "time:",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Get",
          "up!",
          "$walking",
          "to",
          "the",
          "great",
          "$city",
          "of",
          "Nineveh",
          "and",
          "proclaim",
          "to",
          "it",
          "the",
          "message",
          "that",
          "I",
          "$mouth",
          "you.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "This",
          "time",
          "Jonah",
          "got",
          "up",
          "and",
          "$walking",
          "to",
          "Nineveh,",
          "in",
          "accordance",
          "with",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag.",
          "Now",
          "Nineveh",
          "was",
          "a",
          "great",
          "$city",
          "to",
          "$fire,",
          "requiring",
          "a",
          "three",
          "day",
          "journey.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "On",
          "the",
          "first",
          "$sun",
          "of",
          "his",
          "journey,",
          "Jonah",
          "set",
          "out",
          "into",
          "the",
          "$city",
          "and",
          "proclaimed,",
          "Forty",
          "more",
          "$sun",
          "and",
          "Nineveh",
          "will",
          "be",
          "overturned!",
        ],
      },
      {
        verse_number: 5,
        words: [
          "And",
          "the",
          "Ninevites",
          "$anchor",
          "$fire.",
          "They",
          "proclaimed",
          "a",
          "fast",
          "and",
          "dressed",
          "in",
          "sackcloth,",
          "from",
          "the",
          "greatest",
          "of",
          "them",
          "to",
          "the",
          "least.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "When",
          "$speech",
          "reached",
          "the",
          "$king",
          "of",
          "Nineveh,",
          "he",
          "got",
          "up",
          "from",
          "his",
          "throne,",
          "took",
          "off",
          "his",
          "royal",
          "robe,",
          "covered",
          "himself",
          "with",
          "sackcloth,",
          "and",
          "sat",
          "in",
          "ashes.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Then",
          "he",
          "issued",
          "a",
          "proclamation",
          "in",
          "Nineveh:",
          "By",
          "the",
          "decree",
          "of",
          "the",
          "$king",
          "and",
          "his",
          "nobles:",
          "Let",
          "$no_entry",
          "$person",
          "or",
          "beast,",
          "herd",
          "or",
          "$sheep,",
          "taste",
          "anything",
          "at",
          "all.",
          "They",
          "must",
          "$no_entry",
          "eat",
          "or",
          "drink.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Furthermore,",
          "let",
          "both",
          "$person",
          "and",
          "beast",
          "be",
          "covered",
          "with",
          "sackcloth,",
          "and",
          "have",
          "everyone",
          "call",
          "out",
          "to",
          "$fire",
          "earnestly.",
          "Let",
          "each",
          "$man_beard",
          "$turn_back",
          "$tray_out",
          "his",
          "$thumbs_down",
          "$road",
          "and",
          "from",
          "the",
          "violence",
          "in",
          "his",
          "hands.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Who",
          "$lightbulb?",
          "$fire",
          "may",
          "$turn_back",
          "and",
          "relent;",
          "He",
          "may",
          "$turn_back",
          "from",
          "His",
          "fierce",
          "anger,",
          "so",
          "that",
          "we",
          "will",
          "$no_entry",
          "perish.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "When",
          "$fire",
          "$eye",
          "their",
          "actions,",
          "that",
          "they",
          "had",
          "$turn_back",
          "from",
          "their",
          "$thumbs_down",
          "$road,",
          "He",
          "relented",
          "from",
          "the",
          "$thumbs_down",
          "He",
          "had",
          "$mouth",
          "to",
          "$hammer",
          "upon",
          "them.",
        ],
      },
    ],
  };
  return chapter;
}
