export function bible_glyph_chapter_psa063() {
  "Psalm 63, drawn in pictures, so that a person who cannot read the letters can still follow it. David wrote it in the wilderness of Judah, and it is the other thirst psalm, the one where there is no stream at all. Eleven lines.";
  "THE WATER PICTURE LANDS ON THE LINE THAT SAYS THERE IS NO WATER. The first line ends in a dry and weary land without water, and the collection is seated on the Hebrew word for water, so the water picture is drawn there. Nothing is drawn on the word without, because this page has a mark for a plain no and the Hebrew word used here is a different one it is not seated on. A reader with no letters therefore sees a land and some water at the end of the sentence about thirst. It is the first place found where the marks do not merely lose the meaning but reverse it, and it is worth putting beside Psalm 42, which drew its water on a stream that was really there.";
  "A REAL RIGHT HAND GOES UNDRAWN AND A POWER GETS THE HAND PICTURE, TWO LINES APART. The eighth line says Your right hand upholds me and carries no hand. The tenth line says they will fall to the power of the sword, and the Hebrew word behind power there is the general word for a hand, so a hand is drawn. This is the third chapter tonight doing exactly this, after Daniel 12, which had both halves inside one verse, and Song of Songs 2, which lost a left hand and a right arm in an embrace. Hebrew has one word for a hand in general and separate words for the right hand and the left, and this collection is seated on the first and not the others.";
  "THE MOUTH IS DRAWN ON THE LIARS AND NOT ON THE MOUTHS. The last line says the mouths of liars will be shut. The word mouths gets nothing. The word liars is a Hebrew phrase built on speaking, close enough to the seated root that the mouth picture fires there instead. So the sentence about shutting mouths shows one mouth, in the wrong half of it.";
  "TWO LINES IN THE MIDDLE GO COMPLETELY BARE AND ONE OF THEM IS THE WINGS. The sixth line, remembering God on a bed through the watches of the night, carries nothing. The seventh, in the shadow of Your wings I will sing for joy, carries nothing either. A bed has no picture, night has none, a shadow has none, wings have none and joy has none. They are the only two empty lines in the psalm and they sit next to each other, so the quietest part of the text is also the emptiest part of the page.";
  "THE BLESSING SURVIVES BY ONE LINE. The fourth line has the group mark for blessing God, which is a speech bubble with a thumbs up. The rule this collection follows is that such a mark stands down if the same line also draws one of its own halves on its own, and this line does not. The line immediately before it does: the third line draws a plain thumbs up on the word better. So the mark survives by a single line, and a reader going down the page meets a thumbs up and then a speech bubble with a thumbs up one line later, which is the closest that rule has come to failing.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA063",
    reference: "Psalm 63",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "Psalm",
          "of",
          "David,",
          "when",
          "he",
          "was",
          "in",
          "the",
          "Wilderness",
          "of",
          "Judah.",
          "O",
          "$fire,",
          "You",
          "are",
          "my",
          "$fire.",
          "Earnestly",
          "I",
          "seek",
          "You;",
          "my",
          "$person_other",
          "thirsts",
          "for",
          "You,",
          "my",
          "$meat",
          "yearns",
          "for",
          "You,",
          "in",
          "a",
          "dry",
          "and",
          "weary",
          "$earth",
          "without",
          "$water.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "So",
          "I",
          "have",
          "$eye",
          "You",
          "in",
          "the",
          "$sparkle",
          "place,",
          "beholding",
          "Your",
          "power",
          "and",
          "Your",
          "$star.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Because",
          "Your",
          "$gift",
          "is",
          "$thumbs_up",
          "than",
          "$sprout,",
          "my",
          "lips",
          "will",
          "glorify",
          "You.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "So",
          "I",
          "will",
          "$speech+thumbs_up",
          "You",
          "as",
          "long",
          "as",
          "I",
          "$sprout;",
          "in",
          "Your",
          "$name_tag",
          "I",
          "will",
          "lift",
          "my",
          "hands.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "My",
          "$person_other",
          "is",
          "satisfied",
          "as",
          "with",
          "the",
          "richest",
          "of",
          "foods;",
          "with",
          "joyful",
          "lips",
          "my",
          "mouth",
          "will",
          "praise",
          "You.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "When",
          "I",
          "remember",
          "You",
          "on",
          "my",
          "bed,",
          "I",
          "think",
          "of",
          "You",
          "through",
          "the",
          "watches",
          "of",
          "the",
          "night.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "For",
          "You",
          "are",
          "my",
          "help;",
          "in",
          "the",
          "shadow",
          "of",
          "Your",
          "wings",
          "I",
          "will",
          "sing",
          "for",
          "joy.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "My",
          "$person_other",
          "clings",
          "to",
          "You;",
          "Your",
          "right",
          "hand",
          "upholds",
          "me.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "But",
          "those",
          "who",
          "seek",
          "my",
          "$person_other",
          "to",
          "destroy",
          "it",
          "will",
          "$footprints",
          "into",
          "the",
          "depths",
          "of",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "They",
          "will",
          "fall",
          "to",
          "the",
          "$hand",
          "of",
          "the",
          "$sword;",
          "they",
          "will",
          "become",
          "a",
          "portion",
          "for",
          "foxes.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "But",
          "the",
          "$king",
          "will",
          "rejoice",
          "in",
          "$fire;",
          "all",
          "who",
          "swear",
          "by",
          "Him",
          "will",
          "exult,",
          "for",
          "the",
          "mouths",
          "of",
          "$mouth",
          "will",
          "be",
          "shut.",
        ],
      },
    ],
  };
  return chapter;
}
