export function bible_glyph_chapter_psa111() {
  "The hundred and eleventh psalm, drawn in pictures. It is the twin of the psalm that comes just before it on this list: ten verses about what God is like, built in the same shape as ten verses about what a man who fears Him is like, and the third verse of each says the same three words.";
  "THE THIRD VERSE HERE IS THE THIRD VERSE OF THE NEXT PAGE, WORD FOR WORD. His righteousness endures forever. In Hebrew that is three words - tsidqato, omedet, la'ad - and the hundred and twelfth psalm puts the identical three in the identical order, about a man. The measuring mark falls in both places, so a reader who cannot read a syllable of it can see the same picture in the same slot on two facing pages and know that one is quoting the other. That is the pair working exactly as it was meant to.";
  "THE TWO HEBREW WORDS FOR FOREVER STAND TOUCHING IN THE EIGHTH VERSE AND ONLY ONE OF THEM IS DRAWN. The line is upheld forever and ever, and forever is la'ad while and ever is olam. The root table seats olam on the hourglass and has never seated la'ad, so the eighth verse shows one plain word beside one picture where the Hebrew has two words of the same weight. It is the sharpest place on the list to see that gap, because nothing separates the two words at all. La'ad falls three times on this page, in the third verse, the eighth and the last, and every one of the three is a plain word. Olam falls three times too, in the fifth, the eighth and the ninth, and every one of those gets the hourglass. Same page, same meaning, one seated and one not.";
  "THE SHORT NAME OF GOD IS THE SECOND WORD AND IT IS NOT DRAWN. Hallelujah is two words in Hebrew, praise and Yah, and Yah is the short form of the name the name tag stands for. Two words later the long form arrives and gets the mark. So the first line of the psalm names God twice and a picture reader sees Him once. Four pages on this list now open or close on that same hole, and this one puts it in the first two words.";
  "ONE HEBREW VERB IS ON THE PAGE THREE TIMES AND ENGLISH USES A DIFFERENT WORD AT EVERY ONE. It is the ordinary verb for doing or making, and it carries the hammer. In the fourth verse it is He has caused His wonders to be remembered. In the eighth it is enacted in truth and uprightness. In the tenth it is all who follow His precepts. Caused, enacted, follow - three unrelated English words, one Hebrew word, and the hammer in all three places. A reader with no language at all sees that the making at the start and the doing at the end are the same act.";
  "THE NAME MARK HAD TO BE STOOD DOWN ONCE, IN THE NINTH VERSE. Holy and awesome is His name. The word is shem, the ordinary word for a name, and the root table seats it on the same picture as the covenant name, so drawn as it stands the line would read holy and awesome is the LORD - close, and not what is written. It is left in plain letters. This is the same exception that a growing number of Hebrew pages have needed, and it is the version of it where the subject really is God, which makes it the easiest one to miss.";
  "THE WORKS OF THE LORD ARE NAMED THREE TIMES AND NEVER DRAWN. The second verse, the sixth and the seventh all use one noun built on that same verb for doing, and none of the three carries a mark, while the verb beside them does. So the page shows the act and hides the thing made, which is backwards from what a picture Bible would choose if it were choosing. It is not choosing. The table seated the verb early because verbs are common, and the noun is still waiting.";
  "The pictures are the root table's, not this chapter's. Every mark here was already seated on a Hebrew root before this page was written, and a word that has no seat waits in plain letters until one is bought for it.";
  let chapter = {
    chapter_code: "PSA111",
    reference: "Psalm 111",
    verses: [
      {
        verse_number: 1,
        words: [
          "Hallelujah!",
          "I",
          "will",
          "$hands_raised",
          "to",
          "the",
          "$name_tag",
          "with",
          "all",
          "my",
          "$heart_organ",
          "in",
          "the",
          "council",
          "of",
          "the",
          "upright",
          "and",
          "in",
          "the",
          "assembly.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Great",
          "are",
          "the",
          "works",
          "of",
          "the",
          "$name_tag;",
          "they",
          "are",
          "pondered",
          "by",
          "all",
          "who",
          "delight",
          "in",
          "them.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Splendid",
          "and",
          "majestic",
          "is",
          "His",
          "work,",
          "and",
          "His",
          "$ruler",
          "endures",
          "forever.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "He",
          "has",
          "$hammer",
          "His",
          "wonders",
          "to",
          "be",
          "remembered;",
          "the",
          "$name_tag",
          "is",
          "gracious",
          "and",
          "compassionate.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "He",
          "$hands_giving",
          "food",
          "to",
          "those",
          "who",
          "fear",
          "Him;",
          "He",
          "remembers",
          "His",
          "covenant",
          "$hourglass.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "has",
          "shown",
          "His",
          "$family",
          "the",
          "$lightning",
          "of",
          "His",
          "works",
          "by",
          "$hands_giving",
          "them",
          "the",
          "inheritance",
          "of",
          "the",
          "$map.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "works",
          "of",
          "His",
          "$hand",
          "are",
          "$check",
          "and",
          "$scales;",
          "all",
          "His",
          "precepts",
          "are",
          "$anchor.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "They",
          "are",
          "upheld",
          "forever",
          "and",
          "$hourglass,",
          "$hammer",
          "in",
          "$check",
          "and",
          "uprightness.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "has",
          "sent",
          "redemption",
          "to",
          "His",
          "$family;",
          "He",
          "has",
          "ordained",
          "His",
          "covenant",
          "$hourglass.",
          "$sparkle",
          "and",
          "awesome",
          "is",
          "His",
          "name.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "The",
          "fear",
          "of",
          "the",
          "$name_tag",
          "is",
          "the",
          "beginning",
          "of",
          "wisdom;",
          "all",
          "who",
          "$hammer",
          "His",
          "precepts",
          "gain",
          "$thumbs_up",
          "understanding.",
          "His",
          "praise",
          "endures",
          "forever.",
        ],
      },
    ],
  };
  return chapter;
}
