import { fn_name } from "./fn_name.mjs";
import { text_from_code_number } from "./text_from_code_number.mjs";
export function bible_glyph_word_separator() {
  "The character standing between two words of this picture Bible that would otherwise run into one another - a word ending in a picture followed by a word starting with one - in plain text and on a page alike: one em space, as wide as the pictures either side of it.";
  ("IT IS NOT WRITTEN IN EVERY GAP, WHICH IS THE CORRECTION THIS PARAGRAPH EXISTS TO MAKE. It was, for as long as it existed, and that was the mistake: of the thirteen thousand gaps in the written chapters only seven hundred and thirty five have a picture on both sides, so the other twelve thousand were being marked by something that had nothing to mark. ", fn_name("bible_glyph_word_pair_separator"), " decides one gap at a time now and asks for this character only where a pair could be misread as one word. Nothing else may spell an em space into drawn text, and a gate walks the whole Bible to say so.");\n  "THE GAP IS THE ONLY PUNCTUATION THIS WRITING SYSTEM HAS. Several pictures standing together are ONE word, so a reader has to be able to tell two pictures of one word from two pictures that are two words, and what tells them is that the first pair touch and the second pair do not. There is no second device - no ring drawn round a group, no joining mark. The whole difference between a word and two words is carried by how wide one character is.";
  "A GAP COSTS NOTHING TO TEACH AND A DRAWN MARK COSTS A LESSON. Every symbol this Bible uses is paid for before the first verse, in a tutorial that has to teach it from nothing; the space between words is the one device every writing system on earth already taught its readers, so it arrives free. That is the whole argument for spacing over a ring drawn round the group, which is what this replaced.";
  "AND IT NESTS, WHICH A RING COULD NOT. A ring is drawn or it is not, so a group inside a group had no way to be written at all. Gaps have sizes, so a smaller gap inside a larger one inside a word gap says the same thing in three levels without a new mark. Nothing writes a nested group yet and this is not that feature - it is the reason the door is left open.";
  "AN EM SPACE IS THE SMALLEST HONEST FIX because it makes the gap the same size as the things it separates. Until now the character here was an ordinary space, about a quarter of an em standing between two pictures each a full em wide, and a reader was being asked to read a quarter-em gap as a separator and a nought-em gap as a join - a judgement about a fifth of a picture's width. Two pictures with a picture's width of nothing between them read as apart at a glance instead, and nobody has to measure anything.";
  "IT IS A CHARACTER AND NOT A LAYOUT RULE, which is the whole point of choosing this one and the reason it is the same answer for both drawers. The Bible is meant to be copied out and pasted into a message, and a width set in a style does not survive that journey while a character does. An ordinary run of spaces would not survive it either: two spaces are collapsed back into one by every browser and by most chat windows, so the widening would vanish exactly where it was needed most. The em space is not collapsed, because the rules that collapse white space name the ordinary space, the tab and the newline and stop there.";
  "IT DOES NOT RESCUE THE SAME PICTURE TWICE OVER, and that limit is worth stating beside the fix rather than discovering later. Every other pair changes shape at the boundary, so a wider gap is all a reader needs; the same picture on both sides changes nothing at the boundary, and a reader is still being asked to count. That case has to be kept out of the vocabulary rather than spaced apart, and it is why one group was taken back out of the tenth of John.";
  ("IT IS SPELLED AS ITS NUMBER AND NEVER AS THE CHARACTER ITSELF, for the reason ",
    fn_name("text_from_code_number"),
    " already gives: a character that prints as nothing looks in the source exactly like a mistyped empty word, and the ordinary space it must be told apart from is the very thing it resembles. Eight thousand one hundred and ninety five is U+2003, the em space.");
  let r = text_from_code_number(8195);
  return r;
}
