export function bible_glyph_chapter_pro03() {
  "The third chapter of Proverbs, drawn in pictures. A father tells his son to trust the LORD with all his heart, describes wisdom as a tree of life, and then gives five plain commands about how to treat a neighbour. Thirty five lines.";
  "FIVE COMMANDS IN A ROW ALL OPEN WITH THE SAME CROSSING OUT MARK. The twenty seventh through the thirty first verses are do not withhold, do not tell, do not devise, do not accuse, do not envy - and in pictures that is the same mark standing at the head of five lines, one under the other, in a chapter whose left edge is otherwise all different. The mark falls sixteen times in all, more than any other on the page, and the thirtieth verse takes two of them: do not accuse a man without cause, when he has done you no harm. English says do not each time as well, so this is one of the few places where the picture is not showing the reader something English hid. It is showing it harder.";
  "THE HEART MARK FALLS THREE TIMES AND ALL THREE ARE IN THE FIRST FIVE LINES. Let your heart keep my commandments, write them on the tablet of your heart, trust in the LORD with all your heart. Then it never appears again in the remaining thirty verses. That is the shape of the chapter and it is easy to miss when reading: everything is put into the heart at the start, and the rest of the page is what comes out of it - long life, healing, full barns, a safe road, a good sleep, and five ways to treat the man next door.";
  "THE SAME PROMISE IS MADE TWICE, IN THE SECOND VERSE AND THE SIXTEENTH. The second says they will add length to your days. The sixteenth says long life is in her right hand. English uses two different phrases, but the Hebrew is the same pair of words both times - length of days - so both take the day mark, and the sixteenth line is answering the second. The first time it is a father promising it to his son. The second time it is wisdom herself holding it out in her hand. The living mark is separate and falls three times, in the second verse, in the tree of life, and in the twenty second where sound judgment is called life to your soul.";
  "THE WAY MARK FALLS FIVE TIMES AND IT BELONGS TO THREE DIFFERENT PEOPLE. In the sixth it is your ways. In the seventeenth it is hers, twice over, all her ways are pleasant and all her paths are peaceful. In the twenty third it is your way again, now safe. In the thirty first it is his - a violent man - and the line says do not choose any of them. The chapter is a choice between roads, and the picture puts the same mark on all of them so the reader can see that it is one choice and not five separate pieces of advice.";
  "THE WORD FOR GOD IS USED IN THE TWENTY SEVENTH VERSE TO MEAN NOTHING MORE THAN ABILITY. Do not withhold good from the deserving when it is in your power to act - and the word there translated power is one of the Hebrew words for God, used the way we might say a strong hand. The mark on this page means God, not strength, so it is left off and that line is drawn without it. The fourth verse keeps the mark, because there the word really does mean God: you will find favour in the sight of God and man.";
  "THREE HEART PICTURES ON THIS PAGE, AND THREE DIFFERENT HEBREW WORDS BEHIND THEM. The plain heart in the first five verses is the seat of thinking and choosing. The twelfth verse has the loving heart - the LORD disciplines the one He loves. The thirty first has the burning heart - do not envy a violent man - because Hebrew names envy with a word about heat. They look alike on purpose, since all three are about what a person wants, but they are not the same word and a reader should not read them as one.";
  "THE GLORY MARK OPENS IN WISDOM HANDS AND CLOSES AS WHAT THE WISE ARE GIVEN. It falls twice. In the sixteenth verse riches and honour are in her left hand. In the thirty fifth, the last line of the chapter, the wise will inherit honour. Held out at the middle of the page, handed over at the end of it.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PRO03",
    reference: "Proverbs 3",
    verses: [
      {
        verse_number: 1,
        words: [
          "My",
          "$son,",
          "do",
          "$no_entry",
          "forget",
          "my",
          "$scroll,",
          "but",
          "let",
          "your",
          "$heart_organ",
          "keep",
          "my",
          "$scroll;",
        ],
      },
      {
        verse_number: 2,
        words: [
          "for",
          "they",
          "will",
          "add",
          "length",
          "to",
          "your",
          "$sun,",
          "years",
          "to",
          "your",
          "$sprout,",
          "and",
          "peace",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$no_entry",
          "let",
          "$gift",
          "or",
          "$check",
          "leave",
          "you;",
          "bind",
          "them",
          "around",
          "your",
          "neck,",
          "write",
          "them",
          "on",
          "the",
          "tablet",
          "of",
          "your",
          "$heart_organ.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Then",
          "you",
          "will",
          "find",
          "favor",
          "and",
          "high",
          "regard",
          "in",
          "the",
          "$eyes",
          "of",
          "$fire",
          "and",
          "$person.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Trust",
          "in",
          "the",
          "$name_tag",
          "with",
          "all",
          "your",
          "$heart_organ,",
          "and",
          "lean",
          "$no_entry",
          "on",
          "your",
          "own",
          "understanding;",
        ],
      },
      {
        verse_number: 6,
        words: [
          "in",
          "all",
          "your",
          "$road",
          "$lightbulb",
          "Him,",
          "and",
          "He",
          "will",
          "make",
          "your",
          "paths",
          "straight.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Be",
          "$no_entry",
          "wise",
          "in",
          "your",
          "own",
          "$eyes;",
          "fear",
          "the",
          "$name_tag",
          "and",
          "turn",
          "away",
          "from",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "This",
          "will",
          "bring",
          "healing",
          "to",
          "your",
          "body",
          "and",
          "refreshment",
          "to",
          "your",
          "bones.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Honor",
          "the",
          "$name_tag",
          "with",
          "your",
          "wealth",
          "and",
          "with",
          "the",
          "firstfruits",
          "of",
          "all",
          "your",
          "crops.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Then",
          "your",
          "barns",
          "will",
          "be",
          "filled",
          "with",
          "plenty,",
          "and",
          "your",
          "vats",
          "will",
          "overflow",
          "with",
          "new",
          "wine.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "My",
          "$son,",
          "do",
          "$no_entry",
          "reject",
          "the",
          "discipline",
          "of",
          "the",
          "$name_tag,",
          "and",
          "do",
          "$no_entry",
          "loathe",
          "His",
          "rebuke;",
        ],
      },
      {
        verse_number: 12,
        words: [
          "for",
          "the",
          "$name_tag",
          "disciplines",
          "the",
          "one",
          "He",
          "$heart_red,",
          "as",
          "a",
          "$father",
          "the",
          "$son",
          "in",
          "whom",
          "he",
          "delights.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$gift+smile",
          "is",
          "the",
          "$person",
          "who",
          "finds",
          "wisdom,",
          "the",
          "$person",
          "who",
          "acquires",
          "understanding,",
        ],
      },
      {
        verse_number: 14,
        words: [
          "for",
          "she",
          "is",
          "more",
          "$thumbs_up",
          "than",
          "silver,",
          "and",
          "her",
          "gain",
          "is",
          "better",
          "than",
          "fine",
          "gold.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "She",
          "is",
          "more",
          "precious",
          "than",
          "rubies;",
          "nothing",
          "you",
          "desire",
          "compares",
          "with",
          "her.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "Long",
          "$sun",
          "is",
          "in",
          "her",
          "right",
          "hand;",
          "in",
          "her",
          "left",
          "hand",
          "are",
          "riches",
          "and",
          "$star.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "All",
          "her",
          "$road",
          "are",
          "pleasant,",
          "and",
          "all",
          "her",
          "$road",
          "are",
          "peaceful.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "She",
          "is",
          "a",
          "$tree",
          "of",
          "$sprout",
          "to",
          "those",
          "who",
          "embrace",
          "her,",
          "and",
          "those",
          "who",
          "lay",
          "hold",
          "of",
          "her",
          "are",
          "blessed.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "The",
          "$name_tag",
          "founded",
          "the",
          "$earth",
          "by",
          "wisdom",
          "and",
          "established",
          "the",
          "$sky",
          "by",
          "understanding.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "By",
          "His",
          "knowledge",
          "the",
          "watery",
          "depths",
          "were",
          "broken",
          "open,",
          "and",
          "the",
          "clouds",
          "dripped",
          "with",
          "dew.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "My",
          "$son,",
          "do",
          "$no_entry",
          "lose",
          "$eyes",
          "of",
          "this:",
          "Preserve",
          "sound",
          "judgment",
          "and",
          "discernment.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "They",
          "will",
          "be",
          "$sprout",
          "to",
          "your",
          "$person_other",
          "and",
          "adornment",
          "to",
          "your",
          "neck.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Then",
          "you",
          "will",
          "$walking",
          "on",
          "your",
          "$road",
          "in",
          "safety,",
          "and",
          "your",
          "foot",
          "will",
          "$no_entry",
          "stumble.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "When",
          "you",
          "lie",
          "down,",
          "you",
          "will",
          "$no_entry",
          "be",
          "afraid;",
          "when",
          "you",
          "rest,",
          "your",
          "sleep",
          "will",
          "be",
          "sweet.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Do",
          "$no_entry",
          "fear",
          "sudden",
          "danger",
          "or",
          "the",
          "ruin",
          "that",
          "$footprints",
          "the",
          "$thumbs_down,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "for",
          "the",
          "$name_tag",
          "will",
          "be",
          "your",
          "confidence",
          "and",
          "will",
          "keep",
          "your",
          "foot",
          "from",
          "the",
          "snare.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "Do",
          "$no_entry",
          "withhold",
          "$thumbs_up",
          "from",
          "the",
          "deserving",
          "when",
          "it",
          "is",
          "in",
          "the",
          "power",
          "of",
          "your",
          "$hand",
          "to",
          "$hammer.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "Do",
          "$no_entry",
          "$speech",
          "your",
          "neighbor,",
          "$walking",
          "$turn_back",
          "tomorrow",
          "and",
          "I",
          "will",
          "$hands_giving,",
          "when",
          "you",
          "already",
          "have",
          "the",
          "means.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "Do",
          "$no_entry",
          "devise",
          "$thumbs_down",
          "against",
          "your",
          "neighbor,",
          "for",
          "he",
          "dwells",
          "trustfully",
          "beside",
          "you.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "Do",
          "$no_entry",
          "accuse",
          "a",
          "$person",
          "without",
          "cause,",
          "when",
          "he",
          "has",
          "done",
          "you",
          "$no_entry",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "Do",
          "$no_entry",
          "$heart_on_fire",
          "a",
          "violent",
          "$man_beard,",
          "or",
          "choose",
          "any",
          "of",
          "his",
          "$road;",
        ],
      },
      {
        verse_number: 32,
        words: [
          "for",
          "the",
          "$name_tag",
          "detests",
          "the",
          "perverse,",
          "but",
          "He",
          "is",
          "a",
          "friend",
          "to",
          "the",
          "upright.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "The",
          "curse",
          "of",
          "the",
          "$name_tag",
          "is",
          "on",
          "the",
          "$house",
          "of",
          "the",
          "$thumbs_down,",
          "but",
          "He",
          "$speech+thumbs_up",
          "the",
          "home",
          "of",
          "the",
          "$ruler.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "He",
          "mocks",
          "the",
          "mockers,",
          "but",
          "$hands_giving",
          "grace",
          "to",
          "the",
          "humble.",
        ],
      },
      {
        verse_number: 35,
        words: [
          "The",
          "wise",
          "will",
          "inherit",
          "$star,",
          "but",
          "fools",
          "are",
          "held",
          "up",
          "to",
          "shame.",
        ],
      },
    ],
  };
  return chapter;
}
