export function bible_glyph_chapter_gen05() {
  "The fifth chapter of Genesis, drawn in pictures. Ten men from Adam to Noah, each one given the same three lines, how old he was when his son came, how long he lived afterwards, and how long he lived altogether. The point of a list this even is what happens when it is broken.";
  "AND HE DIED IS SAID EIGHT TIMES. It closes the entry for Adam, Seth, Enosh, Kenan, Mahalalel, Jared, Methuselah and Lamech. Nothing is added to it and nothing is explained by it. Ten men are listed and only eight get those words, so the two who do not are marked by the silence rather than by anything said about them. This is a chapter that makes its point by being boring on purpose, because a reader who has heard the same ending eight times will hear the ninth one missing.";
  "ENOCH GETS THE SAME SENTENCE WITH ONE VERB SWAPPED. Every other man lived after he fathered his son. Enoch walked with God after he fathered Methuselah. The word for lived is taken out and the word for walked is put in its place, in exactly the slot the reader is expecting, and then it is done a second time before the end. The chapter does not stop to explain the change. It just puts a different word where the same word has been nine times, and lets you notice.";
  "AND THEN THE ENDING IS MISSING TOO. The days of Enoch were three hundred and sixty five years, and the sentence that has ended every entry so far does not come. Instead, Enoch walked with God, and he was not, because God took him. The word for took is an ordinary word, the same one used for taking a wife or taking a stone. There is no vision and no chariot here. A man is walking, and then the list simply has nobody left to write about.";
  "THE WORD FOR MAN AND THE NAME ADAM ARE THE SAME WORD. In the first verse God created man, and this is the book of the generations of Adam, and both are the same four letters. In the second verse God called their name Adam, which is said of the two of them together, so the name is given to a man and a woman at once. And the word for the ground the man was taken from is the same root again, which is why the last man in the list is named out of a complaint about that ground.";
  "LIKENESS AND IMAGE ARE HANDED DOWN ONE STEP. The first verse says God made him in the likeness of God. The third verse says Adam fathered a son in his own likeness, after his own image. The two words move together from God to Adam, and then from Adam to Seth, in the same order both times. Whatever a man is when God makes him, the chapter says he passes on, and it says it by repeating the words rather than by arguing for it.";
  "LAMECH NAMES HIS SON OUT OF A WORD THAT IS NOT QUITE HIS NAME. He calls him Noah, and says this one will comfort us from our work and from the toil of our hands, from the ground the LORD has cursed. Comfort and Noah sound alike and are not the same root, and the verse joins them by the sound. The word for toil is the word from the curse in the third chapter, and the ground is the same ground. So the last name in the list is a man asking, in his sons name, when the third chapter is going to be over.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "GEN05",
    reference: "Genesis 5",
    verses: [
      {
        verse_number: 1,
        words: [
          "This",
          "is",
          "the",
          "book",
          "of",
          "the",
          "generations",
          "of",
          "Adam.",
          "In",
          "the",
          "$sun",
          "$fire",
          "created",
          "$person,",
          "in",
          "the",
          "likeness",
          "of",
          "$fire",
          "he",
          "$hammer",
          "him.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Male",
          "and",
          "female",
          "he",
          "created",
          "them,",
          "and",
          "he",
          "$speech+thumbs_up",
          "them,",
          "and",
          "called",
          "their",
          "$name_tag",
          "$person",
          "in",
          "the",
          "$sun",
          "they",
          "were",
          "created.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "When",
          "Adam",
          "had",
          "$sprout",
          "a",
          "hundred",
          "and",
          "thirty",
          "years,",
          "he",
          "fathered",
          "in",
          "his",
          "own",
          "likeness,",
          "after",
          "his",
          "own",
          "image,",
          "and",
          "called",
          "his",
          "$name_tag",
          "Seth.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "And",
          "the",
          "$sun",
          "of",
          "Adam",
          "after",
          "he",
          "fathered",
          "Seth",
          "were",
          "eight",
          "hundred",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "the",
          "$sprout",
          "of",
          "Adam",
          "were",
          "nine",
          "hundred",
          "and",
          "thirty",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "When",
          "Seth",
          "had",
          "$sprout",
          "a",
          "hundred",
          "and",
          "five",
          "years,",
          "he",
          "fathered",
          "Enosh.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "And",
          "Seth",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Enosh",
          "eight",
          "hundred",
          "and",
          "seven",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Seth",
          "were",
          "nine",
          "hundred",
          "and",
          "twelve",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "When",
          "Enosh",
          "had",
          "$sprout",
          "ninety",
          "years,",
          "he",
          "fathered",
          "Kenan.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "And",
          "Enosh",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Kenan",
          "eight",
          "hundred",
          "and",
          "fifteen",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Enosh",
          "were",
          "nine",
          "hundred",
          "and",
          "five",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "When",
          "Kenan",
          "had",
          "$sprout",
          "seventy",
          "years,",
          "he",
          "fathered",
          "Mahalalel.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "And",
          "Kenan",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Mahalalel",
          "eight",
          "hundred",
          "and",
          "forty",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Kenan",
          "were",
          "nine",
          "hundred",
          "and",
          "ten",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "When",
          "Mahalalel",
          "had",
          "$sprout",
          "sixty",
          "and",
          "five",
          "years,",
          "he",
          "fathered",
          "Jared.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "And",
          "Mahalalel",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Jared",
          "eight",
          "hundred",
          "and",
          "thirty",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Mahalalel",
          "were",
          "eight",
          "hundred",
          "and",
          "ninety",
          "and",
          "five",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "When",
          "Jared",
          "had",
          "$sprout",
          "a",
          "hundred",
          "and",
          "sixty",
          "and",
          "two",
          "years,",
          "he",
          "fathered",
          "Enoch.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "And",
          "Jared",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Enoch",
          "eight",
          "hundred",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Jared",
          "were",
          "nine",
          "hundred",
          "and",
          "sixty",
          "and",
          "two",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "When",
          "Enoch",
          "had",
          "$sprout",
          "sixty",
          "and",
          "five",
          "years,",
          "he",
          "fathered",
          "Methuselah.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "And",
          "Enoch",
          "$walking",
          "with",
          "$fire",
          "after",
          "he",
          "fathered",
          "Methuselah",
          "three",
          "hundred",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Enoch",
          "were",
          "three",
          "hundred",
          "and",
          "sixty",
          "and",
          "five",
          "years.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "And",
          "Enoch",
          "$walking",
          "with",
          "$fire,",
          "and",
          "he",
          "was",
          "not,",
          "because",
          "$fire",
          "$hand_receiving",
          "him.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "When",
          "Methuselah",
          "had",
          "$sprout",
          "a",
          "hundred",
          "and",
          "eighty",
          "and",
          "seven",
          "years,",
          "he",
          "fathered",
          "Lamech.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "And",
          "Methuselah",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Lamech",
          "seven",
          "hundred",
          "and",
          "eighty",
          "and",
          "two",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Methuselah",
          "were",
          "nine",
          "hundred",
          "and",
          "sixty",
          "and",
          "nine",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "When",
          "Lamech",
          "had",
          "$sprout",
          "a",
          "hundred",
          "and",
          "eighty",
          "and",
          "two",
          "years,",
          "he",
          "fathered",
          "a",
          "$son.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "And",
          "he",
          "called",
          "his",
          "$name_tag",
          "Noah,",
          "$speech,",
          "This",
          "one",
          "will",
          "comfort",
          "us",
          "from",
          "our",
          "work",
          "and",
          "from",
          "the",
          "toil",
          "of",
          "our",
          "$hand,",
          "$tray_out",
          "the",
          "ground",
          "that",
          "$name_tag",
          "$speech+thumbs_down.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "And",
          "Lamech",
          "$sprout",
          "after",
          "he",
          "fathered",
          "Noah",
          "five",
          "hundred",
          "and",
          "ninety",
          "and",
          "five",
          "years,",
          "and",
          "he",
          "fathered",
          "$son",
          "and",
          "$woman.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "So",
          "all",
          "the",
          "$sun",
          "of",
          "Lamech",
          "were",
          "seven",
          "hundred",
          "and",
          "seventy",
          "and",
          "seven",
          "years,",
          "and",
          "$skull.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "And",
          "Noah",
          "was",
          "a",
          "$son",
          "of",
          "five",
          "hundred",
          "years,",
          "and",
          "Noah",
          "fathered",
          "Shem,",
          "Ham",
          "and",
          "Japheth.",
        ],
      },
    ],
  };
  return chapter;
}
