export function bible_glyph_chapter_3jn01() {
  "The twentieth picture Bible chapter written by hand: the whole of the third letter of John, in the shorthand a person types.";
  "IT IS THE SECOND WHOLE BOOK IN A ROW AND THE SECOND IN ONE SITTING. The letter before it was the first book here small enough to be its own chapter, and the note beside that one said what a complete book buys a reader that a chapter cannot. Two of them side by side buys something further: a reader who finishes one can start another and finish that too, which is the first time this collection has offered anything like a run.";
  "AND IT COST NO PICTURES, WHICH IS NOW TWICE IN A ROW. Every mark this letter draws was seated by the five chapters of the first letter or by the second, so two whole books by one hand have been added to this Bible for nothing at all. A single free chapter says the table is starting to pay back; two free books in succession says the paying back is the normal condition and the buying was the exceptional one.";
  "THERE ARE THREE MEN NAMED IN FOURTEEN VERSES AND NOT ONE OF THEM IS DRAWN. Gaius, Diotrephes and Demetrius stay in plain English, because a proper name is never seated here - the same rule that made the thirteenth of Jeremiah unusable and the thirteenth of Judges readable. And then the seventh verse draws THE Name, which is the covenant mark and not a man at all. So the one letter in this Bible with the most personal names in it is also the letter where the name mark falls on nobody, and a reader who has met that mark elsewhere is being told precisely which name is meant.";
  "TWO DIFFERENT MARKS FOR SEEING, AND THE LETTER BEFORE THIS ONE HAD TWO FOR SPEAKING. Blepo is the wide eyes and is drawn in the second letter, where John says watch yourselves; horao is the single eye and is drawn twice here, where the man who does evil has not seen God and where John hopes to see his friend. English calls both of them see. The two letters together are the shortest run in the collection where a reader can watch two ordinary English words each split into a pair of marks.";
  "AND THERE ARE TWO HEARTS IN THIS ONE. Agape and agapetos take the red heart, which is the mark the whole first letter is built out of; philos, the friend, takes the orange one, and it is drawn twice in the closing line and nowhere else in this Bible so far. A letter that opens by calling a man beloved and closes by greeting the friends by name is the one place where the difference is standing in front of the reader rather than being asserted.";
  "THE POINTING BACK IS DOING A THIRD JOB HERE AND IT IS STILL ONE WORD. In the letter before this it carried her and his and him and once it stood where the English reads love. Here it is among THEM in the ninth verse and it is the intensive ITSELF in the twelfth, where Demetrius is well spoken of by the truth itself. Different English words every time and one Greek word every time, which is the case where a mark carrying several senses is teaching rather than colliding.";
  "THE HAMMER AND THE TOOLS STAND IN ONE CLAUSE IN THE TENTH VERSE. Poieo is the hammer, the doing; erga is the tools, the things done. English joins them - the deeds he does - and reads like a phrase with a word to spare; the Greek is a verb and its object and the two marks show that. This is the same trade the fourth verse of the letter before took, where a smooth translation had folded a noun and a verb into one.";
  "AND THE NO ENTRY SIGN MEASURES IN THE FOURTH VERSE INSTEAD OF FORBIDDING. I have NO greater joy than this - the mark there is doing comparison, and seven verses later the same mark is do not imitate what is evil, which is a prohibition. Both are ouk or me and both are honest, and a reader who meets the forbidding one first has to widen what the sign means rather than correct it. That is worth leaving visible: a mark that only ever forbade would be a smaller and falser thing than the word it draws.";
  let chapter = {
    chapter_code: "3JN01",
    reference: "3 John",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "elder,",
          "To",
          "Gaius",
          "the",
          "$heart_red,",
          "whom",
          "I",
          "$heart_red",
          "$tray_in",
          "$check.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$heart_red,",
          "I",
          "pray",
          "that",
          "in",
          "every",
          "way",
          "you",
          "may",
          "prosper",
          "$plus",
          "be",
          "in",
          "good",
          "health,",
          "just",
          "as",
          "your",
          "soul",
          "prospers.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "For",
          "I",
          "$smile",
          "greatly",
          "when",
          "the",
          "$brother",
          "$footprints",
          "$plus",
          "$witness",
          "to",
          "your",
          "$check,",
          "just",
          "as",
          "you",
          "$walking",
          "$tray_in",
          "the",
          "$check.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "have",
          "$no_entry",
          "greater",
          "$smile",
          "than",
          "to",
          "$ear",
          "that",
          "my",
          "$child",
          "are",
          "$walking",
          "$tray_in",
          "the",
          "$check.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$heart_red,",
          "you",
          "are",
          "$anchor",
          "in",
          "what",
          "you",
          "$hammer",
          "for",
          "the",
          "$brother,",
          "$plus",
          "they",
          "are",
          "strangers",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "They",
          "have",
          "$witness",
          "to",
          "the",
          "$church",
          "about",
          "your",
          "$heart_red.",
          "You",
          "will",
          "$hammer",
          "well",
          "to",
          "send",
          "them",
          "on",
          "their",
          "way",
          "in",
          "a",
          "manner",
          "worthy",
          "of",
          "$fire.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "For",
          "they",
          "went",
          "out",
          "on",
          "behalf",
          "of",
          "the",
          "$name_tag,",
          "$hand_receiving",
          "nothing",
          "from",
          "the",
          "Gentiles.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Therefore",
          "we",
          "ought",
          "to",
          "support",
          "such",
          "men,",
          "so",
          "that",
          "we",
          "may",
          "be",
          "fellow",
          "workers",
          "for",
          "the",
          "$check.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "I",
          "have",
          "written",
          "to",
          "the",
          "$church,",
          "but",
          "Diotrephes,",
          "who",
          "loves",
          "to",
          "be",
          "first",
          "among",
          "$pointing_back,",
          "will",
          "$no_entry",
          "accept",
          "our",
          "instruction.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "So",
          "if",
          "I",
          "$footprints,",
          "I",
          "will",
          "call",
          "attention",
          "to",
          "$pointing_back",
          "$tools,",
          "which",
          "he",
          "$hammer",
          "with",
          "$thumbs_down",
          "$speech",
          "against",
          "us.",
          "$plus",
          "$no_entry",
          "satisfied",
          "with",
          "that,",
          "$pointing_back",
          "refuses",
          "to",
          "welcome",
          "the",
          "$brother",
          "$plus",
          "forbids",
          "those",
          "who",
          "want",
          "to,",
          "$plus",
          "puts",
          "them",
          "$tray_out",
          "the",
          "$church.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$heart_red,",
          "$no_entry",
          "imitate",
          "what",
          "is",
          "$thumbs_down",
          "but",
          "what",
          "is",
          "$thumbs_up.",
          "The",
          "one",
          "who",
          "does",
          "good",
          "is",
          "$tray_out",
          "$fire;",
          "the",
          "one",
          "who",
          "does",
          "evil",
          "has",
          "$no_entry",
          "$eye",
          "$fire.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Demetrius",
          "has",
          "good",
          "$witness",
          "from",
          "everyone,",
          "$plus",
          "from",
          "the",
          "$check",
          "$pointing_back.",
          "$plus",
          "we",
          "also",
          "$witness,",
          "$plus",
          "you",
          "$lightbulb",
          "$pointing",
          "our",
          "$witness",
          "is",
          "true.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "I",
          "have",
          "many",
          "things",
          "to",
          "write",
          "to",
          "you,",
          "but",
          "I",
          "would",
          "$no_entry",
          "write",
          "with",
          "ink",
          "$plus",
          "pen.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Instead",
          "I",
          "hope",
          "to",
          "$eye",
          "you",
          "soon,",
          "$plus",
          "we",
          "will",
          "$mouth",
          "face",
          "to",
          "face.",
          "Peace",
          "to",
          "you.",
          "The",
          "$heart_orange",
          "here",
          "send",
          "you",
          "greetings.",
          "Greet",
          "the",
          "$heart_orange",
          "there",
          "by",
          "$name_tag.",
        ],
      },
    ],
  };
  return chapter;
}
