export function bible_glyph_chapter_pro01() {
  "Proverbs 1, drawn in pictures, so that a person who cannot read the letters can still follow it. It opens the book, says what the book is for, warns a boy off a gang, and then hands the last third of the chapter to Wisdom herself, shouting in the street. Thirty three lines.";
  "THE LINE THE WHOLE BOOK STANDS ON COMES OUT WITH ONE MARK. The fear of the LORD is the beginning of knowledge, but fools despise wisdom and discipline. Sixteen words, and the only thing drawn in them is the name of God. There is no picture for fear, none for a beginning, none for knowledge, none for a fool, none for wisdom and none for discipline. That is the seventh line, it is the sentence the other thirty one chapters of this book hang on, and a reader following pictures gets a name tag and a row of letters.";
  "KNOWING HAS A LAMP AND WISDOM HAS NOTHING. There is a lamp drawing and it sits on the verb, so the second line lights up on gaining and the twenty third lights up on I would have made my words known to you. Meanwhile wisdom and wise are said seven times in this chapter and knowledge four times, and every one of them is plain letters. The chapter is an advertisement for a thing it cannot show. Of everything this collection still has no picture for, this is the one where the gap is the loudest, because the missing word is the title of the book.";
  "THE LAST FOURTEEN LINES ARE SPOKEN BY A WOMAN AND THE PAGE NEVER SHOWS HER. From the twentieth line on, Wisdom is a person: she calls out in the street, she lifts her voice, she cries aloud at the city gates, she is refused, and she answers. There is a woman drawing and it never comes, because the word on the page is Wisdom and not woman. So a reader gets a hand lifted, a voice, a city and a speech, and no idea that anybody is standing there. The whole force of the passage is that wisdom is not a topic but somebody shouting at you in public, and that is exactly what does not survive.";
  "THE ONE BIRD IN THE CHAPTER IS NOT CALLED A BIRD. The seventeenth line says how useless it is to spread a net where any bird can see it, and there is a bird drawing that eight other chapters use. It cannot come here, because the Hebrew does not say bird; it says owner of a wing. So the line keeps its eyes and loses both the net and the creature. The net, the purse in the fourteenth line, and the garland and the pendant in the ninth are the chapter's other solid objects, and none of the four is drawn either.";
  "BLOOD IS THE ONE WORD THAT IS DRAWN EVERY TIME IT IS SAID, AND THE THIRD TIME IS THE POINT. The gang says let us lie in wait for blood in the eleventh line; the sixteenth says their feet are swift to shed blood; the eighteenth says they lie in wait for their own blood. Same mark, three times, and the argument of the passage is that the third one is what the first two were always going to mean. Here the sameness of the picture is doing the work rather than losing it, which is rare enough on these pages to be worth writing down.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PRO01",
    reference: "Proverbs 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "proverbs",
          "of",
          "Solomon",
          "$son",
          "of",
          "David,",
          "$king",
          "of",
          "Israel:",
        ],
      },
      {
        verse_number: 2,
        words: [
          "For",
          "$lightbulb",
          "wisdom",
          "and",
          "discipline,",
          "for",
          "comprehending",
          "words",
          "of",
          "insight,",
        ],
      },
      {
        verse_number: 3,
        words: [
          "for",
          "$hand_receiving",
          "instruction",
          "in",
          "wise",
          "living,",
          "in",
          "$ruler,",
          "$scales,",
          "and",
          "equity;",
        ],
      },
      {
        verse_number: 4,
        words: [
          "to",
          "$hands_giving",
          "prudence",
          "to",
          "the",
          "simple",
          "and",
          "knowledge",
          "and",
          "discretion",
          "to",
          "the",
          "young:",
        ],
      },
      {
        verse_number: 5,
        words: [
          "let",
          "the",
          "wise",
          "$ear",
          "and",
          "gain",
          "instruction,",
          "and",
          "the",
          "discerning",
          "acquire",
          "wise",
          "counsel",
        ],
      },
      {
        verse_number: 6,
        words: [
          "by",
          "understanding",
          "the",
          "proverbs",
          "and",
          "parables,",
          "the",
          "$speech",
          "and",
          "riddles",
          "of",
          "the",
          "wise.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "fear",
          "of",
          "the",
          "$name_tag",
          "is",
          "the",
          "beginning",
          "of",
          "knowledge,",
          "but",
          "fools",
          "despise",
          "wisdom",
          "and",
          "discipline.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$ear,",
          "my",
          "$son,",
          "to",
          "your",
          "$father",
          "instruction,",
          "and",
          "do",
          "not",
          "forsake",
          "the",
          "$scroll",
          "of",
          "your",
          "mother.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "For",
          "they",
          "are",
          "a",
          "garland",
          "of",
          "grace",
          "on",
          "your",
          "head",
          "and",
          "a",
          "pendant",
          "around",
          "your",
          "neck.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "My",
          "$son,",
          "if",
          "sinners",
          "entice",
          "you,",
          "$no_entry",
          "yield",
          "to",
          "them.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "If",
          "they",
          "$speech,",
          "$walking",
          "along,",
          "let",
          "us",
          "lie",
          "in",
          "wait",
          "for",
          "$blood,",
          "let",
          "us",
          "ambush",
          "the",
          "innocent",
          "without",
          "cause,",
        ],
      },
      {
        verse_number: 12,
        words: [
          "let",
          "us",
          "swallow",
          "them",
          "$sprout",
          "like",
          "Sheol,",
          "and",
          "whole",
          "like",
          "those",
          "descending",
          "into",
          "the",
          "Pit.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "We",
          "will",
          "find",
          "all",
          "manner",
          "of",
          "precious",
          "goods;",
          "we",
          "will",
          "fill",
          "our",
          "$house",
          "with",
          "plunder.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Throw",
          "in",
          "your",
          "lot",
          "with",
          "us;",
          "let",
          "us",
          "all",
          "share",
          "one",
          "purse",
        ],
      },
      {
        verse_number: 15,
        words: [
          "my",
          "$son,",
          "$no_entry",
          "$walking",
          "in",
          "the",
          "$road",
          "with",
          "them",
          "or",
          "set",
          "foot",
          "upon",
          "their",
          "path.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "For",
          "their",
          "feet",
          "run",
          "to",
          "$thumbs_down,",
          "and",
          "they",
          "are",
          "swift",
          "to",
          "shed",
          "$blood.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "How",
          "futile",
          "it",
          "is",
          "to",
          "spread",
          "the",
          "net",
          "where",
          "any",
          "bird",
          "can",
          "$eyes",
          "it!",
        ],
      },
      {
        verse_number: 18,
        words: [
          "But",
          "they",
          "lie",
          "in",
          "wait",
          "for",
          "their",
          "own",
          "$blood;",
          "they",
          "ambush",
          "their",
          "own",
          "$person_other.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Such",
          "is",
          "the",
          "fate",
          "of",
          "all",
          "who",
          "are",
          "greedy,",
          "whose",
          "unjust",
          "gain",
          "$hand_receiving",
          "the",
          "$person_other",
          "of",
          "its",
          "possessors.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Wisdom",
          "calls",
          "out",
          "in",
          "the",
          "street;",
          "she",
          "$hands_giving",
          "her",
          "$voice",
          "in",
          "the",
          "square.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "In",
          "the",
          "main",
          "concourse",
          "she",
          "cries",
          "aloud;",
          "at",
          "the",
          "$city",
          "gates",
          "she",
          "$speech:",
        ],
      },
      {
        verse_number: 22,
        words: [
          "How",
          "long,",
          "O",
          "simple",
          "ones,",
          "will",
          "you",
          "$heart_red",
          "your",
          "simple",
          "ways?",
          "How",
          "long",
          "will",
          "scoffers",
          "delight",
          "in",
          "their",
          "scorn",
          "and",
          "fools",
          "hate",
          "knowledge?",
        ],
      },
      {
        verse_number: 23,
        words: [
          "If",
          "you",
          "had",
          "$turn_back",
          "at",
          "my",
          "rebuke,",
          "then",
          "surely",
          "I",
          "would",
          "have",
          "poured",
          "out",
          "my",
          "$wind",
          "on",
          "you;",
          "I",
          "would",
          "have",
          "$lightbulb",
          "my",
          "$speech",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "Because",
          "you",
          "refused",
          "my",
          "call,",
          "and",
          "no",
          "one",
          "took",
          "my",
          "outstretched",
          "$hand,",
        ],
      },
      {
        verse_number: 25,
        words: [
          "because",
          "you",
          "neglected",
          "all",
          "my",
          "counsel,",
          "and",
          "wanted",
          "$no_entry",
          "of",
          "my",
          "correction,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "in",
          "turn",
          "I",
          "will",
          "mock",
          "your",
          "calamity;",
          "I",
          "will",
          "sneer",
          "when",
          "terror",
          "$footprints",
          "you,",
        ],
      },
      {
        verse_number: 27,
        words: [
          "when",
          "your",
          "dread",
          "$footprints",
          "like",
          "a",
          "storm,",
          "and",
          "your",
          "destruction",
          "like",
          "a",
          "whirlwind,",
          "when",
          "distress",
          "and",
          "anguish",
          "$footprints",
          "you.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "Then",
          "they",
          "will",
          "call",
          "on",
          "me,",
          "but",
          "I",
          "will",
          "$no_entry",
          "answer;",
          "they",
          "will",
          "earnestly",
          "seek",
          "me,",
          "but",
          "will",
          "$no_entry",
          "find",
          "me.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "For",
          "they",
          "hated",
          "knowledge",
          "and",
          "chose",
          "$no_entry",
          "to",
          "fear",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "They",
          "accepted",
          "$no_entry",
          "of",
          "my",
          "counsel;",
          "they",
          "despised",
          "all",
          "my",
          "reproof.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "So",
          "they",
          "will",
          "eat",
          "the",
          "fruit",
          "of",
          "their",
          "own",
          "$road,",
          "and",
          "be",
          "filled",
          "with",
          "their",
          "own",
          "devices.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "For",
          "the",
          "waywardness",
          "of",
          "the",
          "simple",
          "will",
          "slay",
          "them,",
          "and",
          "the",
          "complacency",
          "of",
          "fools",
          "will",
          "destroy",
          "them.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "But",
          "whoever",
          "$ear",
          "to",
          "me",
          "will",
          "dwell",
          "in",
          "safety,",
          "secure",
          "from",
          "the",
          "fear",
          "of",
          "$thumbs_down.",
        ],
      },
    ],
  };
  return chapter;
}
