export function bible_production_brief() {
  "The whole brief for what gets made in what order - audio, designs, still pictures, animation, three dimensions, and the game - covering which of those carry from one rung to the next, which are thrown away by climbing, and which decision is not this project's to make.";
  "★ THE LADDER IS THE WRONG AXIS, AND SORTING BY WHAT CARRIES ANSWERS THE QUESTION THE LADDER WAS ASKED TO ANSWER. Rungs suggest that everything at the bottom is a step toward the top, and most of it is not: rendered frames carry nowhere, so a still picture is discarded the day it is animated. Two things carry unchanged all the way up, and everything else is per-rung spend.";
  "★ THE AUDIO CARRIES UNCHANGED THROUGH EVERY RUNG, WHICH MAKES IT THE ONE ASSET THAT IS NEVER A PROTOTYPE. A reading of a passage sounds the same behind a still picture, behind a cartoon and behind a modelled scene. It is also the most expensive thing here that a machine cannot decide - a voice, a pace, a tone - and it is already load-bearing, because the player hears the passage read aloud before anything is asked of them. So it is finished work at rung one and finished work at rung four.";
  "★ THE DESIGNS CARRY TOO, AND THE SCENE BRIEF ALREADY SAYS WHY. Consistency from picture to picture is a property of the DESIGN and not of the pictures, so a figure settled once is got by every scene that names it - and a figure sculpted from turnaround drawings is the ordinary way a two-dimensional design becomes a three-dimensional one. So a 2-D game and a 3-D cutscene sharing one design is normal rather than a compromise.";
  "It follows that the two things worth doing now are the two with no rungs: record the readings, and settle the designs. Neither is thrown away by any later choice, and both are exactly the work that has to exist before an artist can be handed anything.";
  "★ CUTSCENE-BEFORE-GAME IS FORCED AND IS NOT A SCHEDULE PREFERENCE, WHICH IS THE STRONGEST THING IN THIS BRIEF. The word step is settled: the player hears the passage read aloud, whole and in order, BEFORE any of it is asked. That is what keeps carrying a sentence from being authoring one. So a played piece cannot exist without its reading, and the reading with its pictures IS the cutscene. The dependency runs one way and no ordering decision is available.";
  "★ TWO DIMENSIONS OR THREE IS THE ARTIST'S DECISION AND DELIBERATELY NOT MADE HERE, BY THE SAME RULE THAT LEAVES INCLUSION TO THE BUILDER. Whoever renders is the one who can say I can find a way to do this well, and a brief answering that in advance takes the choice from the only person holding it. What this brief owes them is the audio, the designs, the scene divisions and the passages - not a medium.";
  "The arguments both ways are worth handing over with the decision. Three dimensions is front-loaded and then cheap per scene: a hillside and a crowd are built once and both feedings use them, which matters when the corpus already holds hundreds of events and is growing. Still pictures are cheap per scene and have a far lower floor - one artist can make an excellent one, whereas indifferent 3-D reads as cheap in a way an excellent drawing never does, and PSA33:3 says to play skilfully.";
  "★ THE ONE THING THAT WOULD BE EXPENSIVE IS PRODUCING MANY SCENES BEFORE PRODUCING ONE END TO END. Gathering is nearly free and rendering is not, so the cost per scene is the number nobody has yet and everything else is guessing. One event carried the whole way - gathered, read, designed, pictured, played - prices the rest of the corpus and will change somebody's mind about the medium, which is another reason not to fix the medium first.";
  let brief = {
    step: "production",
    what: "what is made in what order, and which of it survives a change of medium",
    settled:
      "rendered frames carry nowhere; the readings and the designs carry through every medium unchanged, so both are finished work rather than prototypes and both are the work to do now; a cutscene must exist before its game piece can, because the passage is heard before anything is asked; a 2-D game and a 3-D cutscene may share one design",
    open: "two dimensions or three, which belongs to whoever renders; who reads and in which translation; whether a scene's pictures are commissioned per scene or assembled from a shared set; what one finished event actually costs",
    forbidden:
      "asking a player to act on a passage they have not heard read; fixing the medium before one event has been carried end to end; producing many scenes at a cost per scene nobody has measured; treating a recorded reading or a settled design as a throwaway for one rung",
    done: "one event exists gathered, read aloud, designed, pictured and played, and the cost of the next one is a number rather than a guess",
  };
  return brief;
}
