export function bible_glyph_chapter_psa001() {
  "The forty fourth picture Bible chapter written by hand: the whole of the first psalm, the two ways set side by side at the door of the book, in the shorthand a person types.";
  "THE OLD TESTAMENT MEASURES HIGHER THAN THE NEW AND NOBODY HAD LOOKED UNTIL NOW. Every survey run for this list so far has been run over the New Testament. Run over the nine hundred and eighteen unwritten chapters of the Old, it comes back with the hundred and thirty fourth psalm at sixty in a hundred, the sixty seventh at forty nine, the hundred and forty sixth and the hundred and fifteenth at forty six, and the eighty fifth at forty five - against a New Testament ceiling of forty one after forty two chapters of drawing at it. The reason is not that Hebrew is easier. It is that a psalm is short, and that what a psalm is made of - the Name, the road, the law, knowing, water, wind, a tree - is very nearly the list of things this table was seated on first.";
  "AND PSALM ONE WAS TAKEN AT FORTY THREE OVER SIX CHAPTERS THAT MEASURED HIGHER, BECAUSE IT IS THE DOOR OF THE BOOK. Five psalms already stand on this list and not the one that opens the Psalter. Everything the rest of the book argues from is set out in six verses here: two ways, one that ends in fruit and one that ends in chaff, and a Name that knows the first of them. The thirty fifth entry took a chapter over one that measured higher because a whole gospel was missing; a share cannot measure a doorway either.";
  "FOUR OF THE FIVE GRAMMAR MARKS NEVER CROSS INTO HEBREW, AND THIS PAGE IS WHERE A READER MEETS THAT. The plus, the tray in, the pointing and the pointing back appear nowhere in any of the eleven Hebrew chapters written before this one, and they appear nowhere here; only the tray out crosses, six times across all of them. Those marks are seated on Greek words - the and, the in, the that, the him - and Hebrew does not have separate words to seat them on. So a reader coming to this page from a letter of Paul finds every and gone plain, and that is the language underneath showing through rather than anything left out.";
  "THE NEGATION FALLS SIX TIMES IN SIX VERSES, WHICH IS THE DENSEST THIS BIBLE HAS EVER BEEN. Three in the first verse, one in the third, one in the fourth and one in the fifth, and every one of them replaces the English word not. Hebrew says the negative three times in the first verse and English wants to say it once and then use or twice, so the English here is written with the not spelled out each time - does not walk, does not stand, does not sit. That is a plain English sentence and it lets the marks land where the language underneath actually puts them, which is what a reader of pictures is reading.";
  "THE WICKED IS A PICTURE AND SINNERS IS NOT, AND THEY STAND SIDE BY SIDE TWICE. They are two different words underneath, and only one of them is seated, so the fifth verse has a mark and a plain word in the same sentence doing the same job. A reader should not read that as a distinction being drawn here. The forty second entry had God drawn and fire plain inside one verse for exactly the same reason: a mark stands for one root of the language underneath, never for one word of the English on top.";
  "THE RULER AND THE SCALES ARE BOTH ON THIS PAGE AND THEY ARE THE ARGUMENT OF IT. The ruler is a measure and says the judging is straight; the scales are the judgment itself. The fifth verse puts them one after the other - the wicked will not stand in the judgment, nor sinners in the assembly of the righteous - so the picture of the weighing and the picture of the standard arrive together. Both were seated by earlier Hebrew chapters and neither was chosen here.";
  "THE NAME IS THE NAME TAG AND IT FALLS TWICE, WHICH IS HOW EVERY HEBREW PAGE HERE WRITES IT. English Bibles print the divine name as LORD in capitals; this Bible draws a name tag, because that is what the word underneath is - a name and not a title. It opens the second verse and it opens the last, so the psalm's two halves are each hung on it.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA001",
    reference: "Psalm 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "$gift+smile",
          "is",
          "the",
          "$man_beard",
          "who",
          "does",
          "$no_entry",
          "$walking",
          "in",
          "the",
          "counsel",
          "of",
          "the",
          "$thumbs_down,",
          "does",
          "$no_entry",
          "stand",
          "in",
          "the",
          "$road",
          "of",
          "sinners,",
          "does",
          "$no_entry",
          "sit",
          "in",
          "the",
          "seat",
          "of",
          "mockers.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "But",
          "his",
          "delight",
          "is",
          "in",
          "the",
          "$scroll",
          "of",
          "the",
          "$name_tag,",
          "and",
          "on",
          "His",
          "$scroll",
          "he",
          "meditates",
          "day",
          "and",
          "night.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "He",
          "is",
          "like",
          "a",
          "$tree",
          "planted",
          "by",
          "streams",
          "of",
          "$water,",
          "which",
          "$hands_giving",
          "its",
          "fruit",
          "in",
          "season,",
          "whose",
          "leaf",
          "does",
          "$no_entry",
          "wither,",
          "and",
          "who",
          "prospers",
          "in",
          "whatever",
          "he",
          "$hammer.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$no_entry",
          "so",
          "the",
          "$thumbs_down!",
          "For",
          "they",
          "are",
          "like",
          "chaff",
          "driven",
          "off",
          "by",
          "the",
          "$wind.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Therefore",
          "the",
          "$thumbs_down",
          "will",
          "$no_entry",
          "stand",
          "in",
          "the",
          "$scales,",
          "nor",
          "sinners",
          "in",
          "the",
          "assembly",
          "of",
          "the",
          "$ruler.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "For",
          "the",
          "$name_tag",
          "$lightbulb",
          "the",
          "$road",
          "of",
          "the",
          "$ruler,",
          "but",
          "the",
          "$road",
          "of",
          "the",
          "$thumbs_down",
          "will",
          "perish.",
        ],
      },
    ],
  };
  return chapter;
}
