import { bible_glyph_chapter_luk24 } from "./bible_glyph_chapter_luk24.mjs";
import { bible_glyph_chapter_jhn02 } from "./bible_glyph_chapter_jhn02.mjs";
import { bible_glyph_chapter_gen01 } from "./bible_glyph_chapter_gen01.mjs";
import { bible_glyph_chapter_luk07 } from "./bible_glyph_chapter_luk07.mjs";
import { bible_glyph_chapter_mrk10 } from "./bible_glyph_chapter_mrk10.mjs";
import { bible_glyph_chapter_mrk11 } from "./bible_glyph_chapter_mrk11.mjs";
import { bible_glyph_chapter_mrk12 } from "./bible_glyph_chapter_mrk12.mjs";
import { bible_glyph_chapter_luk15 } from "./bible_glyph_chapter_luk15.mjs";
import { bible_glyph_chapter_mrk05 } from "./bible_glyph_chapter_mrk05.mjs";
import { bible_glyph_chapter_mat05 } from "./bible_glyph_chapter_mat05.mjs";
import { bible_glyph_chapter_mrk04 } from "./bible_glyph_chapter_mrk04.mjs";
import { bible_glyph_chapter_mrk08 } from "./bible_glyph_chapter_mrk08.mjs";
import { bible_glyph_chapter_luk02 } from "./bible_glyph_chapter_luk02.mjs";
import { bible_glyph_chapter_jhn04 } from "./bible_glyph_chapter_jhn04.mjs";
import { bible_glyph_chapter_jhn20 } from "./bible_glyph_chapter_jhn20.mjs";
import { bible_glyph_chapter_jhn17 } from "./bible_glyph_chapter_jhn17.mjs";
import { fn_name } from "./fn_name.mjs";
import { bible_glyph_chapter_jhn09 } from "./bible_glyph_chapter_jhn09.mjs";
import { bible_glyph_chapter_jhn10 } from "./bible_glyph_chapter_jhn10.mjs";
import { bible_glyph_chapter_jud01 } from "./bible_glyph_chapter_jud01.mjs";
import { bible_glyph_chapter_3jn01 } from "./bible_glyph_chapter_3jn01.mjs";
import { bible_glyph_chapter_2jn01 } from "./bible_glyph_chapter_2jn01.mjs";
import { bible_glyph_chapter_psa023 } from "./bible_glyph_chapter_psa023.mjs";
import { bible_glyph_chapter_psa100 } from "./bible_glyph_chapter_psa100.mjs";
import { bible_glyph_chapter_1jn02 } from "./bible_glyph_chapter_1jn02.mjs";
import { bible_glyph_chapter_ezk18 } from "./bible_glyph_chapter_ezk18.mjs";
import { bible_glyph_chapter_jdg13 } from "./bible_glyph_chapter_jdg13.mjs";
import { bible_glyph_chapter_exo20 } from "./bible_glyph_chapter_exo20.mjs";
import { bible_glyph_chapter_ezk33 } from "./bible_glyph_chapter_ezk33.mjs";
import { bible_glyph_chapter_deu30 } from "./bible_glyph_chapter_deu30.mjs";
import { bible_glyph_chapter_psa138 } from "./bible_glyph_chapter_psa138.mjs";
import { bible_glyph_chapter_psa029 } from "./bible_glyph_chapter_psa029.mjs";
import { bible_glyph_chapter_psa136 } from "./bible_glyph_chapter_psa136.mjs";
import { bible_glyph_chapter_1jn03 } from "./bible_glyph_chapter_1jn03.mjs";
import { bible_glyph_chapter_1jn05 } from "./bible_glyph_chapter_1jn05.mjs";
import { bible_glyph_chapter_1jn01 } from "./bible_glyph_chapter_1jn01.mjs";
import { bible_glyph_chapter_jhn14 } from "./bible_glyph_chapter_jhn14.mjs";
import { bible_glyph_chapter_jhn03 } from "./bible_glyph_chapter_jhn03.mjs";
import { bible_glyph_chapter_jhn01 } from "./bible_glyph_chapter_jhn01.mjs";
import { bible_glyph_chapter_1jn04 } from "./bible_glyph_chapter_1jn04.mjs";
export function bible_glyph_chapters() {
  "Every picture Bible chapter written so far, given as its chapter code and its shorthand.";
  "THE FOURTH WAS MEASURED AGAINST FOUR OTHERS rather than measured alone, which is the step past what the third one did. John three was asked of the table and the answer was taken; John fourteen was picked because five candidates were asked and it came back highest, and because its gaps turned out to be grammar rather than vocabulary. A single measurement tells you whether one chapter is thin. Comparing them is what actually chooses.";
  "THE FIFTH WAS MEASURED AGAINST ELEVEN OTHERS AND THE MEASURING COST ONE CALL, which is the step past what the fourth one did. Choosing the fourth meant running the one-chapter reading five times by hand and writing five shares down; a command that takes a whole shortlist was built first this time, so the first letter of John was picked out of twelve candidates for the price of asking about one. The next chapter should be chosen from a longer list still, because the list is now the cheap part.";
  "AND IT WAS THE FIRST ONE CHOSEN PARTLY FOR BEING SHORT. Ten verses at the top of the shortlist beat a chapter half again as drawable at fifty verses, because what gets finished is what gets read, and four of the five chapters here ran long enough to fill a sitting on their own.";
  "THE SIXTH WAS MEASURED AGAINST TWENTY NINE OTHERS, which is the longer list the fifth one's note asked for, and the widening cost nothing because the command already took a whole shortlist. The fifth chapter of the same letter came back highest and shortest of the three at the top, so both of the rules that chose the fifth chose this one too. What has changed is only how many candidates they were applied to.";
  "AND IT COST ONE NEW PICTURE, against three for the chapter before it. That is the table starting to pay back: the words this chapter needed were mostly bought by the five chapters ahead of it, so the sixth was cheaper to draw than the fifth despite being twice as long. A later chapter costing less than an earlier one is the whole argument for a table keyed by root, arriving as a measurement rather than as a claim.";
  "THE SEVENTH WAS MEASURED AGAINST ALL OF THEM, which ends the widening the fifth one's note started. Five candidates chose the fourth, twelve the fifth, thirty the sixth, and every unwritten chapter of the testament chose this one - two hundred and fifty four of them, in two and a half seconds, because the reading was taught to find its own set instead of being handed a list somebody typed. There is no longer a step between one chapter and all of them.";
  "AND THIS LIST IS WHAT MAKES THAT ANSWER USEFUL. A survey of every chapter would otherwise put the six already written at the top of itself forever, since coming top is why they were written; the survey reads this list and leaves them out. A list kept so that nothing has to guess what exists turns out to be the thing that keeps the survey honest as well.";
  "THE EIGHTH IS THE FIRST FROM THE OTHER TESTAMENT, and it is the only entry on this list whose point is not its share. Seven chapters of Greek were written before a word of Hebrew was, so the Hebrew root table was a promise nobody had cashed: the same pictures over a second set of numbers, so that a reader who learned them in a letter of John can open a psalm and read. The hundred and thirty sixth psalm is that promise cashed, and until it existed the claim was only ever an argument.";
  "AND THE MEASURING CROSSED THE TESTAMENT WITH IT. The seventh was chosen out of every unwritten chapter of the New Testament, two hundred and fifty four of them; the eighth was chosen out of every chapter of the Old, nine hundred and twenty nine. The survey needed nothing added to do it - it takes the testament's name and reads that testament's table - so the widening that ran out of room in the New found a canon three and a half times the size waiting next to it.";
  "THE NINTH IS THE FIRST THAT COST NOTHING TO DRAW. Every chapter before it bought at least one picture - three for the fifth, one for the sixth, one for the eighth - and the twenty ninth psalm bought none: every word it draws was already seated by a chapter ahead of it, and the three it leans on hardest were bought by the psalm written immediately before it. That is the argument for a table keyed by root arriving as a measurement instead of a claim, and it is the first time the number is zero.";
  "AND IT IS THE SECOND FROM THE OLD TESTAMENT, which is what makes the zero mean anything. A ninth chapter of Greek costing nothing would only have said that seven chapters of Greek had covered the Greek. A second chapter of Hebrew costing nothing says the Hebrew table crossed from one psalm to an unrelated one on its own, which is the whole promise the two tables were built to keep.";
  "THE TENTH IS THE ONE THAT PROVES A REFUSAL. The eighth bought the raised hands and a note beside them refused to merge yadah, to give thanks, with yada, to know - two Hebrew words one letter apart. Nothing tested that until the hundred and thirty eighth psalm, which gives thanks three times and knows once, so the two marks stand eight lines apart on one page. A table's careful distinctions are claims until a chapter makes a reader look at them.";
  "AND THREE OF THE TEN ARE NOW PSALMS, which is a fact about the table rather than a taste. The survey ranks by what can be drawn and the table was built out of covenant words - the name, the gift, the glory, the fire - which is what a psalm is made of. The psalter will keep coming top until the words that narrative and law are made of are seated too, so the way to a chapter of Genesis runs through the table and not through the survey.";
  "THE ELEVENTH IS THE FIRST FROM THE LAW, and it is the entry that answers the note above it. That note said the psalter would keep coming top until the words narrative and law are made of were seated, and named that as the way to a chapter outside the psalms. So the table was asked which pictures the Greek side already draws that the Hebrew side had never seated - nineteen of them - and eight turned out to mean the same thing in both languages: the blood, the darkness, the witness, the child, the two negatives, the out-of and the world. None cost a picture. The survey moved the same morning, and Deuteronomy took three of the ten highest places outside the psalter.";
  "AND IT IS THE FIRST TIME THE TABLE WAS GROWN INSTEAD OF THE SURVEY BEING RE-RUN. Every chapter before this one was chosen by asking what was most drawable and taking the answer. This one was reached by changing what drawable means. Those are different acts, and only the second can get you out of a book the table happens to be good at - which is why ten chapters had come from two books and no amount of surveying was going to find an eleventh anywhere else.";
  "THE TWELFTH IS THE FIRST FROM THE PROPHETS, and the books are now four. The eleventh's note said the way out of the psalter runs through the table rather than through the survey, and this one says the same thing about a different kind of word. Eleven chapters had been drawn almost entirely out of covenant vocabulary, so a chapter whose engine is a sword could not be reached at all: the thirty third of Ezekiel says chereb six times, and every one of them would have stood in English inside a line made of pictures. The sword was bought, and the chapter became authorable the same morning.";
  "AND IT IS THE FIRST PICTURE BOUGHT FOR A CONCRETE NOUN. Every glyph before it was seated for something a covenant is made of - the name, the fire, the gift, the heart - or for grammar. Four plain nouns were measured together and two of them could be seated; the other two, the altar and the priest, have no artwork and no honest composition, so they are the first words in this Bible waiting on a picture being drawn rather than found. What this chapter shows is that the two which could be bought were enough to open a book.";
  "AND THE COVENANT NAME WAS HALF BLANK UNTIL THIS CHAPTER LOOKED. The four letters carry two Strong's numbers, and only the first was seated - so wherever the prophets write the Lord GOD, the crown drew and the name beside it stayed in English, three hundred and six times across the testament. Eleven chapters went by without it surfacing because none of them came from the prophets, which is where that phrase lives. A table keyed by number can go blank in a way no survey measures: those three hundred and six words were counted as undrawable vocabulary, which was true of the number and false of the name.";
  "THE THIRTEENTH IS THE FIRST NOT TAKEN OFF THE TOP OF THE SURVEY, and the reason is the only reason that should ever override a measurement here. Every chapter before it was the highest-scoring one available; the twentieth of Exodus was fourth. It is the Ten Commandments, which is the one passage a stranger who has never opened a Bible has still met - so it is the only chapter where a reader with no shared language can be shown the pictures and checked against something they already know. The test this whole project is waiting on needs a chapter like that to exist, and no amount of coverage substitutes for it.";
  "AND IT IS THE CHAPTER WHERE THE TWO REFUSALS COST THE MOST, WHICH IS WHY NEITHER SURVIVED IT. The blessing was blank in the verse that gives the Sabbath its reason and the altar in the three verses the chapter ends on; both had been measured, wanted, and left undrawn on purpose. Writing them out where they hurt is what bought them. Barak became the first word here drawn by two pictures rather than one - the speech and the good sign, to speak good over somebody - and the altar became the first word seated with no picture at all, drawing its own English until somebody makes one. A chapter is a better instrument than a survey for finding what a table is missing, because a survey counts a gap and a chapter makes you read it.";
  "THE FOURTEENTH IS THE FIRST STORY, and thirteen chapters went by without one. Every chapter above it is a psalm, a law, a letter or a prophecy - forms whose sentences could be reordered without a reader losing much. The claim this Bible makes is that somebody with no shared language can follow it, and a psalm only ever hands such a reader a mood. A narrative hands them events in an order, so a reader who takes nothing from a line but the angel, the woman and the fire has still learnt what happened. The strongest form of the claim had never been attempted until the thirteenth of Judges.";
  "AND IT IS THE FIRST TIME A HIGHER SHARE WAS TURNED DOWN FOR A REASON THE SURVEY CANNOT SEE. The twenty sixth of Jeremiah measured slightly higher and is a trial, whose cast is seven proper names - and a proper name is never drawn here, so a stranger meets long blank runs and cannot tell which man is speaking. The share was real and the reading would have been unusable. This chapter's cast is a man, his wife, an angel and a son, and none of them is named until the last verse. The survey counts drawable words; it cannot count whether the people in the story are the kind a picture can draw, and in narrative that is the thing that decides.";
  "AND THE FIFTEENTH IS THE FIRST SECOND CHAPTER IN A BOOK, which is where a root table stops being an argument and starts being a saving. Ezekiel eighteen and Ezekiel thirty three say the same thing twice - turn and live - and the second one needed no new picture at all. The first chapter in a book pays for the vocabulary and every later chapter in it spends what is already there.";
  "THE SIXTEENTH COMPLETES A BOOK, and it is the first entry chosen for what it finishes rather than for what share of it can be drawn. Four chapters of John's first letter were already here and the second was the only gap, so writing it turns fifteen scattered chapters into one whole book a reader can open at the start and read to the end. Every earlier entry was the top of a survey or, twice, a chapter the survey could not judge; none of them changed what the collection IS.";
  "AND THE SURVEY WAS STILL ASKED FIRST, which is what keeps the reason above from being an excuse to stop measuring. Two hundred and fifty three unwritten chapters were ranked and this one came back one point off the highest, so completing the book cost nothing that could be counted. That is a tie-break and not an override, and the difference matters: a reason the survey cannot see is exactly the kind that would let a chapter be chosen by taste and called strategy.";
  "AND A WHOLE BOOK IS THE FIRST THING HERE THAT TESTS THE PICTURES ACROSS AN ARGUMENT. Scattered chapters test whether a passage carries. A book is one writer turning the same few words over for five chapters, so the light and the darkness a reader meets in the first chapter come back in the second as the thing the whole letter turns on - and whether the marks hold their meaning over that distance is a question no single chapter can put.";
  "THE SEVENTEENTH IS THE FIRST CHAPTER CHOSEN TO SPEND A PICTURE BOUGHT THE SAME HOUR. The twenty third psalm was asked for, its four words were measured, and one of them - the sheep - turned out to be worth a mark while the shepherd needed none and the rod and the staff had to be refused. The survey was then re-run against the grown table and the hundredth psalm came back third of nine hundred and twenty one, holding the sheep in its third verse. So the purchase and its first use are one commit apart, which is the shortest a claim about a picture has ever had to wait to be checked.";
  "AND IT IS THE FIRST PAIR IN THIS LIST WHERE ONE CHAPTER FINISHES THE OTHER'S SENTENCE. The twenty third has the LORD as one man's shepherd and the hundredth has the nation as His flock, the same animal at both scales - and because the shepherd is drawn as the human and the sheep together, a reader who has met either verse is looking at half of the other. The twenty third is not written yet and does not have to be for that to be true, because the mark carries it rather than the chapter.";
  "THE EIGHTEENTH IS THE CHAPTER THE SEVENTEENTH WAS BOUGHT FOR, AND IT ARRIVED ONE COMMIT LATE ON PURPOSE. The twenty third psalm asked for four pictures, was told it could have one, and then had to wait while the hundredth psalm proved that one was worth having. So the pair above closed from the other end: the promise in the seventeenth entry that the twenty third need not be written for the mark to carry is now a promise that was kept and can be checked by reading both.";
  "AND IT IS THE FIRST CHAPTER WHOSE MOST FAMOUS VERSE DRAWS NOTHING. The table, the enemies, the oil, the cup running over - five words a reader could recite and not one of them seated, so the fifth verse sits in plain English between two marked ones. That is the clearest thing this list contains about what the project is: the marks follow the root table and not the imagery, and a chapter that drew where the pictures were vivid would be illustrating rather than glossing.";
  "THE NINETEENTH IS THE FIRST WHOLE BOOK, AND IT IS ONE CHAPTER LONG. The sixteenth entry completed a book too, and it took five chapters and five sittings to do it; the second letter of John is thirteen verses, so the book and the chapter are the same object and a reader gets a complete piece of the Bible in one file. What that buys is the only thing a scattered chapter cannot: a reader who has finished it has finished something, rather than having stopped.";
  "AND IT COST NOTHING BECAUSE THE SAME MAN WROTE THE FIVE CHAPTERS ABOVE IT. The ninth entry was the first chapter to buy no picture and the note beside it says a table keyed by root is proved by a measurement rather than a claim. This is that measurement taken along a new axis - not a second chapter inside a book, but a second BOOK by one writer, turning over the same truth and love and walking and commandment. The saving follows the hand that wrote, and not only the scroll it was written on.";
  "THE TWENTIETH IS THE SECOND WHOLE BOOK IN A ROW, AND THE SECOND FOR NOTHING. The entry above it says a complete book gives a reader something a chapter cannot; two of them side by side give something further, which is a run - finish one and the next is also finishable. And the free cost repeated is the part worth writing down: one chapter costing nothing says the table has begun to pay back, and two whole books in succession costing nothing says paying back is now the ordinary case and buying was the exception.";
  "AND IT IS THE LETTER WITH THREE MEN'S NAMES IN IT AND NOT ONE OF THEM DRAWN. Gaius, Diotrephes and Demetrius stay in English by the rule that turned down the twenty sixth of Jeremiah, and then the seventh verse draws THE Name. So the chapter that most tests the no-proper-names rule is the chapter where that rule says the most.";
  "THE TWENTY FIRST IS THE THIRD WHOLE BOOK IN A ROW AND THE THIRD FOR NOTHING, AND IT IS THE ONE THAT SETTLES THE ARGUMENT. The two entries above it are the two shortest books in the New Testament, so a sceptic could read their free cost as short books being cheap. Jude is nearly twice the length of either and goes where neither goes - angels, the sea, Egypt, the last judgment - and it still asked for no picture at all. Cheapness on unfamiliar ground is a property of the table; cheapness on home ground was only a property of the neighbourhood.";
  "AND ITS FIFTH VERSE PUTS THE CROSS IN THE EXODUS. The Greek there reads Iesous and the sentence is about bringing a people out of Egypt, so the mark that stands beside the man from Nazareth everywhere else in this list stands here beside Sinai. Nothing was smoothed to spare the reader that, because the rule is that the mark is drawn where the word is. It is the first place in this Bible where the pictures walk a reader into a hard reading rather than around it.";
  "THE TWENTY SECOND IS THE FIRST CHAPTER A PICTURE WAS BOUGHT FOR BEFORE THE CHAPTER WAS THOUGHT OF. The note beside the shepherd and the sheep in the Greek table has said since the day they were borrowed that a reader who learns the ewe in the psalms meets the same animal in the tenth of John. Two psalms were written on the strength of that sentence and this is the other end of it: the twenty third has the LORD as one man's shepherd, the hundredth has the nation as His flock, and the eleventh verse here says I am the good shepherd in the same two marks. The eighteenth entry says a promise about a mark can be kept a commit later; this one was kept a fortnight later and across a testament.";
  "AND IT WAS NINTH ON THE SURVEY, WHICH IS THE SECOND TIME A HIGHER SHARE WAS TURNED DOWN. The thirteenth entry reached past three chapters for the Ten Commandments and its note says what makes such a reach honest - the measurement is asked first and out loud, and the reason given is one the measurement could not have found. Four of the eight chapters above this one are the Revelation, whose share comes from a vocabulary of thrones and lamps this table has barely seated, and none of the eight cashes a promise the table had already made in writing. A survey cannot rank a promise, because it cannot read one.";
  "AND THE CHAPTER FOUND A BLANK OF THE KIND NO SURVEY MEASURES, WHICH IS NOW THE THIRD. Psuche had no row in the Greek table at all while nephesh had been seated on the person since the Hebrew table was written, so the good shepherd laying down his life stood in plain English three times over. The covenant name was half seated the same way for three hundred and six verses of the prophets. A share counts those occurrences as vocabulary that cannot be drawn, which is true of the number and false of the word - and only a chapter makes somebody read the line.";
  "THE TWENTY THIRD IS THE FIRST CHAPTER WHERE THE SUBJECT AND THE PROJECT ARE THE SAME THING. Every entry above had to argue its pictures against its content; the ninth of John is about a man who could not see and then could, and it is being drawn for a reader who cannot read the words. That is not why it was taken. The survey was asked first, over all two hundred and forty eight unwritten New Testament chapters, and this came back tied at the very top - and three of the four tied with it were turned down: two Revelations, for the reason the twenty second entry already gives, and the fourth of John for being fifty four verses, half again longer than anything here. So the measuring picked the shortlist and the reading picked from the shortlist, which is the order this list has used since the thirteenth.";
  "AND ITS CAST IS THE STRONGEST CASE YET FOR THE NO PROPER NAMES RULE, because the rule costs it nothing. The fourteenth entry turned down a trial whose cast was seven names; the twentieth wrote a letter with three. Forty one verses here contain two proper names, Siloam and Moses, and everybody else in the story - the blind man, his parents, the Pharisees, the crowd - arrives as a mark a reader has already met. A narrative that needs no names is the narrative this table can draw.";
  "THE TWENTY FOURTH WAS CHOSEN OUT OF NINE MEASURED CHAPTERS AND NOT BY THE NUMBER THEY CAME BACK WITH. Nine unwritten chapters of John were asked of the root table on 2026-08-27 and the answers ran from thirty three to forty one, which is too narrow a band to decide anything with. The seventeenth came second and was taken because its blanks are the article, the pronouns and the particles - the same profile that chose the fourth entry - and because it is twenty six verses where the chapter that led is fifty four. The twenty third entry says a survey picks the shortlist and a reading picks from the shortlist; this is that order used again.";
  "AND IT PAID FOR ITSELF BEFORE A WORD OF IT WAS WRITTEN, WHICH NO EARLIER CHAPTER DID. A chapter that says glorify eight times found the glory row holding the noun alone, so the verb was seated on the same star by the rule the holy row had already used three entries deep - one edit, no picture bought, five more words drawn here and every glorify in the gospel drawn after it. The twenty second entry found a blank by authoring; this one found the blank by counting before it authored, and the cheapest seat this list has recorded was the one an existing row already implied.";
  "AND THE WORD THE PRAYER IS BUILT ON IS STILL IN ENGLISH. Sent carries the whole argument of the chapter and neither Greek verb for it is seated; the artwork set answers send with nothing at all and offers an envelope, which claims a message where the word sends a person. It was left in letters and written down as a hole with a shape, because a chapter that reaches for the nearest wrong picture under time pressure teaches a reader a wrong word for good.";
  "THE TWENTY FIFTH IS JOHN TWENTY, AND IT WAS TAKEN THREE POINTS BELOW WHAT THE SURVEY NAMED BECAUSE THE COLLECTION HAD A HOLE NO SHARE COULD MEASURE. The instrument put the fourth of John at the top with forty one words drawable in a hundred and this one at thirty eight, and the fourth of John had already been turned down here once for its length. Twenty four chapters had been written and not one of them was the resurrection: the letters argue from a risen Christ, and the fourteenth and the seventeenth of John are spoken on the night before He dies, so the event all of them stand on was nowhere in the collection at all. A survey ranks the chapters somebody might author and cannot notice that the one everything else rests on is missing. The subject suits pictures for a second reason, which is that almost nothing in it is argued - a woman walking to a grave in the dark, a stone taken away, two men running, folded cloth lying where a body was, a locked door, a hand put into a wound - and narrative is what this vocabulary draws and argument is what it cannot.";
  "THE TWENTY SIXTH IS THE LONGEST CHAPTER IN THIS BIBLE AND THE THIRD IN A ROW THAT COST NOTHING. Fifty four verses, half again the length of anything above it, and every mark it draws was already seated. The ninth entry recorded a free chapter as a first and the twentieth and twenty first repeated it, but all three were short. A chapter this long asking the table for nothing is a different claim: a short book drawing on a full table shows the table is no longer empty, and a long one shows it is no longer small.";
  "AND ITS SUBJECT IS THE REASON THIS BIBLE IS DRAWN AT ALL. The whole gospel is told, for the first time in John, to a woman outside the covenant who was never taught the words, at a well, in a conversation, by a man who opens by asking her for a drink. That is not why it was taken - nine unwritten chapters of John measured within two points of each other, so the band was noise and the choice was made on what the chapter is rather than on a number. And the eighteenth verse holds a thing the survey could never have seen: the two English mans in this chapter are two different Greek words, the husband and the human being, and the page draws them as two different marks where a translation has to spell them the same.";
  "THE TWENTY SEVENTH IS THE FIRST CHAPTER HERE FROM MATTHEW, MARK OR LUKE. Mark five was chosen because twenty six chapters had been written and every gospel chapter among them came from John, so the table had been bought deep and narrow. A narrative gospel leans on a different vocabulary, and this chapter was the test of whether that vocabulary was already seated. It was: Mark five cost no picture at all, which makes four chapters in a row that cost nothing.";
  "THE TWENTY EIGHTH IS THE FIRST CHAPTER HERE FROM LUKE AND THE FIRST TELLING OF THE BIRTH. Eight candidate chapters were measured before one was chosen, and Luke two scored highest of them all: thirty eight in a hundred of its words were already drawable before a word of it was written. The second half of the reason was that it is the one story a stranger already half knows, so a picture Bible without it is missing the door people walk in through. It cost no new picture, which makes five chapters in a row that cost nothing.";
  "THE TWENTY NINTH IS THE SECOND CHAPTER FROM MARK AND THE FIRST CHOSEN PURELY ON A MEASUREMENT. The same survey that put Luke two first put Mark ten second at thirty six in a hundred, and nothing else was weighed: no story was argued for, no gap in the table was being filled. It cost no new picture, which makes six chapters in a row that cost nothing, and that run is now long enough to be a finding rather than a streak. The table is deep enough that an ordinary gospel chapter of conversation draws itself, and the next chapter that costs a picture will be telling us something about its subject rather than about the table.";
  "THE THIRTIETH IS LUKE SEVEN, CHOSEN BY THE SAME SURVEY AND COSTING NOTHING AGAIN. Seven chapters running have now needed no new picture, and this one is the clearest evidence that the run is about the table rather than about the chapters being picked to fit it. Luke seven wanted a sinner, a person declared right, a friend and a man under authority, and every one of those marks was already bought, each for a different chapter and a different reason. The interesting question has flipped: it is no longer what a chapter will cost, it is which chapter finally asks for something the table does not have.";
  "THE THIRTY FIRST IS MARK ELEVEN, AND IT IS THE FIRST CHAPTER THE SURVEY COULD NOT DECIDE ON ITS OWN. Two hundred and forty unwritten chapters of the New Testament were measured and the top sixteen shares came back bunched between forty one and thirty eight in a hundred, which is inside the noise of how one interlinear happens to gloss a word. So the number picked the shortlist and a reading picked the chapter: the undrawn words of Mark eleven are pronouns, prepositions, the marks the interlinear uses for a gap, and three place names, leaving five real words of vocabulary of which one is supplied by a translator. That reading is what actually predicts the cost, and the share is only what narrows the field to sixteen. It cost no new picture, which is eight chapters running that have cost nothing.";
  "THE THIRTY SECOND IS MARK TWELVE, AND IT IS HERE BECAUSE IT FINISHES A SCENE RATHER THAN BECAUSE IT SCORED. Mark eleven left the question about authority hanging in the temple courts, and Mark twelve is the answer given to the same men in the same place on the same day, so a reader who has just finished the eleventh needs nothing explained to walk into the twelfth. Two chapters running that hold together are worth more to a reader with no English than two unrelated chapters that each measured slightly better. Thirty nine words in a hundred were already drawable and no new picture had to be bought, which is nine chapters in a row costing nothing. It also carries the first verse in this Bible that draws nothing at all, the tenth, which is the psalm about the stone the builders rejected, and the largest stack of negations met so far, five of them in the fourteenth, none of which are drawn.";
  "THE THIRTY THIRD IS LUKE FIFTEEN, AND IT WAS TAKEN OVER THE CHAPTER THAT WOULD HAVE CONTINUED THE ONE BEFORE IT. Mark thirteen carries on from Mark twelve exactly as Mark twelve carried on from Mark eleven, and it measured thirty two words drawable in a hundred against Luke fifteen at thirty three, so the numbers said nothing. What decided it was what the two chapters are made of. Mark thirteen is the discourse about the end, and almost nothing in it is a thing a picture can be of; Luke fifteen is three stories about losing something and finding it, made of sheep, coin, son, father, pigs, ring, robe and feast. So a chapter was turned down for its genre while its score stood level, which is the first time a reading has overruled a tie here rather than broken one. It cost no new picture, which is ten chapters in a row costing nothing.";
  "THE THIRTY FOURTH IS GENESIS ONE, AND IT IS THE FIRST CHAPTER OF THE BIBLE ARRIVING THIRTY FOURTH. Every chapter before it was chosen by what the table could draw, and the first page of the Bible was never top of that reading - thirty five words drawable in a hundred, squarely mid-range, with its commonest undrawn entries being the interlinear dash and the phrase after their kind rather than a missing vocabulary. So it was taken on a different ground: a picture Bible without the chapter a stranger opens first is missing the one page everybody already knows, and its content is concrete nouns, which is the best case pictures have. That is the second time a reading has been overruled here, and the first time the reason was the reader rather than the genre.";
  ("AND IT COST THREE PICTURES, AFTER SIX CHAPTERS IN A ROW COSTING NOTHING. The fish, the bird and the tree had no mark before it, and a moon was seated in the table beside them and goes undrawn, because Genesis one says the lesser light and never says moon - so the table grew by four and the chapter cost three, and it is the drawn one that is the cost. Ask ",
    fn_name("bible_glyph_chapters_pictures_bought"),
    " for those two numbers rather than counting them here, because a hand count of them goes stale in silence. A run of chapters costing nothing is the table paying back what the early chapters bought; a chapter that costs anything is the table meeting a part of the Bible the covenant words never reached. Creation is made of animals and plants and the table was built out of the name, the gift, the glory and the fire.");
  ("THE THIRTY FIFTH IS MATTHEW FIVE, AND IT IS THE FIRST CHAPTER OF MATTHEW ARRIVING THIRTY FIFTH. Four gospels were in the collection and only three of them had ever been opened - John eight times, Mark four, Luke three, Matthew not once. Nothing decided that: every chapter until here was chosen by what the table could already draw, and the first gospel simply never came out on top. So this one was taken against the number rather than by it. Seven candidates were measured before any of them was opened, and Luke twenty four drew thirty seven words in a hundred, Mark one thirty five, Revelation twenty one thirty two, and this drew thirty. It was taken anyway for what its blanks ARE: the commonest undrawn entries are the dash the interlinear writes where English says nothing, the article, and the pronouns you and your, and none of those is vocabulary and none of them will ever be a picture. A chapter whose gaps are the small words reads far better than its share says. That is the third time a reading has overruled the measurement here, after the genre and after the reader, and this time the ground was a whole book of the Bible being absent from a picture Bible. It cost no new picture and it seated one word: blessed, which opens nine verses running and had stood here in plain letters, is drawn as the gift and the smile, two marks a reader has already met and each honest on its own.");
  ("THE THIRTY SIXTH IS MARK FOUR, AND IT WAS TAKEN FOR WHERE ITS UNDRAWN WORDS FALL RATHER THAN FOR HOW MANY THERE ARE. It measured thirty four words drawable in a hundred and John fifteen measured thirty three, which decides nothing. What decided it is that the undrawn words of Mark four are the furniture of the parable - seed, sower, thorn, root, lamp, sickle, boat - while the words the parable is about are every one of them seated: word, hear, ear, soil, good, yield, understand, turn. John fifteen is that same measurement inverted, with vine, branch, fruit and remain all four undrawn, so its whole central image would have been spelled out while its grammar drew itself. A share counts undrawn words and cannot tell what a chapter is about from what it is furnished with, and that reading is what the share needs beside it. It cost no new picture.");
  ("THE THIRTY SEVENTH IS MARK EIGHT, AND IT WAS TAKEN OVER A CHAPTER THAT MEASURED HIGHER, ON THE SAME READING THAT CHOSE THE THIRTY SIXTH. The second of First Corinthians came back forty one words drawable in a hundred and Mark eight came back forty, so the share alone would have taken the letter. What the share cannot see is that the word First Corinthians two repeats most is wisdom, and wisdom is undrawn, along with mind, thoughts and rulers - the chapter is about wisdom and would have spelled the word out in letters on every line while its grammar drew itself. Mark eight is the opposite: its blanks are Peter, Herod, Elijah, Satan, the Pharisees, the scribes, and the fish, leaven, baskets and trees the story is furnished with, while bread, see, hear, understand, heart, spirit, life, Son, Man, Christ, God, glory, holy and follow are every one of them seated. That is now twice running that where the blanks fall has overruled how many of them there are, and it is the reading this list asks for beside every share. It cost no new picture.");
  ("THE THIRTY EIGHTH IS JOHN TWO, AND IT WAS TAKEN BY THE MEASUREMENT WITHOUT AN ARGUMENT AGAINST IT. Four hundred and thirty words and thirty seven drawable in a hundred, above Mark four at thirty four and Luke fifteen at thirty three, both of which are already in this list. What the number does not say is what the chapter gives: believe in the eleventh verse and entrust in the twenty fourth are one Greek word and take one mark, so the reader of the pictures watches it close on they trusted Him and He did not trust them, where English spends two unrelated words and the answering shape is lost. The sixteenth verse says house twice, where English says house and then marketplace. It cost no new picture.");
  ("THE THIRTY NINTH IS LUKE TWENTY FOUR, AND IT IS THE CHAPTER THIS LIST ITSELF WROTE DOWN AND THEN DID NOT TAKE. The thirty fifth entry above says that Luke twenty four drew thirty seven words in a hundred, the highest of the seven it measured, and then took Matthew five instead, because a whole gospel was missing from the collection and no share can measure a missing book. That reason was good and it did not expire with the measurement: asked again four entries later this chapter still comes back at thirty seven, level with John eleven and above the four others measured beside it. It was taken over John eleven on size and on subject - fifty three verses against fifty seven, and a man raised who will die again against the one the whole book turns on. Of the thirty commonest words the table cannot draw here, only six are vocabulary at all; the rest are the gap marks the interlinear leaves, the article, the pronouns, the prepositions, the connectives and the name of a city. It cost no new picture. And it is the second resurrection in the collection and the first one that argues: John twenty was taken for being narrative, which is what these pictures draw, while the road to Emmaus and the risen Christ beginning at Moses to show that all the Scriptures were about Himself is the claim this project makes about itself, said inside the book.");
  ("Thirty nine chapters today, and the list is here rather than the chapters being found by name so that nothing has to guess what exists. A reader asking what this Bible contains gets an answer instead of a search.");
  ("THE FIRST IS FIRST JOHN FOUR, AND IT WAS PICKED BY READING BECAUSE THERE WAS NOTHING YET TO MEASURE WITH. The root table every later entry is measured against did not exist, so the passage was chosen for being the densest love passage in the New Testament: the one picture this whole project started from is a red heart for agape, and if a picture Bible can be read anywhere it can be read here. That is a test rather than a taste - a specimen placed where the odds are best fails informatively if it fails at all. It began at verses seven to twelve and was carried out to both ends of the chapter afterwards, and those six verses were left exactly as they were first written, because a specimen tidied to match what came later stops being evidence of anything. It leaves the grammar in English, and the entry below it is the answer to that.");
  ("THE SECOND IS THE WHOLE OF JOHN ONE, AND IT IS HERE SO THAT THE FIRST CAN BE CHECKED. One chapter proves that a passage can be drawn and cannot prove that a picture means the same thing twice, because there is nothing to hold it against. This passage shares almost nothing with first John four except its vocabulary - another subject, another kind of sentence - so a reader who learned a mark in the first entry either recognises it here or does not, and that is the first real test this project ran. It is also the first chapter to draw the grammar: the pictures for and, in and not were bought between the two, and this is the first passage authored after they existed. The older chapter was deliberately not tidied to match, because two chapters drawn the same way answer nothing while two drawn differently let a reader say which one they could actually read.");
  ("THE THIRD WAS CHOSEN BY MEASURING RATHER THAN BY READING, which is the change worth noticing about this list. The first two were picked because somebody thought they would draw well; John three was asked of the root table before a word of it was authored, and the table answered with a share and with the words it could not draw. That is repeatable by anyone, so the fourth chapter need not be a matter of taste either.");
  ("THEY ARE IN THE ORDER THEY WERE WRITTEN and deliberately not in the order of the Bible. The second chapter draws the grammar words and the first does not, so reading them in this order is reading the project's two lanes in the order they were tried - and a reader who meets the newer one second meets it as an answer to the older one rather than as an unexplained difference.");
  ("The chapters stay one function each rather than one large one, because a chapter is what a person authors in a sitting and what a peer reviews in a sitting, and two people writing two chapters should never be editing the same file.");
  ("A CHAPTER NAMED HERE IS HALF THE WORK AND THE OTHER HALF IS ONE COMMAND. A new entry owes the count in the sentence above, the light list of chapters, both of the chains that send for one chapter on its own, a Rosetta band, that band named in the register beside it, and every reveal language refetched. Not one of those is authored - every word of all of them is already spelled here or in a chapter file - which is why they are commands rather than instructions. None of that is optional and none of it is visible from this file, so it has twice been found by a gate going red rather than by anybody remembering it - and once by a person reconstructing three arguments the writer never wrote down. That is why the four are now run by one command rather than named here in an order a reader has to keep: the order was the last part of the procedure still written as a sentence, and a sentence is the part that gets skipped. After adding a chapter to this list, hand its code to:");
  fn_name("bible_glyph_chapter_added_write");
  let first = bible_glyph_chapter_1jn04();
  let second = bible_glyph_chapter_jhn01();
  let third = bible_glyph_chapter_jhn03();
  let fourth = bible_glyph_chapter_jhn14();
  let fifth = bible_glyph_chapter_1jn01();
  let sixth = bible_glyph_chapter_1jn05();
  let seventh = bible_glyph_chapter_1jn03();
  let eighth = bible_glyph_chapter_psa136();
  let ninth = bible_glyph_chapter_psa029();
  let tenth = bible_glyph_chapter_psa138();
  let eleventh = bible_glyph_chapter_deu30();
  let twelfth = bible_glyph_chapter_ezk33();
  let thirteenth = bible_glyph_chapter_exo20();
  let fourteenth = bible_glyph_chapter_jdg13();
  let fifteenth = bible_glyph_chapter_ezk18();
  let sixteenth = bible_glyph_chapter_1jn02();
  let seventeenth = bible_glyph_chapter_psa100();
  let eighteenth = bible_glyph_chapter_psa023();
  let nineteenth = bible_glyph_chapter_2jn01();
  let twentieth = bible_glyph_chapter_3jn01();
  let twenty_first = bible_glyph_chapter_jud01();
  let twenty_second = bible_glyph_chapter_jhn10();
  let twenty_third = bible_glyph_chapter_jhn09();
  let twenty_fourth = bible_glyph_chapter_jhn17();
  let twenty_fifth = bible_glyph_chapter_jhn20();
  let twenty_sixth = bible_glyph_chapter_jhn04();
  let twenty_seventh = bible_glyph_chapter_mrk05();
  let twenty_eighth = bible_glyph_chapter_luk02();
  let twenty_ninth = bible_glyph_chapter_mrk10();
  let thirtieth = bible_glyph_chapter_luk07();
  let thirty_first = bible_glyph_chapter_mrk11();
  let thirty_second = bible_glyph_chapter_mrk12();
  let thirty_third = bible_glyph_chapter_luk15();
  let thirty_fourth = bible_glyph_chapter_gen01();
  let thirty_fifth = bible_glyph_chapter_mat05();
  let thirty_sixth = bible_glyph_chapter_mrk04();
  let thirty_seventh = bible_glyph_chapter_mrk08();
  let thirty_eighth = bible_glyph_chapter_jhn02();
  let thirty_ninth = bible_glyph_chapter_luk24();
  let chapters = [
    first,
    second,
    third,
    fourth,
    fifth,
    sixth,
    seventh,
    eighth,
    ninth,
    tenth,
    eleventh,
    twelfth,
    thirteenth,
    fourteenth,
    fifteenth,
    sixteenth,
    seventeenth,
    eighteenth,
    nineteenth,
    twentieth,
    twenty_first,
    twenty_second,
    twenty_third,
    twenty_fourth,
    twenty_fifth,
    twenty_sixth,
    twenty_seventh,
    twenty_eighth,
    twenty_ninth,
    thirtieth,
    thirty_first,
    thirty_second,
    thirty_third,
    thirty_fourth,
    thirty_fifth,
    thirty_sixth,
    thirty_seventh,
    thirty_eighth,
    thirty_ninth,
  ];
  return chapters;
}
