export function bible_glyph_chapter_gen15() {
  "The fifteenth chapter of Genesis, drawn in pictures. God promises a childless man more descendants than he can count, the man believes it, and God cuts a covenant with him in the dark.";
  "THE SUN GOING IN AND A MAN GOING TO HIS FATHERS ARE ONE WORD, AND THE PICTURE SHOWS IT THREE TIMES. The Hebrew verb bo means to come in or go in, and the root table draws it as footprints. It falls three times on this page. In the twelfth verse the sun goes in and Abram falls into a deep sleep. In the fifteenth God tells him you will go in to your fathers in peace and be buried at a good old age. In the seventeenth the sun has gone in and it is dark. English writes setting, go, and set, which are three different words, so an English reader has no way of noticing that the chapter frames a man's death with two sunsets using one verb for all three. In pictures the same footprints come back and the frame is impossible to miss.";
  "THE SON MARK FALLS TWICE ON THIS PAGE AND NEITHER TIME IS IT HIS SON. Abram's complaint in the second and third verses is that he has no child, and yet the son mark appears in both of those verses. In the second it is the heir of my house, which in Hebrew is a son of possession; in the third it is a servant in my household, which is a son of my house. English writes heir and servant and hides the word completely. Then in the fourth verse, where God finally speaks of the real child - one who comes from your own body - the son mark is not there at all, because Hebrew does not use the word. So the picture of a son shows up twice for the two men who are not the son, and stays away from the promise itself.";
  "THE ANCHOR LANDS HERE ON THE ONE VERSE THE NEW TESTAMENT ARGUES FROM. The sixth verse is five words long in Hebrew and it carries two marks: Abram believed the LORD, and it was credited to him as righteousness. Believing is the anchor and righteousness is the measuring ruler. That single verse is what Paul builds a whole argument on twice over, and a reader coming to this list from the Greek chapters has seen the anchor on page after page without ever seeing the sentence those pages are arguing from. Here it is, on a man who has been given nothing yet except a sentence, standing outside at night counting stars he cannot count.";
  "THE WORD FOR CREDITED IN THE SIXTH VERSE IS THE WORD FOR THOUGHTS IN ISAIAH, AND THE TABLE DRAWS NEITHER. Hebrew chashav is to reckon, to count something as something, to think. The noun made from it is the word Isaiah uses in the fifty fifth chapter for My thoughts are not your thoughts. So the thing God does with Abram's faith here is the same thing the word for God's thinking is made of - He counts it, He reckons it so. The root table seats neither the verb nor the noun, so the most important word in the verse stands in plain letters on this page and its noun stands in plain letters five times on that one. A reader following the pictures gets believing and righteousness and has to take on trust the word joining them, which is the one word the whole argument turns on.";
  "KNOW FOR CERTAIN IS THE WORD KNOW WRITTEN TWICE. In the thirteenth verse the Hebrew says know, know, and English has no way to write that, so it writes know for certain and turns the second word into an adverb. The root table has a lamp for knowing, so on this page the two lamps come back and stand side by side. The third of Exodus and the fifty fifth of Isaiah both do the same thing on this list - Hebrew doubles a verb to lean on it, English turns the doubled word into an extra adverb, and pictures put the doubling straight back where it was. Here it is the strongest thing God says all chapter, and it is introducing four hundred years of slavery.";
  "THE FIRST VERSE USES ONE WORD TWICE AND ENGLISH WRITES EVENTS AND WORD. After these events, the word of the LORD came to Abram. Both of those are davar, and the root table draws it as speech, so the verse opens with the same mark twice in eight words. Hebrew uses one noun for a thing said and a thing that happened, which is a whole way of seeing the world folded into a single word, and English has to choose one of the two meanings every time it meets it. The picture does not have to choose.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "GEN15",
    reference: "Genesis 15",
    verses: [
      {
        verse_number: 1,
        words: [
          "After",
          "these",
          "$speech,",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag",
          "came",
          "to",
          "Abram",
          "in",
          "a",
          "vision:",
          "Do",
          "$no_entry",
          "be",
          "afraid,",
          "Abram.",
          "I",
          "am",
          "your",
          "shield,",
          "your",
          "very",
          "great",
          "reward.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "But",
          "Abram",
          "$speech,",
          "O",
          "$crown",
          "$name_tag,",
          "what",
          "can",
          "You",
          "$hands_giving",
          "me,",
          "since",
          "I",
          "$walking",
          "childless,",
          "and",
          "the",
          "$son",
          "of",
          "my",
          "$house",
          "is",
          "Eliezer",
          "of",
          "Damascus?",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Abram",
          "$speech,",
          "Behold,",
          "You",
          "have",
          "$hands_giving",
          "me",
          "$no_entry",
          "offspring,",
          "so",
          "a",
          "$son",
          "in",
          "my",
          "$house",
          "will",
          "be",
          "my",
          "heir.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Then",
          "the",
          "$speech",
          "of",
          "the",
          "$name_tag",
          "came",
          "to",
          "Abram,",
          "$speech,",
          "This",
          "one",
          "will",
          "$no_entry",
          "be",
          "your",
          "heir,",
          "but",
          "one",
          "who",
          "comes",
          "from",
          "your",
          "own",
          "body",
          "will",
          "be",
          "your",
          "heir.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "And",
          "the",
          "LORD",
          "took",
          "him",
          "outside",
          "and",
          "$speech,",
          "Now",
          "look",
          "to",
          "the",
          "$sky",
          "and",
          "count",
          "the",
          "stars,",
          "if",
          "you",
          "are",
          "able.",
          "Then",
          "He",
          "$speech",
          "him,",
          "So",
          "shall",
          "your",
          "offspring",
          "be.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Abram",
          "$anchor",
          "the",
          "$name_tag,",
          "and",
          "it",
          "was",
          "credited",
          "to",
          "him",
          "as",
          "$ruler.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "also",
          "$speech",
          "him,",
          "I",
          "am",
          "the",
          "$name_tag,",
          "who",
          "brought",
          "you",
          "out",
          "of",
          "Ur",
          "of",
          "the",
          "Chaldeans",
          "to",
          "$hands_giving",
          "you",
          "this",
          "$earth",
          "to",
          "possess.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "But",
          "Abram",
          "$speech,",
          "$crown",
          "$name_tag,",
          "how",
          "can",
          "I",
          "$lightbulb",
          "that",
          "I",
          "will",
          "possess",
          "it?",
        ],
      },
      {
        verse_number: 9,
        words: [
          "And",
          "the",
          "LORD",
          "$speech",
          "to",
          "him,",
          "$hand_receiving",
          "Me",
          "a",
          "heifer,",
          "a",
          "goat,",
          "and",
          "a",
          "ram,",
          "each",
          "three",
          "years",
          "old,",
          "along",
          "with",
          "a",
          "turtledove",
          "and",
          "a",
          "young",
          "pigeon.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "So",
          "Abram",
          "$hand_receiving",
          "all",
          "these",
          "to",
          "Him,",
          "split",
          "each",
          "of",
          "them",
          "down",
          "the",
          "middle,",
          "and",
          "$hands_giving",
          "the",
          "halves",
          "opposite",
          "each",
          "other.",
          "The",
          "birds,",
          "however,",
          "he",
          "did",
          "$no_entry",
          "cut",
          "in",
          "half.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "And",
          "the",
          "birds",
          "of",
          "prey",
          "descended",
          "on",
          "the",
          "carcasses,",
          "but",
          "Abram",
          "drove",
          "them",
          "away.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "As",
          "the",
          "sun",
          "was",
          "$footprints,",
          "Abram",
          "fell",
          "into",
          "a",
          "deep",
          "sleep,",
          "and",
          "suddenly",
          "great",
          "terror",
          "and",
          "darkness",
          "overwhelmed",
          "him.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Then",
          "the",
          "LORD",
          "$speech",
          "to",
          "Abram,",
          "$lightbulb",
          "$lightbulb",
          "that",
          "your",
          "descendants",
          "will",
          "be",
          "strangers",
          "in",
          "a",
          "$earth",
          "that",
          "is",
          "$no_entry",
          "their",
          "own,",
          "and",
          "they",
          "will",
          "be",
          "$kneeling",
          "and",
          "mistreated",
          "four",
          "hundred",
          "years.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "But",
          "I",
          "will",
          "judge",
          "the",
          "$map",
          "they",
          "$kneeling,",
          "and",
          "afterward",
          "they",
          "will",
          "depart",
          "with",
          "many",
          "possessions.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "You,",
          "however,",
          "will",
          "$footprints",
          "to",
          "your",
          "$father",
          "in",
          "peace",
          "and",
          "be",
          "buried",
          "at",
          "a",
          "$thumbs_up",
          "old",
          "age.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "In",
          "the",
          "fourth",
          "generation",
          "your",
          "descendants",
          "will",
          "$turn_back",
          "here,",
          "for",
          "the",
          "iniquity",
          "of",
          "the",
          "Amorites",
          "is",
          "$no_entry",
          "yet",
          "complete.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "When",
          "the",
          "sun",
          "had",
          "$footprints",
          "and",
          "darkness",
          "had",
          "fallen,",
          "behold,",
          "a",
          "smoking",
          "firepot",
          "and",
          "a",
          "flaming",
          "torch",
          "appeared",
          "and",
          "passed",
          "between",
          "the",
          "halves.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "On",
          "that",
          "$sun",
          "the",
          "$name_tag",
          "made",
          "a",
          "covenant",
          "with",
          "Abram,",
          "$speech,",
          "To",
          "your",
          "descendants",
          "I",
          "have",
          "$hands_giving",
          "this",
          "$earth,",
          "from",
          "the",
          "river",
          "of",
          "Egypt",
          "to",
          "the",
          "great",
          "River",
          "Euphrates:",
        ],
      },
      {
        verse_number: 19,
        words: [
          "the",
          "land",
          "of",
          "the",
          "Kenites,",
          "Kenizzites,",
          "Kadmonites,",
        ],
      },
      {
        verse_number: 20,
        words: ["Hittites,", "Perizzites,", "Rephaites,"],
      },
      {
        verse_number: 21,
        words: [
          "Amorites,",
          "Canaanites,",
          "Girgashites,",
          "and",
          "Jebusites.",
        ],
      },
    ],
  };
  return chapter;
}
