import { fn_name } from "./fn_name.mjs";
export function bible_word_section_marks_welded_spellings() {
  "Every spelling in the chapters this repo can show where a Hebrew paragraph mark is welded onto the end of the word instead of standing beside it, with its chanting marks already taken off.";
  "★ IT IS A LIST RATHER THAN A RULE BECAUSE NO RULE CAN READ THE WORD ALONE. The open mark gives itself away, since a word ending in that letter is written in its final shape and this one is not; the closed mark does not, because that letter ends real words every day - a cup is spelt with it. Only the transliteration beside each word can tell the two apart, and the reader's finger hands over a word with no transliteration attached.";
  "★ IT IS WRITTEN OUT RATHER THAN FETCHED BECAUSE THE PAGE RUNS IN A BROWSER, where there is no file to read; and both the recorder and the tap have to reach the same answer or the tap asks storage for a clip nobody made.";
  ("Every entry was found by ",
    fn_name("bible_interlinear_section_marks_welded"),
    ", which keeps a word only when the record's own transliteration says the mark's sound is not there - so each one is proved by the hand that wrote it, not by a guess about Hebrew.");
  ("IT GOES STALE WHEN A NEW CHAPTER IS GLOSSED, and a stale entry is silent: the word is simply said wrong. Run that command again after adding chapters and write what it finds back here.");
  let spellings = [
    "אֲבִיכֶםפ",
    "אַבְרָהָםס",
    "אֱדוֹםס",
    "אֱדוֹםפ",
    "אֶחָדפ",
    "אֲחוֹתֵנוּפ",
    "אֶחָיופ",
    "אֱלֹהִיםס",
    "אֱלֹהִיםפ",
    "אִמּוֹפ",
    "אִתּוֹפ",
    "אֹתָםפ",
    "בְּגוֹיֵהֶםס",
    "בָהּס",
    "בְּחָרָןס",
    "בְּיִשְׂרָאֵלס",
    "בָּכוּתפ",
    "בָּךְס",
    "בָּנָיופ",
    "הָאָרֶץפ",
    "הָאֹתֹתפ",
    "הַבְּכֹרָהס",
    "הִבָּרְאָםס",
    "הַזֶּהס",
    "הַחַיִּיםס",
    "הַטַּבָּחִיםפ",
    "הַיְבוּסִיס",
    "הַיּוֹםס",
    "הַמַּבּוּלפ",
    "הַמִּטָּהפ",
    "הַנֶּגְבָּהפ",
    "הֵפַרס",
    "הַשֵּׁםפ",
    "הַשִּׁשִּׁיפ",
    "וּבָנוֹתס",
    "וּבְקַשְׁתִּיפ",
    "וַיַּלְבִּשֵׁםפ",
    "וַיָּמֹתס",
    "וַיָּמֹתפ",
    "וַיִּשְׁכָּחֵהוּפ",
    "וּלְרִבְקָהס",
    "זָרַחס",
    "חֶלְקָםס",
    "חֲמִישִׁיפ",
    "חֵתס",
    "יְהוָהפ",
    "יִשְׂרָאֵלס",
    "כַּפְתֹּרִיםס",
    "לְאַבְרָםס",
    "לְאִשָּׁהס",
    "לַיהוָהפ",
    "לַמּוּלֹתפ",
    "לַעֲשׂוֹתפ",
    "מֵחָלָבפ",
    "מַחֲנָיִםפ",
    "מֶלֶךְס",
    "מַעֲכָהס",
    "מַצְלִיחַס",
    "מִצְרָיְמָהס",
    "מִצְרָיִםפ",
    "נָכְרִיָּהפ",
    "נָפָלפ",
    "סֻכּוֹתס",
    "עֹבֵדס",
    "עָלָהפ",
    "עָקֵבס",
    "עָשָׂהס",
    "צִידֹןס",
    "רֹאִיס",
    "רַבִּיםפ",
    "רְבִיעִיפ",
    "שִׁבְעִיםפ",
    "שָׁבַעפ",
    "שְׁלִישִׁיפ",
    "שֵׁנִיפ",
    "שֵׂעִירפ",
    "שָׁפֶרס",
    "תְּחַיּוּןס",
  ];
  return spellings;
}
