export function bible_glyph_chapter_jhn02() {
  "The thirty eighth picture Bible chapter written by hand: the whole of John two, in the shorthand a person types.";
  "IT WAS CHOSEN BY THE COVERAGE MEASUREMENT AND NOT BY READING IT FIRST. Four hundred and thirty words, of which thirty seven in a hundred are already drawn - above Mark four at thirty four and Luke fifteen at thirty three, both of which are authored chapters. Small enough to finish in one sitting, and the sitting is the unit that matters, because a chapter left half written is a chapter no reader can open.";
  "BELIEVE AND ENTRUST ARE ONE GREEK WORD AND THE ELEVENTH AND TWENTY FOURTH VERSES ARE WHERE THAT SHOWS. His disciples believed in Him, says the eleventh; Jesus did not entrust Himself to them, says the twenty fourth. Both are pisteuo and both take the same mark, so a reader of the pictures watches the chapter close on the sentence English hides: they trusted Him, and He did not trust them. English spends two unrelated words on it and the answering shape disappears. This is the same win the wind and the Spirit gave in John three, arriving on its own without anything being bought.";
  "THE HOUSE IS DRAWN TWICE IN ONE SENTENCE AND THE REPETITION IS THE SENTENCE. The Greek of the sixteenth verse says oikos and then says oikos again - the house of My Father into a house of trade - and English writes house and then writes marketplace, so the two stop being the same thing and the accusation loses its hinge. Two of the same picture side by side put the hinge back, and no footnote was needed to do it.";
  "THE WATER IS DRAWN AND THAT IS NOT THE MISTAKE IT RESEMBLES. A mark stands down where the passage means the very thing the picture shows and the seat is on some other word - fire for God, moving air for the Spirit. Here the seat is on hydor itself, so the drop is water and is standing in for nothing. The test is the number the word carries, never the way the English reads, and this chapter is a good place to say so because water is in it seven times.";
  "THE FURNITURE OF THIS CHAPTER IS ALL IN ENGLISH AND THAT IS THE HONEST RESULT. Wedding, wine, jars, Cana, Galilee, whip, doves, money changers, bridegroom - not one of them drawn. What the pictures fall on is the grammar, the people, and what those people do and know and believe. That is the narrative reading again: a story spends its words on things that happen once, and a root table can only pay for words that come back.";
  "TEMPLE IS THE ONE BLANK IN IT WORTH ARGUING ABOUT. The nineteenth to the twenty first verses turn on the word - destroy this temple, and He was speaking about the temple of His body - and it stands in letters every time. It is not grammar and it is not a proper name, so it is the one content word here that a reader who has no English simply loses. The argument belongs in the root table, where a seat is decided once for the whole Bible, and not in this file, where it would be a decision made per passage.";
  "NOTHING NEW WAS BOUGHT FOR IT. Every mark this chapter draws was already seated for an earlier chapter, so the thirty eighth costs the reader nothing new to learn, and the whole of its work was word order.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "JHN02",
    reference: "John 2",
    verses: [
      {
        verse_number: 1,
        words: [
          "$plus",
          "On",
          "the",
          "third",
          "$sun",
          "a",
          "wedding",
          "took",
          "place",
          "$tray_in",
          "Cana",
          "of",
          "Galilee,",
          "$plus",
          "the",
          "mother",
          "of",
          "$cross",
          "was",
          "there.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$plus",
          "$cross",
          "had",
          "been",
          "invited",
          "to",
          "the",
          "wedding,",
          "$plus",
          "$pointing_back",
          "$learner",
          "as",
          "well.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$plus",
          "when",
          "the",
          "wine",
          "ran",
          "out,",
          "the",
          "mother",
          "of",
          "$cross",
          "$speech",
          "to",
          "$pointing_back,",
          "“They",
          "have",
          "$no_entry",
          "wine.”",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$plus",
          "$cross",
          "$speech",
          "to",
          "$pointing_back,",
          "“$woman,",
          "what",
          "is",
          "that",
          "to",
          "Me",
          "$plus",
          "to",
          "you?",
          "My",
          "hour",
          "has",
          "not",
          "yet",
          "come.”",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$pointing_back",
          "mother",
          "$speech",
          "to",
          "the",
          "servants,",
          "“$hammer",
          "whatever",
          "He",
          "$speech",
          "to",
          "you.”",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Now",
          "six",
          "stone",
          "water",
          "jars",
          "were",
          "standing",
          "there,",
          "for",
          "the",
          "purification",
          "of",
          "the",
          "$menorah,",
          "each",
          "holding",
          "twenty",
          "to",
          "thirty",
          "gallons.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$cross",
          "$speech",
          "to",
          "$pointing_back,",
          "“Fill",
          "the",
          "jars",
          "with",
          "$water.”",
          "$plus",
          "they",
          "filled",
          "$pointing_back",
          "to",
          "the",
          "brim.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$plus",
          "He",
          "$speech",
          "to",
          "$pointing_back,",
          "“Now",
          "draw",
          "some",
          "out",
          "$plus",
          "take",
          "it",
          "to",
          "the",
          "master",
          "of",
          "the",
          "banquet.”",
          "So",
          "they",
          "did.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "master",
          "of",
          "the",
          "banquet",
          "tasted",
          "the",
          "$water",
          "that",
          "had",
          "been",
          "turned",
          "into",
          "wine,",
          "$plus",
          "he",
          "did",
          "$no_entry",
          "$lightbulb",
          "where",
          "it",
          "was",
          "from,",
          "but",
          "the",
          "servants",
          "who",
          "had",
          "drawn",
          "the",
          "$water",
          "did",
          "$lightbulb.",
          "Then",
          "he",
          "called",
          "the",
          "bridegroom",
          "aside",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$plus",
          "$speech",
          "to",
          "$pointing_back,",
          "“Every",
          "$person",
          "serves",
          "the",
          "$thumbs_up",
          "wine",
          "first,",
          "$plus",
          "then",
          "the",
          "cheap",
          "wine",
          "after",
          "the",
          "guests",
          "have",
          "drunk",
          "freely.",
          "But",
          "you",
          "have",
          "saved",
          "the",
          "$thumbs_up",
          "wine",
          "until",
          "now.”",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$cross",
          "$hammer",
          "this,",
          "the",
          "first",
          "of",
          "His",
          "signs,",
          "$tray_in",
          "Cana",
          "of",
          "Galilee.",
          "$plus",
          "He",
          "revealed",
          "$pointing_back",
          "$star,",
          "$plus",
          "$pointing_back",
          "$learner",
          "$anchor",
          "in",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "After",
          "this",
          "He",
          "went",
          "down",
          "to",
          "Capernaum,",
          "$plus",
          "$pointing_back",
          "mother",
          "$plus",
          "$pointing_back",
          "$brother",
          "$plus",
          "$pointing_back",
          "$learner,",
          "$plus",
          "they",
          "stayed",
          "there",
          "$no_entry",
          "many",
          "$sun.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$plus",
          "when",
          "the",
          "Passover",
          "of",
          "the",
          "$menorah",
          "was",
          "near,",
          "$plus",
          "$cross",
          "went",
          "up",
          "to",
          "Jerusalem.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "$plus",
          "$tray_in",
          "the",
          "temple",
          "He",
          "found",
          "those",
          "selling",
          "cattle",
          "$plus",
          "$sheep",
          "$plus",
          "doves,",
          "$plus",
          "the",
          "money",
          "changers",
          "seated",
          "there.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "$plus",
          "He",
          "$hammer",
          "a",
          "whip",
          "$tray_out",
          "cords",
          "and",
          "drove",
          "them",
          "all",
          "$tray_out",
          "the",
          "temple,",
          "$plus",
          "both",
          "the",
          "$sheep",
          "$plus",
          "the",
          "cattle.",
          "He",
          "poured",
          "out",
          "the",
          "coins",
          "of",
          "the",
          "money",
          "changers",
          "$plus",
          "overturned",
          "their",
          "tables.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "$plus",
          "to",
          "those",
          "selling",
          "doves",
          "He",
          "$speech,",
          "“Take",
          "these",
          "out",
          "of",
          "here!",
          "$no_entry",
          "$hammer",
          "the",
          "$house",
          "of",
          "My",
          "$father",
          "into",
          "a",
          "market",
          "$house!”",
        ],
      },
      {
        verse_number: 17,
        words: [
          "$pointing_back",
          "$learner",
          "remembered",
          "$pointing",
          "it",
          "is",
          "written:",
          "“$heart_on_fire",
          "for",
          "Your",
          "$house",
          "will",
          "consume",
          "Me.”",
        ],
      },
      {
        verse_number: 18,
        words: [
          "$plus",
          "the",
          "$menorah",
          "$speech",
          "to",
          "$pointing_back,",
          "“What",
          "sign",
          "can",
          "You",
          "show",
          "us",
          "$pointing",
          "You",
          "may",
          "$hammer",
          "these",
          "things?”",
        ],
      },
      {
        verse_number: 19,
        words: [
          "$cross",
          "answered",
          "$plus",
          "$speech",
          "to",
          "$pointing_back,",
          "“Destroy",
          "this",
          "temple,",
          "$plus",
          "$tray_in",
          "three",
          "$sun",
          "I",
          "will",
          "raise",
          "$pointing_back",
          "up",
          "again.”",
        ],
      },
      {
        verse_number: 20,
        words: [
          "$plus",
          "the",
          "$menorah",
          "$speech,",
          "“Forty",
          "six",
          "years",
          "this",
          "temple",
          "was",
          "in",
          "the",
          "building,",
          "$plus",
          "You",
          "will",
          "raise",
          "$pointing_back",
          "up",
          "$tray_in",
          "three",
          "$sun?”",
        ],
      },
      {
        verse_number: 21,
        words: [
          "But",
          "He",
          "was",
          "$speech",
          "about",
          "the",
          "temple",
          "of",
          "$pointing_back",
          "body.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "So",
          "when",
          "He",
          "was",
          "raised",
          "$tray_out",
          "the",
          "$skull,",
          "$pointing_back",
          "$learner",
          "remembered",
          "$pointing",
          "He",
          "had",
          "$speech",
          "this,",
          "$plus",
          "they",
          "$anchor",
          "the",
          "Scripture",
          "$plus",
          "the",
          "$speech",
          "that",
          "$cross",
          "had",
          "$speech.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "While",
          "He",
          "was",
          "$tray_in",
          "Jerusalem",
          "$tray_in",
          "the",
          "Passover,",
          "$tray_in",
          "the",
          "Feast,",
          "many",
          "$anchor",
          "in",
          "$pointing_back",
          "$name_tag,",
          "seeing",
          "the",
          "signs",
          "$pointing_back",
          "was",
          "$hammer.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "But",
          "$cross",
          "did",
          "$no_entry",
          "$anchor",
          "Himself",
          "to",
          "$pointing_back,",
          "because",
          "$pointing_back",
          "$lightbulb",
          "all",
          "men.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "$plus",
          "He",
          "had",
          "$no_entry",
          "need",
          "$pointing",
          "anyone",
          "should",
          "$witness",
          "about",
          "the",
          "$person,",
          "for",
          "$pointing_back",
          "$lightbulb",
          "what",
          "was",
          "$tray_in",
          "the",
          "$person.",
        ],
      },
    ],
  };
  return chapter;
}
