export function bible_glyph_chapter_psa008() {
  "Psalm 8, drawn in pictures, so that a person who cannot read the letters can still follow it. A man looks up at the night sky, works out how small he is, and then finds out what he was given anyway. Nine lines, and the first and the last are the same line.";
  "THE MOST FAMOUS NIGHT SKY IN THE BIBLE, AND THE STAR IS TWO LINES AWAY ON THE WRONG WORD. The third line says the moon and the stars, the work of Your fingers, and it comes out with two marks on it, an eye and a sky, and no moon and no star. Then the fifth line says You crowned him with glory, and a star appears. There is a star drawing and there is a moon drawing, and the star has been given to the word glory, which turns up in forty two chapters, and the moon has been given to nothing at all. So this psalm has its star two lines below the sky it belongs in, sitting on an idea, while the sky that the whole psalm is written about is empty. Nehemiah 9 has the same fault twelve lines apart. Here it is two, and here the sky is the subject.";
  "THE FIRST LINE AND THE LAST LINE ARE THE SAME LINE, AND BOTH OF THEM LOSE THE NAME TWICE. O LORD, our Lord, how majestic is Your name in all the earth. The covenant name and the plain word name are drawn by one tag, so a line holding both asks for the same picture meaning two things, and every name mark in it has to be put away. This psalm is built as a frame, the same sentence at the top and at the bottom, and the frame is exactly where the fault lands, so it lands twice. Exodus 33, Exodus 34, Isaiah 43, Psalm 34, Psalm 116, Deuteronomy 32 and Nehemiah 9 were the earlier ones. None of those lost the line the reader is meant to carry away.";
  "THE LINE JESUS QUOTED HAS NOTHING ON IT AT ALL. From the mouths of children and infants You have ordained praise. Nine lines, and the second one comes out blank. There is no picture for a child, none for an infant, none for praise, none for an enemy and none for silencing, and the one literal mouth in the psalm gets nothing because the mouth drawing means speaking and is spent elsewhere. A reader following pictures turns the page and finds a whole sentence of letters.";
  "EVERYTHING THAT WAS MADE IS LISTED AND ONLY THE FISH IS DRAWN. Sheep, oxen, the beasts of the field, the birds of the air, the fish of the sea: that is the seventh and eighth lines and it is the point of the psalm, that all of it was handed over. The page draws a sky, a fish, and a sea twice. The places are drawn and the animals are not, except for one, so the reader is shown where the creatures live and not what they are. The seventh line, which is sheep and oxen and wild animals together, is blank.";
  "THE PAGE SAYS GOD WHERE THE ENGLISH SAYS ANGELS, AND THE PAGE IS SAYING THE OLDER THING. The fifth line reads a little lower than the angels, and the word underneath it is the ordinary Hebrew word for God, so the flame lands there. A reader following the pictures is told a little lower than God, which is what the Hebrew line says. The same thing happens quietly with the word glory: the first line and the fifth line both say it in English and they are two different Hebrew words, and the page draws only the second of them. Zechariah 12 and Ezra 3 are the other two places found so far where the pictures are more exact than the translation they sit beside.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA008",
    reference: "Psalm 8",
    verses: [
      {
        verse_number: 1,
        words: [
          "O",
          "LORD,",
          "our",
          "$crown,",
          "how",
          "majestic",
          "is",
          "Your",
          "name",
          "in",
          "all",
          "the",
          "$earth!",
          "You",
          "have",
          "$hands_giving",
          "Your",
          "glory",
          "above",
          "the",
          "$sky.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "From",
          "the",
          "mouths",
          "of",
          "children",
          "and",
          "infants",
          "You",
          "have",
          "ordained",
          "praise",
          "on",
          "account",
          "of",
          "Your",
          "adversaries,",
          "to",
          "silence",
          "the",
          "enemy",
          "and",
          "avenger.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "When",
          "I",
          "$eye",
          "Your",
          "$sky,",
          "the",
          "work",
          "of",
          "Your",
          "fingers,",
          "the",
          "moon",
          "and",
          "the",
          "stars,",
          "which",
          "You",
          "have",
          "set",
          "in",
          "place,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "what",
          "is",
          "man",
          "that",
          "You",
          "are",
          "mindful",
          "of",
          "him,",
          "or",
          "the",
          "$son",
          "of",
          "$person",
          "that",
          "You",
          "care",
          "for",
          "him?",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "made",
          "him",
          "a",
          "little",
          "lower",
          "than",
          "the",
          "$fire;",
          "You",
          "crowned",
          "him",
          "with",
          "$star",
          "and",
          "honor.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "You",
          "made",
          "him",
          "ruler",
          "of",
          "the",
          "works",
          "of",
          "Your",
          "$hand;",
          "You",
          "have",
          "placed",
          "everything",
          "under",
          "his",
          "feet:",
        ],
      },
      {
        verse_number: 7,
        words: [
          "all",
          "sheep",
          "and",
          "oxen,",
          "and",
          "even",
          "the",
          "beasts",
          "of",
          "the",
          "field,",
        ],
      },
      {
        verse_number: 8,
        words: [
          "the",
          "birds",
          "of",
          "the",
          "$sky,",
          "and",
          "the",
          "$fish",
          "of",
          "the",
          "$sea,",
          "all",
          "that",
          "swim",
          "the",
          "paths",
          "of",
          "the",
          "$sea.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "O",
          "LORD,",
          "our",
          "$crown,",
          "how",
          "majestic",
          "is",
          "Your",
          "name",
          "in",
          "all",
          "the",
          "$earth!",
        ],
      },
    ],
  };
  return chapter;
}
