export function bible_glyph_chapter_psa097() {
  "The fifty fourth picture Bible chapter written by hand: the whole of the ninety seventh psalm, the LORD reigning over the earth and the fire going before Him, in the shorthand a person types.";
  "IT IS THE FIRST OF THE REIGNING PSALMS TO GO ON THIS LIST. Twelve verses, forty three in a hundred. Psalms ninety three to ninety nine are a block that all say the same thing in different words - that the LORD is king now, over the whole earth, and that this is good news for the ground itself and not only for people. None of them was on the list before this one. Three more of the block measure just as well and are the obvious next pages after it.";
  "THE PAGE OPENS ON THE CASTLE MARK AND THAT ONE MARK IS THE WHOLE PSALM. The first three words are the LORD and the castle, and everything after them is what follows from it: the earth glad, the mountains going soft, the peoples looking up. A reader who knows only that one mark has the argument. It is only the second Hebrew page here to carry it - the other nine chapters that use it are all Greek ones.";
  "RIGHTEOUSNESS AND JUSTICE ARE TWO DIFFERENT MARKS AND THE PAGE PUTS THEM TOGETHER AND THEN SPLITS THEM. They stand side by side in the second verse holding up the throne. After that they part: the scales go to the eighth verse where Zion is glad about them, and the ruler goes to the sixth, the eleventh and the twelfth, where it stops meaning a quality of God and starts meaning the people who belong to Him. Same mark, moved from the judge to the judged, and nothing in the English says so.";
  "THE FIRE MARK IS FOR GOD AND THE WORD FIRE ON THIS PAGE IS NOT DRAWN. The third verse has fire going out before Him and it is left in plain letters. The seventh and the ninth verses do carry the mark, and there it is standing on the word for gods - the ones told to bow, and the ones He is above. So on this one page the picture of fire never means fire. That is not a slip; it is what the root table decides, and it is worth seeing once.";
  "THE EARTH MARK FALLS FOUR TIMES AND THE WORLD MARK ONCE, AND THEY ARE NOT THE SAME WORD. The earth is glad in the first verse, sees and trembles in the fourth, has its Lord in the fifth, and is what God is over in the ninth. The fourth verse also has the round world lit up by lightning, which is a second Hebrew word and gets its own picture. English uses earth and world almost interchangeably. The marks keep them apart.";
  "TWO WORDS HERE HAVE PICTURES WAITING AND NEITHER GETS ONE. The second verse says thick darkness is around Him, and the darkness mark is not used, because the Hebrew word here is araphel and the mark is seated on choshek, the plain word for dark that opens Genesis. The fourth verse says lightning and the lightning mark is not used either. Both are left in letters, which is safe, and both are real gaps in the root table that somebody could close.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA097",
    reference: "Psalm 97",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "$name_tag",
          "$castle,",
          "let",
          "the",
          "$earth",
          "rejoice;",
          "let",
          "the",
          "distant",
          "shores",
          "be",
          "glad.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Clouds",
          "and",
          "thick",
          "darkness",
          "surround",
          "Him;",
          "$ruler",
          "and",
          "$scales",
          "are",
          "the",
          "foundation",
          "of",
          "His",
          "throne.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Fire",
          "$walking",
          "before",
          "Him",
          "and",
          "consumes",
          "His",
          "foes",
          "on",
          "every",
          "side.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "His",
          "lightning",
          "illuminates",
          "the",
          "$globe;",
          "the",
          "$earth",
          "$eye",
          "and",
          "trembles.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$mountain",
          "melt",
          "like",
          "wax",
          "at",
          "the",
          "presence",
          "of",
          "the",
          "$name_tag,",
          "before",
          "the",
          "$crown",
          "of",
          "all",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "$sky",
          "proclaim",
          "His",
          "$ruler;",
          "all",
          "the",
          "$family",
          "$eye",
          "His",
          "$star.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "All",
          "who",
          "$kneeling",
          "carved",
          "images",
          "are",
          "put",
          "to",
          "shame,",
          "those",
          "who",
          "boast",
          "in",
          "idols.",
          "$bowing",
          "Him,",
          "all",
          "you",
          "$fire!",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Zion",
          "$ear",
          "and",
          "rejoices,",
          "and",
          "the",
          "$woman",
          "of",
          "Judah",
          "exult,",
          "because",
          "of",
          "Your",
          "$scales,",
          "O",
          "$name_tag.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "For",
          "You,",
          "O",
          "$name_tag,",
          "are",
          "Most",
          "High",
          "over",
          "all",
          "the",
          "$earth;",
          "You",
          "are",
          "exalted",
          "far",
          "above",
          "all",
          "$fire.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Let",
          "those",
          "who",
          "$heart_red",
          "the",
          "$name_tag",
          "hate",
          "$thumbs_down;",
          "He",
          "preserves",
          "the",
          "$person_other",
          "of",
          "His",
          "saints",
          "and",
          "delivers",
          "them",
          "from",
          "the",
          "$hand",
          "of",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$light",
          "shines",
          "on",
          "the",
          "$ruler,",
          "and",
          "gladness",
          "on",
          "the",
          "upright",
          "in",
          "$heart_organ.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Rejoice",
          "in",
          "the",
          "$name_tag,",
          "O",
          "you",
          "$ruler,",
          "and",
          "$hands_raised",
          "to",
          "His",
          "$sparkle",
          "name.",
        ],
      },
    ],
  };
  return chapter;
}
