export function bible_glyph_chapter_psa051() {
  "The fifty first psalm, drawn in pictures. It is what David wrote after Nathan came to him, and it is the psalm people go to when they have done something they cannot undo.";
  "ONE HEBREW ROOT IS DRAWN FOUR TIMES ON THIS PAGE AND LEFT PLAIN THREE TIMES, AND IT IS THE SAME WORD EVERY TIME. Chata means to miss the mark, which is why the root table draws it as a bow. Four different forms of it stand in this psalm, seven times between them. The bow falls on cleanse me from my sin in the second verse, my sin is always before me in the third, have I sinned in the fourth, and purify me in the seventh. It does not fall on I was sinful in the fifth, hide Your face from my sins in the ninth, or sinners will return to You in the thirteenth. Nothing in the Hebrew changed between those two lists. The table seats words by their Strongs number and it holds two of the four numbers this root uses here, so the picture appears or vanishes according to which grammatical form the psalm happened to reach for. A reader following pictures is told that the fifth verse is about something different from the fourth, and it is not.";
  "THE SAME BOW MEANS DOING THE WRONG AND MEANS BEING WASHED OF IT. The fourth verse has against You only have I sinned and the seventh has purify me with hyssop, and in Hebrew those are one verb - chata in the plain form is to miss, and chata in the intensive form is to un-miss, to take the missing away. English needs two unrelated words, sinned and purify, and gives no sign they are related. The bow stands at both. That is the psalm in one mark: the thing that was done and the undoing of it are the same word turned around, which is what the whole prayer is asking for.";
  "THE OTHER TWO WORDS FOR WRONG HAVE NO PICTURE AT ALL. Avon, twisted or crooked, stands three times - wash away my iniquity, in iniquity I was brought forth, blot out all my iniquities - and pesha, rebellion or breaking away, stands in the first verse and the third, with the people it names, transgressors, in the thirteenth. Neither is seated, and nor is that third form. So the psalm has three separate Hebrew words for what is wrong with a person and only one of them can be seen, and even that one only two thirds of the time. The fifth, ninth and eighteenth verses carry no mark whatever.";
  "THE SPIRIT MARK FALLS FOUR TIMES AND ENGLISH GIVES IT FOUR DIFFERENT COATS. Ruach stands in the tenth verse as a right spirit, in the eleventh as Your Holy Spirit, in the twelfth as a willing spirit, and in the seventeenth as a broken spirit. The same picture stands at all four. Read down the page, the marks say plainly that the psalm is turning one thing over four ways - renew it, do not take it, hold me up with it, this is the offering God wants - and a reader is following the argument without knowing a word of it.";
  "THE HEADING IS PART OF THE PSALM HERE AND ONE MARK IN IT LANDS TWICE. Nathan came to him, and David had gone in to Bathsheba, and in Hebrew both of those are bo, the ordinary verb for going in, which the table draws as footprints. So the heading has two sets of footprints: the ones David made and the ones that came after him. English writes the first as came and buries the second in a euphemism, and the two look nothing alike. The picture puts them side by side in a single line, which is exactly the connection the heading is making.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA051",
    reference: "Psalm 51",
    verses: [
      {
        verse_number: 1,
        words: [
          "For",
          "the",
          "choirmaster.",
          "A",
          "Psalm",
          "of",
          "David,",
          "when",
          "Nathan",
          "the",
          "$megaphone",
          "$footprints",
          "to",
          "him",
          "after",
          "he",
          "had",
          "$footprints",
          "in",
          "to",
          "Bathsheba.",
          "Have",
          "mercy",
          "on",
          "me,",
          "O",
          "$fire,",
          "according",
          "to",
          "Your",
          "$gift;",
          "according",
          "to",
          "Your",
          "great",
          "compassion,",
          "blot",
          "out",
          "my",
          "transgressions.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Wash",
          "away",
          "all",
          "my",
          "iniquity",
          "and",
          "cleanse",
          "me",
          "from",
          "my",
          "$bow.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "For",
          "I",
          "$lightbulb",
          "my",
          "transgressions,",
          "and",
          "my",
          "$bow",
          "is",
          "always",
          "before",
          "me.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Against",
          "You,",
          "You",
          "only,",
          "have",
          "I",
          "$bow",
          "and",
          "$hammer",
          "what",
          "is",
          "$thumbs_down",
          "in",
          "Your",
          "$eyes,",
          "so",
          "that",
          "You",
          "may",
          "be",
          "$ruler",
          "when",
          "You",
          "$mouth",
          "and",
          "blameless",
          "when",
          "You",
          "judge.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Surely",
          "I",
          "was",
          "brought",
          "forth",
          "in",
          "iniquity;",
          "I",
          "was",
          "sinful",
          "when",
          "my",
          "mother",
          "conceived",
          "me.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Surely",
          "You",
          "desire",
          "$check",
          "in",
          "the",
          "inmost",
          "being;",
          "You",
          "$lightbulb",
          "me",
          "wisdom",
          "in",
          "the",
          "inmost",
          "place.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$bow",
          "me",
          "with",
          "hyssop,",
          "and",
          "I",
          "will",
          "be",
          "clean;",
          "wash",
          "me,",
          "and",
          "I",
          "will",
          "be",
          "whiter",
          "than",
          "snow.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Let",
          "me",
          "$ear",
          "joy",
          "and",
          "gladness;",
          "let",
          "the",
          "bones",
          "You",
          "have",
          "crushed",
          "rejoice.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Hide",
          "Your",
          "face",
          "from",
          "my",
          "sins,",
          "and",
          "blot",
          "out",
          "all",
          "my",
          "iniquities.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Create",
          "in",
          "me",
          "a",
          "clean",
          "$heart_organ,",
          "O",
          "$fire,",
          "and",
          "renew",
          "a",
          "right",
          "$wind",
          "within",
          "me.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Do",
          "$no_entry",
          "cast",
          "me",
          "away",
          "from",
          "Your",
          "presence;",
          "do",
          "$no_entry",
          "$hand_receiving",
          "Your",
          "$sparkle",
          "$wind",
          "from",
          "me.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "$turn_back",
          "to",
          "me",
          "the",
          "joy",
          "of",
          "Your",
          "salvation,",
          "and",
          "sustain",
          "me",
          "with",
          "a",
          "willing",
          "$wind.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Then",
          "I",
          "will",
          "teach",
          "transgressors",
          "Your",
          "$road,",
          "and",
          "sinners",
          "will",
          "$turn_back",
          "to",
          "You.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Deliver",
          "me",
          "from",
          "$blood,",
          "O",
          "$fire,",
          "the",
          "$fire",
          "of",
          "my",
          "salvation,",
          "and",
          "my",
          "tongue",
          "will",
          "sing",
          "of",
          "Your",
          "$ruler.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "O",
          "$crown,",
          "open",
          "my",
          "lips,",
          "and",
          "my",
          "mouth",
          "will",
          "declare",
          "Your",
          "praise.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "For",
          "You",
          "do",
          "$no_entry",
          "delight",
          "in",
          "sacrifice,",
          "or",
          "I",
          "would",
          "$hands_giving",
          "it;",
          "You",
          "take",
          "$no_entry",
          "pleasure",
          "in",
          "burnt",
          "offerings.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "The",
          "sacrifices",
          "of",
          "$fire",
          "are",
          "a",
          "broken",
          "$wind;",
          "a",
          "broken",
          "and",
          "a",
          "contrite",
          "$heart_organ,",
          "O",
          "$fire,",
          "You",
          "will",
          "$no_entry",
          "despise.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "In",
          "Your",
          "good",
          "pleasure,",
          "cause",
          "Zion",
          "to",
          "prosper;",
          "build",
          "up",
          "the",
          "walls",
          "of",
          "Jerusalem.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Then",
          "You",
          "will",
          "delight",
          "in",
          "$ruler",
          "sacrifices,",
          "in",
          "whole",
          "burnt",
          "offerings;",
          "then",
          "bulls",
          "will",
          "be",
          "offered",
          "on",
          "Your",
          "$altar.",
        ],
      },
    ],
  };
  return chapter;
}
