export function bible_glyph_chapter_psa091() {
  "Psalm 91, drawn in pictures. The psalm of shelter: whoever lives under the shadow of the Most High is promised cover from terror, from arrows, from plague and from anything that walks in the dark. Sixteen lines.";
  "THE MOST FAMOUS LINE IN THIS PSALM DRAWS NOTHING AT ALL. He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. That is the sentence people know this psalm by, and every single word of it stays in plain letters. The shelter has no seat. The shadow has no seat. And the two great titles of God the psalm is built on, the Most High and the Almighty, have no seat either, so the first line of the page is blank while the second one draws the ordinary word for God without any trouble. A picture reader opening here meets an empty line first.";
  "IT IS A PSALM ABOUT COVER AND THIS BIBLE HAS NO PICTURE FOR COVER. Refuge, fortress, feathers, wings, shield, rampart, tent: seven different words for being kept safe, spread over the first ten lines, and not one of them is seated in the root table. The psalm says the same thing seven ways because that is how Hebrew poetry insists, and the page loses the insistence and keeps the argument around it. What survives of those lines is the name, a flame, a tick for faithfulness, and three refusals.";
  "THE ONE THING GOD ASKS FOR HERE IS THE ONE WORD THE PAGE PUTS AWAY. The fourteenth line gives the reason for everything promised above it: because he knows My name, I will protect him. Knowing has a picture and it is drawn. The name does not get one, because the mark for the name of God is also the mark for the ordinary Hebrew word name, and wherever the ordinary word turns up the mark has to stand down or a reader learns the wrong thing. So the psalm draws the knowing and leaves the thing known in letters, which is exactly backwards from what the verse is arguing.";
  "THE STONE THE DEVIL QUOTED IS UNDRAWN, AND SO ARE ALL FOUR ANIMALS UNDER IT. The twelfth line is the one Satan read out to Jesus in the wilderness: they will lift you up in their hands, so that you will not strike your foot against a stone. There is no stone in this Bible. The thirteenth line then names a lion, a cobra, a young lion and a serpent, and there is no picture for any of the four. Two of the best known lines in the psalter go past with nothing on them at all.";
  "AND IT IS THE THINNEST PAGE IN THE WHOLE COLLECTION. Nineteen marks over sixteen lines, which is one and a fifth marks a line, and the chapter that held the record before it was the nineteenth of Job at one and a third. Five of the sixteen lines carry nothing at all: the first, the third, the twelfth, the thirteenth and the fifteenth. A psalm everybody can recite turns out to be almost the least drawable thing written here, and the reason is not that the psalm is difficult. It is that a psalm made of shelter, weather, animals and titles for God is made of exactly the words this table has not bought yet. The place a survey would have sent you and the place a reader needs you are not the same place.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA091",
    reference: "Psalm 91",
    verses: [
      {
        verse_number: 1,
        words: [
          "He",
          "who",
          "dwells",
          "in",
          "the",
          "shelter",
          "of",
          "the",
          "Most",
          "High",
          "will",
          "abide",
          "in",
          "the",
          "shadow",
          "of",
          "the",
          "Almighty.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "I",
          "will",
          "$speech",
          "of",
          "the",
          "$name_tag,",
          "He",
          "is",
          "my",
          "refuge",
          "and",
          "my",
          "fortress,",
          "my",
          "$fire,",
          "in",
          "whom",
          "I",
          "trust.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Surely",
          "He",
          "will",
          "deliver",
          "you",
          "from",
          "the",
          "snare",
          "of",
          "the",
          "fowler,",
          "and",
          "from",
          "the",
          "deadly",
          "plague.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "He",
          "will",
          "cover",
          "you",
          "with",
          "His",
          "feathers;",
          "under",
          "His",
          "wings",
          "you",
          "will",
          "find",
          "refuge.",
          "His",
          "$check",
          "is",
          "a",
          "shield",
          "and",
          "rampart.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "will",
          "$no_entry",
          "fear",
          "the",
          "terror",
          "of",
          "the",
          "night,",
          "nor",
          "the",
          "arrow",
          "that",
          "flies",
          "by",
          "day,",
        ],
      },
      {
        verse_number: 6,
        words: [
          "nor",
          "the",
          "pestilence",
          "that",
          "$walking",
          "in",
          "the",
          "darkness,",
          "nor",
          "the",
          "calamity",
          "that",
          "destroys",
          "at",
          "noon.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Though",
          "a",
          "thousand",
          "may",
          "fall",
          "at",
          "your",
          "side,",
          "and",
          "ten",
          "thousand",
          "at",
          "your",
          "right",
          "hand,",
          "$no_entry",
          "harm",
          "will",
          "come",
          "near",
          "you.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "You",
          "will",
          "only",
          "look",
          "on",
          "it",
          "with",
          "your",
          "$eyes",
          "and",
          "$eye",
          "the",
          "punishment",
          "of",
          "the",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Because",
          "you",
          "have",
          "made",
          "the",
          "$name_tag,",
          "who",
          "is",
          "my",
          "refuge,",
          "even",
          "the",
          "Most",
          "High,",
          "your",
          "dwelling,",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$no_entry",
          "$thumbs_down",
          "will",
          "befall",
          "you,",
          "and",
          "$no_entry",
          "plague",
          "will",
          "approach",
          "your",
          "tent.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "He",
          "will",
          "command",
          "His",
          "$angel",
          "concerning",
          "you,",
          "to",
          "guard",
          "you",
          "in",
          "all",
          "your",
          "$road.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "They",
          "will",
          "lift",
          "you",
          "up",
          "in",
          "their",
          "hands,",
          "so",
          "that",
          "you",
          "will",
          "not",
          "strike",
          "your",
          "foot",
          "against",
          "a",
          "stone.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "You",
          "will",
          "tread",
          "on",
          "the",
          "lion",
          "and",
          "the",
          "cobra;",
          "you",
          "will",
          "trample",
          "the",
          "young",
          "lion",
          "and",
          "the",
          "serpent.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Because",
          "he",
          "loves",
          "Me,",
          "I",
          "will",
          "deliver",
          "him;",
          "because",
          "he",
          "$lightbulb",
          "My",
          "name,",
          "I",
          "will",
          "protect",
          "him.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "When",
          "he",
          "calls",
          "out",
          "to",
          "Me,",
          "I",
          "will",
          "answer",
          "him;",
          "I",
          "will",
          "be",
          "with",
          "him",
          "in",
          "trouble,",
          "I",
          "will",
          "deliver",
          "him",
          "and",
          "honor",
          "him.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "With",
          "long",
          "$sun",
          "I",
          "will",
          "satisfy",
          "him,",
          "and",
          "$eye",
          "him",
          "My",
          "salvation.",
        ],
      },
    ],
  };
  return chapter;
}
