export function bible_glyph_divine_numbers() {
  "Every Strong's number that names God and has no picture yet, given with a chapter code that says which testament the number belongs to.";
  "IT EXISTS TO STOP ONE MARK, AND THE MARK IS THE NAME BADGE. The badge says A NAME STANDS HERE and the letters beside it are that name, which is the right thing to draw over David and Nineveh and Habakkuk. Over Shaddai it is the wrong thing, not because it is false - Shaddai is a name - but because it is the same mark that stands over Pharaoh, and a picture Bible that draws the Almighty and Pharaoh with one mark has said something about them that the text does not.";
  "THE REASON IS REVERENCE AND IT WAS ASKED FOR IN THOSE WORDS. The covenant name was given its own sign rather than the tag that every other name wore, and the sentence that settled it was that I AM is its own symbol. That is a rule about a class and not about one word, so every name of God meets it, and the ones that have no picture yet wait in letters rather than take the generic one.";
  "WAITING IN LETTERS IS NOT THE SAME AS BEING SKIPPED. A number listed here is a number that still owes a picture, and listing it is how it stays visible as owing one. The name badge would have hidden that debt behind a mark that looked like an answer, which is the quiet way a gap stops being counted.";
  "SO THE LIST IS MEANT TO EMPTY ITSELF AND A SEATED NUMBER MUST LEAVE IT. Once a number is drawn, nothing here is doing any work - the drawer already passes over every number that has a picture, because a number with a picture is not a name waiting for one. The gate beside this asks exactly that of every row, so seating Shaddai turns this file red and the repair is to delete the row. That is the difference between a list that expires and a register that quietly outlives its reason.";
  "TWO NAMES WERE HERE ON THE DAY IT WAS WRITTEN AND LEFT THE SAME DAY. Yah turned out to be the covenant name said short and Messias the word John translates as the Christ in the verse he uses it in, so both were seated on marks already drawn rather than listed here, and the list is shorter by the two that were never really undecided. What was left after them was the two titles and the one ordinary noun, which is the whole of what anybody had to think about.";
  "THE TESTAMENT IS CARRIED BY A CHAPTER AND NOT BY ITS NAME, because a Strong's number means different things on the two sides and the division names are already spelled in one place. Hebrew 4990 and Greek 4990 are both real numbers and only one of them is the saviour, so a row that gave the number alone would refuse a badge in the wrong half of the Bible. Naming a chapter that is certainly in the testament meant, and asking what testament that chapter is in, keeps the spelling where it already lives.";
  "PANTOKRATOR LEFT BY BEING DRAWN, WHICH IS THE WAY OUT OF HERE THAT WAS ALWAYS INTENDED. Its own word is two words - all joined to one who holds power - so the picture is those two pictures, and nothing had to be decided that the Greek had not already said. That is the test any remaining row has to meet: can the word's parts be read off the word itself. Where they can, the title is drawn and the row goes; where they cannot, the row stays and somebody has to choose.";
  "SHADDAI COULD NOT MEET THAT TEST AND WAS SEATED ANYWAY, WHICH IS THE ONE ROW WORTH FOLLOWING. The Hebrew word is not transparently made of parts the way pantokrator is, and the root behind it is genuinely argued over - to overpower, the breast that feeds, the mountain, the one who is enough. So the picture it now wears is a choice and not a reading, and a choice made here is exactly the kind of thing that must stay arguable. It is drawn by might alone, and every reading that lost is written out beside the one that won.";
  "A PICKED SEAT LEAVES THIS LIST THE SAME WAY A SETTLED ONE DOES, SO THE ARGUMENT HAD TO GO SOMEWHERE ELSE. This file only ever knew that a number was waiting, so once the number is drawn it has nothing left to hold, and the reasoning would have been deleted along with the row. The contested seats table is where it went, and it keeps the rejected pictures rather than the chosen one, because a person who objects needs the alternatives and not the verdict.";
  "THE LIST BEING EMPTY IS THE FINISHED STATE AND NOT AN UNWRITTEN ONE. Every name of God that had no picture now has one, so nothing here is owed, and an empty list that still explains itself is the honest way to leave a thing that expired. A number added here later is a new name found undrawn, which is the only reason to write a row again.";
  let rows = [];
  return rows;
}
