export function bible_glyph_chapter_lam03() {
  "The third chapter of Lamentations, drawn in pictures. A man who has watched his city destroyed spends twenty verses describing what God has done to him, turns in the twenty first verse, and says the words about mercies being new every morning. Then he goes back to weeping. It is sixty six lines long and the turn is in the middle.";
  "THE TURNING MARK FALLS FOUR TIMES AND IT IS THE WHOLE SHAPE OF THE CHAPTER. In the third verse God keeps turning His hand against him. In the twenty first he calls this to mind, which in Hebrew is I turn this back to my heart - the sentence that changes the poem. In the fortieth the people are told to turn back to the LORD. In the sixty fourth God will pay them back, which is the same word again. English uses four unrelated phrases: turns His hand, call to mind, turn back, pay back. The picture uses one mark four times, so a reader sees a hand turned against a man, then the man's own mind turning, then a whole people turning, then the whole thing turned around on his enemies. The hand mark makes it tighter still: it appears exactly twice on the page, in the third verse and the sixty fourth, and both times the turning mark is standing beside it.";
  "THE WORD HE SAYS HE HAS FORGOTTEN IS THE WORD HE THEN SAYS THREE TIMES IN A ROW. The seventeenth verse ends I have forgotten what prosperity is, and prosperity there is the ordinary Hebrew word for good. Eight verses later it comes back: the LORD is good, it is good to wait quietly, it is good for a man to bear the yoke - three consecutive verses, three identical marks. So the man who said he could no longer remember what good was says good three times before the paragraph ends. English hides it completely, because a translator quite reasonably wrote prosperity the first time. In the pictures it is the same mark in both places and impossible to miss.";
  "THE MOST QUOTED LINE IN THE BOOK IS BUILT OUT OF TWO CROSSINGS OUT. The twenty second verse says because of the LORD's loving devotion we are not consumed, for His mercies never fail. Both halves are negative and both carry the crossing out mark, so the picture of the great hope of Lamentations is two things that did not happen. The chapter uses that mark thirteen times in all, and this is the only place two of them stand in one line. It is worth sitting with: the comfort here is not stated as something given, but as something withheld.";
  "THE HEART MARK FALLS FOUR TIMES AND ONE OF THEM IS CALLED WILLINGLY. In the twenty first verse he turns this back to his heart. In the thirty third God does not afflict or grieve the sons of men willingly, and willingly there is literally from His heart. In the forty first the people lift up their hearts and hands. In the sixty fifth God puts a veil over the hearts of the enemies. So the same picture carries the man's turn, God's reluctance, the nation's prayer and the enemies' blindness, and the second of those is the one English cannot show - He does not do this from His heart.";
  "I SAW, MY EYES RAN, YOU HAVE SEEN. The first line of the chapter is I am the man who has seen affliction. The middle is his eyes: streams of tears from my eyes, my eyes overflow unceasingly, my eyes bring grief to my soul. The end is God: You have seen, O LORD, the wrong done to me; You have seen all their malice. Two marks are doing this, one for the verb and one for the pair of eyes, and between them they run the length of the poem in that order. There is a fifth seeing in the thirty sixth verse that English has to call something else - of these the Lord does not approve is literally the Lord does not see it.";
  "THE ONLY TWO PRAYER MARKS ON THE PAGE ARE BOTH ABOUT PRAYER NOT GETTING THROUGH. The eighth verse says even when I cry out and plead for help, He shuts out my prayer. The forty fourth says You have covered Yourself with a cloud that no prayer can pass through. Those are the only two, and the chapter never draws a prayer that arrives. It does draw a hearing, twice, in the fifty sixth and sixty first verses - You heard my plea, and You have heard their insults. So the answer, when it comes, is not drawn as a prayer reaching God but as God hearing.";
  "THE NAME MARK IS PUT AWAY IN THE FIFTY FIFTH VERSE. That line is I called on Your name, O LORD, and both the word name and the covenant name would carry the same tag, because the tag is really the ordinary word for a name. One picture doing two jobs in one short sentence is unreadable, so both are left in plain letters. It costs the page two marks in the verse where he calls out from the bottom of the pit, which is a real loss and worth stating rather than hiding.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "LAM03",
    reference: "Lamentations 3",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "am",
          "the",
          "man",
          "who",
          "has",
          "$eye",
          "affliction",
          "under",
          "the",
          "rod",
          "of",
          "God's",
          "wrath.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "He",
          "has",
          "driven",
          "me",
          "away",
          "and",
          "made",
          "me",
          "$walking",
          "in",
          "$darkness",
          "instead",
          "of",
          "$light.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Indeed,",
          "He",
          "keeps",
          "$turn_back",
          "His",
          "$hand",
          "against",
          "me",
          "all",
          "day",
          "long.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "He",
          "has",
          "worn",
          "away",
          "my",
          "$meat",
          "and",
          "skin;",
          "He",
          "has",
          "shattered",
          "my",
          "bones.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "He",
          "has",
          "besieged",
          "me",
          "and",
          "surrounded",
          "me",
          "with",
          "bitterness",
          "and",
          "hardship.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "has",
          "made",
          "me",
          "dwell",
          "in",
          "darkness",
          "like",
          "those",
          "$skull",
          "for",
          "$hourglass.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "has",
          "walled",
          "me",
          "in",
          "so",
          "I",
          "$no_entry",
          "escape;",
          "He",
          "has",
          "weighed",
          "me",
          "down",
          "with",
          "chains.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Even",
          "when",
          "I",
          "cry",
          "out",
          "and",
          "plead",
          "for",
          "help,",
          "He",
          "shuts",
          "out",
          "my",
          "$hands_praying.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "has",
          "barred",
          "my",
          "$road",
          "with",
          "cut",
          "stones;",
          "He",
          "has",
          "made",
          "my",
          "paths",
          "crooked.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "is",
          "a",
          "bear",
          "lying",
          "in",
          "wait,",
          "a",
          "lion",
          "hiding",
          "in",
          "ambush.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "He",
          "forced",
          "me",
          "off",
          "my",
          "$road",
          "and",
          "tore",
          "me",
          "to",
          "pieces;",
          "He",
          "left",
          "me",
          "without",
          "help.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "He",
          "bent",
          "His",
          "bow",
          "and",
          "set",
          "me",
          "as",
          "the",
          "target",
          "for",
          "His",
          "arrow.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "He",
          "$footprints",
          "my",
          "kidneys",
          "with",
          "the",
          "$son",
          "of",
          "His",
          "quiver.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "I",
          "am",
          "a",
          "laughingstock",
          "to",
          "all",
          "my",
          "$family;",
          "they",
          "mock",
          "me",
          "in",
          "song",
          "all",
          "day",
          "long.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "He",
          "has",
          "filled",
          "me",
          "with",
          "bitterness;",
          "He",
          "has",
          "intoxicated",
          "me",
          "with",
          "wormwood.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "He",
          "has",
          "ground",
          "my",
          "teeth",
          "with",
          "gravel",
          "and",
          "trampled",
          "me",
          "in",
          "the",
          "dust.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "My",
          "$person_other",
          "has",
          "been",
          "deprived",
          "of",
          "peace;",
          "I",
          "have",
          "forgotten",
          "what",
          "$thumbs_up",
          "is.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "So",
          "I",
          "$speech,",
          "My",
          "strength",
          "has",
          "perished,",
          "along",
          "with",
          "my",
          "hope",
          "from",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Remember",
          "my",
          "affliction",
          "and",
          "wandering,",
          "the",
          "wormwood",
          "and",
          "the",
          "gall.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Surely",
          "my",
          "$person_other",
          "remembers",
          "and",
          "is",
          "humbled",
          "within",
          "me.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Yet",
          "I",
          "$turn_back",
          "this",
          "to",
          "$heart_organ,",
          "and",
          "therefore",
          "I",
          "have",
          "hope:",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Because",
          "of",
          "the",
          "$name_tag",
          "$gift",
          "we",
          "are",
          "$no_entry",
          "consumed,",
          "for",
          "His",
          "mercies",
          "$no_entry",
          "fail.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "They",
          "are",
          "new",
          "every",
          "morning;",
          "great",
          "is",
          "Your",
          "faithfulness!",
        ],
      },
      {
        verse_number: 24,
        words: [
          "The",
          "$name_tag",
          "is",
          "my",
          "portion,",
          "$speech",
          "my",
          "$person_other,",
          "therefore",
          "I",
          "will",
          "hope",
          "in",
          "Him.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "The",
          "$name_tag",
          "is",
          "$thumbs_up",
          "to",
          "those",
          "who",
          "wait",
          "for",
          "Him,",
          "to",
          "the",
          "$person_other",
          "who",
          "seeks",
          "Him.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "to",
          "wait",
          "quietly",
          "for",
          "the",
          "salvation",
          "of",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "for",
          "a",
          "man",
          "to",
          "bear",
          "the",
          "yoke",
          "while",
          "he",
          "is",
          "still",
          "young.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "Let",
          "him",
          "sit",
          "alone",
          "in",
          "silence,",
          "for",
          "God",
          "has",
          "laid",
          "it",
          "upon",
          "him.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "Let",
          "him",
          "$hands_giving",
          "his",
          "face",
          "in",
          "the",
          "dust",
          "-",
          "perhaps",
          "there",
          "is",
          "still",
          "hope.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "Let",
          "him",
          "$hands_giving",
          "his",
          "cheek",
          "to",
          "the",
          "one",
          "who",
          "would",
          "strike",
          "him;",
          "let",
          "him",
          "be",
          "filled",
          "with",
          "reproach.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "For",
          "the",
          "$crown",
          "will",
          "$no_entry",
          "cast",
          "us",
          "off",
          "$hourglass.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "Even",
          "if",
          "He",
          "causes",
          "grief,",
          "He",
          "will",
          "show",
          "compassion",
          "according",
          "to",
          "His",
          "abundant",
          "$gift.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "For",
          "He",
          "does",
          "$no_entry",
          "afflict",
          "or",
          "grieve",
          "the",
          "$son",
          "of",
          "$man_beard",
          "$heart_organ.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "To",
          "crush",
          "underfoot",
          "all",
          "the",
          "prisoners",
          "of",
          "the",
          "$earth,",
        ],
      },
      {
        verse_number: 35,
        words: [
          "to",
          "deny",
          "$scales",
          "to",
          "a",
          "man",
          "before",
          "the",
          "Most",
          "High,",
        ],
      },
      {
        verse_number: 36,
        words: [
          "to",
          "subvert",
          "a",
          "$person",
          "in",
          "his",
          "lawsuit",
          "-",
          "of",
          "these",
          "the",
          "$crown",
          "does",
          "$no_entry",
          "$eye.",
        ],
      },
      {
        verse_number: 37,
        words: [
          "Who",
          "has",
          "$speech",
          "and",
          "it",
          "came",
          "to",
          "pass,",
          "$no_entry",
          "the",
          "$crown",
          "has",
          "ordained",
          "it?",
        ],
      },
      {
        verse_number: 38,
        words: [
          "Do",
          "$no_entry",
          "both",
          "$thumbs_down",
          "and",
          "$thumbs_up",
          "come",
          "from",
          "the",
          "mouth",
          "of",
          "the",
          "Most",
          "High?",
        ],
      },
      {
        verse_number: 39,
        words: [
          "Why",
          "should",
          "any",
          "$sprout",
          "$person",
          "complain,",
          "in",
          "view",
          "of",
          "his",
          "sins?",
        ],
      },
      {
        verse_number: 40,
        words: [
          "Let",
          "us",
          "examine",
          "and",
          "test",
          "our",
          "$road,",
          "and",
          "$turn_back",
          "to",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 41,
        words: [
          "Let",
          "us",
          "lift",
          "up",
          "our",
          "$heart_organ",
          "and",
          "hands",
          "to",
          "$fire",
          "in",
          "$sky:",
        ],
      },
      {
        verse_number: 42,
        words: [
          "We",
          "have",
          "sinned",
          "and",
          "rebelled;",
          "You",
          "have",
          "$no_entry",
          "forgiven.",
        ],
      },
      {
        verse_number: 43,
        words: [
          "You",
          "have",
          "covered",
          "Yourself",
          "in",
          "anger",
          "and",
          "pursued",
          "us;",
          "You",
          "have",
          "killed",
          "$no_entry",
          "pity.",
        ],
      },
      {
        verse_number: 44,
        words: [
          "You",
          "have",
          "covered",
          "Yourself",
          "with",
          "a",
          "cloud",
          "that",
          "no",
          "$hands_praying",
          "can",
          "pass",
          "through.",
        ],
      },
      {
        verse_number: 45,
        words: [
          "You",
          "have",
          "made",
          "us",
          "scum",
          "and",
          "refuse",
          "among",
          "the",
          "$family.",
        ],
      },
      {
        verse_number: 46,
        words: [
          "All",
          "our",
          "enemies",
          "open",
          "their",
          "mouths",
          "against",
          "us.",
        ],
      },
      {
        verse_number: 47,
        words: [
          "Panic",
          "and",
          "pitfall",
          "have",
          "come",
          "upon",
          "us,",
          "devastation",
          "and",
          "destruction.",
        ],
      },
      {
        verse_number: 48,
        words: [
          "Streams",
          "of",
          "$water",
          "flow",
          "from",
          "my",
          "$eyes",
          "over",
          "the",
          "destruction",
          "of",
          "the",
          "$woman",
          "of",
          "my",
          "$family.",
        ],
      },
      {
        verse_number: 49,
        words: [
          "My",
          "$eyes",
          "overflow",
          "$no_entry",
          "ceasing,",
          "without",
          "relief,",
        ],
      },
      {
        verse_number: 50,
        words: [
          "until",
          "the",
          "$name_tag",
          "looks",
          "down",
          "from",
          "$sky",
          "and",
          "$eye.",
        ],
      },
      {
        verse_number: 51,
        words: [
          "My",
          "$eyes",
          "bring",
          "grief",
          "to",
          "my",
          "$person_other",
          "because",
          "of",
          "all",
          "the",
          "$woman",
          "of",
          "my",
          "$city.",
        ],
      },
      {
        verse_number: 52,
        words: [
          "Without",
          "cause",
          "my",
          "enemies",
          "hunted",
          "me",
          "like",
          "a",
          "bird.",
        ],
      },
      {
        verse_number: 53,
        words: [
          "They",
          "dropped",
          "me",
          "$sprout",
          "into",
          "a",
          "pit",
          "and",
          "$hands_raised",
          "stones",
          "upon",
          "me.",
        ],
      },
      {
        verse_number: 54,
        words: [
          "The",
          "$water",
          "flowed",
          "over",
          "my",
          "head,",
          "and",
          "I",
          "$speech",
          "I",
          "was",
          "going",
          "to",
          "die.",
        ],
      },
      {
        verse_number: 55,
        words: [
          "I",
          "called",
          "on",
          "Your",
          "name,",
          "O",
          "LORD,",
          "out",
          "of",
          "the",
          "depths",
          "of",
          "the",
          "Pit.",
        ],
      },
      {
        verse_number: 56,
        words: [
          "You",
          "$ear",
          "my",
          "$voice:",
          "$no_entry",
          "ignore",
          "my",
          "cry",
          "for",
          "relief.",
        ],
      },
      {
        verse_number: 57,
        words: [
          "You",
          "drew",
          "near",
          "$sun",
          "I",
          "called",
          "on",
          "You;",
          "You",
          "$speech,",
          "$no_entry",
          "be",
          "afraid.",
        ],
      },
      {
        verse_number: 58,
        words: [
          "You",
          "defend",
          "my",
          "cause,",
          "O",
          "$crown;",
          "You",
          "redeem",
          "my",
          "$sprout.",
        ],
      },
      {
        verse_number: 59,
        words: [
          "You",
          "have",
          "$eye,",
          "O",
          "$name_tag,",
          "the",
          "wrong",
          "done",
          "to",
          "me;",
          "vindicate",
          "my",
          "$scales!",
        ],
      },
      {
        verse_number: 60,
        words: [
          "You",
          "have",
          "$eye",
          "all",
          "their",
          "malice,",
          "all",
          "their",
          "plots",
          "against",
          "me.",
        ],
      },
      {
        verse_number: 61,
        words: [
          "You",
          "have",
          "$ear",
          "their",
          "insults,",
          "O",
          "$name_tag,",
          "all",
          "their",
          "plots",
          "against",
          "me",
          "-",
        ],
      },
      {
        verse_number: 62,
        words: [
          "the",
          "slander",
          "and",
          "murmuring",
          "of",
          "my",
          "assailants",
          "against",
          "me",
          "all",
          "$sun.",
        ],
      },
      {
        verse_number: 63,
        words: [
          "When",
          "they",
          "sit",
          "and",
          "when",
          "they",
          "rise,",
          "see",
          "how",
          "they",
          "mock",
          "me",
          "in",
          "song.",
        ],
      },
      {
        verse_number: 64,
        words: [
          "You",
          "will",
          "$turn_back",
          "them",
          "what",
          "they",
          "deserve,",
          "O",
          "$name_tag,",
          "according",
          "to",
          "the",
          "work",
          "of",
          "their",
          "$hand.",
        ],
      },
      {
        verse_number: 65,
        words: [
          "$hands_giving",
          "a",
          "veil",
          "of",
          "anguish",
          "over",
          "their",
          "$heart_organ;",
          "may",
          "Your",
          "curse",
          "be",
          "upon",
          "them.",
        ],
      },
      {
        verse_number: 66,
        words: [
          "You",
          "will",
          "pursue",
          "them",
          "in",
          "anger",
          "and",
          "exterminate",
          "them",
          "from",
          "under",
          "the",
          "$sky",
          "of",
          "the",
          "$name_tag.",
        ],
      },
    ],
  };
  return chapter;
}
