import { fn_name } from "./fn_name.mjs";
export function bible_glyph_chapter_jhn01() {
  "The second picture Bible chapter written by hand: the prologue of John, verses one to eighteen, in the shorthand a person types.";
  "IT IS THE SECOND CHAPTER SO THAT THE FIRST CAN BE CHECKED. One chapter proves that a passage can be drawn; it cannot prove that a picture means the same thing twice, because there is nothing to compare it against. This passage was picked because it shares almost nothing with first John four except its vocabulary - a different subject, a different kind of sentence - so a reader who learned the fire and the seed there and reads them here is testing the only claim this Bible actually makes.";
  "IT IS THE FIRST CHAPTER TO DRAW THE GRAMMAR, and that is the whole reason it looks different from the one beside it. First John four says plainly that leaving in, and, not and is in English makes it an English Bible with pictures in it rather than the wordless Bible this is aiming at. The pictures for those words have been drawn since, and this is the first passage authored after they existed - so it draws them, and the two chapters on one page are the two lanes side by side rather than a chapter somebody forgot to finish.";
  "THE OLDER CHAPTER IS NOT TIDIED TO MATCH. It would take an afternoon and it would destroy the comparison: two chapters drawn the same way answer nothing, and two drawn differently let a reader say which one they could actually read. The day that question is settled, the loser gets rewritten - and not before.";
  "THE REST OF THE CHAPTER WAS WRITTEN IN A SECOND SITTING, and the reason it was put off turned out to be half wrong. Verses nineteen to fifty-one are John the Baptist answering the priests and the first disciples being called, and they are indeed full of names - Elijah, Bethany, Nazareth, Cephas, Nathanael - which pictures cannot carry and which stay in letters. What was wrong was the conclusion drawn from that. A name is a word the reader looks up rather than understands, so leaving it in letters costs the passage very little; what carries a story is its verbs, and the verbs here - saw, said, came, followed, knew, believed - were all drawn already.";
  "NARRATIVE DRAWS THINNER THAN TEACHING, and these two halves are the measurement rather than an opinion. The prologue says light, life, word and God over and over and every one of them is a picture; the narrative says Philip, Nathanael, Bethsaida and Rabbi and none of them is. So the second half reads more like English with pictures in it than the first half does, and that is a fact about telling a story rather than a fault in the drawing - it will be true of every chapter that tells one.";
  "THE GLYPH ON A WORD WAS READ AND NEVER CHOSEN. The root table seats a picture under a word once, for every chapter, so that a word drawn one way here is drawn that way everywhere; what an author decides is where the word sits in a readable sentence and which words have to stay English because nothing is seated under them yet.";
  ("The seating was read word by word from ",
    fn_name("bible_glyph_chapter_draft_words"),
    " rather than counted off a line of pictures, because counting seats a glyph on the wrong word and nothing anywhere catches it.");
  ("A WORD DOING GRAMMATICAL WORK IS LEFT IN ENGLISH even when a picture is seated on it. Verse nine says was coming, where the was is carrying the tense of the verb beside it rather than saying that anything is anything. The picture belongs to the word when the word is doing its own work.");
  ("EVERY IS IN THIS CHAPTER IS ENGLISH, and it did not start that way. This chapter was first drawn with an equals sign on the verb to be, because the seed table seated one there and the table is meant to be obeyed rather than argued with inside a verse. Verse one is what settled it: the same word appears three times in one sentence and does three different jobs - the Word EXISTED, the Word stood in a relation to God, the Word WAS God - and only the third is anything an equals sign was drawn for.");
  ("The mark was withdrawn from the seed table rather than avoided here, because a wrong mark that an author quietly steps around is a wrong mark waiting for the next author.");
  ("Verse eighteen reads the one and only God rather than the one and only Son, because that is what the Greek in the interlinear says, and a picture Bible that quietly moved to the easier reading would be hiding the one place the prologue is hardest.");
  let chapter = {
    chapter_code: "JHN01",
    reference: "John 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "$tray_in",
          "the",
          "beginning",
          "was",
          "the",
          "$speech,",
          "$plus",
          "the",
          "$speech",
          "was",
          "with",
          "$fire,",
          "$plus",
          "the",
          "$speech",
          "was",
          "$fire.",
        ],
      },
      {
        verse_number: 2,
        words: ["He", "was", "$tray_in", "the", "beginning", "with", "$fire."],
      },
      {
        verse_number: 3,
        words: [
          "Through",
          "$pointing_back",
          "all",
          "things",
          "were",
          "made,",
          "$plus",
          "without",
          "$pointing_back",
          "nothing",
          "was",
          "made",
          "that",
          "has",
          "been",
          "made.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$tray_in",
          "$pointing_back",
          "was",
          "$sprout,",
          "$plus",
          "that",
          "$sprout",
          "was",
          "the",
          "$light",
          "of",
          "$person$s.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$light",
          "shines",
          "$tray_in",
          "the",
          "$darkness,",
          "$plus",
          "the",
          "$darkness",
          "has",
          "$no_entry",
          "overcome",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "There",
          "came",
          "a",
          "$person",
          "sent",
          "from",
          "$fire,",
          "and",
          "$pointing_back’s",
          "$name_tag",
          "was",
          "John.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "$footprints",
          "as",
          "a",
          "$witness,",
          "to",
          "$witness",
          "about",
          "the",
          "$light,",
          "so",
          "that",
          "through",
          "$pointing_back",
          "everyone",
          "might",
          "$anchor.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "He",
          "himself",
          "was",
          "$no_entry",
          "the",
          "$light,",
          "but",
          "he",
          "came",
          "to",
          "$witness",
          "about",
          "the",
          "$light.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "true",
          "$light,",
          "which",
          "$light$s",
          "every",
          "$person,",
          "was",
          "$footprints",
          "into",
          "the",
          "$globe.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "was",
          "$tray_in",
          "the",
          "$globe,",
          "$plus",
          "though",
          "the",
          "$globe",
          "was",
          "made",
          "through",
          "$pointing_back,",
          "the",
          "$globe",
          "did",
          "$no_entry",
          "$lightbulb",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "He",
          "$footprints",
          "to",
          "His",
          "own,",
          "$plus",
          "His",
          "own",
          "did",
          "$no_entry",
          "receive",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "But",
          "to",
          "all",
          "who",
          "did",
          "$hand_receiving",
          "$pointing_back,",
          "to",
          "those",
          "who",
          "$anchor$d",
          "$tray_in",
          "$pointing_back’s",
          "$name_tag,",
          "He",
          "$hands_giving",
          "$pointing_back",
          "the",
          "$key",
          "to",
          "become",
          "children",
          "of",
          "$fire.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "children",
          "born",
          "$no_entry",
          "$tray_out",
          "blood,",
          "nor",
          "$tray_out",
          "the",
          "desire",
          "of",
          "the",
          "$meat,",
          "nor",
          "$tray_out",
          "the",
          "will",
          "of",
          "$man_beard,",
          "but",
          "$tray_out",
          "$fire.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "$speech",
          "became",
          "$meat",
          "$plus",
          "made",
          "His",
          "dwelling",
          "$tray_in",
          "us.",
          "We",
          "have",
          "seen",
          "$pointing_back’s",
          "$star,",
          "the",
          "$star",
          "of",
          "the",
          "one",
          "and",
          "only",
          "Son",
          "from",
          "the",
          "$father,",
          "full",
          "of",
          "$gift",
          "$plus",
          "$check.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "John",
          "$witness$ed",
          "about",
          "$pointing_back.",
          "He",
          "cried",
          "out,",
          "$speech,",
          "“This",
          "was",
          "He",
          "of",
          "whom",
          "I",
          "$speech,",
          "‘He",
          "who",
          "$footprints",
          "after",
          "me",
          "has",
          "surpassed",
          "me,",
          "$pointing",
          "He",
          "was",
          "before",
          "me.’”",
        ],
      },
      {
        verse_number: 16,
        words: [
          "$tray_out",
          "$pointing_back’s",
          "fullness",
          "we",
          "have",
          "all",
          "$hand_receiving$d",
          "$gift",
          "upon",
          "$gift.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "$pointing",
          "the",
          "$scroll",
          "was",
          "$hands_giving$n",
          "through",
          "Moses;",
          "$gift",
          "$plus",
          "$check",
          "came",
          "through",
          "$cross",
          "$oil.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "No",
          "one",
          "has",
          "ever",
          "$eye$n",
          "$fire.",
          "The",
          "one",
          "and",
          "only",
          "$fire,",
          "who",
          "is",
          "at",
          "the",
          "$father’s",
          "side,",
          "has",
          "made",
          "Him",
          "known.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "This",
          "was",
          "John’s",
          "$witness",
          "when",
          "the",
          "$menorah",
          "$tray_out",
          "Jerusalem",
          "sent",
          "priests",
          "$plus",
          "Levites",
          "to",
          "ask",
          "$pointing_back,",
          "“Who",
          "are",
          "you?”",
        ],
      },
      {
        verse_number: 20,
        words: [
          "He",
          "confessed",
          "$plus",
          "did",
          "$no_entry",
          "deny,",
          "but",
          "confessed",
          "$pointing",
          "“I",
          "am",
          "$no_entry",
          "the",
          "$oil.”",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$plus",
          "they",
          "asked",
          "$pointing_back,",
          "“Who",
          "then?",
          "Are",
          "you",
          "Elijah?”",
          "$plus",
          "he",
          "$speech,",
          "“I",
          "am",
          "$no_entry.”",
          "“Are",
          "you",
          "the",
          "$megaphone?”",
          "$plus",
          "he",
          "answered,",
          "“$no_entry.”",
        ],
      },
      {
        verse_number: 22,
        words: [
          "So",
          "they",
          "$speech",
          "to",
          "$pointing_back,",
          "“Who",
          "are",
          "you?",
          "We",
          "must",
          "$hands_giving",
          "an",
          "answer",
          "to",
          "those",
          "who",
          "sent",
          "us.",
          "What",
          "do",
          "you",
          "$speech",
          "about",
          "yourself?”",
        ],
      },
      {
        verse_number: 23,
        words: [
          "He",
          "$speech,",
          "“I",
          "am",
          "a",
          "$voice",
          "of",
          "one",
          "calling",
          "$tray_in",
          "the",
          "wilderness,",
          "‘Make",
          "straight",
          "the",
          "$road",
          "for",
          "the",
          "$crown,’”",
          "as",
          "Isaiah",
          "the",
          "$megaphone",
          "$speech.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "Now",
          "those",
          "who",
          "had",
          "been",
          "sent",
          "were",
          "$tray_out",
          "the",
          "Pharisees.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "$plus",
          "they",
          "$speech",
          "to",
          "$pointing_back,",
          "“Why",
          "then",
          "do",
          "you",
          "baptize,",
          "if",
          "you",
          "are",
          "$no_entry",
          "the",
          "$oil,",
          "nor",
          "Elijah,",
          "nor",
          "the",
          "$megaphone?”",
        ],
      },
      {
        verse_number: 26,
        words: [
          "John",
          "$speech,",
          "“I",
          "baptize",
          "$tray_in",
          "water,",
          "but",
          "among",
          "you",
          "stands",
          "One",
          "you",
          "do",
          "$no_entry",
          "$lightbulb.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "He",
          "is",
          "the",
          "One",
          "who",
          "$footprints",
          "after",
          "me,",
          "whose",
          "sandal",
          "straps",
          "I",
          "am",
          "$no_entry",
          "worthy",
          "to",
          "untie.”",
        ],
      },
      {
        verse_number: 28,
        words: [
          "All",
          "this",
          "happened",
          "$tray_in",
          "Bethany",
          "beyond",
          "the",
          "Jordan,",
          "where",
          "John",
          "was",
          "baptizing.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "The",
          "next",
          "day",
          "John",
          "$eyes",
          "$cross",
          "$footprints",
          "toward",
          "$pointing_back",
          "$plus",
          "$speech,",
          "“Look,",
          "the",
          "Lamb",
          "of",
          "$fire,",
          "who",
          "takes",
          "away",
          "the",
          "$bow",
          "of",
          "the",
          "$globe!",
        ],
      },
      {
        verse_number: 30,
        words: [
          "This",
          "is",
          "He",
          "of",
          "whom",
          "I",
          "$speech,",
          "‘A",
          "$man_beard",
          "who",
          "$footprints",
          "after",
          "me",
          "has",
          "surpassed",
          "me,",
          "$pointing",
          "He",
          "was",
          "before",
          "me.’",
        ],
      },
      {
        verse_number: 31,
        words: [
          "I",
          "myself",
          "did",
          "$no_entry",
          "$lightbulb",
          "$pointing_back,",
          "but",
          "I",
          "$footprints",
          "baptizing",
          "$tray_in",
          "water",
          "so",
          "that",
          "He",
          "might",
          "be",
          "revealed",
          "to",
          "Israel.”",
        ],
      },
      {
        verse_number: 32,
        words: [
          "$plus",
          "John",
          "$witness$ed,",
          "$speech,",
          "“$pointing",
          "I",
          "saw",
          "the",
          "$wind",
          "descending",
          "like",
          "a",
          "dove",
          "$tray_out",
          "$sky,",
          "$plus",
          "resting",
          "on",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "I",
          "myself",
          "did",
          "$no_entry",
          "$lightbulb",
          "$pointing_back,",
          "but",
          "the",
          "One",
          "who",
          "sent",
          "me",
          "to",
          "baptize",
          "$tray_in",
          "water",
          "$speech",
          "to",
          "me,",
          "‘The",
          "One",
          "on",
          "whom",
          "you",
          "$eye",
          "the",
          "$wind",
          "descend",
          "$plus",
          "rest",
          "is",
          "He",
          "who",
          "will",
          "baptize",
          "$tray_in",
          "the",
          "$sparkle",
          "$wind.’",
        ],
      },
      {
        verse_number: 34,
        words: [
          "$plus",
          "I",
          "have",
          "$eye$n",
          "$plus",
          "$witness$ed",
          "$pointing",
          "this",
          "is",
          "the",
          "$son",
          "of",
          "$fire.”",
        ],
      },
      {
        verse_number: 35,
        words: [
          "The",
          "next",
          "day",
          "John",
          "was",
          "there",
          "again",
          "with",
          "two",
          "of",
          "$pointing_back’s",
          "$learner$s.",
        ],
      },
      {
        verse_number: 36,
        words: [
          "When",
          "he",
          "saw",
          "$cross",
          "walking",
          "by,",
          "he",
          "$speech,",
          "“Look,",
          "the",
          "Lamb",
          "of",
          "$fire!”",
        ],
      },
      {
        verse_number: 37,
        words: [
          "$plus",
          "when",
          "the",
          "two",
          "$learner$s",
          "$ear",
          "$pointing_back",
          "$mouth",
          "this,",
          "they",
          "followed",
          "$cross.",
        ],
      },
      {
        verse_number: 38,
        words: [
          "$cross",
          "turned",
          "$plus",
          "saw",
          "them",
          "following,",
          "$plus",
          "$speech",
          "to",
          "$pointing_back,",
          "“What",
          "do",
          "you",
          "want?”",
          "They",
          "$speech,",
          "“Rabbi”",
          "(which",
          "means",
          "Teacher),",
          "“where",
          "are",
          "You",
          "staying?”",
        ],
      },
      {
        verse_number: 39,
        words: [
          "He",
          "$speech,",
          "“Come",
          "$plus",
          "$eye.”",
          "So",
          "they",
          "$footprints",
          "$plus",
          "$eye",
          "where",
          "He",
          "was",
          "staying,",
          "$plus",
          "they",
          "stayed",
          "with",
          "$pointing_back",
          "that",
          "$sun.",
          "It",
          "was",
          "about",
          "the",
          "tenth",
          "hour.",
        ],
      },
      {
        verse_number: 40,
        words: [
          "Andrew,",
          "Simon",
          "Peter’s",
          "$brother,",
          "was",
          "one",
          "$tray_out",
          "the",
          "two",
          "who",
          "$ear",
          "John",
          "$plus",
          "followed",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 41,
        words: [
          "He",
          "first",
          "found",
          "his",
          "own",
          "$brother",
          "Simon",
          "$plus",
          "$speech",
          "to",
          "$pointing_back,",
          "“We",
          "have",
          "found",
          "the",
          "Messiah”",
          "(which",
          "is",
          "translated",
          "$oil).",
        ],
      },
      {
        verse_number: 42,
        words: [
          "He",
          "brought",
          "$pointing_back",
          "to",
          "$cross.",
          "$cross",
          "looked",
          "at",
          "$pointing_back",
          "$plus",
          "$speech,",
          "“You",
          "are",
          "Simon",
          "$son",
          "of",
          "John.",
          "You",
          "will",
          "be",
          "called",
          "Cephas”",
          "(which",
          "is",
          "translated",
          "Peter).",
        ],
      },
      {
        verse_number: 43,
        words: [
          "The",
          "next",
          "day",
          "$cross",
          "decided",
          "to",
          "set",
          "out",
          "for",
          "Galilee.",
          "$plus",
          "finding",
          "Philip,",
          "He",
          "$speech",
          "to",
          "$pointing_back,",
          "“Follow",
          "Me.”",
        ],
      },
      {
        verse_number: 44,
        words: [
          "Now",
          "Philip",
          "was",
          "from",
          "Bethsaida,",
          "$tray_out",
          "the",
          "$city",
          "of",
          "Andrew",
          "$plus",
          "Peter.",
        ],
      },
      {
        verse_number: 45,
        words: [
          "Philip",
          "found",
          "Nathanael",
          "$plus",
          "$speech",
          "to",
          "$pointing_back,",
          "“We",
          "have",
          "found",
          "the",
          "One",
          "Moses",
          "wrote",
          "about",
          "$tray_in",
          "the",
          "$scroll,",
          "$plus",
          "about",
          "whom",
          "the",
          "$megaphone$s",
          "wrote:",
          "$cross",
          "of",
          "Nazareth,",
          "the",
          "$son",
          "of",
          "Joseph.”",
        ],
      },
      {
        verse_number: 46,
        words: [
          "“Can",
          "anything",
          "$thumbs_up",
          "come",
          "$tray_out",
          "Nazareth?”",
          "Nathanael",
          "$speech.",
          "“$footprints",
          "$plus",
          "see,”",
          "Philip",
          "$speech.",
        ],
      },
      {
        verse_number: 47,
        words: [
          "$cross",
          "$eye",
          "Nathanael",
          "$footprints",
          "toward",
          "$pointing_back",
          "$plus",
          "$speech",
          "of",
          "$pointing_back,",
          "“Here",
          "is",
          "a",
          "true",
          "Israelite,",
          "$tray_in",
          "whom",
          "there",
          "is",
          "$no_entry",
          "deceit.”",
        ],
      },
      {
        verse_number: 48,
        words: [
          "“How",
          "do",
          "You",
          "$lightbulb",
          "me?”",
          "Nathanael",
          "$speech.",
          "$cross",
          "answered,",
          "“Before",
          "Philip",
          "called",
          "you,",
          "while",
          "you",
          "were",
          "under",
          "the",
          "fig",
          "tree,",
          "I",
          "$eye",
          "you.”",
        ],
      },
      {
        verse_number: 49,
        words: [
          "“Rabbi,”",
          "Nathanael",
          "answered,",
          "“You",
          "are",
          "the",
          "$son",
          "of",
          "$fire!",
          "You",
          "are",
          "the",
          "$king",
          "of",
          "Israel!”",
        ],
      },
      {
        verse_number: 50,
        words: [
          "$cross",
          "$speech",
          "to",
          "$pointing_back,",
          "“Do",
          "you",
          "$anchor",
          "$pointing",
          "I",
          "$speech",
          "to",
          "you,",
          "‘I",
          "$eye",
          "you",
          "under",
          "the",
          "fig",
          "tree’?",
          "You",
          "will",
          "$eye",
          "greater",
          "things",
          "than",
          "these.”",
        ],
      },
      {
        verse_number: 51,
        words: [
          "$plus",
          "He",
          "declared,",
          "“$check,",
          "$check,",
          "I",
          "$speech",
          "to",
          "you,",
          "you",
          "will",
          "$eye",
          "$sky",
          "opened",
          "$plus",
          "the",
          "$angel$s",
          "of",
          "$fire",
          "ascending",
          "$plus",
          "descending",
          "on",
          "the",
          "$son",
          "of",
          "$person.”",
        ],
      },
    ],
  };
  return chapter;
}
