export function bible_glyph_chapter_psa019() {
  "The nineteenth psalm, drawn in pictures. Six verses about the sky, then six about the law, then two of a man asking to be kept. It is fourteen lines long and the join in the middle is the most argued about seam in the psalms, because the two halves look like two different poems.";
  "THE FIRST SIX VERSES NEVER WRITE THE NAME AND THE NEXT THREE WRITE IT SIX TIMES. The sky half calls God by the short general word, once, in the opening line, and then says nothing more about who He is - it is all heavens, day, night, earth, world and a sun running its course. The moment the psalm turns to the law, the covenant name appears and does not stop: six times in three verses, then once more in the last line. In English both halves say God or the LORD and a reader has no way of knowing the words changed. In pictures the second half is suddenly covered in one mark that was completely absent from the first. That is the whole argument of the psalm made visible: the sky tells you there is a God, and the law tells you His name.";
  "SIX STATEMENTS ABOUT THE LAW, SIX NAME MARKS, ONE EACH. Verses seven, eight and nine are six sentences in the same shape - the law is perfect, the testimony is trustworthy, the precepts are right, the commandments are radiant, the fear is pure, the judgments are true. Each one carries exactly one name mark, so the middle of the page is a column of six identical pictures at even spacing. English readers feel that repetition; a reader who cannot read English can see it.";
  "THE MIDDLE OF THE PSALM IS ABOUT THE SUN AND THE SUN IS NEVER DRAWN. Verses four, five and six are the tent pitched for the sun, the bridegroom, the champion running his course, and the circuit from one end of the heavens to the other. Not one mark falls on any of it. The mark that looks like a sun is used twice in the second verse, on the word day, because that is the word it is seated on. So the reader must learn early that the mark means a day and not the thing in the sky - and this page is a good place to learn it, because here the two stand a few lines apart.";
  "THE ONLY TURNING ON THE PAGE IS WHAT THE LAW DOES TO A SOUL. The seventh verse says the Law of the LORD is perfect, reviving the soul, and reviving there is the ordinary Hebrew word for turning something back. It is the same word used elsewhere for a whole nation repenting. Here it is what a book does to a person. The mark falls once in the psalm and this is where.";
  "THE HEART IS DRAWN TWICE, ONCE RECEIVING AND ONCE OFFERING. In the eighth verse the precepts of the LORD bring joy to the heart. In the fourteenth the meditation of the heart is what the man hopes will be pleasing. The two marks sit at either side of the closing section, and between them is a servant kneeling twice, asking to be cleansed of what he cannot see and kept from what he can. The one crossing out mark on the page is in that request - may they not rule over me.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA019",
    reference: "Psalm 19",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "$sky",
          "declare",
          "the",
          "$star",
          "of",
          "$fire;",
          "the",
          "skies",
          "proclaim",
          "the",
          "work",
          "of",
          "His",
          "$hand.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$sun",
          "after",
          "$sun",
          "they",
          "pour",
          "forth",
          "speech;",
          "night",
          "after",
          "night",
          "they",
          "reveal",
          "knowledge.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Without",
          "speech",
          "or",
          "language,",
          "without",
          "a",
          "$voice",
          "to",
          "be",
          "$ear,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "their",
          "voice",
          "has",
          "gone",
          "out",
          "into",
          "all",
          "the",
          "$earth,",
          "their",
          "words",
          "to",
          "the",
          "ends",
          "of",
          "the",
          "$globe.",
          "In",
          "the",
          "heavens",
          "He",
          "has",
          "pitched",
          "a",
          "tent",
          "for",
          "the",
          "sun.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Like",
          "a",
          "bridegroom",
          "emerging",
          "from",
          "his",
          "chamber,",
          "like",
          "a",
          "champion",
          "rejoicing",
          "to",
          "run",
          "his",
          "course.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "It",
          "rises",
          "at",
          "one",
          "end",
          "of",
          "the",
          "$sky",
          "and",
          "runs",
          "its",
          "circuit",
          "to",
          "the",
          "other;",
          "nothing",
          "is",
          "deprived",
          "of",
          "its",
          "warmth.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$scroll",
          "of",
          "the",
          "$name_tag",
          "is",
          "perfect,",
          "$turn_back",
          "the",
          "$person_other;",
          "the",
          "$witness",
          "of",
          "the",
          "$name_tag",
          "is",
          "$anchor,",
          "making",
          "wise",
          "the",
          "simple.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "precepts",
          "of",
          "the",
          "$name_tag",
          "are",
          "right,",
          "bringing",
          "joy",
          "to",
          "the",
          "$heart_organ;",
          "the",
          "$scroll",
          "of",
          "the",
          "$name_tag",
          "are",
          "radiant,",
          "giving",
          "light",
          "to",
          "the",
          "$eyes.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "fear",
          "of",
          "the",
          "$name_tag",
          "is",
          "pure,",
          "enduring",
          "forever;",
          "the",
          "$scales",
          "of",
          "the",
          "$name_tag",
          "are",
          "$check,",
          "being",
          "altogether",
          "$ruler.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "They",
          "are",
          "more",
          "precious",
          "than",
          "gold,",
          "than",
          "much",
          "pure",
          "gold;",
          "they",
          "are",
          "sweeter",
          "than",
          "honey,",
          "than",
          "honey",
          "from",
          "the",
          "comb.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "By",
          "them",
          "indeed",
          "Your",
          "$kneeling",
          "is",
          "warned;",
          "in",
          "keeping",
          "them",
          "is",
          "great",
          "reward.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Who",
          "can",
          "discern",
          "his",
          "own",
          "errors?",
          "Cleanse",
          "me",
          "from",
          "my",
          "hidden",
          "faults.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Keep",
          "Your",
          "$kneeling",
          "also",
          "from",
          "willful",
          "sins;",
          "may",
          "they",
          "$no_entry",
          "rule",
          "over",
          "me.",
          "Then",
          "I",
          "will",
          "be",
          "blameless",
          "and",
          "cleansed",
          "of",
          "great",
          "transgression.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "May",
          "the",
          "words",
          "of",
          "my",
          "mouth",
          "and",
          "the",
          "meditation",
          "of",
          "my",
          "$heart_organ",
          "be",
          "pleasing",
          "in",
          "Your",
          "sight,",
          "O",
          "$name_tag,",
          "my",
          "Rock",
          "and",
          "my",
          "Redeemer.",
        ],
      },
    ],
  };
  return chapter;
}
