export function bible_glyph_chapter_lam05() {
  "Lamentations 5, drawn in pictures. The last chapter of the book and the shortest one, and the only one of the five that is not an alphabet poem - it still has twenty two lines, one for each Hebrew letter, but the letters have stopped lining up. It is a prayer said out loud by a whole town at once, and it does not end well. The fifth and final chapter of Lamentations.";
  "THE LAST VERSE OF THE BOOK HAS NO PICTURE ON IT AT ALL. Unless You have utterly rejected us and remain angry with us beyond measure. That is how the book of Lamentations ends - on a word that means unless, with the sentence left hanging. The line closes on thirteen plain English words and not one picture. Nothing was held back to make that happen; the root table simply has no seat for any word in the line. A reader who knows no English gets exactly what a reader who does gets here, which is silence.";
  "THE TWENTY FIRST VERSE DRAWS THE SAME PICTURE TWICE AND THAT IS THE WHOLE PRAYER. Restore us to Yourself, O LORD, so we may return. Restore and return are one Hebrew word said twice, and this Bible draws it as an arrow curving back the way it came. So the line reads: turn us back, name of God, and we will turn back. God moves first and the people move second, and a reader sees it as one shape repeated. The same word falls eleven times in the first chapter of Ruth, where it is everybody going home; here it is the last thing the town asks for.";
  "THE ONE VERSE THAT SAYS CROWN CANNOT DRAW A CROWN. The sixteenth verse is, The crown has fallen from our head. Woe to us, for we have sinned. This Bible does have a crown picture, but it is seated on the Hebrew word for Lord, not on the object, and the actual headpiece in this line is a different word with no seat at all. So the verse about a crown coming off arrives with one mark on it, and the mark is the archery bow for sin. The crown really has gone.";
  "FIVE VERSES IN THIS CHAPTER CARRY NO MARK AND THEY ARE THE ONES ABOUT BODIES AND SILENCE. We have become fatherless orphans; our mothers are widows. Our skin is as hot as an oven with fever from our hunger. The elders have left the city gate; the young men have stopped their music. Why have You forgotten us forever? And then the last verse. Orphans, widows, skin, hunger, an empty gate, stopped music, and a question with no answer - none of it can be drawn, and the effect of that on the page is a chapter that goes quiet in exactly the places it is describing quiet.";
  "TWO HEARTS AND A PAIR OF EYES IN TWO LINES RUNNING. Joy has left our hearts, says the fifteenth verse. Because of this our hearts are faint; because of these our eyes grow dim, says the seventeenth. Both hearts are the beating organ rather than the red love heart, because the Hebrew means the thing inside the chest, and the eyes beside them are the ones going dark. There are only two refusal marks in the whole chapter, which is strange for a page that is nothing but loss - almost everything taken here is described by naming what was taken, not by saying no.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "LAM05",
    reference: "Lamentations 5",
    verses: [
      {
        verse_number: 1,
        words: [
          "Remember,",
          "O",
          "$name_tag,",
          "what",
          "has",
          "happened",
          "to",
          "us.",
          "Look",
          "and",
          "$eye",
          "our",
          "disgrace!",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Our",
          "inheritance",
          "has",
          "been",
          "turned",
          "over",
          "to",
          "strangers,",
          "our",
          "$house",
          "to",
          "foreigners.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "We",
          "have",
          "become",
          "fatherless",
          "orphans;",
          "our",
          "mothers",
          "are",
          "widows.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "We",
          "must",
          "buy",
          "the",
          "$water",
          "we",
          "drink;",
          "our",
          "$tree",
          "$footprints",
          "at",
          "a",
          "price.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "We",
          "are",
          "closely",
          "pursued;",
          "we",
          "are",
          "weary",
          "and",
          "find",
          "$no_entry",
          "rest.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "We",
          "$hands_giving",
          "to",
          "Egypt",
          "and",
          "Assyria",
          "to",
          "get",
          "enough",
          "$bread.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Our",
          "$father",
          "$bow",
          "and",
          "are",
          "no",
          "more,",
          "but",
          "we",
          "bear",
          "their",
          "punishment.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$kneeling",
          "rule",
          "over",
          "us;",
          "there",
          "is",
          "no",
          "one",
          "to",
          "deliver",
          "us",
          "from",
          "their",
          "$hand.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "We",
          "$footprints",
          "our",
          "$bread",
          "at",
          "the",
          "risk",
          "of",
          "our",
          "$person_other",
          "because",
          "of",
          "the",
          "$sword",
          "in",
          "the",
          "wilderness.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Our",
          "skin",
          "is",
          "as",
          "hot",
          "as",
          "an",
          "oven",
          "with",
          "fever",
          "from",
          "our",
          "hunger.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$woman",
          "have",
          "been",
          "ravished",
          "in",
          "Zion,",
          "virgins",
          "in",
          "the",
          "$city",
          "of",
          "Judah.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Princes",
          "have",
          "been",
          "hung",
          "up",
          "by",
          "their",
          "$hand;",
          "elders",
          "receive",
          "$no_entry",
          "respect.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Young",
          "men",
          "toil",
          "at",
          "millstones;",
          "boys",
          "stagger",
          "under",
          "loads",
          "of",
          "$tree.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "elders",
          "have",
          "left",
          "the",
          "city",
          "gate;",
          "the",
          "young",
          "men",
          "have",
          "stopped",
          "their",
          "music.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Joy",
          "has",
          "left",
          "our",
          "$heart_organ;",
          "our",
          "dancing",
          "has",
          "turned",
          "to",
          "mourning.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "The",
          "crown",
          "has",
          "fallen",
          "from",
          "our",
          "head.",
          "Woe",
          "to",
          "us,",
          "for",
          "we",
          "have",
          "$bow!",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Because",
          "of",
          "this",
          "our",
          "$heart_organ",
          "are",
          "faint;",
          "because",
          "of",
          "these",
          "our",
          "$eyes",
          "grow",
          "dim",
        ],
      },
      {
        verse_number: 18,
        words: [
          "because",
          "of",
          "$mountain",
          "Zion,",
          "which",
          "lies",
          "desolate,",
          "$walking",
          "by",
          "foxes.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "You,",
          "O",
          "$name_tag,",
          "reign",
          "$hourglass;",
          "Your",
          "throne",
          "endures",
          "from",
          "generation",
          "to",
          "generation.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Why",
          "have",
          "You",
          "forgotten",
          "us",
          "forever?",
          "Why",
          "have",
          "You",
          "forsaken",
          "us",
          "for",
          "so",
          "long?",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$turn_back",
          "us",
          "to",
          "Yourself,",
          "O",
          "$name_tag,",
          "so",
          "we",
          "may",
          "$turn_back;",
          "renew",
          "our",
          "$sun",
          "as",
          "of",
          "old,",
        ],
      },
      {
        verse_number: 22,
        words: [
          "unless",
          "You",
          "have",
          "utterly",
          "rejected",
          "us",
          "and",
          "remain",
          "angry",
          "with",
          "us",
          "beyond",
          "measure.",
        ],
      },
    ],
  };
  return chapter;
}
