export function bible_scene_division_brief() {
  "The whole brief for deciding what a scene is: the unit that gets read aloud and rendered once, how it is addressed, and what happens where several books tell the same thing.";
  "★ THIS IS THE ONE ASSET THAT SURVIVES EVERY CHOICE NOT YET MADE. Still pictures, moving ones, three dimensions, a game or no game - all of them need to know where a scene starts and stops, and none of them changes the answer. So it can be settled now, while rendering cannot, and settling it is the only work here that cannot be wasted by a later change of mind.";
  "★ THE SHAPE ALREADY EXISTS AND THE DISCIPLINE FOR FILLING IT DOES NOT. A gathered event is a title and a list of passages, and there are 248 of them across Genesis, Exodus and Numbers. Thirteen hold more than one passage - and every single one of those is a run of adjacent chapters, a scene the chapter division happened to cut in half. So the container that would hold four Gospel accounts of one afternoon has never once been used for that, and anybody reading the data and concluding the question is answered has read thirteen chapter repairs.";
  "★ NO GOSPEL IS GATHERED YET, AND ONE PART OF THIS IS CHEAP TODAY AND EXPENSIVE LATER. The corpus is three books of the Law. The expensive mistake is not choosing the wrong rendering - that is recoverable, as the rendering paragraphs below show - it is gathering scenes that throw the parallel passages away, because no later choice can get them back and some hundreds of scenes then need re-cutting by hand. Gather so that both renderings stay possible, and the rendering can be argued about afterwards.";
  "★ A SCENE IS WHAT IS READ ALOUD, AND THAT SETTLES MOST OF THE QUESTION BY ITSELF. The reading is already fixed elsewhere as the foundation of delivering a word, and it is what a cutscene is built on too. Nobody can read four accounts aloud at once. So a scene has exactly one reading, and a scene assembled out of parallel accounts would force somebody to choose which account is the one heard - a decision about Scripture wearing the clothes of a decision about rendering.";
  "★ SCENES DIVIDE BY TEXT AND DEPICTIONS CONSOLIDATE BY SUBJECT, WHICH IS HOW BOTH THINGS ARE HAD AT ONCE. Whatever a scene turns out to be, the hillside, the boy, the basket of loaves and the face of Jesus are one each, because a depiction is not a text. That way nothing is flattened - Mark keeps his green grass and John keeps his boy - and the drawing is still made once. The saving people hope to get from a harmony is real, and it lives in the depictions rather than in the text.";
  "★ ONE READING RULES OUT BLENDING AND LEAVES TWO WAYS STANDING, WHICH IS LESS THAN AN EARLIER DRAFT HERE CLAIMED. It said four accounts meant four scenes, treating that as settled by the one-reading rule; it is not, and the rule is narrower than the conclusion drawn from it.";
  "The way that is ruled out is BLENDING: one text assembled out of four, which forces somebody to choose whose wording is heard and deletes what the other three said.";
  "The first way that stands is SERIAL: each account is its own scene with its own reading, taken in turn. Nothing is lost and nothing is chosen, at the cost of a viewer hearing the same afternoon four times.";
  "The second way that stands is PRIMARY AND GLOSSED: one account is read, and where another book carries a detail this one does not, that detail is heard as a direct quotation, marked plainly as coming from elsewhere. It is one reading, so the rule is satisfied, and it differs from blending in the one way that matters - the seams are shown rather than hidden, so nothing is presented as the primary account's words that is not. It is the passage glossed by its cross-references, which is a discipline this repo already has for words.";
  "★ PRIMARY AND GLOSSED IS CHOSEN, AND SERIAL IS KEPT AS A SECOND RENDERING RATHER THAN DISCARDED. Somebody who wants each account whole and in turn should be able to ask for that and have the videos and the readings generated for them, so serial becomes an option offered rather than a road not taken.";
  "★ THAT IS WHY THE CHOICE TURNS OUT NOT TO BE EXPENSIVE, AND THE CONDITION IS EXACT. Both renderings are generated from one gathering, so long as the scene records every parallel passage and says which one is primary - serial reads them one after another, glossed reads the primary and quotes the rest. What would have been expensive is a gathering that kept only the primary passage and threw the parallels away, because no later choice could get them back. So the rule for gathering is: keep all four, mark one.";
  "It follows that primary and glossed is a rendering decision and not a division decision, which is why it can be made today and revisited without re-cutting anything.";
  "That is also where the character designs live, and why designing them is not wasted at any rendering level. A design carries from a still to a moving picture to a modelled one - a figure sculpted from turnaround drawings is the ordinary way that is done - even though not one rendered frame carries. Consistency from picture to picture is a property of the design and not of the pictures, so it is settled once, in the depictions, and every scene that names a figure gets it.";
  "★ GATHERING COLLECTS AND DOES NOT SELECT, BECAUSE ONLY THE BUILDER KNOWS WHAT CAN BE BUILT. Whoever makes the cutscene or the game is the one who can say I can find a way to do this or I do not know how to do this, and a gatherer answering that in advance takes the choice away from the only person holding it. So everything is carried now and chosen later, and a scene nobody yet knows how to use is kept as a scene nobody yet knows how to use.";
  "★ THAT COLLIDES WITH THE ONE FILTER THE EXISTING CORPUS ALREADY APPLIES, AND SOMEBODY HAS TO SETTLE IT. The gathered spans keep only what HAPPENS, WITH AGENTS, which is what leaves the genealogies out - GEN05 in part, GEN10 entire, GEN11:10-30, the line of Cain. Those are named in prose at the foot of each span, so a reader can find them, but they are not in the data, so nothing can ask for them and no builder is ever offered them. Under the rule above that is a selection made too early. The repair is to carry the absences as data beside the events with the reason attached, not to widen the filter and lose the judgement.";
  "★ A PIECE IS A PART OF A SCENE SOMEBODY COULD BUILD SOMETHING OUT OF, AND THE KINDS MAY ALREADY BE KNOWN. Reading the twenty dream passages turned up four things a player can be asked to do - put a shape there, make something move, get a number right, carry a sentence whole - and there is reason to think those are not particular to dreams. A scene is made of shapes, movements, counts and words wherever it is set. Whether the Gospel scenes gathered so far break that vocabulary is the next thing to test, and finding a fifth kind would be a result rather than a failure.";
  "An account only one book carries is not a special case under this rule. It is one reading, so it is one scene, exactly like the other three.";
  let brief = {
    step: "scene division",
    what: "the unit that is read aloud once and rendered once, and how it is addressed",
    settled:
      "a scene has exactly one reading; the accounts differ and the differences are Scripture; blended text is ruled out; primary-and-glossed is the rendering, with serial offered as a second one generated from the same gathering; a scene keeps every parallel passage and marks which is primary",
    open: "how a quotation from another book is marked as coming from elsewhere; which account is primary where the choice is not obvious; how a depiction is addressed and shared between scenes; how a scene too long to hear in one sitting is handled",
    forbidden:
      "merging parallel accounts into one text; picking one account as the true one; a scene with two readings; gathering a scene that keeps only its primary passage",
    done: "every Gospel can be gathered without later re-cutting, one afternoon on a hillside is drawn once, and nothing any of the four books says has been dropped",
  };
  return brief;
}
