export function bible_glyph_chapter_psa096() {
  "The fifty fifth picture Bible chapter written by hand: the whole of the ninety sixth psalm, a new song for all the earth and the LORD coming to judge it, in the shorthand a person types.";
  "IT IS THE SECOND OF THE REIGNING PSALMS AND IT SHARES ITS CENTRE WITH THE FIRST. Thirteen verses, forty two in a hundred. The ninety seventh psalm opens on the castle mark; this one saves it for the tenth verse, where it is the thing to be said out loud among the nations. Two pages, the same three words at the hinge of each, put in opposite places. Read together they are one argument told twice, and the mark is what makes that visible without a commentary.";
  "THE NAME MARK IS STOOD DOWN TWICE AND BOTH TIMES IT IS GODS OWN NAME. The second verse blesses His name and the eighth gives glory due His name, and in both the Hebrew word is shem, which the root table seats on the same picture it uses for the LORD. Writing the mark there would have said bless the LORD, which is close but is not what the line says: the psalm is careful to speak of the name as a thing of its own. So it is left in letters at both. Earlier pages needed the same removal for a king, three rivers and a wife, which is an ordinary name being mistaken for the Name. Here it is the other direction, and the ninety seventh psalm does it once at its last verse too. Both cases come out of one seat carrying two jobs.";
  "THREE WORDS MEAN EVERYBODY AND ONLY TWO OF THEM ARE DRAWN. The family mark falls five times and the map mark twice, and the third and tenth verses put both in the same breath - His glory among the nations, His wonders among all peoples. English hands you two near synonyms and lets you assume they are decoration. The marks show them as two different words doing the same work from two different angles, one about tribes and one about territory.";
  "THE GODS OF THE PEOPLES GET THE SAME PICTURE AS GOD. The fourth verse has Him feared above all gods and the fifth says those gods are idols, and both times the word is drawn with the fire mark - the same mark that stands for God everywhere else on the list. That is not the table being careless. Hebrew uses one word, elohim, for both, and the psalm is arguing about which one it belongs to. A reader who sees the same picture on both sides of the fifth verse has the argument in front of them.";
  "THE EARTH IS A CHARACTER HERE AND NOT A PLACE. It is told to sing in the first verse, to tremble in the ninth, to rejoice in the eleventh, and it is what He comes to judge in the last. Around it the sea resounds, the fields exult and the trees of the forest sing; the sea and the trees are drawn and the fields are not. The shape holds either way: nothing on this page is asked to praise Him that is not either a person or a piece of ground.";
  "THE COMING MARK FALLS TWICE IN THE LAST VERSE AND THAT REPEAT IS THE POINT. He is coming, He is coming to judge the earth. Hebrew says the word twice on purpose and English keeps it, and here the picture is doubled too, so the emphasis survives into a reading that has no grammar in it at all. The same mark closes the eighth verse, where it is the worshipper who comes into His courts. The traffic goes both ways on this page.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA096",
    reference: "Psalm 96",
    verses: [
      {
        verse_number: 1,
        words: [
          "Sing",
          "to",
          "the",
          "$name_tag",
          "a",
          "new",
          "song;",
          "sing",
          "to",
          "the",
          "$name_tag,",
          "all",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Sing",
          "to",
          "the",
          "$name_tag,",
          "$speech+thumbs_up",
          "His",
          "name;",
          "proclaim",
          "His",
          "salvation",
          "$sun",
          "after",
          "$sun.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Declare",
          "His",
          "$star",
          "among",
          "the",
          "$map,",
          "His",
          "wonders",
          "among",
          "all",
          "$family.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "For",
          "great",
          "is",
          "the",
          "$name_tag,",
          "and",
          "greatly",
          "to",
          "be",
          "praised;",
          "He",
          "is",
          "to",
          "be",
          "feared",
          "above",
          "all",
          "$fire.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "For",
          "all",
          "the",
          "$fire",
          "of",
          "the",
          "$family",
          "are",
          "idols,",
          "but",
          "the",
          "$name_tag",
          "$hammer",
          "the",
          "$sky.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Splendor",
          "and",
          "majesty",
          "are",
          "before",
          "Him;",
          "strength",
          "and",
          "beauty",
          "fill",
          "His",
          "sanctuary.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Ascribe",
          "to",
          "the",
          "$name_tag,",
          "O",
          "families",
          "of",
          "the",
          "$family,",
          "ascribe",
          "to",
          "the",
          "$name_tag",
          "$star",
          "and",
          "strength.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Ascribe",
          "to",
          "the",
          "$name_tag",
          "the",
          "$star",
          "due",
          "His",
          "name;",
          "bring",
          "an",
          "offering",
          "and",
          "$footprints",
          "into",
          "His",
          "courts.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$bowing",
          "the",
          "$name_tag",
          "in",
          "the",
          "splendor",
          "of",
          "$sparkle;",
          "tremble",
          "before",
          "Him,",
          "all",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$speech",
          "among",
          "the",
          "$map,",
          "The",
          "$name_tag",
          "$castle!",
          "The",
          "$globe",
          "is",
          "firmly",
          "established;",
          "it",
          "cannot",
          "be",
          "moved.",
          "He",
          "will",
          "judge",
          "the",
          "$family",
          "with",
          "equity.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Let",
          "the",
          "$sky",
          "be",
          "glad",
          "and",
          "the",
          "$earth",
          "rejoice;",
          "let",
          "the",
          "$sea",
          "resound,",
          "and",
          "all",
          "that",
          "fills",
          "it.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Let",
          "the",
          "fields",
          "exult,",
          "and",
          "all",
          "that",
          "is",
          "in",
          "them.",
          "Then",
          "all",
          "the",
          "$tree",
          "of",
          "the",
          "forest",
          "will",
          "sing",
          "for",
          "joy",
        ],
      },
      {
        verse_number: 13,
        words: [
          "before",
          "the",
          "$name_tag,",
          "for",
          "He",
          "$footprints;",
          "He",
          "$footprints",
          "to",
          "judge",
          "the",
          "$earth.",
          "He",
          "will",
          "judge",
          "the",
          "$globe",
          "in",
          "$ruler",
          "and",
          "the",
          "$family",
          "in",
          "His",
          "faithfulness.",
        ],
      },
    ],
  };
  return chapter;
}
