export function bible_dream_hand_fade_far() {
  "How far from a stroke a hand has to stray, in the drawing's own units, for its own mark to have faded halfway to the faintest it goes.";
  "★ IT IS NOT THE CORRIDOR, AND IT USED TO BE, WHICH IS WHY THE FADING COULD HARDLY BE SEEN. The corridor is five units to a side, so measuring the fade against it spent the whole visible difference inside the corridor and had nothing left for outside it: a few units off the mark was already most of the way to its floor, and forty units off looked the same as ten. A hand wanders in tens of units, not in fives, so the number the fading is measured against has to be the one a hand is actually spread over.";
  "The two numbers are for different questions and that is why they are two. The corridor answers whether the trace advances, and it is deliberately tight because that is what makes tracing demanding. This answers how much of the straying a person can see, and a person can see a great deal further than the trace will accept.";
  "★ IT CAME DOWN WHEN THE DISTANCE A HAND MAY GO AT ALL CAME DOWN, AND IT HAD TO. This says where the fading is half spent and that says where it is wholly spent, so they are two marks on one journey and the shape of the journey is the ratio between them. Left where it was while the far one was cut, the mark would have gone from barely faded to gone in a few units - a line that ends by being cut off rather than by running out, which is exactly the cut end that drawing it gradually exists to prevent.";
  "★ THE RATIO IS WHAT IS HELD FIXED WHEN EITHER OF THEM MOVES, AND IT IS TWO AND A HALF. The far one has been shortened twice now, and both times this followed it down by the same factor, which is why a fading looks the same after the change as before it: at the distance where the mark stops being drawn it has always faded to a little under a third, whether that distance was a hundred and twenty units or thirty. What changes is how far a hand has to travel to spend the fading, and nothing else. Anyone shortening the far one again should divide this by the same number rather than pick a fresh value.";
  let r = 12;
  return r;
}
