export function bible_depiction_brief() {
  "The whole brief for depicting anything Scripture does not describe - a face, a garment, a room, a tone of voice - covering how much may be added, in what order the rules bind, and how a figure stays the same figure from scene to scene.";
  "★ ADDING DETAIL IS UNAVOIDABLE, SO THE QUESTION IS NEVER WHETHER BUT HOW MUCH AND POINTING AT WHAT. A face has features, a robe has a colour, a spoken line has a tone, and Scripture gives none of those for most of what it narrates. It cannot be escaped by refusing to draw either: a person simply reading a chapter aloud has already chosen a pronunciation, a pace and a tone, and nobody has ever called that adding to Scripture. So a rule forbidding addition would forbid reading the Bible out loud, and what is wanted is a bound.";
  "★ FIVE RULES, AND THE ORDER IS THE WHOLE OF IT. Include every detail the passage gives. Contradict no detail anywhere in Scripture. Be playable somehow. Honour tradition where possible. Honour history where possible. A lower rule never buys a higher one, so a depiction that plays beautifully and contradicts a verse is simply wrong, and a historically exact soldier who is missing something the passage said is also wrong.";
  "The first two rules are different jobs and both are needed. The first forbids leaving out what is in front of you. The second forbids putting in something that collides with a book you were not reading - the garments of a priest are described in Exodus whatever chapter you are drawing, and a depiction that ignores them has contradicted Scripture without ever touching its own passage.";
  "★ THE DETAIL MUST POINT AT THE SCRIPTURE AND NOT AT ITSELF, AND THAT IS A BOUND ON SIZE RATHER THAN ONLY ON CONTENT. 1TI4:7 sets aside godless myths and old wives' tales. One invented detail is not a myth; a mass of them becomes one, because detail accumulates into story. Give an added figure a name, a history and a motive and a second story is now running, it has to be followed, and the passage has quietly become the setting for it. Past some size the additions carry more story than Scripture does, and a viewer is then following the additions.";
  "★ THE BOUND IS ON ADDED STORY AND NEVER ON ADDED QUALITY, AND AN EARLIER DRAFT HERE HAD THAT EXACTLY BACKWARDS. It proposed testing whether the added material would still be interesting with the Scripture taken out, and condemning it if it would. Singing Scripture to instruments destroys that test: change the words and a good setting is still a good song, so the music is interesting without the Scripture and is plainly not competing with it. Worse, PSA33:3 says to play skilfully, so a rule that penalised excellence in the vehicle would contradict Scripture and fail the second rule above.";
  "★ THE TEST IS OF KIND, NOT OF QUALITY: DOES THE ADDITION CONSIST OF EVENTS, CAUSES OR MOTIVES? Those are the same stuff Scripture is made of, so anything added in that kind competes with it however small and however plainly told. Everything else - how a thing looks, sounds, moves, is coloured, is played - is manner, it carries the account rather than rivalling it, and it may be made as excellent as anybody can make it. The music was swappable precisely because it never held any of the story; the invented childhood is not swappable, because it is story.";
  "The size bound survives that correction and is now about conversion rather than about quantity. Enough manner becomes story: a face is manner, but a face with a limp and a scar and a glance at the door has implied a history nobody was given. So manner is unbounded in craft and bounded at the point where it starts implying events, and that point is what a designer has to watch.";
  "★ THE BOUND IS A MAGNIFICATION, AND THAT IS THE PLAINEST WAY ANYBODY HAS PUT IT HERE. Take a picture of a face in pixels and enlarge it far enough and the face becomes hairs, then skin cells, then organelles. Nothing at any of those magnifications is false, and the face is gone. A viewer can be lost in what is true close up, so the rule is to stay zoomed out far enough that the face is what is seen - and the face is the passage.";
  "★ A SLIGHT ENLARGEMENT IS NOT A DEPARTURE, IT IS WHAT MEDITATING ON SCRIPTURE HAS ALWAYS LOOKED LIKE. Somebody sitting with the text asks why this is here and that is there, and how an apparent gap closes: how did anyone know to bring Uriah's name to David, and the answer is that Uriah the Hittite is in the list of the thirty at 2SA23:39. That question and that answer are meditation, they are the goal rather than a risk to be managed, and a depiction that comes out of them is a reader thinking about four pixels and what one colour they would make.";
  "★ SO THE KIND TEST WRITTEN ABOVE IS TOO STRICT AS IT STANDS, AND THE REAL DISCRIMINATOR IS WHERE THE MATERIAL CAME FROM. That test forbade any added cause or reason, however small. The Uriah answer is an added reason and it is good, because Scripture supplied it. A cause another passage gives is a cross-reference; a cause nobody gives is an invention. Two bounds hold together, then: the source of a detail, Scripture or nobody, and the magnification, how far past the face it goes.";
  "It follows that nothing is set aside for being a list of names. A genealogy read well, with the imagery and the music behind it, can be worth watching and listening to, and it is Scripture at the same zoom as everything else.";
  "★ WHERE SCRIPTURE SUMMARISES AN ACT INSTEAD OF TELLING IT, DEPICTING IT NEEDS WORDS NOBODY WAS GIVEN, AND THAT IS THE HARDEST CASE THE KIND TEST HAS TO SURVIVE. MAT16:14 reports that people said John the Baptist, Elijah, Jeremiah, one of the prophets. Putting that on a screen as three men disagreeing supplies lines the text never wrote. It is allowed here, because the event and its subject and its content are all the passage's and only the manner of the saying is added - three voices are how an argument looks.";
  "★ DIGRESSION IS THE EXACT POINT WHERE MANNER TURNS INTO STORY, AND IT IS A TEST ANYBODY CAN APPLY. Let the same argument run on and it reaches Sadducees on the resurrection, then Elisha, then Moses against tradition - every line still drawn from Scripture, and the scene no longer about who John the Baptist was. Nothing false was said and the passage has been left behind. So an interpolation stays on the exact subject the passage named, adds no event, no motive and no outcome, and stops when the passage stops.";
  "This is a limit chosen for this project and not a judgement passed on anybody's art. A Christian writing that longer scene may be doing good work, God can use it, and someone will meet Scripture through a story who would not have met it through a verse. The reason for the lighter hand here is what this thing is for: it puts a player inside a passage, so anything invented sits where the passage is supposed to be.";
  "Tradition and history are last because they disagree, with Scripture and with each other. A Levite's garments are Scripture and not tradition. A Roman soldier's armour is historical record and settles itself. A face is neither: the iconographic tradition and the painted one do not agree and never have, and the repo already meets this elsewhere by carrying more than one tradition rather than choosing between them.";
  "A figure who ages is the ordinary hard case and not a rare one. Joseph is seventeen in one gathered scene and a hundred and ten in another, so a depiction is not one drawing but a thing that has to answer for a lifetime, and whoever takes this step should design for that from the start rather than discover it at Genesis 41.";
  let brief = {
    step: "depiction",
    what: "how a figure, place or garment that Scripture leaves undescribed is settled once and used by every scene that names it",
    settled:
      "the five rules and their order; that added detail must point at the passage; that the bound falls on added story and not on added quality, so craft in the manner of a depiction is unbounded; that a summarised act may be depicted in the manner Scripture withheld, and stops where the passage stops; that the goal is meditating on the passage, so a detail drawn out of another passage is a cross-reference and a detail drawn out of nobody is an invention; that the bound is a magnification, staying zoomed out far enough that the passage is what is seen",
    open: "where manner has accumulated far enough to imply events; how a depiction is addressed and named; what to do where traditions disagree; how a figure who ages is held together; whether a depiction may differ between renderings",
    forbidden:
      "an event, cause, reason or outcome no passage anywhere supplies; invented biography or backstory for anyone; a depicted exchange that leaves the subject the passage named; supplying anything at a point the text chose to withhold; detail magnified far enough that it is what a viewer is looking at; any detail contradicting any passage anywhere",
    done: "every figure named in a gathered scene has a depiction that satisfies the five rules in order, every added detail can be traced to a passage or is manner only, and none of it is magnified far enough to be what a viewer ends up looking at",
  };
  return brief;
}
