export function bible_glyph_chapter_pro16() {
  "Proverbs 16, drawn in pictures, so that a person who cannot read the letters can still follow it. Thirty three separate sayings about plans, kings, speech and pride, including the one about pride going before destruction. Thirty three lines.";
  "THE BOOK OF WISDOM CANNOT SAY WISDOM. The sixteenth line is the thesis of the whole book: how much better to acquire wisdom than gold, and to gain understanding is more desirable than silver. Four of its words are wisdom, understanding, gold and silver, and all four are blank, so the line arrives with a single thumb on the word better and nothing else. It is not one line. Wisdom, wise, understanding and discerning are said seven times across this page and there is no picture for any of them. A collection meant for someone who cannot read the letters is drawing the book of wisdom without the word.";
  "AND THE CHAPTER IS ABOUT THE MOUTH AND THERE IS NO MOUTH. The tongue in the first line, the lips and the mouth in the tenth, the lips in the thirteenth, speech in the twenty first, the mouth and the lips in the twenty third, speech in the twenty seventh, the lips in the thirtieth: nine mentions of a mouth, lips, a tongue or speech, and every one is plain. The mouth picture does land once, in the thirteenth line, and it lands on the word speaks, because that picture is seated on the act of speaking and not on the mouth. So the one page in the Bible most concerned with what comes out of a mouth can show a mouth exactly never.";
  "THE MOST QUOTED LINE IN THE BOOK COMES OUT WITH ONE MARK AND IT IS THE WRONG ONE. Pride goes before destruction, and a haughty spirit before a fall. Pride, destruction, haughty and fall are all blank. The only picture on the line is a wind, on the word spirit, because the Hebrew word there is the same one used for wind and for breath and for the Spirit of God. A reader who has learnt that picture from the earlier chapters will read a gust of wind going before a fall.";
  "THE SCALES APPEAR TWICE AND NEITHER TIME ON A SCALE. The eleventh line says honest scales and balances are from the LORD, and all the weights in the bag are His concern. Scales, balances and weights, three weighing words in one sentence, and all three are plain. The scale picture in that line is standing on the word honest, and the other one on this page is in the thirty third line, standing on the word decision. That artwork is seated on the Hebrew word for judgment, so it can arrive in a line about weighing only by accident, and it can never be the weight itself.";
  "THE CROWN AND THE THRONE ARE BOTH HERE AND BOTH BLANK. A throne is established through righteousness, in the twelfth line, which is the fifth chapter here to name a throne and draw nothing. Gray hair is a crown of glory, in the thirty first, and the crown artwork in this collection is spent on the word lord, so it cannot come to an actual crown. The gray hair is blank as well, and so is the gold and the silver in the sixteenth line and the honeycomb in the twenty fourth.";
  "WHAT THE PAGE DOES CARRY IS THE ROAD. Proverbs is built on the picture of two paths and the road mark lands eight times here: a man's ways in the second and the seventh, his course in the ninth, his way in the seventeenth, twice in the twenty fifth where a way that seems right ends in death, the path in the twenty ninth and the path of righteousness in the thirty first. A reader following pictures alone still gets the spine of the book, which is that there are two roads and they end differently.";
  "Seven marks were dropped. Two sat on a Hebrew idiom in the fifth line that reads hand to hand, which this English renders as be assured, so there is no hand left to draw. Two are winds the draft placed on the words motives in the second line and temper in the thirty second; the word underneath is the same one that means spirit, but neither English word says spirit, and a picture has to hold what the word above it holds. The last three are a generic human figure the draft put on the words life, soul and appetite, in the seventeenth, twenty fourth and twenty sixth lines; the Hebrew underneath is a soul, and a human figure is the wrong shape for it.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PRO16",
    reference: "Proverbs 16",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "plans",
          "of",
          "the",
          "$heart_organ",
          "belong",
          "to",
          "$person,",
          "but",
          "the",
          "reply",
          "of",
          "the",
          "tongue",
          "is",
          "from",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "All",
          "a",
          "$man_beard",
          "$road",
          "are",
          "pure",
          "in",
          "his",
          "own",
          "$eyes,",
          "but",
          "his",
          "motives",
          "are",
          "weighed",
          "out",
          "by",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Commit",
          "your",
          "works",
          "to",
          "the",
          "$name_tag,",
          "and",
          "your",
          "plans",
          "will",
          "be",
          "achieved.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "The",
          "$name_tag",
          "has",
          "made",
          "everything",
          "for",
          "His",
          "purpose,",
          "even",
          "the",
          "$thumbs_down",
          "for",
          "the",
          "$sun",
          "of",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Everyone",
          "who",
          "is",
          "proud",
          "in",
          "$heart_organ",
          "is",
          "detestable",
          "to",
          "the",
          "$name_tag;",
          "be",
          "assured",
          "that",
          "he",
          "will",
          "$no_entry",
          "go",
          "unpunished.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "By",
          "$gift",
          "and",
          "$check",
          "iniquity",
          "is",
          "atoned",
          "for,",
          "and",
          "by",
          "the",
          "fear",
          "of",
          "the",
          "$name_tag",
          "one",
          "turns",
          "aside",
          "from",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "When",
          "a",
          "$man_beard",
          "$road",
          "please",
          "the",
          "$name_tag,",
          "He",
          "makes",
          "even",
          "his",
          "enemies",
          "live",
          "at",
          "peace",
          "with",
          "him.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$thumbs_up",
          "is",
          "a",
          "little",
          "with",
          "$ruler",
          "than",
          "great",
          "gain",
          "with",
          "$no_entry.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "A",
          "$person",
          "$heart_organ",
          "plans",
          "his",
          "$road,",
          "but",
          "the",
          "$name_tag",
          "determines",
          "his",
          "steps.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "A",
          "divine",
          "verdict",
          "is",
          "on",
          "the",
          "lips",
          "of",
          "a",
          "$king;",
          "his",
          "mouth",
          "must",
          "$no_entry",
          "betray",
          "$scales.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "$scales",
          "scales",
          "and",
          "balances",
          "are",
          "from",
          "the",
          "$name_tag;",
          "all",
          "the",
          "weights",
          "in",
          "the",
          "bag",
          "are",
          "His",
          "concern.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Wicked",
          "$hammer",
          "is",
          "detestable",
          "to",
          "$king,",
          "for",
          "a",
          "throne",
          "is",
          "established",
          "through",
          "$ruler.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$ruler",
          "lips",
          "are",
          "a",
          "$king",
          "delight,",
          "and",
          "he",
          "who",
          "$mouth",
          "honestly",
          "is",
          "$heart_red.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "wrath",
          "of",
          "a",
          "$king",
          "is",
          "a",
          "$angel",
          "of",
          "$skull,",
          "but",
          "a",
          "wise",
          "$man_beard",
          "will",
          "pacify",
          "it.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "When",
          "a",
          "$king",
          "face",
          "$light",
          "there",
          "is",
          "$sprout;",
          "his",
          "favor",
          "is",
          "like",
          "a",
          "rain",
          "cloud",
          "in",
          "spring.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "How",
          "much",
          "$thumbs_up",
          "to",
          "acquire",
          "wisdom",
          "than",
          "gold!",
          "To",
          "gain",
          "understanding",
          "is",
          "more",
          "desirable",
          "than",
          "silver.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "The",
          "highway",
          "of",
          "the",
          "upright",
          "leads",
          "away",
          "from",
          "$thumbs_down;",
          "he",
          "who",
          "guards",
          "his",
          "$road",
          "protects",
          "his",
          "life.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Pride",
          "goes",
          "before",
          "destruction,",
          "and",
          "a",
          "haughty",
          "$wind",
          "before",
          "a",
          "fall.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "to",
          "be",
          "lowly",
          "in",
          "$wind",
          "among",
          "the",
          "humble",
          "than",
          "to",
          "divide",
          "the",
          "spoil",
          "with",
          "the",
          "proud.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Whoever",
          "heeds",
          "$speech",
          "will",
          "find",
          "$thumbs_up,",
          "and",
          "$gift+smile",
          "is",
          "he",
          "who",
          "trusts",
          "in",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "The",
          "wise",
          "in",
          "$heart_organ",
          "are",
          "called",
          "discerning,",
          "and",
          "pleasant",
          "speech",
          "promotes",
          "instruction.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Understanding",
          "is",
          "a",
          "fountain",
          "of",
          "$sprout",
          "to",
          "its",
          "possessor,",
          "but",
          "the",
          "discipline",
          "of",
          "fools",
          "is",
          "folly.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "The",
          "$heart_organ",
          "of",
          "the",
          "wise",
          "man",
          "instructs",
          "his",
          "mouth",
          "and",
          "adds",
          "persuasiveness",
          "to",
          "his",
          "lips.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "Pleasant",
          "words",
          "are",
          "a",
          "honeycomb,",
          "sweet",
          "to",
          "the",
          "soul",
          "and",
          "healing",
          "to",
          "the",
          "bones.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "There",
          "is",
          "a",
          "$road",
          "that",
          "seems",
          "right",
          "to",
          "a",
          "$man_beard,",
          "but",
          "its",
          "end",
          "is",
          "the",
          "$road",
          "of",
          "$skull.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "A",
          "worker",
          "appetite",
          "works",
          "for",
          "him,",
          "because",
          "his",
          "hunger",
          "drives",
          "him",
          "onward.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "A",
          "worthless",
          "$man_beard",
          "digs",
          "up",
          "$thumbs_down,",
          "and",
          "his",
          "speech",
          "is",
          "like",
          "a",
          "scorching",
          "fire.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "A",
          "perverse",
          "$man_beard",
          "spreads",
          "dissension,",
          "and",
          "a",
          "gossip",
          "divides",
          "close",
          "friends.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "A",
          "violent",
          "$man_beard",
          "entices",
          "his",
          "neighbor",
          "and",
          "$walking",
          "him",
          "down",
          "a",
          "$road",
          "that",
          "is",
          "$no_entry",
          "$thumbs_up.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "He",
          "who",
          "winks",
          "his",
          "$eyes",
          "devises",
          "perversity;",
          "he",
          "who",
          "purses",
          "his",
          "lips",
          "is",
          "bent",
          "on",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "Gray",
          "hair",
          "is",
          "a",
          "crown",
          "of",
          "glory;",
          "it",
          "is",
          "attained",
          "along",
          "the",
          "$road",
          "of",
          "$ruler.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "$thumbs_up",
          "is",
          "he",
          "who",
          "is",
          "slow",
          "to",
          "anger",
          "than",
          "a",
          "warrior,",
          "and",
          "he",
          "who",
          "controls",
          "his",
          "temper",
          "than",
          "one",
          "who",
          "captures",
          "a",
          "$city.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "The",
          "lot",
          "is",
          "cast",
          "into",
          "the",
          "lap,",
          "but",
          "its",
          "every",
          "$scales",
          "is",
          "from",
          "the",
          "$name_tag.",
        ],
      },
    ],
  };
  return chapter;
}
