import { fn_name } from "./fn_name.mjs";
export function bible_glyph_roots_greek_drafted() {
  ("The New Testament words seated in bulk by the AI rather than one at a time in the hand-written table, one row each: the Strong's number, the root family it is filed under, its picture and a short gloss. The hand-written table merges these in, so every reader sees one table. The rules for choosing are written once, beside the Old Testament rows in ",
    fn_name("bible_glyph_roots_hebrew_drafted"),
    ".");
  ("A GREEK NAME OF HEBREW ORIGIN WEARS ITS HEBREW NAME'S PICTURE, copied rather than chosen again, and is filed under the same root word, so Isaiah, Samuel and Jonah are drawn alike in both testaments and a reader meets one picture for one person. Judas waits by the human's choice, and with him the patriarch Judah and Jude, since Greek gives all three one number.");
  let rows = [
    ["5281", "hupomone", "person_climbing", "endurance"],
    ["1656", "eleos", "heart_hands", "mercy"],
    ["1653", "eleos", "heart_hands+doing", "have_mercy"],
    ["3408", "misthos", "dollar_banknote", "wages"],
    ["1249", "diakonos", "bellhop_bell+doer", "servant"],
    ["1247", "diakonos", "bellhop_bell+doing", "serve"],
    ["1248", "diakonos", "bellhop_bell+thing", "service"],
    ["1746", "enduo", "cloak+doing", "clothe"],
    ["228", "alethinos", "check+describing", "true"],
    ["3466", "musterion", "crystal_ball", "mystery"],
    ["3076", "lupe", "crying_face+doing", "grieve"],
    ["3077", "lupe", "crying_face", "grief"],
    ["2240", "heko", "airplane_arrival", "come"],
    ["4202", "porneia", "love_hotel", "fornication"],
    ["4203", "porneia", "love_hotel+doing", "fornicate"],
    ["4205", "porneia", "love_hotel+doer", "fornicator"],
    ["3022", "leukos", "white_circle", "white"],
    ["1992", "epistole", "envelope", "letter"],
    ["792", "aster", "star_plain", "star"],
    ["3983", "limos", "eating+hollow_circle+doing", "hunger"],
    ["4893", "suneidesis", "compass", "conscience"],
    ["941", "bastazo", "backpack", "bear"],
    ["91", "dikaios", "ruler+no_entry+doing", "wrong"],
    ["93", "dikaios", "ruler+no_entry+thing", "unrighteousness"],
    ["94", "dikaios", "ruler+no_entry+describing", "unrighteous"],
    ["4012", "peri", "clockwise_arrows", "around"],
    ["5037", "te", "plus+plus", "both"],
    ["2309", "thelo", "shooting_star+doing", "want"],
    ["2307", "thelo", "shooting_star", "will"],
    ["3992", "pempo", "incoming_envelope", "send"],
    ["154", "aiteo", "pleading", "ask"],
    ["71", "ago", "guide_dog", "lead"],
    ["5342", "phero", "shopping_cart", "carry"],
    ["5346", "phemi", "left_speech_bubble", "say"],
    ["1535", "eite", "traffic_light+plus+plus", "whether"],
    ["5225", "huparcho", "down_arrow+clapper_board", "possess"],
    ["2235", "ede", "hourglass_done", "already"],
    ["5108", "toioutos", "flashlight+likeness", "such"],
    ["4687", "sperma", "seed+doing", "sow"],
    ["3982", "pistis", "anchor+doing", "persuade"],
    ["1860", "epangelia", "pointing_up+angel", "promise"],
    ["3850", "parabole", "framed_picture", "parable"],
    ["5532", "chreia", "sos_button", "need"],
    ["4374", "prosphero", "toward+shopping_cart", "offer"],
    ["4253", "pro", "last_track", "before"],
    ["4716", "stauros", "latin_cross", "cross"],
    ["4717", "stauros", "latin_cross+doing", "crucify"],
    ["1074", "genea", "dna", "generation"],
    ["3958", "pascho", "confounded_face", "suffer"],
    ["3313", "meros", "pizza", "part"],
    ["3404", "miseo", "face_with_symbols_on_mouth", "hate"],
    ["3062", "loipos", "puzzle_piece", "rest"],
    ["3049", "logizomai", "abacus+doing", "reckon"],
    ["3844", "para", "children_crossing", "beside"],
    ["3860", "paradidomi", "children_crossing+hands_giving", "hand over"],
    ["3880", "paralambano", "children_crossing+hand_receiving", "take along"],
    ["3854", "paraginomai", "children_crossing+butterfly", "arrive"],
    ["3853", "parangello", "children_crossing+angel", "command"],
    ["3928", "parerchomai", "children_crossing+footprints", "pass by"],
    ["3908", "paratithemi", "children_crossing+palm_down", "set before"],
    ["3930", "parecho", "children_crossing+raised_fist", "provide"],
    ["2776", "kephale", "person_gesturing_ok", "head"],
    ["4983", "soma", "person_standing", "body"],
    ["3189", "melas", "black_circle", "black"],
    ["3188", "melan", "black_circle+thing", "ink"],
    ["2978", "lailaps", "tornado", "windstorm"],
    ["1023", "brachion", "flexed_biceps", "arm"],
    ["832", "auleo", "flute+doing", "play the flute"],
    ["258", "alopex", "fox", "fox"],
    ["5404", "phoinix", "palm_tree", "palm"],
    ["5326", "phantasma", "ghost", "ghost"],
    ["5045", "tekton", "carpentry_saw+doer", "carpenter"],
    ["4718", "staphule", "grapes", "grapes"],
    ["4699", "spongos", "sponge", "sponge"],
    ["4563", "saroo", "broom+doing", "sweep"],
    ["4627", "skaphe", "canoe", "lifeboat"],
    ["4628", "skelos", "leg", "legs"],
    ["5592", "psuchos", "cold_face", "cold"],
    ["5201", "hudria", "water+amphora", "water jar"],
    ["4737", "stephanoo", "crown+doing", "crown"],
    ["4444", "purgos", "tower", "tower"],
    ["4209", "porphura", "purple_circle", "purple"],
    ["4210", "porphurous", "purple_circle+describing", "purple"],
    ["3747", "osteon", "bone", "bones"],
    ["3738", "orcheomai", "man_dancing", "dance"],
    ["3192", "meli", "honey", "honey"],
    ["2952", "kunarion", "dog+child", "puppy"],
    ["2949", "kuma", "water_wave", "waves"],
    ["2062", "herpeton", "lizard", "reptile"],
    ["1181", "dekate", "ten+describing", "tenth"],
    ["501", "antleo", "bucket+doing", "draw water"],
    ["3164", "machomai", "boxing_glove+doing", "quarrel"],
    ["3163", "mache", "boxing_glove", "quarrel"],
    ["3803", "pagis", "mouse_trap", "snare"],
    ["3688", "onos", "donkey", "donkey"],
    ["3590", "ogdoos", "eight+describing", "eighth"],
    ["3521", "nesteia", "eating+locked", "fasting"],
    ["3472", "moria", "brain+thing", "foolishness"],
    ["3025", "lenos", "grapes+foot", "winepress"],
    ["2965", "kuon", "dog", "dog"],
    ["2852", "kolaphizo", "fist+face", "strike with fist"],
    ["2441", "himatismos", "garment+thing", "clothing"],
    ["2338", "thelus", "female_sign", "female"],
    ["2337", "thelazo", "baby_bottle+doing", "nurse"],
    ["2255", "hemisu", "divide", "half"],
    ["1767", "ennea", "nine", "nine"],
    ["1051", "gala", "milk", "milk"],
    ["681", "hapto", "fire+hand", "kindle"],
    ["231", "halieus", "fishing_pole+doer", "fisherman"],
    ["105", "aetos", "eagle", "eagle"],
    ["103", "ado", "song+doing", "sing"],
    ["3961", "pateo", "foot+doing", "trample"],
    ["3795", "opsarion", "fish+pinching_hand", "small fish"],
    ["3997", "penthos", "loudly_crying+thing", "grief"],
    ["5604", "odin", "pregnant_woman+weary_face", "birth pains"],
    ["3744", "osme", "nose+thing", "fragrance"],
    ["3690", "oxos", "wine+lemon", "sour wine"],
    ["3677", "onar", "dream", "dream"],
    ["3448", "moschos", "ox+child", "calf"],
    ["3184", "methuo", "wine+woozy_face", "be drunk"],
    ["3074", "lukos", "wolf", "wolf"],
    ["2894", "kophinos", "basket", "basket"],
    ["4711", "spuris", "basket+bread", "basket"],
    ["2847", "kokkinos", "red_circle", "scarlet"],
    ["2807", "kleis", "old_key", "key"],
    ["2574", "kamelos", "camel", "camel"],
    ["2390", "iaomai", "bandage+doing", "heal"],
    ["2395", "iatros", "bandage+doer", "physician"],
    ["2392", "iasis", "bandage+thing", "healing"],
    ["1733", "hendeka", "one+ten", "eleven"],
    ["1385", "dokos", "wood", "beam"],
    ["5205", "huetos", "rain", "rain"],
    ["5156", "tromos", "fearful_face", "trembling"],
    ["5141", "tremo", "fearful_face+doing", "tremble"],
    ["4651", "skorpios", "scorpion", "scorpion"],
    ["3565", "numphe", "woman+ring", "bride"],
    ["2825", "kline", "bed", "couch, bed"],
    ["1016", "bous", "ox", "ox"],
    ["2877", "korasion", "girl+pinching_hand", "little girl"],
    ["4154", "pneuma", "wind+doing", "blow"],
    ["1026", "brecho", "rain+doing", "rain"],
    ["4693", "spelaion", "cave", "cave"],
    ["5494", "cheimon", "snow+clock", "winter"],
    ["5510", "chion", "snow", "snow"],
    ["5603", "ode", "song", "song"],
    ["5568", "psalmos", "harp+thing", "psalm"],
    ["5567", "psalmos", "harp+doing", "sing praise"],
    ["2172", "proseuchomai", "hands_praying", "pray"],
    ["5370", "philos", "heart_orange+mouth", "kiss"],
    ["5286", "hupopodion", "foot+seat", "footstool"],
    ["1430", "doma", "house+top", "roof"],
    ["4004", "pente", "five+zero", "fifty"],
    ["1364", "duo", "two+repeat", "twice"],
    ["2344", "thesauros", "gem_stone", "treasure"],
    ["2343", "thesauros", "gem_stone+doing", "store up treasure"],
    ["5258", "hupnos", "sleeping_face+thing", "sleep"],
    ["2518", "katheudo", "sleeping_face+doing", "sleep"],
    ["2837", "koimao", "sleeping_face+pointing_down", "fall asleep"],
    ["1030", "brugmos", "grimacing_face", "gnashing"],
    ["4486", "rhegnumi", "broken_chain", "burst, tear"],
    ["5444", "phullon", "leaf", "leaf"],
    ["5519", "choiros", "pig", "pigs"],
    ["3599", "odous", "tooth", "tooth"],
    ["106", "azumos", "flatbread", "unleavened bread"],
    ["4149", "ploutos", "money_bag", "riches"],
    ["4145", "ploutos", "money_bag+describing", "rich"],
    ["4147", "ploutos", "money_bag+doing", "be rich"],
    ["1859", "heorte", "party_popper", "feast"],
    ["1632", "ekcheo", "pouring_liquid+doing", "pour out"],
    ["3538", "nipto", "bathtub+doing", "wash"],
    ["3068", "louo", "bathtub", "bathe"],
    ["438", "anthos", "blossom", "flower"],
    ["3528", "nikao", "trophy+doing", "overcome"],
    ["3529", "nikao", "trophy", "victory"],
    ["217", "halas", "salt", "salt"],
    ["5528", "chortos", "herb", "grass"],
    ["2936", "ktizo", "milky_way+doing", "create"],
    ["2937", "ktizo", "milky_way+thing", "creation"],
    ["2939", "ktizo", "milky_way+doer", "creator"],
    ["4663", "skolex", "worm", "worm"],
    ["1637", "elaion", "oil+olive", "olive oil"],
    ["1501", "eikosi", "two+zero", "twenty"],
    ["1497", "eidolon", "moai", "idol"],
    ["254", "halusis", "link+thing", "chain"],
    ["220", "alektor", "bird+morning", "rooster"],
    ["5557", "chrusion", "coin+crown", "gold"],
    ["5266", "hupodema", "sandal", "sandals"],
    ["5067", "tessares", "four+describing", "fourth"],
    ["3638", "okto", "eight", "eight"],
    ["1766", "ennea", "nine+describing", "ninth"],
    ["1442", "hepta", "seven+describing", "seventh"],
    ["1835", "hex", "six+zero", "sixty"],
    ["3023", "leon", "lion", "lion"],
    ["3520", "nesos", "sea+mountain", "island"],
    ["3135", "margarites", "hollow_circle+sparkle", "pearl"],
    ["1144", "dakru", "loudly_crying+water", "tear"],
    ["4439", "pule", "door+city", "gate"],
    ["5038", "teichos", "wall", "wall"],
    ["2925", "krouo", "door+fist", "knock"],
    ["4623", "siopao", "mouth+locked", "be silent"],
    ["3324", "mestos", "cup+top", "full"],
    ["2985", "lampas", "lamp+fire", "torch"],
    ["4969", "sphazo", "sword+skull", "slay"],
    ["3960", "patasso", "sword+doing", "strike"],
    ["5305", "husteros", "next_track+manner", "later"],
    ["5030", "tachu", "fast_forward+manner", "quickly"],
    ["3996", "pentheo", "loudly_crying+doing", "mourn"],
    ["21", "agalliao", "beaming+raised_back_of_hand", "rejoice"],
    ["976", "biblos", "open_book+thing", "book"],
    ["3034", "lithazo", "rock+throwing", "stone"],
    ["2348", "thnesko", "skull+doing", "die"],
    ["5142", "trepho", "bread+hands_giving", "feed"],
    ["1636", "elaia", "olive", "olive"],
    ["3789", "ophis", "snake", "snake"],
    ["4071", "peteinon", "bird+all", "birds"],
    ["3088", "luchnos", "lamp", "lamp"],
    ["3087", "luchnos", "lamp+seat", "lampstand"],
    ["1404", "drakon", "snake+fire", "dragon"],
    ["173", "akantha", "thorns", "thorns"],
    ["1350", "diktuon", "net", "net"],
    ["4537", "salpizo", "trumpet+doing", "sound a trumpet"],
    ["1763", "eniautos", "year+one", "year"],
    ["1623", "hex", "six+describing", "sixth"],
    ["5151", "treis", "three+repeat", "three times"],
    ["4578", "seismos", "earth+collision", "earthquake"],
    ["3358", "metron", "triangular_ruler", "measure"],
    ["2806", "klao", "bread+collision", "break"],
    ["2813", "klepto", "hand+lying_face", "steal"],
    ["5180", "tupto", "fist+doing", "beat"],
    ["1194", "dero", "fist+repeat", "beat"],
    ["4084", "piazo", "hand+clamp", "seize"],
    ["726", "harpazo", "hand+fast_forward", "snatch"],
    ["5035", "tachu", "fast_forward+manner", "quickly"],
    ["4404", "proi", "morning", "early, morning"],
    ["3798", "opsios", "sunset", "evening"],
    ["2586", "kapnos", "fire+cloud", "smoke"],
    ["1027", "bronte", "cloud+loudspeaker", "thunder"],
    ["1119", "gonu", "kneeling+thing", "knee"],
    ["4454", "polos", "donkey+child", "colt"],
    ["5357", "phiale", "cup+hollow_circle", "bowl"],
    ["1089", "geuomai", "tongue+doing", "taste"],
    ["1131", "gumnos", "garment+no_entry", "naked"],
    ["5560", "cholos", "foot+bandage", "lame"],
    ["2974", "kophos", "ear+locked", "deaf, mute"],
    ["3474", "moros", "brain+no_entry", "foolish"],
    ["5429", "phronimos", "brain+describing", "wise"],
    ["3115", "makrothumia", "timer_clock+heart_red", "patience"],
    ["994", "boao", "loudspeaker+mouth", "cry out"],
    ["4697", "splanchnizomai", "heart_red+pleading", "have compassion"],
    ["2165", "euphraino", "beaming+doing", "rejoice"],
    ["928", "basanizo", "weary_face+doing", "torment"],
    ["2853", "kollao", "link+doing", "join"],
    ["3307", "merizo", "scissors+doing", "divide"],
    ["5563", "chorizo", "scissors+away", "separate"],
    ["4464", "rhabdos", "white_cane", "staff"],
    ["2563", "kalamos", "tanabata_tree", "reed"],
    ["5553", "chrusion", "coin+crown", "gold"],
    ["3042", "limos", "eating+hollow_circle", "famine"],
    ["3507", "nephele", "cloud", "cloud"],
    ["1186", "dendron", "tree", "tree"],
    ["3586", "xulon", "tree+thing", "wood, tree"],
    ["2486", "ichthus", "fish", "fish"],
    ["2462", "hippos", "horse", "horse"],
    ["3376", "men", "new_moon", "month"],
    ["4582", "selene", "moon", "moon"],
    ["2808", "kleio", "locked+doing", "shut"],
    ["3129", "manthano", "learner+doing", "learn"],
    ["3403", "mimnesko", "reminder_ribbon+doing", "remember"],
    ["3421", "mimnesko", "reminder_ribbon+doing", "remember"],
    ["3563", "nous", "brain", "mind"],
    ["2749", "keimai", "bed+doing", "lie"],
    ["769", "astheneo", "thermometer_face+thing", "weakness"],
    ["772", "astheneo", "thermometer_face+describing", "weak"],
    ["2836", "koilia", "baby+house", "womb, belly"],
    ["2226", "zoe", "sprout+thing", "living creature"],
    ["571", "pistis", "anchor+no_entry", "unbelieving"],
    ["5062", "tessares", "four+zero", "forty"],
    ["4453", "poleo", "coin+hands_giving", "sell"],
    ["4127", "plege", "fist+thing", "blow, plague"],
    ["50", "ginosko", "lightbulb+no_entry", "not know"],
    ["5143", "trecho", "running", "run"],
    ["4633", "skene", "tent", "tent"],
    ["694", "argurion", "coin", "money"],
    ["2923", "krino", "scales+doer", "judge"],
    ["4215", "potamos", "national_park", "river"],
    ["1033", "broma", "eating+thing", "food"],
    ["5259", "hupo", "down_arrow", "under, by"],
    ["5228", "huper", "up_arrow", "over, on behalf of"],
    ["3306", "meno", "pin+doing", "remain, abide"],
    ["3123", "mallon", "more", "more, rather"],
    ["615", "apokteino", "fist+skull", "kill"],
    ["3319", "mesos", "radio_button", "middle"],
    ["2334", "theoreo", "eye+doing", "look at, see"],
    ["1188", "dexios", "hand+right_arrow", "right hand"],
    ["1377", "dioko", "running+toward", "pursue"],
    ["4219", "pote", "question+clock", "when"],
    ["3842", "pantote", "all+clock", "always"],
    ["3694", "opiso", "back", "behind"],
    ["3340", "metanoeo", "brain+turn_back", "repent"],
    ["3341", "metanoeo", "brain+turn_back", "repentance"],
    ["2246", "helios", "sun_with_face", "sun"],
    ["2511", "katharos", "soap+doing", "cleanse"],
    ["2513", "katharos", "soap+describing", "clean"],
    ["2512", "katharos", "soap+thing", "cleansing"],
    ["169", "katharos", "soap+no_entry", "unclean"],
    ["417", "anemos", "wind+dashing_away", "wind"],
    ["59", "agorazo", "coin+hand_receiving", "buy"],
    ["5343", "pheugo", "dashing_away", "flee"],
    ["4624", "skandalon", "snare+doing", "cause to stumble"],
    ["4625", "skandalon", "snare", "trap, stumbling block"],
    ["5055", "telos", "end_arrow+doing", "finish, fulfil"],
    ["2479", "ischus", "might", "strength"],
    ["2480", "ischus", "might+doing", "be able"],
    ["2478", "ischus", "might+describing", "strong"],
    ["2364", "thugater", "girl", "daughter"],
    ["1060", "gamos", "ring+doing", "marry"],
    ["1062", "gamos", "ring+thing", "wedding"],
    ["2968", "kome", "houses", "village"],
    ["2917", "krino", "scales+thing", "judgment"],
    ["4613", "shama", "ear+proper_name", "Simon"],
    ["2501", "yoseph", "i_am+plus", "Joseph"],
    ["2268", "yasha", "rescue+i_am", "Isaiah"],
    ["2464", "tsachaq", "laughing+proper_name", "Isaac"],
    ["4672", "shalom", "peace+proper_name", "Solomon"],
    ["4540", "shamar", "guard+proper_name", "Samaria"],
    ["2197", "zakar", "reminder_ribbon+i_am", "Zechariah"],
    ["2448", "yadah", "hands_raised+proper_name", "Judah, the town"],
    ["2495", "yonah", "dove+proper_name", "Jonah"],
    ["76", "adam", "person+proper_name", "Adam"],
    ["3482", "nathan", "hands_giving+heart_on_fire", "Nathanael, given of God"],
    ["5328", "paroh", "house+proper_name", "Pharaoh"],
    ["3017", "levi", "handshake+proper_name", "Levi"],
    ["958", "ben", "son+right_arrow", "Benjamin"],
    ["4545", "shama", "ear+heart_on_fire", "Samuel"],
    ["4528", "shaal", "question+heart_on_fire", "Shealtiel"],
    ["2408", "rum", "up_arrow+i_am", "Jeremiah"],
    ["1662", "qum", "heart_on_fire+pointing_up", "Eliakim"],
    ["7", "ab", "father+i_am", "Abijah"],
    ["4524", "tsedeq", "ruler+proper_name", "Zadok"],
    ["2498", "mishpat", "i_am+scales", "Jehoshaphat"],
    ["1478", "chazaq", "might+i_am", "Hezekiah"],
    ["5617", "yasha", "rescue+proper_name", "Hosea"],
    ["4502", "raah", "eyes+son", "Reuben"],
    ["4488", "rapha", "bandage+i_am", "Rhesa, Rephaiah"],
    ["3518", "ner", "lamp+i_am", "Neri, Neriah"],
    ["2493", "yhwh", "i_am+heart_on_fire", "Joel"],
    ["2422", "pathach", "unlocked+proper_name", "Jephthah"],
    ["2242", "alah", "pointing_up+proper_name", "Heli, Eli"],
    ["1800", "ish", "man_beard+proper_name", "Enosh"],
    ["1697", "chamor", "donkey+proper_name", "Hamor"],
    ["1666", "elisha", "heart_on_fire+rescue", "Elisha"],
    ["5502", "kerub", "cherub", "cherubim"],
    ["4519", "tsaba", "military_helmet", "sabaoth, hosts"],
    ["2581", "qanna", "face_steam+describing", "Cananaean, zealot"],
  ];
  let drafted = [];
  for (let row of rows) {
    drafted.push({
      strong: row[0],
      root: row[1],
      glyph: row[2],
      gloss: row[3],
    });
  }
  return drafted;
}
