export function bible_glyph_chapter_zec05() {
  "Zechariah 5, drawn in pictures, so that a person who cannot read the letters can still follow it. A prophet is shown two things. First a scroll the length of a house flying over the land, which is a curse that goes into the homes of thieves and false swearers and eats them from the timbers down. Then a woman called Wickedness, shut inside a measuring basket under a lid of lead, carried off between earth and sky by two women with the wings of a stork. Eleven lines.";
  "THE SCROLL PICTURE CANNOT GO ON A FLYING SCROLL EITHER, AND THAT IS NOW TWO CHAPTERS RUNNING. The scroll is named in the first line and again in the second, where its size is measured, and both are bare letters. The picture is seated on the Hebrew word for the law and on the word for a commandment, so it draws what a scroll carries and never the thing itself. The chapter written just before this one has a prophet eat a scroll and could not draw that either.";
  "AND THE NAME FAULT FIRES ON THE LINE ABOUT SWEARING FALSELY BY THE NAME. The fourth line says the LORD of Hosts and then says the house of him who swears falsely by My name. One picture serves both the name of God and the ordinary word for a name, so when a line holds the two of them the picture cannot say which it means, and both tags come off. This is the third chapter where that fault has landed on the one line the whole point rests on.";
  "THE SINGLE EYE STANDS BESIDE THE PAIR OF EYES THREE TIMES ON ONE PAGE. The first line, the fifth and the ninth all lift up the eyes and then see, and each time a picture of two eyes is followed within a few words by a picture of one. They are separate pictures for separate Hebrew words and a reader has no way to know that. It has happened in five earlier chapters, one time each. Here it happens three times in eleven lines.";
  "AND THE THING THE WHOLE SECOND HALF IS ABOUT IS NEVER DRAWN. The measuring basket is named in the sixth line, the seventh, the eighth, the ninth, the tenth and the eleventh, and it is plain letters every time. The woman shut inside it is drawn, and so are the two women who carry it. So a reader following only the marks watches a woman sitting in nothing, and then watches two more women lift nothing between the earth and the sky.";
  "THE TWO THINNEST LINES ARE THE TWO THAT SHOW THE WICKEDNESS. The seventh line raises the lead lid and finds the woman, and carries one mark. The eighth names her Wickedness and shoves her back down, and carries one mark. Everything that makes those two lines frightening is the lid, the basket and the name, and there is a picture for none of the three.";
  "Thirty eight marks over eleven lines. The ninth is the fullest at six, and nothing is empty. Two marks were kept by putting the plainer English back: the first line turns rather than saying again, and the tenth asks where they are going with the basket rather than where they are taking it.";
  "Three marks the draft offered were put away. Two of them are the name tags in the fourth line, taken off for the reason given above. The third is in the sixth line, where a picture of two eyes sat on the word iniquity. The Hebrew word behind it is the one that means an eye and also means the look of a thing, and this English gives it as iniquity, which holds no eyes at all.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "ZEC05",
    reference: "Zechariah 5",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "$turn_back",
          "again",
          "and",
          "lifted",
          "up",
          "my",
          "$eyes,",
          "and",
          "$eye",
          "before",
          "me",
          "a",
          "flying",
          "scroll.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "He",
          "$speech",
          "me,",
          "What",
          "do",
          "you",
          "$eye?",
          "I",
          "$speech,",
          "I",
          "$eye",
          "a",
          "flying",
          "scroll,",
          "twenty",
          "cubits",
          "long",
          "and",
          "ten",
          "cubits",
          "wide.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Then",
          "he",
          "$speech",
          "me,",
          "This",
          "is",
          "the",
          "curse",
          "that",
          "is",
          "going",
          "out",
          "over",
          "the",
          "face",
          "of",
          "all",
          "the",
          "$earth.",
          "According",
          "to",
          "one",
          "side",
          "of",
          "it",
          "every",
          "thief",
          "will",
          "be",
          "removed,",
          "and",
          "according",
          "to",
          "the",
          "other",
          "side",
          "every",
          "perjurer",
          "will",
          "be",
          "removed.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "will",
          "send",
          "it",
          "out,",
          "declares",
          "the",
          "LORD",
          "of",
          "Hosts,",
          "and",
          "it",
          "will",
          "$footprints",
          "the",
          "$house",
          "of",
          "the",
          "thief",
          "and",
          "the",
          "$house",
          "of",
          "him",
          "who",
          "swears",
          "falsely",
          "by",
          "My",
          "name.",
          "It",
          "will",
          "remain",
          "inside",
          "his",
          "$house",
          "and",
          "destroy",
          "it,",
          "down",
          "to",
          "its",
          "$tree",
          "and",
          "stones.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Then",
          "the",
          "$angel",
          "who",
          "was",
          "$mouth",
          "with",
          "me",
          "came",
          "forward",
          "and",
          "$speech",
          "me,",
          "Now",
          "lift",
          "up",
          "your",
          "$eyes",
          "and",
          "$eye",
          "what",
          "is",
          "approaching.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "I",
          "$speech,",
          "What",
          "is",
          "it?",
          "And",
          "he",
          "$speech,",
          "A",
          "measuring",
          "basket",
          "is",
          "going",
          "forth.",
          "Then",
          "he",
          "$speech,",
          "This",
          "is",
          "their",
          "iniquity",
          "in",
          "all",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "And",
          "behold,",
          "the",
          "cover",
          "of",
          "lead",
          "was",
          "raised,",
          "and",
          "there",
          "was",
          "a",
          "$woman",
          "sitting",
          "inside",
          "the",
          "basket.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "He",
          "$speech,",
          "This",
          "is",
          "Wickedness.",
          "And",
          "he",
          "shoved",
          "her",
          "down",
          "into",
          "the",
          "basket,",
          "pushing",
          "the",
          "lead",
          "cover",
          "down",
          "over",
          "its",
          "opening.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Then",
          "I",
          "lifted",
          "up",
          "my",
          "$eyes",
          "and",
          "$eye",
          "two",
          "$woman",
          "approaching,",
          "with",
          "the",
          "$wind",
          "in",
          "their",
          "wings.",
          "Their",
          "wings",
          "were",
          "like",
          "those",
          "of",
          "a",
          "stork,",
          "and",
          "they",
          "lifted",
          "up",
          "the",
          "basket",
          "between",
          "$earth",
          "and",
          "$sky.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "I",
          "$speech",
          "the",
          "$angel",
          "who",
          "was",
          "$mouth",
          "with",
          "me,",
          "Where",
          "are",
          "they",
          "$walking",
          "with",
          "the",
          "basket?",
        ],
      },
      {
        verse_number: 11,
        words: [
          "He",
          "$speech",
          "me,",
          "To",
          "build",
          "a",
          "$house",
          "for",
          "it",
          "in",
          "the",
          "$earth",
          "of",
          "Shinar.",
          "And",
          "when",
          "it",
          "is",
          "ready,",
          "the",
          "basket",
          "will",
          "be",
          "set",
          "there",
          "on",
          "its",
          "pedestal.",
        ],
      },
    ],
  };
  return chapter;
}
