export function bible_glyph_chapter_isa35() {
  "Isaiah 35, drawn in pictures. A desert blooms, blind eyes open, and a clean road runs through country that used to be full of lions, with the rescued walking home on it. Ten lines, and one of the shortest chapters in this Bible.";
  "THIS CHAPTER IS ABOUT JOY AND THERE IS NO PICTURE FOR JOY. Glad, rejoice, rejoice, joy, singing, shout for joy, singing, joy, gladness, joy - ten of them in ten lines, and the page draws not one. The first verse is the famous one, the wilderness and the dry land will be glad and the desert will blossom like a rose, and it carries no mark at all. A picture reader arrives at the most quoted sentence in the chapter and finds a line of plain letters. The last verse ends on gladness and joy overtaking people while sorrow and sighing flee, and of those four the page can draw none.";
  "FOUR BODIES ARE HEALED IN TWO VERSES AND ONLY ONE OF THEM GETS A PICTURE. Blind eyes are opened, deaf ears are unstopped, a lame man leaps like a deer, a mute tongue shouts. The eyes are drawn. The ears in the very next breath are not, though this Bible owns an ear and draws it on other pages: the root table simply has no answer for the word standing here. The leaping and the tongue have no pictures either. So the healing a reader can see is one pair of eyes, and the other three arrive as words.";
  "THE GLORY MARK IS A STAR AND IT IS DRAWN TWICE IN ONE VERSE, ONCE FOR A MOUNTAIN AND ONCE FOR GOD. The glory of Lebanon will be given to the desert, and then they will see the glory of the LORD. Same Hebrew word, same picture, four words apart - the weight of a cedar forest and the weight of God, and the page makes no distinction between them. That is the whole argument of the verse: what Lebanon has is being handed to a wasteland, and what a wasteland then shows you is Him.";
  "THE PICTURE FOR ALIVE IS DRAWN ONCE AND IT IS ON AN ANIMAL THAT WILL NOT BE THERE. The ninth verse says no lion will be there and no vicious beast will go up on it. The Hebrew for a beast is the word for a living thing, so the green shoot this Bible draws for life lands on the predator being kept off the road. It is the only one in the chapter. Every living thing that is welcome on that road - the redeemed, the walkers, the ransomed coming home - is written in plain letters.";
  "THE ROAD IS DRAWN TWICE AND BOTH TIMES IT IS THE SAME ROAD. The eighth verse builds a highway and names it the Way of Holiness, and this Bible has a picture for a road and one for holy, so that verse puts down six pictures - a road, a road, a holiness, two refusals and a walking. The unclean will not travel it and fools will not stray onto it. In a chapter that draws almost nothing, the page is clearest about who is not on the road.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "ISA35",
    reference: "Isaiah 35",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "wilderness",
          "and",
          "the",
          "dry",
          "land",
          "will",
          "be",
          "glad,",
          "the",
          "desert",
          "will",
          "rejoice",
          "and",
          "blossom",
          "like",
          "a",
          "rose.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "It",
          "will",
          "bloom",
          "profusely",
          "and",
          "rejoice",
          "with",
          "joy",
          "and",
          "singing.",
          "The",
          "$star",
          "of",
          "Lebanon",
          "will",
          "be",
          "$hands_giving",
          "to",
          "it,",
          "the",
          "splendor",
          "of",
          "Carmel",
          "and",
          "Sharon.",
          "They",
          "will",
          "$eye",
          "the",
          "$star",
          "of",
          "the",
          "$name_tag,",
          "the",
          "splendor",
          "of",
          "our",
          "$fire.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Strengthen",
          "the",
          "limp",
          "$hand",
          "and",
          "steady",
          "the",
          "feeble",
          "knees.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$speech",
          "to",
          "those",
          "with",
          "anxious",
          "$heart_organ,",
          "Be",
          "strong,",
          "do",
          "$no_entry",
          "fear!",
          "Behold,",
          "your",
          "$fire",
          "will",
          "$footprints",
          "with",
          "vengeance.",
          "With",
          "the",
          "retribution",
          "of",
          "$fire",
          "He",
          "will",
          "$footprints",
          "to",
          "save",
          "you.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Then",
          "the",
          "$eyes",
          "of",
          "the",
          "blind",
          "will",
          "be",
          "opened",
          "and",
          "the",
          "ears",
          "of",
          "the",
          "deaf",
          "unstopped.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Then",
          "the",
          "lame",
          "will",
          "leap",
          "like",
          "a",
          "deer,",
          "and",
          "the",
          "tongue",
          "of",
          "the",
          "mute",
          "will",
          "shout",
          "for",
          "joy.",
          "For",
          "$water",
          "will",
          "gush",
          "forth",
          "in",
          "the",
          "wilderness,",
          "and",
          "streams",
          "in",
          "the",
          "desert.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "parched",
          "ground",
          "will",
          "become",
          "a",
          "pool,",
          "the",
          "thirsty",
          "land",
          "springs",
          "of",
          "$water.",
          "In",
          "the",
          "haunt",
          "where",
          "jackals",
          "once",
          "lay,",
          "there",
          "will",
          "be",
          "grass",
          "and",
          "reeds",
          "and",
          "papyrus.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "And",
          "there",
          "will",
          "be",
          "a",
          "highway",
          "called",
          "the",
          "$road",
          "of",
          "$sparkle.",
          "The",
          "unclean",
          "will",
          "$no_entry",
          "travel",
          "it,",
          "only",
          "those",
          "who",
          "$walking",
          "in",
          "the",
          "$road,",
          "and",
          "fools",
          "will",
          "$no_entry",
          "stray",
          "onto",
          "it.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$no_entry",
          "lion",
          "will",
          "be",
          "there,",
          "and",
          "$no_entry",
          "vicious",
          "$sprout",
          "will",
          "go",
          "up",
          "on",
          "it.",
          "Such",
          "will",
          "$no_entry",
          "be",
          "found",
          "there,",
          "but",
          "the",
          "redeemed",
          "will",
          "$walking",
          "upon",
          "it.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "So",
          "the",
          "redeemed",
          "of",
          "the",
          "$name_tag",
          "will",
          "$turn_back",
          "and",
          "$footprints",
          "Zion",
          "with",
          "singing,",
          "crowned",
          "with",
          "$hourglass",
          "joy.",
          "Gladness",
          "and",
          "joy",
          "will",
          "overtake",
          "them,",
          "and",
          "sorrow",
          "and",
          "sighing",
          "will",
          "flee.",
        ],
      },
    ],
  };
  return chapter;
}
