export function bible_glyph_chapter_psa032() {
  "The thirty second psalm, drawn in pictures. A man describes what it was like to keep quiet about something he had done, and then what happened when he stopped. It is eleven lines long and the whole turn happens in the middle one.";
  "THE SILENCE DRAWS ONE MARK AND THE CONFESSION DRAWS SEVEN. The third verse and the fourth are the ones about keeping quiet - brittle bones, groaning all day, strength drained as in summer heat - and between them they carry a single picture, the heavy hand. The fifth verse is where he speaks, and it carries seven. Nobody arranged that; the marks come from the root table and fall wherever the seated words happen to be. But it means a reader who cannot read a word of the psalm can still see where it turns, because the page is nearly blank for two lines and then crowded for one. The seventh verse, where he is safe again, goes quiet a second time and draws nothing at all.";
  "TWO NEGATIONS ARE THE SAME MARK, AND THE SECOND ONE CAUSES THE FIRST. The second verse says the LORD does not count his iniquity against him. The fifth says he did not hide it. Those are the same crossing out picture on two different verbs, and the order the psalm puts them in is the order a reader meets them, not the order they happened. He stopped hiding, and so it stopped being counted. English gives no hint that these two sentences belong together. The mark shows it, and the psalm uses the same mark twice more - great waters will not come near, and do not be like the horse.";
  "THE SIN MARK FALLS TWICE AND BOTH TIMES ARE IN THE VERSE WHERE HE SAYS IT OUT LOUD. The first two verses name what is wrong three different ways and draw none of them. The fifth verse names it three ways too, and draws two - I acknowledged my sin, and You forgave the guilt of my sin. In between, the word that English writes as acknowledged is the ordinary word for knowing, so it carries the knowing mark. A reader following the pictures sees the same thing said twice with a knowing in the middle of it, which is a fair description of what confession is.";
  "THE PSALM OPENS ON A PAIR AND CLOSES ON HALF OF IT. Blessed, in the first line and again in the second, is drawn as two pictures together - a gift and a smile. The tenth verse ends on loving devotion, and that is the gift picture standing on its own. So the mark that begins the psalm inside a pair comes back at the end without its partner, on the word for the kindness God keeps showing. There is nothing in the English to connect blessed with loving devotion. In the pictures a reader sees the first half of the opening mark again and has to decide what that means, which is the right question to be left with.";
  "THE ONE VERSE WHERE THE PSALM TEACHES DRAWS A ROAD, A WALKING AND A PAIR OF EYES. The eighth verse is God speaking rather than David - I will instruct you and teach you the way you should go, I will give you counsel and watch over you. Three of its pictures are the road, the going and the eyes, in that order, and none of the three appears anywhere else on the page. So the single line of instruction in the psalm is also the only line that shows a path, a person moving along it, and somebody looking.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA032",
    reference: "Psalm 32",
    verses: [
      {
        verse_number: 1,
        words: [
          "Of",
          "David.",
          "A",
          "Maskil.",
          "$gift+smile",
          "is",
          "he",
          "whose",
          "transgressions",
          "are",
          "forgiven,",
          "whose",
          "sins",
          "are",
          "covered.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$gift+smile",
          "is",
          "the",
          "$person",
          "whose",
          "iniquity",
          "the",
          "$name_tag",
          "does",
          "$no_entry",
          "count",
          "against",
          "him,",
          "in",
          "whose",
          "$wind",
          "there",
          "is",
          "no",
          "deceit.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "When",
          "I",
          "kept",
          "silent,",
          "my",
          "bones",
          "became",
          "brittle",
          "from",
          "my",
          "groaning",
          "all",
          "day",
          "long.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "For",
          "day",
          "and",
          "night",
          "Your",
          "$hand",
          "was",
          "heavy",
          "upon",
          "me;",
          "my",
          "strength",
          "was",
          "drained",
          "as",
          "in",
          "the",
          "summer",
          "heat.",
          "Selah",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Then",
          "I",
          "$lightbulb",
          "my",
          "$bow",
          "to",
          "You",
          "and",
          "did",
          "$no_entry",
          "hide",
          "my",
          "iniquity.",
          "I",
          "$speech,",
          "I",
          "will",
          "$hands_raised",
          "my",
          "transgressions",
          "to",
          "the",
          "$name_tag,",
          "and",
          "You",
          "forgave",
          "the",
          "guilt",
          "of",
          "my",
          "$bow.",
          "Selah",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Therefore",
          "let",
          "all",
          "the",
          "godly",
          "$hands_praying",
          "to",
          "You",
          "while",
          "You",
          "may",
          "be",
          "found.",
          "Surely",
          "when",
          "great",
          "$water",
          "rise,",
          "they",
          "will",
          "$no_entry",
          "come",
          "near.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "You",
          "are",
          "my",
          "hiding",
          "place;",
          "You",
          "protect",
          "me",
          "from",
          "trouble;",
          "You",
          "surround",
          "me",
          "with",
          "songs",
          "of",
          "deliverance.",
          "Selah",
        ],
      },
      {
        verse_number: 8,
        words: [
          "I",
          "will",
          "instruct",
          "you",
          "and",
          "teach",
          "you",
          "the",
          "$road",
          "you",
          "should",
          "$walking;",
          "I",
          "will",
          "give",
          "you",
          "counsel",
          "and",
          "$eyes",
          "over",
          "you.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$no_entry",
          "be",
          "like",
          "the",
          "horse",
          "or",
          "mule,",
          "which",
          "have",
          "no",
          "understanding,",
          "which",
          "must",
          "be",
          "controlled",
          "with",
          "bit",
          "and",
          "bridle",
          "to",
          "make",
          "them",
          "come",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Many",
          "are",
          "the",
          "sorrows",
          "of",
          "the",
          "$thumbs_down,",
          "but",
          "$gift",
          "surrounds",
          "him",
          "who",
          "trusts",
          "in",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Be",
          "glad",
          "in",
          "the",
          "$name_tag",
          "and",
          "rejoice,",
          "O",
          "$ruler;",
          "shout",
          "for",
          "joy,",
          "all",
          "you",
          "upright",
          "in",
          "$heart_organ.",
        ],
      },
    ],
  };
  return chapter;
}
