export function bible_scene_division_brief() {
  "The whole brief for deciding what a scene is: the unit that gets read aloud and rendered once, how it is addressed, and what happens where several books tell the same thing.";
  "★ THIS IS THE ONE ASSET THAT SURVIVES EVERY CHOICE NOT YET MADE. Still pictures, moving ones, three dimensions, a game or no game - all of them need to know where a scene starts and stops, and none of them changes the answer. So it can be settled now, while rendering cannot, and settling it is the only work here that cannot be wasted by a later change of mind.";
  "★ THE SHAPE ALREADY EXISTS AND THE DISCIPLINE FOR FILLING IT DOES NOT. A gathered event is a title and a list of passages, and there are 248 of them across Genesis, Exodus and Numbers. Thirteen hold more than one passage - and every single one of those is a run of adjacent chapters, a scene the chapter division happened to cut in half. So the container that would hold four Gospel accounts of one afternoon has never once been used for that, and anybody reading the data and concluding the question is answered has read thirteen chapter repairs.";
  "★ NO GOSPEL IS GATHERED YET, WHICH IS WHY THIS IS CHEAP TODAY AND EXPENSIVE LATER. The corpus is three books of the Law. Gathering a Gospel under the wrong rule would create some hundreds of scenes that somebody then has to re-cut by hand, and re-cutting is exactly the work that never gets scheduled. Decide first, gather second.";
  "★ A SCENE IS WHAT IS READ ALOUD, AND THAT SETTLES MOST OF THE QUESTION BY ITSELF. The reading is already fixed elsewhere as the foundation of delivering a word, and it is what a cutscene is built on too. Nobody can read four accounts aloud at once. So a scene has exactly one reading, and a scene assembled out of parallel accounts would force somebody to choose which account is the one heard - a decision about Scripture wearing the clothes of a decision about rendering.";
  "★ SCENES DIVIDE BY TEXT AND DEPICTIONS CONSOLIDATE BY SUBJECT, WHICH IS HOW BOTH THINGS ARE HAD AT ONCE. Whatever a scene turns out to be, the hillside, the boy, the basket of loaves and the face of Jesus are one each, because a depiction is not a text. That way nothing is flattened - Mark keeps his green grass and John keeps his boy - and the drawing is still made once. The saving people hope to get from a harmony is real, and it lives in the depictions rather than in the text.";
  "★ ONE READING RULES OUT BLENDING AND LEAVES TWO WAYS STANDING, WHICH IS LESS THAN AN EARLIER DRAFT HERE CLAIMED. It said four accounts meant four scenes, treating that as settled by the one-reading rule; it is not, and the rule is narrower than the conclusion drawn from it.";
  "The way that is ruled out is BLENDING: one text assembled out of four, which forces somebody to choose whose wording is heard and deletes what the other three said.";
  "The first way that stands is SERIAL: each account is its own scene with its own reading, taken in turn. Nothing is lost and nothing is chosen, at the cost of a viewer hearing the same afternoon four times.";
  "The second way that stands is PRIMARY AND GLOSSED: one account is read, and where another book carries a detail this one does not, that detail is heard as a direct quotation, marked plainly as coming from elsewhere. It is one reading, so the rule is satisfied, and it differs from blending in the one way that matters - the seams are shown rather than hidden, so nothing is presented as the primary account's words that is not. It is the passage glossed by its cross-references, which is a discipline this repo already has for words.";
  "Choosing between those two is not a rendering question and is not answered here.";
  "That is also where the character designs live, and why designing them is not wasted at any rendering level. A design carries from a still to a moving picture to a modelled one - a figure sculpted from turnaround drawings is the ordinary way that is done - even though not one rendered frame carries. Consistency from picture to picture is a property of the design and not of the pictures, so it is settled once, in the depictions, and every scene that names a figure gets it.";
  "An account only one book carries is not a special case under this rule. It is one reading, so it is one scene, exactly like the other three.";
  let brief = {
    step: "scene division",
    what: "the unit that is read aloud once and rendered once, and how it is addressed",
    settled:
      "a scene has exactly one reading; the accounts differ and the differences are Scripture; blended text is ruled out; the existing shape is a title with a list of passages",
    open: "serial or primary-and-glossed for parallel accounts; how a quotation from another book is marked as such; how a depiction is addressed and shared between scenes; how a scene too long to hear in one sitting is handled",
    forbidden:
      "merging parallel accounts into one text; picking one account as the true one; a scene with two readings; gathering a Gospel before this is decided",
    done: "every Gospel can be gathered without later re-cutting, one afternoon on a hillside is drawn once, and nothing any of the four books says has been dropped",
  };
  return brief;
}
