export function bible_glyph_chapter_num08() {
  "The eighth chapter of Numbers, drawn in pictures. Twenty six verses. Aaron sets up the seven lamps so they shine forward, and then the Levites are washed, shaved, offered as a wave offering and handed over to God in place of every firstborn son of Israel. The chapter ends with the only working ages in the book, twenty five to fifty.";
  "THE CHAPTER IS ABOUT THE LEVITES AND THE WORD LEVITE HAS NO PICTURE IN THE TABLE. It is said twenty times, in fifteen of the twenty six verses, and every one of them is plain English. The whole subject of the chapter is undrawn.";
  "THE LAMPSTAND HAS NO PICTURE AND ITS LAMPS DO. The word for the stand is said four times, in verses two, three and four, and the word for the lamps three times. So the first four verses draw the light and leave the thing holding it up as plain words.";
  "THE ONLY ONE WHO SPEAKS IS THE LORD, AND ALWAYS TO MOSES. Verses one, five and twenty three each open the same way, and the one other speaking word, in verse two, is the LORD telling Moses to speak to Aaron. Nobody in the chapter answers Him.";
  "AARON IS NAMED NINE TIMES AND NEVER SAYS A WORD. He is in verses two, three, eleven, thirteen, nineteen, twenty, twenty one and twenty two, lighting lamps, presenting men and making atonement, and he is silent in all of them.";
  "THE FIRSTBORN ARE THE REASON FOR THE WHOLE EXCHANGE AND ARE NAMED IN ONLY THREE VERSES. The word falls four times, at verses sixteen, seventeen and eighteen, and has no picture. The Levites are taken in place of them, and the ones being replaced are barely in the chapter.";
  "THE WORD FOR SON IS SAID TWENTY THREE TIMES AND MOST OF THEM ARE NOT SONS. It is the ordinary Hebrew way of saying the Israelites, and verse nineteen alone holds six of the twenty three. In verse twenty four it means a number of years, and in verse seventeen it means a male.";
  "THE LAST THREE VERSES ARE THE ONLY AGE LIMIT IN THE BOOK. A Levite starts at twenty five and stops at fifty, and after that he may help his brothers but may not do the work himself. The word for stopping is the ordinary word for turning back.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "NUM08",
    reference: "Numbers 8",
    verses: [
      {
        verse_number: 1,
        words: ["$mouth", "Then", "$name_tag", "to", "Moses,", "$speech,"],
      },
      {
        verse_number: 2,
        words: [
          "$mouth",
          "to",
          "Aaron",
          "$speech",
          "him,",
          "When",
          "you",
          "set",
          "up",
          "$lamp",
          "in",
          "front",
          "of",
          "the",
          "lampstand,",
          "they",
          "are",
          "to",
          "light",
          "the",
          "area,",
          "the",
          "seven",
          "$lamp.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$hammer",
          "so",
          "And",
          "Aaron",
          "toward",
          "the",
          "front",
          "facing",
          "of",
          "the",
          "lampstand",
          "he",
          "set",
          "up",
          "$lamp,",
          "just",
          "as",
          "had",
          "commanded",
          "$name_tag",
          "Moses.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "This",
          "is",
          "how",
          "was",
          "constructed",
          "the",
          "lampstand,",
          "it",
          "was",
          "made",
          "of",
          "hammered",
          "$gold",
          "from",
          "its",
          "base",
          "to",
          "its",
          "blossoms,",
          "according",
          "to",
          "the",
          "pattern",
          "$eye",
          "$name_tag",
          "Moses,",
          "$hammer.",
        ],
      },
      {
        verse_number: 5,
        words: ["$mouth", "Again", "$name_tag", "to", "Moses,", "$speech,"],
      },
      {
        verse_number: 6,
        words: [
          "$hand_receiving",
          "the",
          "Levites",
          "from",
          "among",
          "$son,",
          "and",
          "make",
          "them",
          "ceremonially",
          "clean.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "This",
          "is",
          "what",
          "$hammer",
          "to",
          "cleanse",
          "them.",
          "Sprinkle",
          "them",
          "$water",
          "$bow.",
          "Have",
          "them",
          "shave",
          "their",
          "whole",
          "$meat,",
          "and",
          "wash",
          "$garment,",
          "and",
          "so",
          "purify",
          "themselves.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$hand_receiving",
          "$bull",
          "$son",
          "$grain_offering",
          "$flour",
          "mixed",
          "with",
          "oil,",
          "and",
          "a",
          "second",
          "$bull",
          "$son",
          "$hand_receiving",
          "$bow.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Bring",
          "the",
          "Levites",
          "before",
          "$tent",
          "of",
          "Meeting,",
          "and",
          "assemble",
          "the",
          "whole",
          "congregation",
          "$son",
          "of",
          "Israel.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "You",
          "are",
          "to",
          "present",
          "the",
          "Levites",
          "before",
          "$name_tag,",
          "and",
          "have",
          "$son",
          "lay",
          "$hand",
          "upon",
          "them.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Aaron",
          "is",
          "to",
          "present",
          "the",
          "Levites",
          "as",
          "a",
          "wave",
          "offering",
          "before",
          "$name_tag,",
          "$son",
          "of",
          "Israel,",
          "$kneeling",
          "the",
          "service",
          "$name_tag.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "And",
          "the",
          "Levites",
          "are",
          "to",
          "lay",
          "$hand",
          "on",
          "the",
          "heads",
          "$bull,",
          "$hammer",
          "one",
          "$bow",
          "and",
          "the",
          "other",
          "$burnt_offering",
          "$name_tag,",
          "to",
          "make",
          "atonement",
          "for",
          "the",
          "Levites.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "You",
          "are",
          "to",
          "have",
          "the",
          "Levites",
          "stand",
          "before",
          "Aaron",
          "$son,",
          "and",
          "then",
          "present",
          "them",
          "as",
          "a",
          "wave",
          "offering",
          "$name_tag.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "In",
          "this",
          "way",
          "you",
          "shall",
          "separate",
          "the",
          "Levites",
          "from",
          "$son,",
          "the",
          "rest",
          "of",
          "the",
          "Israelites,",
          "and",
          "the",
          "Levites",
          "will",
          "belong",
          "to",
          "Me.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "After",
          "$footprints",
          "$kneeling",
          "$tent",
          "of",
          "Meeting,",
          "you",
          "have",
          "cleansed",
          "them",
          "and",
          "presented",
          "them",
          "as",
          "a",
          "wave",
          "offering.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "For",
          "$hands_giving",
          "$hands_giving",
          "the",
          "Levites",
          "to",
          "Me",
          "from",
          "among",
          "$son",
          "of",
          "Israel.",
          "In",
          "place",
          "of",
          "all",
          "who",
          "come",
          "first",
          "from",
          "the",
          "womb,",
          "the",
          "firstborn",
          "of",
          "all",
          "$son",
          "of",
          "Israel,",
          "$hand_receiving",
          "them",
          "for",
          "Myself.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "For",
          "every",
          "firstborn",
          "$son",
          "in",
          "Israel",
          "is",
          "Mine,",
          "$person",
          "and",
          "beast.",
          "$sun",
          "I",
          "struck",
          "down",
          "all",
          "the",
          "firstborn",
          "$earth",
          "of",
          "Egypt,",
          "$sparkle",
          "for",
          "Myself.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "$hand_receiving",
          "the",
          "Levites",
          "in",
          "place",
          "of",
          "all",
          "the",
          "firstborn",
          "$son",
          "of",
          "Israel.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "$hands_giving",
          "the",
          "Levites",
          "$hands_giving",
          "to",
          "Aaron",
          "$son",
          "from",
          "among",
          "$son",
          "the",
          "Israelites,",
          "$kneeling",
          "the",
          "service",
          "$son",
          "$tent",
          "of",
          "Meeting",
          "and",
          "to",
          "make",
          "atonement",
          "$son,",
          "$no_entry",
          "plague",
          "will",
          "come",
          "$son",
          "when",
          "they",
          "approach",
          "$son",
          "$sparkle.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "$hammer",
          "So",
          "Moses,",
          "Aaron",
          "and",
          "the",
          "whole",
          "congregation",
          "$son",
          "of",
          "Israel",
          "with",
          "the",
          "Levites",
          "everything",
          "that",
          "$name_tag",
          "had",
          "commanded",
          "Moses",
          "$hammer",
          "$son.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$bow",
          "The",
          "Levites",
          "themselves",
          "and",
          "washed",
          "$garment,",
          "and",
          "Aaron",
          "presented",
          "them",
          "as",
          "a",
          "wave",
          "offering",
          "before",
          "$name_tag,",
          "Aaron",
          "also",
          "made",
          "atonement",
          "for",
          "them",
          "to",
          "cleanse",
          "them.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "After",
          "that",
          "$footprints",
          "the",
          "Levites",
          "$kneeling",
          "their",
          "service",
          "$tent",
          "of",
          "Meeting",
          "in",
          "the",
          "presence",
          "of",
          "Aaron",
          "$son,",
          "just",
          "as",
          "$name_tag",
          "had",
          "commanded",
          "Moses",
          "with",
          "the",
          "Levites.",
          "Thus",
          "$hammer.",
        ],
      },
      {
        verse_number: 23,
        words: ["$mouth", "And", "$name_tag", "to", "Moses,", "$speech,"],
      },
      {
        verse_number: 24,
        words: [
          "This",
          "applies",
          "to",
          "the",
          "Levites.",
          "Men",
          "twenty",
          "five",
          "$son",
          "of",
          "years",
          "or",
          "older",
          "$footprints",
          "to",
          "perform",
          "the",
          "service",
          "in",
          "the",
          "work",
          "$tent",
          "of",
          "Meeting.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "But",
          "$son",
          "of",
          "fifty",
          "$turn_back",
          "from",
          "performing",
          "the",
          "work",
          "$no_entry",
          "$kneeling",
          "longer.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "After",
          "that",
          "they",
          "may",
          "assist",
          "$brother",
          "$tent",
          "of",
          "Meeting",
          "in",
          "fulfilling",
          "their",
          "duties,",
          "but",
          "$no_entry",
          "$kneeling",
          "the",
          "work",
          "themselves.",
          "This",
          "is",
          "how",
          "$hammer",
          "responsibilities",
          "to",
          "the",
          "Levites.",
        ],
      },
    ],
  };
  return chapter;
}
