export function bible_glyph_chapter_job31() {
  "Job 31, drawn in pictures, so that a person who cannot read the letters can still follow it. Job swears a long oath of innocence, going one at a time through his eyes, his hands, his household, his gold, the poor, the widow, the fatherless and his own land, and calling down a curse on himself for each one if he is lying. Forty lines.";
  "ONE PAGE HERE HOLDS BOTH HALVES OF THE PROOF THAT THE SCALES ARE NOT A WEIGHING SCALE. The sixth line asks God to weigh him with honest scales, and the word scales is plain letters. What lands in that line instead is a ruler, on the word honest. Seven lines later, in the thirteenth, Job speaks of the cause of his manservant, which is a legal case with nothing in it to weigh, and that is where the balance picture comes. So the one line in the chapter that names an actual pair of scales cannot show them, and the picture of a pair of scales turns up on a lawsuit. Every other chapter in this collection could only argue that the scales are seated on judgment. This one demonstrates it twice over, seven lines apart, on a single page.";
  "AND FOUR MORE THINGS THIS CHAPTER NAMES CANNOT BE DRAWN, BECAUSE THEIR PICTURES ARE ALREADY SPENT ON SOMETHING ELSE. The twenty sixth line has Job looking at the sun in its radiance, and the sun does not come. A general light comes instead, because in this collection the sun belongs to the word day, and the moon in the same breath is blank. The twelfth line says it is a fire that burns down to Abaddon, and the flame does not come, because the flame is God. The twenty seventh line has a hand throwing a kiss from a mouth, and the mouth does not come, because the mouth is speaking. The thirty sixth line has Job wearing the indictment against him like a crown, and the crown does not come, because the crown is a lord. Four objects, four pictures for them sitting in this same collection, and all four looking the other way.";
  "AND THE SAME PAGE SHOWS THAT MACHINERY FROM THE OTHER SIDE, IN A BOW. The thirtieth line is Job saying he never let his mouth sin, and the picture that lands on the word sin is a bow and arrow, because sinning in Hebrew is missing what you aimed at. So the one bow this collection owns belongs to sinning, and no archer can ever be drawn with it. Genesis 21 already paid for that: it measures a distance as a bowshot and says the boy became an archer, and both are plain letters.";
  "AND THE PEOPLE THE WHOLE OATH IS ABOUT HAVE NO PICTURES AT ALL. The poor in the sixteenth line, the widow in the sixteenth and again in the eighteenth, the fatherless in the seventeenth and the twenty first, the needy man in the nineteenth, the stranger and the traveler in the thirty second: this is the moral centre of the chapter, the list of people by whom a rich man is measured, and every one of them is plain letters. The one thing that can be drawn beside them is a father, once, in the eighteenth line, where Job says he reared the fatherless as a father would. A reader following pictures sees a man swearing at great length about people the pictures cannot show.";
  "AND NINE OF THE FORTY LINES CARRY NO PICTURE AT ALL, AND FOUR OF THOSE COME ONE AFTER ANOTHER AT THE END. The second, eighth, eleventh, twelfth and twenty second lines are blank, and then the thirty sixth, thirty seventh, thirty eighth and thirty ninth are blank in a row: the crown on his shoulder, going to God like a prince, his land crying out against him, and the tenants whose spirit he might have broken. The oath runs out of pictures exactly where it becomes a challenge to God. The last mark in the chapter is a speech bubble in the fortieth line, on the words of Job, and the briers and the stinkweed beside it are plain.";
  "WHAT THE PAGE DOES CARRY IS THE WORD NOT. The commonest picture here by a long way is the crossed circle, eleven times, more than twice anything else, because the whole chapter is a list of things a man did not do: does He not see, did not the same One make them, not sharing with the fatherless, if his heart has not blessed me, I cannot overpower, I have not allowed my mouth, who has not had his fill, no stranger had to lodge, and I would not go outside. Beside it the chapter draws the parts of a man that are on trial, an eye four times and a pair of eyes three, a heart three times and a hand three. So a reader who sees only the pictures still gets the shape of the thing right: a man pointing at his own eyes and hands and heart, and saying no.";
  "Twelve marks were dropped. Three sat on pieces of Hebrew this English swallows and had no word of their own to stand on. Two sat on the function words from and it. Two are the general human figure standing on a soul, on the words his life in the thirtieth line and on the spirit of its tenants in the thirty ninth, where the Hebrew is one word for a living thing rather than a person you could point at. The last five are marks the English word underneath does not hold. Three of those are one mistake three times over, a pair of giving hands on the Hebrew idiom for oh that, which this English writes as allowed, as is there, and as I had, and not one of those is a gift. One is a bearded man on the word accuser in the thirty fifth line, where the Hebrew says the man of my dispute and this English keeps only the dispute. The last is a lightning bolt on the word produce in the thirty ninth line, where the Hebrew word means strength and this English means crops.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "JOB31",
    reference: "Job 31",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "have",
          "made",
          "a",
          "covenant",
          "with",
          "my",
          "$eyes.",
          "How",
          "then",
          "could",
          "I",
          "gaze",
          "with",
          "desire",
          "at",
          "a",
          "virgin?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "What",
          "is",
          "the",
          "allotment",
          "from",
          "God",
          "above,",
          "or",
          "the",
          "heritage",
          "from",
          "the",
          "Almighty",
          "on",
          "high?",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Is",
          "$no_entry",
          "disaster",
          "for",
          "the",
          "unjust",
          "and",
          "calamity",
          "for",
          "the",
          "workers",
          "of",
          "iniquity?",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Does",
          "He",
          "$no_entry",
          "$eye",
          "my",
          "$road",
          "and",
          "count",
          "my",
          "every",
          "step?",
        ],
      },
      {
        verse_number: 5,
        words: [
          "If",
          "I",
          "have",
          "$walking",
          "in",
          "falsehood",
          "or",
          "my",
          "foot",
          "has",
          "rushed",
          "to",
          "deceit,",
        ],
      },
      {
        verse_number: 6,
        words: [
          "let",
          "God",
          "weigh",
          "me",
          "with",
          "$ruler",
          "scales,",
          "that",
          "He",
          "may",
          "$lightbulb",
          "my",
          "integrity.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "If",
          "my",
          "steps",
          "have",
          "turned",
          "from",
          "the",
          "$road,",
          "if",
          "my",
          "$heart_organ",
          "has",
          "followed",
          "my",
          "$eyes,",
          "or",
          "if",
          "my",
          "hands",
          "are",
          "stained,",
        ],
      },
      {
        verse_number: 8,
        words: [
          "then",
          "may",
          "another",
          "eat",
          "what",
          "I",
          "have",
          "sown,",
          "and",
          "may",
          "my",
          "crops",
          "be",
          "uprooted.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "If",
          "my",
          "$heart_organ",
          "has",
          "been",
          "enticed",
          "by",
          "my",
          "neighbor's",
          "$woman,",
          "or",
          "I",
          "have",
          "lurked",
          "at",
          "his",
          "door,",
        ],
      },
      {
        verse_number: 10,
        words: [
          "then",
          "may",
          "my",
          "own",
          "$woman",
          "grind",
          "for",
          "another,",
          "and",
          "may",
          "other",
          "men",
          "sleep",
          "with",
          "her.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "that",
          "would",
          "be",
          "a",
          "heinous",
          "crime,",
          "an",
          "iniquity",
          "to",
          "be",
          "judged.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "For",
          "it",
          "is",
          "a",
          "fire",
          "that",
          "burns",
          "down",
          "to",
          "Abaddon;",
          "it",
          "would",
          "root",
          "out",
          "my",
          "entire",
          "harvest.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "If",
          "I",
          "have",
          "rejected",
          "the",
          "$scales",
          "of",
          "my",
          "$kneeling",
          "or",
          "maidservant",
          "when",
          "they",
          "made",
          "a",
          "complaint",
          "against",
          "me,",
        ],
      },
      {
        verse_number: 14,
        words: [
          "what",
          "will",
          "I",
          "$hammer",
          "when",
          "$fire",
          "rises",
          "to",
          "judge?",
          "How",
          "will",
          "I",
          "$turn_back",
          "when",
          "called",
          "to",
          "account?",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Did",
          "$no_entry",
          "the",
          "same",
          "One",
          "who",
          "$hammer",
          "me",
          "in",
          "the",
          "womb",
          "also",
          "$hammer",
          "them?",
          "Did",
          "not",
          "the",
          "same",
          "One",
          "form",
          "us",
          "in",
          "the",
          "womb?",
        ],
      },
      {
        verse_number: 16,
        words: [
          "If",
          "I",
          "have",
          "denied",
          "the",
          "desires",
          "of",
          "the",
          "poor",
          "or",
          "allowed",
          "the",
          "widow's",
          "$eyes",
          "to",
          "fail,",
        ],
      },
      {
        verse_number: 17,
        words: [
          "if",
          "I",
          "have",
          "eaten",
          "my",
          "morsel",
          "alone,",
          "$no_entry",
          "sharing",
          "it",
          "with",
          "the",
          "fatherless,",
        ],
      },
      {
        verse_number: 18,
        words: [
          "though",
          "from",
          "my",
          "youth",
          "I",
          "reared",
          "him",
          "as",
          "would",
          "a",
          "$father,",
          "and",
          "from",
          "my",
          "mother's",
          "womb",
          "I",
          "guided",
          "the",
          "widow,",
        ],
      },
      {
        verse_number: 19,
        words: [
          "if",
          "I",
          "have",
          "$eye",
          "one",
          "perish",
          "for",
          "lack",
          "of",
          "clothing,",
          "or",
          "a",
          "needy",
          "man",
          "without",
          "a",
          "cloak,",
        ],
      },
      {
        verse_number: 20,
        words: [
          "if",
          "his",
          "heart",
          "has",
          "$no_entry",
          "$speech+thumbs_up",
          "for",
          "warming",
          "him",
          "with",
          "the",
          "fleece",
          "of",
          "my",
          "sheep,",
        ],
      },
      {
        verse_number: 21,
        words: [
          "if",
          "I",
          "have",
          "lifted",
          "up",
          "my",
          "$hand",
          "against",
          "the",
          "fatherless",
          "because",
          "I",
          "$eye",
          "that",
          "I",
          "had",
          "support",
          "in",
          "the",
          "gate,",
        ],
      },
      {
        verse_number: 22,
        words: [
          "then",
          "may",
          "my",
          "arm",
          "fall",
          "from",
          "my",
          "shoulder",
          "and",
          "be",
          "torn",
          "from",
          "its",
          "socket.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "For",
          "calamity",
          "from",
          "$fire",
          "terrifies",
          "me,",
          "and",
          "His",
          "splendor",
          "I",
          "$no_entry",
          "overpower.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "If",
          "I",
          "have",
          "put",
          "my",
          "trust",
          "in",
          "gold",
          "or",
          "$speech",
          "pure",
          "gold",
          "my",
          "security,",
        ],
      },
      {
        verse_number: 25,
        words: [
          "if",
          "I",
          "have",
          "rejoiced",
          "in",
          "my",
          "great",
          "wealth",
          "because",
          "my",
          "$hand",
          "had",
          "gained",
          "so",
          "much,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "if",
          "I",
          "have",
          "$eye",
          "the",
          "$light",
          "in",
          "its",
          "radiance",
          "or",
          "the",
          "moon",
          "$walking",
          "in",
          "splendor,",
        ],
      },
      {
        verse_number: 27,
        words: [
          "so",
          "that",
          "my",
          "$heart_organ",
          "was",
          "secretly",
          "enticed",
          "and",
          "my",
          "$hand",
          "threw",
          "a",
          "kiss",
          "from",
          "my",
          "mouth,",
        ],
      },
      {
        verse_number: 28,
        words: [
          "this",
          "would",
          "also",
          "be",
          "an",
          "iniquity",
          "to",
          "be",
          "judged,",
          "for",
          "I",
          "would",
          "have",
          "denied",
          "$fire",
          "on",
          "high.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "If",
          "I",
          "have",
          "rejoiced",
          "in",
          "my",
          "enemy's",
          "ruin,",
          "or",
          "exulted",
          "when",
          "$thumbs_down",
          "befell",
          "him,",
        ],
      },
      {
        verse_number: 30,
        words: [
          "I",
          "have",
          "$no_entry",
          "allowed",
          "my",
          "mouth",
          "to",
          "$bow",
          "by",
          "asking",
          "for",
          "his",
          "life",
          "with",
          "a",
          "curse,",
        ],
      },
      {
        verse_number: 31,
        words: [
          "if",
          "the",
          "men",
          "of",
          "my",
          "house",
          "have",
          "$no_entry",
          "$speech,",
          "Who",
          "is",
          "there",
          "who",
          "has",
          "$no_entry",
          "had",
          "his",
          "fill?",
        ],
      },
      {
        verse_number: 32,
        words: [
          "but",
          "$no_entry",
          "stranger",
          "had",
          "to",
          "lodge",
          "on",
          "the",
          "street,",
          "for",
          "my",
          "door",
          "has",
          "been",
          "open",
          "to",
          "the",
          "traveler,",
        ],
      },
      {
        verse_number: 33,
        words: [
          "if",
          "I",
          "have",
          "covered",
          "my",
          "transgressions",
          "like",
          "$person",
          "by",
          "hiding",
          "my",
          "guilt",
          "in",
          "my",
          "heart,",
        ],
      },
      {
        verse_number: 34,
        words: [
          "because",
          "I",
          "greatly",
          "feared",
          "the",
          "crowds",
          "and",
          "the",
          "contempt",
          "of",
          "the",
          "clans",
          "terrified",
          "me,",
          "so",
          "that",
          "I",
          "kept",
          "silent",
          "and",
          "would",
          "$no_entry",
          "go",
          "outside,",
        ],
      },
      {
        verse_number: 35,
        words: [
          "Oh,",
          "that",
          "I",
          "had",
          "one",
          "to",
          "$ear",
          "me!",
          "Here",
          "is",
          "my",
          "signature.",
          "Let",
          "the",
          "Almighty",
          "answer",
          "me;",
          "let",
          "my",
          "accuser",
          "compose",
          "an",
          "indictment.",
        ],
      },
      {
        verse_number: 36,
        words: [
          "Surely",
          "I",
          "would",
          "carry",
          "it",
          "on",
          "my",
          "shoulder",
          "and",
          "wear",
          "it",
          "like",
          "a",
          "crown.",
        ],
      },
      {
        verse_number: 37,
        words: [
          "I",
          "would",
          "give",
          "account",
          "of",
          "all",
          "my",
          "steps;",
          "I",
          "would",
          "approach",
          "Him",
          "like",
          "a",
          "prince.",
        ],
      },
      {
        verse_number: 38,
        words: [
          "If",
          "my",
          "land",
          "cries",
          "out",
          "against",
          "me",
          "and",
          "its",
          "furrows",
          "weep",
          "together,",
        ],
      },
      {
        verse_number: 39,
        words: [
          "if",
          "I",
          "have",
          "devoured",
          "its",
          "produce",
          "without",
          "payment",
          "or",
          "broken",
          "the",
          "spirit",
          "of",
          "its",
          "tenants,",
        ],
      },
      {
        verse_number: 40,
        words: [
          "then",
          "let",
          "briers",
          "grow",
          "instead",
          "of",
          "wheat",
          "and",
          "stinkweed",
          "instead",
          "of",
          "barley.",
          "Thus",
          "conclude",
          "the",
          "$speech",
          "of",
          "Job.",
        ],
      },
    ],
  };
  return chapter;
}
