export function bible_glyph_chapter_hos14() {
  "Hosea 14, drawn in pictures. The last chapter of the book, and after thirteen chapters of accusation it is nothing but the way home. Israel is told what words to bring, God says what He will do with them, and the whole thing turns green. Nine lines.";
  "THE SAME ARROW IS DRAWN FOR THE PEOPLE TURNING BACK AND FOR GOD'S ANGER TURNING AWAY. The turn back arrow falls four times in nine lines. Return, O Israel. Bring your confessions and return. My anger has turned away from them. They will return and dwell in his shade. It is one Hebrew root doing all four jobs, so the page shows the people turning, God's anger turning, and the people turning again, with the same picture every time. After thirteen chapters of accusation, the book ends by drawing the coming back four times.";
  "THE FLAME MEANS GOD IN THE FIRST VERSE AND IDOLS IN THE THIRD, AND THE PAGE CANNOT TELL THEM APART. Return to the LORD your God carries a flame. We will never again say Our gods to the work of our own hands carries the same flame. Two verses apart, opposite meanings, identical marks. A reader with no English sees a flame, a refusal, and a flame, and has no way of knowing that the second one is a lie being renounced. This is the plainest place in the chapter where the pictures need the words, and it is worth a reader knowing the page has this seam in it.";
  "THREE REFUSALS IN ONE BREATH, AND THEY ARE A PEOPLE GIVING UP EVERYTHING THEY EVER TRUSTED. Assyria will not save us. Nor will we ride on horses. We will never again say Our gods. Three refusal signs in one verse, the only three in the chapter, and every one of them is something being let go of - an army, a cavalry, a homemade god. It is the same mark that means loss everywhere else in this book, used here for a people choosing the loss on purpose.";
  "THE GREENEST THREE VERSES IN THE BOOK DRAW ALMOST NOTHING. Dew, lily, root, cedars, shoots, olive tree, fragrance, shade, grain, vine, wine. Eleven growing things across three verses, and not one of those words has a picture seated on it. The fifth verse comes out completely blank. There is one green mark in the whole run and it is on the word grow - and the word sprout, one line earlier, does not get it. The sprout picture is not seated on the word sprout, which is worth knowing before anyone assumes a mark and a word mean the same thing.";
  "THE LAST VERSE OF HOSEA DRAWS A ROAD AND SOMEBODY WALKING ON IT. The ways of the LORD are right, and the righteous walk in them, but the rebellious stumble in them. The second half of the line draws four in a row: a road, the name of God, a measuring rule for righteous, and a walker. Between them they nearly say the sentence. The stumbling is not drawn, so a picture reader gets the road and the walking and has to be told about the falling.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "HOS14",
    reference: "Hosea 14",
    verses: [
      {
        verse_number: 1,
        words: [
          "$turn_back,",
          "O",
          "Israel,",
          "to",
          "the",
          "$name_tag",
          "your",
          "$fire,",
          "for",
          "you",
          "have",
          "stumbled",
          "by",
          "your",
          "iniquity.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$hand_receiving",
          "your",
          "$speech",
          "and",
          "$turn_back",
          "to",
          "the",
          "$name_tag.",
          "$speech",
          "to",
          "Him:",
          "Take",
          "away",
          "all",
          "our",
          "iniquity",
          "and",
          "$hand_receiving",
          "us",
          "$thumbs_up,",
          "that",
          "we",
          "may",
          "present",
          "the",
          "fruit",
          "of",
          "our",
          "lips.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Assyria",
          "will",
          "$no_entry",
          "save",
          "us,",
          "nor",
          "will",
          "$no_entry",
          "we",
          "ride",
          "on",
          "horses.",
          "We",
          "will",
          "$no_entry",
          "again",
          "$speech",
          "Our",
          "$fire",
          "to",
          "the",
          "work",
          "of",
          "our",
          "own",
          "$hand.",
          "For",
          "in",
          "You",
          "the",
          "fatherless",
          "find",
          "compassion.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "will",
          "heal",
          "their",
          "apostasy;",
          "I",
          "will",
          "freely",
          "$heart_red",
          "them,",
          "for",
          "My",
          "anger",
          "has",
          "$turn_back",
          "$tray_out",
          "them.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "I",
          "will",
          "be",
          "like",
          "the",
          "dew",
          "to",
          "Israel;",
          "he",
          "will",
          "blossom",
          "like",
          "the",
          "lily",
          "and",
          "take",
          "root",
          "like",
          "the",
          "cedars",
          "of",
          "Lebanon.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "His",
          "shoots",
          "will",
          "$walking,",
          "and",
          "his",
          "splendor",
          "will",
          "be",
          "like",
          "the",
          "olive",
          "tree,",
          "his",
          "fragrance",
          "like",
          "the",
          "cedars",
          "of",
          "Lebanon.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "They",
          "will",
          "$turn_back",
          "and",
          "dwell",
          "in",
          "his",
          "shade;",
          "they",
          "will",
          "$sprout",
          "grain",
          "and",
          "blossom",
          "like",
          "the",
          "vine.",
          "His",
          "renown",
          "will",
          "be",
          "like",
          "the",
          "wine",
          "of",
          "Lebanon.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "O",
          "Ephraim,",
          "what",
          "have",
          "I",
          "to",
          "do",
          "anymore",
          "with",
          "idols?",
          "It",
          "is",
          "I",
          "who",
          "answer",
          "and",
          "watch",
          "over",
          "him.",
          "I",
          "am",
          "like",
          "a",
          "flourishing",
          "cypress;",
          "your",
          "fruit",
          "comes",
          "$tray_out",
          "Me.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Whoever",
          "is",
          "wise,",
          "let",
          "him",
          "understand",
          "these",
          "things;",
          "whoever",
          "is",
          "discerning,",
          "let",
          "him",
          "$lightbulb",
          "them.",
          "For",
          "the",
          "$road",
          "of",
          "the",
          "$name_tag",
          "are",
          "right,",
          "and",
          "the",
          "$ruler",
          "$walking",
          "in",
          "them,",
          "but",
          "the",
          "rebellious",
          "stumble",
          "in",
          "them.",
        ],
      },
    ],
  };
  return chapter;
}
