export function bible_glyph_chapter_psa022() {
  "The twenty second psalm, drawn in pictures. A man who feels abandoned describes what is happening to his body and to the crowd around him, and then turns and spends the last third of the psalm promising to tell everybody what God did.";
  "WHAT THE PSALM CALLS GOD CHANGES EXACTLY WHERE THE PSALM TURNS. The fire mark stands for God, and it falls four times here - twice in the opening cry, once in the second verse and once in the tenth. Every one of them is in the first ten verses. The name tag stands for the LORD, and it falls six times, and not one of them comes before the nineteenth verse. So the half of the psalm that is abandoned says my God, and the half that is praising says the LORD, and the two halves do not overlap at all. English has both words too and prints them as God and LORD, but nothing in the shape of the page shows a reader that the choice flips and never flips back. The marks show it at a glance, without knowing what either word means.";
  "THE EIGHTH VERSE KEEPS EVERY MARK IN PLAIN LETTERS BECAUSE ENGLISH SAYS LORD THREE TIMES WHERE HEBREW SAYS IT ONCE. He trusts in the LORD, let the LORD deliver him, let the LORD rescue him. Hebrew has the name once and then says let Him deliver, let Him rescue, and English fills the pronouns back in with the noun to keep the sentence clear. If the mark were drawn on the one real occurrence the page would show one tag and two words spelled out, and a reader would reasonably think they were different things. So all three stay in letters. This is the rule this list follows everywhere: where drawing a mark would teach a reader something false, the mark stands down and the prose says why.";
  "THE FIRST VERSE ASKS WHY AND THE TWENTY FOURTH ANSWERS IT WITH THREE NEGATIONS IN A ROW. Why have You forsaken me is the question, and the answer when it comes is not an explanation - it is three refusals stacked: He has not despised, not detested, not hidden His face. The negation mark falls ten times on this page and three of them are in that one verse. Nowhere else on the page do three of them stand together. A reader watching only the marks sees the psalm open with a question and close its argument with a triple no, which is exactly the shape of the Hebrew, and needs no vocabulary at all to follow.";
  "THE SIXTH VERSE HAS THREE DIFFERENT WORDS FOR PEOPLE AND GETS THREE DIFFERENT PICTURES. I am a worm and not a man, scorned by men and despised by the people. Man there is ish, men is adam, and people is am, and the root table draws them as the bearded man, the person, and the family. English writes man, men, people, which looks like one idea in three grammatical forms, and it is not - it is a single man, humanity in general, and a nation, three different sizes of thing. The verse is measuring how far the scorn reaches, and in pictures the widening is visible in the marks themselves.";
  "THE MIDDLE OF THE PSALM IS DRAWN ON A BODY. From the fourteenth verse to the twentieth the marks stop being about God and become anatomy: poured out like water, the heart melting, the strength dried up, the dust of death, the pierced hands, and then the hand of the dog at the end. Water, heart, lightning, skull and hand, one after another, with almost nothing else drawn among them. It is the most physical stretch of anything on this list, and it is the part of the psalm the Gospels are pointing at. A reader who has no words at all can see that this section is about a body coming apart, because the pictures are of the parts.";
  "THE NAME TAG MEANS THE WORD NAME EXACTLY ONCE HERE, IN THE VERSE THE NEW TESTAMENT QUOTES. Five of the six tags on this page are the divine name. The sixth, in the twenty second verse, is the ordinary Hebrew word for a name: I will proclaim Your name to my brothers, in the assembly I will praise You. That is the verse the letter to the Hebrews quotes to say that Jesus is not ashamed to call people brothers, and the two other marks in it are the brother and the gathering. So the pivot of the whole psalm - the moment the sufferer starts speaking to a crowd instead of to God - carries three marks, and all three of them are about who is being spoken to.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA022",
    reference: "Psalm 22",
    verses: [
      {
        verse_number: 1,
        words: [
          "My",
          "$fire,",
          "my",
          "$fire,",
          "why",
          "have",
          "You",
          "forsaken",
          "me?",
          "Why",
          "are",
          "You",
          "so",
          "far",
          "from",
          "saving",
          "me,",
          "so",
          "far",
          "from",
          "my",
          "$speech",
          "of",
          "groaning?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "I",
          "cry",
          "out",
          "by",
          "day,",
          "O",
          "my",
          "$fire,",
          "but",
          "You",
          "do",
          "$no_entry",
          "answer,",
          "and",
          "by",
          "night,",
          "but",
          "I",
          "have",
          "$no_entry",
          "rest.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Yet",
          "You",
          "are",
          "$sparkle,",
          "enthroned",
          "on",
          "the",
          "praises",
          "of",
          "Israel.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "In",
          "You",
          "our",
          "$father",
          "trusted;",
          "they",
          "trusted",
          "and",
          "You",
          "delivered",
          "them.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "They",
          "cried",
          "out",
          "to",
          "You",
          "and",
          "were",
          "set",
          "free;",
          "they",
          "trusted",
          "in",
          "You",
          "and",
          "were",
          "$no_entry",
          "disappointed.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "But",
          "I",
          "am",
          "a",
          "worm",
          "and",
          "$no_entry",
          "a",
          "$man_beard,",
          "scorned",
          "by",
          "$person",
          "and",
          "despised",
          "by",
          "the",
          "$family.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "All",
          "who",
          "$eye",
          "me",
          "mock",
          "me;",
          "they",
          "sneer",
          "and",
          "shake",
          "their",
          "heads:",
        ],
      },
      {
        verse_number: 8,
        words: [
          "He",
          "trusts",
          "in",
          "the",
          "LORD,",
          "let",
          "the",
          "LORD",
          "deliver",
          "him;",
          "let",
          "the",
          "LORD",
          "rescue",
          "him,",
          "since",
          "He",
          "delights",
          "in",
          "him.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Yet",
          "You",
          "brought",
          "me",
          "forth",
          "from",
          "the",
          "womb;",
          "You",
          "made",
          "me",
          "secure",
          "at",
          "my",
          "mother's",
          "breast.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "From",
          "birth",
          "I",
          "was",
          "cast",
          "upon",
          "You;",
          "from",
          "my",
          "mother's",
          "womb",
          "You",
          "have",
          "been",
          "my",
          "$fire.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Be",
          "$no_entry",
          "far",
          "$tray_out",
          "me,",
          "for",
          "trouble",
          "is",
          "near",
          "and",
          "there",
          "is",
          "no",
          "one",
          "to",
          "help.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Many",
          "bulls",
          "surround",
          "me;",
          "strong",
          "bulls",
          "of",
          "Bashan",
          "encircle",
          "me.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "They",
          "open",
          "their",
          "jaws",
          "against",
          "me",
          "like",
          "lions",
          "that",
          "roar",
          "and",
          "maul.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "I",
          "am",
          "poured",
          "out",
          "like",
          "$water,",
          "and",
          "all",
          "my",
          "bones",
          "are",
          "disjointed.",
          "My",
          "$heart_organ",
          "is",
          "like",
          "wax;",
          "it",
          "melts",
          "away",
          "within",
          "me.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "My",
          "$lightning",
          "is",
          "dried",
          "up",
          "like",
          "a",
          "potsherd,",
          "and",
          "my",
          "tongue",
          "sticks",
          "to",
          "the",
          "roof",
          "of",
          "my",
          "mouth.",
          "You",
          "lay",
          "me",
          "in",
          "the",
          "dust",
          "of",
          "$skull.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "For",
          "dogs",
          "surround",
          "me;",
          "a",
          "band",
          "of",
          "evil",
          "men",
          "encircles",
          "me;",
          "they",
          "have",
          "pierced",
          "my",
          "$hand",
          "and",
          "feet.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "I",
          "can",
          "count",
          "all",
          "my",
          "bones;",
          "they",
          "stare",
          "and",
          "$eye",
          "over",
          "me.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "They",
          "divide",
          "my",
          "garments",
          "among",
          "them,",
          "and",
          "cast",
          "lots",
          "for",
          "my",
          "clothing.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "But",
          "You,",
          "O",
          "$name_tag,",
          "be",
          "$no_entry",
          "far",
          "off;",
          "O",
          "my",
          "Strength,",
          "come",
          "quickly",
          "to",
          "help",
          "me.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Deliver",
          "my",
          "$person_other",
          "from",
          "the",
          "$sword,",
          "my",
          "precious",
          "life",
          "from",
          "the",
          "$hand",
          "of",
          "wild",
          "dogs.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Save",
          "me",
          "from",
          "the",
          "mouth",
          "of",
          "the",
          "lion;",
          "at",
          "the",
          "horns",
          "of",
          "the",
          "wild",
          "oxen",
          "You",
          "have",
          "answered",
          "me!",
        ],
      },
      {
        verse_number: 22,
        words: [
          "I",
          "will",
          "proclaim",
          "Your",
          "$name_tag",
          "to",
          "my",
          "$brother;",
          "I",
          "will",
          "praise",
          "You",
          "in",
          "the",
          "$church.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "You",
          "who",
          "fear",
          "the",
          "$name_tag,",
          "praise",
          "Him!",
          "All",
          "descendants",
          "of",
          "Jacob,",
          "honor",
          "Him!",
          "Revere",
          "Him,",
          "all",
          "offspring",
          "of",
          "Israel!",
        ],
      },
      {
        verse_number: 24,
        words: [
          "For",
          "He",
          "has",
          "$no_entry",
          "despised,",
          "$no_entry",
          "detested,",
          "the",
          "torment",
          "of",
          "the",
          "afflicted.",
          "He",
          "has",
          "$no_entry",
          "hidden",
          "His",
          "face",
          "$tray_out",
          "him,",
          "but",
          "has",
          "$ear",
          "his",
          "cry",
          "for",
          "help.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "My",
          "praise",
          "for",
          "You",
          "resounds",
          "in",
          "the",
          "great",
          "$church;",
          "I",
          "will",
          "fulfill",
          "my",
          "vows",
          "before",
          "those",
          "who",
          "fear",
          "You.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "The",
          "poor",
          "will",
          "eat",
          "and",
          "be",
          "satisfied;",
          "those",
          "who",
          "seek",
          "the",
          "$name_tag",
          "will",
          "praise",
          "Him.",
          "May",
          "your",
          "$heart_organ",
          "$sprout",
          "forever!",
        ],
      },
      {
        verse_number: 27,
        words: [
          "All",
          "the",
          "ends",
          "of",
          "the",
          "$earth",
          "will",
          "remember",
          "and",
          "$turn_back",
          "to",
          "the",
          "$name_tag.",
          "All",
          "the",
          "families",
          "of",
          "the",
          "$map",
          "will",
          "$bowing",
          "before",
          "Him.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "For",
          "dominion",
          "belongs",
          "to",
          "the",
          "$name_tag",
          "and",
          "He",
          "rules",
          "over",
          "the",
          "$map.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "All",
          "the",
          "rich",
          "of",
          "the",
          "$earth",
          "will",
          "feast",
          "and",
          "$bowing;",
          "all",
          "who",
          "go",
          "down",
          "to",
          "the",
          "dust",
          "will",
          "kneel",
          "before",
          "Him",
          "-",
          "even",
          "those",
          "$no_entry",
          "able",
          "to",
          "$sprout",
          "their",
          "$person_other.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "Posterity",
          "will",
          "$kneeling",
          "Him;",
          "they",
          "will",
          "declare",
          "the",
          "$crown",
          "to",
          "a",
          "new",
          "generation.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "They",
          "will",
          "$footprints",
          "and",
          "proclaim",
          "His",
          "$ruler",
          "to",
          "a",
          "$family",
          "yet",
          "unborn",
          "-",
          "for",
          "He",
          "has",
          "$hammer",
          "it.",
        ],
      },
    ],
  };
  return chapter;
}
