export function bible_glyph_chapter_job28() {
  "Job 28, drawn in pictures, so that a person who cannot read the letters can still follow it. It is a poem about a mine: men dig silver and gold out of the dark, and then the poem asks where wisdom is dug from, and answers that nobody can buy it. Twenty eight lines.";
  "THE QUESTION THE CHAPTER EXISTS TO ASK IS ASKED TWICE AND DRAWN NEITHER TIME. But where can wisdom be found, and where does understanding dwell? That is the twelfth line, and it comes out completely blank. The twentieth line asks it again and gets one mark, a pair of footprints, on the word come. There is no picture for wisdom and none for understanding, so on both askings the page shows a reader everything except what is being looked for. This is the third chapter in a row to run into it. Proverbs 1 lost the sentence its whole book stands on, Proverbs 8 lost thirty six lines of a speaker who is called Wisdom, and Job 28 loses the question itself.";
  "THE ANSWER IS IN THE LAST LINE AND THE TWO WORDS THAT ARE THE ANSWER ARE PLAIN. The fear of the Lord, that is wisdom; and to turn away from evil is understanding. Four marks land on it: some speaking, a person, a crown for the Lord, and a thumbs down for evil. Wisdom and understanding, the two words the chapter has spent twenty seven lines hunting, are the two words with nothing on them. A reader following pictures reaches the end of the poem and is told that somebody said something to a man about a lord and about something bad.";
  "THE POEM IS A PRICE LIST AND NOT ONE ITEM ON IT IS DRAWN. Silver, gold, iron, copper, ore, sapphires, onyx, crystal, jewels, coral, quartz, rubies, topaz: the word gold alone comes seven times and silver twice, and none of them has a picture. The whole argument is that wisdom is worth more than all of this, so both sides of the comparison are gone at once. Five lines in a row, the fifteenth to the nineteenth, say it cannot be bought, cannot be valued, cannot be compared, cannot be exchanged, and they carry eight marks between them of which seven are the same crossed circle. That is true to the text and it leaves the reader with no idea what it is not worth buying with.";
  "THIS IS THE ONLY MINE IN THE BIBLE AND THERE IS NO SHAFT AND NO ORE. The first eleven lines are a man on a rope in a tunnel: he cuts a shaft, he dangles and sways far from anyone, he strikes the flint, he overturns mountains at their base, he hews channels through the rock and stops the streams up to bring hidden things to light. What the page can show of the mining lines is a hand taking, the dark twice, two arrows meaning away from here, some ground, a loaf, a mountain, a pair of eyes on the treasure and a light at the end. The shaft, the rope, the ore, the flint, the furnace and the tunnel have no pictures at all, and the opening line, which names both silver and gold, comes out blank.";
  "THE FALCON IS GONE AND ITS EYE IS STILL THERE. No bird of prey knows that path, no falcon eye has seen it, no proud beast has trodden it, no lion has prowled over it. Four creatures in two lines, and the marks that arrive are four crossed circles, a lamp and a pair of eyes. So the eye is drawn and the bird it belongs to is not, which is what happened to the stone with seven eyes on it in Zechariah 3. A bird picture does exist and is used on eight other pages here; it does not come because these birds are named as a bird of prey and a falcon rather than by the ordinary word. The lion has no picture at all.";
  "WHERE THE CHAPTER TURNS TO GOD THE PICTURES COME BACK. He fixed the weight of the wind and measured out the waters, and the wind and the water both land. He looks to the ends of the earth and sees everything under the heavens, and the earth, the sky and the eye all land. It is worth saying which half of this poem the page can carry: the half about God weighing the world comes through, and the half about men digging in it does not.";
  "One mark was dropped in the eighth line. Proud beasts is the sons of pride in Hebrew, so the draft put a child on it; the English word has no child in it, so it was left plain. Rain and thunderbolt in the twenty sixth line, and Abaddon in the twenty second, have no pictures either.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "JOB28",
    reference: "Job 28",
    verses: [
      {
        verse_number: 1,
        words: [
          "Surely",
          "there",
          "is",
          "a",
          "mine",
          "for",
          "silver",
          "and",
          "a",
          "place",
          "where",
          "gold",
          "is",
          "refined.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Iron",
          "is",
          "$hand_receiving",
          "from",
          "the",
          "earth,",
          "and",
          "copper",
          "is",
          "smelted",
          "from",
          "ore.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Man",
          "puts",
          "an",
          "end",
          "to",
          "the",
          "$darkness;",
          "he",
          "probes",
          "the",
          "farthest",
          "recesses",
          "for",
          "ore",
          "in",
          "the",
          "deepest",
          "$darkness.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$tray_out",
          "human",
          "habitation",
          "he",
          "cuts",
          "a",
          "shaft,",
          "in",
          "places",
          "forgotten",
          "by",
          "the",
          "foot",
          "of",
          "man;",
          "far",
          "from",
          "men",
          "he",
          "dangles",
          "and",
          "sways.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$earth,",
          "$tray_out",
          "which",
          "$bread",
          "comes,",
          "is",
          "transformed",
          "below",
          "as",
          "by",
          "fire.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Its",
          "rocks",
          "are",
          "the",
          "source",
          "of",
          "sapphires,",
          "containing",
          "flecks",
          "of",
          "gold.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$no_entry",
          "bird",
          "of",
          "prey",
          "$lightbulb",
          "that",
          "path;",
          "$no_entry",
          "falcon",
          "$eyes",
          "has",
          "seen",
          "it.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Proud",
          "beasts",
          "have",
          "$no_entry",
          "trodden",
          "it;",
          "$no_entry",
          "lion",
          "has",
          "prowled",
          "over",
          "it.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "The",
          "miner",
          "strikes",
          "the",
          "flint;",
          "he",
          "overturns",
          "$mountain",
          "at",
          "their",
          "base.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "hews",
          "out",
          "channels",
          "in",
          "the",
          "rocks,",
          "and",
          "his",
          "$eyes",
          "$eye",
          "every",
          "treasure.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "He",
          "stops",
          "up",
          "the",
          "sources",
          "of",
          "the",
          "streams",
          "to",
          "bring",
          "what",
          "is",
          "hidden",
          "to",
          "$light.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "But",
          "where",
          "can",
          "wisdom",
          "be",
          "found,",
          "and",
          "where",
          "does",
          "understanding",
          "dwell?",
        ],
      },
      {
        verse_number: 13,
        words: [
          "$no_entry",
          "man",
          "can",
          "$lightbulb",
          "its",
          "value,",
          "$no_entry",
          "is",
          "it",
          "found",
          "in",
          "the",
          "$earth",
          "of",
          "the",
          "$sprout.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "The",
          "ocean",
          "depths",
          "$speech,",
          "It",
          "is",
          "$no_entry",
          "in",
          "me,",
          "while",
          "the",
          "$sea",
          "$speech,",
          "It",
          "is",
          "not",
          "with",
          "me.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "It",
          "$no_entry",
          "be",
          "$hands_giving",
          "with",
          "gold,",
          "$no_entry",
          "can",
          "its",
          "price",
          "be",
          "weighed",
          "out",
          "in",
          "silver.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "It",
          "$no_entry",
          "be",
          "valued",
          "in",
          "the",
          "gold",
          "of",
          "Ophir,",
          "in",
          "precious",
          "onyx",
          "or",
          "sapphire.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "$no_entry",
          "gold",
          "nor",
          "crystal",
          "can",
          "compare",
          "to",
          "it,",
          "nor",
          "can",
          "it",
          "be",
          "exchanged",
          "for",
          "jewels",
          "of",
          "fine",
          "gold.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Coral",
          "and",
          "quartz",
          "are",
          "$no_entry",
          "of",
          "mention;",
          "the",
          "price",
          "of",
          "wisdom",
          "is",
          "beyond",
          "rubies.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Topaz",
          "from",
          "Cush",
          "$no_entry",
          "compare",
          "to",
          "it;",
          "it",
          "$no_entry",
          "be",
          "valued",
          "in",
          "pure",
          "gold.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "From",
          "where,",
          "then,",
          "does",
          "wisdom",
          "$footprints,",
          "and",
          "where",
          "does",
          "understanding",
          "dwell?",
        ],
      },
      {
        verse_number: 21,
        words: [
          "It",
          "is",
          "hidden",
          "from",
          "the",
          "$eyes",
          "of",
          "every",
          "$sprout",
          "and",
          "concealed",
          "from",
          "the",
          "$bird",
          "of",
          "the",
          "$sky.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Abaddon",
          "and",
          "$skull",
          "$speech,",
          "We",
          "have",
          "$ear",
          "a",
          "rumor",
          "about",
          "it.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "But",
          "$fire",
          "understands",
          "its",
          "$road,",
          "and",
          "He",
          "$lightbulb",
          "its",
          "place.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "For",
          "He",
          "looks",
          "to",
          "the",
          "ends",
          "of",
          "the",
          "$earth",
          "and",
          "$eye",
          "everything",
          "under",
          "the",
          "$sky.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "When",
          "God",
          "$hammer",
          "the",
          "weight",
          "of",
          "the",
          "$wind",
          "and",
          "measured",
          "out",
          "the",
          "$water,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "when",
          "He",
          "$hammer",
          "a",
          "limit",
          "for",
          "the",
          "rain",
          "and",
          "a",
          "$road",
          "for",
          "the",
          "thunderbolt,",
        ],
      },
      {
        verse_number: 27,
        words: [
          "then",
          "He",
          "$eye",
          "wisdom",
          "and",
          "appraised",
          "it;",
          "He",
          "established",
          "it",
          "and",
          "searched",
          "it",
          "out.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "And",
          "He",
          "$speech",
          "to",
          "$person,",
          "Behold,",
          "the",
          "fear",
          "of",
          "the",
          "$crown,",
          "that",
          "is",
          "wisdom;",
          "and",
          "to",
          "turn",
          "away",
          "from",
          "$thumbs_down",
          "is",
          "understanding.",
        ],
      },
    ],
  };
  return chapter;
}
