export function bible_glyph_chapter_job19() {
  "The nineteenth chapter of Job, drawn in pictures. Job answers his friends for the fourth time, lists everyone who has left him, and then says the sentence about his Redeemer living. It is twenty nine lines long and the sentence everyone remembers is in the twenty fifth.";
  "THE PEOPLE WHO ABANDONED HIM ARE CALLED HIS KNOWERS. The knowing mark falls five times on this page, and English hides three of them. In the sixth verse Job tells his friends to understand one thing. In the thirteenth his acquaintances have abandoned him, and in the fourteenth his friends have forgotten him - both of those words are, in Hebrew, the ones who know me. Then the twenty fifth: but I know that my Redeemer lives. And the twenty ninth, to the friends: so that you may know there is a judgment. So the chapter is one word five times. He asks them to know, his knowers all leave, and what he is left holding is that he knows. There is no way to see that in English, where the same word arrives as understand, acquaintances, friends, know and know.";
  "THE FLESH MARK FALLS THREE TIMES AND THE LAST ONE IS THE HOPE. In the twentieth verse his skin and flesh cling to his bones. In the twenty second he asks his friends whether they will never get enough of his flesh. In the twenty sixth he says that after his skin has been destroyed, yet in his flesh he will see God. The same picture is his body wasting, his body being eaten by his friends, and his body standing up to see. A reader watching only that one mark gets the whole argument of the chapter in three lines.";
  "THE ONLY GLORY MARK ON THE PAGE IS BEING TAKEN OFF HIS HEAD. It appears once, in the ninth verse - He has stripped me of my honor - and never again, not even in the twenty fifth where the Redeemer stands. The two growing pictures work the same way: the tenth verse uproots his hope like a tree, and the twenty fifth says his Redeemer lives. Those are the only two, and they are the two ends of the argument.";
  "THE TWENTY SEVENTH VERSE DRAWS SEEING TWICE IN ONE LINE. I will see Him for myself, my eyes will behold Him. Hebrew doubles it deliberately - the eyes and the beholding are two separate words piled up to insist that this is not somebody else doing the looking. The picture keeps both marks side by side. It also carries the last crossing out mark on the page, on and not as a stranger, which is the only one of the five that is not about something Job has been refused.";
  "THE BREATH MARK IS PUT AWAY IN THE SEVENTEENTH VERSE. My breath is repulsive to my wife, and the word there is the same one used everywhere else in this Bible for the Spirit of God. The mark means the Spirit, not moving air, so where a line means literal breath it is left in plain letters. The same restraint applies to the word God on this page: Job says it four times and it is only drawn once, because he uses three different Hebrew names for God and only one of them has a seat in the root table.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "JOB19",
    reference: "Job 19",
    verses: [
      {
        verse_number: 1,
        words: ["Then", "Job", "answered:"],
      },
      {
        verse_number: 2,
        words: [
          "How",
          "long",
          "will",
          "you",
          "torment",
          "$person_other",
          "and",
          "crush",
          "me",
          "with",
          "words?",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Ten",
          "times",
          "now",
          "you",
          "have",
          "reproached",
          "me;",
          "you",
          "shamelessly",
          "mistreat",
          "me.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Even",
          "if",
          "I",
          "have",
          "truly",
          "gone",
          "astray,",
          "my",
          "error",
          "concerns",
          "me",
          "alone.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "If",
          "indeed",
          "you",
          "would",
          "exalt",
          "yourselves",
          "above",
          "me",
          "and",
          "use",
          "my",
          "disgrace",
          "against",
          "me,",
        ],
      },
      {
        verse_number: 6,
        words: [
          "then",
          "$lightbulb",
          "that",
          "it",
          "is",
          "God",
          "who",
          "has",
          "wronged",
          "me",
          "and",
          "drawn",
          "His",
          "net",
          "around",
          "me.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Though",
          "I",
          "cry",
          "out,",
          "Violence!",
          "I",
          "get",
          "$no_entry",
          "response;",
          "though",
          "I",
          "call",
          "for",
          "help,",
          "there",
          "is",
          "no",
          "$scales.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "He",
          "has",
          "blocked",
          "my",
          "way",
          "so",
          "I",
          "$no_entry",
          "pass;",
          "He",
          "has",
          "veiled",
          "my",
          "paths",
          "with",
          "$darkness.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "has",
          "stripped",
          "me",
          "of",
          "my",
          "$star",
          "and",
          "removed",
          "the",
          "crown",
          "from",
          "my",
          "head.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "tears",
          "me",
          "down",
          "on",
          "every",
          "side",
          "until",
          "I",
          "am",
          "$walking;",
          "He",
          "uproots",
          "my",
          "hope",
          "like",
          "a",
          "$tree.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "His",
          "anger",
          "burns",
          "against",
          "me,",
          "and",
          "He",
          "counts",
          "me",
          "among",
          "His",
          "enemies.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "His",
          "troops",
          "$footprints",
          "together;",
          "they",
          "construct",
          "a",
          "$road",
          "against",
          "me",
          "and",
          "encamp",
          "around",
          "my",
          "tent.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "He",
          "has",
          "removed",
          "my",
          "$brother",
          "from",
          "me;",
          "my",
          "$lightbulb",
          "have",
          "abandoned",
          "me.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "My",
          "kinsmen",
          "have",
          "failed",
          "me,",
          "and",
          "my",
          "$lightbulb",
          "have",
          "forgotten",
          "me.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "My",
          "$house",
          "and",
          "maidservants",
          "count",
          "me",
          "as",
          "a",
          "stranger;",
          "I",
          "am",
          "a",
          "foreigner",
          "in",
          "their",
          "$eyes.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "I",
          "call",
          "for",
          "my",
          "$kneeling,",
          "but",
          "he",
          "does",
          "$no_entry",
          "answer,",
          "though",
          "I",
          "implore",
          "him",
          "with",
          "my",
          "own",
          "mouth.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "My",
          "breath",
          "is",
          "repulsive",
          "to",
          "my",
          "$woman,",
          "and",
          "I",
          "am",
          "loathsome",
          "to",
          "my",
          "own",
          "$son.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Even",
          "little",
          "boys",
          "scorn",
          "me;",
          "when",
          "I",
          "appear,",
          "they",
          "$mouth",
          "me.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "All",
          "my",
          "best",
          "friends",
          "despise",
          "me,",
          "and",
          "those",
          "I",
          "$heart_red",
          "have",
          "turned",
          "against",
          "me.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "My",
          "skin",
          "and",
          "$meat",
          "cling",
          "to",
          "my",
          "bones;",
          "I",
          "have",
          "escaped",
          "by",
          "the",
          "skin",
          "of",
          "my",
          "teeth.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Have",
          "pity",
          "on",
          "me,",
          "my",
          "friends,",
          "have",
          "pity,",
          "for",
          "the",
          "$hand",
          "of",
          "God",
          "has",
          "struck",
          "me.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Why",
          "do",
          "you",
          "persecute",
          "me",
          "as",
          "$fire",
          "does?",
          "Will",
          "you",
          "$no_entry",
          "get",
          "enough",
          "of",
          "my",
          "$meat?",
        ],
      },
      {
        verse_number: 23,
        words: [
          "I",
          "wish",
          "that",
          "my",
          "words",
          "were",
          "recorded",
          "and",
          "inscribed",
          "in",
          "a",
          "book,",
        ],
      },
      {
        verse_number: 24,
        words: [
          "or",
          "chiseled",
          "in",
          "stone",
          "forever",
          "by",
          "an",
          "iron",
          "stylus",
          "on",
          "lead!",
        ],
      },
      {
        verse_number: 25,
        words: [
          "But",
          "I",
          "$lightbulb",
          "that",
          "my",
          "Redeemer",
          "$sprout,",
          "and",
          "in",
          "the",
          "end",
          "He",
          "will",
          "stand",
          "upon",
          "the",
          "earth.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "Even",
          "after",
          "my",
          "skin",
          "has",
          "been",
          "destroyed,",
          "yet",
          "in",
          "my",
          "$meat",
          "I",
          "will",
          "see",
          "God.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "I",
          "will",
          "see",
          "Him",
          "for",
          "myself;",
          "my",
          "$eyes",
          "will",
          "$eye",
          "Him,",
          "and",
          "$no_entry",
          "as",
          "a",
          "stranger.",
          "How",
          "my",
          "heart",
          "yearns",
          "within",
          "me!",
        ],
      },
      {
        verse_number: 28,
        words: [
          "If",
          "you",
          "$speech,",
          "Let",
          "us",
          "persecute",
          "him,",
          "since",
          "the",
          "root",
          "of",
          "the",
          "$speech",
          "lies",
          "with",
          "him,",
        ],
      },
      {
        verse_number: 29,
        words: [
          "then",
          "you",
          "should",
          "fear",
          "the",
          "$sword",
          "yourselves,",
          "because",
          "wrath",
          "brings",
          "punishment",
          "by",
          "the",
          "$sword,",
          "so",
          "that",
          "you",
          "may",
          "$lightbulb",
          "there",
          "is",
          "a",
          "judgment.",
        ],
      },
    ],
  };
  return chapter;
}
