export function bible_glyph_chapter_psa046() {
  "Psalm 46, drawn in pictures. The psalm that gave Martin Luther his hymn, and the source of the sentence people quote most often when everything is going wrong: Be still, and know that I am God. Eleven lines in which the whole world comes apart and one city does not. A song of the sons of Korah.";
  "SEVEN GOD FLAMES IN ELEVEN LINES, AND THE ONE REAL FIRE IN THE PSALM IS NOT DRAWN AT ALL. This Bible draws the word God as a flame. Here it falls seven times, more than any other picture on the page - our refuge, the city of God, God is within her, God will help her, the God of Jacob, I am God, the God of Jacob again. Then the ninth verse says He burns the shields in the fire, and that fire, the only actual burning thing in the psalm, arrives in plain letters. The Hebrew word for a real fire is not the one the flame is seated on. So a reader sees seven flames that are all God and none that are fire, which is exactly the distinction this Bible is trying to teach.";
  "THE HEART IS DRAWN ONCE HERE AND IT IS THE HEART OF THE SEA. The second verse says the mountains are toppled into the depths of the seas, and the Hebrew word behind depths is the ordinary word for a heart - the thing in your chest. So the page draws a beating heart in the middle of a line about drowning mountains. Nothing was arranged to make that happen; the word simply is what it is, and the picture follows the word. It is the only heart in the psalm.";
  "BE STILL AND KNOW THAT I AM GOD DRAWS EXACTLY TWO MARKS. A lightbulb for know, and a flame for God. Be still has no picture at all, and neither does I am. So the single most quoted line in this psalm reaches a reader with no English as two shapes side by side: understanding, and God. That is not a bad reduction of what the sentence means, and it took nothing but the root table to get there.";
  "THE EARTH IS DRAWN FIVE TIMES AND IT NEVER ONCE HOLDS STILL. The earth is transformed. The earth melts when He lifts His voice. He brings devastation upon the earth. He makes wars to cease throughout the earth. I will be exalted over the earth. Five grounds, and every one of them is moving, melting, being wrecked or being stood on. The mountains are drawn twice and they are toppling both times. The psalm tells a person not to be afraid and then spends nine lines describing precisely the thing they are afraid of.";
  "THE REFRAIN IS DRAWN THE SAME WAY BOTH TIMES IT COMES. The LORD of Hosts is with us; the God of Jacob is our fortress. That line is the seventh verse and it is the eleventh verse, word for word, and both times it puts down the name of God and then the flame and nothing else - the word fortress has no seat. So the psalm has a picture chorus: two marks, twice, in the same order, closing each half of the song.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA046",
    reference: "Psalm 46",
    verses: [
      {
        verse_number: 1,
        words: [
          "For",
          "the",
          "choirmaster.",
          "Of",
          "the",
          "$son",
          "of",
          "Korah.",
          "According",
          "to",
          "Alamoth.",
          "A",
          "song.",
          "$fire",
          "is",
          "our",
          "refuge",
          "and",
          "strength,",
          "an",
          "ever-present",
          "help",
          "in",
          "times",
          "of",
          "trouble.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Therefore",
          "we",
          "will",
          "$no_entry",
          "fear,",
          "though",
          "the",
          "$earth",
          "is",
          "transformed",
          "and",
          "the",
          "$mountain",
          "are",
          "toppled",
          "into",
          "the",
          "$heart_organ",
          "of",
          "the",
          "$sea,",
        ],
      },
      {
        verse_number: 3,
        words: [
          "though",
          "their",
          "$water",
          "roar",
          "and",
          "foam",
          "and",
          "the",
          "$mountain",
          "quake",
          "in",
          "the",
          "surge.",
          "Selah",
        ],
      },
      {
        verse_number: 4,
        words: [
          "There",
          "is",
          "a",
          "river",
          "whose",
          "streams",
          "delight",
          "the",
          "$city",
          "of",
          "$fire,",
          "the",
          "$sparkle",
          "place",
          "where",
          "the",
          "Most",
          "High",
          "dwells.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$fire",
          "is",
          "within",
          "her;",
          "she",
          "will",
          "not",
          "be",
          "moved.",
          "$fire",
          "will",
          "help",
          "her",
          "when",
          "morning",
          "dawns.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$map",
          "rage,",
          "$castle",
          "crumble;",
          "the",
          "$earth",
          "melts",
          "when",
          "He",
          "$hands_giving",
          "His",
          "$voice.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$name_tag",
          "of",
          "Hosts",
          "is",
          "with",
          "us;",
          "the",
          "$fire",
          "of",
          "Jacob",
          "is",
          "our",
          "fortress.",
          "Selah",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$walking,",
          "see",
          "the",
          "works",
          "of",
          "the",
          "$name_tag,",
          "who",
          "brings",
          "devastation",
          "upon",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "makes",
          "wars",
          "to",
          "cease",
          "throughout",
          "the",
          "$earth;",
          "He",
          "breaks",
          "the",
          "bow",
          "and",
          "shatters",
          "the",
          "spear;",
          "He",
          "burns",
          "the",
          "shields",
          "in",
          "the",
          "fire.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Be",
          "still",
          "and",
          "$lightbulb",
          "that",
          "I",
          "am",
          "$fire;",
          "I",
          "will",
          "be",
          "exalted",
          "among",
          "the",
          "$map,",
          "I",
          "will",
          "be",
          "exalted",
          "over",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "The",
          "$name_tag",
          "of",
          "Hosts",
          "is",
          "with",
          "us;",
          "the",
          "$fire",
          "of",
          "Jacob",
          "is",
          "our",
          "fortress.",
          "Selah",
        ],
      },
    ],
  };
  return chapter;
}
