export function bible_glyph_chapter_2jn01() {
  "The nineteenth picture Bible chapter written by hand: the whole of the second letter of John, in the shorthand a person types.";
  "IT IS THE FIRST WHOLE BOOK WRITTEN IN ONE SITTING. The letter of John already here took five chapters and many sittings to finish, and every other book in this collection is still a chapter or two out of a long one. This letter is thirteen verses long, so the book and the chapter and the file are the same thing, and a reader who opens it reads a complete piece of the Bible from its first word to its last without once meeting a gap. That is a different experience from reading a chapter, and until now nothing here offered it in a single sitting.";
  "AND IT COST NO PICTURES AT ALL. Every word this letter draws was already seated by the five chapters of the first letter, which is the same writer turning over the same few words - the truth, the love, the walking, the commandment, the children. The second chapter to come out of a book costing nothing is the argument for a table keyed by root; the second BOOK by the same hand costing nothing says the saving follows the writer and not just the scroll.";
  "TWO DIFFERENT GREEK NEGATIVES DRAW THE SAME MARK, ELEVEN TIMES IN THIRTEEN VERSES. Ou and me are not one word and no lexicon merges them - one denies a fact and the other denies a thought - but the picture Bible seats both on the no entry sign, and this letter is where that decision is finally worked hard. Verse nine has them one clause apart, denying the same man twice. The distinction they carry is mood, and mood is exactly what a mark on a page cannot say; drawing two signs would have taught a reader a difference they could not use and could not check.";
  "THE SMILE DOES TWO JOBS AND THIS CHAPTER IS WHY THAT IS REALLY ONE JOB. It is joy in verse twelve and it is a greeting in verses ten and eleven, and an English reader meets those as unrelated words. The Greek is one root: to greet somebody is to say rejoice to them. So the mark that looked like it was being asked to mean two things is the mark that shows the two things were one thing, which is the opposite of what happened to the arrow in the twenty third psalm - there one mark said turn back and dwell in one chapter and the second use had to be refused. A mark doing two jobs is a hazard until you check which kind it is.";
  "AND THE GREETING IS DRAWN AS TWO MARKS BECAUSE THE GREEK IS TWO WORDS. English says greet him and the Greek says say rejoice to him, so the speech mark and the smile stand side by side and the reader watches a greeting being assembled out of its parts. Smoothing that to one English word would have hidden the very thing the previous paragraph turned on.";
  "AND THERE ARE TWO SPEAKING MARKS IN THIRTEEN VERSES. Lego is drawn as the speech in verses ten and eleven and laleo as the mouth in verse twelve, where John hopes to speak face to face. They are near enough in English to be the same word and far enough in Greek to be seated apart, and this is the shortest passage in the collection where both stand close enough for a reader to notice the difference exists.";
  "THE COMMANDMENT AND THE RECEIVING IN VERSE FOUR WERE BOTH HIDDEN BY SMOOTH ENGLISH. Every readable translation writes just as the Father has commanded us, which is one verb; the Greek is just as we received commandment from the Father, which is a verb and a noun, and both of them are seated - the hand taking something and the scroll. So the English here follows the Greek and reads a little stiffer, because the smoother sentence would have drawn one mark where the writer wrote two. This is the same trade the twenty third psalm took on the days it says twice.";
  "ONE MARK CARRIES HIS AND HIM AND HER AND IT. Autos is the pointing back and it is drawn six times, and the last of them is the crux: verse six ends that you must walk in IT, and almost every English Bible writes in love, because it reads better and the antecedent is love. The mark points back and does not name what it points at, so the reader is left in exactly the position the Greek leaves them - which is the one time in this letter where a picture is more faithful than the English it replaces.";
  "AND VERSE THREE HAS TWO ANDS AND ONLY ONE IS DRAWN. Grace, mercy AND peace - that and is supplied by the translator and is not in the Greek at all, while the and joining the Father to Jesus Christ is. So one stands as a plain English word between two marked ones. Drawing both would have been the easy thing and would have quietly taught that the picture means the English word rather than the Greek one, which is the whole difference between a gloss and a decoration.";
  let chapter = {
    chapter_code: "2JN01",
    reference: "2 John",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "elder,",
          "To",
          "the",
          "chosen",
          "lady",
          "$plus",
          "$pointing_back",
          "$child,",
          "whom",
          "I",
          "$heart_red",
          "$tray_in",
          "the",
          "$check,",
          "$plus",
          "$no_entry",
          "I",
          "alone,",
          "but",
          "$plus",
          "all",
          "who",
          "$lightbulb",
          "the",
          "$check,",
        ],
      },
      {
        verse_number: 2,
        words: [
          "because",
          "of",
          "the",
          "$check",
          "that",
          "abides",
          "$tray_in",
          "us",
          "$plus",
          "will",
          "be",
          "with",
          "us",
          "$hourglass:",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$gift,",
          "mercy,",
          "and",
          "peace",
          "from",
          "$fire",
          "the",
          "$father",
          "$plus",
          "from",
          "$cross",
          "$oil,",
          "the",
          "$son",
          "of",
          "the",
          "$father,",
          "will",
          "be",
          "with",
          "us",
          "$tray_in",
          "$check",
          "$plus",
          "$heart_red.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "$smile",
          "greatly",
          "$pointing",
          "I",
          "have",
          "found",
          "$tray_out",
          "your",
          "$child",
          "$walking",
          "$tray_in",
          "the",
          "$check,",
          "just",
          "as",
          "we",
          "$hand_receiving",
          "$scroll",
          "from",
          "the",
          "$father.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$plus",
          "now",
          "I",
          "urge",
          "you,",
          "lady,",
          "$no_entry",
          "as",
          "a",
          "new",
          "$scroll,",
          "but",
          "one",
          "we",
          "have",
          "had",
          "from",
          "the",
          "beginning:",
          "that",
          "we",
          "$heart_red",
          "$arrow_both_ways.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$plus",
          "this",
          "is",
          "$heart_red,",
          "that",
          "we",
          "$walking",
          "according",
          "to",
          "$pointing_back",
          "$scroll.",
          "This",
          "is",
          "the",
          "$scroll,",
          "just",
          "as",
          "you",
          "have",
          "$ear",
          "from",
          "the",
          "beginning,",
          "that",
          "you",
          "must",
          "$walking",
          "$tray_in",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$pointing",
          "many",
          "deceivers",
          "have",
          "gone",
          "out",
          "into",
          "the",
          "$globe,",
          "$no_entry",
          "confessing",
          "$cross",
          "$oil",
          "$footprints",
          "$tray_in",
          "$meat.",
          "Any",
          "such",
          "one",
          "is",
          "the",
          "deceiver",
          "$plus",
          "the",
          "antichrist.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$eyes",
          "yourselves,",
          "so",
          "that",
          "you",
          "do",
          "$no_entry",
          "lose",
          "what",
          "we",
          "have",
          "worked",
          "for,",
          "but",
          "that",
          "you",
          "may",
          "receive",
          "a",
          "full",
          "reward.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Anyone",
          "who",
          "runs",
          "ahead",
          "$plus",
          "does",
          "$no_entry",
          "remain",
          "$tray_in",
          "the",
          "teaching",
          "of",
          "$oil",
          "does",
          "$no_entry",
          "have",
          "$fire.",
          "Whoever",
          "remains",
          "$tray_in",
          "the",
          "teaching",
          "has",
          "$plus",
          "the",
          "$father",
          "$plus",
          "the",
          "$son.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "If",
          "anyone",
          "$footprints",
          "to",
          "you",
          "$plus",
          "does",
          "$no_entry",
          "bring",
          "this",
          "teaching,",
          "$no_entry",
          "$hand_receiving",
          "$pointing_back",
          "into",
          "your",
          "house,",
          "$plus",
          "$no_entry",
          "$speech",
          "$smile",
          "to",
          "$pointing_back.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Whoever",
          "$speech",
          "$smile",
          "to",
          "$pointing_back",
          "shares",
          "in",
          "$pointing_back",
          "$thumbs_down",
          "$tools.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "I",
          "have",
          "many",
          "things",
          "to",
          "write",
          "to",
          "you,",
          "but",
          "I",
          "would",
          "$no_entry",
          "use",
          "paper",
          "$plus",
          "ink.",
          "Instead",
          "I",
          "hope",
          "to",
          "come",
          "to",
          "you",
          "$plus",
          "$mouth",
          "face",
          "to",
          "face,",
          "so",
          "that",
          "our",
          "$smile",
          "may",
          "be",
          "complete.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "The",
          "$child",
          "of",
          "your",
          "elect",
          "sister",
          "send",
          "you",
          "greetings.",
        ],
      },
    ],
  };
  return chapter;
}
