export function bible_glyph_chapter_psa103() {
  "The hundred and third psalm, drawn in pictures. David telling his own soul to bless God, and then listing the reasons - forgiveness, healing, a father's pity, and a love measured against the distance from the sky to the ground and from the east to the west.";
  "THE BLESSING MARK IS THE FRAME OF THE WHOLE PSALM, AND IT NEVER APPEARS IN THE MIDDLE. Bless the LORD, O my soul opens it twice, and the last three verses say bless four more times, ending on the same sentence it began with. In between, from the third verse to the nineteenth, that mark does not occur once - the middle is all reasons, and the blessing is the box they sit in. A reader who cannot read a word can see the shape: a cluster of the same picture at the top, nothing for a long stretch, then the cluster again at the bottom. One of them is missing, and it is worth saying why. The blessing mark is a group picture built out of the speaking mark, and the twentieth verse also uses the speaking mark twice on its own, for His word and His command. A group standing next to its own parts cannot be read, so the group is put away there and the word bless is left in plain letters. Five of the six are drawn.";
  "THE FIRST VERSE SAYS THE WORD NAME, SO IT LOSES BOTH ITS TAGS. Bless the LORD, O my soul, and all that is within me, bless His holy name. The name tag is the picture for that name, and this line says the word outright, so both tags stand down and the psalm opens in plain letters where a reader would most expect them. What is left in that verse is the blessing group, the soul, and the mark for holy - which is the actual subject of the sentence anyway. The rule costs the opening line its two most obvious pictures, and the honest thing is to say so rather than to let a reader wonder why the most famous first line on the page is the barest.";
  "FOUR REFUSALS IN TWO VERSES, AND EVERY ONE IS SOMETHING GOD DOES NOT DO TO US. He will not always accuse us, not harbor His anger forever, not dealt with us according to our sins, not repaid us according to our iniquities. The ninth and tenth verses carry four negation marks between them, which is more than the whole rest of the psalm holds. Everywhere else on this list a run of negation marks is a threat or a refusal of something offered; here the same run is the good news, and it is the middle of the psalm. The reader who has learned that mark elsewhere meets it doing the opposite job, and the shape on the page is the argument: four things crossed out, and all four are punishments.";
  "ONE HEBREW WORD FOR LOVING DEVOTION CARRIES THE PSALM, AND IT FALLS FOUR TIMES. It is crowned on the head in the fourth verse, abounding in the eighth, measured against the height of the sky in the eleventh, and stretched from everlasting to everlasting in the seventeenth. English spells it loving devotion here and mercy elsewhere and kindness elsewhere again, so the four are not obviously one thing; the same mark four times makes them one thing. The seventeenth verse is also where the forever mark falls twice in a row, because Hebrew says from everlasting to everlasting by using the same word at both ends, and two identical marks side by side is exactly what that looks like.";
  "THE SON MARK IS ALSO THE WORD FOR A WHOLE PEOPLE. In the seventh verse the English reads the people of Israel, and the Hebrew reads the sons of Israel, so the son mark appears on a word that has nothing to do with anyone's child. Six verses later it is a father's children, and in the seventeenth it is children's children - two of the same mark in a row, which is how Hebrew says grandchildren. So the same picture covers a nation, a family, and a generation past the family. That is a wide job for one mark, and a reader who meets it on the word people first will be confused unless someone says this once.";
  "TO OBEY IS TO DO, AND THE DOING MARK IS WHAT PROVES IT. The eighteenth verse says remember His precepts to obey them, and the word under obey is the plain Hebrew verb for making or doing something. The same mark falls on executes righteousness in the sixth verse, on dealt with us in the tenth, on carry out His word in the twentieth, and on do His will in the twenty first. Five of them, and only one is translated as a word about obedience. The picture says what the Hebrew says: obeying is not a separate inner act that then produces behaviour - it is the doing itself, the same verb used of God executing justice and of angels carrying out orders.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA103",
    reference: "Psalm 103",
    verses: [
      {
        verse_number: 1,
        words: [
          "Of",
          "David.",
          "$speech+thumbs_up",
          "the",
          "LORD,",
          "O",
          "my",
          "$person_other;",
          "and",
          "all",
          "that",
          "is",
          "within",
          "me,",
          "bless",
          "His",
          "$sparkle",
          "name.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$speech+thumbs_up",
          "the",
          "$name_tag,",
          "O",
          "my",
          "$person_other,",
          "and",
          "do",
          "$no_entry",
          "forget",
          "all",
          "His",
          "kind",
          "deeds.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "He",
          "who",
          "forgives",
          "all",
          "your",
          "iniquities",
          "and",
          "heals",
          "all",
          "your",
          "diseases,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "who",
          "redeems",
          "your",
          "$sprout",
          "from",
          "the",
          "Pit,",
          "who",
          "crowns",
          "you",
          "with",
          "$gift",
          "and",
          "compassion,",
        ],
      },
      {
        verse_number: 5,
        words: [
          "who",
          "satisfies",
          "you",
          "with",
          "$thumbs_up",
          "things,",
          "so",
          "that",
          "your",
          "youth",
          "is",
          "renewed",
          "like",
          "the",
          "eagle's.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "$name_tag",
          "$hammer",
          "$ruler",
          "and",
          "$scales",
          "for",
          "all",
          "the",
          "oppressed.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "made",
          "$lightbulb",
          "His",
          "$road",
          "to",
          "Moses,",
          "His",
          "deeds",
          "to",
          "the",
          "$son",
          "of",
          "Israel.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$name_tag",
          "is",
          "compassionate",
          "and",
          "gracious,",
          "slow",
          "to",
          "anger,",
          "abounding",
          "in",
          "$gift.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "will",
          "$no_entry",
          "always",
          "accuse",
          "us,",
          "$no_entry",
          "harbor",
          "His",
          "anger",
          "$hourglass.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "has",
          "$no_entry",
          "$hammer",
          "with",
          "us",
          "according",
          "to",
          "our",
          "sins,",
          "and",
          "$no_entry",
          "repaid",
          "us",
          "according",
          "to",
          "our",
          "iniquities.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "as",
          "high",
          "as",
          "the",
          "$sky",
          "are",
          "above",
          "the",
          "$earth,",
          "so",
          "great",
          "is",
          "His",
          "$gift",
          "for",
          "those",
          "who",
          "fear",
          "Him.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "As",
          "far",
          "as",
          "the",
          "east",
          "is",
          "$tray_out",
          "the",
          "west,",
          "so",
          "far",
          "has",
          "He",
          "removed",
          "our",
          "transgressions",
          "from",
          "us.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "As",
          "a",
          "$father",
          "has",
          "compassion",
          "on",
          "his",
          "$son,",
          "so",
          "the",
          "$name_tag",
          "has",
          "compassion",
          "on",
          "those",
          "who",
          "fear",
          "Him.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "For",
          "He",
          "$lightbulb",
          "our",
          "frame;",
          "He",
          "is",
          "mindful",
          "that",
          "we",
          "are",
          "dust.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "As",
          "for",
          "man,",
          "his",
          "$sun",
          "are",
          "like",
          "grass",
          "-",
          "he",
          "blooms",
          "like",
          "a",
          "flower",
          "of",
          "the",
          "field;",
        ],
      },
      {
        verse_number: 16,
        words: [
          "when",
          "the",
          "$wind",
          "passes",
          "over,",
          "it",
          "vanishes,",
          "and",
          "its",
          "place",
          "remembers",
          "it",
          "$no_entry",
          "more.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "But",
          "from",
          "$hourglass",
          "to",
          "$hourglass",
          "the",
          "$gift",
          "of",
          "the",
          "$name_tag",
          "extends",
          "to",
          "those",
          "who",
          "fear",
          "Him,",
          "and",
          "His",
          "$ruler",
          "to",
          "their",
          "$son",
          "$son",
          "-",
        ],
      },
      {
        verse_number: 18,
        words: [
          "to",
          "those",
          "who",
          "keep",
          "His",
          "covenant",
          "and",
          "remember",
          "His",
          "precepts",
          "to",
          "$hammer",
          "them.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "The",
          "$name_tag",
          "has",
          "established",
          "His",
          "throne",
          "in",
          "$sky,",
          "and",
          "His",
          "kingdom",
          "rules",
          "over",
          "all.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Bless",
          "the",
          "$name_tag,",
          "all",
          "His",
          "$angel,",
          "mighty",
          "in",
          "$lightning,",
          "who",
          "$hammer",
          "His",
          "$speech,",
          "who",
          "$ear",
          "to",
          "the",
          "$voice",
          "of",
          "His",
          "$speech.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "$speech+thumbs_up",
          "the",
          "$name_tag,",
          "all",
          "His",
          "hosts,",
          "you",
          "servants",
          "who",
          "$hammer",
          "His",
          "will.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "$speech+thumbs_up",
          "the",
          "$name_tag,",
          "all",
          "His",
          "works",
          "in",
          "all",
          "places",
          "of",
          "His",
          "dominion.",
          "$speech+thumbs_up",
          "the",
          "$name_tag,",
          "O",
          "my",
          "$person_other.",
        ],
      },
    ],
  };
  return chapter;
}
