export function bible_glyph_chapter_pro02() {
  "Proverbs 2, drawn in pictures, so that a person who cannot read the letters can still follow it. A father tells his son that if he searches for wisdom like silver, he will understand the fear of the LORD, and it will keep him from the crooked man and the forbidden woman. Twenty two lines.";
  "THIS IS THE WISDOM CHAPTER AND THERE IS NO PICTURE FOR WISDOM. There is none for understanding either, or for knowledge, or insight, or discretion. Those five words are said thirteen times across twenty two lines, they are the whole subject of the page, and every one of the thirteen comes out as plain letters. A reader following only the marks sees a son, a road, a heart, a giving hand and a set of footprints, and never once sees the thing the father is telling him to go and find.";
  "AND TWO OF THE THREE EMPTY LINES ARE THE TWO MOST ABOUT IT. The fourth is seek it like silver and search it like hidden treasure, which is the most famous line here, and it has silver and treasure in it and a picture for neither, so it goes out completely bare. The eleventh is discretion will watch over you and understanding will guard you, which is the promise the whole chapter is built towards, and it is bare for the same reason. The third empty line is the fifteenth, the crooked paths.";
  "AND THE SAME FAULT SHOWS UP TWICE MORE HERE IN ITS CLEAREST FORM. There is an ear picture and there is a mouth picture, but the ear is seated on the Hebrew word for hearing and the mouth on the Hebrew word for speaking, so neither can go on the body part it is named after. The second line says incline your ear and the ear stays plain. The sixth says from His mouth come knowledge and the mouth stays plain. Then the twelfth line puts the mouth picture on the word speaks, six lines later, in the same chapter. A reader sees a mouth where the text says speaks and sees nothing where the text says mouth.";
  "THE BALANCE WORKS HERE, WHICH IS WORTH SAYING AFTER TWO CHAPTERS WHERE IT DID NOT. It is seated on the Hebrew word for judgment, and the eighth and ninth lines both put it where the English says justice, so it lands honestly twice. The last two chapters written here had to put it away three times between them because the English said share and manner instead.";
  "AND THE COVENANT IS BLANK AGAIN, IN THE SEVENTEENTH LINE, where the woman forgets the covenant of her God. That is the same hole a whole chapter of Genesis fell into, and it turns up here in a single line about a marriage.";
  "Forty five marks over twenty two lines. The nineteenth is the fullest at five, and three lines are empty.";
  "One mark stood down out of forty six. It was a bare preposition with nothing of its own to say.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PRO02",
    reference: "Proverbs 2",
    verses: [
      {
        verse_number: 1,
        words: [
          "My",
          "$son,",
          "if",
          "you",
          "$hand_receiving",
          "my",
          "words",
          "and",
          "hide",
          "my",
          "$scroll",
          "within",
          "you,",
        ],
      },
      {
        verse_number: 2,
        words: [
          "if",
          "you",
          "incline",
          "your",
          "ear",
          "to",
          "wisdom",
          "and",
          "direct",
          "your",
          "$heart_organ",
          "to",
          "understanding,",
        ],
      },
      {
        verse_number: 3,
        words: [
          "if",
          "you",
          "truly",
          "call",
          "out",
          "to",
          "insight",
          "and",
          "$hands_giving",
          "your",
          "$voice",
          "to",
          "understanding,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "if",
          "you",
          "seek",
          "it",
          "like",
          "silver",
          "and",
          "search",
          "it",
          "out",
          "like",
          "hidden",
          "treasure,",
        ],
      },
      {
        verse_number: 5,
        words: [
          "then",
          "you",
          "will",
          "discern",
          "the",
          "fear",
          "of",
          "the",
          "$name_tag",
          "and",
          "discover",
          "the",
          "knowledge",
          "of",
          "$fire.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "For",
          "the",
          "$name_tag",
          "$hands_giving",
          "wisdom.",
          "From",
          "His",
          "mouth",
          "come",
          "knowledge",
          "and",
          "understanding.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "stores",
          "up",
          "sound",
          "wisdom",
          "for",
          "the",
          "upright.",
          "He",
          "is",
          "a",
          "shield",
          "to",
          "those",
          "who",
          "$walking",
          "with",
          "integrity,",
        ],
      },
      {
        verse_number: 8,
        words: [
          "to",
          "guard",
          "the",
          "paths",
          "of",
          "$scales",
          "and",
          "protect",
          "the",
          "$road",
          "of",
          "His",
          "saints.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Then",
          "you",
          "will",
          "discern",
          "$ruler",
          "and",
          "$scales",
          "and",
          "equity,",
          "every",
          "$thumbs_up",
          "path.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "For",
          "wisdom",
          "will",
          "$footprints",
          "your",
          "$heart_organ,",
          "and",
          "knowledge",
          "will",
          "delight",
          "your",
          "$person_other.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Discretion",
          "will",
          "watch",
          "over",
          "you,",
          "and",
          "understanding",
          "will",
          "guard",
          "you,",
        ],
      },
      {
        verse_number: 12,
        words: [
          "to",
          "deliver",
          "you",
          "from",
          "the",
          "$road",
          "of",
          "$thumbs_down,",
          "from",
          "the",
          "$man_beard",
          "who",
          "$mouth",
          "perversity,",
        ],
      },
      {
        verse_number: 13,
        words: [
          "from",
          "those",
          "who",
          "leave",
          "the",
          "straight",
          "paths",
          "to",
          "$walking",
          "in",
          "the",
          "$road",
          "of",
          "$darkness,",
        ],
      },
      {
        verse_number: 14,
        words: [
          "from",
          "those",
          "who",
          "enjoy",
          "$hammer",
          "$thumbs_down",
          "and",
          "rejoice",
          "in",
          "the",
          "twistedness",
          "of",
          "$thumbs_down,",
        ],
      },
      {
        verse_number: 15,
        words: [
          "whose",
          "paths",
          "are",
          "crooked",
          "and",
          "whose",
          "ways",
          "are",
          "devious.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "It",
          "will",
          "rescue",
          "you",
          "from",
          "the",
          "forbidden",
          "$woman,",
          "from",
          "the",
          "stranger",
          "with",
          "seductive",
          "words,",
        ],
      },
      {
        verse_number: 17,
        words: [
          "who",
          "abandons",
          "the",
          "partner",
          "of",
          "her",
          "youth",
          "and",
          "forgets",
          "the",
          "covenant",
          "of",
          "her",
          "$fire.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "For",
          "her",
          "$house",
          "sinks",
          "down",
          "to",
          "$skull,",
          "and",
          "her",
          "tracks",
          "to",
          "the",
          "departed",
          "spirits.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "All",
          "who",
          "$footprints",
          "to",
          "her",
          "do",
          "$no_entry",
          "$turn_back,",
          "and",
          "do",
          "$no_entry",
          "reach",
          "the",
          "paths",
          "of",
          "$sprout.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "So",
          "you",
          "will",
          "$walking",
          "in",
          "the",
          "$road",
          "of",
          "the",
          "$thumbs_up",
          "and",
          "keep",
          "to",
          "the",
          "paths",
          "of",
          "the",
          "$ruler.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "For",
          "the",
          "upright",
          "will",
          "inhabit",
          "the",
          "$earth,",
          "and",
          "the",
          "blameless",
          "will",
          "remain",
          "in",
          "it,",
        ],
      },
      {
        verse_number: 22,
        words: [
          "but",
          "the",
          "$thumbs_down",
          "will",
          "be",
          "cut",
          "off",
          "from",
          "the",
          "$earth,",
          "and",
          "the",
          "unfaithful",
          "will",
          "be",
          "uprooted.",
        ],
      },
    ],
  };
  return chapter;
}
