export function bible_glyph_chapter_psa027() {
  "Psalm 27, drawn in pictures. David asking for one thing, and it is not rescue - it is to live in God's house and look at Him. The psalm turns halfway through, from a man who is sure of everything to a man begging not to be left, and then ends by telling itself to wait. Fourteen lines.";
  "THE LAST LINE ASKS FOR THREE THINGS AND THE PAGE CAN DRAW NONE OF THEM. Wait patiently for the LORD; be strong and courageous. Wait patiently for the LORD. Waiting has no picture in this Bible. Being strong has no picture. Being courageous has no picture - and the Hebrew there is literally take heart, which would have drawn beautifully, except the heart word is swallowed inside a larger chunk and cannot be reached. So the closing line of one of the best loved psalms reaches a reader with no English as two flashes of the name of God with a blank stretch between them. That blank is a shopping list: strength, courage, waiting.";
  "THE NAME OF GOD IS DRAWN THIRTEEN TIMES IN FOURTEEN LINES. That is nearly one a line, and no other picture here comes close. The fourth verse alone puts it down three times: one thing I have asked of the LORD, to dwell in the house of the LORD, to gaze on the beauty of the LORD. Read only the pictures and the psalm looks like a man saying one name over and over in different rooms - in a battle, in a temple, at a door, in a courtroom, on a road.";
  "THE NINTH VERSE PUTS DOWN FOUR REFUSALS IN ONE BREATH. Hide not Your face from me, nor turn away Your servant in anger; do not leave me or forsake me. Four small refusal marks in a single sentence, more than the whole rest of the psalm holds. It is also the exact point where the psalm changes its mind about itself: the first eight lines are a man who is not afraid of an army, and this one is the same man afraid of being left alone. The picture count is where you can see the seam.";
  "TWO HEARTS ARE DRAWN AND A THIRD ONE IS LOST. My heart will not fear, in the third verse. My heart said, Seek His face, in the eighth. Both are the beating organ, because the Hebrew means the thing inside the chest rather than the feeling. The third one, in the last line, is the take heart that could not be reached. So the psalm has a heart at the start, a heart in the middle, and a hole where the heart at the end should be.";
  "LIFE IS DRAWN AS A GROWING PLANT, THREE TIMES. The stronghold of my life. All the days of my life. The land of the living. One Hebrew root, three places, and this Bible seats it on a green shoot coming out of the ground. It is the quiet argument of the psalm: the man is surrounded by an army and a war and false witnesses, and the picture that keeps coming back for what he has is a plant growing.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA027",
    reference: "Psalm 27",
    verses: [
      {
        verse_number: 1,
        words: [
          "Of",
          "David.",
          "The",
          "$name_tag",
          "is",
          "my",
          "$light",
          "and",
          "my",
          "salvation",
          "-",
          "whom",
          "shall",
          "I",
          "fear?",
          "The",
          "$name_tag",
          "is",
          "the",
          "stronghold",
          "of",
          "my",
          "$sprout",
          "-",
          "whom",
          "shall",
          "I",
          "dread?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "When",
          "the",
          "wicked",
          "came",
          "upon",
          "me",
          "to",
          "devour",
          "my",
          "$meat,",
          "my",
          "enemies",
          "and",
          "foes",
          "stumbled",
          "and",
          "fell.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Though",
          "an",
          "army",
          "encamps",
          "around",
          "me,",
          "my",
          "$heart_organ",
          "will",
          "$no_entry",
          "fear;",
          "though",
          "a",
          "war",
          "breaks",
          "out",
          "against",
          "me,",
          "I",
          "will",
          "keep",
          "my",
          "trust.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "One",
          "thing",
          "I",
          "have",
          "asked",
          "of",
          "the",
          "$name_tag;",
          "this",
          "is",
          "what",
          "I",
          "desire:",
          "to",
          "dwell",
          "in",
          "the",
          "$house",
          "of",
          "the",
          "$name_tag",
          "all",
          "the",
          "$sun",
          "of",
          "my",
          "$sprout,",
          "to",
          "gaze",
          "on",
          "the",
          "beauty",
          "of",
          "the",
          "$name_tag",
          "and",
          "seek",
          "Him",
          "in",
          "His",
          "temple.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "For",
          "in",
          "the",
          "$sun",
          "of",
          "$thumbs_down",
          "He",
          "will",
          "hide",
          "me",
          "in",
          "His",
          "shelter;",
          "He",
          "will",
          "conceal",
          "me",
          "under",
          "the",
          "cover",
          "of",
          "His",
          "tent;",
          "He",
          "will",
          "set",
          "me",
          "high",
          "upon",
          "a",
          "rock.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Then",
          "my",
          "head",
          "will",
          "be",
          "held",
          "high",
          "above",
          "my",
          "enemies",
          "around",
          "me.",
          "At",
          "His",
          "tabernacle",
          "I",
          "will",
          "offer",
          "sacrifices",
          "with",
          "shouts",
          "of",
          "joy;",
          "I",
          "will",
          "sing",
          "and",
          "make",
          "music",
          "to",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$ear,",
          "O",
          "$name_tag,",
          "my",
          "$voice",
          "when",
          "I",
          "call;",
          "be",
          "merciful",
          "and",
          "answer",
          "me.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "My",
          "$heart_organ",
          "$speech,",
          "Seek",
          "His",
          "face.",
          "Your",
          "face,",
          "O",
          "$name_tag,",
          "I",
          "will",
          "seek.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Hide",
          "$no_entry",
          "Your",
          "face",
          "$tray_out",
          "me,",
          "$no_entry",
          "turn",
          "away",
          "Your",
          "$kneeling",
          "in",
          "anger.",
          "You",
          "have",
          "been",
          "my",
          "helper;",
          "do",
          "$no_entry",
          "leave",
          "me",
          "$no_entry",
          "forsake",
          "me,",
          "O",
          "$fire",
          "of",
          "my",
          "salvation.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Though",
          "my",
          "$father",
          "and",
          "mother",
          "forsake",
          "me,",
          "the",
          "$name_tag",
          "will",
          "receive",
          "me.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Teach",
          "me",
          "Your",
          "$road,",
          "O",
          "$name_tag,",
          "and",
          "lead",
          "me",
          "on",
          "a",
          "level",
          "path",
          "because",
          "of",
          "my",
          "oppressors.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Do",
          "$no_entry",
          "$hands_giving",
          "me",
          "over",
          "to",
          "the",
          "$person_other",
          "of",
          "my",
          "foes,",
          "for",
          "false",
          "$witness",
          "rise",
          "up",
          "against",
          "me,",
          "breathing",
          "out",
          "violence.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Still",
          "I",
          "am",
          "$anchor",
          "to",
          "$eye",
          "the",
          "goodness",
          "of",
          "the",
          "$name_tag",
          "in",
          "the",
          "$earth",
          "of",
          "the",
          "$sprout.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Wait",
          "patiently",
          "for",
          "the",
          "$name_tag;",
          "be",
          "strong",
          "and",
          "courageous.",
          "Wait",
          "patiently",
          "for",
          "the",
          "$name_tag!",
        ],
      },
    ],
  };
  return chapter;
}
