export function bible_glyph_chapter_lev15() {
  "The fifteenth chapter of Leviticus, drawn in pictures. Thirty three verses about what runs out of a body, and what has to be washed afterwards. It is the plainest chapter in the book, and the last two lines say what the whole thing was for.";
  "UNCLEAN IS SAID TWENTY NINE TIMES AND CLEAN IS SAID FIVE. The verb for becoming unclean is used twenty five times and the adjective four more, against four for the verb for becoming clean and one for the adjective. The noun for uncleanness is used seven times on top of that. The chapter is almost entirely one word.";
  "THE ANSWER IS THE SAME THREE THINGS EVERY TIME. Wash the clothes, bathe in water, wait until evening. The word for evening is used fifteen times and the word for water fifteen, the verb for bathing twelve, the verb for washing eleven, and the word for clothes eleven. No verse asks for anything harder than that.";
  "THE FOUR CASES ARE ARRANGED IN A MIRROR. A man with a long discharge, then a man with a short one, then a woman with a short one, then a woman with a long one. The two long cases end the same way and the two short cases end the same way. Nothing in the middle is treated as worse than anything at the edges.";
  "THE FURNITURE IS COUNTED IN FOURS OF SEVEN. The word for a bed is used seven times, the verb for sitting seven, the word for a vessel seven, and the noun for uncleanness seven. What the person touches is the real subject, and the verb for touching is used ten times.";
  "THE PRIEST IS NAMED SIX TIMES AND ONLY AT THE END OF THE TWO LONG CASES. He does not appear in the washing at all. When he does appear, at verses fourteen and fifteen for the man and verses twenty nine and thirty for the woman, the offering is the same words both times: two turtledoves or two young pigeons, one for sin and one to be burned.";
  "THE REASON IS IN VERSE THIRTY ONE AND IT IS NOT ABOUT DIRT. The line is so that they do not die by defiling the tabernacle that is among them. The word for tabernacle is used once in the chapter, right there. All the washing is because God chose to live in the middle of the camp rather than at a safe distance from it.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV15",
    reference: "Leviticus 15",
    verses: [
      {
        verse_number: 1,
        words: [
          "And",
          "$name_tag",
          "$mouth",
          "to",
          "Moses",
          "and",
          "Aaron,",
          "$speech:",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$mouth",
          "to",
          "the",
          "$son",
          "of",
          "Israel,",
          "$speech,",
          "When",
          "a",
          "$man_beard,",
          "any",
          "$man_beard,",
          "has",
          "a",
          "discharge",
          "from",
          "his",
          "$meat,",
          "the",
          "discharge",
          "is",
          "unclean.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "This",
          "uncleanness",
          "is",
          "from",
          "his",
          "discharge,",
          "whether",
          "his",
          "$meat",
          "allows",
          "the",
          "discharge",
          "to",
          "flow",
          "or",
          "his",
          "$meat",
          "blocks",
          "it.",
          "So",
          "his",
          "discharge",
          "will",
          "bring",
          "about",
          "uncleanness.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Any",
          "$bed",
          "on",
          "which",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "lies",
          "will",
          "be",
          "unclean,",
          "and",
          "any",
          "furniture",
          "on",
          "which",
          "he",
          "sits",
          "will",
          "be",
          "unclean.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Any",
          "$man_beard",
          "who",
          "touches",
          "his",
          "$bed",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Whoever",
          "sits",
          "on",
          "furniture",
          "on",
          "which",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "was",
          "sitting",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Whoever",
          "touches",
          "the",
          "$meat",
          "of",
          "the",
          "man",
          "with",
          "a",
          "discharge",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "If",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "spits",
          "on",
          "one",
          "who",
          "is",
          "clean,",
          "that",
          "person",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Any",
          "saddle",
          "on",
          "which",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "rides",
          "will",
          "be",
          "unclean.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Whoever",
          "touches",
          "anything",
          "that",
          "was",
          "under",
          "him",
          "will",
          "be",
          "unclean",
          "until",
          "evening,",
          "and",
          "whoever",
          "carries",
          "such",
          "things",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "If",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "touches",
          "anyone",
          "and",
          "has",
          "$no_entry",
          "first",
          "rinsed",
          "his",
          "$hand",
          "with",
          "$water,",
          "the",
          "one",
          "who",
          "was",
          "touched",
          "must",
          "wash",
          "his",
          "$garment",
          "and",
          "bathe",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Any",
          "clay",
          "pot",
          "that",
          "the",
          "man",
          "with",
          "the",
          "discharge",
          "touches",
          "must",
          "be",
          "broken,",
          "and",
          "any",
          "$tree",
          "utensil",
          "must",
          "be",
          "rinsed",
          "with",
          "$water.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "When",
          "the",
          "man",
          "has",
          "been",
          "cleansed",
          "from",
          "his",
          "discharge,",
          "he",
          "must",
          "count",
          "off",
          "seven",
          "$sun",
          "for",
          "his",
          "cleansing,",
          "wash",
          "his",
          "$garment,",
          "and",
          "bathe",
          "his",
          "$meat",
          "in",
          "$sprout",
          "$water,",
          "and",
          "he",
          "shall",
          "be",
          "clean.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "On",
          "the",
          "eighth",
          "$sun",
          "he",
          "is",
          "to",
          "$hand_receiving",
          "two",
          "turtledoves",
          "or",
          "two",
          "$son",
          "of",
          "the",
          "$dove,",
          "$footprints",
          "before",
          "$name_tag",
          "at",
          "the",
          "entrance",
          "to",
          "the",
          "$tent",
          "of",
          "Meeting,",
          "and",
          "$hands_giving",
          "them",
          "to",
          "the",
          "$priest.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "The",
          "$priest",
          "is",
          "to",
          "$hammer",
          "them,",
          "one",
          "as",
          "a",
          "$bow",
          "and",
          "the",
          "other",
          "as",
          "a",
          "$burnt_offering.",
          "In",
          "this",
          "way",
          "the",
          "$priest",
          "will",
          "make",
          "atonement",
          "for",
          "the",
          "man",
          "before",
          "$name_tag",
          "because",
          "of",
          "his",
          "discharge.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "When",
          "a",
          "$man_beard",
          "has",
          "an",
          "emission",
          "of",
          "$seed",
          "$tray_out",
          "of",
          "him,",
          "he",
          "must",
          "bathe",
          "his",
          "whole",
          "$meat",
          "with",
          "$water,",
          "and",
          "he",
          "will",
          "be",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Any",
          "$garment",
          "or",
          "leather",
          "on",
          "which",
          "there",
          "is",
          "an",
          "emission",
          "of",
          "$seed",
          "must",
          "be",
          "washed",
          "with",
          "$water,",
          "and",
          "it",
          "will",
          "remain",
          "unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "$woman",
          "lies with",
          "$man_beard",
          "and there is an emission",
          "$seed,",
          "both must bathe",
          "$water,",
          "and they will remain unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "$woman",
          "When",
          "has",
          "a discharge",
          "$blood",
          "consisting",
          "$meat,",
          "for seven",
          "$sun",
          "she will be",
          "unclean due to her menstruation,",
          "and anyone",
          "who touches",
          "her",
          "will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Anything",
          "which",
          "she lies",
          "on",
          "during her menstruation",
          "will be unclean,",
          "or sits.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "and anyone",
          "who touches",
          "$bed",
          "must wash",
          "$garment",
          "and bathe",
          "$water,",
          "and he will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Whoever",
          "touches",
          "any",
          "furniture",
          "which",
          "she was sitting",
          "on",
          "must wash",
          "$garment",
          "and bathe",
          "$water,",
          "and he will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "And whether",
          "$bed",
          "it is",
          "or",
          "on",
          "furniture",
          "which",
          "she",
          "was sitting,",
          "whoever touches",
          "it",
          "will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "If",
          "lies with",
          "her",
          "$man_beard",
          "touches",
          "and her menstrual flow",
          "him,",
          "he will be unclean",
          "for seven",
          "$sun,",
          "and any",
          "$bed",
          "which",
          "he lies",
          "on",
          "will become unclean.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "$woman",
          "When",
          "has a discharge",
          "$blood",
          "$sun",
          "for many",
          "$no_entry",
          "at a time",
          "her menstrual period,",
          "or",
          "if",
          "it continues",
          "beyond",
          "her period,",
          "all",
          "$sun",
          "discharge",
          "of her unclean,",
          "$sun",
          "of her menstruation",
          "will be",
          "unclean",
          "she.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "Any",
          "$bed",
          "which",
          "she lies",
          "on",
          "or any",
          "$sun",
          "of her discharge",
          "$bed",
          "furniture",
          "which",
          "she sits",
          "on",
          "unclean",
          "will be",
          "during her menstrual period.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "Anyone",
          "who touches",
          "these things",
          "will be unclean.",
          "he must wash",
          "$garment",
          "and bathe",
          "$water,",
          "and he will be unclean",
          "until",
          "evening.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "When",
          "a woman is cleansed",
          "of her discharge",
          "she must count off",
          "seven",
          "$sun,",
          "and after that",
          "she will be ceremonially clean.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "$sun",
          "On the eighth",
          "$hand_receiving",
          "two",
          "turtledoves",
          "or",
          "two",
          "$son",
          "$dove,",
          "$footprints",
          "them",
          "to",
          "$priest",
          "at",
          "the entrance",
          "$tent",
          "of Meeting.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "$hammer",
          "$priest",
          "one",
          "$bow",
          "and the other",
          "$burnt_offering,",
          "will make atonement",
          "for her",
          "$priest",
          "before",
          "$name_tag",
          "discharge",
          "for her unclean.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "You must keep",
          "$son",
          "of Israel separate",
          "from their uncleanness,",
          "$no_entry",
          "$skull",
          "by defiling",
          "My tabernacle",
          "which",
          "is among them.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "This",
          "$scroll",
          "of him who has a discharge,",
          "of the man who",
          "has",
          "$tray_out",
          "an emission",
          "$seed,",
          "he is unclean",
          "whereby,",
        ],
      },
      {
        verse_number: 33,
        words: [
          "of a woman",
          "in her menstrual period,",
          "who has a discharge",
          "of any male",
          "or female,",
          "$man_beard",
          "who",
          "lies",
          "with",
          "an unclean woman.",
        ],
      },
    ],
  };
  return chapter;
}
