export function bible_glyph_chapter_pro08() {
  "Proverbs 8, drawn in pictures, so that a person who cannot read the letters can still follow it. Wisdom stands in the street and speaks for the whole chapter in the first person, and near the end she says she was there before the world was made. Thirty six lines.";
  "THIRTY SIX LINES SPOKEN BY SOMEONE THE PAGE NEVER SHOWS. Every line here is her talking, and the word wisdom is said three times and the word wise once, and not one of the four gets a picture. There is no drawing for wisdom, and because the speaker is called Wisdom there is no drawing of a woman standing in a street either. The fifth line tells fools to gain understanding and comes out completely blank. So does the twelfth, which is the one line where she says her own name: I, wisdom, dwell together with prudence. Proverbs 1 gave her the last fourteen lines and that was already the strongest case in this collection for buying her a picture. This chapter gives her thirty six.";
  "THE SPRINGS OF THE DEEP COME OUT AS EYES. In the twenty eighth line the fountains of the deep gush open, and the mark that lands there is a pair of eyes, because the Hebrew word for a spring of water is the same word as the word for an eye. Nothing is broken; the page is drawing what the word says. But a reader following pictures through the creation passage meets sky, sea, water, mountain, ground, and then two eyes in the middle of it with no face anywhere near. This is the third word found here that locks a picture onto the wrong sense: the sea that also means west in Ezekiel 47, the name that also means the covenant name, and now the eye that is also a spring.";
  "THE WHOLE ARGUMENT IS A PRICE, AND NEITHER SIDE OF IT IS DRAWN. Take my instruction instead of silver, and knowledge rather than choice gold. My fruit is better than gold, than pure gold, and my harvest than choice silver. Gold three times, silver twice, rubies once, treasuries once: not one of them has a picture. What the reader gets of the tenth line is a hand taking something and a crossed circle, and of the nineteenth a thumbs up. The argument of this chapter is that one thing is worth more than another thing, and the page can show neither thing.";
  "SIX WORDS FOR SOMEONE IN CHARGE, AND THE ONLY RULER ON THE PAGE IS A MEASURING STICK. Kings, rulers, princes, nobles, and all who govern: two lines full of authority, and the marks that arrive are a king, a castle, and a straightedge which is there because the laws are just, not because anyone is ruling. A reader who has learnt that straightedge as the picture for what is right will see it in both lines and neither time is it about the man standing there. The seventh line has the same shape a different way, where my mouth will speak the truth draws a tick for the truth and leaves the mouth blank, because the mouth picture is spent on the act of speaking.";
  "THE LAST LINE DRAWS A BOW, AND IT IS EXACTLY RIGHT TO. He who fails to find me harms himself, and the mark on failing to find is an archer's bow, because the Hebrew word for sinning is the word for missing a shot. That is the picture explaining something the English cannot say without a footnote. It is worth putting beside all the losses above: the page is not weak everywhere, and where a root carries a picture inside it the reader gets more than the words gave them, not less.";
  "Two marks in her opening lines were dropped because the English does not carry them: a house at the crossroads, which is in the Hebrew phrase and not in the English word, and a hand at beside, which is the Hebrew way of saying next to. The third line then names gates, a city and entrances and comes out with nothing at all, although a city picture exists and is used on other pages here.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PRO08",
    reference: "Proverbs 8",
    verses: [
      {
        verse_number: 1,
        words: [
          "Does",
          "$no_entry",
          "wisdom",
          "call",
          "out,",
          "and",
          "understanding",
          "$hands_giving",
          "her",
          "$voice?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "On",
          "the",
          "heights",
          "overlooking",
          "the",
          "$road,",
          "at",
          "the",
          "crossroads",
          "she",
          "takes",
          "her",
          "stand.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Beside",
          "the",
          "gates",
          "to",
          "the",
          "city,",
          "at",
          "the",
          "entrances,",
          "she",
          "cries",
          "out:",
        ],
      },
      {
        verse_number: 4,
        words: [
          "To",
          "you,",
          "O",
          "$man_beard,",
          "I",
          "call",
          "out,",
          "and",
          "my",
          "$voice",
          "is",
          "to",
          "the",
          "$son",
          "of",
          "$person.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Learn",
          "to",
          "be",
          "shrewd,",
          "O",
          "simple",
          "ones;",
          "O",
          "fools,",
          "gain",
          "understanding.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "$ear,",
          "for",
          "I",
          "$mouth",
          "of",
          "noble",
          "things,",
          "and",
          "the",
          "opening",
          "of",
          "my",
          "lips",
          "will",
          "reveal",
          "right.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "For",
          "my",
          "mouth",
          "will",
          "speak",
          "the",
          "$check,",
          "and",
          "wickedness",
          "is",
          "detestable",
          "to",
          "my",
          "lips.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "All",
          "the",
          "words",
          "of",
          "my",
          "mouth",
          "are",
          "$ruler;",
          "none",
          "are",
          "crooked",
          "or",
          "perverse.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "They",
          "are",
          "all",
          "plain",
          "to",
          "the",
          "discerning,",
          "and",
          "upright",
          "to",
          "those",
          "who",
          "find",
          "knowledge.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$hand_receiving",
          "my",
          "instruction",
          "$no_entry",
          "silver,",
          "and",
          "knowledge",
          "rather",
          "than",
          "choice",
          "gold.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "wisdom",
          "is",
          "$thumbs_up",
          "than",
          "rubies,",
          "and",
          "nothing",
          "you",
          "desire",
          "compares",
          "with",
          "her.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "I,",
          "wisdom,",
          "dwell",
          "together",
          "with",
          "prudence,",
          "and",
          "I",
          "find",
          "knowledge",
          "and",
          "discretion.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "To",
          "fear",
          "the",
          "$name_tag",
          "is",
          "to",
          "hate",
          "$thumbs_down;",
          "I",
          "hate",
          "arrogant",
          "pride,",
          "$thumbs_down",
          "$road,",
          "and",
          "perverse",
          "speech.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "Counsel",
          "and",
          "sound",
          "judgment",
          "are",
          "mine;",
          "I",
          "have",
          "insight",
          "and",
          "strength.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "By",
          "me",
          "$king",
          "$castle,",
          "and",
          "rulers",
          "enact",
          "$ruler",
          "laws.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "By",
          "me",
          "princes",
          "rule,",
          "and",
          "all",
          "nobles",
          "who",
          "govern",
          "$ruler.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "I",
          "$heart_red",
          "those",
          "who",
          "$heart_red",
          "me,",
          "and",
          "those",
          "who",
          "seek",
          "me",
          "early",
          "shall",
          "find",
          "me.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "With",
          "me",
          "are",
          "riches",
          "and",
          "$star,",
          "enduring",
          "wealth",
          "and",
          "$ruler.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "My",
          "fruit",
          "is",
          "$thumbs_up",
          "than",
          "gold,",
          "than",
          "pure",
          "gold,",
          "and",
          "my",
          "harvest",
          "than",
          "choice",
          "silver.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "I",
          "$walking",
          "in",
          "the",
          "way",
          "of",
          "$ruler,",
          "along",
          "the",
          "paths",
          "of",
          "$scales,",
        ],
      },
      {
        verse_number: 21,
        words: [
          "bestowing",
          "wealth",
          "on",
          "those",
          "who",
          "$heart_red",
          "me",
          "and",
          "making",
          "their",
          "treasuries",
          "full.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "The",
          "$name_tag",
          "created",
          "me",
          "as",
          "His",
          "first",
          "$road,",
          "before",
          "His",
          "works",
          "of",
          "old.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "From",
          "$hourglass",
          "I",
          "was",
          "established,",
          "from",
          "the",
          "beginning,",
          "before",
          "the",
          "$earth",
          "began.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "When",
          "there",
          "were",
          "no",
          "watery",
          "depths,",
          "I",
          "was",
          "brought",
          "forth,",
          "when",
          "no",
          "springs",
          "were",
          "overflowing",
          "with",
          "$water.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Before",
          "the",
          "$mountain",
          "were",
          "settled,",
          "before",
          "the",
          "hills,",
          "I",
          "was",
          "brought",
          "forth,",
        ],
      },
      {
        verse_number: 26,
        words: [
          "before",
          "He",
          "$hammer",
          "the",
          "$earth",
          "or",
          "fields",
          "or",
          "any",
          "of",
          "the",
          "dust",
          "of",
          "the",
          "$globe.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "when",
          "He",
          "established",
          "the",
          "$sky,",
          "I",
          "was",
          "there,",
          "when",
          "He",
          "inscribed",
          "a",
          "circle",
          "on",
          "the",
          "face",
          "of",
          "the",
          "deep,",
        ],
      },
      {
        verse_number: 28,
        words: [
          "when",
          "He",
          "established",
          "the",
          "clouds",
          "above",
          "and",
          "gushed",
          "forth",
          "the",
          "$eyes",
          "of",
          "the",
          "deep,",
        ],
      },
      {
        verse_number: 29,
        words: [
          "when",
          "He",
          "set",
          "a",
          "boundary",
          "for",
          "the",
          "$sea",
          "so",
          "that",
          "the",
          "$water",
          "would",
          "$no_entry",
          "surpass",
          "His",
          "command,",
          "when",
          "He",
          "marked",
          "out",
          "the",
          "foundations",
          "of",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "Then",
          "I",
          "was",
          "a",
          "skilled",
          "craftsman",
          "at",
          "His",
          "side,",
          "and",
          "His",
          "delight",
          "$sun",
          "by",
          "$sun,",
          "rejoicing",
          "in",
          "His",
          "presence",
          "always,",
        ],
      },
      {
        verse_number: 31,
        words: [
          "rejoicing",
          "in",
          "His",
          "whole",
          "$globe",
          "and",
          "delighting",
          "in",
          "the",
          "$son",
          "of",
          "$person.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "Now",
          "therefore,",
          "my",
          "$son,",
          "$ear",
          "to",
          "me;",
          "$gift+smile",
          "are",
          "those",
          "who",
          "keep",
          "my",
          "$road.",
        ],
      },
      {
        verse_number: 33,
        words: [
          "$ear",
          "to",
          "instruction",
          "and",
          "be",
          "wise;",
          "do",
          "$no_entry",
          "ignore",
          "it.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "$gift+smile",
          "is",
          "the",
          "$person",
          "who",
          "$ear",
          "to",
          "me,",
          "watching",
          "$sun",
          "at",
          "my",
          "doors,",
          "waiting",
          "at",
          "the",
          "posts",
          "of",
          "my",
          "doorway.",
        ],
      },
      {
        verse_number: 35,
        words: [
          "For",
          "whoever",
          "finds",
          "me",
          "finds",
          "$sprout",
          "and",
          "obtains",
          "the",
          "favor",
          "of",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 36,
        words: [
          "But",
          "he",
          "who",
          "$bow",
          "harms",
          "$person_other;",
          "all",
          "who",
          "hate",
          "me",
          "$heart_red",
          "$skull.",
        ],
      },
    ],
  };
  return chapter;
}
