export function bible_glyph_chapter_psa121() {
  "Psalm 121, drawn in pictures. Eight short lines sung by people walking uphill to Jerusalem, and one of the best loved passages in the Old Testament. It is a psalm about being watched over on a road, which makes it one of the plainest things in this whole Bible for a reader who has no English at all.";
  "FIVE REFUSAL MARKS IN EIGHT LINES, AND EVERY SINGLE ONE OF THEM IS A PROMISE. He will not allow your foot to slip. Your Protector will not slumber. He will neither slumber nor sleep. The sun will not strike you by day. Everywhere else in this Bible the small refusal mark is a loss - no one to comfort her, no hand turned to help, no rest. Here it is the safest picture on the page, five times running. A reader who has met that mark in Lamentations and meets it again here learns something real about it: it does not mean bad news, it means the sentence is being closed off, and what gets closed off here is every way the walker could come to harm.";
  "THE WORD THE WHOLE PSALM IS BUILT ON IS SAID SIX TIMES AND CANNOT BE DRAWN ONCE. Protector, Protector, keeper, guard, preserve, watch over - six times from the third line to the last, and the Hebrew behind most of them is one word. There is no picture in this Bible for keeping somebody safe, so the psalm's own keyword is in plain letters on every line it appears. This is the same shape as the missing word for comfort in the first chapter of Lamentations: a passage whose single point cannot be shown, only spelled.";
  "THE ONE LINE ABOUT THE SUN CANNOT DRAW THE SUN. The sixth verse is, The sun will not strike you by day, nor the moon by night. This Bible has a sun picture and uses it constantly - but it is seated on the Hebrew word for a day, not on the burning thing in the sky, which is a different word with no seat. So the line goes out with one mark on it, the refusal, and both the sun and the moon stand there in letters. The sharper part is the moon: there is a moon picture drawn and ready in this Bible, and this line still cannot use it, because the Hebrew word for moon standing here has no seat. The artwork exists and the seat does not.";
  "THE NAME OF GOD IS DRAWN FIVE TIMES ON FOUR OF THE EIGHT LINES. The fifth verse names Him twice in one breath: the LORD is your keeper, the LORD is the shade on your right hand. Only two other pictures are drawn more than once here: the refusal, five times, and the coming mark, twice. Those two are worth watching, because the coming mark opens the psalm and closes it - From where does my help come, in the first line, and your coming and going, in the last. The page begins by asking where help arrives from and ends with the walker himself arriving.";
  "THE FIRST LINE IS ALMOST A COMPLETE PICTURE WITH NO WORDS LEFT OVER. I lift up my eyes to the hills. From where does my help come? Eyes, mountains, and a coming - three marks in one short question, and between them they carry nearly everything the line is doing. It is an unusual opening as well, because it asks a question instead of making a claim, and the answer arrives on the very next line.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA121",
    reference: "Psalm 121",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "song",
          "of",
          "ascents.",
          "I",
          "lift",
          "up",
          "my",
          "$eyes",
          "to",
          "the",
          "$mountain.",
          "From",
          "where",
          "does",
          "my",
          "help",
          "$footprints?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "My",
          "help",
          "comes",
          "from",
          "the",
          "$name_tag,",
          "the",
          "$hammer",
          "of",
          "$sky",
          "and",
          "$earth.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "He",
          "will",
          "$no_entry",
          "$hands_giving",
          "your",
          "foot",
          "to",
          "slip;",
          "your",
          "Protector",
          "will",
          "$no_entry",
          "slumber.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Behold,",
          "the",
          "Protector",
          "of",
          "Israel",
          "will",
          "$no_entry",
          "slumber",
          "$no_entry",
          "sleep.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$name_tag",
          "is",
          "your",
          "keeper;",
          "the",
          "$name_tag",
          "is",
          "the",
          "shade",
          "on",
          "your",
          "right",
          "$hand.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "sun",
          "will",
          "$no_entry",
          "strike",
          "you",
          "by",
          "day,",
          "nor",
          "the",
          "moon",
          "by",
          "night.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "The",
          "$name_tag",
          "will",
          "guard",
          "you",
          "from",
          "all",
          "$thumbs_down;",
          "He",
          "will",
          "preserve",
          "your",
          "$person_other.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "The",
          "$name_tag",
          "will",
          "watch",
          "over",
          "your",
          "$footprints",
          "and",
          "going,",
          "both",
          "now",
          "and",
          "forevermore.",
        ],
      },
    ],
  };
  return chapter;
}
