import { fn_name } from "./fn_name.mjs";
export function bible_glyph_artwork_absent() {
  "The glyphs the artwork set holds no drawing for at all, and what each one falls back to.";
  "A NAME THE SET DOES NOT ANSWER TO AND A PICTURE THE SET DOES NOT HAVE ARE OPPOSITE FACTS that both show up as one missing file. The first is a mistake in this repo and is corrected by spelling the name the set's way. The second is a fact about the set, and no spelling will fix it. Keeping the second here is what stops somebody spending an afternoon hunting for a name that was never going to be found.";
  "IT WAS NOT A PROBLEM FOR THE FIRST TWO AND IT IS THE WHOLE POINT OF THE LAST TWO, which is why they are listed together and told apart here rather than in two files. The first two have a character a font draws, so the drawn file was only ever a better version of something already complete, and a missing file changes nothing a reader sees. The last two have no character anywhere - no font on earth draws an altar or a priest - so for those the missing file IS the word, and the plain text prints the English instead.";
  "THAT IS THE LINE BETWEEN THE TWO TEXTS THIS BIBLE MAKES. The emoji text can be sent as a message and read in a terminal and can never say altar; the drawn text says everything and needs a page. A glyph in this list with an emoji character belongs to both texts and is merely undrawn; a glyph in this list whose character is an English word belongs to the drawn text alone. Nothing else in the repo has to know the difference, because the page already hides the character behind the picture and shows it only when the picture fails.";
  "AND THE LAST TWO ARE THE ONLY WORDS HERE WAITING ON SOMEBODY DRAWING RATHER THAN SOMEBODY SEARCHING. Both were measured, both are wanted, and neither can be composed out of what is already seated without claiming something false - an altar out of meat and fire says meat God, and a priest out of a person and oil says the Messiah. So they sit here fully seated and fully authored, drawing the English until a picture exists, which costs the emoji text nothing and lets the drawn text finish the moment one arrives.";
  "BOTH WERE ASKED A SECOND TIME, on a later day and through a listing fetched fresh, and the set held nothing carrying holding hands, nothing carrying family, and nothing carrying men at all. Asking twice is what tells a fact about the set apart from a listing that happened to be short the first time, and the second answer is what makes this list something to trust rather than something to re-check.";
  "THE FINDING WAS READ FROM THE SET rather than assumed from a failed fetch. The set's own list of names was searched for the words - family, holding hands - and holds nothing carrying either of them, which is a different and much stronger statement than one address not answering.";
  "THE REST CAME IN ONE BATCH, for the glyphs seated with an English word as their character, and they were read from the set the same way - every glyph's own word searched against one listing of the set's names. Each reason says what the search found: nothing at all, or a near picture turned down because it draws something else or is already spent on another glyph. They are waiting on somebody drawing, as the altar and the priest are, and the drawn text prints the English for them until then.";
  "TWENTY THREE ENTRIES WERE TAKEN OUT OF THIS LIST ON 2026-09-18 BECAUSE THEY WERE WRONG, and the shape of the mistake matters more than the count. Each one said the set holds no picture for a word - no chair, no tomb, no cup, no wall, no raven - and the set held every one of them, under the name a picture catalogue uses rather than the name scripture uses. The tomb is Headstone, the cup is Teacup without handle, the wall is Brick, the raven is Blackbird, the throne is Chair. One entry even said that searching for a chair returns wheelchairs, which was true, and the true plain Chair was in the same answer further down.";
  "SO READ THE PARAGRAPH ABOVE THIS ONE AGAINST WHAT ACTUALLY HAPPENED. It says the rest were read from the set the same careful way, every glyph's own word searched against one listing. That was done, and it was still wrong, because searching the set for the Bible's word asks whether two vocabularies happen to spell one thing the same - and they mostly do not. Ask the set for the shape a reader would see and pick from what comes back.";
  "AND THE READING THAT OUTLIVES THE FIX: A REFUSAL WRITTEN DOWN AS PROSE IS A MEASUREMENT WITH A DATE ON IT, NOT A FACT. Every because line in this list was true of some listing on some day. Prose is never re-run, so a wrong one sits here looking as settled as a right one for as long as nobody doubts it. Treat any sentence here saying the set holds nothing as a lead to check rather than a question already closed.";
  "THIRTY ONE ENTRIES LEFT THIS LIST ON 2026-10-08 - the altar and the priest among them - under a rule the human gave: the goal is emoji; so an imperfect picture that exists beats an English word; provided no picture stands for two unrelated words. Each took one whole picture and not a composition; which is what the objection above was to. The altar is Place of worship; the priest is Prayer beads; the burnt offering is Fireworks. What is left are the three whose character is already an emoji and only the drawing is missing.";
  ("THE LAST THREE LEFT ON 2026-10-09 - brother, sister and family - once the human said the emoji Bible and the picture Bible are separate products. The drawn text no longer has to wait for one picture of two people: it stands the set's own people side by side, in ",
    fn_name("bible_glyph_artwork_composed"),
    ". The list is empty and stays here for the next glyph the set truly cannot draw.");
  let absent = [];
  return absent;
}
