export function bible_glyph_chapter_isa64() {
  "Isaiah 64, drawn in pictures, so that a person who cannot read the letters can still follow it. A prayer asking God to tear the sky open and come down, and then admitting why He has not. Twelve lines.";
  "THE ONE PICTURE EVERYBODY REMEMBERS FROM THIS CHAPTER IS THE ONE THE PAGE CANNOT DRAW. The eighth line says we are the clay and You are the potter. There is no picture for clay and no picture for a potter, so both halves come out as plain letters in the middle of a line that has a name tag, a father and a hand in it. Worse than blank: the same line ends we are all the work of Your hand, and the hand does have a picture. So the reader following pictures gets a hand, and a hand is the one part of that sentence that was never the point.";
  "AND THE LINE THAT DENIES THREE SENSES AT ONCE COULD ONLY KEEP TWO OF THEM. The fourth line says no one has heard, no ear has perceived, no eye has seen any God besides You. It carries a crossing-out three times over, an ear, and a pair of eyes, and it is by a long way the fullest line in the chapter. But the draft put a single eye on has seen as well as a pair of eyes on the word eye, and one of those had to go. A single eye and a pair of eyes standing next to each other in the same line are two pictures a reader has no way to tell apart, and a reader who cannot tell them apart learns nothing from either. The pair stayed, on the word that names them.";
  "AND FIRE BURNS THE TEMPLE DOWN WITHOUT A FIRE ANYWHERE ON THE PAGE. The eleventh line says the holy and beautiful house where our fathers praised You has been burned with fire. The second line says fire kindles the brushwood. Neither fire is drawn, because in this collection the flame is the picture for God, and putting it on a fire that burns down His own temple would teach a reader the wrong thing twice in one line. So the chapter shows a flame in its fourth line, meaning God, and then seven lines later shows nothing at all where a building is going up in flames.";
  "AND ALMOST NOTHING THIS CHAPTER IS MADE OF CAN BE DRAWN. The sky opens, the mountains shake, water boils and a wind carries people off, and those four do have pictures. After that it stops. The brushwood, the leaf we wither like, the filthy rags, the clay, the potter, the wilderness, the wasteland, the desolation and the ruins are all plain letters. A reader following pictures gets a sky torn open at the top of the page and a burnt-out silence at the bottom, and has to take the middle on trust.";
  "WHAT THE PAGE DOES CARRY IS SOMEBODY ASKING AND ADMITTING. Thirty eight marks over twelve lines, which is thin, and the two commonest are a crossing-out at six and the name of the LORD at five. Only three lines carry that crossing-out, but one of them carries it three times over. That is the honest shape of this prayer: come down, and we know why You have not, and come down anyway.";
  "Three marks were dropped from forty one. One was the single eye standing beside the pair of eyes. One was an hourglass on the phrase if we remain in our sins, where the Hebrew carries a long time but this English does not. One sat on the words from us.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "ISA64",
    reference: "Isaiah 64",
    verses: [
      {
        verse_number: 1,
        words: [
          "Oh,",
          "that",
          "You",
          "would",
          "rend",
          "the",
          "$sky",
          "and",
          "come",
          "down,",
          "that",
          "the",
          "$mountain",
          "would",
          "quake",
          "at",
          "Your",
          "presence",
        ],
      },
      {
        verse_number: 2,
        words: [
          "as",
          "fire",
          "kindles",
          "the",
          "brushwood",
          "and",
          "causes",
          "the",
          "$water",
          "to",
          "boil,",
          "to",
          "make",
          "Your",
          "$name_tag",
          "$lightbulb",
          "to",
          "Your",
          "enemies,",
          "so",
          "that",
          "the",
          "$map",
          "will",
          "tremble",
          "at",
          "Your",
          "presence.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "When",
          "You",
          "$hammer",
          "awesome",
          "works",
          "that",
          "we",
          "did",
          "$no_entry",
          "expect,",
          "You",
          "came",
          "down,",
          "and",
          "the",
          "$mountain",
          "trembled",
          "at",
          "Your",
          "presence.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "From",
          "ancient",
          "$hourglass",
          "$no_entry",
          "one",
          "has",
          "$ear,",
          "$no_entry",
          "ear",
          "has",
          "perceived,",
          "$no_entry",
          "$eyes",
          "has",
          "seen",
          "any",
          "$fire",
          "besides",
          "You,",
          "who",
          "$hammer",
          "on",
          "behalf",
          "of",
          "those",
          "who",
          "wait",
          "for",
          "Him.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "welcome",
          "those",
          "who",
          "gladly",
          "$hammer",
          "$ruler,",
          "who",
          "remember",
          "Your",
          "$road.",
          "Surely",
          "You",
          "were",
          "angry,",
          "for",
          "we",
          "$bow.",
          "How",
          "can",
          "we",
          "be",
          "saved",
          "if",
          "we",
          "remain",
          "in",
          "our",
          "sins?",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Each",
          "of",
          "us",
          "has",
          "become",
          "like",
          "something",
          "unclean,",
          "and",
          "all",
          "our",
          "$ruler",
          "are",
          "like",
          "filthy",
          "rags.",
          "We",
          "all",
          "wither",
          "like",
          "a",
          "leaf,",
          "and",
          "our",
          "iniquities",
          "carry",
          "us",
          "away",
          "like",
          "the",
          "$wind.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "No",
          "one",
          "calls",
          "on",
          "Your",
          "$name_tag",
          "or",
          "strives",
          "to",
          "take",
          "hold",
          "of",
          "You.",
          "For",
          "You",
          "have",
          "hidden",
          "Your",
          "face",
          "from",
          "us",
          "and",
          "delivered",
          "us",
          "into",
          "the",
          "$hand",
          "of",
          "our",
          "iniquity.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "But",
          "now,",
          "O",
          "$name_tag,",
          "You",
          "are",
          "our",
          "$father.",
          "We",
          "are",
          "the",
          "clay,",
          "and",
          "You",
          "are",
          "the",
          "potter;",
          "we",
          "are",
          "all",
          "the",
          "work",
          "of",
          "Your",
          "$hand.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Do",
          "$no_entry",
          "be",
          "angry,",
          "O",
          "$name_tag,",
          "beyond",
          "measure;",
          "do",
          "$no_entry",
          "remember",
          "our",
          "iniquity",
          "forever.",
          "Oh,",
          "look",
          "upon",
          "us,",
          "we",
          "pray;",
          "we",
          "are",
          "all",
          "Your",
          "$family.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Your",
          "$sparkle",
          "$city",
          "have",
          "become",
          "a",
          "wilderness.",
          "Zion",
          "has",
          "become",
          "a",
          "wasteland,",
          "Jerusalem",
          "a",
          "desolation.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "Our",
          "$sparkle",
          "and",
          "beautiful",
          "$house,",
          "where",
          "our",
          "$father",
          "praised",
          "You,",
          "has",
          "been",
          "burned",
          "with",
          "fire,",
          "and",
          "all",
          "that",
          "was",
          "dear",
          "to",
          "us",
          "lies",
          "in",
          "ruins.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "After",
          "all",
          "this,",
          "O",
          "$name_tag,",
          "will",
          "You",
          "restrain",
          "Yourself?",
          "Will",
          "You",
          "keep",
          "silent",
          "and",
          "afflict",
          "us",
          "beyond",
          "measure?",
        ],
      },
    ],
  };
  return chapter;
}
