export function bible_glyph_chapter_psa099() {
  "The fifty sixth picture Bible chapter written by hand: the whole of the ninety ninth psalm, the LORD enthroned and holy, and the three men who called on Him, in the shorthand a person types.";
  "IT IS THE THIRD OF THE REIGNING PSALMS AND THE SHORTEST OF THE THREE. Nine verses, forty two in a hundred, against twelve in the ninety seventh and thirteen in the ninety sixth. All three are now on the list and they were written one after another on purpose: a reader who takes them in order meets the same castle mark opening the first, buried in the middle of the second, and opening the third again. Nothing else on the list repeats a shape that closely.";
  "THE HOLY MARK FALLS FOUR TIMES AND IT IS THE ONLY THING THIS PSALM SAYS TWICE. It closes the third verse, closes the fifth, and closes the ninth twice over - once on the mountain and once on God Himself. Three of the nine verses end on it. Hebrew poems mark their sections with a repeated line the way a song marks them with a chorus, and here the repeated line is one word, so the shape of the poem survives into a reading with no words in it at all.";
  "THE KING MARK IS HERE AND IT IS NOT THE CROWN MARK. The fourth verse has the mighty King who loves justice, and that is the word melek, which has its own picture. The ninety seventh psalm two pages back has the Lord of all the earth, and that is adon, which gets the crown. English writes both as a capital letter and a title. The two marks keep two Hebrew words apart that a reader would otherwise have no way of telling had ever been different.";
  "THE NAME MARK IS STOOD DOWN TWICE AND BOTH TIMES IT IS GODS OWN NAME. The third verse has them praise His great and awesome name, and the sixth says Samuel was among those who called on His name; at both the word is shem, seated on the same picture the table uses for the LORD. Drawing it there would have turned calling on the name into calling on the LORD, which is nearly the same sentence and is not the one written. This is the third page running to need that removal for God rather than for a person, and three in a row stops being a coincidence.";
  "THREE MEN ARE NAMED IN ONE VERSE AND NOT ONE OF THEM IS DRAWN. Moses, Aaron and Samuel stand in the sixth verse in plain letters, with Jacob in the fourth and Zion in the second. The list never draws a person or a place by name, because a picture of a man would say man and not Moses. So the sixth verse looks emptier than the ones around it, and that emptiness is accurate: it is the one verse whose content is who, not what.";
  "THE LAST VERSE IS THE FIFTH VERSE MOVED UP A MOUNTAIN. Both say exalt the LORD our God and worship, and the only thing that changes is where: at His footstool in the fifth, at His holy mountain in the ninth. The first half of the two lines is identical mark for mark - the name tag, the fire, the bowing - and then the fifth stops at a footstool while the ninth climbs a holy mountain and says the name tag and the fire over again. A reader following pictures sees the repeat and sees where it grows, which is exactly what the Hebrew is doing.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA099",
    reference: "Psalm 99",
    verses: [
      {
        verse_number: 1,
        words: [
          "The",
          "$name_tag",
          "$castle;",
          "let",
          "the",
          "$family",
          "tremble.",
          "He",
          "is",
          "enthroned",
          "above",
          "the",
          "cherubim;",
          "let",
          "the",
          "$earth",
          "quake.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Great",
          "is",
          "the",
          "$name_tag",
          "in",
          "Zion;",
          "He",
          "is",
          "exalted",
          "above",
          "all",
          "the",
          "$family.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Let",
          "them",
          "$hands_raised",
          "Your",
          "great",
          "and",
          "awesome",
          "name;",
          "$sparkle",
          "is",
          "He.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "The",
          "mighty",
          "$king",
          "$heart_red",
          "$scales.",
          "You",
          "have",
          "established",
          "equity;",
          "You",
          "have",
          "$hammer",
          "$scales",
          "and",
          "$ruler",
          "in",
          "Jacob.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Exalt",
          "the",
          "$name_tag",
          "our",
          "$fire",
          "and",
          "$bowing",
          "at",
          "His",
          "footstool;",
          "$sparkle",
          "is",
          "He.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Moses",
          "and",
          "Aaron",
          "were",
          "among",
          "His",
          "$priest,",
          "Samuel",
          "was",
          "among",
          "those",
          "who",
          "called",
          "on",
          "His",
          "name;",
          "they",
          "called",
          "to",
          "the",
          "$name_tag",
          "and",
          "He",
          "answered",
          "them.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "$mouth",
          "to",
          "them",
          "from",
          "the",
          "pillar",
          "of",
          "cloud;",
          "they",
          "kept",
          "His",
          "decrees",
          "and",
          "the",
          "statutes",
          "He",
          "$hands_giving",
          "them.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "O",
          "$name_tag",
          "our",
          "$fire,",
          "You",
          "answered",
          "them.",
          "You",
          "were",
          "a",
          "forgiving",
          "$fire",
          "to",
          "them,",
          "yet",
          "an",
          "avenger",
          "of",
          "their",
          "misdeeds.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "Exalt",
          "the",
          "$name_tag",
          "our",
          "$fire",
          "and",
          "$bowing",
          "at",
          "His",
          "$sparkle",
          "$mountain,",
          "for",
          "the",
          "$name_tag",
          "our",
          "$fire",
          "is",
          "$sparkle.",
        ],
      },
    ],
  };
  return chapter;
}
