export function bible_glyph_chapter_psa112() {
  "The fifty ninth picture Bible chapter written by hand: the whole of the hundred and twelfth psalm, the man who fears the LORD and what his life looks like, in the shorthand a person types.";
  "IT IS THE SECOND HALF OF A PAIR AND THE FIRST HALF IS ABOUT GOD. Ten verses, forty one in a hundred, thirty two of its seventy nine words drawn. The psalm written just before this one is built the same way and is about God. This one takes the same shape and points it at a person. The third verse here says his righteousness endures forever, and the third verse there says exactly that about God - the same four Hebrew words in the same order, which is not a resemblance but a quotation. Whatever a reader decides that means, only half of it is on this list so far: the hundred and eleventh psalm has not been drawn yet, so the quotation can be read here but not yet compared. Drawing that psalm would put the two third verses side by side in pictures, and it is the obvious next page after this one.";
  "ONE ENGLISH WORD BLESSED IS TWO HEBREW WORDS HERE AND THE MARKS SPLIT THEM APART. The first verse says blessed is the man who fears the LORD and the second says the generation of the upright will be blessed. English uses one word twice. The Hebrew uses two different ones, and the root table already has them on different pictures - the gift beside the smiling face in the first verse, the speech mark beside the thumbs up in the second. The first is a word for being fortunate, something true of the man. The second is a word for being spoken well of, something done to him by somebody else. A reader following pictures gets that distinction handed to him in two consecutive lines; a reader following the English has to be told.";
  "FOREVER IS SAID FOUR TIMES ON THIS PAGE AND ONLY TWO OF THEM ARE DRAWN. The sixth verse says it twice and both times the hourglass falls. The third verse and the ninth verse say it too and both times the word sits there in plain letters. That is not a choice made in this chapter. There are two Hebrew words for forever in these ten verses, and the root table seats one of them and has never seated the other. So the psalm looks less permanent in pictures than it is in words, and the two places where it looks flattest are the two where it is quoting the psalm about God. This is a gap in the table, and it is the same kind of gap as the one the short name of God leaves.";
  "THE MEASURING MARK FALLS FOUR TIMES AND IT IS THE SPINE OF THE PSALM. Twice it stands on the word for righteousness as a thing a man has, and twice on the word for a righteous man as a kind of person. Those are two different Hebrew words sharing one root, and the table gives them one picture, which is right - the difference between the deed and the doer is not a difference a picture should have to carry. Take those four out and the psalm has no argument left.";
  "THE SAME VERB IS TRANSLATED TWO DIFFERENT WAYS IN TWO VERSES RUNNING AND THE MARK SHOWS IT IS ONE WORD. In the eighth verse the man of God looks on his foes and it is rendered looks in triumph. In the tenth the wicked man looks and it is rendered will see. Same verb, same tense, one verse apart. English hid it by choosing two phrases; the eye mark falls in both places and puts them back side by side. That is the whole ending of the psalm: two men look at the same scene and it does opposite things to them.";
  "THE ONLY THING INSIDE THIS MAN THAT THE PSALM DESCRIBES IS HIS HEART. The heart mark falls twice, in the seventh verse and the eighth, and both times the sentence around it is about not being afraid. Everything else on the page is outward - what he lends, what he gives away, what he is remembered for, what happens to his household. The negation mark is on the page three times and two of the three are attached to fear. So the inward part of this life gets one picture and one subject, and the psalm spends the rest of its words on what other people can see.";
  "THE SHORT NAME OF GOD IS THE SECOND WORD OF THE PSALM AND IT IS NOT DRAWN. Hallelujah is two Hebrew words, praise and Yah, and Yah is the short form of the name that the name mark stands for. Four words later the full name arrives and gets the mark. So the same God is named twice in one verse and only the second naming is visible to a picture reader. The table seats the long name and has never seated the short one, which has now shown up as a hole on more than one page.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA112",
    reference: "Psalm 112",
    verses: [
      {
        verse_number: 1,
        words: [
          "Hallelujah!",
          "$gift+smile",
          "is",
          "the",
          "$man_beard",
          "who",
          "fears",
          "the",
          "$name_tag,",
          "who",
          "greatly",
          "delights",
          "in",
          "His",
          "$scroll.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "His",
          "descendants",
          "will",
          "be",
          "mighty",
          "in",
          "the",
          "$earth;",
          "the",
          "generation",
          "of",
          "the",
          "upright",
          "will",
          "be",
          "$speech+thumbs_up.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Wealth",
          "and",
          "riches",
          "are",
          "in",
          "his",
          "$house,",
          "and",
          "his",
          "$ruler",
          "endures",
          "forever.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$light",
          "dawns",
          "in",
          "the",
          "$darkness",
          "for",
          "the",
          "upright,",
          "for",
          "the",
          "gracious",
          "and",
          "compassionate",
          "and",
          "$ruler.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "It",
          "is",
          "$thumbs_up",
          "with",
          "the",
          "$man_beard",
          "who",
          "is",
          "generous",
          "and",
          "lends",
          "freely,",
          "who",
          "conducts",
          "his",
          "$speech",
          "with",
          "$scales.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Surely",
          "he",
          "will",
          "$no_entry",
          "be",
          "shaken",
          "$hourglass;",
          "the",
          "$ruler",
          "man",
          "will",
          "be",
          "remembered",
          "$hourglass.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "does",
          "$no_entry",
          "fear",
          "$thumbs_down",
          "news;",
          "his",
          "$heart_organ",
          "is",
          "steadfast,",
          "trusting",
          "in",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "His",
          "$heart_organ",
          "is",
          "assured;",
          "he",
          "does",
          "$no_entry",
          "fear,",
          "until",
          "he",
          "$eye",
          "in",
          "triumph",
          "on",
          "his",
          "foes.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "He",
          "has",
          "scattered",
          "abroad;",
          "he",
          "$hands_giving",
          "to",
          "the",
          "poor;",
          "his",
          "$ruler",
          "endures",
          "forever;",
          "his",
          "horn",
          "will",
          "be",
          "lifted",
          "high",
          "in",
          "$star.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "The",
          "$thumbs_down",
          "man",
          "will",
          "$eye",
          "and",
          "be",
          "grieved;",
          "he",
          "will",
          "gnash",
          "his",
          "teeth",
          "and",
          "waste",
          "away;",
          "the",
          "desires",
          "of",
          "the",
          "$thumbs_down",
          "will",
          "perish.",
        ],
      },
    ],
  };
  return chapter;
}
