export function bible_glyph_chapter_psa015() {
  "The fifty eighth picture Bible chapter written by hand: the whole of the fifteenth psalm, who may live on the holy mountain and what such a person does, in the shorthand a person types.";
  "IT IS THE SAME QUESTION AS THE PSALM WRITTEN BEFORE IT, ASKED FROM THE OTHER END. Five verses, forty two in a hundred. The hundred and first psalm is a king deciding who may live in his house. This one asks who may live in the house of God, and answers with the same kind of list. The two were written back to back on purpose, and a reader who takes them in that order sees one man's household rule first and then the rule it was copied from.";
  "IT IS NOW THE THICKEST PAGE ON THE WHOLE LIST FOR THE NEGATION MARK. Seven of them in five verses, which beats the first psalm at six in six and the eighteenth of Ezekiel at thirty one in thirty two. That is not a poetic effect; it is what the answer is made of. Six of the eleven things said about the person who may stay are things he does not do, and the mark carries all six without a word of grammar attached.";
  "THE GIVING HAND AND THE TAKING HAND ARE BOTH REFUSED IN ONE VERSE. The fifth verse says he does not lend his money at interest and does not take a bribe, and those are two different marks - the hand held out and the hand held open. Both stand under the negation. Money moving either direction can buy a person, and the psalm blocks both directions with the same word and two different pictures, which is a thing English needs a whole clause to do.";
  "THE ANSWER IS ALL VERBS AND THE MARKS MAKE THAT OBVIOUS. Walks, practices, speaks, does, despises, honours, lends, takes, and at the end is not shaken. Not one line asks what the man thinks or feels or believes. The only inward word on the page is the heart in the second verse, and even that is where truth is spoken from rather than something held there. A reader who follows only pictures gets a list of actions, which is exactly what the Hebrew gives a reader who follows only words.";
  "THE LAST LINE IS THE ONLY PROMISE HERE AND IT USES THE FOREVER MARK. Everything before it is a condition. Then the page turns once, at the end, and says the one who does these things will never be shaken - the negation and the hourglass side by side, so never arrives as two pictures instead of as a word. The hundred and forty sixth psalm ends on the same hourglass with the castle beside it, promising the same permanence about God that this one promises about a man who keeps his word. The two endings share a picture and are talking about opposite kinds of subject, and only the marks put that side by side.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA015",
    reference: "Psalm 15",
    verses: [
      {
        verse_number: 1,
        words: [
          "O",
          "$name_tag,",
          "who",
          "may",
          "abide",
          "in",
          "Your",
          "tent?",
          "Who",
          "may",
          "dwell",
          "on",
          "Your",
          "$sparkle",
          "$mountain?",
        ],
      },
      {
        verse_number: 2,
        words: [
          "He",
          "who",
          "$walking",
          "with",
          "integrity",
          "and",
          "practices",
          "$ruler,",
          "who",
          "$mouth",
          "the",
          "$check",
          "from",
          "his",
          "$heart_organ,",
        ],
      },
      {
        verse_number: 3,
        words: [
          "who",
          "has",
          "$no_entry",
          "slander",
          "on",
          "his",
          "tongue,",
          "who",
          "$no_entry",
          "$hammer",
          "$thumbs_down",
          "to",
          "his",
          "neighbor,",
          "who",
          "casts",
          "$no_entry",
          "scorn",
          "on",
          "his",
          "friend,",
        ],
      },
      {
        verse_number: 4,
        words: [
          "who",
          "despises",
          "the",
          "vile",
          "in",
          "his",
          "$eyes",
          "but",
          "honors",
          "those",
          "who",
          "fear",
          "the",
          "$name_tag,",
          "who",
          "does",
          "$no_entry",
          "revise",
          "a",
          "costly",
          "oath,",
        ],
      },
      {
        verse_number: 5,
        words: [
          "who",
          "does",
          "$no_entry",
          "$hands_giving",
          "his",
          "money",
          "at",
          "interest,",
          "and",
          "does",
          "$no_entry",
          "$hand_receiving",
          "a",
          "bribe",
          "against",
          "the",
          "innocent.",
          "He",
          "who",
          "$hammer",
          "these",
          "things",
          "will",
          "$no_entry",
          "be",
          "shaken",
          "$hourglass.",
        ],
      },
    ],
  };
  return chapter;
}
