export function bible_glyph_chapter_lev09() {
  "The ninth chapter of Leviticus, drawn in pictures. On the eighth day Aaron offers for the first time, and this time he does it himself. Everything in the chapter is aimed at the last verse, where fire comes out and the people fall on their faces.";
  "ONE HEBREW WORD CARRIES THE WHOLE CHAPTER FROM END TO END. At verse four it is a promise, today the LORD will appear to you. At verse six it is the reason, so that the glory of the LORD may appear. At verse twenty three it happens, and the glory of the LORD appeared. At verse twenty four the people see it. Four uses of the same root, and everything else in the chapter sits between them.";
  "THE LAST OF THE FOUR IS A DIFFERENT KIND OF SEEING. The first three are the passive form, the thing showing itself. The fourth is the plain active form, and the ones doing it are the people. The chapter ends by handing the seeing over to them.";
  "GLORY IS SAID TWICE AND THE TWO ARE THE PROMISE AND THE KEEPING OF IT. Verse six and verse twenty three, with seventeen verses of butchery in between and no mention of it anywhere in them.";
  "THIS TIME AARON DOES IT HIMSELF. In chapter eight every verb belonged to Moses. Here Aaron approaches, slaughters, dips, applies, pours out, burns, presents, waves and blesses. Aaron is named ten times and Moses seven, and the reversal is the point of the chapter.";
  "THERE ARE TWO FIRES AND ONLY ONE OF THEM IS GOD. The word for fire is used twice. At verse eleven it is the ordinary fire outside the camp that burns up the hide and the flesh. At verse twenty four it comes out from the presence of the LORD.";
  "BLESSING HAPPENS TWICE, ONCE ALONE AND ONCE TOGETHER. At verse twenty two Aaron lifts his hands and blesses, and the verb is singular. At verse twenty three the verb turns plural and Moses and Aaron come out of the tent and bless together.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV09",
    reference: "Leviticus 9",
    verses: [
      {
        verse_number: 1,
        words: [
          "On",
          "the",
          "eighth",
          "$sun",
          "Moses",
          "summoned",
          "Aaron",
          "and",
          "$son",
          "and",
          "the",
          "elders",
          "of",
          "Israel.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$speech",
          "to",
          "Aaron,",
          "$hand_receiving",
          "for",
          "yourself",
          "$calf,",
          "$son",
          "of",
          "the",
          "herd,",
          "$bow,",
          "and",
          "$ram",
          "$burnt_offering,",
          "both",
          "without",
          "blemish,",
          "and",
          "present",
          "them",
          "before",
          "$name_tag.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Then",
          "$mouth",
          "to",
          "$son",
          "of",
          "Israel",
          "$speech",
          "$hand_receiving",
          "a",
          "male",
          "$goat",
          "$bow,",
          "and",
          "$calf",
          "and",
          "$lamb,",
          "both",
          "$son",
          "of",
          "a",
          "year",
          "and",
          "without",
          "blemish,",
          "$burnt_offering.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Also",
          "$ox",
          "and",
          "$ram",
          "to",
          "sacrifice",
          "for",
          "a",
          "peace",
          "offering",
          "before",
          "$name_tag,",
          "and",
          "$grain_offering",
          "mixed",
          "with",
          "oil.",
          "For",
          "$sun",
          "$name_tag",
          "$eye",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "So",
          "they",
          "$hand_receiving",
          "what",
          "Moses",
          "had",
          "commanded",
          "to",
          "the",
          "front",
          "$tent",
          "of",
          "Meeting,",
          "and",
          "the",
          "whole",
          "congregation",
          "drew",
          "near",
          "and",
          "stood",
          "before",
          "$name_tag.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "And",
          "Moses",
          "$speech,",
          "$speech",
          "This",
          "is",
          "what",
          "$name_tag",
          "has",
          "commanded",
          "you",
          "$hammer,",
          "so",
          "that",
          "$star",
          "$name_tag",
          "$eye",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Then",
          "Moses",
          "$speech",
          "to",
          "Aaron,",
          "Approach",
          "$altar",
          "$hammer",
          "$bow",
          "and",
          "$burnt_offering",
          "to",
          "make",
          "atonement",
          "for",
          "yourself",
          "and",
          "for",
          "$family.",
          "$hammer",
          "the",
          "offering",
          "of",
          "$family",
          "to",
          "make",
          "atonement",
          "for",
          "them,",
          "as",
          "$name_tag",
          "has",
          "commanded.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "So",
          "Aaron",
          "approached",
          "$altar",
          "and",
          "slaughtered",
          "$calf",
          "$bow",
          "for",
          "himself.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$son",
          "of",
          "Aaron",
          "brought",
          "$blood",
          "to",
          "him,",
          "and",
          "he",
          "dipped",
          "his",
          "finger",
          "$blood",
          "and",
          "$hands_giving",
          "it",
          "to",
          "$horn",
          "$altar.",
          "And",
          "$blood",
          "he",
          "poured",
          "out",
          "at",
          "the",
          "base",
          "of",
          "$altar.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "$altar",
          "he",
          "burned",
          "the",
          "fat,",
          "the",
          "kidneys",
          "and",
          "the",
          "lobe",
          "$tray_out",
          "the",
          "liver",
          "$tray_out",
          "$bow,",
          "as",
          "$name_tag",
          "had",
          "commanded",
          "Moses.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "But",
          "$meat",
          "and",
          "the",
          "hide",
          "he",
          "burned",
          "up",
          "outside",
          "$camp.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Then",
          "he",
          "slaughtered",
          "$burnt_offering.",
          "$son",
          "brought",
          "him",
          "$blood,",
          "and",
          "he",
          "splattered",
          "it",
          "on",
          "all",
          "sides",
          "of",
          "$altar.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "They",
          "brought",
          "him",
          "$burnt_offering",
          "piece",
          "by",
          "piece,",
          "including",
          "the",
          "head,",
          "and",
          "he",
          "burned",
          "them",
          "on",
          "$altar.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "He",
          "washed",
          "the",
          "entrails",
          "and",
          "the",
          "legs",
          "and",
          "burned",
          "them",
          "atop",
          "$burnt_offering",
          "$altar.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Aaron",
          "then",
          "presented",
          "the",
          "offering",
          "of",
          "$family.",
          "$hand_receiving",
          "the",
          "male",
          "goat",
          "$bow",
          "of",
          "$family,",
          "slaughtered",
          "it",
          "and",
          "$bow",
          "like",
          "the",
          "first",
          "one.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "He",
          "presented",
          "$burnt_offering",
          "and",
          "$hammer",
          "$scales.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Next",
          "he",
          "presented",
          "$grain_offering,",
          "took",
          "a",
          "handful",
          "$tray_out,",
          "and",
          "burned",
          "it",
          "on",
          "$altar",
          "in",
          "addition",
          "to",
          "$morning",
          "$burnt_offering.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Then",
          "he",
          "slaughtered",
          "$ox",
          "and",
          "$ram",
          "as",
          "$sacrifice",
          "of",
          "the",
          "peace",
          "offering",
          "of",
          "$family.",
          "$son",
          "brought",
          "him",
          "$blood,",
          "and",
          "he",
          "splattered",
          "it",
          "on",
          "all",
          "sides",
          "of",
          "$altar.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "They",
          "also",
          "brought",
          "the",
          "fat",
          "portions",
          "$tray_out",
          "$ox",
          "and",
          "$tray_out",
          "$ram,",
          "the",
          "fat",
          "tail,",
          "the",
          "fat",
          "covering",
          "the",
          "entrails,",
          "the",
          "kidneys",
          "and",
          "the",
          "lobe",
          "of",
          "the",
          "liver.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "and",
          "placed",
          "these",
          "on",
          "the",
          "breasts,",
          "and",
          "Aaron",
          "burned",
          "the",
          "fat",
          "portions",
          "$altar.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "But",
          "the",
          "breasts",
          "and",
          "the",
          "right",
          "thigh",
          "he",
          "waved",
          "as",
          "a",
          "wave",
          "offering",
          "before",
          "$name_tag,",
          "as",
          "Moses",
          "had",
          "commanded.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "Aaron",
          "lifted",
          "up",
          "$hand",
          "toward",
          "$family",
          "$speech+thumbs_up.",
          "And",
          "having",
          "$hammer",
          "$bow,",
          "$burnt_offering",
          "and",
          "the",
          "peace",
          "offering,",
          "he",
          "stepped",
          "down.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Moses",
          "and",
          "Aaron",
          "$footprints",
          "$tent",
          "of",
          "Meeting.",
          "When",
          "they",
          "came",
          "out,",
          "$speech+thumbs_up",
          "$family,",
          "and",
          "$star",
          "$name_tag",
          "$eye",
          "to",
          "all",
          "$family.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "Fire",
          "came",
          "out",
          "from",
          "the",
          "presence",
          "$name_tag",
          "and",
          "consumed",
          "$burnt_offering",
          "and",
          "the",
          "fat",
          "portions",
          "on",
          "$altar.",
          "And",
          "when",
          "all",
          "$family",
          "$eye,",
          "they",
          "shouted",
          "for",
          "joy",
          "and",
          "fell",
          "facedown.",
        ],
      },
    ],
  };
  return chapter;
}
