export function bible_glyph_chapter_psa110() {
  "The hundred and tenth psalm, drawn in pictures. Seven verses in which God speaks to someone the writer calls his own master, seats him at the right hand, and swears he is a priest forever.";
  "THE FIRST VERSE HAS TWO DIFFERENT WORDS FOR LORD AND ENGLISH TELLS THEM APART ONLY BY THE SIZE OF ITS LETTERS. The LORD said to my Lord. In Hebrew the first is the name, and the second is adon, an ordinary word for a master or an owner. English distinguishes them by printing one in small capitals and the other in lower case, which disappears the moment anyone reads the verse out loud, and which means nothing at all to a reader who has never been told the convention. The root table gives them two completely different pictures: the name tag and the crown. So on this page the first sentence is one mark speaking to another mark, and a reader who cannot read a word of English can see there are two people in it. That distinction is the entire point of the verse and of every argument the New Testament builds on it.";
  "THE CROWN COMES BACK IN THE FIFTH VERSE AND THIS TIME IT IS THE ONE DOING THE CRUSHING. In the first verse the crown is sitting down and being spoken to. Four verses later the same mark is at the right hand and crushing kings in the day of His wrath - and the word for those kings is a different Hebrew word with a different picture, so the verse holds a crown and a king side by side without confusing them. The psalm begins with the crowned one seated and ends with him standing over the ones who wear the other mark. Nothing in the English shows that the two Lords of verse one and verse five are the same word while the kings of verse five are not.";
  "A PRIEST FOREVER IS THREE MARKS AND A WHOLE NEW TESTAMENT LETTER HANGS ON THEM. The fourth verse is the LORD has sworn and will not change His mind, you are a priest forever. The negation, the priest and the hourglass all land in that one verse, and they are the three things the letter to the Hebrews spends seven chapters on: the oath that is not taken back, the priesthood, and the fact that it does not end. A reader following pictures gets the argument in the order the argument is actually made, without a single term of theology being introduced.";
  "THE RIGHT HAND IS THE PART EVERYONE QUOTES AND IT HAS NO PICTURE AT ALL. Sit at My right hand is the most quoted half sentence in this psalm, and it stands here in plain letters both times it occurs, in the first verse and the fifth. The root table draws a hand, and it draws a hand giving and a hand receiving, but it has nothing for the right hand as a place - which is what the phrase is, a seat rather than a limb. So the picture Bible can show a reader that there are two Lords in the first verse and cannot show where the second one is sitting. That is worth saying plainly rather than papering over: the marks carry the argument and stop short of the image the argument is set in.";
  "THE PSALM SPENDS ALMOST ALL ITS MARKS IN THE FIRST FIVE VERSES AND ENDS NEARLY BARE. Thirteen of the fifteen marks on this page fall in verses one to five. The last two verses judge the nations, heap up the dead, crush the leaders of a wide country, drink from a brook and lift up a head, and out of all of that the table draws two things: the nations and the road. The ending is the part a reader has to take on the words alone. Where a page thins out like that it is the table that is thin, not the psalm, and a reader can see exactly where the help stops.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA110",
    reference: "Psalm 110",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "Psalm",
          "of",
          "David.",
          "The",
          "$name_tag",
          "said",
          "to",
          "my",
          "$crown:",
          "Sit",
          "at",
          "My",
          "right",
          "hand",
          "until",
          "I",
          "make",
          "Your",
          "enemies",
          "a",
          "footstool",
          "for",
          "Your",
          "feet.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "The",
          "$name_tag",
          "extends",
          "Your",
          "mighty",
          "scepter",
          "from",
          "Zion:",
          "Rule",
          "in",
          "the",
          "midst",
          "of",
          "Your",
          "enemies.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Your",
          "$family",
          "shall",
          "be",
          "willing",
          "on",
          "Your",
          "$sun",
          "of",
          "battle.",
          "Arrayed",
          "in",
          "$sparkle",
          "splendor,",
          "from",
          "the",
          "womb",
          "of",
          "the",
          "dawn,",
          "to",
          "You",
          "belongs",
          "the",
          "dew",
          "of",
          "Your",
          "youth.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "The",
          "$name_tag",
          "has",
          "sworn",
          "and",
          "will",
          "$no_entry",
          "change",
          "His",
          "mind:",
          "You",
          "are",
          "a",
          "$priest",
          "$hourglass",
          "in",
          "the",
          "order",
          "of",
          "Melchizedek.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$crown",
          "is",
          "at",
          "Your",
          "right",
          "hand;",
          "He",
          "will",
          "crush",
          "$king",
          "in",
          "the",
          "$sun",
          "of",
          "His",
          "wrath.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "will",
          "judge",
          "the",
          "$map,",
          "heaping",
          "up",
          "the",
          "dead;",
          "He",
          "will",
          "crush",
          "the",
          "leaders",
          "far",
          "and",
          "wide.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "will",
          "drink",
          "from",
          "the",
          "brook",
          "by",
          "the",
          "$road;",
          "therefore",
          "He",
          "will",
          "lift",
          "up",
          "His",
          "head.",
        ],
      },
    ],
  };
  return chapter;
}
