export function bible_glyph_undrawn_wanted() {
  "The words this picture Bible wants a picture for and still has none seated under, each with the fact that is blocking it.";
  "THIS IS THE THIRD OF THREE LISTS AND IT IS THE ONLY ONE THAT RECORDS WORK RATHER THAN A DECISION. One sibling holds the words drawn as nothing because a reader loses nothing. The other holds the words no single mark can carry because the sentence and not the word decides what they are doing. Both of those are answers. This list is the question, written down, so that a word nobody has chosen a picture for stops being indistinguishable from a word somebody decided against.";
  "IT HAS BEEN THROUGH TWO PASSES AND BOTH TIMES MOST OF THE LIST LEFT IT, WHICH IS THE POINT OF IT. Thirty three words were measured first and twenty nine of them came back clean and are seated now. Eighty five more were measured after that and fifty eight of those were seated too. Seventy five more went through a third time and twenty three of those were seated, after four came back out for wearing a picture that already meant something else and ten more came back out for sharing a picture with a sibling word. Every one went the same way - counted as plain English standing in a drawn verse, then looked up in the interlinear to see what Hebrew number it answers to and what share of that number it covers. What stays in this list is what the count refused, and nothing else.";
  "THE READING THAT DECIDED EACH ONE IS NOT A JUDGMENT ABOUT THE WORD, it is a count of what the interlinear says the Hebrew number means everywhere it stands. A single wording covering nearly every place is what makes a seat honest. A number split between two unrelated wordings has two meanings under one key, and a picture on it draws one of them and lies about the other. That is why the covenant was taken at two hundred and sixty four places out of two hundred and eighty three, and why the bone was refused at ninety out of a hundred and fifteen even though ninety is the larger want.";
  "EVERY REFUSAL HERE IS A SPLIT AND NOT AN ABSENCE, which makes these harder than the words that were never looked at. The word is wanted, the Hebrew is known, and the count is in hand. What blocks each one is that the number carries a second meaning the picture would say something false about. Nobody can fix that by drawing better. It is fixed by deciding whether the two meanings should be told apart, which is a decision about the text and not about the artwork.";
  "THE PROVISIONAL PICTURE IS THE ENGLISH WORD AND IT IS DELIBERATELY NOT A SEQUENCE OF MARKS ALREADY SEATED. This was tried and written down before, for the altar and for the priest, and the reason it failed is that a composite does not read as provisional. An altar built out of meat and fire says meat God. A priest built out of a person and oil says the Messiah. A reader has no way to see that a sequence is a placeholder, so the sequence is simply read, and read as a claim the text never made. The English word claims nothing it should not, prints in both the emoji text and the drawn text, and is how the altar and the priest already ship, so nothing new had to be built for the twenty nine to become provisional.";
  "THE QUEUE BEHIND THIS LIST WAS A GUESS UNTIL THE THIRD PASS COUNTED EVERY WORD. The first two passes worked from a hand written list of a hundred and forty two English words somebody had noticed. The third pass counted instead - every plain English word standing in every drawn chapter, five thousand nine hundred and forty seven of them across four hundred and fifty three chapters, ranked by how many chapters each one stands in. That ranking turned up concrete nouns nobody had noticed, and it also said something the hand written list could never have said.";
  "WHAT IS LEFT STANDING IN PLAIN ENGLISH IS MOSTLY NOT DRAWABLE, and that is a finding rather than a complaint. The words standing in the most chapters are like and away and also and until and must and only and surely and yet - verbs and adverbs and joining words. About forty of the top hundred and thirty are concrete nouns and roughly half of those were seated or refused in this pass. The noun queue is close to empty. What is left is grammar, and grammar is a different problem from a missing picture.";
  "A THIRD OUTCOME EXISTS AND IT IS NOT A REFUSAL, and two words found it. The wife and the palace were both written into this list as refusals and both were wrong to be here, because the number each one wants is already seated under a broader picture that is telling the truth. The word for a wife is the word for a woman and the woman mark is on it. The word for a palace is the word for a house and the house mark is on it. Neither reader loses anything, so neither word is work outstanding. A gate found both of these within a minute of being written, which is the argument for the gate.";
  "A CLEAN COUNT IS NOT ENOUGH, BECAUSE THE MARK MAY ALREADY BE TAKEN, and this was found the hard way. Four numbers were measured, came back at ninety and a hundred in a hundred, were seated on the picture that carries their name, and every one of the four was wrong. The crown picture was already the master. The star picture was already the glory of God. The oil picture was already the anointing and so already said Messiah. The scroll picture was already the law. A glyph name says what the artwork looks like. It does not say what the mark has been made to mean, and the seat is a claim about the meaning.";
  "NOTHING IN THE MEASURING COULD HAVE CAUGHT THAT, but a gate already could have, and that is the more useful half of the story. The interlinear count answers whether one Hebrew number has one sense; it cannot answer whether some other number is already wearing the picture. A gate for exactly that question has been in the build the whole time, it calls a picture standing for two roots the worst fault the alphabet can have, and it names every offender in one run. It was not asked. Four wrong seats were then found by hand, and when the gate was finally run it named nine more that the hand reading had walked straight past. So the rule is two questions and not one - is the word one sense, and is the picture free - and the second question already has an answer waiting to be asked for.";
  "THE NINE THE GATE FOUND WERE ALL THE SAME MISTAKE IN ITS MILD FORM: a second Hebrew word put on a picture a first Hebrew word already had, because English says both with one word. The heavy rain beside the rain, the needy beside the poor, the male goat and the leading he goat beside the goat, the Babylonian furnace beside the smelting one, the bird trap beside the snare, the thrusting spear beside the spear, the ground meal beside the fine flour, the word for in front beside the sunrise, and the metal trumpet beside the ram horn. Each one was dropped and the commoner word kept, because the alphabet holds one rule here and holds it one way - a root may have many pictures, a picture may not have many roots. A reader meeting a picture has only the picture, and no amount of kinship between two words gives back which was meant. These are not wants and they are not refusals; they are listed so nobody measures them and seats them a second time.";
  "A REFUSAL CAN ALSO BE ANSWERED BY SEATING A DIFFERENT WORD, and the grain proved it. The grain sat here refused because the number the lines were asking for is the grain offering and not the crop, so a sheaf of wheat on it would have drawn a harvest where the text has a sacrifice. That reading was right and the conclusion was too small: the offering is a thing, it is one sense in a hundred and sixty of its two hundred and three wordings, and it can hold a picture of its own. It is seated now as the grain offering, beside the burnt offering, and the entry is gone from this list because the want it recorded has been met under the name the text actually uses. The gate caught the entry the moment the seat landed, which is the second time that gate has answered a question nobody thought to ask it.";
  "TWENTY SIX WORDS, AND FIVE MORE THAT THE TEXT HAS NO WORD FOR AT ALL. A razor, a ladder, a suit of armour, a prison and a wedding were each looked for and each turned out to be a phrase rather than a word - a prison is the house of confinement and a wedding is taking a wife. Those five are not refusals and they are not work outstanding, because there is nothing there to seat a picture on. They are here so that nobody measures them a third time.";
  "PANIM WAS TAKEN OFF THIS LIST ON 2026-09-18 AND SEATED ON A FACE, and the entry it had here is worth knowing about because the argument it made is a good one made from the wrong side. It counted the English the interlinear puts under the word - only fifteen in a hundred of those wordings say face, and the commonest is before - and concluded that a face would be drawn on the word for in front of five times out of six.";
  "WHAT DECIDED AGAINST IT IS THAT THE ENGLISH WORDING IS NOT THE ORIGINAL WORD. Panim is the face. Before is what a face does in this language, the way anger is what a nose does - and the nose entry still on this list refuses the anger picture for exactly that reason, keeping the body part and turning down the sense English reached for. Counting wordings measures which English the translators chose; the goal of this Bible is the word underneath them, and drawing the face is what lets a reader see that in front of and to the face of are one word rather than two.";
  "SO THE MEASURE STAYS USEFUL AND ITS CONCLUSION DOES NOT FOLLOW AUTOMATICALLY. A lopsided wording count is a reason to look hard at a seat, and it settles the question whenever the two senses are unrelated - the fear entry is decided that way. It does not settle it when the rarer wording is the word itself and the commoner one is built out of it.";
  "ROSH WAS TAKEN OFF THIS LIST ON 2026-10-08 AND SEATED ON A HEAD, FOR THE REASON PANIM WAS. Its entry counted only fifty eight in a hundred wordings saying head, the rest chief, top and beginning. Those are what a head is in this language, so the head is the word and the rest is English reaching for it.";
  "EVERY REMAINING ENTRY WAS TAKEN OFF THIS LIST ON 2026-10-08 AND SEATED, BECAUSE AN IMPERFECT PICTURE BEATS LETTERS. The goal is a Bible read through the emoji people already have, so a picture that fits only some senses of a word is still a picture, and an English word left standing shuts the reader out. Every refusal here was a quality objection, and quality is not a reason to leave letters. The one test that still refuses a seat is distinctness - one picture must not stand for two unrelated roots - and each of these twenty two was given a picture no other root holds: the nose burning for anger, the open mouth, the cyclone for the twisting that iniquity is, a box for the ark because tebah is a chest, a closed book, a curled page for the scroll, a lotion bottle for the oil that is not the anointing, a plain star beside the glowing one that is glory, and the crown with a thing beside the crown verb of the same root.";
  let wanted = [];
  return wanted;
}
