export function bible_glyph_chapter_lev02() {
  "The second chapter of Leviticus, drawn in pictures. The offering here is food a person made rather than an animal, and most of the chapter is about how it was cooked and what was not allowed in it.";
  "GRAIN OFFERING IS SAID FIFTEEN TIMES IN SIXTEEN VERSES. It is nearly the only noun the chapter keeps. Whatever shape the food takes, the name never changes, so the chapter is one thing seen from several kitchens.";
  "FOUR WAYS OF COOKING AND THE SAME NAME FOR ALL FOUR. Verse one is uncooked flour, verse four is baked in an oven, verse five is on a griddle, verse seven is in a pan. All four are called by the same word, and each gets the same handful burned. How you cooked it does not change what it is.";
  "TWO DIFFERENT WORDS FOR LEAVEN ARE BOTH SHUT OUT. Verse eleven says no leavened bread, and then says no starter either. They are separate words in the Hebrew, one for the risen dough and one for the lump that makes it rise. Honey is named beside them. Nothing that swells and nothing that sweetens goes on the fire.";
  "SALT IS SAID THREE TIMES AND ALL THREE ARE IN ONE VERSE. Verse thirteen says season with salt, do not leave the salt out, add salt. In between it calls it the salt of the covenant of your God. It is the only place in the chapter where the offering is tied to an agreement rather than to a meal.";
  "THERE ARE FOUR NOTS AND THE LAST ONE IS THE ONLY THING YOU MUST DO. Three of them forbid something, no leaven, no honey burned, firstfruits not going up in smoke. The fourth says do not leave out the salt, which is a command wearing the shape of a prohibition. The one required ingredient arrives as a thing you may not omit.";
  "THE PRIEST BURNS A HANDFUL AND KEEPS THE REST. Verses two and three do it once, verses nine and ten do it again in the same words. What goes up is called a memorial portion and what stays is called most holy. Holy is said four times in the chapter and every time it is about the part nobody burned.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "LEV02",
    reference: "Leviticus 2",
    verses: [
      {
        verse_number: 1,
        words: [
          "When",
          "$person_other",
          "brings",
          "$grain_offering",
          "$name_tag,",
          "his",
          "offering",
          "must",
          "be",
          "$flour.",
          "He",
          "is",
          "to",
          "pour",
          "olive",
          "oil",
          "on",
          "it",
          "and",
          "$hands_giving",
          "frankincense",
          "on",
          "it.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "And",
          "$footprints",
          "it",
          "to",
          "$son",
          "of",
          "Aaron",
          "$priest.",
          "He",
          "shall",
          "take",
          "a",
          "handful",
          "$flour",
          "and",
          "oil,",
          "together",
          "with",
          "all",
          "the",
          "frankincense,",
          "and",
          "$priest",
          "shall",
          "burn",
          "this",
          "as",
          "a",
          "memorial",
          "portion",
          "$altar,",
          "a",
          "food",
          "offering,",
          "a",
          "pleasing",
          "aroma",
          "$name_tag.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "The",
          "remainder",
          "$tray_out",
          "$grain_offering",
          "shall",
          "belong",
          "to",
          "Aaron",
          "and",
          "$son;",
          "it",
          "is",
          "$sparkle",
          "$sparkle",
          "of",
          "the",
          "food",
          "offerings",
          "$name_tag.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Now",
          "if",
          "you",
          "bring",
          "$grain_offering",
          "baked",
          "in",
          "an",
          "oven,",
          "it",
          "must",
          "be",
          "$flour,",
          "either",
          "unleavened",
          "cakes",
          "mixed",
          "with",
          "oil",
          "or",
          "unleavened",
          "wafers",
          "$oil",
          "with",
          "oil.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "If",
          "your",
          "offering",
          "$grain_offering",
          "prepared",
          "on",
          "a",
          "griddle,",
          "it",
          "must",
          "be",
          "$flour",
          "mixed",
          "with",
          "oil,",
          "unleavened.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Crumble",
          "it",
          "and",
          "pour",
          "oil",
          "on",
          "it;",
          "it",
          "$grain_offering.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "If",
          "your",
          "offering",
          "$grain_offering",
          "cooked",
          "in",
          "a",
          "pan,",
          "it",
          "must",
          "be",
          "$hammer",
          "$flour",
          "with",
          "oil.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "When",
          "you",
          "$footprints",
          "$grain_offering",
          "$hammer",
          "in",
          "any",
          "of",
          "these",
          "ways",
          "$name_tag,",
          "it",
          "is",
          "to",
          "be",
          "presented",
          "to",
          "$priest,",
          "and",
          "he",
          "shall",
          "take",
          "it",
          "to",
          "$altar.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$priest",
          "is",
          "to",
          "remove",
          "the",
          "memorial",
          "portion",
          "$tray_out",
          "$grain_offering",
          "and",
          "burn",
          "it",
          "$altar",
          "as",
          "a",
          "food",
          "offering,",
          "a",
          "pleasing",
          "aroma",
          "$name_tag.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "But",
          "the",
          "remainder",
          "$tray_out",
          "$grain_offering",
          "shall",
          "belong",
          "to",
          "Aaron",
          "and",
          "$son;",
          "it",
          "is",
          "$sparkle",
          "$sparkle",
          "of",
          "the",
          "food",
          "offerings",
          "$name_tag.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "No",
          "$grain_offering",
          "that",
          "you",
          "present",
          "$name_tag",
          "$no_entry",
          "$hammer",
          "with",
          "leaven,",
          "for",
          "you",
          "are",
          "$no_entry",
          "to",
          "burn",
          "any",
          "leaven",
          "or",
          "$honey",
          "$tray_out",
          "it",
          "as",
          "a",
          "food",
          "offering",
          "$name_tag.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "You",
          "may",
          "bring",
          "them",
          "$name_tag",
          "as",
          "an",
          "offering",
          "of",
          "firstfruits,",
          "but",
          "they",
          "$no_entry",
          "go",
          "up",
          "on",
          "$altar",
          "as",
          "a",
          "pleasing",
          "aroma.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "And",
          "you",
          "shall",
          "season",
          "each",
          "of",
          "your",
          "$grain_offering",
          "with",
          "salt.",
          "You",
          "$no_entry",
          "leave",
          "the",
          "salt",
          "$covenant",
          "of",
          "$fire",
          "out",
          "of",
          "$grain_offering;",
          "to",
          "each",
          "of",
          "your",
          "offerings",
          "you",
          "are",
          "to",
          "add",
          "salt.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "If",
          "you",
          "bring",
          "$grain_offering",
          "of",
          "firstfruits",
          "$name_tag,",
          "you",
          "shall",
          "offer",
          "crushed",
          "heads",
          "of",
          "new",
          "grain",
          "roasted",
          "on",
          "the",
          "fire",
          "as",
          "$grain_offering.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "And",
          "you",
          "are",
          "to",
          "$hands_giving",
          "oil",
          "on",
          "it",
          "and",
          "frankincense;",
          "it",
          "$grain_offering.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "$priest",
          "shall",
          "then",
          "burn",
          "the",
          "memorial",
          "portion",
          "of",
          "the",
          "crushed",
          "grain",
          "and",
          "the",
          "oil,",
          "together",
          "with",
          "all",
          "its",
          "frankincense,",
          "as",
          "a",
          "food",
          "offering",
          "$name_tag.",
        ],
      },
    ],
  };
  return chapter;
}
