export function bible_glyph_chapter_1jn01() {
  "The fifth picture Bible chapter written by hand: the whole of the first chapter of John's first letter, in the shorthand a person types.";
  "TWELVE CHAPTERS WERE MEASURED AT ONCE AND THIS ONE CAME BACK HIGHEST, which is the first time the comparison cost one call rather than one call per candidate. Forty two parts in a hundred were already drawn here, against thirty nine for John four, thirty six for John eleven and John ten, and twenty three for the sixth of Matthew at the bottom. The command that asks a whole shortlist at once was built for this and is the thing to reach for next time.";
  "AND IT IS TEN VERSES, which counted for as much as the share did. A chapter is what one person authors in a sitting, and the four before this one ran to thirty one, fifty one, twenty one and thirty six verses; a short chapter at the top of the shortlist is a whole chapter finished rather than a long one left half drawn.";
  "THIS ONE COST NEW VOCABULARY AND JOHN FOURTEEN DID NOT, which is the honest difference between them and was known before a word was written. John fourteen's blanks were the article, the pronouns and the connectives - the class that never becomes a picture - so it needed nothing new. Of the thirty commonest blanks here about ten are content words, and three of them were worth drawing. That is a real cost and it was paid deliberately: the pictures bought are blood, joined hands and walking, and all three are words this Bible will spend again everywhere.";
  "THE JOY AND THE BOTH-WAYS ARROW WERE DRAWN FOR OTHER CHAPTERS AND EARN THEIR KEEP HERE, in the fourth verse and the seventh. Neither was chosen for this letter and neither had to be. That is the second time a picture chosen for one passage has arrived already paying for itself in another, and it is the whole argument for a table keyed by root over a choice made per passage.";
  "WALKING IS THE SAME PICTURE THE GOING WORD ALREADY HAD, and the two verses that use it are the ones the chapter turns on: walking in the darkness against walking in the light. The Greek there is a different root from the one John fourteen used for going to the Father, and it is drawn the same, because a reader who sees a person walking in both places has been told something true both times.";
  "THE SIXTH VERSE AND THE SEVENTH ARE ONE SENTENCE DRAWN TWICE, and the page shows it. Both open with joined hands and a person walking, and only the light and the darkness differ between them - so the whole weight of the pair falls on the one opposition this Bible was most careful to draw far apart. A reader who cannot read a word of the chapter can still see that those two verses are the same shape and disagree.";
  "THE EIGHTH VERSE AND THE TENTH COME OUT AS THE SAME PICTURE and they are not the same claim, so this says so rather than leaving it to be found. Having no sin and having not sinned are a noun and a verb off one root, and the table draws one root with one mark on purpose. The marks therefore tell the reader less than the words do, which is allowed everywhere in this Bible; what is never allowed is a mark telling them more.";
  "CONFESS, DECEIVE, LIAR, UNRIGHTEOUSNESS AND CLEANSE STAYED IN ENGLISH, and the reasons are written in the root table with the other refusals rather than here, because a reason written here would be a reason held for one passage only. The short of it is that each of them needs a mark for something said or for a negation of a word that is not drawn yet, and every candidate claimed more than the word claims.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "1JN01",
    reference: "1 John 1",
    verses: [
      {
        verse_number: 1,
        words: [
          "That",
          "which",
          "was",
          "from",
          "the",
          "beginning,",
          "which",
          "we",
          "have",
          "$ear,",
          "which",
          "we",
          "have",
          "$eye",
          "with",
          "our",
          "own",
          "eyes,",
          "which",
          "we",
          "have",
          "gazed",
          "upon",
          "$plus",
          "touched",
          "with",
          "our",
          "own",
          "$hand:",
          "this",
          "is",
          "the",
          "$speech",
          "of",
          "$sprout.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$plus",
          "this",
          "is",
          "the",
          "$sprout",
          "that",
          "was",
          "revealed;",
          "we",
          "have",
          "$eye",
          "it",
          "$plus",
          "$witness",
          "to",
          "it,",
          "$plus",
          "we",
          "proclaim",
          "to",
          "you",
          "the",
          "eternal",
          "$sprout",
          "that",
          "was",
          "with",
          "the",
          "$father",
          "$plus",
          "was",
          "revealed",
          "to",
          "us.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "What",
          "we",
          "have",
          "$eye",
          "$plus",
          "$ear",
          "we",
          "proclaim",
          "to",
          "you,",
          "so",
          "that",
          "you",
          "also",
          "may",
          "have",
          "$handshake",
          "with",
          "us.",
          "$plus",
          "this",
          "$handshake",
          "of",
          "ours",
          "is",
          "with",
          "the",
          "$father",
          "$plus",
          "with",
          "$pointing_back",
          "$son,",
          "$cross",
          "$oil.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$plus",
          "we",
          "write",
          "these",
          "things",
          "so",
          "that",
          "our",
          "$smile",
          "may",
          "be",
          "complete.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$plus",
          "this",
          "is",
          "the",
          "message",
          "we",
          "have",
          "$ear",
          "from",
          "$pointing_back",
          "$plus",
          "announce",
          "to",
          "you:",
          "$fire",
          "is",
          "$light,",
          "$plus",
          "$tray_in",
          "$pointing_back",
          "there",
          "is",
          "$no_entry",
          "$darkness",
          "at",
          "all.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "If",
          "we",
          "$speech",
          "$pointing",
          "we",
          "have",
          "$handshake",
          "with",
          "$pointing_back",
          "yet",
          "$walking",
          "$tray_in",
          "the",
          "$darkness,",
          "we",
          "lie",
          "$plus",
          "do",
          "$no_entry",
          "$hammer",
          "the",
          "$check.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "But",
          "if",
          "we",
          "$walking",
          "$tray_in",
          "the",
          "$light",
          "as",
          "$pointing_back",
          "is",
          "$tray_in",
          "the",
          "$light,",
          "we",
          "have",
          "$handshake",
          "with",
          "$arrow_both_ways,",
          "$plus",
          "the",
          "$blood",
          "of",
          "$cross",
          "$pointing_back",
          "$son",
          "cleanses",
          "us",
          "from",
          "all",
          "$bow.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "If",
          "we",
          "$speech",
          "$pointing",
          "we",
          "have",
          "$no_entry",
          "$bow,",
          "we",
          "deceive",
          "ourselves",
          "$plus",
          "the",
          "$check",
          "is",
          "$no_entry",
          "$tray_in",
          "us.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "If",
          "we",
          "confess",
          "our",
          "$bow,",
          "$pointing_back",
          "is",
          "$anchor",
          "$plus",
          "just",
          "to",
          "forgive",
          "us",
          "our",
          "$bow",
          "$plus",
          "to",
          "cleanse",
          "us",
          "from",
          "all",
          "unrighteousness.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "If",
          "we",
          "$speech",
          "$pointing",
          "we",
          "have",
          "$no_entry",
          "$bow,",
          "we",
          "$hammer",
          "$pointing_back",
          "out",
          "to",
          "be",
          "a",
          "liar,",
          "$plus",
          "$pointing_back",
          "$speech",
          "is",
          "$no_entry",
          "$tray_in",
          "us.",
        ],
      },
    ],
  };
  return chapter;
}
