export function bible_glyph_chapter_isa12() {
  "Isaiah 12, drawn in pictures, so that a person who cannot read the letters can still follow it. A short song of thanks placed at the end of eleven chapters of judgment, in which a rescued people tell each other to draw water and to make the name of God known everywhere. Six lines.";
  "THE LINE THAT IS ABOUT THE NAME LOSES EVERY NAME MARK ON IT. The fourth line says proclaim His name, and declare that His name is exalted, and it says it to the LORD. Three name marks were drafted onto that one sentence and all three had to come off, because the picture for the divine name and the picture for the Hebrew word name are the same picture, and a line holding both would show a reader the same tag standing for two different things. Thirteen other chapters here have lost a name mark to that collision. This is the worst of them, because the fourth line is the only line in the chapter whose whole subject is the name, and it now carries a day, a speech bubble, raised hands, a lightbulb and a family, and nothing at all where the name goes.";
  "THE LINE EVERYBODY KNOWS COMES OUT AS ONE DROP OF WATER. With joy you will draw water from the springs of salvation. Joy, drawing, springs and salvation, and the only picture on the line is the water. There is no drawing for joy, none for a spring or a well, and none for salvation, so the third line of this chapter, which is the line people put on walls, shows a reader one drop and four blank words.";
  "SALVATION IS THE WHOLE SUBJECT AND THERE IS NO PICTURE FOR IT. God is my salvation in the second line, He has become my salvation at the end of the second line, the springs of salvation in the third. Three times in three lines, and plain every time. The prophet's own name means the LORD saves, and the six lines here are the song the rescued sing. A reader following pictures can see the flame, the trust and the water and cannot see the one word all three of them are about.";
  "THE ANGER TURNS AWAY AND THE COMFORT DOES NOT ARRIVE. Although You were angry with me, Your anger has turned away and You have comforted me. That sentence is the hinge of the whole song, and it has one mark on it, the arrow that means turning back, sitting exactly where the turn happens. The anger has no picture either side of it and the comforting has none. So a reader sees something turn around and is not shown what turned or what came instead.";
  "WHAT THE PAGE DOES CARRY IS THE SHAPE OF THE SONG. In that day you will say opens the first line and on that day you will say opens the fourth, and both of them arrive complete, a sun and a speech bubble in the same order. Raised hands land on praise in both halves. So a reader with no letters can still see that this is one song in two parts, each of them beginning the same way and each of them opening into praise. For six lines that is most of the structure.";
  "Three marks were dropped, and all three of them are the name marks in the fourth line described above. Nothing else on this page had to stand down, which makes it one of the cleanest chapters drawn here.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "ISA12",
    reference: "Isaiah 12",
    verses: [
      {
        verse_number: 1,
        words: [
          "In",
          "that",
          "$sun",
          "you",
          "will",
          "$speech,",
          "I",
          "will",
          "$hands_raised",
          "You,",
          "O",
          "$name_tag.",
          "Although",
          "You",
          "were",
          "angry",
          "with",
          "me,",
          "Your",
          "anger",
          "has",
          "$turn_back",
          "and",
          "You",
          "have",
          "comforted",
          "me.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Surely",
          "$fire",
          "is",
          "my",
          "salvation;",
          "I",
          "will",
          "trust",
          "and",
          "$no_entry",
          "be",
          "afraid.",
          "For",
          "the",
          "LORD",
          "$name_tag",
          "is",
          "my",
          "strength",
          "and",
          "my",
          "song,",
          "and",
          "He",
          "also",
          "has",
          "become",
          "my",
          "salvation.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "With",
          "joy",
          "you",
          "will",
          "draw",
          "$water",
          "from",
          "the",
          "springs",
          "of",
          "salvation.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "And",
          "on",
          "that",
          "$sun",
          "you",
          "will",
          "$speech,",
          "Give",
          "$hands_raised",
          "to",
          "the",
          "LORD,",
          "proclaim",
          "His",
          "name;",
          "$lightbulb",
          "His",
          "works",
          "known",
          "among",
          "the",
          "$family,",
          "declare",
          "that",
          "His",
          "name",
          "is",
          "exalted.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Sing",
          "to",
          "the",
          "$name_tag,",
          "for",
          "He",
          "has",
          "$hammer",
          "glorious",
          "things.",
          "Let",
          "this",
          "be",
          "$lightbulb",
          "in",
          "all",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Cry",
          "out",
          "and",
          "sing,",
          "O",
          "citizen",
          "of",
          "Zion,",
          "for",
          "great",
          "among",
          "you",
          "is",
          "the",
          "$sparkle",
          "One",
          "of",
          "Israel.",
        ],
      },
    ],
  };
  return chapter;
}
