export function bible_glyph_chapter_jon02() {
  "The second chapter of Jonah, drawn in pictures. It is one prayer, said from inside a fish, and it is almost entirely made of water going over a man. Ten lines.";
  "THE VOICE MARK FALLS TWICE AND THERE IS ONE AT EACH END OF THE PRAYER. In the second verse, You heard my voice. In the ninth, I will sacrifice to You with the voice of thanksgiving. Those are the only two, and between them is everything the water did to him. So the shape of the page in pictures is a voice going up, a long drowning, and a voice going up again - and the second one is not asking for anything. The second verse also carries the ear beside the voice, which is the pair the whole prayer rests on: he made a sound and it was heard.";
  "THREE LINES IN A ROW SAY LIFE AND TWO DIFFERENT PICTURES CARRY IT. The fifth verse says the waters engulfed me to take my life. The sixth says You raised my life from the pit. The seventh says as my life was fading away. English uses the same word all three times, but Hebrew does not: the fifth and the seventh are the word this Bible draws as a person, the one it uses for a living soul, and the sixth is a different word, the one it draws as something growing. So the life the sea was taking and the life God pulled up are named differently in the middle of three consecutive lines, and only the picture shows it.";
  "THE HOLY MARK FALLS TWICE AND BOTH TIMES IT IS THE SAME TEMPLE. In the fourth verse, banished and sinking, he says yet I will look once more toward Your holy temple. In the seventh, my prayer went up to You, to Your holy temple. The first is where he decided to aim and the second is where it arrived. Two marks, four verses apart, and they are the two halves of one sentence about a prayer that had a long way to travel.";
  "THE FISH IS ON THE FIRST LINE AND THE LAST AND NOWHERE IN BETWEEN. The chapter opens from inside the fish and closes with the LORD commanding the fish. Eight verses of prayer sit between them without mentioning it once, which is exactly right: the man inside is not thinking about the fish. And the tenth verse uses the speaking word for what God says to it - the same picture that carried Jonah saying and the prophet praying is what God uses on an animal.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "JON02",
    reference: "Jonah 2",
    verses: [
      {
        verse_number: 1,
        words: [
          "From",
          "inside",
          "the",
          "$fish,",
          "Jonah",
          "$hands_praying",
          "to",
          "the",
          "$name_tag",
          "his",
          "$fire,",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$speech:",
          "In",
          "my",
          "distress",
          "I",
          "called",
          "to",
          "the",
          "$name_tag,",
          "and",
          "He",
          "answered",
          "me.",
          "From",
          "the",
          "belly",
          "of",
          "Sheol",
          "I",
          "called",
          "for",
          "help,",
          "and",
          "You",
          "$ear",
          "my",
          "$voice.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "For",
          "You",
          "cast",
          "me",
          "into",
          "the",
          "deep,",
          "into",
          "the",
          "$heart_organ",
          "of",
          "the",
          "$sea,",
          "and",
          "the",
          "current",
          "swirled",
          "about",
          "me;",
          "all",
          "Your",
          "breakers",
          "and",
          "waves",
          "swept",
          "over",
          "me.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "At",
          "this,",
          "I",
          "$speech,",
          "I",
          "have",
          "been",
          "banished",
          "from",
          "Your",
          "$eyes;",
          "yet",
          "I",
          "will",
          "look",
          "once",
          "more",
          "toward",
          "Your",
          "$sparkle",
          "temple.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$water",
          "engulfed",
          "me",
          "to",
          "take",
          "my",
          "$person_other;",
          "the",
          "watery",
          "depths",
          "closed",
          "around",
          "me;",
          "the",
          "seaweed",
          "wrapped",
          "around",
          "my",
          "head.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "To",
          "the",
          "roots",
          "of",
          "the",
          "$mountain",
          "I",
          "descended;",
          "the",
          "$earth",
          "beneath",
          "me",
          "barred",
          "me",
          "in",
          "$hourglass!",
          "But",
          "You",
          "raised",
          "my",
          "$sprout",
          "from",
          "the",
          "pit,",
          "O",
          "$name_tag",
          "my",
          "$fire!",
        ],
      },
      {
        verse_number: 7,
        words: [
          "As",
          "my",
          "$person_other",
          "was",
          "fading",
          "away,",
          "I",
          "remembered",
          "the",
          "$name_tag.",
          "My",
          "$hands_praying",
          "$footprints",
          "up",
          "to",
          "You,",
          "to",
          "Your",
          "$sparkle",
          "temple.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Those",
          "who",
          "cling",
          "to",
          "worthless",
          "idols",
          "forsake",
          "His",
          "$gift.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "But",
          "I,",
          "with",
          "the",
          "$voice",
          "of",
          "thanksgiving,",
          "will",
          "sacrifice",
          "to",
          "You.",
          "What",
          "I",
          "have",
          "vowed",
          "I",
          "will",
          "fulfill.",
          "Salvation",
          "is",
          "from",
          "the",
          "$name_tag!",
        ],
      },
      {
        verse_number: 10,
        words: [
          "And",
          "the",
          "$name_tag",
          "$speech",
          "the",
          "$fish,",
          "and",
          "it",
          "vomited",
          "Jonah",
          "onto",
          "dry",
          "land.",
        ],
      },
    ],
  };
  return chapter;
}
