export function bible_glyph_chapter_job23() {
  "Job 23, drawn in pictures, so that a person who cannot read the letters can still follow it. Job wishes he could find God and put his case before him like a man in court, admits he has looked in all four directions and cannot find him anywhere, and ends terrified in the dark. Seventeen lines.";
  "FOUR OF THE SEVENTEEN LINES COME OUT COMPLETELY BLANK, AND THE FIRST LINE IS ONE OF THEM. Then Job answered has a speaking mark in the draft, but it sits on a piece of Hebrew that this English swallows, so it had nothing to stand on and the chapter opens with no picture at all. The seventh line, about being delivered forever from his Judge, and the fourteenth, about God carrying out his decree, were drafted with nothing on them. The fifteenth, I am terrified in His presence, had one mark and it was an out-of picture sitting on the word Him, which does not hold it. So a reader turning to this page meets four sentences in a row of ordinary letters and no help.";
  "THE FOUR DIRECTIONS ARE THE WHOLE ARGUMENT AND NOT ONE OF THEM IS DRAWN. If I go east He is not there, if I go west I cannot find Him, when He is at work in the north I cannot behold Him, when He turns to the south I cannot see Him. East, west, north and south, four words in two lines, and there is no picture for a direction in this collection at all. What lands instead is a walking figure on the first go and a working hammer in the north, so a reader sees a man walking and God working and never learns that the point is that Job looked everywhere.";
  "WHAT THE PAGE DOES CARRY IS THE NOT. Seven crossing-out marks land here, in the sixth, eighth, eleventh, twelfth and seventeenth lines and twice in the ninth. This is a chapter about a man who cannot find, cannot behold, cannot see, has not turned aside, has not departed and is not silenced, and the crossing-out is the single most common picture on the page. A reader following only pictures gets the shape of it: a man searching, and again and again a thing struck out. That is a fair reading of Job 23 and it arrives for free.";
  "THE SEAT AND THE JUDGE ARE BLANK AND ONLY THE SCALES ARRIVE. So that I could go to His seat in the third line, I would plead my case before Him in the fourth, delivered forever from my Judge in the seventh. The whole chapter is staged as a courtroom, and of its three pieces of furniture the scales land and the throne and the judge do not, because there is no picture for either. Esther 1 lost a throne in its second line for the same reason. What a reader sees is a man walking somewhere and a set of scales, which is most of the idea but not the part about who is sitting there.";
  "THERE ARE TWO MOUTHS AND A PAIR OF LIPS ON THIS PAGE AND NOT ONE OF THEM IS DRAWN. Fill my mouth with arguments in the fourth line, the command of His lips and the words of His mouth in the twelfth. The mouth picture exists and is used in many chapters here, and it is spent on the Hebrew verb for speaking, so it is never available for an actual mouth. The twelfth line says lips and mouth in one sentence and both come out plain, with a scroll on the word command sitting between them.";
  "THE DARKNESS IS SAID TWICE IN THE LAST LINE AND DRAWN ONCE. I am not silenced by the darkness, by the thick darkness that covers my face. Two different Hebrew words, and only the first has artwork seated on it, so the closing sentence of the chapter shows one dark mark and then repeats itself in plain letters. The face in that line has no picture either.";
  "Four marks were dropped. The speaking mark in the first line and a giving mark in the third both sat on Hebrew the English swallows. The out-of mark on the word Him in the fifteenth line does not hold what the picture says. The fourth is a generic-person picture that the draft put on the word He in the thirteenth line, where the Hebrew underneath is his soul; drawing an ordinary human being for God would have been worse than leaving the word plain.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "JOB23",
    reference: "Job 23",
    verses: [
      {
        verse_number: 1,
        words: ["Then", "Job", "answered:"],
      },
      {
        verse_number: 2,
        words: [
          "Even",
          "$sun",
          "my",
          "complaint",
          "is",
          "bitter.",
          "His",
          "$hand",
          "is",
          "heavy",
          "despite",
          "my",
          "groaning.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "If",
          "only",
          "I",
          "$lightbulb",
          "where",
          "to",
          "find",
          "Him,",
          "so",
          "that",
          "I",
          "could",
          "$footprints",
          "to",
          "His",
          "seat!",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "would",
          "plead",
          "my",
          "$scales",
          "before",
          "Him",
          "and",
          "fill",
          "my",
          "mouth",
          "with",
          "arguments.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "I",
          "would",
          "$lightbulb",
          "how",
          "He",
          "would",
          "answer",
          "and",
          "consider",
          "what",
          "He",
          "would",
          "$speech.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Would",
          "He",
          "contend",
          "with",
          "me",
          "in",
          "His",
          "great",
          "$lightning?",
          "$no_entry,",
          "He",
          "would",
          "certainly",
          "take",
          "note",
          "of",
          "me.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Then",
          "an",
          "upright",
          "man",
          "could",
          "reason",
          "with",
          "Him,",
          "and",
          "I",
          "would",
          "be",
          "delivered",
          "forever",
          "from",
          "my",
          "Judge.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "If",
          "I",
          "$walking",
          "east,",
          "He",
          "is",
          "not",
          "there;",
          "and",
          "if",
          "I",
          "go",
          "west,",
          "I",
          "$no_entry",
          "find",
          "Him.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "When",
          "He",
          "is",
          "at",
          "$hammer",
          "in",
          "the",
          "north,",
          "I",
          "$no_entry",
          "behold",
          "Him;",
          "when",
          "He",
          "turns",
          "to",
          "the",
          "south,",
          "I",
          "$no_entry",
          "$eye",
          "Him.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "Yet",
          "He",
          "$lightbulb",
          "the",
          "$road",
          "I",
          "have",
          "taken;",
          "when",
          "He",
          "has",
          "tested",
          "me,",
          "I",
          "will",
          "come",
          "forth",
          "as",
          "gold.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "My",
          "feet",
          "have",
          "followed",
          "in",
          "His",
          "tracks;",
          "I",
          "have",
          "kept",
          "His",
          "$road",
          "$no_entry",
          "turning",
          "aside.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "I",
          "have",
          "$no_entry",
          "departed",
          "from",
          "the",
          "$scroll",
          "of",
          "His",
          "lips;",
          "I",
          "have",
          "treasured",
          "the",
          "words",
          "of",
          "His",
          "mouth",
          "more",
          "than",
          "my",
          "daily",
          "bread.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "But",
          "He",
          "is",
          "unchangeable,",
          "and",
          "who",
          "can",
          "$turn_back",
          "Him?",
          "What",
          "He",
          "desires,",
          "He",
          "$hammer.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "For",
          "He",
          "carries",
          "out",
          "His",
          "decree",
          "against",
          "me,",
          "and",
          "He",
          "has",
          "many",
          "such",
          "plans.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Therefore",
          "I",
          "am",
          "terrified",
          "in",
          "His",
          "presence;",
          "when",
          "I",
          "consider",
          "this,",
          "I",
          "fear",
          "Him.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "$fire",
          "has",
          "made",
          "my",
          "$heart_organ",
          "faint;",
          "the",
          "Almighty",
          "has",
          "terrified",
          "me.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Yet",
          "I",
          "am",
          "$no_entry",
          "silenced",
          "by",
          "the",
          "$darkness,",
          "by",
          "the",
          "thick",
          "darkness",
          "that",
          "covers",
          "my",
          "face.",
        ],
      },
    ],
  };
  return chapter;
}
