export function bible_glyph_chapter_psa139() {
  "The hundred and thirty ninth psalm, drawn in pictures. A man works out that there is nowhere he could go where God would not already be, that he was put together before anyone had seen him, and then asks to be searched anyway.";
  "THE PSALM OPENS WITH YOU HAVE KNOWN ME AND ENDS BY ASKING TO BE KNOWN. The first verse is O LORD, You have searched me and known me. The second to last is Search me, O God, and know my heart. Same two verbs, same order, at both ends of the poem - and the knowing mark, which falls six times in all, sits on both. The difference between the two ends is not the words but the mood. The first is a report of something already true and slightly alarming. The last is a request for more of it. A reader who follows only the marks can see the psalm begin and end on the same picture and can be told, truthfully, that everything in between is what changed the man's mind about it.";
  "THE ROAD MARK OPENS THE PSALM AND THEN FILLS ITS LAST LINE. In the third verse God is aware of all my ways. In the last verse the psalmist asks whether there is any offensive way in him, and then asks to be led in the way everlasting. Three roads in all, one at the start and two together at the finish, so the poem is shaped like a journey in its pictures as well as its words - it begins with someone's paths being examined and ends with him asking to be put on a different one. Only the everlasting mark comes after them, which is the right last word for a road.";
  "THE DARKNESS MARK APPEARS TWICE AND THE SECOND TIME IT IS CROSSED OUT. Surely the darkness will hide me - and then, even the darkness is not dark to You. The same picture twice, one verse apart, first as a hiding place and then as no hiding place at all. The first time it is followed by the light it was supposed to swallow. The second time the very next mark is the negation, and the verse finishes on the day. So a reader who takes only the pictures across those two verses gets dark, light, dark, crossed out, day - which is the argument of the passage, in order, with no vocabulary needed to follow it.";
  "THE VERSES NOBODY QUOTES COME RIGHT BEFORE THE ONES EVERYBODY DOES. This psalm is loved for being knit together in a mother's womb and for the search me at the end. Sitting between those two is a stretch where the psalmist asks God to kill people and says he hates them with perfect hatred. The marks make the join impossible to skip: the wicked mark and the blood mark stand four verses before the two knowing marks of the request. That order is worth keeping rather than tidying. The man asks to be searched immediately after saying the most violent thing in the poem, which is either the bravest line in it or the most necessary one, and either way it is why the request is there.";
  "TWO DIFFERENT EYE MARKS STAND SIDE BY SIDE IN ONE VERSE, AND THE SEEING ONE COMES BACK AT THE END. The sixteenth verse says Your eyes saw my unformed body, and the table draws the eyes and the seeing with two different pictures, side by side. They are separate words in Hebrew, so they are separate marks here, and a reader meeting them together learns something useful about how these pages work: a mark is a word, not an idea, and the noun and the verb do not have to share one. The last verse then opens with See if there is any offensive way in me, using the same seeing mark that watched the unformed body - the psalm asks to be looked at with the eye that has already looked.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "PSA139",
    reference: "Psalm 139",
    verses: [
      {
        verse_number: 1,
        words: [
          "For",
          "the",
          "choirmaster.",
          "A",
          "Psalm",
          "of",
          "David.",
          "O",
          "$name_tag,",
          "You",
          "have",
          "searched",
          "me",
          "and",
          "$lightbulb",
          "me.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "You",
          "$lightbulb",
          "when",
          "I",
          "sit",
          "and",
          "when",
          "I",
          "rise;",
          "You",
          "understand",
          "my",
          "thoughts",
          "from",
          "afar.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "You",
          "search",
          "out",
          "my",
          "path",
          "and",
          "my",
          "lying",
          "down;",
          "You",
          "are",
          "aware",
          "of",
          "all",
          "my",
          "$road.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Even",
          "before",
          "a",
          "word",
          "is",
          "on",
          "my",
          "tongue,",
          "You",
          "$lightbulb",
          "all",
          "about",
          "it,",
          "O",
          "$name_tag.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "You",
          "hem",
          "me",
          "in",
          "behind",
          "and",
          "before;",
          "You",
          "have",
          "laid",
          "Your",
          "hand",
          "upon",
          "me.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Such",
          "knowledge",
          "is",
          "too",
          "wonderful",
          "$tray_out",
          "me,",
          "too",
          "lofty",
          "for",
          "me",
          "to",
          "attain.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "Where",
          "can",
          "I",
          "$walking",
          "to",
          "escape",
          "Your",
          "$wind?",
          "Where",
          "can",
          "I",
          "flee",
          "from",
          "Your",
          "presence?",
        ],
      },
      {
        verse_number: 8,
        words: [
          "If",
          "I",
          "ascend",
          "to",
          "the",
          "$sky,",
          "You",
          "are",
          "there;",
          "if",
          "I",
          "make",
          "my",
          "bed",
          "in",
          "Sheol,",
          "You",
          "are",
          "there.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "If",
          "I",
          "rise",
          "on",
          "the",
          "wings",
          "of",
          "the",
          "dawn,",
          "if",
          "I",
          "settle",
          "by",
          "the",
          "farthest",
          "$sea,",
        ],
      },
      {
        verse_number: 10,
        words: [
          "even",
          "there",
          "Your",
          "$hand",
          "will",
          "guide",
          "me;",
          "Your",
          "right",
          "hand",
          "will",
          "hold",
          "me",
          "fast.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "If",
          "I",
          "$speech,",
          "Surely",
          "the",
          "$darkness",
          "will",
          "hide",
          "me,",
          "and",
          "the",
          "$light",
          "become",
          "night",
          "around",
          "me",
          "-",
        ],
      },
      {
        verse_number: 12,
        words: [
          "even",
          "the",
          "$darkness",
          "is",
          "$no_entry",
          "dark",
          "$tray_out",
          "You,",
          "but",
          "the",
          "night",
          "shines",
          "like",
          "the",
          "$sun,",
          "for",
          "darkness",
          "is",
          "as",
          "light",
          "to",
          "You.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "For",
          "You",
          "formed",
          "my",
          "inmost",
          "being;",
          "You",
          "knit",
          "me",
          "together",
          "in",
          "my",
          "mother's",
          "womb.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "I",
          "$hands_raised",
          "You,",
          "for",
          "I",
          "am",
          "fearfully",
          "and",
          "wonderfully",
          "made.",
          "Marvelous",
          "are",
          "Your",
          "works,",
          "and",
          "$person_other",
          "$lightbulb",
          "this",
          "very",
          "well.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "My",
          "frame",
          "was",
          "$no_entry",
          "hidden",
          "$tray_out",
          "You",
          "when",
          "I",
          "was",
          "$hammer",
          "in",
          "secret,",
          "when",
          "I",
          "was",
          "woven",
          "together",
          "in",
          "the",
          "depths",
          "of",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "Your",
          "$eyes",
          "$eye",
          "my",
          "unformed",
          "body;",
          "all",
          "my",
          "$sun",
          "were",
          "written",
          "in",
          "Your",
          "book",
          "and",
          "ordained",
          "for",
          "me",
          "before",
          "one",
          "of",
          "them",
          "came",
          "to",
          "be.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "How",
          "precious",
          "to",
          "me",
          "are",
          "Your",
          "thoughts,",
          "O",
          "$fire!",
          "How",
          "vast",
          "is",
          "their",
          "sum!",
        ],
      },
      {
        verse_number: 18,
        words: [
          "If",
          "I",
          "were",
          "to",
          "count",
          "them,",
          "they",
          "would",
          "outnumber",
          "the",
          "grains",
          "of",
          "sand;",
          "and",
          "when",
          "I",
          "awake,",
          "I",
          "am",
          "still",
          "with",
          "You.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "O",
          "that",
          "You",
          "would",
          "slay",
          "the",
          "$thumbs_down,",
          "O",
          "God!",
          "Away",
          "$tray_out",
          "me,",
          "you",
          "$blood",
          "men!",
        ],
      },
      {
        verse_number: 20,
        words: [
          "who",
          "$speech",
          "of",
          "You",
          "deceitfully;",
          "Your",
          "enemies",
          "take",
          "Your",
          "name",
          "in",
          "vain.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Do",
          "I",
          "$no_entry",
          "hate",
          "those",
          "who",
          "hate",
          "You,",
          "O",
          "$name_tag,",
          "and",
          "detest",
          "those",
          "who",
          "rise",
          "against",
          "You?",
        ],
      },
      {
        verse_number: 22,
        words: [
          "I",
          "hate",
          "them",
          "with",
          "perfect",
          "hatred;",
          "I",
          "count",
          "them",
          "as",
          "my",
          "enemies.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Search",
          "me,",
          "O",
          "$fire,",
          "and",
          "$lightbulb",
          "my",
          "$heart_organ;",
          "test",
          "me",
          "and",
          "$lightbulb",
          "my",
          "concerns.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "$eye",
          "if",
          "there",
          "is",
          "any",
          "offensive",
          "$road",
          "in",
          "me,",
          "and",
          "lead",
          "me",
          "in",
          "the",
          "$road",
          "$hourglass.",
        ],
      },
    ],
  };
  return chapter;
}
