export function bible_glyph_chapter_mal04() {
  "Malachi 4, drawn in pictures. Six verses, and the last of them is the last verse of the Old Testament. A furnace for the arrogant, healing for those who fear the name, Moses remembered, Elijah promised, and fathers and children turned back toward each other. Malachi 1, 2 and 3 are already written, so this completes the book.";
  "FOUR SUN MARKS ON THIS PAGE, AND NOT ONE OF THEM IS THE SUN. The Hebrew word for day is seated on the sun picture, and this chapter says day four times - the day that is coming, the day that is coming again, the day I am preparing, and the Day of the LORD. Then in the second verse it says the sun of righteousness, which is the one place on the page that means an actual sun in the actual sky, and Hebrew uses a different word for it, and that word has no seat. So a reader sees four suns, none of which is the sun, standing next to the sun, which is not drawn. It is the same shape as the four fire marks in Joel 1 that are not fire.";
  "THE COMING MARK FALLS FOUR TIMES AND THE OLD TESTAMENT GOES OUT ON IT. The day is coming, the day is coming, before the coming Day of the LORD, and at the very end I will come and strike the land. It is the same picture every time, and it is the last picture in this half of the Bible - which is exactly right for a book that stops in the middle of waiting for someone.";
  "THE LAST VERSE IS A MIRROR AND THE PICTURES SHOW IT WITHOUT A WORD. The hearts of the fathers to their children, and the hearts of the children to their fathers. Heart, father, child, then heart, child, father - three marks laid down and then laid down again backwards. A reader who cannot read the sentence can still see the turn in it, which is the one thing the sentence is about.";
  "THE SERVANT MARK LANDS ON MOSES. Remember the law of My servant Moses. This Bible puts the same kneeling picture on Moses five times in Joshua 1 and on Zerubbabel at the end of Haggai 2, so the last chapter of the Old Testament reaches back and picks up the title the first of those books never put down.";
  "THE OLD TESTAMENT ENDS ON THE WORD CURSE AND THERE IS NO MARK ON IT. The Hebrew here is not the cursing word that this Bible owns a picture for; it is the word for a thing devoted to destruction, and it has no seat. So the final word of thirty-nine books arrives in plain letters, with the two marks before it - I will come, and the land - drawn on either side of a silence.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "MAL04",
    reference: "Malachi 4",
    verses: [
      {
        verse_number: 1,
        words: [
          "For",
          "behold,",
          "the",
          "$sun",
          "is",
          "$footprints,",
          "burning",
          "like",
          "a",
          "furnace,",
          "when",
          "all",
          "the",
          "arrogant",
          "and",
          "every",
          "$hammer",
          "of",
          "evil",
          "will",
          "be",
          "stubble.",
          "The",
          "$sun",
          "is",
          "$footprints",
          "when",
          "I",
          "will",
          "set",
          "them",
          "ablaze,",
          "$speech",
          "the",
          "$name_tag",
          "of",
          "Hosts.",
          "$no_entry",
          "a",
          "root",
          "or",
          "branch",
          "will",
          "be",
          "left",
          "to",
          "them.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "But",
          "for",
          "you",
          "who",
          "fear",
          "My",
          "$name_tag,",
          "the",
          "sun",
          "of",
          "$ruler",
          "will",
          "rise",
          "with",
          "healing",
          "in",
          "its",
          "wings,",
          "and",
          "you",
          "will",
          "go",
          "out",
          "and",
          "leap",
          "like",
          "calves",
          "from",
          "the",
          "stall.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Then",
          "you",
          "will",
          "trample",
          "the",
          "$thumbs_down,",
          "for",
          "they",
          "will",
          "be",
          "ashes",
          "under",
          "the",
          "soles",
          "of",
          "your",
          "feet",
          "on",
          "the",
          "$sun",
          "I",
          "am",
          "$hammer,",
          "$speech",
          "the",
          "$name_tag",
          "of",
          "Hosts.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Remember",
          "the",
          "$scroll",
          "of",
          "My",
          "$kneeling",
          "Moses,",
          "the",
          "statutes",
          "and",
          "$scales",
          "I",
          "commanded",
          "him",
          "at",
          "Horeb",
          "for",
          "all",
          "Israel.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Behold,",
          "I",
          "will",
          "send",
          "you",
          "Elijah",
          "the",
          "$megaphone",
          "before",
          "the",
          "$footprints",
          "of",
          "the",
          "great",
          "and",
          "awesome",
          "$sun",
          "of",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "And",
          "he",
          "will",
          "$turn_back",
          "the",
          "$heart_organ",
          "of",
          "the",
          "$father",
          "to",
          "their",
          "$son,",
          "and",
          "the",
          "$heart_organ",
          "of",
          "the",
          "$son",
          "to",
          "their",
          "$father.",
          "Otherwise,",
          "I",
          "will",
          "$footprints",
          "and",
          "strike",
          "the",
          "$earth",
          "with",
          "a",
          "curse.",
        ],
      },
    ],
  };
  return chapter;
}
