export function bible_glyph_chapter_psa084() {
  "Psalm 84, drawn in pictures. Somebody far from the temple writes down how badly they want to be back in it, and works out on the way that the road there is already the good part. Twelve lines.";
  "THE WHOLE PSALM IS HOMESICKNESS AND NONE OF THE WANTING CAN BE DRAWN. The second verse says my soul longs, even faints, for the courts of the LORD, and my heart and my flesh cry out. The page draws the soul, and the heart, and the flesh, and God, and leaves out the longing, the fainting and the crying out. Three pictures stand there naming parts of a person, and the thing all three of them are doing is in plain letters.";
  "TWO DIFFERENT BLESSING PICTURES SIT ON ONE PAGE AND THEY ARE NOT THE SAME WORD. Three times the psalm says blessed are those, and that is one Hebrew word, drawn with a gift and a smile. Once, in the sixth verse, a different Hebrew word turns up and it gets the other blessing mark, a speech and a thumbs up. English uses blessed for both and hides the seam. The page shows it, because the root table seated them on two separate pictures.";
  "THAT SECOND BLESSING MARK IS SITTING ON RAINWATER. In Hebrew the word for pools and the word for blessings are written the same way, and translators have to pick one. Some Bibles say the autumn rain fills the pools; others say it covers the valley with blessings. The picture Bible cannot pick, because the mark is seated on the word and not on the meaning, so a reader of this page sees a blessing put down in the middle of a rainstorm and is left exactly where the translators were.";
  "THE PSALM CALLS GOD A SUN AND THE PAGE CANNOT DRAW IT. The eleventh verse says the LORD God is a sun and a shield, and both go bare, because in this Bible the little sun is seated on the Hebrew word for a day and not on the thing in the sky. One line earlier that same little sun is drawn, for one day in Your courts is better than a thousand elsewhere. So the sun is on the page, one line above the sentence that needed it.";
  "THE WORD MESSIAH IS IN THIS PSALM AND IT IS DRAWN AS A JAR OF OIL. The ninth verse asks God to look with favor on the face of Your anointed, and the anointed one is where that jar is seated in this Bible. A reader who has met the jar anywhere else in this Bible will recognise it here without being told.";
  "The marks come from the root table, not from this page. A word already seated on a Hebrew root is drawn the same way everywhere in this Bible, and a word with no seat stays in plain letters until one is bought.";
  let chapter = {
    chapter_code: "PSA084",
    reference: "Psalm 84",
    verses: [
      {
        verse_number: 1,
        words: [
          "For",
          "the",
          "choirmaster.",
          "According",
          "to",
          "Gittith.",
          "A",
          "Psalm",
          "of",
          "the",
          "$son",
          "of",
          "Korah.",
          "How",
          "lovely",
          "is",
          "Your",
          "dwelling",
          "place,",
          "O",
          "$name_tag",
          "of",
          "Hosts!",
        ],
      },
      {
        verse_number: 2,
        words: [
          "My",
          "$person_other",
          "longs,",
          "even",
          "faints,",
          "for",
          "the",
          "courts",
          "of",
          "the",
          "$name_tag;",
          "my",
          "$heart_organ",
          "and",
          "my",
          "$meat",
          "cry",
          "out",
          "for",
          "the",
          "$sprout",
          "$fire.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Even",
          "the",
          "sparrow",
          "has",
          "found",
          "a",
          "$house,",
          "and",
          "the",
          "swallow",
          "a",
          "nest",
          "for",
          "herself,",
          "where",
          "she",
          "places",
          "her",
          "young",
          "near",
          "Your",
          "$altar,",
          "O",
          "$name_tag",
          "of",
          "Hosts,",
          "my",
          "$king",
          "and",
          "my",
          "$fire.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "$gift+smile",
          "are",
          "those",
          "who",
          "dwell",
          "in",
          "Your",
          "$house;",
          "they",
          "are",
          "ever",
          "praising",
          "You.",
          "Selah",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$gift+smile",
          "are",
          "$person",
          "whose",
          "strength",
          "is",
          "in",
          "You,",
          "whose",
          "$heart_organ",
          "are",
          "set",
          "on",
          "pilgrimage.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "As",
          "they",
          "pass",
          "through",
          "the",
          "Valley",
          "of",
          "Baca,",
          "they",
          "make",
          "it",
          "a",
          "place",
          "of",
          "springs;",
          "the",
          "autumn",
          "rain",
          "covers",
          "it",
          "with",
          "$speech+thumbs_up.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "They",
          "$walking",
          "from",
          "strength",
          "to",
          "strength,",
          "until",
          "each",
          "$eye",
          "before",
          "$fire",
          "in",
          "Zion.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "O",
          "$name_tag",
          "$fire",
          "of",
          "Hosts,",
          "$ear",
          "my",
          "$hands_praying;",
          "give",
          "ear,",
          "O",
          "$fire",
          "of",
          "Jacob.",
          "Selah",
        ],
      },
      {
        verse_number: 9,
        words: [
          "$eye",
          "our",
          "shield,",
          "O",
          "$fire,",
          "and",
          "look",
          "with",
          "favor",
          "on",
          "the",
          "face",
          "of",
          "Your",
          "$oil.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "For",
          "one",
          "$sun",
          "in",
          "Your",
          "courts",
          "is",
          "$thumbs_up",
          "than",
          "a",
          "thousand",
          "elsewhere.",
          "I",
          "would",
          "rather",
          "be",
          "a",
          "doorkeeper",
          "in",
          "the",
          "$house",
          "of",
          "my",
          "$fire",
          "than",
          "dwell",
          "in",
          "the",
          "tents",
          "of",
          "the",
          "wicked.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "the",
          "$name_tag",
          "$fire",
          "is",
          "a",
          "sun",
          "and",
          "a",
          "shield;",
          "the",
          "$name_tag",
          "$hands_giving",
          "grace",
          "and",
          "$star.",
          "He",
          "withholds",
          "$no_entry",
          "$thumbs_up",
          "thing",
          "from",
          "those",
          "who",
          "$walking",
          "with",
          "integrity.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "O",
          "$name_tag",
          "of",
          "Hosts,",
          "$gift+smile",
          "is",
          "the",
          "$person",
          "who",
          "trusts",
          "in",
          "You.",
        ],
      },
    ],
  };
  return chapter;
}
