export function bible_glyph_chapter_psa073() {
  "Psalm 73, drawn in pictures, so that a person who cannot read the letters can still follow it. A man admits he nearly gave up because the people who do wrong were doing so well, and then he goes into the temple and sees how it ends. Twenty eight lines.";
  "THE HEART IS THE SPINE OF THIS PSALM AND THE HEART IS DRAWN. Pure in heart in the first line, the imaginations of their hearts in the seventh, my heart was grieved in the twenty first, and in the twenty sixth my flesh and my heart may fail, but God is the strength of my heart. Five hearts land, and a reader following pictures can watch the argument move from a clean heart to a wild one to a broken one to a held one without reading a word. That is what these pages are supposed to do and it does not happen often, so it is worth naming when it does.";
  "AND THE ONE HEART THE POET CALLS HIS OWN IS THE ONE THAT FELL OFF. In vain I have kept my heart pure and washed my hands in innocence. The heart mark in that line belongs to a Hebrew word that the English swallows into the phrase, so it has no English word of its own to sit on and it cannot be drawn. The line comes out with nothing at all on it. Of six hearts in the psalm, the five about God and about the wicked survive and the sixth, which is the poet defending himself, does not.";
  "THE LINE EVERYBODY KNOWS IS ABOUT FEET, AND IT HAS NOTHING ON IT. But as for me, my feet had almost stumbled; my steps had nearly slipped. Feet, steps, stumbling, slipping, four chances, and the second line of this psalm is blank. There is a footprint picture here and it is used in this same chapter, fifteen lines later, on the word entered. So the mark for feet exists, is available, and does not arrive in the one line of the psalm that is about feet.";
  "THE WHOLE PSALM TURNS ON ONE WORD AND THERE IS NO PICTURE FOR IT. Until I entered the sanctuary of God, then I discerned their end. Everything before that line is the complaint and everything after it is the answer, and the hinge is the building he walks into. There is no drawing for a sanctuary or a temple. What the page gives is a footprint and the flame that means God, so a reader sees a man going somewhere and God being there, and never learns that he went into the house.";
  "PRIDE IS A NECKLACE AND VIOLENCE IS A COAT, AND THAT LINE IS BLANK TOO. Therefore pride is their necklace; a garment of violence covers them. The psalm dresses the wicked, which is the same move Zechariah 3 makes with the filthy clothes, and there is still no picture for a garment or for anything worn. Two lines later they set their mouths against the heavens and their tongues strut across the earth, and the sky, the walking and the earth all arrive while the mouths and the tongues do not, because the mouth picture is spent on the act of speaking.";
  "One mark was dropped in the seventh line. The draft put a pair of eyes on the word iniquity, and there is no eye in the English word, so it was left plain.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA073",
    reference: "Psalm 73",
    verses: [
      {
        verse_number: 1,
        words: [
          "A",
          "Psalm",
          "of",
          "Asaph.",
          "Surely",
          "$fire",
          "is",
          "$thumbs_up",
          "to",
          "Israel,",
          "to",
          "those",
          "who",
          "are",
          "pure",
          "in",
          "$heart_organ.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "But",
          "as",
          "for",
          "me,",
          "my",
          "feet",
          "had",
          "almost",
          "stumbled;",
          "my",
          "steps",
          "had",
          "nearly",
          "slipped.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "For",
          "I",
          "$heart_on_fire",
          "the",
          "arrogant",
          "when",
          "I",
          "$eye",
          "the",
          "prosperity",
          "of",
          "the",
          "$thumbs_down.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "They",
          "have",
          "no",
          "struggle",
          "in",
          "their",
          "$skull;",
          "their",
          "bodies",
          "are",
          "well",
          "fed.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "They",
          "are",
          "free",
          "of",
          "the",
          "burdens",
          "others",
          "carry;",
          "they",
          "are",
          "$no_entry",
          "afflicted",
          "like",
          "other",
          "$person.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "Therefore",
          "pride",
          "is",
          "their",
          "necklace;",
          "a",
          "garment",
          "of",
          "violence",
          "covers",
          "them.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "From",
          "their",
          "prosperity",
          "proceeds",
          "iniquity;",
          "the",
          "imaginations",
          "of",
          "their",
          "$heart_organ",
          "run",
          "wild.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "They",
          "mock",
          "and",
          "$mouth",
          "with",
          "$thumbs_down;",
          "with",
          "arrogance",
          "they",
          "$mouth",
          "oppression.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "They",
          "set",
          "their",
          "mouths",
          "against",
          "the",
          "$sky,",
          "and",
          "their",
          "tongues",
          "$walking",
          "across",
          "the",
          "$earth.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "So",
          "their",
          "$family",
          "$turn_back",
          "to",
          "this",
          "place",
          "and",
          "drink",
          "up",
          "$water",
          "in",
          "abundance.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "The",
          "wicked",
          "$speech,",
          "How",
          "can",
          "$fire",
          "$lightbulb?",
          "Does",
          "the",
          "Most",
          "High",
          "have",
          "knowledge?",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Behold,",
          "these",
          "are",
          "the",
          "$thumbs_down,",
          "$hourglass",
          "carefree",
          "as",
          "they",
          "increase",
          "their",
          "wealth.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "Surely",
          "in",
          "vain",
          "I",
          "have",
          "kept",
          "my",
          "heart",
          "pure",
          "and",
          "washed",
          "my",
          "hands",
          "in",
          "innocence.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "For",
          "I",
          "am",
          "afflicted",
          "all",
          "day",
          "long",
          "and",
          "punished",
          "every",
          "morning.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "If",
          "I",
          "had",
          "$speech,",
          "I",
          "will",
          "speak",
          "this",
          "way,",
          "then",
          "I",
          "would",
          "have",
          "betrayed",
          "Your",
          "$son.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "When",
          "I",
          "tried",
          "to",
          "$lightbulb",
          "all",
          "this,",
          "it",
          "was",
          "troublesome",
          "in",
          "my",
          "$eyes.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "until",
          "I",
          "$footprints",
          "the",
          "sanctuary",
          "of",
          "$fire,",
          "then",
          "I",
          "discerned",
          "their",
          "end.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "Surely",
          "You",
          "set",
          "them",
          "on",
          "slick",
          "ground;",
          "You",
          "cast",
          "them",
          "down",
          "into",
          "ruin.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "How",
          "suddenly",
          "they",
          "are",
          "laid",
          "waste,",
          "completely",
          "swept",
          "away",
          "$tray_out",
          "terrors!",
        ],
      },
      {
        verse_number: 20,
        words: [
          "Like",
          "one",
          "waking",
          "from",
          "a",
          "dream,",
          "so",
          "You,",
          "O",
          "$crown,",
          "awaken",
          "and",
          "despise",
          "their",
          "form.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "When",
          "my",
          "$heart_organ",
          "was",
          "grieved",
          "and",
          "I",
          "was",
          "pierced",
          "within,",
        ],
      },
      {
        verse_number: 22,
        words: [
          "I",
          "was",
          "senseless",
          "$no_entry",
          "$lightbulb;",
          "I",
          "was",
          "a",
          "brute",
          "beast",
          "before",
          "You.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "Yet",
          "I",
          "am",
          "always",
          "with",
          "You;",
          "You",
          "hold",
          "my",
          "right",
          "$hand.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "You",
          "guide",
          "me",
          "with",
          "Your",
          "counsel,",
          "and",
          "later",
          "$hand_receiving",
          "me",
          "in",
          "$star.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "Whom",
          "have",
          "I",
          "in",
          "$sky",
          "but",
          "You?",
          "And",
          "on",
          "$earth",
          "I",
          "desire",
          "$no_entry",
          "besides",
          "You.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "My",
          "flesh",
          "and",
          "my",
          "$heart_organ",
          "may",
          "fail,",
          "but",
          "$fire",
          "is",
          "the",
          "strength",
          "of",
          "my",
          "$heart_organ",
          "and",
          "my",
          "portion",
          "$hourglass.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "Those",
          "far",
          "$tray_out",
          "You",
          "will",
          "surely",
          "perish;",
          "You",
          "destroy",
          "all",
          "who",
          "are",
          "unfaithful",
          "to",
          "You.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "But",
          "as",
          "for",
          "me,",
          "it",
          "is",
          "$thumbs_up",
          "to",
          "draw",
          "near",
          "to",
          "$fire.",
          "I",
          "have",
          "made",
          "the",
          "$crown",
          "$name_tag",
          "my",
          "refuge,",
          "that",
          "I",
          "may",
          "proclaim",
          "all",
          "Your",
          "$tools.",
        ],
      },
    ],
  };
  return chapter;
}
