export function bible_glyph_chapter_psa116() {
  "Psalm 116, drawn in pictures, so that a person who cannot read the letters can still follow it. It is a man who was close to death, was answered, and now stands in public working out what he owes. Nineteen lines.";
  "THE THREE LINES THAT NEED THE NAME MOST ARE THE THREE THAT LOSE IT. The picture for the covenant name is also the picture for the word name, so a line saying I will call on the name of the LORD asks for the same tag twice in a row, meaning two different things, with nothing to tell them apart. That is the refrain of this psalm and it comes three times, in the fourth line, the thirteenth and the seventeenth. All the name marks in those three lines are put away, which is what Exodus 33, Exodus 34, Isaiah 43 and Psalm 34 all did before. Seven of the eighteen marks this psalm asked for are gone, and the three that are gone hardest are the ones the psalm is built around. Eleven remain, still nearly one a line, so the page is not short of the name. It is short of it in exactly the wrong places.";
  "THE CUP OF SALVATION HAS NO CUP. The thirteenth line is the one people know and the one this psalm gave to the Last Supper, and there is no picture for a cup here. Nor for the ropes of death in the third line, nor for Sheol beside them, nor for the vows paid twice over, nor for the sacrifice of thanksgiving. What a reader gets of the thirteenth line is a lift, a salvation and a call, all in letters.";
  "PRECIOUS IN THE SIGHT OF THE LORD IS THE DEATH OF HIS SAINTS, AND THE PAGE KEEPS ONLY THE DEATH. Eyes, a name tag and a skull. Precious is not drawn and neither are the saints, so the one line of this psalm that gets carved on gravestones arrives as a pair of eyes watching somebody die. The mark is not wrong. It is just that the two words that make the line bearable are the two with no picture.";
  "THE SERVANT AND THE SLAVE MEET IN ONE BREATH THIS TIME. The sixteenth line says I am Your servant twice, and the kneeling figure that draws it is the same mark Joshua 24 puts on the house of slavery in Egypt, because one Hebrew word covers both. Here the collision is tighter than it was there: the very next clause is You have broken my bonds. Two kneeling figures and then a set of chains coming off, and the page cannot say whether the kneeling is the thing he was rescued from or the thing he chose.";
  "THE ANCHOR IS THE PICTURE FOR BELIEVING, AND THAT BILL HAS NOT COME IN YET. The tenth line says I believed, and an anchor appears, as it does in forty six other chapters, from Abram believed the LORD onward. That is the same shape of fault as a lampstand meaning the Jews or a lightning bolt meaning strength: a picture named after an object, seated on an idea, so the object can never be drawn. It has cost nothing so far only because no chapter written yet contains a real anchor. Acts 27 does, four of them thrown off a ship in a storm, and on the day that chapter is drawn the debt falls due. Worth saying plainly, because faith was on the list of things this collection still needed a picture for, and it already has one.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "PSA116",
    reference: "Psalm 116",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "$heart_red",
          "the",
          "$name_tag,",
          "for",
          "He",
          "has",
          "$ear",
          "my",
          "$voice,",
          "my",
          "appeal",
          "for",
          "mercy.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Because",
          "He",
          "has",
          "inclined",
          "His",
          "ear",
          "to",
          "me,",
          "I",
          "will",
          "call",
          "on",
          "Him",
          "as",
          "long",
          "as",
          "I",
          "$sun.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "The",
          "ropes",
          "of",
          "$skull",
          "entangled",
          "me;",
          "the",
          "anguish",
          "of",
          "Sheol",
          "overcame",
          "me;",
          "I",
          "was",
          "confronted",
          "by",
          "trouble",
          "and",
          "sorrow.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "Then",
          "I",
          "called",
          "on",
          "the",
          "name",
          "of",
          "the",
          "LORD:",
          "O",
          "LORD,",
          "deliver",
          "my",
          "$person_other.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "The",
          "$name_tag",
          "is",
          "gracious",
          "and",
          "$ruler;",
          "our",
          "$fire",
          "is",
          "full",
          "of",
          "compassion.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "The",
          "$name_tag",
          "preserves",
          "the",
          "simplehearted;",
          "I",
          "was",
          "helpless,",
          "and",
          "He",
          "saved",
          "me.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$turn_back",
          "to",
          "your",
          "rest,",
          "O",
          "my",
          "$person_other,",
          "for",
          "the",
          "$name_tag",
          "has",
          "been",
          "good",
          "to",
          "you.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "For",
          "You",
          "have",
          "delivered",
          "my",
          "$person_other",
          "from",
          "$skull,",
          "my",
          "$eyes",
          "$tray_out",
          "tears,",
          "my",
          "feet",
          "from",
          "stumbling.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "I",
          "will",
          "$walking",
          "before",
          "the",
          "$name_tag",
          "in",
          "the",
          "$earth",
          "of",
          "the",
          "$sprout.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "I",
          "$anchor,",
          "therefore",
          "I",
          "$mouth,",
          "I",
          "am",
          "greatly",
          "afflicted.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "In",
          "my",
          "alarm",
          "I",
          "$speech,",
          "All",
          "$person",
          "are",
          "liars.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "How",
          "can",
          "I",
          "$turn_back",
          "the",
          "$name_tag",
          "for",
          "all",
          "His",
          "goodness",
          "to",
          "me?",
        ],
      },
      {
        verse_number: 13,
        words: [
          "I",
          "will",
          "lift",
          "the",
          "cup",
          "of",
          "salvation",
          "and",
          "call",
          "on",
          "the",
          "name",
          "of",
          "the",
          "LORD.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "I",
          "will",
          "fulfill",
          "my",
          "vows",
          "to",
          "the",
          "$name_tag",
          "in",
          "the",
          "presence",
          "of",
          "all",
          "His",
          "$family.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Precious",
          "in",
          "the",
          "$eyes",
          "of",
          "the",
          "$name_tag",
          "is",
          "the",
          "$skull",
          "of",
          "His",
          "saints.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "Truly,",
          "O",
          "$name_tag,",
          "I",
          "am",
          "Your",
          "$kneeling;",
          "I",
          "am",
          "Your",
          "$kneeling,",
          "the",
          "$son",
          "of",
          "Your",
          "maidservant.",
          "You",
          "have",
          "broken",
          "my",
          "bonds.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "I",
          "will",
          "offer",
          "to",
          "You",
          "a",
          "sacrifice",
          "of",
          "thanksgiving",
          "and",
          "call",
          "on",
          "the",
          "name",
          "of",
          "the",
          "LORD.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "I",
          "will",
          "fulfill",
          "my",
          "vows",
          "to",
          "the",
          "$name_tag",
          "in",
          "the",
          "presence",
          "of",
          "all",
          "His",
          "$family,",
        ],
      },
      {
        verse_number: 19,
        words: [
          "in",
          "the",
          "courts",
          "of",
          "the",
          "$house",
          "of",
          "the",
          "$name_tag,",
          "in",
          "your",
          "midst,",
          "O",
          "Jerusalem.",
          "Hallelujah!",
        ],
      },
    ],
  };
  return chapter;
}
