export function bible_glyph_chapter_hos11() {
  "The eleventh chapter of Hosea, drawn in pictures. God remembering teaching a child to walk, deciding out loud whether to give him up, and deciding not to. The chapter Matthew quotes in his second chapter, and a page where the decision is made out loud, in the middle of the verses, where the reader can watch it happen.";
  "THE CORDS OF KINDNESS IN THE FOURTH VERSE ARE LITERALLY THE CORDS OF A MAN. English says I led them with cords of kindness, with ropes of love. The word under kindness is the ordinary Hebrew word for a human being - the same word drawn wherever a person appears on these pages. So the line says human cords, and the rest of the verse explains why that matters: I lifted the yoke from their necks and bent down to feed them. A yoke and a rope are how an animal is led. The verse is insisting that this was not that, and it does it by putting the word man where the rope should be. English replaces the word with kindness, which is true to the sense and loses the picture. The mark keeps the picture.";
  "THE WORD UNDER WRATH IN THE NINTH VERSE IS THE ORDINARY WORD FOR A CITY. The line reads I will not come in wrath. The word under it is the one the root table draws as a city, so a city is what appears there, standing at the end of the verse where the English says wrath. This page does not argue about which reading is right; it shows which word is underneath. That is the whole use of a picture beside a translation - the reader can see the place where the two do not agree, without knowing any Hebrew and without being told.";
  "THE FIFTH VERSE USES ONE WORD FOR THE WRONG RETURN AND THE RIGHT ONE. Will they not return to the land of Egypt - and then, because they refused to repent. Return and repent there are the same Hebrew word, twice in one sentence, going in opposite directions: back to slavery, or back to God. English cannot use one word for both without sounding wrong, so it uses two and the joint disappears. Two identical marks in one line put it back. The same word turns up once more in the ninth verse, in I will not again destroy, where English writes it as the small word again.";
  "THE NINTH VERSE REFUSES FOUR TIMES. I will not execute the full fury of My anger. I will not again destroy Ephraim. For I am God and not man. And I will not come in wrath. Four negation marks in one verse, more than the whole rest of the chapter carries. This is the verse where the decision is made, and the decision is made entirely out of things that will not happen. The reason is the third of the four: not because Ephraim has improved, but because of what God is and a man is not.";
  "THE FIRST VERSE ENDS ON THE SON, AND THE SON COMES BACK NEAR THE END. Out of Egypt I called My son - the sentence Matthew quotes about a child brought back out of Egypt. The same mark returns in the tenth verse, where His children come trembling from the west. Hebrew says west there by saying sea, so that word is drawn as the sea, which is worth knowing: a language with the ocean on one side can use it for a direction, and the picture shows the reason the word is what it is.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "HOS11",
    reference: "Hosea 11",
    verses: [
      {
        verse_number: 1,
        words: [
          "When",
          "Israel",
          "was",
          "a",
          "child,",
          "I",
          "$heart_red",
          "him,",
          "and",
          "out",
          "of",
          "Egypt",
          "I",
          "called",
          "My",
          "$son.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "But",
          "the",
          "more",
          "I",
          "called",
          "Israel,",
          "the",
          "farther",
          "they",
          "$walking",
          "from",
          "Me.",
          "They",
          "sacrificed",
          "to",
          "the",
          "Baals",
          "and",
          "burned",
          "incense",
          "to",
          "carved",
          "images.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "It",
          "was",
          "I",
          "who",
          "taught",
          "Ephraim",
          "to",
          "walk,",
          "$hand_receiving",
          "them",
          "by",
          "the",
          "arms;",
          "but",
          "they",
          "$no_entry",
          "$lightbulb",
          "that",
          "it",
          "was",
          "I",
          "who",
          "healed",
          "them.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "I",
          "led",
          "them",
          "with",
          "cords",
          "of",
          "$person,",
          "with",
          "ropes",
          "of",
          "$heart_red.",
          "I",
          "lifted",
          "the",
          "yoke",
          "from",
          "their",
          "necks",
          "and",
          "bent",
          "down",
          "to",
          "feed",
          "them.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Will",
          "they",
          "$no_entry",
          "$turn_back",
          "to",
          "the",
          "$earth",
          "of",
          "Egypt",
          "and",
          "be",
          "$king",
          "by",
          "Assyria,",
          "because",
          "they",
          "refused",
          "to",
          "$turn_back?",
        ],
      },
      {
        verse_number: 6,
        words: [
          "A",
          "$sword",
          "will",
          "flash",
          "through",
          "their",
          "$city;",
          "it",
          "will",
          "destroy",
          "the",
          "bars",
          "of",
          "their",
          "gates",
          "and",
          "consume",
          "them",
          "in",
          "their",
          "own",
          "plans.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "My",
          "$family",
          "are",
          "bent",
          "on",
          "turning",
          "from",
          "Me.",
          "Though",
          "they",
          "call",
          "to",
          "the",
          "Most",
          "High,",
          "He",
          "will",
          "by",
          "$no_entry",
          "means",
          "exalt",
          "them.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "How",
          "could",
          "I",
          "$hands_giving",
          "you",
          "up,",
          "O",
          "Ephraim?",
          "How",
          "could",
          "I",
          "surrender",
          "you,",
          "O",
          "Israel?",
          "How",
          "could",
          "I",
          "$hands_giving",
          "you",
          "like",
          "Admah?",
          "How",
          "could",
          "I",
          "treat",
          "you",
          "like",
          "Zeboiim?",
          "My",
          "$heart_organ",
          "is",
          "turned",
          "within",
          "Me;",
          "My",
          "compassion",
          "is",
          "stirred.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "I",
          "will",
          "$no_entry",
          "$hammer",
          "the",
          "full",
          "fury",
          "of",
          "My",
          "anger;",
          "I",
          "will",
          "$no_entry",
          "$turn_back",
          "destroy",
          "Ephraim.",
          "For",
          "I",
          "am",
          "$fire",
          "and",
          "$no_entry",
          "$man_beard,",
          "the",
          "$sparkle",
          "One",
          "among",
          "you;",
          "and",
          "I",
          "will",
          "$no_entry",
          "$footprints",
          "in",
          "$city.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "They",
          "will",
          "walk",
          "after",
          "the",
          "$name_tag;",
          "He",
          "will",
          "roar",
          "like",
          "a",
          "lion.",
          "When",
          "He",
          "roars,",
          "His",
          "$son",
          "will",
          "come",
          "trembling",
          "from",
          "the",
          "$sea.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "They",
          "will",
          "come",
          "trembling",
          "like",
          "birds",
          "from",
          "Egypt,",
          "and",
          "like",
          "doves",
          "from",
          "the",
          "$earth",
          "of",
          "Assyria.",
          "Then",
          "I",
          "will",
          "settle",
          "them",
          "in",
          "their",
          "$house,",
          "declares",
          "the",
          "$name_tag.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "Ephraim",
          "surrounds",
          "Me",
          "with",
          "lies,",
          "the",
          "$house",
          "of",
          "Israel",
          "with",
          "deceit;",
          "but",
          "Judah",
          "still",
          "walks",
          "with",
          "$fire",
          "and",
          "is",
          "$anchor",
          "to",
          "the",
          "$sparkle",
          "One.",
        ],
      },
    ],
  };
  return chapter;
}
