export function bible_glyph_chapter_sng02() {
  "Song of Songs 2, drawn in pictures, so that a person who cannot read the letters can still follow it. It is the spring chapter of the love song, the one with the rose of Sharon and the little foxes and the winter being over. Seventeen lines, and it is the hardest test this collection has been given so far, because almost everything in it is a thing you can point at.";
  "THE FIRST LINE IS THE BEST KNOWN IN THE BOOK AND ARRIVES COMPLETELY BLANK. I am a rose of Sharon, a lily of the valleys. There is no rose here and no lily and no valley, so the opening line of the chapter carries not one mark. The fifteenth line, catch for us the foxes, the little foxes that ruin the vineyards, is the second most quoted and is also completely blank. Three of the seventeen lines carry nothing at all, and two of them are the two lines a reader would have come for.";
  "SIX KINDS OF ANIMAL ARE NAMED AND NONE OF THEM IS DRAWN, AND A DOVE IS SITTING IN THE COLLECTION UNUSED. Gazelles, does, a stag, turtledoves, a dove and foxes, ten mentions between them, and the page shows no animal anywhere. The dove is the sharp one. This collection owns a picture of a dove. It has never been drawn on any page of any chapter, not once, and the fourteenth line here begins O my dove and still cannot use it, because the picture is not seated on the Hebrew word. So the artwork and the word are both present, in the same chapter, and they never meet.";
  "THE GARDEN IS GONE AND ONE TREE IS LEFT STANDING. A rose, lilies three times, thorns, an apple tree, apples, a forest, fruit, raisins, flowers, a fig tree, figs, vines in blossom, and vineyards twice. Out of all of that the page draws a single tree, in the third line, and it is the generic word for trees of the forest rather than any of the named plants. A chapter that is mostly a garden comes through as one tree.";
  "BOTH HANDS OF THE EMBRACE GO UNDRAWN, WHICH IS THE SECOND TIME TONIGHT. The sixth line is his left hand is under my head and his right arm embraces me, and it carries no mark at all. Daniel 12 lost its two hands the same way a few hours ago. The reason is the same in both places and it is not that hands have no picture: Zechariah 4 draws hands twice, on the hands of Zerubbabel. Hebrew has a general word for a hand, which is what the picture is seated on, and separate words for the right hand and the left hand, which it is not. So a page can draw a hand in the abstract and loses both of them the moment the text says which one.";
  "WHAT THE PAGE KEEPS IS THE FEELING. Love is drawn three times, in the fourth line, the fifth and the seventh, and it is nearly the only thing in the chapter that survives intact. Everything the two of them can see is missing and the thing they cannot see is the clearest mark on the page. That is the opposite of what this collection usually does, and it happened by accident, because concrete nouns need a picture each and an abstract one only needs the picture it already has.";
  "The root table behind these marks is the same one every other chapter here uses, so a picture learnt on this page is the same picture on the next one.";
  let chapter = {
    chapter_code: "SNG02",
    reference: "Song of Songs 2",
    verses: [
      {
        verse_number: 1,
        words: [
          "I",
          "am",
          "a",
          "rose",
          "of",
          "Sharon,",
          "a",
          "lily",
          "of",
          "the",
          "valleys.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "Like",
          "a",
          "lily",
          "among",
          "the",
          "thorns",
          "is",
          "my",
          "darling",
          "among",
          "the",
          "$woman.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "Like",
          "an",
          "apple",
          "tree",
          "among",
          "the",
          "$tree",
          "of",
          "the",
          "forest",
          "is",
          "my",
          "beloved",
          "among",
          "the",
          "$son.",
          "I",
          "delight",
          "to",
          "sit",
          "in",
          "his",
          "shade,",
          "and",
          "his",
          "fruit",
          "is",
          "sweet",
          "to",
          "my",
          "taste.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "He",
          "has",
          "$footprints",
          "me",
          "to",
          "the",
          "$house",
          "of",
          "wine,",
          "and",
          "his",
          "banner",
          "over",
          "me",
          "is",
          "$heart_red.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "Sustain",
          "me",
          "with",
          "raisins,",
          "refresh",
          "me",
          "with",
          "apples,",
          "for",
          "I",
          "am",
          "faint",
          "with",
          "$heart_red.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "His",
          "left",
          "hand",
          "is",
          "under",
          "my",
          "head,",
          "and",
          "his",
          "right",
          "arm",
          "embraces",
          "me.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "I",
          "adjure",
          "you,",
          "O",
          "$woman",
          "of",
          "Jerusalem,",
          "by",
          "the",
          "gazelles",
          "and",
          "does",
          "of",
          "the",
          "field:",
          "Do",
          "not",
          "arouse",
          "or",
          "awaken",
          "$heart_red",
          "until",
          "the",
          "time",
          "is",
          "right.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "$voice!",
          "My",
          "beloved",
          "approaches.",
          "Look,",
          "here",
          "he",
          "$footprints,",
          "leaping",
          "across",
          "the",
          "$mountain,",
          "bounding",
          "over",
          "the",
          "hills.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "My",
          "beloved",
          "is",
          "like",
          "a",
          "gazelle",
          "or",
          "a",
          "young",
          "stag.",
          "Look,",
          "he",
          "stands",
          "behind",
          "our",
          "wall,",
          "gazing",
          "$tray_out",
          "the",
          "windows,",
          "peering",
          "$tray_out",
          "the",
          "lattice.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "My",
          "beloved",
          "$speech",
          "to",
          "me,",
          "Arise,",
          "my",
          "darling,",
          "my",
          "beautiful",
          "one,",
          "$walking",
          "with",
          "me.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "For",
          "now",
          "the",
          "winter",
          "is",
          "past;",
          "the",
          "rain",
          "is",
          "over",
          "and",
          "$walking.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "The",
          "flowers",
          "have",
          "$eye",
          "in",
          "the",
          "$earth,",
          "the",
          "season",
          "of",
          "singing",
          "has",
          "come,",
          "and",
          "the",
          "$voice",
          "of",
          "turtledoves",
          "is",
          "$ear",
          "in",
          "our",
          "$earth.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "The",
          "fig",
          "tree",
          "ripens",
          "its",
          "figs,",
          "and",
          "the",
          "blossoming",
          "vines",
          "$hands_giving",
          "their",
          "fragrance.",
          "Arise,",
          "$walking,",
          "my",
          "darling,",
          "my",
          "beautiful",
          "one,",
          "$walking",
          "with",
          "me.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "O",
          "my",
          "dove,",
          "in",
          "the",
          "clefts",
          "of",
          "the",
          "rock,",
          "in",
          "the",
          "crevices",
          "of",
          "the",
          "cliff,",
          "let",
          "me",
          "$eye",
          "your",
          "face,",
          "let",
          "me",
          "$ear",
          "your",
          "$voice;",
          "for",
          "your",
          "$voice",
          "is",
          "sweet",
          "and",
          "your",
          "countenance",
          "is",
          "lovely.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "Catch",
          "for",
          "us",
          "the",
          "foxes,",
          "the",
          "little",
          "foxes",
          "that",
          "ruin",
          "the",
          "vineyards,",
          "for",
          "our",
          "vineyards",
          "are",
          "in",
          "bloom.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "My",
          "beloved",
          "is",
          "mine",
          "and",
          "I",
          "am",
          "his;",
          "he",
          "$person+sheep",
          "among",
          "the",
          "lilies.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "Before",
          "the",
          "$sun",
          "breaks",
          "and",
          "the",
          "shadows",
          "flee,",
          "turn,",
          "my",
          "beloved,",
          "and",
          "be",
          "like",
          "a",
          "gazelle",
          "or",
          "a",
          "young",
          "stag",
          "on",
          "the",
          "$mountain",
          "of",
          "Bether.",
        ],
      },
    ],
  };
  return chapter;
}
