export function bible_glyph_chapter_psa136() {
  "The eighth picture Bible chapter written by hand: the whole of the hundred and thirty sixth psalm, in the shorthand a person types.";
  "IT IS THE FIRST ONE FROM THE OLD TESTAMENT, and that is the thing to notice about it rather than its share. Seven chapters of Greek were written before any Hebrew was, which made the Hebrew table a claim nobody had tested: a table can look complete and still draw nothing anybody wants to read. This is the test, and what it proves is the promise the two tables were built on - that a reader who learned the fire and the hourglass in John's letters can open a psalm and already be reading.";
  "EVERY CHAPTER OF THE OLD TESTAMENT WAS MEASURED, nine hundred and twenty nine of them, by the same reading that measured all two hundred and fifty four of the New. The psalm came back second at forty seven parts in a hundred, one behind a psalm of three verses, and was taken over it anyway. Three verses is not a chapter a reader can learn a language from; a share computed over twenty five words is a number about almost nothing.";
  "AND ITS REAL SHARE IS HIGHER THAN THE NUMBER SAYS. Twenty six of its undrawn words are the interlinear's own mark for the elided refrain rather than words of the psalm at all. Discount them and the psalm is drawn a hair over half. This is worth stating because the survey cannot know it: a share is a count of what a table draws, and a source that writes some of its text as an ellipsis makes the denominator lie in exactly one direction. Nothing here is wrong; it just reads low.";
  "THE REFRAIN IS THE WHOLE CASE FOR THIS PSALM. Twenty six verses end in the same four words and two of the four are pictures - the gift and the hourglass, in that order, every single time. A symbol language has to be taught, and nothing teaches like a line a reader meets twenty six times in one sitting. A reader who does not know the gift on the first verse knows it by the sixth, and they were never told; they were drilled.";
  "IT COST ONE NEW PICTURE AND PICKED UP TWO FREE ONES. The raised hands were bought for the giving of thanks, which opens the psalm three times and closes it once. The water and the light were already drawn for the Greek and simply had no seat in the Hebrew table yet, so they cost nothing; they are in this chapter once each, and were taken because we were already in the table rather than because the psalm was short of them.";
  "THE SUN AND THE DAY STAND SIDE BY SIDE IN THE EIGHTH VERSE AND ONLY ONE OF THEM IS DRAWN. The table seats the sun's picture on yom, the word for a day, and the psalm's word for the sun itself has no seat, so the verse reads the sun to rule the picture-of-a-sun. It looks like a mistake and it is the clearest lesson on the page: the marks sit on the Hebrew words and never on the English ones, and here the English says sun twice while the Hebrew says two different things. Fixing it by drawing the sun as well would have made the two words identical, which is the one thing this verse must not do.";
  "THE STARS ARE LEFT IN ENGLISH ON PURPOSE, in the ninth verse, and the star is one of the pictures this Bible already has. It is seated on kabod, the weight and glory of God, and a psalm that put it on the stars in the sky would spend the reader's understanding of the word to save one blank. A wrong mark is worse than no mark, and a mark that is right elsewhere is the easiest wrong one to write.";
  "THE CREATURE OF THE TWENTY FIFTH VERSE IS DRAWN AS MEAT AND IT SITS BADLY. The Hebrew is basar, all flesh, and the table draws basar as meat - which is right for a sacrifice and reads, beside the word food in the same clause, as though God fed every steak. The author does not get to pick a different picture for one passage, because a word drawn one way in one chapter and another way in the next breaks the only promise a reader learning these pictures has. So it is drawn as the table says and named here instead: this verse is the evidence that basar wants a second seat, for the living creature as against the flesh of one.";
  "THE PROPER NAMES ARE ALL LEFT IN ENGLISH - Egypt, Israel, Pharaoh, Sihon, Og, Bashan, the Amorites, the Red Sea. That is not a gap to fill later. A name points at one person or one place and a picture of it would be a portrait, which is the largest claim a picture can make and the one this table refuses everywhere. The kings around them are drawn, because king is a word rather than a name.";
  "THE GOD OF GODS AND THE LORD OF LORDS ARE EACH ONE PICTURE TWICE OVER, in the second and third verses, because each is one Hebrew word twice over. English writes a plural and a singular; the Hebrew writes the same word in both slots. Drawing it the same way both times is what shows the construction, and it is the sort of thing a reader sees on a picture page and would never see in a translation.";
  let chapter = {
    chapter_code: "PSA136",
    reference: "Psalm 136",
    verses: [
      {
        verse_number: 1,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$name_tag,",
          "for",
          "He",
          "is",
          "$thumbs_up.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$fire",
          "of",
          "$fire.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$crown",
          "of",
          "$crown.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "He",
          "alone",
          "$hammer",
          "great",
          "wonders.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "By",
          "His",
          "insight",
          "He",
          "$hammer",
          "the",
          "$sky.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "He",
          "spread",
          "out",
          "the",
          "$earth",
          "upon",
          "the",
          "$water.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "He",
          "$hammer",
          "the",
          "great",
          "$light.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "the",
          "sun",
          "to",
          "rule",
          "the",
          "$sun.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "the",
          "moon",
          "and",
          "stars",
          "to",
          "govern",
          "the",
          "night.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 10,
        words: [
          "He",
          "struck",
          "down",
          "the",
          "firstborn",
          "of",
          "Egypt.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "and",
          "brought",
          "Israel",
          "out",
          "from",
          "among",
          "them.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "with",
          "a",
          "mighty",
          "$hand",
          "and",
          "an",
          "outstretched",
          "arm.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "He",
          "divided",
          "the",
          "Red",
          "Sea",
          "in",
          "two.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 14,
        words: [
          "and",
          "led",
          "Israel",
          "through",
          "the",
          "midst.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 15,
        words: [
          "but",
          "swept",
          "Pharaoh",
          "and",
          "his",
          "army",
          "into",
          "the",
          "Red",
          "Sea.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 16,
        words: [
          "He",
          "$walking",
          "His",
          "$family",
          "through",
          "the",
          "wilderness.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "He",
          "struck",
          "down",
          "great",
          "$king.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "and",
          "slaughtered",
          "mighty",
          "$king.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "Sihon",
          "$king",
          "of",
          "the",
          "Amorites.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "and",
          "Og",
          "$king",
          "of",
          "Bashan.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "and",
          "He",
          "$hands_giving",
          "their",
          "$earth",
          "as",
          "an",
          "inheritance.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "a",
          "heritage",
          "to",
          "His",
          "$kneeling",
          "Israel.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "He",
          "remembered",
          "us",
          "in",
          "our",
          "low",
          "estate.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "and",
          "freed",
          "us",
          "from",
          "our",
          "enemies.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "He",
          "$hands_giving",
          "food",
          "to",
          "every",
          "$meat.",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "$hands_raised",
          "to",
          "the",
          "$fire",
          "of",
          "$sky!",
          "His",
          "$gift",
          "endures",
          "$hourglass.",
        ],
      },
    ],
  };
  return chapter;
}
