export function bible_glyph_chapter_gen25() {
  "The twenty fifth chapter of Genesis, drawn in pictures. Abraham dies and his two sons bury him together, and then Isaacs twin boys are born fighting, grow up loved by one parent each, and one of them sells his birthright for a bowl of stew.";
  "THE GREAT WILL SERVE THE SMALL. The answer Rebekah gets in the twenty third verse is three Hebrew words at the end: great, serve, small. Everything before it comes in pairs - two nations, two peoples, one people stronger than the other. Then three words that turn the ordinary order of a family upside down before either boy has been born.";
  "HIS NAME IS THE PART OF HIS BROTHER HE WAS HOLDING. The twenty sixth verse says the second twin came out with his hand gripping the heel of the first, and so they called him Jacob. The Hebrew word for heel and the name Jacob are built from the same letters. He is named after a grab, and the chapter has him make another one before it ends.";
  "ONE PARENT LOVES WITH A REASON AND THE OTHER JUST LOVES. The twenty eighth verse uses the Hebrew word for love twice. For Isaac it is a plain past tense with a reason attached - he loved Esau, because game was in his mouth. For Rebekah it is the form that means a thing going on continuously, and no reason is given at all. She loved Jacob. The verse does not say why, and it never says why.";
  "HE ASKS FOR THE RED RED AND GETS A NATIONS NAME FROM IT. In the thirtieth verse Esau does not have a word for the food. He says let me gulp some of the red, the red, using the same Hebrew word twice, and the verb he uses is the one for feeding an animal. The verse ends by telling you that this is why he is called Edom, which is that same red word. A man too hungry to name his dinner names a whole people.";
  "FIVE VERBS AND THE LAST ONE IS THE VERDICT. The last verse is five Hebrew verbs one after another: he ate, and he drank, and he got up, and he went, and he despised his birthright. There is no description in it and no explanation. The chapter reports what he did four times over and then tells you what it was.";
  "TWO BROTHERS BURY THEIR FATHER TOGETHER. The ninth verse says Isaac and Ishmael buried Abraham - the two sons who were split apart four chapters earlier, standing at one grave. Genesis does the same thing again at the end of chapter thirty five, where Esau and Jacob bury Isaac. Both pairs of brothers were pulled apart by a birthright, and both of them come back for the burial.";
  "The glyph a word gets is taken from the root table and never chosen here, so a word drawn one way in this chapter is drawn that way in every chapter.";
  let chapter = {
    chapter_code: "GEN25",
    reference: "Genesis 25",
    verses: [
      {
        verse_number: 1,
        words: [
          "Abraham",
          "$hand_receiving",
          "another",
          "$woman,",
          "$name_tag",
          "$proper_name$Keturah.",
        ],
      },
      {
        verse_number: 2,
        words: [
          "She",
          "bore",
          "him",
          "$proper_name$Zimran,",
          "$proper_name$Jokshan,",
          "$proper_name$Medan,",
          "$proper_name$Midian,",
          "$proper_name$Ishbak",
          "and",
          "$proper_name$Shuah.",
        ],
      },
      {
        verse_number: 3,
        words: [
          "$proper_name$Jokshan",
          "was",
          "the",
          "father",
          "of",
          "$proper_name$Sheba",
          "and",
          "$proper_name$Dedan.",
          "The",
          "$son",
          "of",
          "$proper_name$Dedan",
          "were",
          "the",
          "$proper_name$Asshurites,",
          "the",
          "$proper_name$Letushites",
          "and",
          "the",
          "$proper_name$Leummites.",
        ],
      },
      {
        verse_number: 4,
        words: [
          "The",
          "$son",
          "of",
          "$proper_name$Midian",
          "were",
          "$proper_name$Ephah,",
          "$proper_name$Epher,",
          "$proper_name$Hanoch,",
          "$proper_name$Abida",
          "and",
          "$proper_name$Eldaah.",
          "All",
          "these",
          "were",
          "$son",
          "of",
          "$proper_name$Keturah.",
        ],
      },
      {
        verse_number: 5,
        words: [
          "$proper_name$Abraham",
          "$hands_giving",
          "everything",
          "he",
          "owned",
          "to",
          "$proper_name$Isaac.",
        ],
      },
      {
        verse_number: 6,
        words: [
          "But",
          "while",
          "he",
          "was",
          "still",
          "$sprout,",
          "$proper_name$Abraham",
          "$hands_giving",
          "gifts",
          "to",
          "the",
          "$son",
          "of",
          "his",
          "servants",
          "and",
          "sent",
          "them",
          "$hand_sending",
          "from",
          "$proper_name$Isaac",
          "his",
          "$son,",
          "to",
          "the",
          "$earth",
          "of",
          "the",
          "east.",
        ],
      },
      {
        verse_number: 7,
        words: [
          "$proper_name$Abraham",
          "$sprout",
          "a",
          "hundred",
          "and",
          "seventy",
          "five",
          "$sun.",
        ],
      },
      {
        verse_number: 8,
        words: [
          "Then",
          "he",
          "breathed",
          "his",
          "last",
          "and",
          "$skull",
          "at",
          "a",
          "$thumbs_up",
          "old",
          "age,",
          "old",
          "and",
          "full,",
          "and",
          "he",
          "was",
          "gathered",
          "to",
          "his",
          "$family.",
        ],
      },
      {
        verse_number: 9,
        words: [
          "His",
          "$son",
          "$proper_name$Isaac",
          "and",
          "$proper_name$Ishmael",
          "buried",
          "him",
          "in",
          "the",
          "$cave",
          "of",
          "$proper_name$Machpelah,",
          "in",
          "the",
          "$field",
          "of",
          "$proper_name$Ephron",
          "the",
          "$son",
          "of",
          "$proper_name$Zohar",
          "the",
          "$proper_name$Hittite,",
          "near",
          "$proper_name$Mamre,",
        ],
      },
      {
        verse_number: 10,
        words: [
          "the",
          "$field",
          "$proper_name$Abraham",
          "had",
          "bought",
          "from",
          "the",
          "$son",
          "of",
          "Heth.",
          "There",
          "$proper_name$Abraham",
          "was",
          "buried",
          "with",
          "$proper_name$Sarah",
          "his",
          "$woman.",
        ],
      },
      {
        verse_number: 11,
        words: [
          "After",
          "the",
          "$skull",
          "of",
          "Abraham,",
          "$fire",
          "$speech+thumbs_up",
          "$proper_name$Isaac",
          "his",
          "$son,",
          "and",
          "$proper_name$Isaac",
          "lived",
          "near",
          "Beer",
          "Lahai",
          "Roi.",
        ],
      },
      {
        verse_number: 12,
        words: [
          "This",
          "is",
          "the",
          "account",
          "of",
          "$proper_name$Ishmael",
          "the",
          "$son",
          "of",
          "$proper_name$Abraham,",
          "whom",
          "$proper_name$Hagar",
          "the",
          "$proper_name$Egyptian,",
          "the",
          "servant",
          "of",
          "Sarah,",
          "bore",
          "to",
          "$proper_name$Abraham.",
        ],
      },
      {
        verse_number: 13,
        words: [
          "These",
          "are",
          "the",
          "$name_tag",
          "of",
          "the",
          "$son",
          "of",
          "$proper_name$Ishmael",
          "in",
          "the",
          "order",
          "they",
          "were",
          "born:",
          "$proper_name$Nebaioth",
          "the",
          "firstborn,",
          "then",
          "$proper_name$Kedar,",
          "$proper_name$Adbeel,",
          "$proper_name$Mibsam,",
        ],
      },
      {
        verse_number: 14,
        words: ["$proper_name$Mishma,", "$proper_name$Dumah,", "$proper_name$Massa,"],
      },
      {
        verse_number: 15,
        words: ["$proper_name$Hadad,", "$proper_name$Tema,", "$proper_name$Jetur,", "$proper_name$Naphish", "and", "$proper_name$Kedemah."],
      },
      {
        verse_number: 16,
        words: [
          "These",
          "were",
          "the",
          "$son",
          "of",
          "$proper_name$Ishmael,",
          "and",
          "these",
          "were",
          "their",
          "$name_tag",
          "by",
          "their",
          "villages",
          "and",
          "their",
          "camps,",
          "twelve",
          "leaders",
          "of",
          "their",
          "tribes.",
        ],
      },
      {
        verse_number: 17,
        words: [
          "$proper_name$Ishmael",
          "$sprout",
          "a",
          "hundred",
          "and",
          "thirty",
          "seven",
          "years.",
          "Then",
          "he",
          "breathed",
          "his",
          "last",
          "and",
          "$skull,",
          "and",
          "he",
          "was",
          "gathered",
          "to",
          "his",
          "$family.",
        ],
      },
      {
        verse_number: 18,
        words: [
          "They",
          "settled",
          "from",
          "$proper_name$Havilah",
          "to",
          "$proper_name$Shur,",
          "near",
          "the",
          "border",
          "of",
          "$proper_name$Egypt,",
          "as",
          "you",
          "$footprints",
          "toward",
          "$proper_name$Asshur.",
          "They",
          "lived",
          "in",
          "hostility",
          "toward",
          "all",
          "their",
          "$brother.",
        ],
      },
      {
        verse_number: 19,
        words: [
          "This",
          "is",
          "the",
          "account",
          "of",
          "$proper_name$Isaac",
          "the",
          "$son",
          "of",
          "$proper_name$Abraham.",
          "$proper_name$Abraham",
          "was",
          "the",
          "father",
          "of",
          "$proper_name$Isaac.",
        ],
      },
      {
        verse_number: 20,
        words: [
          "$proper_name$Isaac",
          "was",
          "forty",
          "$son",
          "old",
          "when",
          "he",
          "$hand_receiving",
          "$proper_name$Rebekah,",
          "the",
          "$woman",
          "of",
          "$proper_name$Bethuel",
          "the",
          "$proper_name$Aramean",
          "from",
          "Paddan",
          "Aram,",
          "the",
          "$sister",
          "of",
          "$proper_name$Laban",
          "the",
          "$proper_name$Aramean,",
          "as",
          "his",
          "$woman.",
        ],
      },
      {
        verse_number: 21,
        words: [
          "Isaac",
          "prayed",
          "to",
          "$i_am",
          "for",
          "his",
          "$woman,",
          "because",
          "she",
          "was",
          "barren.",
          "$i_am",
          "heard",
          "him,",
          "and",
          "$proper_name$Rebekah",
          "his",
          "$woman",
          "conceived.",
        ],
      },
      {
        verse_number: 22,
        words: [
          "But",
          "the",
          "$son",
          "struggled",
          "inside",
          "her,",
          "and",
          "she",
          "$speech,",
          "Why",
          "is",
          "this",
          "happening",
          "to",
          "me?",
          "So",
          "she",
          "$walking",
          "to",
          "ask",
          "$i_am.",
        ],
      },
      {
        verse_number: 23,
        words: [
          "$i_am",
          "$speech",
          "to",
          "her,",
          "Two",
          "$map",
          "are",
          "in",
          "your",
          "womb,",
          "and",
          "two",
          "peoples",
          "from",
          "inside",
          "you",
          "will",
          "be",
          "separated.",
          "One",
          "people",
          "will",
          "be",
          "stronger",
          "than",
          "the",
          "other,",
          "and",
          "the",
          "greater",
          "will",
          "$kneeling",
          "the",
          "smaller.",
        ],
      },
      {
        verse_number: 24,
        words: [
          "When",
          "the",
          "$sun",
          "came",
          "for",
          "her",
          "to",
          "give",
          "birth,",
          "there",
          "were",
          "twins",
          "in",
          "her",
          "womb.",
        ],
      },
      {
        verse_number: 25,
        words: [
          "The",
          "first",
          "came",
          "out",
          "red,",
          "$hair",
          "all",
          "over",
          "like",
          "a",
          "coat,",
          "so",
          "they",
          "$name_tag",
          "him",
          "$proper_name$Esau.",
        ],
      },
      {
        verse_number: 26,
        words: [
          "After",
          "that",
          "his",
          "$brother",
          "came",
          "out,",
          "with",
          "his",
          "$hand",
          "gripping",
          "the",
          "heel",
          "of",
          "Esau,",
          "so",
          "he",
          "was",
          "$name_tag",
          "$proper_name$Jacob.",
          "Isaac",
          "was",
          "sixty",
          "$son",
          "old",
          "when",
          "they",
          "were",
          "born.",
        ],
      },
      {
        verse_number: 27,
        words: [
          "The",
          "boys",
          "grew",
          "up.",
          "$proper_name$Esau",
          "became",
          "a",
          "$lightbulb",
          "hunter,",
          "a",
          "$man_beard",
          "of",
          "the",
          "$field,",
          "while",
          "$proper_name$Jacob",
          "was",
          "a",
          "quiet",
          "$man_beard",
          "who",
          "stayed",
          "among",
          "the",
          "$tent.",
        ],
      },
      {
        verse_number: 28,
        words: [
          "$proper_name$Isaac",
          "$heart_red",
          "$proper_name$Esau,",
          "because",
          "the",
          "game",
          "was",
          "in",
          "his",
          "mouth,",
          "but",
          "$proper_name$Rebekah",
          "$heart_red",
          "$proper_name$Jacob.",
        ],
      },
      {
        verse_number: 29,
        words: [
          "One",
          "day",
          "while",
          "Jacob",
          "was",
          "cooking",
          "stew,",
          "$proper_name$Esau",
          "$footprints",
          "in",
          "$tray_out",
          "of",
          "the",
          "$field",
          "and",
          "he",
          "was",
          "worn",
          "out.",
        ],
      },
      {
        verse_number: 30,
        words: [
          "He",
          "$speech",
          "to",
          "$proper_name$Jacob,",
          "Let",
          "me",
          "gulp",
          "some",
          "of",
          "that",
          "red,",
          "the",
          "red,",
          "for",
          "I",
          "am",
          "worn",
          "out.",
          "That",
          "is",
          "why",
          "he",
          "was",
          "$name_tag",
          "$proper_name$Edom.",
        ],
      },
      {
        verse_number: 31,
        words: [
          "$proper_name$Jacob",
          "$speech,",
          "Sell",
          "me",
          "your",
          "birthright",
          "$sun.",
        ],
      },
      {
        verse_number: 32,
        words: [
          "$proper_name$Esau",
          "$speech,",
          "Look,",
          "I",
          "am",
          "$walking",
          "to",
          "$skull.",
          "What",
          "good",
          "is",
          "a",
          "birthright",
          "to",
          "me?",
        ],
      },
      {
        verse_number: 33,
        words: [
          "$proper_name$Jacob",
          "$speech,",
          "Swear",
          "to",
          "me",
          "$sun.",
          "So",
          "he",
          "swore",
          "to",
          "him",
          "and",
          "sold",
          "his",
          "birthright",
          "to",
          "$proper_name$Jacob.",
        ],
      },
      {
        verse_number: 34,
        words: [
          "Then",
          "Jacob",
          "$hands_giving",
          "$proper_name$Esau",
          "$bread",
          "and",
          "lentil",
          "stew.",
          "He",
          "ate,",
          "and",
          "he",
          "drank,",
          "and",
          "he",
          "got",
          "up,",
          "and",
          "he",
          "$walking,",
          "and",
          "he",
          "despised",
          "his",
          "birthright.",
        ],
      },
    ],
  };
  return chapter;
}
