export function bless_sidewalk_depth() {
  "How many tiles deep the pavement in front of a block is.";
  "Two, and the number is set by the crowd rather than by taste. One tile wide, two people";
  "walking towards each other have nowhere to go but the way they came, so every meeting";
  "ends with somebody turning round. Two is enough for two people to pass - and this street";
  "does not hold two people, it holds a block's worth, because that is what the ladder says";
  "a block is.";
  "Measured on the built block: at two deep the pavement ran between 74 and 95 per cent";
  "occupied, and the player standing on it had NO free tile beside them in two runs out of";
  "five and one at best. A street the player cannot take a step down is not a street.";
  "Three was enough for a while, and then it was not, and what changed was not this number";
  "but who is out on the pavement. A walker may be anywhere on the pavement and nowhere off";
  "it, so raising the share of people who walk moves the whole rise onto these tiles. At four";
  "in five walking, three deep was measured with 54 people standing on 65 pavement tiles -";
  "77 per cent - and 38 of those 54, seven in ten, had no free tile beside them in any";
  "direction at all. They were told to step every beat and the step was refused every time,";
  "so the street the player watched was a crowd of people holding still. That is the failure";
  "this number answers, and it is the one a player reports: hardly anybody is walking.";
  "Four leaves the same 54 people on 84 tiles - 64 per cent - and only 14 of them, one in";
  "four, with nowhere to go. Five was measured too, and it is better again but barely: 55 per";
  "cent occupied and 18 per cent stuck. Almost the whole gain is in the step from three to";
  "four, and the last few points are not worth what they cost.";
  "Every measurement above was taken when a block held SIXTY. The ladder then cut a building";
  "from four households to two, because widening the pavement had run out of room to widen";
  "into while the street still read as packed; that put a block at thirty, one tile in three";
  "and about one person in twenty stuck, and the player who had reported the jam then said";
  "the street wanted a few more people. It settled at three households, forty-five to a";
  "block: four tiles in seven, about one person in seven momentarily boxed in.";
  "So this number was doing what the paragraph above hoped it would, and then the street";
  "changed under it. A building went from three squares across to seven, so that every door";
  "has wall on both sides of it and can be counted, and that took a block from nineteen";
  "tiles long to thirty-nine while it went on holding the same forty-five people. Three deep";
  "then measured thirty-eight per cent occupied, which is the thin street the player had";
  "already asked to have the crowd put back into.";
  "Two deep puts those forty-five on seventy-eight tiles, fifty-eight per cent, with about";
  "one person in five momentarily boxed in. That is where the street stood when it was last";
  "tuned by hand and the player said it was right: nineteen long by four deep, fifty-nine";
  "per cent and one in six. So this is not a new setting, it is the same crowd at the same";
  "closeness on a block twice as long.";
  "The paragraph above ruling two deep out was measured on a block nineteen tiles long,";
  "where two deep ran seventy-four to ninety-five per cent full. The block being twice as";
  "long is what answers it, and not a change of mind: the depth on its own never meant";
  "anything, the tiles per person did, and that is what was being read off it both times.";
  "Not wider than it has to be. Thirty-nine long against two deep is twenty to one and reads";
  "as a line, and a line is what makes some people plainly walking one way and some the";
  "other; wide enough to wander about on, it would read as a square with houses on one side.";
  let depth = 2;
  return depth;
}
