import { arguments_assert } from "./arguments_assert.mjs";
import { property_get } from "./property_get.mjs";
import { list_get } from "./list_get.mjs";
import { bless_building_shape } from "./bless_building_shape.mjs";
import { divide_floor } from "./divide_floor.mjs";
import { subtract } from "./subtract.mjs";
import { add } from "./add.mjs";
import { greater_than_equal } from "./greater_than_equal.mjs";
import { less_than_equal } from "./less_than_equal.mjs";
import { and } from "./and.mjs";
import { list_filter } from "./list_filter.mjs";
export function bless_building_family_tiles(building, index) {
  arguments_assert(arguments, 2);
  ("One family's share of a building, given as the ground it covers - the slab of front");
  ("their door sits in the middle of, and the roof behind it.");
  ("The building divides into these EXACTLY, one slab per family and nothing left over, and");
  ("that is what this is for. A family that has been prayed for lights its own share, so a");
  ("house with two of its three families done is two thirds lit and can be read as two");
  ("thirds done from across the street. Lighting only the door said the same thing in a");
  ("mark too small to see and too easily mistaken for the door simply being drawn.");
  ("A SLAB rather than a single square, because a lit slab reads as a part of the house and");
  ("a lit square reads as a mark hung on its wall. The player is being told how much of");
  ("this house is done, and a third of a house is a third of the shape of it.");
  ("The slab is found by ASKING the building where it put this family's door and taking the");
  ("squares either side of it, rather than by counting along the front. How wide a slab is");
  ("and where the doors fall are both decided by the shape of a building, and a sum done");
  ("here would be a second copy of that decision - free to go quietly wrong the next time");
  ("either number changed, with the slabs still drawn and still the right size, just no");
  ("longer over the doors they belong to.");
  ("It takes the whole DEPTH of the building and not only the front row. The roof behind a");
  ("family is that family's roof, and lighting the wall while leaving the roof dark would");
  ("draw a lit stripe along the bottom of a house rather than a lit part of a house.");
  let tiles = property_get(building, "tiles");
  let doorways = property_get(building, "doorways");
  let door = list_get(doorways, index);
  let x_door = property_get(door, "x");
  let shape = bless_building_shape();
  let slab = property_get(shape, "family_width");
  let reach = divide_floor(slab, 2);
  let x_least = subtract(x_door, reach);
  let x_most = add(x_door, reach);
  function tile_in_slab(tile) {
    let x = property_get(tile, "x");
    let after = greater_than_equal(x, x_least);
    let before = less_than_equal(x, x_most);
    let within = and(after, before);
    return within;
  }
  let share = list_filter(tiles, tile_in_slab);
  return share;
}
