import { arguments_assert } from "./arguments_assert.mjs";
import { bless_family_width } from "./bless_family_width.mjs";
export function bless_building_shape() {
  arguments_assert(arguments, 0);
  ("What every building looks like from above except for how wide it is - how many tiles deep it stands, and how much of the front belongs to each family living behind it.");
  ("They belong together because they are one proportion rather than three settings. A building wider than it is deep reads as a frontage on a street, which is what a person walking past actually sees; make it square and the row stops looking like buildings and starts looking like a wall with notches in it.");
  ("The WIDTH is not here any more, and that is the whole of what changed. Buildings have two, three or four doors depending on where they stand in the row, so there is no one width for all of them; a building is asked for its own, and what is left here is everything that is the same whichever building it is.");
  ("THE ALLEY IS NO LONGER HERE, and what moved it out is that it stopped being one number. Every gap between two buildings was a single tile, so a row of varied fronts stood behind a row of identical stripes; each building is now asked how wide the gap on its east side is, off the same run of numbers that says how many doors it has. What an alley is FOR has not changed - it is what stops the row being one long building, and it stays too narrow to be somewhere anybody goes, because a gap you could walk down would be a second street and this game has one.");
  ("It belongs with the buildings rather than here for a reason worth keeping. This is the picture of a house, and a picture of a house is the same picture wherever it stands; how far it stands from its neighbour is a fact about the road it stands on. Left here, one number would have had to answer for every gap on every street at once, which is exactly what it was doing.");
  ("A family owns a SLAB of the front three squares wide with its own door in the middle of it, and a building is exactly its families laid side by side. Three is the smallest odd width there is above one, and it has to be odd for the door to sit in the middle of it rather than at one edge.");
  ("Everything about a width falls out of that. A width is the slab times the number of families, so a building divides into them EXACTLY with nothing left over - which is what lets a finished family light its own share of the house instead of only its door, and what makes a half-lit street readable at a glance as how far the praying has got. A width with a spare square in it would leave a strip belonging to nobody, permanently dark or else lit by whoever happened to be next to it.");
  ("Every door then has wall on both sides of it without that having to be arranged: the outer squares of a slab are wall, so a door at the very end of a building still has its own square of wall between it and the alley. Two families side by side put two squares of wall between their doors, one belonging to each of them, and that is the line where one home ends and the next begins.");
  ("Written the other way round - a width chosen and the doors fitted into it - the two numbers would drift the first time a building held a different number of homes, and the front row would go on being drawn while quietly no longer saying anything true about who lives behind it.");
  ("The depth is FOUR, and it is the same four whether a building has one floor or two. What varies is how much of it is wall and how much is roof: a two-storey house shows two bands of wall with a single strip of roof behind them, and a one-storey house shows one band of wall with a broad roof behind it. Seen from above that is the whole of what makes one house look taller than the next.");
  ("The slot is a row deeper than the tallest house that stands in it, and that spare row is the whole reason for the number. A house is one row of roof with one row of wall for each floor, so a two-storey house is three rows tall - and in a three-row slot there was exactly one place it could stand. Every tall house on every street stood flush against the front, and a row that was meant to look drawn stood as though it had been ruled. Four rows gives a tall house two positions and a low house three, so a set-back is a real draw for every kind of house rather than only for the short ones.");
  ("It WAS four once before, for a different reason, and was taken back to three. That attempt was trying to give a downstairs family a row of its own yard in front of its door, and it was a wrong answer to a real question: the view is front-and-top, the ceiling of the first floor is the floor of the second and is covered by it, so the only surface a downstairs family shows IS the single row its door is in. That is still true. This four is not that four - the spare row is not given to anybody, it is room for the house to move in - and the ground it leaves over is grass like the rest of the lawn.");
  ("It does not vary, and that is a decision rather than an oversight. Buildings of different depths would leave the backs of the row ragged and would make every alley between them a different length, which is a great deal of arithmetic bought for a difference nobody standing on the pavement is looking at. The height is read off the wall, and the wall is where it is drawn.");
  ("It was TWO while every building had one floor, and two was right then: only the front row was wall, and one row of roof was enough to say the building had a top without eating the street. A second floor needs a second band of wall to be drawn in, and it may not take the roof strip to get it - a house with no roof showing at all reads as a wall standing on the pavement rather than as a building.");
  let family_width = bless_family_width();
  let shape = {
    depth: 4,
    family_width: family_width,
  };
  return shape;
}
