import { arguments_assert } from "./arguments_assert.mjs";
import { less_than } from "./less_than.mjs";
export function bless_walker_is(fraction) {
  arguments_assert(arguments, 1);
  ("Whether somebody is out walking the pavement rather than standing about outside their");
  ("own front door, drawn from a number between nought and one.");
  ("Two kinds of person, because a street with only one is not a street. Everybody walking");
  ("makes a procession and nobody belongs anywhere; everybody at home makes a set of");
  ("statues with the pavement empty between them. Both together are what a road through a");
  ("neighbourhood actually looks like - a few people going somewhere, past a lot of people");
  ("who are simply outside.");
  ("Drawn once and kept, unlike a pause. Which kind somebody is IS a fact about them: it is");
  ("the difference between a person the player will see again in a minute and a person who");
  ("will have walked out of sight, and a person who changed their mind about it every step");
  ("would be neither.");
  ("The share was set by how much room there is, and it is set by how the street READS now.");
  ("The old worry was the pavement: it holds a fixed count of tiles, a person standing on");
  ("one blocks it, and too many walkers looked like it would jam solid. That worry was");
  ("dismissed here on the argument that a jam costs nothing - somebody with nowhere to step");
  ("simply does not step, and a person waiting to get past is more like a street than one");
  ("nobody has to get past at all. The argument was wrong, and it was wrong because a jam");
  ("this heavy is not a few people waiting, it is everybody waiting. Measured at four in");
  ("five with the pavement three deep: 54 people on 65 tiles, and 38 of them - seven in");
  ("ten - with no free tile beside them in any direction. The street the player watched was");
  ("a crowd holding still, which is the exact complaint raising this number was meant to");
  ("answer.");
  ("So the ceiling is real, and it is answered next door rather than here. A pavement four");
  ("deep instead of three leaves the same crowd one in four stuck instead of seven in ten,");
  ("which is what lets this number be four in five at all. Raising the share and widening");
  ("the pavement are one change, and either half alone is a street that does not work: the");
  ("share without the room is a jam, the room without the share is an empty pavement.");
  ("Both of those were argued when a block held sixty people. It holds forty-five now - the");
  ("pavement was widened as far as the ground allows and the street still read as packed, so");
  ("the crowd itself gave, first to thirty and then back up when that read as thin. This");
  ("number did not move for any of it, and it is worth saying why not: the share and the");
  ("head-count answer different complaints. How many people are out decides whether anybody");
  ("can move at all; how many of them walk decides whether the ones who can are worth");
  ("watching. A block all stood at their own doors would be a street with room to spare and");
  ("nothing happening in it, at any crowd.");
  ("The opposite complaint is real too. The doorstep crowd moves a pace and comes back,");
  ("so from across the map they barely change tiles at all, and the eye counts anybody who");
  ("stays on one square as scenery. At a third, and then at two in five, most of the people");
  ("on screen were scenery, and a street of scenery is not a street.");
  ("Four in five is where it stands. It was raised four times, each time towards more");
  ("motion, and this one crosses half deliberately: the pavement IS the street here, because");
  ("a person walking is the only person the player can watch arrive. The fifth who stay at");
  ("their doors are still enough to say these are people who LIVE here rather than a crowd");
  ("passing through - which is what the player is being asked to pray for - and one in five");
  ("is a doorstep in sight almost everywhere the player looks.");
  let walker = less_than(fraction, 0.8);
  return walker;
}
