export function bless_sidewalk_depth() {
  "How many tiles deep the pavement in front of a block is.";
  "Four, and the number is set by the crowd rather than by taste. One tile wide, two people";
  "walking towards each other have nowhere to go but the way they came, so every meeting";
  "ends with somebody turning round. Two is enough for two people to pass - and this street";
  "does not hold two people, it holds a block's worth, because that is what the ladder says";
  "a block is.";
  "Measured on the built block: at two deep the pavement ran between 74 and 95 per cent";
  "occupied, and the player standing on it had NO free tile beside them in two runs out of";
  "five and one at best. A street the player cannot take a step down is not a street.";
  "Three was enough for a while, and then it was not, and what changed was not this number";
  "but who is out on the pavement. A walker may be anywhere on the pavement and nowhere off";
  "it, so raising the share of people who walk moves the whole rise onto these tiles. At four";
  "in five walking, three deep was measured with 54 people standing on 65 pavement tiles -";
  "77 per cent - and 38 of those 54, seven in ten, had no free tile beside them in any";
  "direction at all. They were told to step every beat and the step was refused every time,";
  "so the street the player watched was a crowd of people holding still. That is the failure";
  "this number answers, and it is the one a player reports: hardly anybody is walking.";
  "Four leaves the same 54 people on 84 tiles - 64 per cent - and only 14 of them, one in";
  "four, with nowhere to go. Five was measured too, and it is better again but barely: 55 per";
  "cent occupied and 18 per cent stuck. Almost the whole gain is in the step from three to";
  "four, and the last few points are not worth what they cost.";
  "Every measurement above was taken when a block held SIXTY. The ladder then cut a building";
  "from four households to two, because widening the pavement had run out of room to widen";
  "into while the street still read as packed; that put a block at thirty, one tile in three";
  "and about one person in twenty stuck, and the player who had reported the jam then said";
  "the street wanted a few more people. It settled at three households, forty-five to a";
  "block: four tiles in seven, about one person in seven momentarily boxed in.";
  "So this number is now doing what the paragraph above hoped it would. Four deep was kept";
  "at the thin crowd on the argument that a roomy pavement is the recoverable mistake -";
  "crowd can be put back, room cannot, because there is no room left on a twenty-seven tile";
  "map to put back. It was put back, into the width this number bought, and that is the whole";
  "case for four rather than three: at three, forty-five people would be seven tiles in ten";
  "occupied, which is the density the original complaint was about.";
  "Not wider than four. Nineteen long against four deep is still close to five to one and";
  "still reads as a line, and a line is what makes some people plainly walking one way and";
  "some the other; wide enough to wander about on, it would read as a square with houses on";
  "one side. Five is where that starts to go.";
  let depth = 4;
  return depth;
}
