import { arguments_assert } from "./arguments_assert.mjs";
import { bless_building_shape } from "./bless_building_shape.mjs";
import { property_get } from "./property_get.mjs";
import { add } from "./add.mjs";
import { subtract } from "./subtract.mjs";
import { integer_random } from "./integer_random.mjs";
export function bless_building_set_back(storeys) {
  arguments_assert(arguments, 1);
  ("How many squares back from the pavement a building of this height stands - drawn afresh");
  ("every time a world is made, and never more than the house has room for.");
  ("Room is the slot MINUS the house. Every building stands in the same three rows of");
  ("ground, and a house is one row of roof with one row of wall under it for each floor -");
  ("two rows for a one-storey house and three for a two-storey one. So a low house has a row");
  ("to spare and a tall one has none, and a tall house is left standing where it is rather");
  ("than pushed out through the back of its slot. The draw is over every position the house");
  ("could take, which for a house with no room to move is only the one it is in - so nothing");
  ("has to ask whether this building is the kind that can step back.");
  ("A DRAW and not a run, which is the one place the street is allowed to differ from itself");
  ("between one visit and the next. The floors and the doors may not: a building is known by");
  ("where it stands in the row, and a record of who has been prayed for is read back through");
  ("that, so a house that had three families yesterday and two today has lost somebody. A");
  ("set-back moves no family and changes no count - it moves a drawing inside a slot whose");
  ("edges do not move - so nothing that is remembered can disagree with it.");
  ("It is what keeps a row of low houses from being a straight line. Two low buildings on a");
  ("block both flush with the pavement draw the same edge as five of them would, and the");
  ("street reads as one long front with doors in it rather than as houses standing side by");
  ("side. Fixed, the same two houses would step back on every street in the world, which is");
  ("its own kind of stamped-out; drawn, a player walking on meets a row they have not seen.");
  ("Asked ONCE per building, when the street is laid out, and carried on the building from");
  ("then on. Asked again later it would answer differently, and the walls a player can see");
  ("would sit a square away from the walls the game thinks are there.");
  let shape = bless_building_shape();
  let depth = property_get(shape, "depth");
  let rows = add(storeys, 1);
  let spare = subtract(depth, rows);
  let back = integer_random(0, spare);
  return back;
}
