import { arguments_assert } from "./arguments_assert.mjs";
export function bless_crossing_look_tiles() {
  arguments_assert(arguments, 0);
  ("How many squares of clear road a walker wants to see before they step off the kerb.");
  ("EIGHT, and it is a number of squares rather than of seconds on purpose, because that is");
  ("what a person actually judges. Nobody times a car; they look at how far away it is and");
  ("at how fast the traffic is going, and here every car goes at exactly one speed, so the");
  ("distance is the whole of the judgement.");
  ("Eight squares is a little over two seconds at the pace the cars keep. It was four, which");
  ("is what a walker who is only getting themselves across needs - four is more than the two");
  ("squares the crossing is deep, so the gap was long enough to walk the whole way over. What");
  ("four was too short for was WATCHING. A walker who steps out on the smallest gap that");
  ("works steps out while a car is plainly still coming, and what that reads as from outside");
  ("is somebody walking into traffic, however cleanly they get across.");
  ("So the number is set by how the crossing LOOKS rather than by what it costs. Played");
  ("against the real rules, eight has the walker standing at the kerb in two crossings out of");
  ("three and waiting about a second and a fifth, against four's two in five and a third of a");
  ("second. Nobody is ever caught in the road either way.");
  ("What it costs is that cars give way more often, because the driver's distance is derived");
  ("from this one. That went from eighteen crossings in one and a half thousand to thirty-");
  ("eight - still under three in a hundred, against every single crossing before the driver's");
  ("courtesy was bounded at all, so the street still keeps moving.");
  ("Not longer, because a walker who waits for an empty street never crosses at all, and");
  ("waiting is the least interesting thing this game can ask anybody to watch - which is also");
  ("why the wait is not spent standing still. The cars give way to somebody already on the");
  ("crossing, so this number decides how POLITE the crossing looks and not whether it is");
  ("safe; safety is settled on the driver's side.");
  let tiles = 8;
  return tiles;
}
