import { arguments_assert } from "./arguments_assert.mjs";
import { add } from "./add.mjs";
import { multiply } from "./multiply.mjs";
export function bless_pace_ms(fraction) {
  arguments_assert(arguments, 1);
  ("How long one person stands between one step and the next, drawn from a number between");
  ("nought and one.");
  ("Everybody keeps their OWN pace, and that is what makes a street rather than a");
  ("formation. One clock ticking for the whole crowd moves everybody at the same instant");
  ("at the same rate, which reads as a body of soldiers however randomly each of them");
  ("chooses a direction - the giveaway is not where they go, it is that they all go at");
  ("once.");
  ("The number is CUBED before it is stretched, so the crowd is mostly brisk with a few");
  ("dawdlers rather than evenly spread between fast and slow. Spread evenly, a street");
  ("would have as many people barely moving as walking, and a crowd where half of");
  ("everybody is nearly still looks broken rather than restful.");
  ("Nobody is ever entirely still. Somebody who never moves at all is scenery, and a");
  ("player who prayed for them and came back an hour later would find them exactly where");
  ("they were - which says the world stopped, not that the person is standing about.");
  ("The two ends were settled from opposite directions and one at a time. The SLOW end came");
  ("down twice: first once a person's step began to LAST their whole wait rather than being");
  ("over in a moment - while the step was quick this number only said how long somebody");
  ("stood between steps, and a very long one merely made them rare to see move, but once it");
  ("became how long they take to cross a single tile, a wait of twenty seconds was a person");
  ("creeping so slowly that no eye could tell them from scenery. It came down again because");
  ("four seconds to cross one tile is a person the player WAITS on rather than notices, and");
  ("past a certain slowness the difference between two people stops reading as character");
  ("and starts reading as a fault. Two and a half seconds is where it stopped, and the");
  ("slowest walker is right there and is meant to be.");
  ("The QUICK end then came down on its own, and that is the whole of the change: half a");
  ("second to cross a tile is somebody with an errand, and a street with nobody on it going");
  ("anywhere in particular reads as a place people are stuck in. Because the number is");
  ("cubed, most of the crowd sits near this end - so lowering it did not add a few fast");
  ("people to an unchanged street, it lifted the ordinary pace of the whole pavement and");
  ("left the dawdlers exactly where they were.");
  ("Five times over between the two is therefore wider than it was, and the width is a");
  ("RESULT rather than a target. What is wanted at each end is what that end looks like on");
  ("its own: plainly walking at the slow end, plainly going somewhere at the quick one.");
  let squared = multiply(fraction, fraction);
  let cubed = multiply(squared, fraction);
  let stretched = multiply(cubed, 2000);
  let ms = add(500, stretched);
  return ms;
}
