import { arguments_assert } from "./arguments_assert.mjs";
import { property_get } from "./property_get.mjs";
import { subtract } from "./subtract.mjs";
import { add } from "./add.mjs";
import { property_equals } from "./property_equals.mjs";
import { list_includes } from "./list_includes.mjs";
import { and } from "./and.mjs";
import { list_filter } from "./list_filter.mjs";
import { list_shuffle_take } from "./list_shuffle_take.mjs";
import { list_first } from "./list_first.mjs";
import { list_map } from "./list_map.mjs";
export function bless_building_windows_ground(walls, doorways) {
  arguments_assert(arguments, 2);
  ("Which squares of a building's ground-floor wall have a window put in them - ONE beside");
  ("every door, on whichever side of it the draw falls, decided once when the street is laid");
  ("out.");
  ("A one-storey house had no windows at all. Its whole front is one band of wall with a door");
  ("in the middle of each family's three squares, and the two squares either side of every");
  ("door were blank - so a low house read as a shed with doors in it, while the tall one next");
  ("to it had glass upstairs. The blank was not saying anything; it was simply the part of");
  ("the wall nothing had been drawn on yet.");
  ("It is asked of every building and not only of the low ones. A rule that gave windows");
  ("downstairs only to houses with nothing upstairs would be saying that a second floor takes");
  ("the ground floor's windows away, which is not true of any house anybody lives in.");
  ("It is asked DOOR BY DOOR, so every home gets exactly one window and exactly half the blank");
  ("wall is glazed. A coin thrown separately at each square gives that half only on average,");
  ("and a house is not an average: a quarter of homes come out with plain wall on both sides");
  ("of the door, which is the shed this was built to stop arriving one home at a time, and a");
  ("quarter come out glazed on both sides, so a narrow house reads as an unbroken row of");
  ("openings. Asking once per door is the only way to promise each home its window AND leave");
  ("half the wall plain.");
  ("WHICH SIDE is the part left to the draw, and it is the part that matters. Every home");
  ("wearing its window on the same side draws a repeating stripe along the street, which reads");
  ("as one long building however the doors are spaced; sides drawn one home at a time make");
  ("windows that sometimes pair up across a party wall and sometimes stand alone, which is");
  ("what a row of separate houses looks like.");
  ("A DRAW rather than a repeating run, and that is allowed here for exactly the reason a");
  ("set-back is. Nothing is remembered about a window: it moves no family, changes no count,");
  ("and no record is read back through it - so a house may wear a different face on the next");
  ("visit without anything the player earned meaning something else. How many doors and how");
  ("many floors may never be drawn that way, because both of those are how a building is");
  ("known.");
  ("The two squares are taken from the WALLS beside the door rather than made up from its");
  ("position. A window has to be in a wall, and the walls are the one list that already knows");
  ("which squares this building actually covers; a square worked out as one-to-the-left of a");
  ("door is a coordinate that nothing has agreed is part of the house.");
  ("Doors are not among the walls, so they cannot be glazed over, and the two lists were");
  ("parted before this is asked.");
  ("Asked ONCE, when the street is laid out, and carried on the building from then on. Asked");
  ("again while it is being drawn it would answer differently every time the street was");
  ("redrawn, and the windows would blink on and off as the player walked.");
  function door_window(door) {
    let door_x = property_get(door, "x");
    let door_y = property_get(door, "y");
    let left = subtract(door_x, 1);
    let right = add(door_x, 1);
    let either = [left, right];
    function beside_is(tile) {
      let level = property_equals(tile, "y", door_y);
      let tile_x = property_get(tile, "x");
      let next_to = list_includes(either, tile_x);
      let beside = and(level, next_to);
      return beside;
    }
    let candidates = list_filter(walls, beside_is);
    let drawn = list_shuffle_take(candidates, 1);
    let chosen = list_first(drawn);
    return chosen;
  }
  let windows = list_map(doorways, door_window);
  return windows;
}
