export function bless_step_timing() {
  "The shape of one person's crossing of a tile: three short pushes with a settle between";
  "them, so a tile is walked in steps rather than travelled in one movement.";
  "A tile used to be crossed in one go, first at an even rate and then at a rising and";
  "falling one. Both were the same mistake at different sizes: the smallest thing a person";
  "did was a whole square, so however the rate was shaped the eye saw one movement per";
  "tile, and one movement is a piece being slid. A walk is made of steps, and a step is";
  "SHORTER than the distance between one tile and the next.";
  "So the crossing is cut into three, and each push covers about a third of the ground";
  "quickly before very nearly stopping. The very nearly is what makes it read as walking";
  "rather than as stuttering: the picture keeps creeping through the settle, so weight is";
  "still shifting, and it is the CONTRAST between push and settle that the eye reads as a";
  "footfall. Stopped dead it would read as three separate little moves.";
  "Three and not two or five, because a push has to last about as long as a real step. A";
  "person here crosses a tile in something under a second at their briskest, so three";
  "pushes are a couple of hundred milliseconds each, which is the length of a stride; two";
  "would be a lope and five a shuffle, and the slow walkers would be worse hit than the";
  "quick ones either way.";
  "The last push arrives a little early and holds, which is the foot landing. It is the";
  "one moment in the whole crossing the picture is genuinely still, and it is what";
  "separates this step from the next one - without it the three pushes run straight into";
  "the next three and the count is lost.";
  "Written as a list of points rather than as a curve because a curve cannot say this. A";
  "curve between two ends has one rise in it however it is bent; a list can rise, level,";
  "rise, level and rise again, which is the whole of what a step is.";
  "A browser too old to understand the list ignores it and keeps the map's own shape, so";
  "the crowd glides as it did before rather than breaking. That is worth knowing when this";
  "is being looked at on somebody else's phone: no steps at all is a browser saying it";
  "cannot, not a mistake in the numbers.";
  let timing = "linear(0, 0.34 24%, 0.36 33%, 0.68 57%, 0.7 66%, 1 91%, 1)";
  return timing;
}
