import { arguments_assert } from "./arguments_assert.mjs";
import { tiles_sides } from "./tiles_sides.mjs";
import { property_get } from "./property_get.mjs";
import { bless_crossing_width } from "./bless_crossing_width.mjs";
import { subtract } from "./subtract.mjs";
import { add } from "./add.mjs";
import { divide_floor } from "./divide_floor.mjs";
import { bless_tiles_rectangle } from "./bless_tiles_rectangle.mjs";
export function bless_road_crossing(road) {
  arguments_assert(arguments, 1);
  ("The squares of one road that are its CROSSING - the only part of it a person on foot may");
  ("walk on, taken as a band straight across both lanes at the middle of the block.");
  ("There is a crossing at all because the blocks are stacked one below another with the road");
  ("at the foot of each, so every journey from this block to the next one goes over a road.");
  ("Closing the road outright would cut the street into pieces the player cannot travel");
  ("between, and the game is a journey down the street; the road has to be crossable.");
  ("It is at the MIDDLE of the block, and that is a choice about fairness rather than about");
  ("looks. Whichever square the player happens to be standing on when they decide to go on,");
  ("the walk to the middle is the shortest walk to a crossing there can be, taken over all");
  ("the places they might have been standing. A crossing at one end is a long detour for");
  ("everybody who was at the other.");
  ("It spans BOTH lanes, top to bottom of the road, because half a crossing is a place to be");
  ("stranded. A person who may step onto the near lane and no further has been invited into");
  ("the traffic and then told to stop in it.");
  ("It is worked out from the road itself rather than handed down with the rest of the block.");
  ("The road is already a rectangle somebody else decided the size and place of, and a");
  ("crossing is a fact about a road; asking the road where its middle is cannot disagree with");
  ("where the road actually went, and a second copy of those numbers could.");
  let sides = tiles_sides(road);
  let left = property_get(sides, "left");
  let right = property_get(sides, "right");
  let top = property_get(sides, "top");
  let bottom = property_get(sides, "bottom");
  let width = bless_crossing_width();
  let span = subtract(right, left);
  let across = add(span, 1);
  let spare = subtract(across, width);
  let along = divide_floor(spare, 2);
  let at = add(left, along);
  let deep = subtract(bottom, top);
  let depth = add(deep, 1);
  let tiles = bless_tiles_rectangle(at, top, width, depth);
  return tiles;
}
