import { arguments_assert } from "./arguments_assert.mjs";
import { emoji_video_game } from "./emoji_video_game.mjs";
import { emoji_globe_americas } from "./emoji_globe_americas.mjs";
import { bless_prayer_flanked } from "./bless_prayer_flanked.mjs";
export function bless_prayer_transfer_shown(prayer) {
  arguments_assert(arguments, 1);
  ("The prayer at the door as the player sees it - a game controller in front of it and the");
  ("world behind it.");
  ("These two are FIXED, where the prayer over a person takes whatever the draw gives it.");
  ("The reason is that this prayer is read once and the other is read a thousand times: a");
  ("picture drawn at random earns its keep by keeping a panel from going stale, and");
  ("nothing seen once can go stale. So the one screen that gets to choose its pictures for");
  ("what they MEAN chooses them.");
  ("And they are the two ends of the sentence between them, in the order it says them. The");
  ("prayer runs from this video game to everyone in the world the player lives in, so a");
  ("controller stands where the game is named and the world stands where the world is, and");
  ("the line reads left to right as the crossing the prayer is asking for. Somebody who");
  ("reads nothing but the two pictures has still been told what the door is for.");
  ("The controller is why praying hands are not here, and losing them was the trade worth");
  ("making. Hands would have said the player is praying - which the player already knows,");
  ("because they are looking at a prayer - and they are on the amen a moment later anyway,");
  ("so this screen would have shown the same picture twice and said nothing with either.");
  ("The controller says the one thing on this screen that is genuinely surprising: that");
  ("what is about to happen is a GAME, and that the game is the thing being handed over.");
  ("The globe is kept for this screen alone and is not in the pool the other prayers draw");
  ("from, so it goes on meaning the whole world rather than becoming one more picture the");
  ("game shows sometimes.");
  let before = emoji_video_game();
  let after = emoji_globe_americas();
  let text = bless_prayer_flanked(prayer, before, after);
  return text;
}
