import { arguments_assert } from "./arguments_assert.mjs";
import { list_size } from "./list_size.mjs";
import { multiply } from "./multiply.mjs";
import { text_words } from "./text_words.mjs";
export function bless_prayer_read_ms(prayer) {
  arguments_assert(arguments, 1);
  ("How long the quickest honest reading of a prayer takes - long enough that nobody gets");
  ("past the words without seeing them.");
  ("It is a FLOOR and never a limit. The amen is held back this long and then waits as long");
  ("as the player likes, so the one thing that cannot be optimised away is the reading -");
  ("which is the player's whole part in this game.");
  ("Measured from the words rather than fixed, because the prayers differ: blessing one");
  ("person is five words and blessing everyone on their continent is ten, and one time for");
  ("both would either rush the long one or leave the short one waiting for nothing.");
  ("Set to the FASTEST reader and not to the average one, which is the whole of choosing the");
  ("number. A slow reader is never touched by it: they have not finished when it lifts, and");
  ("it lifts silently. It binds nobody except somebody who has already read the prayer - so");
  ("every millisecond above a quick reading is time spent by a player who is done, and time");
  ("spent by somebody who is done is a toll.");
  ("A toll is the one thing this must not become. The whole shape of the game is that the");
  ("fastest way through it is to pray; put idle seconds on top of the praying and the");
  ("fastest way through is to pray and then wait, which makes the prayer the thing standing");
  ("between the player and the game rather than the game itself.");
  ("Three hundred milliseconds a word is a brisk reading of a sentence somebody means. It");
  ("is faster than saying it out loud, and that is deliberate: reading aloud is what the");
  ("prayer is FOR, and anybody doing it will still be speaking when the button arrives.");
  let words = text_words(prayer);
  let count = list_size(words);
  let ms = multiply(count, 300);
  return ms;
}
