import { function_duplicate_kind_parallel } from "./function_duplicate_kind_parallel.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { less_than } from "./less_than.mjs";
export function bless_walker_is(fraction) {
  function_duplicate_kind_parallel();
  arguments_assert(arguments, 1);
  ("Whether somebody is out walking the pavement rather than standing about outside their");
  ("own front door, drawn from a number between nought and one.");
  ("Two kinds of person, because a street with only one is not a street. Everybody walking");
  ("makes a procession and nobody belongs anywhere; everybody at home makes a set of");
  ("statues with the pavement empty between them. Both together are what a road through a");
  ("neighbourhood actually looks like - a few people going somewhere, past a lot of people");
  ("who are simply outside.");
  ("Drawn once and kept, unlike a pause. Which kind somebody is IS a fact about them: it is");
  ("the difference between a person the player will see again in a minute and a person who");
  ("will have walked out of sight, and a person who changed their mind about it every step");
  ("would be neither.");
  ("The share was set by how much room there is, and it is set by how the street READS now.");
  ("The old worry was the pavement: it holds a fixed count of tiles, a person standing on");
  ("one blocks it, and too many walkers looked like it would jam solid. It does not, and the");
  ("reason it does not is what a jam actually costs here. Somebody with nowhere to step");
  ("simply does not step, and stands where they are until a way opens - which is a person");
  ("waiting to get past, and a pavement with those on it is more like a street than one");
  ("nobody has to get past at all. So the ceiling that number was held under was never real.");
  ("What IS real is the opposite complaint. The doorstep crowd moves a pace and comes back,");
  ("so from across the map they barely change tiles at all, and the eye counts anybody who");
  ("stays on one square as scenery. At a third, and then at two in five, most of the people");
  ("on screen were scenery, and a street of scenery is not a street.");
  ("Four in five is where it stands. It was raised four times, each time towards more");
  ("motion, and this one crosses half deliberately: the pavement IS the street here, because");
  ("a person walking is the only person the player can watch arrive. The fifth who stay at");
  ("their doors are still enough to say these are people who LIVE here rather than a crowd");
  ("passing through - which is what the player is being asked to pray for - and one in five");
  ("is a doorstep in sight almost everywhere the player looks.");
  let walker = less_than(fraction, 0.4);
  return walker;
}
