export function ebible_books_engbsb() {
  "the 66-book engbsb (Berean Standard Bible) book list, baked in as a local module instead of fetched from firebase Storage (bible/engbsb/books.json). it is a tiny (~0.8KB), immutable list, so the ~700ms remote round-trip on every page load was pure latency; baked, it ships and versions with the code — no request at all";
  let books = [
    { book_code: "GEN", text: "Genesis", href: "GEN01.htm" },
    { book_code: "EXO", text: "Exodus", href: "EXO01.htm" },
    { book_code: "LEV", text: "Leviticus", href: "LEV01.htm" },
    { book_code: "NUM", text: "Numbers", href: "NUM01.htm" },
    { book_code: "DEU", text: "Deuteronomy", href: "DEU01.htm" },
    { book_code: "JOS", text: "Joshua", href: "JOS01.htm" },
    { book_code: "JDG", text: "Judges", href: "JDG01.htm" },
    { book_code: "RUT", text: "Ruth", href: "RUT01.htm" },
    { book_code: "1SA", text: "1 Samuel", href: "1SA01.htm" },
    { book_code: "2SA", text: "2 Samuel", href: "2SA01.htm" },
    { book_code: "1KI", text: "1 Kings", href: "1KI01.htm" },
    { book_code: "2KI", text: "2 Kings", href: "2KI01.htm" },
    { book_code: "1CH", text: "1 Chronicles", href: "1CH01.htm" },
    { book_code: "2CH", text: "2 Chronicles", href: "2CH01.htm" },
    { book_code: "EZR", text: "Ezra", href: "EZR01.htm" },
    { book_code: "NEH", text: "Nehemiah", href: "NEH01.htm" },
    { book_code: "EST", text: "Esther", href: "EST01.htm" },
    { book_code: "JOB", text: "Job", href: "JOB01.htm" },
    { book_code: "PSA", text: "Psalms", href: "PSA001.htm" },
    { book_code: "PRO", text: "Proverbs", href: "PRO01.htm" },
    { book_code: "ECC", text: "Ecclesiastes", href: "ECC01.htm" },
    { book_code: "SNG", text: "Song", href: "SNG01.htm" },
    { book_code: "ISA", text: "Isaiah", href: "ISA01.htm" },
    { book_code: "JER", text: "Jeremiah", href: "JER01.htm" },
    { book_code: "LAM", text: "Lamentations", href: "LAM01.htm" },
    { book_code: "EZK", text: "Ezekiel", href: "EZK01.htm" },
    { book_code: "DAN", text: "Daniel", href: "DAN01.htm" },
    { book_code: "HOS", text: "Hosea", href: "HOS01.htm" },
    { book_code: "JOL", text: "Joel", href: "JOL01.htm" },
    { book_code: "AMO", text: "Amos", href: "AMO01.htm" },
    { book_code: "OBA", text: "Obadiah", href: "OBA01.htm" },
    { book_code: "JON", text: "Jonah", href: "JON01.htm" },
    { book_code: "MIC", text: "Micah", href: "MIC01.htm" },
    { book_code: "NAM", text: "Nahum", href: "NAM01.htm" },
    { book_code: "HAB", text: "Habakkuk", href: "HAB01.htm" },
    { book_code: "ZEP", text: "Zephaniah", href: "ZEP01.htm" },
    { book_code: "HAG", text: "Haggai", href: "HAG01.htm" },
    { book_code: "ZEC", text: "Zechariah", href: "ZEC01.htm" },
    { book_code: "MAL", text: "Malachi", href: "MAL01.htm" },
    { book_code: "MAT", text: "Matthew", href: "MAT01.htm" },
    { book_code: "MRK", text: "Mark", href: "MRK01.htm" },
    { book_code: "LUK", text: "Luke", href: "LUK01.htm" },
    { book_code: "JHN", text: "John", href: "JHN01.htm" },
    { book_code: "ACT", text: "Acts", href: "ACT01.htm" },
    { book_code: "ROM", text: "Romans", href: "ROM01.htm" },
    { book_code: "1CO", text: "1 Corinthians", href: "1CO01.htm" },
    { book_code: "2CO", text: "2 Corinthians", href: "2CO01.htm" },
    { book_code: "GAL", text: "Galatians", href: "GAL01.htm" },
    { book_code: "EPH", text: "Ephesians", href: "EPH01.htm" },
    { book_code: "PHP", text: "Philippians", href: "PHP01.htm" },
    { book_code: "COL", text: "Colossians", href: "COL01.htm" },
    { book_code: "1TH", text: "1 Thessalonians", href: "1TH01.htm" },
    { book_code: "2TH", text: "2 Thessalonians", href: "2TH01.htm" },
    { book_code: "1TI", text: "1 Timothy", href: "1TI01.htm" },
    { book_code: "2TI", text: "2 Timothy", href: "2TI01.htm" },
    { book_code: "TIT", text: "Titus", href: "TIT01.htm" },
    { book_code: "PHM", text: "Philemon", href: "PHM01.htm" },
    { book_code: "HEB", text: "Hebrews", href: "HEB01.htm" },
    { book_code: "JAS", text: "James", href: "JAS01.htm" },
    { book_code: "1PE", text: "1 Peter", href: "1PE01.htm" },
    { book_code: "2PE", text: "2 Peter", href: "2PE01.htm" },
    { book_code: "1JN", text: "1 John", href: "1JN01.htm" },
    { book_code: "2JN", text: "2 John", href: "2JN01.htm" },
    { book_code: "3JN", text: "3 John", href: "3JN01.htm" },
    { book_code: "JUD", text: "Jude", href: "JUD01.htm" },
    { book_code: "REV", text: "Revelation", href: "REV01.htm" },
  ];
  return books;
}
