import { fn_name } from "./fn_name.mjs";
export function ebible_languages_more_rows() {
  ("Every language eBible gives away on terms this repo may ship that the hand-written list does not already carry, one translation each, three words to a language: what it is called, the folder its chapters sit in, and its short code. Read back into whole records by ",
    fn_name("ebible_languages_from_rows"),
    " - an edit made here is thrown away the next time it is generated.");
  let v = [
    ["'Olelo Hawai'i (Hawaiian)", "haw1868", "haw"],
    ["Abureni", "mgj", "mgj"],
    ["Ajanji (Janji)", "jni", "jni"],
    ["Ajiya", "idc", "idc"],
    ["Akukem", "spm", "spm"],
    ["Alaba-K’abeena (Alaba-K'abeena)", "alw", "alw"],
    ["Amarasi", "aaz", "aaz"],
    ["Ambala Ayta (Ayta, Ambala)", "abc", "abc"],
    ["Aninka", "aqk", "aqk"],
    ["Apalɨ (Apal)", "ena", "ena"],
    ["Arapaho", "arp", "arp"],
    ["Armãneashti/Arumanisht", "rup", "rup"],
    ["Arosi", "aia", "aia"],
    ["Aruamu", "msy2020", "msy"],
    ["Asang Khongca (Chin, Eastern Khumi)", "cekak", "cek"],
    ["Auna (Tsikimba)", "kdl", "kdl"],
    ["Awabakalkoba (Awabakal)", "awk", "awk"],
    ["Baegu (Baeggu)", "bvd", "bvd"],
    ["Baga Sitemu", "bsp", "bsp"],
    ["bahasa Indonesia (Indonesian)", "ind", "ind"],
    ["Baikeno", "bkx", "bkx"],
    ["Bambam", "ptu", "ptu"],
    ["Bangunji (Bangwinji)", "bsj", "bsj"],
    ["Basa-Gurmana", "buj", "buj"],
    ["Bayso (Baiso)", "bswe", "bsw"],
    ["Bedamuni (Beami)", "beo", "beo"],
    ["Bekwel", "bkw", "bkw"],
    ["Bhilali", "bhi", "bhi"],
    ["Bhumiya (Bhunjia)", "bhu", "bhu"],
    ["Bimin", "bhl", "bhl"],
    ["Boga", "bvw", "bvw"],
    ["Bondei", "bou", "bou"],
    ["Borei", "gai", "gai"],
    ["Borni (Borna)", "bwo", "bwo"],
    ["Brezhoneg (Breton)", "breBRG", "bre"],
    ["Bu (Bauchi State)", "zbu", "zbu"],
    ["Bughotu", "bgt", "bgt"],
    ["Bwile", "bwc", "bwc"],
    ["český (Czech)", "ces1613", "ces"],
    ["Chamorro", "cha", "cha"],
    ["Chergash (Romani, Vlax)", "rmyChergash", "rmy"],
    ["Chhattisgarhi", "hne", "hne"],
    ["Chikuahane (Kuhane)", "sbs", "sbs"],
    ["Chingoni (Ngoni)", "xnj", "xnj"],
    ["Chisoli (Soli)", "sby", "sby"],
    ["Chongthu (Chin, Thado)", "tczchongthu", "tcz"],
    ["Chung (Cung)", "cug", "cug"],
    ["Chuukese", "chk", "chk"],
    ["Cishingini", "asg", "asg"],
    ["Ciyawo (Chiyawo)", "yao", "yao"],
    ["Daai (Chin, Daai)", "dao", "dao"],
    ["Dadibi", "mps", "mps"],
    ["Dane Zaa (Beaver)", "bea", "bea"],
    ["Dano", "aso", "aso"],
    ["Danu", "dnv", "dnv"],
    ["Dawro", "dwrl", "dwr"],
    ["Deutsch (German, Standard)", "deu1951", "deu"],
    ["Dhanki", "dhn", "dhn"],
    ["Dhao", "nfa", "nfa"],
    ["Didayi (Gata')", "gaq", "gaq"],
    ["Dieri", "dif", "dif"],
    ["Djinang", "dji", "dji"],
    ["Dongxiang", "sce", "sce"],
    ["Doromu-Koki", "kqc", "kqc"],
    ["Duya", "ldb", "ldb"],
    ["Eesti (Estonian, Standard)", "ekk", "ekk"],
    ["Ekajuk", "eka", "eka"],
    ["Esperanto", "epo", "epo"],
    ["Etulo", "utr", "utr"],
    ["Falam", "cfm", "cfm"],
    ["Fataleka", "far", "far"],
    ["Folopa", "ppo", "ppo"],
    ["Gamit", "gbl", "gbl"],
    ["Gamotso (Gamo)", "gmve", "gmv"],
    ["Gapapaiwa", "pwg", "pwg"],
    ["Gayil", "gyl", "gyl"],
    ["Geji", "gyz", "gyz"],
    ["Ghanongga", "ghn", "ghn"],
    ["Gilaki", "glk", "glk"],
    ["Glavda", "glwl", "glw"],
    ["Gohllaru (Holiya)", "hoy", "hoy"],
    ["Goofa", "gofe", "gof"],
    ["Gourma (Gourmanchéma)", "gux", "gux"],
    ["Gowlan", "goj", "goj"],
    ["Gowli", "gok", "gok"],
    ["Guduf-Gava", "gdf", "gdf"],
    ["Gugu Yimidhirr (Guugu Yimidhirr)", "kky", "kky"],
    ["Guguminjen (Kunjen)", "kjn", "kjn"],
    ["gujii", "gax", "gax"],
    ["Gwahatike", "dah", "dah"],
    ["Halbi", "hlb", "hlb"],
    ["Hassaniyya", "mey", "mey"],
    ["Havai (Ambae, East)", "omb", "omb"],
    ["Havu", "hav", "hav"],
    ["Hawu", "hvn", "hvn"],
    ["Helong", "hegNTpo", "heg"],
    ["Hona (Hwana)", "hwo", "hwo"],
    ["Hre", "hrebt", "hre"],
    ["Hruso", "hru", "hru"],
    ["Hrvatski (Croatian)", "hrv", "hrv"],
    ["Ikizu", "ikz", "ikz"],
    ["Ilocano", "iloulb", "ilo"],
    ["Ilonggo", "hil", "hil"],
    ["isiNdebele (Ndebele)", "nde", "nde"],
    ["Íslenska (Icelandic)", "isl", "isl"],
    ["Ivatan (Yaka)", "iyx", "iyx"],
    ["Jida (Bu)", "jid", "jid"],
    ["Jumjum", "jum", "jum"],
    ["Juray", "juy", "juy"],
    ["Kamano-Kafe (Kamano)", "kbq", "kbq"],
    ["Kapin", "tbx", "tbx"],
    ["Kapingamarangi", "kpg", "kpg"],
    ["Karo (Rawa) (Rawa)", "rwo-karo", "rwo"],
    ["Kese (Kisi)", "kiz", "kiz"],
    ["Kharam (Naga, Kharam)", "kfw", "kfw"],
    ["Kho (Bugun)", "bgg", "bgg"],
    ["Kiisanzu (Isanzu)", "isn", "isn"],
    ["Kikara (Kara)", "reg", "reg"],
    ["Kikuyu (Gikuyu)", "kik", "kik"],
    ["Kindengereko (Ndengereko)", "ndg", "ndg"],
    ["Kisafwa (Safwa)", "sbk", "sbk"],
    ["Kitaabua (Taabwa)", "tap", "tap"],
    ["Kituba", "mkw", "mkw"],
    ["Kivwanji (Vwanji)", "wbi", "wbi"],
    ["Kiyombi", "yom", "yom"],
    ["Kizalamo", "zajp", "zaj"],
    ["Koda", "cdz", "cdz"],
    ["Kolami (Vaghri)", "vgr", "vgr"],
    ["Konda Porja (Konda-Dora)", "kfcp", "kfc"],
    ["Kosrae (Kosraean)", "kos", "kos"],
    ["Koya", "kff", "kff"],
    ["Kreyòl Ayisyen (Haitian)", "hat", "hat"],
    ["Kupang Malay", "mkn", "mkn"],
    ["Kurama", "krh", "krh"],
    ["Kurti", "ktm", "ktm"],
    ["Kutu", "kdc", "kdc"],
    ["Kuturmi", "khj", "khj"],
    ["Kuuk Thayorre (Thayore)", "thd", "thd"],
    ["Kwara'ae", "kwf", "kwf"],
    ["Latine (Latin)", "latVUC", "lat"],
    ["lietuvių (Lithuanian)", "lit", "lit"],
    ["Lingála", "lin", "lin"],
    ["Lodha (Lodhi)", "lbm", "lbm"],
    ["Loxicha Zapotec (Zapotec, Loxicha)", "ztp", "ztp"],
    ["Luqa (Lungga)", "lga", "lga"],
    ["Luyana", "lyn", "lyn"],
    ["Maale (Male)", "mdyeth", "mdy"],
    ["Magyar", "hun", "hun"],
    ["Mahanji (Kinga)", "zgam", "zga"],
    ["Mahasui (Pahari, Mahasu)", "bfz", "bfz"],
    ["Makhuwa-Meetto", "mgh2016", "mgh"],
    ["Marghi South", "mfm", "mfm"],
    ["Mashi (Shi)", "shr", "shr"],
    ["Matengo", "mgv", "mgv"],
    ["Matumbi", "mgw", "mgw"],
    ["Matupi Chin (Chin, Matu)", "hlt", "hlt"],
    ["Mbe", "mfo", "mfo"],
    ["Mbula (Mbula-Bwazza)", "mbu", "mbu"],
    ["Melo", "mfxe", "mfx"],
    ["Meriam Mir (Meriam)", "ulk1902", "ulk"],
    ["Mori Atas", "mzq", "mzq"],
    ["Morokodo", "mgc", "mgc"],
    ["Mpoto", "mpa", "mpa"],
    ["Mum", "kqa", "kqa"],
    ["Mupun (Mwaghavul)", "sur", "sur"],
    ["Murrinhpatha (Murrinh-Patha)", "mwf2018", "mwf"],
    ["Mwera", "mwe", "mwe"],
    ["Mynmar language (Burmese)", "mya", "mya"],
    ["Nagamiz (Naga Pidgin)", "nag", "nag"],
    ["Nali", "nss", "nss"],
    ["Natqgu (Natügu)", "ntu", "ntu"],
    ["Nchane (Ncane)", "ncr", "ncr"],
    ["Ndamba", "ndj", "ndj"],
    ["Ndendeule", "dne", "dne"],
    ["Ndondehamba (Ndonde Hamba)", "njd", "njd"],
    ["Ndwewe", "nww", "nww"],
    ["Nend", "anh", "anh"],
    ["Ngarrindjeri (Narrinyeri)", "nay", "nay"],
    ["Ngindo", "nnq", "nnq"],
    ["Nguu", "ngp", "ngp"],
    ["Nii", "nii", "nii"],
    ["Nkangala", "nkn", "nkn"],
    ["Norsk: Bokmål (Norwegian)", "noblb", "nob"],
    ["Nukna", "klt", "klt"],
    ["Ogea", "eri", "eri"],
    ["Oyda", "oyde", "oyd"],
    ["Paama", "pma", "pma"],
    ["Padoe", "pdo", "pdo"],
    ["Pali (Bareli, Palya)", "bpx", "bpx"],
    ["Patep", "ptp", "ptp"],
    ["Pengu (Pengo)", "peg", "peg"],
    ["Pogolo", "poy", "poy"],
    ["Pohnpeian", "pon", "pon"],
    ["Polci", "plj", "plj"],
    ["Powari", "pwr", "pwr"],
    ["Pular", "fuf", "fuf"],
    ["Pura (Blagar)", "beu", "beu"],
    ["Purum", "pub", "pub"],
    ["Qach’abel (K'iche')", "quctt", "quc"],
    ["Qaqet", "byx", "byx"],
    ["Ramoaaina", "rai", "rai"],
    ["Rana Tharu (Tharu, Rana)", "thr", "thr"],
    ["Rangi", "lag", "lag"],
    ["Relli (Reli)", "rei", "rei"],
    ["Rohingya", "rhgc", "rhg"],
    ["Română (Romanian)", "ronbtf", "ron"],
    ["Romanes (Romani, Carpathian)", "rmc", "rmc"],
    ["Romani", "rmna", "rmn"],
    ["Rote Dela (Dela-Oenale)", "row", "row"],
    ["Rote Lole (Lole)", "llg", "llg"],
    ["Rote Rikou (Rikou)", "rgu", "rgu"],
    ["Rote Tii (Tii)", "txq", "txq"],
    ["Rotokas", "roo", "roo"],
    ["Roviana", "rug", "rug"],
    ["Sa'a", "apb", "apb"],
    ["Saafi-Saafi", "sav", "sav"],
    ["Saisai (Nimoa)", "nmws", "nmw"],
    ["Sakechep (Sakachep)", "sch", "sch"],
    ["Saliba", "sbe", "sbe"],
    ["Sanga", "xsn", "xsn"],
    ["Sankaran Maninka", "msc", "msc"],
    ["Sanskrit", "sandev", "san"],
    ["Sari", "asj", "asj"],
    ["Satawalese", "stw", "stw"],
    ["Saveeng (Mutu)", "tuc-t", "tuc"],
    ["Sena", "seh", "seh"],
    ["Shatt", "shj", "shj"],
    ["Sholaga", "sle", "sle"],
    ["Shwe Palaung (Palaung, Shwe)", "pll", "pll"],
    ["Siksiká (Blackfoot)", "bla", "bla"],
    ["Siyin Chin (Chin, Siyin)", "csy", "csy"],
    ["Slovenčina (Slovak)", "slk", "slk"],
    ["Sob Dora (Sop)", "urw", "urw"],
    ["Somau Karia", "six", "six"],
    ["Southeast Ambrym (Ambrym, Southeast)", "tvk", "tvk"],
    ["Southeastern Kolami (Kolami, Southeastern)", "nit", "nit"],
    ["Sudanese Creole Arabic (Arabic, Sudanese Creole)", "pga", "pga"],
    ["Sudest", "tgo", "tgo"],
    ["Suomi (Finnish)", "fin", "fin"],
    ["Tagakaulo", "klg", "klg"],
    ["Tagin", "tgj", "tgj"],
    ["Takuu", "nho", "nho"],
    ["Takwane", "tke", "tke"],
    ["Tandroy (Malagasy, Tandroy-Mahafaly)", "tdx", "tdx"],
    ["Tarok", "yer", "yer"],
    ["Taupota", "tpa", "tpa"],
    ["Tavoyan", "tvn", "tvn"],
    ["Tay (Tai)", "taw", "taw"],
    ["Teke-Tyee", "tyx", "tyx"],
    ["Tetun Dili", "tdt", "tdt"],
    ["Thai Phum (Chin, Thaiphum)", "cth", "cth"],
    ["Thur", "lth", "lth"],
    ["Tichurong", "tcn", "tcn"],
    ["Tiếng Việt (Vietnamese)", "vie1934", "vie"],
    ["Tifal", "tif", "tif"],
    ["Timap (Amo)", "amo", "amo"],
    ["Toka-Leya-Dombe (Dombe)", "dov", "dov"],
    ["Tongan", "ton", "ton"],
    ["Totcha (Naga, Tutsa)", "tvt", "tvt"],
    ["Ts‘əxna miz (Tsakhur)", "tkr", "tkr"],
    ["Tsishingini", "tsw", "tsw"],
    ["Tswana (Setswana)", "tsn", "tsn"],
    ["Tuma-Irumu", "iou", "iou"],
    ["Tutun Belu (Tetun)", "tet", "tet"],
    ["Urat", "urt", "urt"],
    ["ut-Ma'in", "gel", "gel"],
    ["Uyghur tili (Uyghur)", "uigara", "uig"],
    ["Vaagri Booli", "vaa", "vaa"],
    ["Vidunda", "vid", "vid"],
    ["Waddar", "wbq", "wbq"],
    ["Waima", "rro", "rro"],
    ["Waja", "wja", "wja"],
    ["Wala", "lgl", "lgl"],
    ["Waskia", "wsk", "wsk"],
    ["Wolio", "wlo", "wlo"],
    ["Worrorra", "wro", "wro"],
    ["Yaka", "yaf", "yaf"],
    ["Yalë (Yale)", "nce", "nce"],
    ["Yamap", "ymp", "ymp"],
    ["Yansi", "yns", "yns"],
    ["Yapese", "yap", "yap"],
    ["Yau", "yuw", "yuw"],
    ["Yemsa", "jnje", "jnj"],
    ["Yindjibarndi", "yij", "yij"],
    ["Yipunu", "puu", "puu"],
    ["Zanaki", "zak", "zak"],
    ["Zia", "zia", "zia"],
    ["Zigua", "ziw", "ziw"],
    ["Zinza", "zin", "zin"],
    ["Ἑλληνική (Greek, Ancient)", "grcbrent", "grc"],
    ["ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ (Coptic)", "copbhc", "cop"],
    ["русский (Russian)", "russyn", "rus"],
    ["Српски/ Srpski (Serbian)", "srponspc", "srp"],
    ["Українська (Ukrainian)", "ukrfb", "ukr"],
    ["יידיש מזרחית (Yiddish, Eastern)", "ydd", "ydd"],
    ["עברית (Hebrew)", "heb", "heb"],
    ["עברית (Hebrew)", "hbo", "hbo"],
    ["كوردی سۆرانی (Central Kurdish)", "ckb", "ckb"],
    ["अहिराणी‎ (Ahirani)", "ahr", "ahr"],
    ["नेपाली", "npioncb", "npi"],
    ["भटियाली‎ (Bhattiyali)", "bht", "bht"],
    ["भद्रवाही‎ (Bhadrawahi)", "bhd", "bhd"],
    ["हरियाणवी‎ (Haryanvi)", "bgc", "bgc"],
    ["অসমীয়া (Assamese)", "asmfb", "asm"],
    ["মুন্ডা‎ (Muɳɖa) (Munda)", "unx", "unx"],
    ["ଦେଶିଆ (Desiya)", "dso", "dso"],
    ["ବଡ଼ ପରଜା (Bodo Parja)", "bdv", "bdv"],
    ["కువి (Kuvi)", "kxv", "kxv"],
    ["മലയാളം (Malayalam)", "mal", "mal"],
    ["ရခိုင် (Rakhine)", "rki", "rki"],
    ["한국인 (Korean)", "kor", "kor"],
    ["日本語 (Japanese)", "jpn1965", "jpn"],
  ];
  return v;
}
