import { fn_name } from "./fn_name.mjs";
export function ebible_languages_more() {
  ("Every language eBible gives away on terms this repo may ship that the hand-written list does not already carry, one translation each. Generated by ",
    fn_name("ebible_languages_more_write"),
    " - an edit made here is thrown away the next time it runs.");
  let v = [
    {
      name: "'Olelo Hawai'i (Hawaiian)",
      bible_folder: "haw1868",
      language_code: "haw",
    },
    {
      name: "Abureni",
      bible_folder: "mgj",
      language_code: "mgj",
    },
    {
      name: "Ajanji (Janji)",
      bible_folder: "jni",
      language_code: "jni",
    },
    {
      name: "Ajiya",
      bible_folder: "idc",
      language_code: "idc",
    },
    {
      name: "Akukem",
      bible_folder: "spm",
      language_code: "spm",
    },
    {
      name: "Alaba-K’abeena (Alaba-K'abeena)",
      bible_folder: "alw",
      language_code: "alw",
    },
    {
      name: "Amarasi",
      bible_folder: "aaz",
      language_code: "aaz",
    },
    {
      name: "Ambala Ayta (Ayta, Ambala)",
      bible_folder: "abc",
      language_code: "abc",
    },
    {
      name: "Aninka",
      bible_folder: "aqk",
      language_code: "aqk",
    },
    {
      name: "Apalɨ (Apal)",
      bible_folder: "ena",
      language_code: "ena",
    },
    {
      name: "Arapaho",
      bible_folder: "arp",
      language_code: "arp",
    },
    {
      name: "Armãneashti/Arumanisht",
      bible_folder: "rup",
      language_code: "rup",
    },
    {
      name: "Arosi",
      bible_folder: "aia",
      language_code: "aia",
    },
    {
      name: "Aruamu",
      bible_folder: "msy2020",
      language_code: "msy",
    },
    {
      name: "Asang Khongca (Chin, Eastern Khumi)",
      bible_folder: "cekak",
      language_code: "cek",
    },
    {
      name: "Auna (Tsikimba)",
      bible_folder: "kdl",
      language_code: "kdl",
    },
    {
      name: "Awabakalkoba (Awabakal)",
      bible_folder: "awk",
      language_code: "awk",
    },
    {
      name: "Baegu (Baeggu)",
      bible_folder: "bvd",
      language_code: "bvd",
    },
    {
      name: "Baga Sitemu",
      bible_folder: "bsp",
      language_code: "bsp",
    },
    {
      name: "bahasa Indonesia (Indonesian)",
      bible_folder: "ind",
      language_code: "ind",
    },
    {
      name: "Baikeno",
      bible_folder: "bkx",
      language_code: "bkx",
    },
    {
      name: "Bambam",
      bible_folder: "ptu",
      language_code: "ptu",
    },
    {
      name: "Bangunji (Bangwinji)",
      bible_folder: "bsj",
      language_code: "bsj",
    },
    {
      name: "Basa-Gurmana",
      bible_folder: "buj",
      language_code: "buj",
    },
    {
      name: "Bayso (Baiso)",
      bible_folder: "bswe",
      language_code: "bsw",
    },
    {
      name: "Bedamuni (Beami)",
      bible_folder: "beo",
      language_code: "beo",
    },
    {
      name: "Bekwel",
      bible_folder: "bkw",
      language_code: "bkw",
    },
    {
      name: "Bhilali",
      bible_folder: "bhi",
      language_code: "bhi",
    },
    {
      name: "Bhumiya (Bhunjia)",
      bible_folder: "bhu",
      language_code: "bhu",
    },
    {
      name: "Bimin",
      bible_folder: "bhl",
      language_code: "bhl",
    },
    {
      name: "Boga",
      bible_folder: "bvw",
      language_code: "bvw",
    },
    {
      name: "Bondei",
      bible_folder: "bou",
      language_code: "bou",
    },
    {
      name: "Borei",
      bible_folder: "gai",
      language_code: "gai",
    },
    {
      name: "Borni (Borna)",
      bible_folder: "bwo",
      language_code: "bwo",
    },
    {
      name: "Brezhoneg (Breton)",
      bible_folder: "breBRG",
      language_code: "bre",
    },
    {
      name: "Bu (Bauchi State)",
      bible_folder: "zbu",
      language_code: "zbu",
    },
    {
      name: "Bughotu",
      bible_folder: "bgt",
      language_code: "bgt",
    },
    {
      name: "Bwile",
      bible_folder: "bwc",
      language_code: "bwc",
    },
    {
      name: "český (Czech)",
      bible_folder: "ces1613",
      language_code: "ces",
    },
    {
      name: "Chamorro",
      bible_folder: "cha",
      language_code: "cha",
    },
    {
      name: "Chergash (Romani, Vlax)",
      bible_folder: "rmyChergash",
      language_code: "rmy",
    },
    {
      name: "Chhattisgarhi",
      bible_folder: "hne",
      language_code: "hne",
    },
    {
      name: "Chikuahane (Kuhane)",
      bible_folder: "sbs",
      language_code: "sbs",
    },
    {
      name: "Chingoni (Ngoni)",
      bible_folder: "xnj",
      language_code: "xnj",
    },
    {
      name: "Chisoli (Soli)",
      bible_folder: "sby",
      language_code: "sby",
    },
    {
      name: "Chongthu (Chin, Thado)",
      bible_folder: "tczchongthu",
      language_code: "tcz",
    },
    {
      name: "Chung (Cung)",
      bible_folder: "cug",
      language_code: "cug",
    },
    {
      name: "Chuukese",
      bible_folder: "chk",
      language_code: "chk",
    },
    {
      name: "Cishingini",
      bible_folder: "asg",
      language_code: "asg",
    },
    {
      name: "Ciyawo (Chiyawo)",
      bible_folder: "yao",
      language_code: "yao",
    },
    {
      name: "Daai (Chin, Daai)",
      bible_folder: "dao",
      language_code: "dao",
    },
    {
      name: "Dadibi",
      bible_folder: "mps",
      language_code: "mps",
    },
    {
      name: "Dane Zaa (Beaver)",
      bible_folder: "bea",
      language_code: "bea",
    },
    {
      name: "Dano",
      bible_folder: "aso",
      language_code: "aso",
    },
    {
      name: "Danu",
      bible_folder: "dnv",
      language_code: "dnv",
    },
    {
      name: "Dawro",
      bible_folder: "dwrl",
      language_code: "dwr",
    },
    {
      name: "Deutsch (German, Standard)",
      bible_folder: "deu1951",
      language_code: "deu",
    },
    {
      name: "Dhanki",
      bible_folder: "dhn",
      language_code: "dhn",
    },
    {
      name: "Dhao",
      bible_folder: "nfa",
      language_code: "nfa",
    },
    {
      name: "Didayi (Gata')",
      bible_folder: "gaq",
      language_code: "gaq",
    },
    {
      name: "Dieri",
      bible_folder: "dif",
      language_code: "dif",
    },
    {
      name: "Djinang",
      bible_folder: "dji",
      language_code: "dji",
    },
    {
      name: "Dongxiang",
      bible_folder: "sce",
      language_code: "sce",
    },
    {
      name: "Doromu-Koki",
      bible_folder: "kqc",
      language_code: "kqc",
    },
    {
      name: "Duya",
      bible_folder: "ldb",
      language_code: "ldb",
    },
    {
      name: "Eesti (Estonian, Standard)",
      bible_folder: "ekk",
      language_code: "ekk",
    },
    {
      name: "Ekajuk",
      bible_folder: "eka",
      language_code: "eka",
    },
    {
      name: "Esperanto",
      bible_folder: "epo",
      language_code: "epo",
    },
    {
      name: "Etulo",
      bible_folder: "utr",
      language_code: "utr",
    },
    {
      name: "Falam",
      bible_folder: "cfm",
      language_code: "cfm",
    },
    {
      name: "Fataleka",
      bible_folder: "far",
      language_code: "far",
    },
    {
      name: "Folopa",
      bible_folder: "ppo",
      language_code: "ppo",
    },
    {
      name: "Gamit",
      bible_folder: "gbl",
      language_code: "gbl",
    },
    {
      name: "Gamotso (Gamo)",
      bible_folder: "gmve",
      language_code: "gmv",
    },
    {
      name: "Gapapaiwa",
      bible_folder: "pwg",
      language_code: "pwg",
    },
    {
      name: "Gayil",
      bible_folder: "gyl",
      language_code: "gyl",
    },
    {
      name: "Geji",
      bible_folder: "gyz",
      language_code: "gyz",
    },
    {
      name: "Ghanongga",
      bible_folder: "ghn",
      language_code: "ghn",
    },
    {
      name: "Gilaki",
      bible_folder: "glk",
      language_code: "glk",
    },
    {
      name: "Glavda",
      bible_folder: "glwl",
      language_code: "glw",
    },
    {
      name: "Gohllaru (Holiya)",
      bible_folder: "hoy",
      language_code: "hoy",
    },
    {
      name: "Goofa",
      bible_folder: "gofe",
      language_code: "gof",
    },
    {
      name: "Gourma (Gourmanchéma)",
      bible_folder: "gux",
      language_code: "gux",
    },
    {
      name: "Gowlan",
      bible_folder: "goj",
      language_code: "goj",
    },
    {
      name: "Gowli",
      bible_folder: "gok",
      language_code: "gok",
    },
    {
      name: "Guduf-Gava",
      bible_folder: "gdf",
      language_code: "gdf",
    },
    {
      name: "Gugu Yimidhirr (Guugu Yimidhirr)",
      bible_folder: "kky",
      language_code: "kky",
    },
    {
      name: "Guguminjen (Kunjen)",
      bible_folder: "kjn",
      language_code: "kjn",
    },
    {
      name: "gujii",
      bible_folder: "gax",
      language_code: "gax",
    },
    {
      name: "Gwahatike",
      bible_folder: "dah",
      language_code: "dah",
    },
    {
      name: "Halbi",
      bible_folder: "hlb",
      language_code: "hlb",
    },
    {
      name: "Hassaniyya",
      bible_folder: "mey",
      language_code: "mey",
    },
    {
      name: "Havai (Ambae, East)",
      bible_folder: "omb",
      language_code: "omb",
    },
    {
      name: "Havu",
      bible_folder: "hav",
      language_code: "hav",
    },
    {
      name: "Hawu",
      bible_folder: "hvn",
      language_code: "hvn",
    },
    {
      name: "Helong",
      bible_folder: "hegNTpo",
      language_code: "heg",
    },
    {
      name: "Hona (Hwana)",
      bible_folder: "hwo",
      language_code: "hwo",
    },
    {
      name: "Hre",
      bible_folder: "hrebt",
      language_code: "hre",
    },
    {
      name: "Hruso",
      bible_folder: "hru",
      language_code: "hru",
    },
    {
      name: "Hrvatski (Croatian)",
      bible_folder: "hrv",
      language_code: "hrv",
    },
    {
      name: "Ikizu",
      bible_folder: "ikz",
      language_code: "ikz",
    },
    {
      name: "Ilocano",
      bible_folder: "iloulb",
      language_code: "ilo",
    },
    {
      name: "Ilonggo",
      bible_folder: "hil",
      language_code: "hil",
    },
    {
      name: "isiNdebele (Ndebele)",
      bible_folder: "nde",
      language_code: "nde",
    },
    {
      name: "Íslenska (Icelandic)",
      bible_folder: "isl",
      language_code: "isl",
    },
    {
      name: "Ivatan (Yaka)",
      bible_folder: "iyx",
      language_code: "iyx",
    },
    {
      name: "Jida (Bu)",
      bible_folder: "jid",
      language_code: "jid",
    },
    {
      name: "Jumjum",
      bible_folder: "jum",
      language_code: "jum",
    },
    {
      name: "Juray",
      bible_folder: "juy",
      language_code: "juy",
    },
    {
      name: "Kamano-Kafe (Kamano)",
      bible_folder: "kbq",
      language_code: "kbq",
    },
    {
      name: "Kapin",
      bible_folder: "tbx",
      language_code: "tbx",
    },
    {
      name: "Kapingamarangi",
      bible_folder: "kpg",
      language_code: "kpg",
    },
    {
      name: "Karo (Rawa) (Rawa)",
      bible_folder: "rwo-karo",
      language_code: "rwo",
    },
    {
      name: "Kese (Kisi)",
      bible_folder: "kiz",
      language_code: "kiz",
    },
    {
      name: "Kharam (Naga, Kharam)",
      bible_folder: "kfw",
      language_code: "kfw",
    },
    {
      name: "Kho (Bugun)",
      bible_folder: "bgg",
      language_code: "bgg",
    },
    {
      name: "Kiisanzu (Isanzu)",
      bible_folder: "isn",
      language_code: "isn",
    },
    {
      name: "Kikara (Kara)",
      bible_folder: "reg",
      language_code: "reg",
    },
    {
      name: "Kikuyu (Gikuyu)",
      bible_folder: "kik",
      language_code: "kik",
    },
    {
      name: "Kindengereko (Ndengereko)",
      bible_folder: "ndg",
      language_code: "ndg",
    },
    {
      name: "Kisafwa (Safwa)",
      bible_folder: "sbk",
      language_code: "sbk",
    },
    {
      name: "Kitaabua (Taabwa)",
      bible_folder: "tap",
      language_code: "tap",
    },
    {
      name: "Kituba",
      bible_folder: "mkw",
      language_code: "mkw",
    },
    {
      name: "Kivwanji (Vwanji)",
      bible_folder: "wbi",
      language_code: "wbi",
    },
    {
      name: "Kiyombi",
      bible_folder: "yom",
      language_code: "yom",
    },
    {
      name: "Kizalamo",
      bible_folder: "zajp",
      language_code: "zaj",
    },
    {
      name: "Koda",
      bible_folder: "cdz",
      language_code: "cdz",
    },
    {
      name: "Kolami (Vaghri)",
      bible_folder: "vgr",
      language_code: "vgr",
    },
    {
      name: "Konda Porja (Konda-Dora)",
      bible_folder: "kfcp",
      language_code: "kfc",
    },
    {
      name: "Kosrae (Kosraean)",
      bible_folder: "kos",
      language_code: "kos",
    },
    {
      name: "Koya",
      bible_folder: "kff",
      language_code: "kff",
    },
    {
      name: "Kreyòl Ayisyen (Haitian)",
      bible_folder: "hat",
      language_code: "hat",
    },
    {
      name: "Kupang Malay",
      bible_folder: "mkn",
      language_code: "mkn",
    },
    {
      name: "Kurama",
      bible_folder: "krh",
      language_code: "krh",
    },
    {
      name: "Kurti",
      bible_folder: "ktm",
      language_code: "ktm",
    },
    {
      name: "Kutu",
      bible_folder: "kdc",
      language_code: "kdc",
    },
    {
      name: "Kuturmi",
      bible_folder: "khj",
      language_code: "khj",
    },
    {
      name: "Kuuk Thayorre (Thayore)",
      bible_folder: "thd",
      language_code: "thd",
    },
    {
      name: "Kwara'ae",
      bible_folder: "kwf",
      language_code: "kwf",
    },
    {
      name: "Latine (Latin)",
      bible_folder: "latVUC",
      language_code: "lat",
    },
    {
      name: "lietuvių (Lithuanian)",
      bible_folder: "lit",
      language_code: "lit",
    },
    {
      name: "Lingála",
      bible_folder: "lin",
      language_code: "lin",
    },
    {
      name: "Lodha (Lodhi)",
      bible_folder: "lbm",
      language_code: "lbm",
    },
    {
      name: "Loxicha Zapotec (Zapotec, Loxicha)",
      bible_folder: "ztp",
      language_code: "ztp",
    },
    {
      name: "Luqa (Lungga)",
      bible_folder: "lga",
      language_code: "lga",
    },
    {
      name: "Luyana",
      bible_folder: "lyn",
      language_code: "lyn",
    },
    {
      name: "Maale (Male)",
      bible_folder: "mdyeth",
      language_code: "mdy",
    },
    {
      name: "Magyar",
      bible_folder: "hun",
      language_code: "hun",
    },
    {
      name: "Mahanji (Kinga)",
      bible_folder: "zgam",
      language_code: "zga",
    },
    {
      name: "Mahasui (Pahari, Mahasu)",
      bible_folder: "bfz",
      language_code: "bfz",
    },
    {
      name: "Makhuwa-Meetto",
      bible_folder: "mgh2016",
      language_code: "mgh",
    },
    {
      name: "Marghi South",
      bible_folder: "mfm",
      language_code: "mfm",
    },
    {
      name: "Mashi (Shi)",
      bible_folder: "shr",
      language_code: "shr",
    },
    {
      name: "Matengo",
      bible_folder: "mgv",
      language_code: "mgv",
    },
    {
      name: "Matumbi",
      bible_folder: "mgw",
      language_code: "mgw",
    },
    {
      name: "Matupi Chin (Chin, Matu)",
      bible_folder: "hlt",
      language_code: "hlt",
    },
    {
      name: "Mbe",
      bible_folder: "mfo",
      language_code: "mfo",
    },
    {
      name: "Mbula (Mbula-Bwazza)",
      bible_folder: "mbu",
      language_code: "mbu",
    },
    {
      name: "Melo",
      bible_folder: "mfxe",
      language_code: "mfx",
    },
    {
      name: "Meriam Mir (Meriam)",
      bible_folder: "ulk1902",
      language_code: "ulk",
    },
    {
      name: "Mori Atas",
      bible_folder: "mzq",
      language_code: "mzq",
    },
    {
      name: "Morokodo",
      bible_folder: "mgc",
      language_code: "mgc",
    },
    {
      name: "Mpoto",
      bible_folder: "mpa",
      language_code: "mpa",
    },
    {
      name: "Mum",
      bible_folder: "kqa",
      language_code: "kqa",
    },
    {
      name: "Mupun (Mwaghavul)",
      bible_folder: "sur",
      language_code: "sur",
    },
    {
      name: "Murrinhpatha (Murrinh-Patha)",
      bible_folder: "mwf2018",
      language_code: "mwf",
    },
    {
      name: "Mwera",
      bible_folder: "mwe",
      language_code: "mwe",
    },
    {
      name: "Mynmar language (Burmese)",
      bible_folder: "mya",
      language_code: "mya",
    },
    {
      name: "Nagamiz (Naga Pidgin)",
      bible_folder: "nag",
      language_code: "nag",
    },
    {
      name: "Nali",
      bible_folder: "nss",
      language_code: "nss",
    },
    {
      name: "Natqgu (Natügu)",
      bible_folder: "ntu",
      language_code: "ntu",
    },
    {
      name: "Nchane (Ncane)",
      bible_folder: "ncr",
      language_code: "ncr",
    },
    {
      name: "Ndamba",
      bible_folder: "ndj",
      language_code: "ndj",
    },
    {
      name: "Ndendeule",
      bible_folder: "dne",
      language_code: "dne",
    },
    {
      name: "Ndondehamba (Ndonde Hamba)",
      bible_folder: "njd",
      language_code: "njd",
    },
    {
      name: "Ndwewe",
      bible_folder: "nww",
      language_code: "nww",
    },
    {
      name: "Nend",
      bible_folder: "anh",
      language_code: "anh",
    },
    {
      name: "Ngarrindjeri (Narrinyeri)",
      bible_folder: "nay",
      language_code: "nay",
    },
    {
      name: "Ngindo",
      bible_folder: "nnq",
      language_code: "nnq",
    },
    {
      name: "Nguu",
      bible_folder: "ngp",
      language_code: "ngp",
    },
    {
      name: "Nii",
      bible_folder: "nii",
      language_code: "nii",
    },
    {
      name: "Nkangala",
      bible_folder: "nkn",
      language_code: "nkn",
    },
    {
      name: "Norsk: Bokmål (Norwegian)",
      bible_folder: "noblb",
      language_code: "nob",
    },
    {
      name: "Nukna",
      bible_folder: "klt",
      language_code: "klt",
    },
    {
      name: "Ogea",
      bible_folder: "eri",
      language_code: "eri",
    },
    {
      name: "Oyda",
      bible_folder: "oyde",
      language_code: "oyd",
    },
    {
      name: "Paama",
      bible_folder: "pma",
      language_code: "pma",
    },
    {
      name: "Padoe",
      bible_folder: "pdo",
      language_code: "pdo",
    },
    {
      name: "Pali (Bareli, Palya)",
      bible_folder: "bpx",
      language_code: "bpx",
    },
    {
      name: "Patep",
      bible_folder: "ptp",
      language_code: "ptp",
    },
    {
      name: "Pengu (Pengo)",
      bible_folder: "peg",
      language_code: "peg",
    },
    {
      name: "Pogolo",
      bible_folder: "poy",
      language_code: "poy",
    },
    {
      name: "Pohnpeian",
      bible_folder: "pon",
      language_code: "pon",
    },
    {
      name: "Polci",
      bible_folder: "plj",
      language_code: "plj",
    },
    {
      name: "Powari",
      bible_folder: "pwr",
      language_code: "pwr",
    },
    {
      name: "Pular",
      bible_folder: "fuf",
      language_code: "fuf",
    },
    {
      name: "Pura (Blagar)",
      bible_folder: "beu",
      language_code: "beu",
    },
    {
      name: "Purum",
      bible_folder: "pub",
      language_code: "pub",
    },
    {
      name: "Qach’abel (K'iche')",
      bible_folder: "quctt",
      language_code: "quc",
    },
    {
      name: "Qaqet",
      bible_folder: "byx",
      language_code: "byx",
    },
    {
      name: "Ramoaaina",
      bible_folder: "rai",
      language_code: "rai",
    },
    {
      name: "Rana Tharu (Tharu, Rana)",
      bible_folder: "thr",
      language_code: "thr",
    },
    {
      name: "Rangi",
      bible_folder: "lag",
      language_code: "lag",
    },
    {
      name: "Relli (Reli)",
      bible_folder: "rei",
      language_code: "rei",
    },
    {
      name: "Rohingya",
      bible_folder: "rhgc",
      language_code: "rhg",
    },
    {
      name: "Română (Romanian)",
      bible_folder: "ronbtf",
      language_code: "ron",
    },
    {
      name: "Romanes (Romani, Carpathian)",
      bible_folder: "rmc",
      language_code: "rmc",
    },
    {
      name: "Romani",
      bible_folder: "rmna",
      language_code: "rmn",
    },
    {
      name: "Rote Dela (Dela-Oenale)",
      bible_folder: "row",
      language_code: "row",
    },
    {
      name: "Rote Lole (Lole)",
      bible_folder: "llg",
      language_code: "llg",
    },
    {
      name: "Rote Rikou (Rikou)",
      bible_folder: "rgu",
      language_code: "rgu",
    },
    {
      name: "Rote Tii (Tii)",
      bible_folder: "txq",
      language_code: "txq",
    },
    {
      name: "Rotokas",
      bible_folder: "roo",
      language_code: "roo",
    },
    {
      name: "Roviana",
      bible_folder: "rug",
      language_code: "rug",
    },
    {
      name: "Sa'a",
      bible_folder: "apb",
      language_code: "apb",
    },
    {
      name: "Saafi-Saafi",
      bible_folder: "sav",
      language_code: "sav",
    },
    {
      name: "Saisai (Nimoa)",
      bible_folder: "nmws",
      language_code: "nmw",
    },
    {
      name: "Sakechep (Sakachep)",
      bible_folder: "sch",
      language_code: "sch",
    },
    {
      name: "Saliba",
      bible_folder: "sbe",
      language_code: "sbe",
    },
    {
      name: "Sanga",
      bible_folder: "xsn",
      language_code: "xsn",
    },
    {
      name: "Sankaran Maninka",
      bible_folder: "msc",
      language_code: "msc",
    },
    {
      name: "Sanskrit",
      bible_folder: "sandev",
      language_code: "san",
    },
    {
      name: "Sari",
      bible_folder: "asj",
      language_code: "asj",
    },
    {
      name: "Satawalese",
      bible_folder: "stw",
      language_code: "stw",
    },
    {
      name: "Saveeng (Mutu)",
      bible_folder: "tuc-t",
      language_code: "tuc",
    },
    {
      name: "Sena",
      bible_folder: "seh",
      language_code: "seh",
    },
    {
      name: "Shatt",
      bible_folder: "shj",
      language_code: "shj",
    },
    {
      name: "Sholaga",
      bible_folder: "sle",
      language_code: "sle",
    },
    {
      name: "Shwe Palaung (Palaung, Shwe)",
      bible_folder: "pll",
      language_code: "pll",
    },
    {
      name: "Siksiká (Blackfoot)",
      bible_folder: "bla",
      language_code: "bla",
    },
    {
      name: "Siyin Chin (Chin, Siyin)",
      bible_folder: "csy",
      language_code: "csy",
    },
    {
      name: "Slovenčina (Slovak)",
      bible_folder: "slk",
      language_code: "slk",
    },
    {
      name: "Sob Dora (Sop)",
      bible_folder: "urw",
      language_code: "urw",
    },
    {
      name: "Somau Karia",
      bible_folder: "six",
      language_code: "six",
    },
    {
      name: "Southeast Ambrym (Ambrym, Southeast)",
      bible_folder: "tvk",
      language_code: "tvk",
    },
    {
      name: "Southeastern Kolami (Kolami, Southeastern)",
      bible_folder: "nit",
      language_code: "nit",
    },
    {
      name: "Sudanese Creole Arabic (Arabic, Sudanese Creole)",
      bible_folder: "pga",
      language_code: "pga",
    },
    {
      name: "Sudest",
      bible_folder: "tgo",
      language_code: "tgo",
    },
    {
      name: "Suomi (Finnish)",
      bible_folder: "fin",
      language_code: "fin",
    },
    {
      name: "Tagakaulo",
      bible_folder: "klg",
      language_code: "klg",
    },
    {
      name: "Tagin",
      bible_folder: "tgj",
      language_code: "tgj",
    },
    {
      name: "Takuu",
      bible_folder: "nho",
      language_code: "nho",
    },
    {
      name: "Takwane",
      bible_folder: "tke",
      language_code: "tke",
    },
    {
      name: "Tandroy (Malagasy, Tandroy-Mahafaly)",
      bible_folder: "tdx",
      language_code: "tdx",
    },
    {
      name: "Tarok",
      bible_folder: "yer",
      language_code: "yer",
    },
    {
      name: "Taupota",
      bible_folder: "tpa",
      language_code: "tpa",
    },
    {
      name: "Tavoyan",
      bible_folder: "tvn",
      language_code: "tvn",
    },
    {
      name: "Tay (Tai)",
      bible_folder: "taw",
      language_code: "taw",
    },
    {
      name: "Teke-Tyee",
      bible_folder: "tyx",
      language_code: "tyx",
    },
    {
      name: "Tetun Dili",
      bible_folder: "tdt",
      language_code: "tdt",
    },
    {
      name: "Thai Phum (Chin, Thaiphum)",
      bible_folder: "cth",
      language_code: "cth",
    },
    {
      name: "Thur",
      bible_folder: "lth",
      language_code: "lth",
    },
    {
      name: "Tichurong",
      bible_folder: "tcn",
      language_code: "tcn",
    },
    {
      name: "Tiếng Việt (Vietnamese)",
      bible_folder: "vie1934",
      language_code: "vie",
    },
    {
      name: "Tifal",
      bible_folder: "tif",
      language_code: "tif",
    },
    {
      name: "Timap (Amo)",
      bible_folder: "amo",
      language_code: "amo",
    },
    {
      name: "Toka-Leya-Dombe (Dombe)",
      bible_folder: "dov",
      language_code: "dov",
    },
    {
      name: "Tongan",
      bible_folder: "ton",
      language_code: "ton",
    },
    {
      name: "Totcha (Naga, Tutsa)",
      bible_folder: "tvt",
      language_code: "tvt",
    },
    {
      name: "Ts‘əxna miz (Tsakhur)",
      bible_folder: "tkr",
      language_code: "tkr",
    },
    {
      name: "Tsishingini",
      bible_folder: "tsw",
      language_code: "tsw",
    },
    {
      name: "Tswana (Setswana)",
      bible_folder: "tsn",
      language_code: "tsn",
    },
    {
      name: "Tuma-Irumu",
      bible_folder: "iou",
      language_code: "iou",
    },
    {
      name: "Tutun Belu (Tetun)",
      bible_folder: "tet",
      language_code: "tet",
    },
    {
      name: "Urat",
      bible_folder: "urt",
      language_code: "urt",
    },
    {
      name: "ut-Ma'in",
      bible_folder: "gel",
      language_code: "gel",
    },
    {
      name: "Uyghur tili (Uyghur)",
      bible_folder: "uigara",
      language_code: "uig",
    },
    {
      name: "Vaagri Booli",
      bible_folder: "vaa",
      language_code: "vaa",
    },
    {
      name: "Vidunda",
      bible_folder: "vid",
      language_code: "vid",
    },
    {
      name: "Waddar",
      bible_folder: "wbq",
      language_code: "wbq",
    },
    {
      name: "Waima",
      bible_folder: "rro",
      language_code: "rro",
    },
    {
      name: "Waja",
      bible_folder: "wja",
      language_code: "wja",
    },
    {
      name: "Wala",
      bible_folder: "lgl",
      language_code: "lgl",
    },
    {
      name: "Waskia",
      bible_folder: "wsk",
      language_code: "wsk",
    },
    {
      name: "Wolio",
      bible_folder: "wlo",
      language_code: "wlo",
    },
    {
      name: "Worrorra",
      bible_folder: "wro",
      language_code: "wro",
    },
    {
      name: "Yaka",
      bible_folder: "yaf",
      language_code: "yaf",
    },
    {
      name: "Yalë (Yale)",
      bible_folder: "nce",
      language_code: "nce",
    },
    {
      name: "Yamap",
      bible_folder: "ymp",
      language_code: "ymp",
    },
    {
      name: "Yansi",
      bible_folder: "yns",
      language_code: "yns",
    },
    {
      name: "Yapese",
      bible_folder: "yap",
      language_code: "yap",
    },
    {
      name: "Yau",
      bible_folder: "yuw",
      language_code: "yuw",
    },
    {
      name: "Yemsa",
      bible_folder: "jnje",
      language_code: "jnj",
    },
    {
      name: "Yindjibarndi",
      bible_folder: "yij",
      language_code: "yij",
    },
    {
      name: "Yipunu",
      bible_folder: "puu",
      language_code: "puu",
    },
    {
      name: "Zanaki",
      bible_folder: "zak",
      language_code: "zak",
    },
    {
      name: "Zia",
      bible_folder: "zia",
      language_code: "zia",
    },
    {
      name: "Zigua",
      bible_folder: "ziw",
      language_code: "ziw",
    },
    {
      name: "Zinza",
      bible_folder: "zin",
      language_code: "zin",
    },
    {
      name: "Ἑλληνική (Greek, Ancient)",
      bible_folder: "grcbrent",
      language_code: "grc",
    },
    {
      name: "ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ (Coptic)",
      bible_folder: "copbhc",
      language_code: "cop",
    },
    {
      name: "русский (Russian)",
      bible_folder: "russyn",
      language_code: "rus",
    },
    {
      name: "Српски/ Srpski (Serbian)",
      bible_folder: "srponspc",
      language_code: "srp",
    },
    {
      name: "Українська (Ukrainian)",
      bible_folder: "ukrfb",
      language_code: "ukr",
    },
    {
      name: "יידיש מזרחית (Yiddish, Eastern)",
      bible_folder: "ydd",
      language_code: "ydd",
    },
    {
      name: "עברית (Hebrew)",
      bible_folder: "heb",
      language_code: "heb",
    },
    {
      name: "עברית (Hebrew)",
      bible_folder: "hbo",
      language_code: "hbo",
    },
    {
      name: "كوردی سۆرانی (Central Kurdish)",
      bible_folder: "ckb",
      language_code: "ckb",
    },
    {
      name: "अहिराणी‎ (Ahirani)",
      bible_folder: "ahr",
      language_code: "ahr",
    },
    {
      name: "नेपाली",
      bible_folder: "npioncb",
      language_code: "npi",
    },
    {
      name: "भटियाली‎ (Bhattiyali)",
      bible_folder: "bht",
      language_code: "bht",
    },
    {
      name: "भद्रवाही‎ (Bhadrawahi)",
      bible_folder: "bhd",
      language_code: "bhd",
    },
    {
      name: "हरियाणवी‎ (Haryanvi)",
      bible_folder: "bgc",
      language_code: "bgc",
    },
    {
      name: "অসমীয়া (Assamese)",
      bible_folder: "asmfb",
      language_code: "asm",
    },
    {
      name: "মুন্ডা‎ (Muɳɖa) (Munda)",
      bible_folder: "unx",
      language_code: "unx",
    },
    {
      name: "ଦେଶିଆ (Desiya)",
      bible_folder: "dso",
      language_code: "dso",
    },
    {
      name: "ବଡ଼ ପରଜା (Bodo Parja)",
      bible_folder: "bdv",
      language_code: "bdv",
    },
    {
      name: "కువి (Kuvi)",
      bible_folder: "kxv",
      language_code: "kxv",
    },
    {
      name: "മലയാളം (Malayalam)",
      bible_folder: "mal",
      language_code: "mal",
    },
    {
      name: "ရခိုင် (Rakhine)",
      bible_folder: "rki",
      language_code: "rki",
    },
    {
      name: "한국인 (Korean)",
      bible_folder: "kor",
      language_code: "kor",
    },
    {
      name: "日本語 (Japanese)",
      bible_folder: "jpn1965",
      language_code: "jpn",
    },
  ];
  return v;
}
