export function firebase_config_get() {
  // authDomain, projectId, storageBucket are all generated by Firebase from
  // the project name, so they are derived here. The remaining values are
  // opaque ids Firebase assigns independently - nothing to derive them from.
  let project_name = firebase_project_name_jg();
  let firebase_config = {
    apiKey: "AIzaSyABi8aveEhWeD6GyRXj9FUqu_aDWxhuBGQ",
    authDomain: firebase_auth_domain_project(project_name),
    projectId: project_name,
    storageBucket: firebase_storage_url_project(project_name),
    messagingSenderId: "879920885833",
    appId: "1:879920885833:web:2f5a3cb39a398516690f98",
    measurementId: "G-B2XTX9NJCZ",
  };
  return firebase_config;
}
