import { watching_ensure } from "./watching_ensure.mjs";
import { function_worker_pool_ready } from "./function_worker_pool_ready.mjs";
import { worker_job_run } from "./worker_job_run.mjs";
import { modulo } from "./modulo.mjs";
import { property_get } from "./property_get.mjs";
("Run a function on a warm worker instead of spawning a node process per call.");
("");
("Boots are paid per EDIT, not per CALL. Measured on this repo: ~5.4 API");
("requests/second against ~3 file saves/minute typical (~11/minute at peak), so");
("this is ~30x fewer node boots at the worst observed moment and ~100x typical.");
("It also cannot do worse than the spawn-per-call it replaces: boot count is");
("bounded by min(edit rate, call rate), so heavy parallel editing degrades it");
("toward the old cost and never past it.");
("");
("Hot reload is preserved by RETIRING the pool on any watched change: a worker");
("only serves code it booted with, so a fresh worker is the reload. Note the");
("tempting shortcut does not work — import() cache-busting with ?v=<mtime> only");
("re-evaluates the ENTRY module, while transitive deps keep their plain");
("specifiers and stay cached, so editing a dependency would silently go stale.");
("");
("The pool watches files ITSELF rather than being signalled by the love_watch");
("daemon, because that daemon may be down (see CLAUDE.md) and a missed signal");
("would mean silently serving stale code — the exact failure hot reload exists");
("to prevent.");
("");
("How many workers, how long the quiet after a save lasts, the count of");
("retirements, which pool is the current one and whether the watcher has been");
("started are each kept under their own name now. They were five things written");
("at the top of this file, and the top of a file is a place only the file itself");
("can reach — so every helper here that read one was stuck in here with them,");
("and the pass that gives a function its own file refused this whole file rather");
("than break them apart. Named separately they are reachable, and the count and");
("the pool are handed back as boxes rather than as their contents, because what");
("crosses a file boundary is a copy unless it is a thing.");
export async function function_worker_pool_run(f_name, args) {
  await watching_ensure();
  let ready = function_worker_pool_ready();
  let broken = property_get(ready, "broken");
  if (broken) {
    throw new Error(broken);
  }
  let workers = property_get(ready, "workers");
  let next = property_get(ready, "next");
  ("Round-robin. One worker could serve every request concurrently since node");
  ("multiplexes async work, but a CPU-bound function would then block the whole");
  ("event loop for everyone — several processes keep that blast radius small.");
  let worker = workers[modulo(next, workers.length)];
  ready.next = next + 1;
  let r = await worker_job_run(worker, f_name, args);
  return r;
}
