import { fn_name } from "./fn_name.mjs";
export function functions_permission_seams() {
  "The functions that write Claude's own permission rules — the settings file the harness reads to decide what runs without asking, and the source list that file is generated from. Reaching one of these is what makes a command able to widen what commands are allowed.";
  "This is the third set the reachability walk is asked against, and it asks a different question from the other two. Reaching a shell means the arguments could become a command line; reaching a writer means the call costs something that cannot be taken back; reaching one of these means the call can hand out further calls that never ask. That last one escalates rather than merely acts, so an automatic approval for it approves everything it goes on to approve.";
  ("Reaching one of these is a reason to refuse a grant only where there are arguments to steer it, exactly as with the command-running set. Two of these very names already hold standing rules and deserve them: both take nothing and render their file from committed source, so a rule covering every argument they are ever handed covers nothing they would not do anyway, and changing what they write means editing the source first, which is a visible edit. The gap the condition leaves is an argument-free function that writes rules from something outside the source — a log, a network answer — which would pass. One was written since: the restorer of departed grants takes nothing and reads which approvals to put back off the settings file, and it was reported clean to grant for as long as it existed. What answered it was neither the condition nor this list, both of which are unchanged. It was a gate, ",
    fn_name("permission_writers_gate_run"),
    ", which demands that everything reaching one of these names is either refused for a reason the check can see, or stands on a short list of exceptions argued for in the commit that adds it — so the reading that found this one is not owed again.");
  ("The names are spelled rather than imported, which the other two rosters do not do. Importing them would give this function an edge to the very seams it names, and every checker that consults the roster would inherit that edge and be reported as writing permission rules itself — the roster of command seams needed a line in the ignored-imports list for exactly that reason. Spelling a name follows a rename just as well, because the rename pass rewrites these marked strings.");
  ("The third name is the one that proves the list has to be written by hand rather than derived. It used to append a rule straight into the settings file through the ordinary file writer, so nothing about its imports marked it out from the hundreds of functions that write some file or other, and it was found by reading it rather than by following anything.");
  ("It no longer writes that way. It hands the granted names to the one funnel that writes the list and regenerates the file from it, so it now reaches the other two names here and a reader following the generators would arrive at it. That makes its place on this list redundant for the reachability walk rather than load-bearing, and it keeps that place anyway: what the walk needs and what a reader needs are different, and a roster of the ways a rule gets written should still name the one place a rule is written for a name that arrived while the program was running instead of out of committed source.");
  ("Why it wrote directly is worth keeping, because it is what the funnel exists to prevent. Writing the settings file alone left the granted-names list — the source the file is generated from — never opened, so every rule written that way was thrown away by the next thing that regenerated the file. Three approvals the human had already given departed exactly so before the cause was found.");
  let f_name = fn_name("permission_settings_allow_write_from");
  let f_name2 = fn_name("permission_grant_names_write");
  let f_name3 = fn_name("permission_rule_grant_checked_context");
  let names = [f_name, f_name2, f_name3];
  return names;
}
