export function g_arc_style() {
  "How every arc is to be written, said once here so that a fault found in one is answered for all the ones nobody has written yet.";
  "THIS EXISTS BECAUSE A REVIEW NOTE WAS BEING SPENT TWICE AND BANKED NEVER. A note names one line, the line is mended, the note is cleared, and the next batch is written by somebody who never saw it - so a fault that was systematic comes back at full strength and is found again, by a person, one line at a time. Every rule below was paid for by a reader already; the point of writing them down is that nobody pays for them a second time.";
  "WHICH IS WHY MORE ARCS WAIT ON THE REVIEW OF THE ONES THAT EXIST. Generating ahead of the reading is not neutral - it multiplies whatever the reading has not caught yet, and every copy of the fault has to be found and mended by hand afterwards. The reading is the thing that makes the next batch cheaper, so it goes first.";
  "A RULE HERE MUST HAVE COME FROM A READER, never from taste. The test for promoting a note is whether it RECURS - the same defect in more than one line, or found by more than one person. One line that came out wrong is a line to mend; the same wrongness three times is a rule that was missing. Nothing may be added here on the grounds that it sounds right.";
  "WHAT IS WRONG, NEVER WHAT TO SAY INSTEAD - the same shape the note store itself is built on, and for the same reason it gives there: a rule saying what a line should say has done the writing, and the writer is then needed again for every line after. A rule saying what goes wrong fires on lines nobody has looked at yet.";
  "EVERY RULE IS RENDERED INTO THE ARC PROMPT, and that is the whole point of gathering them. A rule kept here and not said in the prompt is a rule the next writing call never hears, which is the same as not having written it down - so nothing may be added here that is meant to stay behind, and nothing may be spelled out again by hand in the prompt beside what this already says.";
  "THE EYEWITNESS RULE READS AS THE PROMPT'S OWN WORDS BECAUSE IT WAS THE PROMPT'S OWN WORDS. It sat in the prompt under what not to write, in a longer and better form than the one first drafted here, so it was moved across rather than summarised - a shorter restatement would have been the one place this gathering could lose something.";
  let rules = [
    {
      rule: "The player never saw Jesus. Somebody who was sent here told the player the gospel, the same way the player is telling this person now. So the person does not speak to the player as somebody who saw or heard or touched him, does not ask the player what he was like, and does not treat the player's answers as things the player watched happen. Where a passage itself says that its writer saw and touched, that is the writer of the letter speaking, and the person may say so. What they may not do is put the player among the ones who were there.",
      why: "1 John opens on a claim only John can make - heard, seen, gazed upon, touched with our hands. A line that puts the player inside that WE turns the reader into a witness of something they were not at, and the whole weight of the letter is that the witness is somebody else and the reader is trusting them. A character may long to have seen Him; the player may not be written as having.",
      from: "raised by the human on 1JN01 while reading the arcs, with the verse quoted back. Two written arcs had already assumed otherwise.",
    },
    {
      rule: "A word most readers know as an ADJECTIVE may not be used as a bare noun. Say the thing plainly: 'the sin I have hidden', never 'the wrong that is mine'. Adjective uses are fine - 'she has done nothing wrong' is clear.",
      why: "the reader has to work out which sense is meant, and a reader whose first language is not English often cannot. Vagueness here is not gentleness: the game is about sin and forgiveness, and somebody who cannot tell what the word refers to cannot connect the line to the verse that answers it.",
      from: "six notes across three people on 1JN01. The same arcs already said 'sin' plainly elsewhere, so the vague half was drift rather than a choice - which is what made it a rule instead of a fix.",
    },
    {
      rule: "The English is written toward people who read English, and carries nothing that only works for one country. What a line assumes about money, weather, food, schooling or law has to hold wherever it is read, or be part of the Bible's own setting.",
      why: "the arcs are translated, and a line resting on something local either goes wrong in translation or has to be rewritten per language. The Bible's own setting travels because it is ancient and shared; a modern local detail does not.",
      from: "given by the human as a standing instruction while reviewing word pictures and definitions",
    },
    {
      rule: "COUNT THE STEPS OF INFERENCE THE PLAYER IS LEFT TO MAKE, and leave none of them unsaid. Zero steps is the person and the passage on the same root - the person says cleanse and the passage says cleanses, or says clean, or says cleansing. One step is the person saying death where the passage says blood, and the step is that a death is where blood is shed. Every step past zero has to be spoken in the after, where the person picks the passage's own word up and sets it beside their own.",
      why: "a step nobody takes aloud is a step the player takes silently or not at all, and the player is somebody who has never read the Bible. The player also cannot take it aloud: they never explain, and are not meant to - their whole utterance is the passage they chose. So the after is the only place a step can be said, and an empty after on a turn that had one is the step going missing rather than the person carrying straight on. It also keeps the connecting with somebody entitled to do it: a person granting a point has been changed by the passage, whereas a player explaining the passage has done that person's thinking for them.",
      from: "raised by the human on 1JN01, on the turn asking why a death of His would do anything about my sin, answered by 1 John 1:7 and its blood that cleanses - with an empty after. First written as a rule about a DIFFERENT WORD and corrected by the human on the spot: a different form of the same root is no step at all, so the thing being counted is inferences and not words. The two turns of the same arc that DO carry an after both already work this way - Confess. Not pay. off 1 John 1:9, and No darkness at all. off 1 John 1:5 - so the shape was there and the turn had simply skipped it.",
    },
    {
      rule: "A WORD THE PASSAGE OWNS IS USED IN THE PASSAGE'S SENSE AND IN NO OTHER SENSE ANYWHERE IN THE ARC. Where the everyday sense is what the person means - dark for not knowing, dark for gone silent on somebody - a different word is used for it. An idiom built on such a word is out for the same reason.",
      why: "the turn rests on the person picking the passage's word up, and the pick-up only lands if the word means one thing. A second job for it elsewhere makes the echo read as a pun, and the reader cannot tell which sense was meant. An idiom is worse than a second sense: it carries a meaning the verse never had, and it is the first thing to break when the arc is translated.",
      from: "found by reading the three written 1JN01 arcs against the four rules above. Dark was doing three jobs across all three people - the moral darkness of 1 John 1:5, in the dark about Him for not knowing, and go dark on me for going silent - and twice as a bare noun besides, which is the rule above it failing in the same word.",
    },
  ];
  return rules;
}
