import { emoji_pray } from "./emoji_pray.mjs";
import { emoji_sunrise } from "./emoji_sunrise.mjs";
import { emoji_heart } from "./emoji_heart.mjs";
import { text_combine } from "./text_combine.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
import { g_name_jesus } from "./g_name_jesus.mjs";
import { emoji_cross } from "./emoji_cross.mjs";
import { emoji_book_open } from "./emoji_book_open.mjs";
import { emoji_family } from "./emoji_family.mjs";
import { emoji_hourglass } from "./emoji_hourglass.mjs";
import { emoji_home } from "./emoji_home.mjs";
import { emoji_dove } from "./emoji_dove.mjs";
import { emoji_rainbow } from "./emoji_rainbow.mjs";
import { emoji_bread } from "./emoji_bread.mjs";
import { emoji_crown } from "./emoji_crown.mjs";
export function g_thanks_gratitude() {
  "the pool of short, person-neutral thanksgivings for the spontaneous gratitude prayer menu — each is {emoji, text}: a topical (mostly by-theme) emoji + a thing to thank God for, anytime. the menu shuffles these and shows a few (no back-to-back set overlap); picking one prays it. no meter, no reward (gratitude is spontaneous, 1 Thess 5:18)";
  let thanks = [
    { emoji: emoji_bread(), text: "God, thank You for enough food to stay alive today" },
    { emoji: emoji_bread(), text: "God, thank You for clean water to drink" },
    { emoji: emoji_bread(), text: "God, thank You for clothes to wear" },
    { emoji: emoji_bread(), text: "God, thank You for a roof over my head" },
    { emoji: emoji_bread(), text: "God, thank You for my daily bread" },
    { emoji: emoji_bread(), text: "God, thank You for work to do with my hands" },
    { emoji: emoji_bread(), text: "God, thank You for enough for my needs, and often more" },
    { emoji: emoji_bread(), text: "God, thank You for the harvest that comes from the earth" },
    { emoji: emoji_bread(), text: "God, thank You for warmth when the days are cold" },
    { emoji: emoji_bread(), text: "God, thank You for provision I did not earn" },
    { emoji: emoji_cross(), text: text_combine_multiple(["God, thank You for saving me through ", g_name_jesus()]) },
    { emoji: emoji_cross(), text: text_combine_multiple(["God, thank You for the cross where ", g_name_jesus(), " died in my place"]) },
    { emoji: emoji_cross(), text: "God, thank You for forgiving all my sins" },
    { emoji: emoji_cross(), text: "God, thank You for grace I could never earn" },
    { emoji: emoji_cross(), text: "God, thank You for adopting me as Your own child" },
    { emoji: emoji_cross(), text: text_combine_multiple(["God, thank You for the blood of ", g_name_jesus(), " that makes me clean"]) },
    { emoji: emoji_cross(), text: text_combine_multiple(["God, thank You for raising ", g_name_jesus(), " from the dead"]) },
    { emoji: emoji_cross(), text: "God, thank You that there is no condemnation for those in Christ" },
    { emoji: emoji_cross(), text: "God, thank You for rescuing me out of the darkness" },
    { emoji: emoji_cross(), text: "God, thank You for writing my name in the book of life" },
    { emoji: emoji_cross(), text: "God, thank You for making me new" },
    { emoji: emoji_book_open(), text: "God, thank You for Your word to guide me" },
    { emoji: emoji_book_open(), text: "God, thank You for Your promises that never fail" },
    { emoji: emoji_book_open(), text: "God, thank You for the truth that sets me free" },
    { emoji: emoji_book_open(), text: "God, thank You for Scripture to light my path" },
    { emoji: emoji_book_open(), text: "God, thank You for Your commands, which are for my good" },
    { emoji: emoji_book_open(), text: text_combine_multiple(["God, thank You for the good news of ", g_name_jesus()]) },
    { emoji: emoji_book_open(), text: "God, thank You that I can read Your word" },
    { emoji: emoji_book_open(), text: "God, thank You for Your word that stands forever" },
    { emoji: emoji_book_open(), text: "God, thank You for the wisdom You give when I ask" },
    { emoji: emoji_book_open(), text: "God, thank You for those who taught me Your word" },
    { emoji: emoji_dove(), text: "God, thank You for Your Spirit living within me" },
    { emoji: emoji_dove(), text: "God, thank You for the Comforter You sent to me" },
    { emoji: emoji_dove(), text: "God, thank You for leading me one step at a time" },
    { emoji: emoji_dove(), text: "God, thank You for the peace that guards my heart" },
    { emoji: emoji_dove(), text: "God, thank You for correcting me gently when I stray" },
    { emoji: emoji_dove(), text: "God, thank You for the gifts Your Spirit gives" },
    { emoji: emoji_dove(), text: "God, thank You for helping me pray when I have no words" },
    { emoji: emoji_dove(), text: "God, thank You for growing good fruit in me" },
    { emoji: emoji_dove(), text: "God, thank You for sealing me as Your own" },
    { emoji: emoji_dove(), text: "God, thank You for a presence that never leaves me" },
    { emoji: emoji_family(), text: "God, thank You for the people You put around me" },
    { emoji: emoji_family(), text: "God, thank You for friends who point me to You" },
    { emoji: emoji_family(), text: "God, thank You for the family of believers" },
    { emoji: emoji_family(), text: "God, thank You for everyone who prays for me" },
    { emoji: emoji_family(), text: "God, thank You for someone to share a meal with" },
    { emoji: emoji_family(), text: "God, thank You for unexpected kindness from strangers" },
    { emoji: emoji_family(), text: "God, thank You for those who forgive me" },
    { emoji: emoji_family(), text: "God, thank You for the church, Your own body" },
    { emoji: emoji_family(), text: "God, thank You for everyone who first told me about You" },
    { emoji: emoji_family(), text: "God, thank You for love that reflects Your love" },
    { emoji: text_combine(emoji_sunrise(), emoji_heart()), text: "God, thank You for another day to love" },
    { emoji: emoji_sunrise(), text: "God, thank You for the sunrise each morning" },
    { emoji: emoji_sunrise(), text: "God, thank You for the beauty spread across the earth" },
    { emoji: emoji_sunrise(), text: "God, thank You for the turning of the seasons" },
    { emoji: emoji_sunrise(), text: "God, thank You for the stars, which You named" },
    { emoji: emoji_sunrise(), text: "God, thank You for fresh air to breathe" },
    { emoji: emoji_sunrise(), text: "God, thank You for birdsong at the break of day" },
    { emoji: emoji_sunrise(), text: "God, thank You for rain that waters the ground" },
    { emoji: emoji_sunrise(), text: "God, thank You for mountains and seas that show Your glory" },
    { emoji: emoji_sunrise(), text: "God, thank You for the wonder woven through creation" },
    { emoji: emoji_heart(), text: "God, thank You for breath in my lungs" },
    { emoji: emoji_heart(), text: "God, thank You for a heart that keeps beating" },
    { emoji: emoji_heart(), text: "God, thank You for healing when I am sick" },
    { emoji: emoji_heart(), text: "God, thank You for eyes to see Your world" },
    { emoji: emoji_heart(), text: "God, thank You for ears to hear voices and music" },
    { emoji: emoji_heart(), text: "God, thank You for strength for the tasks of today" },
    { emoji: emoji_heart(), text: "God, thank You for hands to work and to help" },
    { emoji: emoji_heart(), text: "God, thank You for a mind to think and to know" },
    { emoji: emoji_heart(), text: "God, thank You for the good gift of being alive" },
    { emoji: emoji_heart(), text: "God, thank You for feet to carry me where I am needed" },
    { emoji: emoji_crown(), text: "God, thank You for Your faithfulness that never fails" },
    { emoji: emoji_crown(), text: "God, thank You for mercy that is new every morning" },
    { emoji: emoji_crown(), text: "God, thank You for Your steadfast, unchanging love" },
    { emoji: emoji_crown(), text: "God, thank You for Your holiness and majesty" },
    { emoji: emoji_crown(), text: "God, thank You for Your power over all things" },
    { emoji: emoji_crown(), text: "God, thank You for Your justice that sets things right" },
    { emoji: emoji_crown(), text: "God, thank You for Your goodness in every season" },
    { emoji: emoji_crown(), text: "God, thank You that You are a King who came to serve" },
    { emoji: emoji_crown(), text: "God, thank You that You stay the same when all else changes" },
    { emoji: emoji_crown(), text: "God, thank You that You reign over everything I fear" },
    { emoji: emoji_rainbow(), text: "God, thank You for hope beyond this life" },
    { emoji: emoji_rainbow(), text: "God, thank You for the home You are preparing" },
    { emoji: emoji_rainbow(), text: "God, thank You for the promise of no more tears" },
    { emoji: emoji_rainbow(), text: "God, thank You for the resurrection to come" },
    { emoji: emoji_rainbow(), text: text_combine_multiple(["God, thank You that I will see ", g_name_jesus(), " face to face one day"]) },
    { emoji: emoji_rainbow(), text: "God, thank You that death is not the end" },
    { emoji: emoji_rainbow(), text: "God, thank You for an inheritance that never fades" },
    { emoji: emoji_rainbow(), text: text_combine_multiple(["God, thank You for the day ", g_name_jesus(), " returns"]) },
    { emoji: emoji_rainbow(), text: "God, thank You for joy that will never end" },
    { emoji: emoji_rainbow(), text: "God, thank You for Your promises kept into forever" },
    { emoji: emoji_home(), text: "God, thank You for a place to rest" },
    { emoji: emoji_home(), text: "God, thank You for a home to return to" },
    { emoji: emoji_home(), text: "God, thank You for a bed to sleep in" },
    { emoji: emoji_home(), text: "God, thank You for shelter from the storm" },
    { emoji: emoji_hourglass(), text: "God, thank You for Your patience with me" },
    { emoji: emoji_hourglass(), text: "God, thank You for time to grow" },
    { emoji: emoji_hourglass(), text: "God, thank You for Your perfect timing" },
    { emoji: emoji_pray(), text: "God, thank You for a new day I did nothing to earn" },
    { emoji: emoji_pray(), text: "God, thank You for rest at the end of the work" },
    { emoji: emoji_pray(), text: "God, thank You for laughter shared with others" },
    { emoji: emoji_pray(), text: "God, thank You for small joys along the way" },
    { emoji: emoji_pray(), text: "God, thank You for second chances" },
    { emoji: emoji_pray(), text: "God, thank You for quiet moments alone with You" },
    { emoji: emoji_pray(), text: "God, thank You for prayers You have answered" },
    { emoji: emoji_pray(), text: "God, thank You for Your patience when I forget to thank You" },
    { emoji: emoji_pray(), text: "God, thank You that I can simply speak to You" },
  ];
  return thanks;
}
