import { text_regex_first_groups } from "./text_regex_first_groups.mjs";
export function gloss_explain_roots_claimed(explain) {
  "Every root a gloss explanation names in so many words, in the order it names them.";
  "A claim is the word root followed by a quoted word, allowing for the two fillers the corpus actually uses between them - 'the root is', 'the root word is'. Both the straight quote and the curly pair appear in the corpus, so both are read. Punctuation ending the sentence is dropped when it sits inside the closing quote, which parts of the corpus do, because 'nati,' and 'nati' are the same claim and only one of them is the root. A space is required before the quote, because the corpus also writes the possessive - the apostrophe in \"the root's meaning\" is not a quote opening, and allowing no space read one sentence's worth of English as a root. An explanation that names its root some other way claims nothing here, and that is the honest answer rather than a guess: the caller is meant to fall back to a weaker test when this comes back empty.";
  "Measured on 2026-09-07 over the 258651 entries in the store, 409 explanations write the root before the words is the root rather than after them - ‘sulti’ is the root word meaning ‘to speak’ - and this reads 408 of those as claiming nothing at all. That is not a fault in itself, because the caller falls back to the weaker test on an empty answer and that test finds the root sitting in the text, so all 408 come out agreed. The fault is the other one: in three of the 409 a quoted English gloss follows the word root, as in ‘awit’ is the root ‘to sing’, and there this reads the gloss as the root and hands back a disagreement that is not there. Three sightings out of the 830 the claimed test reports, so the reversed phrasing is a blind spot worth naming and not a hole worth widening the pattern for - a pattern loose enough to read the root before the words would also read the possessive this deliberately refuses.";
  let pattern = /root(?: word)?(?: is)?\s+['‘"]([^'’"]+?)[,.;:!?]?['’"]/g;
  let claimed = text_regex_first_groups(explain, pattern);
  return claimed;
}
