import { fn_name } from "./fn_name.mjs";
export function gloss_back_reference_wordings() {
  "Whole explanations that are nothing but a pointing sentence - matched entire, never as a piece of a longer one.";
  ("This is the second half of the same question ‘$fn ",
    fn_name("gloss_back_reference_markers"),
    "’ answers, and it exists because that half could not be stretched to cover it. A marker is a phrase found inside a wording, and a phrase cannot say ‘and the sentence stops here’. The Urdu store needs exactly that: 1650 of its explanations say the word is the one that came above, and 676 of those go on to teach something after saying it. A phrase names all 1650; a whole wording names only the ones that stop.");
  ("The test each entry had to pass, and the one to apply before adding another: take the wording, strike out ‘the same’, ‘again’, ‘the nth time’ and ‘that came above’, and see whether what is left would let a reader tell this word from any other word of its kind. ‘The same preposition.’ leaves ‘preposition’, which every preposition answers to, so the reader is told nothing. ‘The same preposition, and here it tells place.’ leaves a fact about this occurrence and is a real explanation, so it is not here.");
  ("A proper name is the exception that had to be reasoned out rather than assumed. ‘The same person's name that came above.’ looks like the others and is not: for a name there is nothing further to say, the name is its own meaning, and the store's own full wording for a first occurrence adds only that it takes a capital letter. So the person, city and region name wordings are deliberately absent, and the plain noun one - where the meaning is exactly what has gone missing - is present.");
  ("These are seventy-three wordings out of the five thousand one hundred and thirty-nine the store spells, and they carry 2913 of its 110264 explanations. They were the ones repeated most often, which is the same as saying they are the templates the writing pass falls back on when it has nothing to say. The long tail underneath is nearly all singletons, and a wording used once is usually one that says something particular.");
  let wordings = [
    "وُہی نام کا لفظ ہے جو اُوپر آیا۔",
    "وہی لفظ دوبارہ۔",
    "وُہی فعل ہے جو اُوپر آیا۔",
    "وُہی حرفِ جار ہے۔",
    "وُہی لفظ ہے جو مِلکیّت بتاتا ہے۔",
    "وُہی حرفِ جار۔",
    "وُہی ضمیر۔",
    "وُہی حرفِ جار ہے جو اُوپر آیا۔",
    "وُہی چھوٹا لفظ ہے جو رشتہ بتاتا ہے۔",
    "وُہی نام کا لفظ ہے۔",
    "وہی لفظ چَوتھی بار۔",
    "وُہی قِسم کا حرفِ جار۔",
    "وہی لفظ۔",
    "وُہی ضمیر ہے۔",
    "وُہی معرفہ ہے۔",
    "وہی فعل دوبارہ۔",
    "وہی چھوٹا لفظ تیسری بار۔",
    "وُہی اِسم ہے۔",
    "وہی ضمیر۔",
    "وہی جوڑنے والا لفظ دوبارہ۔",
    "وُہی لفظ ہے جو اُوپر آیا۔",
    "وُہی ملکیت کا لفظ ہے۔",
    "وُہی لفظ ہے جو اگلی بات کو پہلی سے جوڑتا ہے۔",
    "وُہی فعل۔",
    "وُہی ضمیر ہے جو اُوپر آیا۔ پہلا حرف بڑا ہے کیونکہ یہاں سے نیا جُملہ شروع ہو رہا ہے۔",
    "وہی ماضی کا فعل۔",
    "وُہی ضمیر ہے جو اُوپر آیا۔ پہلا حرف بڑا ہے کیونکہ یہ خُداوؔند کی طرف اِشارہ کرتا ہے۔",
    "وُہی جوڑنے والا لفظ ہے۔",
    "وہی اِسم دوبارہ۔",
    "وہی لفظ تیسری بار۔",
    "وُہی حرفِ عطف ہے۔ پہلا حرف بڑا ہے کیونکہ یہاں سے نیا جُملہ شروع ہو رہا ہے۔",
    "وُہی جوڑنے والا لفظ۔",
    "وہی نام۔",
    "وُہی حرفِ جار رِشتے کے لیٔے۔",
    "وُہی مفعولی صُورت ہے۔",
    "وُہی لفظ ہے جو اِشارہ کرتا ہے۔",
    "وُہی ضمیر، دُوسری بار۔",
    "وُہی ضمیر مِلکیّت کے لیٔے۔",
    "وُہی نام ہے۔",
    "وُہی حرفِ تعریف ہے۔ پہلا حرف بڑا ہے کیونکہ یہاں سے نیا جُملہ شروع ہو رہا ہے۔",
    "وُہی فعل ہے جو گُزرے ہوئے زمانے کا ہے۔",
    "وُہی فعل ہے جو اِس وقت کے زمانے کا ہے۔",
    "وُہی بے قاعدہ فعل ہے۔",
    "وُہی مددگار فعل ہے۔",
    "وُہی لفظ دوبارہ۔",
    "وہی لفظ پانچویں بار۔",
    "وُہی قِسم کا ضمیر، اَور یہ مِلکیّت بتاتا ہے۔",
    "وُہی قِسم کا جوڑنے والا لفظ۔",
    "وُہی فعل ہے۔",
    "وہی لفظ دوبارہ، مگر یہاں چھوٹے حرف سے۔",
    "وُہی ضمیر ہے جو اُوپر آیا۔ اُردُو نے یہ لفظ الگ سے نہیں لِکھا۔",
    "وہی نام دوبارہ۔",
    "وُہی لفظ ہے جو مِقدار بتاتا ہے۔",
    "وُہی لفظ ہے جو گِنتی بتاتا ہے۔",
    "وہی لفظ دوبارہ، مگر یہاں پہلا حرف چھوٹا ہے کیونکہ یہ جُملہ کے بیچ میں ہے۔",
    "وُہی طرح کا چھوٹا لفظ ہے۔",
    "وہی چھوٹا لفظ چَوتھی بار۔",
    "وُہی گُذری ہویٔی صُورت ہے۔",
    "وُہی قِسم کا حرفِ جار رِشتے کے لیٔے۔",
    "وُہی صِفت ہے۔",
    "وُہی حرفِ عطف ہے۔ اُردُو نے یہ لفظ الگ سے نہیں لِکھا۔",
    "وہی اِسم۔",
    "وُہی لفظ۔",
    "وُہی فعل دوبارہ۔",
    "وُہی اِسم، دُوسری بار۔",
    "وُہی وقت بتانے والا لفظ ہے۔",
    "وُہی ضمیر، تیسری بار۔",
    "وُہی حرفِ تعریف ہے۔ پہلا حرف بڑا ہے کیونکہ یہاں سے کہی ہویٔی بات شروع ہو رہی ہے۔",
    "وُہی چھوٹا لفظ ہے جو اُوپر آیا۔",
    "وُہی وضاحت کھولنے والا لفظ ہے۔",
    "وُہی لفظ جو اگلے فعل کو جوڑتا ہے۔",
    "وُہی فعل، دُوسری بار۔",
    "وُہی ضمیر مِلکیّت والی صُورت میں۔",
  ];
  return wordings;
}
