import { arguments_assert } from "./arguments_assert.mjs";
export function gloss_explain_clause_claim_verbs_urdu() {
  "The verbs an Urdu word explanation uses to say that a word stood in the verse it has just named, rather than to say what happened in that verse.";
  "URDU'S LITTLE WORD FOR OF ALREADY TELLS AN OWNER FROM AN ADDRESS, AND THESE VERBS TELL THE TWO USES OF AN ADDRESS APART. The reading that finds the numbers cancels a number owning the next word - آیت ۲ کے 'This' says the word This stands in verse two and says nothing about the word being explained. What it leaves standing is the address shape, آیت ۷ میں, in verse seven; and that one shape carries both a claim that a word came there and a sentence about what happened there. The verb at the end of the thought is what separates them.";
  "★ MEASURED ON 2026-10-02 OVER THE FOUR HUNDRED AND FIFTY-NINE ROWS THE URDU STORE STILL STOOD ACCUSED OF: TWO HUNDRED AND THIRTY-NINE OF THE THOUGHTS NAMING THEIR VERSE ALSO SAID ONE OF THESE VERBS, AND TWO HUNDRED AND TWENTY SAID SOMETHING ELSE. Twelve of the something-else thoughts were read by hand and every one of them was a true sentence about the named verse - آیت ۷ میں فرشتوں کو ہَوا کہا گیا تھا، اَور, in verse seven the angels were called wind, and - caught only because the word being explained does not stand in verse seven. So roughly half of the longest queue left in this store was never a fault at all, and the sibling reading next door had already written down that this class exists and goes uncaught.";
  "★ ONLY THE URDU VERBS ARE LISTED, AND ENGLISH'S ARE OWED RATHER THAN FORGOTTEN, FOR THE SAME REASON THE WORD FOR HERE IS LISTED ALONE. An English explanation says came in verse fifteen, and the word came would belong on a list of its own; it is not written here because nothing has read the English stores for this shape yet, and a word belongs on one of these lists when a reading of a store shows one rather than before. What makes the omission safe is the polarity the caller is built with: an absent verb list cannot subtract anything, because a thought is only ever dropped where its verse was named in the language whose verbs are known.";
  "The spelling with the mark above, آیٔا, was looked for and never met in this store, so it is left out rather than carried as a shape nothing writes.";
  arguments_assert(arguments, 0);
  let r = ["آیا", "آئی", "آئے"];
  return r;
}
