import { arguments_assert } from "./arguments_assert.mjs";
export function gloss_explain_clause_here_words() {
  "The words a word explanation uses to turn away from a verse it has just named and back to the word standing in front of the reader.";
  "★ A WORD MEANING HERE ENDS A THOUGHT AS SURELY AS A FULL STOP DOES, BECAUSE IT IS THE SENTENCE SAYING IN SO MANY WORDS THAT IT HAS COME BACK FROM THE VERSE IT NAMED TO THE WORD IN FRONT OF THE READER. Everything after it is about this word in this verse, so anything quoted after it was never a pointer at the verse behind it. The marks beside these on the cutting list are typed; these are said. Nothing else about them differs, and a reading that cut only at what is typed cut in the wrong place every time a writer said it in words instead.";
  "Measured on 2026-09-28 in first Peter four, on the word have in verse five. It is the same verb that came in verse three, but here with 'to' quotes a word and names a verse, and the two have nothing to do with each other: the quote belongs to here, which is verse five. Read whole, verse three stood accused of not holding 'to', which is true and is not what the sentence said. Cut at the word for here, verse three is asked about the word being explained instead, holds it, and the accusation is gone.";
  "The reading turned down was to drop the whole claim wherever one of these words stands in the thought. It would have removed the same false accusation, and it would also have removed a true statement: the sentence really does say the verb of verse five stood in verse three, and it is right. Cutting keeps the half that was said and discards only the quote that was never the subject.";
  "The other reading turned down was to pair a quote with a number only when nothing stands between them. That is the distance rule the reading next door already turned down, for the reason it gives there - it is right about half the time and never says which half.";
  "★ ONLY THE URDU WORD IS LISTED, AND THE ENGLISH ONE IS OWED RATHER THAN FORGOTTEN. The cutting is done by splitting on plain text, which knows nothing of where a word begins, and the English word for here sits inside there and inside where - both of which the explanations use constantly. Listing it would cut the English store's prose in the middle of its commonest words. What makes that cheap to owe is that the English store hardly ever quotes at all: of the two hundred and twenty-nine rows Deuteronomy and Joshua added to it, two hundred and twenty-seven pinned no word, because English prose explaining Hebrew says the same root and quotes nothing. The fault this removes needs a quote to exist.";
  "Nothing on this list names anything that runs - they are words a person writes.";
  arguments_assert(arguments, 0);
  let r = ["یہاں"];
  return r;
}
