import { arguments_assert } from "./arguments_assert.mjs";
export function gloss_explain_clause_claim_verbs_urdu() {
  "The verbs an Urdu word explanation uses to say that a word stood in the verse it has just named, rather than to say what happened in that verse.";
  "URDU'S LITTLE WORD FOR OF ALREADY TELLS AN OWNER FROM AN ADDRESS, AND THESE VERBS TELL THE TWO USES OF AN ADDRESS APART. The reading that finds the numbers cancels a number owning the next word - آیت ۲ کے 'This' says the word This stands in verse two and says nothing about the word being explained. What it leaves standing is the address shape, آیت ۷ میں, in verse seven; and that one shape carries both a claim that a word came there and a sentence about what happened there. The verb at the end of the thought is what separates them.";
  "★ MEASURED ON 2026-10-02 OVER THE FOUR HUNDRED AND FIFTY-NINE ROWS THE URDU STORE STILL STOOD ACCUSED OF: TWO HUNDRED AND THIRTY-NINE OF THE THOUGHTS NAMING THEIR VERSE ALSO SAID ONE OF THESE VERBS, AND TWO HUNDRED AND TWENTY SAID SOMETHING ELSE. Twelve of the something-else thoughts were read by hand and every one of them was a true sentence about the named verse - آیت ۷ میں فرشتوں کو ہَوا کہا گیا تھا، اَور, in verse seven the angels were called wind, and - caught only because the word being explained does not stand in verse seven. So roughly half of the longest queue left in this store was never a fault at all, and the sibling reading next door had already written down that this class exists and goes uncaught.";
  "★ ONLY THE URDU VERBS ARE LISTED, AND ENGLISH'S ARE OWED RATHER THAN FORGOTTEN, FOR THE SAME REASON THE WORD FOR HERE IS LISTED ALONE. An English explanation says came in verse fifteen, and the word came would belong on a list of its own; it is not written here because nothing has read the English stores for this shape yet, and a word belongs on one of these lists when a reading of a store shows one rather than before. What makes the omission safe is the polarity the caller is built with: an absent verb list cannot subtract anything, because a thought is only ever dropped where its verse was named in the language whose verbs are known.";
  "★ THE ENGLISH LIST HAS NOW BEEN READ FOR AND IT IS REFUSED RATHER THAN STILL OWED, BECAUSE ENGLISH NARRATES WITH THE VERBS IT WOULD CLAIM WITH. The original-language store, read on 2026-10-02, writes Verse twenty said sela - the word sela stands in verse twenty - and Verse eleven said the messenger of the LORD, which is what that verse does and claims no word of the entry at all. The same verb on both sides is not a thin measurement that more reading would thicken; it is one word proving the question cannot be asked this way. The rest of that store's shapes say the same: came up against them, gave them into the hand of Midian, ended with, opens with. So a reader reaching this paragraph for the English half should stop here rather than build it.";
  "What marks an English claim instead is a romanized Hebrew word standing as the thought's subject - alah, akhal, esh, sela, yad, laqach - and that table is not in the store. The translit this store keeps is the inflected shape with its mid-dots and its macrons, ha-lak, wat-ta-al, while the prose names the dictionary form; of seven lemma spellings taken out of one chapter's prose, none appeared in any translit field of that chapter. The only table carrying a lemma romanization is a Strong's lexicon, so the English half of this reading waits on that rather than on a verb list.";
  "A third shape no word list reaches at all: the subject is named once and then carried across the cuts. The going-up word, alah, is the sixth outing of a verb this chapter has been handing back and forth - and then five thoughts in a row each name a verse and none of them says alah again. The cut that makes a quote belong to one number is the same cut that throws the subject away, so every one of those five is read as a claim about the word being explained.";
  "The spelling with the mark above, آیٔا, was looked for and never met in this store, so it is left out rather than carried as a shape nothing writes.";
  arguments_assert(arguments, 0);
  let r = ["آیا", "آئی", "آئے"];
  return r;
}
