import { path_join } from "./path_join.mjs";
import { folder_memory_backup } from "./folder_memory_backup.mjs";
import { json_to } from "./json_to.mjs";
import { fn_name } from "./fn_name.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
export function hook_memory_root_code() {
  "The text of the small file a hook reads the memory folder out of - a header saying where it came from and how to make it again, then the folder itself.";
  "The folder is asked of the function that names it and then written down as a plain word. A hook cannot ask, because the answer is outside the repo and so cannot be worked out from where the hook itself sits, and because asking would mean reading a file while the hook runs - and a read that can fail would fail on the side of allowing.";
  "The header is part of what the gate compares, so an edit by hand to either half shows up as drift rather than quietly becoming the new truth.";
  let folder = folder_memory_backup();
  let root = path_join([folder, "memory"]);
  let spelled = json_to(root);
  let f_name = fn_name("hook_memory_root_code");
  let f_name2 = fn_name("hook_memory_root_write");
  let f_name3 = fn_name("hook_memory_root_gate_run");
  let code = text_combine_multiple([
    "// GENERATED by ",
    f_name,
    " — do not edit by hand.\n",
    "// Source of truth: js/",
    folder_memory_backup.name,
    ".mjs. Regenerate with\n",
    "// `node scripts/ai.mjs ",
    f_name2,
    "`; drift fails `q`\n",
    "// via ",
    f_name3,
    ".\n",
    "export const memory_root = ",
    spelled,
    ";\n",
  ]);
  return code;
}
