import { app_shared_name_search_info } from "./app_shared_name_search_info.mjs";
import { property_get } from "./property_get.mjs";
import { app_shared_frozen_assert } from "./app_shared_frozen_assert.mjs";
import { folder_public_latest } from "./folder_public_latest.mjs";
import { repo_path_combine } from "./repo_path_combine.mjs";
import { folder_public } from "./folder_public.mjs";
import { folder_app_copy_all } from "./folder_app_copy_all.mjs";
import { folder_app_stale_delete } from "./folder_app_stale_delete.mjs";
import { firebase_public_app_expected_write } from "./firebase_public_app_expected_write.mjs";
export async function html_public_from_latest(search) {
  "$plain search";
  "Moves an app from the stage it was checked at into the one people see, every piece of it together, refusing on an app that is frozen, and writes down that these are the bytes that were approved.";
  "Which pieces those are is asked of the stage the app was checked at, rather than being the page and the script and nothing else. A build is free to cut part of an app out into a script of its own and have the page send for it once it is running, and it names such a script with a number of its own choosing - so no list written here could name them. Named here, the extra scripts stayed behind at the checked stage while the page went on ahead, and the page then sent for a script that was not there. That goes wrong nowhere but here, because at the checked stage the extra scripts are sitting right beside the page and everything works.";
  "Whatever the previous build left here and this one did not make is taken away afterwards, so what people are looking at is one build's work rather than two builds' leftovers piled together.";
  "Taking away comes after putting in place, so a run that fell over halfway has removed nothing it had not already replaced.";
  "The writing down happens here rather than in whoever asked, because this is the one place every way of putting an app in front of people goes through, and putting it there is the whole of approving it - the folder people see holds what is ready to be sent, and anything not ready belongs at the stage before it. Written in the caller instead it was written by one of the three ways and not by the other two, so an app shipped through the full pipeline landed in that folder with the note still describing the build before it. Measured 2026-08-27: twenty of thirty-four apps were named as unapproved by a sending that had nothing wrong with them, and the one thing that had actually happened was this line sitting one level up.";
  "It comes after the taking away, so what is written down is the folder as it will be walked rather than the folder with the last build's leftovers still in it.";
  let info = await app_shared_name_search_info(search);
  let a_name = property_get(info, "a_name");
  app_shared_frozen_assert(a_name);
  let repo_name = property_get(info, "repo_name");
  let latest_relative = folder_public_latest();
  let from_folder = repo_path_combine(repo_name, latest_relative);
  let public_relative = folder_public();
  let to_folder = repo_path_combine(repo_name, public_relative);
  let copied = await folder_app_copy_all(from_folder, to_folder, a_name);
  await folder_app_stale_delete(to_folder, a_name, copied);
  await firebase_public_app_expected_write(a_name);
  return copied;
}
