import { list_size_equal } from "./list_size_equal.mjs";
import { arguments_assert } from "./arguments_assert.mjs";
import { js_node_type_is } from "./js_node_type_is.mjs";
import { assert } from "./assert.mjs";
import { property_get } from "./property_get.mjs";
import { list_first } from "./list_first.mjs";
import { js_identifier_is_assert } from "./js_identifier_is_assert.mjs";
import { js_identifier_is } from "./js_identifier_is.mjs";
export function js_guard_statements_shape_assert(binding, guard) {
  "Stops unless the two lines built for a guard came out as exactly the two shapes a guard is made of - a name bound to a call on one name, and a test of that name returning one thing.";
  "THE WORDS HANDED IN ARE READ BACK OUT OF THE TREE RATHER THAN CHECKED AS TEXT. Each of the four is dropped into a line, the line is parsed, and the tree is asked whether it is still the shape it was meant to be. A word carrying anything besides a name - a second argument, a call of its own, a line ending and another statement behind it - shows up here as a different shape, and there is no spelling of it that both slips past this and stays the shape.";
  "IT IS ASKED BEFORE ANYTHING IS WRITTEN, so a refusal leaves the file exactly as it was.";
  arguments_assert(arguments, 2);
  let bound_is = js_node_type_is(binding, "VariableDeclaration");
  assert(bound_is);
  let declarations = property_get(binding, "declarations");
  let alone_is = list_size_equal(declarations, 1);
  assert(alone_is);
  let declarator = list_first(declarations);
  let id = property_get(declarator, "id");
  js_identifier_is_assert(id);
  let source = property_get(declarator, "init");
  let called_is = js_node_type_is(source, "CallExpression");
  assert(called_is);
  let callee = property_get(source, "callee");
  js_identifier_is_assert(callee);
  let args = property_get(source, "arguments");
  let single_is = list_size_equal(args, 1);
  assert(single_is);
  let argument = list_first(args);
  js_identifier_is_assert(argument);
  let tested_is = js_node_type_is(guard, "IfStatement");
  assert(tested_is);
  let test = property_get(guard, "test");
  js_identifier_is_assert(test);
  let block = property_get(guard, "consequent");
  let body = property_get(block, "body");
  let one_line_is = list_size_equal(body, 1);
  assert(one_line_is);
  let statement = list_first(body);
  let returning_is = js_node_type_is(statement, "ReturnStatement");
  assert(returning_is);
  ("What is handed back is a name or the word for nothing, and never a call. A call would let a whole line of somebody's code in through the one slot the checks above leave open, and a guard handing back the answer to a further question is a guard doing two things.");
  let handed = property_get(statement, "argument");
  let named_is = js_identifier_is(handed);
  let nothing_is = js_node_type_is(handed, "Literal");
  assert(named_is || nothing_is);
}
