export function lyric_video_picture_style() {
  "The look every picture standing behind the words of a lyric video is drawn in, said once here rather than in each picture's own wording, so that what is particular to a picture is only what it shows.";
  "★ IT FILLS THE FRAME AND IS DRAWN AT THE FRAME'S OWN SHAPE, WHICH IS THE WHOLE DIFFERENCE FROM THE PICTURES DRAWN FOR THE HYMN. Those are emblems on black, drawn square, and the renderer fits them inside the frame without cropping - which is right for a shape on black, because the margin fitting leaves is black against black and so is no margin at all. A ground is the opposite case: fitted, the same margin is two black bands across a photograph, and cropped to fill, the part thrown away is the part of the scene the words were standing on. Asking for the frame's own shape means fitting and filling are the same operation, so nothing had to be decided in the renderer and nothing already rendered can come back different.";
  "★ THE MIDDLE OF THE FRAME IS ASKED TO BE DARK AND QUIET, BECAUSE THAT IS WHERE THE WORDS ARE. A card is placed at the middle of the room above the passage line, in white lettering with a black rim, and a rim is what saves a word standing on something busy - not what makes it comfortable to read. A bright horizon, a sunlit cloud or a field of small detail exactly there costs the reader the psalm even with every rim drawn. So the picture is asked to carry its light at the edges and its detail low, and to leave the middle deep. This is the one clause that is about the video rather than about the scene, and it is the one worth defending first when a picture comes back unreadable.";
  "★ NOTHING STANDS FOR GOD, AND THAT HALF IS NOT NEGOTIABLE. Some of those who will watch these hold that the LORD should not be drawn, and a psalm is addressed to Him throughout. A ground that puts no figure in the place the psalm is speaking to asks nobody to set that conviction aside, and there is no picture worth having that is bought by asking them to.";
  "★ ORDINARY PEOPLE ARE ALLOWED, WHICH IS A CHANGE MADE ON 2026-09-08 AND WORTH SAYING WHY. The clause used to refuse every figure, on the reasoning that any figure at all is a figure somebody has to decide about. That reasoning overreached. What the conviction actually forbids is the depiction of God; nobody's conscience forbids a shepherd on a hillside or harvesters in a field. Refusing those bought no protection and cost the psalms that name people outright - kings, princes, young men and maidens - which were being drawn as the place people stand in and the things they lay down. So people may be shown and God may not, which is the line the objection was always drawn along.";
  "★ THE FIGURE MUST NEVER BE THE ONE THE PSALM IS SPEAKING TO, AND THAT GUARD IS THE SCENE AUTHOR'S AND NOT THE MODEL'S. A drawer knows nothing of the psalm; it is handed one sentence about paint. So the clause below asks only for what a painter can act on - far off, small, low, at the edges - and the judgment that a lone shepherd in Psalm 23 or a lone king in Psalm 2 would be read as the LORD is made when the scene is written, by whoever is reading the line. Where a line would make a single figure stand for Him, draw the flock, the fold, the road, the crown laid down.";
  "★ FAR OFF AND SMALL IS ALSO WHAT KEEPS A FIGURE OUT OF THE LETTERING. The middle third belongs to the words. A person is the one subject a reader's eye goes to first, so a figure standing in the middle of the frame competes with the psalm on the psalm's own ground. Low down and out at the edges is the same instruction the light already has, said again for the one thing that would break it hardest.";
  "NO LETTERING OF ANY KIND. Every word on the screen is set by the video out of a translation somebody chose, and a word drawn inside the picture is a second voice saying something nobody chose - in a language and a spelling nobody checked.";
  "★ WHETHER THAT CLAUSE IS OBEYED IS A PROPERTY OF THE MODEL AND NOT OF THE WORDING, WHICH WAS MEASURED RATHER THAN ASSUMED. The clause spells the forbidden thing five times over, so the obvious suspicion was that naming it summons it. Psalm 148's thirteen scenes were drawn four times over on 2026-09-05 to check: the Black Forest Labs pro model obeys it and carries no lettering anywhere, while flux-2 dev, Qwen-Image and Z-Image Turbo all paint gibberish captions across the middle of nearly every frame. The clause was then rewritten to describe bare paint instead of refusing lettering, and dev was drawn again - it captioned all thirteen still, and painted words lifted out of the new clause itself. So the five namings are not the cause, the rewrite bought nothing, and the original wording is what stands. What the finding actually decides is the model: a house that captions a frame cannot draw these grounds at any price, however well it paints.";
  "IT IS ONE STILL SCENE AND NOT A COMPOSITION OF SEVERAL. A psalm line names four things in a breath - lightning and hail, snow and clouds - and a picture that dutifully shows all four is four small pictures in one frame, none of them readable behind lettering. One of them, large, is the whole of what a ground has room to be.";
  let style = [
    "filling the whole tall frame right out to all four edges, a single wide still scene with nothing cropped away at its centre",
    "the middle third of the frame deep and dark and almost without detail, the light and the detail of the scene kept low down and out at the edges, so that white lettering laid across the middle stands clear of everything behind it",
    "painted in the manner of a quiet oil landscape, deep and luminous, unhurried, reverent, with soft edges and no hard small detail anywhere",
    "nothing at all standing for God himself, no angels drawn as figures, and no faces",
    "people may be shown, but only far off and small, low down or out at the edges of the frame",
    "no text, no lettering, no letters, no numbers, no writing and no symbols of writing anywhere in the picture",
    "no modern things - no buildings of glass or steel, no roads, no wires, no machines, no vehicles, no aircraft",
    "one subject only, large and simple, and not several small things arranged together",
    "not a photograph, not a poster, not a modern digital illustration, and no border, frame or vignette drawn around the picture",
  ];
  return style;
}
