export function lyric_video_picture_style() {
  "The look every picture standing behind the words of a lyric video is drawn in, said once here rather than in each picture's own wording, so that what is particular to a picture is only what it shows.";
  "★ IT FILLS THE FRAME AND IS DRAWN AT THE FRAME'S OWN SHAPE, WHICH IS THE WHOLE DIFFERENCE FROM THE PICTURES DRAWN FOR THE HYMN. Those are emblems on black, drawn square, and the renderer fits them inside the frame without cropping - which is right for a shape on black, because the margin fitting leaves is black against black and so is no margin at all. A ground is the opposite case: fitted, the same margin is two black bands across a photograph, and cropped to fill, the part thrown away is the part of the scene the words were standing on. Asking for the frame's own shape means fitting and filling are the same operation, so nothing had to be decided in the renderer and nothing already rendered can come back different.";
  "★ THE MIDDLE OF THE FRAME IS ASKED TO BE DARK AND QUIET, BECAUSE THAT IS WHERE THE WORDS ARE. A card is placed at the middle of the room above the passage line, in white lettering with a black rim, and a rim is what saves a word standing on something busy - not what makes it comfortable to read. A bright horizon, a sunlit cloud or a field of small detail exactly there costs the reader the psalm even with every rim drawn. So the picture is asked to carry its light at the edges and its detail low, and to leave the middle deep. This is the one clause that is about the video rather than about the scene, and it is the one worth defending first when a picture comes back unreadable.";
  "★ NO PEOPLE AND NO FACES, WHICH IS INHERITED RATHER THAN DECIDED HERE. Some of those who will watch these hold that the LORD should not be drawn, and a psalm is addressed to Him throughout - so any figure at all in the frame is a figure somebody has to decide about. Drawing the created thing the psalm names instead asks nobody to set that conviction aside. Where a psalm names people outright - kings, princes, young men and maidens - what is drawn is the place they stand in and the things they lay down, which is the same care the hymn's symbols take and for the same reason.";
  "★ THE PICTURE MUST CARRY NO LETTERING, AND THE CLAUSE THAT ASKS FOR THAT IS WRITTEN AS A DESCRIPTION OF BARE PAINT RATHER THAN AS A REFUSAL. Every word on the screen is set by the video out of a translation somebody chose, and a word drawn inside the picture is a second voice saying something nobody chose - in a language and a spelling nobody checked. The clause used to spell the forbidden thing five times over - no text, no lettering, no letters, no numbers, no writing - and a model reading it draws what it has just been told about, which is the failure recorded in the memory note on negation. What replaced it says what the surface is instead of what must not be on it.";
  "IT IS ONE STILL SCENE AND NOT A COMPOSITION OF SEVERAL. A psalm line names four things in a breath - lightning and hail, snow and clouds - and a picture that dutifully shows all four is four small pictures in one frame, none of them readable behind lettering. One of them, large, is the whole of what a ground has room to be.";
  let style = [
    "filling the whole tall frame right out to all four edges, a single wide still scene with nothing cropped away at its centre",
    "the middle third of the frame deep and dark and almost without detail, the light and the detail of the scene kept low down and out at the edges, so that white lettering laid across the middle stands clear of everything behind it",
    "painted in the manner of a quiet oil landscape, deep and luminous, unhurried, reverent, with soft edges and no hard small detail anywhere",
    "no people, no faces, no figures, no hands, no angels drawn as figures, and nothing at all standing for God himself",
    "every surface in it bare paint, the sky open and empty, the whole scene silent and wordless",
    "no modern things - no buildings of glass or steel, no roads, no wires, no machines, no vehicles, no aircraft",
    "one subject only, large and simple, and not several small things arranged together",
    "not a photograph, not a poster, not a modern digital illustration, and no border, frame or vignette drawn around the picture",
  ];
  return style;
}
