import { arguments_assert } from "./arguments_assert.mjs";
export function lyric_video_screen_characters_max() {
  "How many letters of a passage will stand on one screen at the lettering size a lyric video uses.";
  "★ THE NUMBER WAS READ OFF RENDERED FRAMES RATHER THAN WORKED OUT FROM THE SIZES. Working it out instead would need the width of a letter in a particular typeface at a particular weight, which is the one thing a count of letters was chosen to avoid needing. The frame it was last read off is the genealogy at the end of the third of Luke - fifteen hundred and five letters, the longest card in the bible - which came out as twenty six lines filling a thousand and twenty of the frame's height, with the letters running about fifty eight to a line. Everything else follows from that one frame by proportion, because letters fit both across and down: at the full lettering size the same words would run about fifteen and a half to a line and about eleven lines would stand in the room there is.";
  "★ IT WENT UP BY HALF WHEN THE CARD WAS MOVED OFF THE MIDDLE OF THE FRAME, AND THAT IS THE WHOLE OF WHY IT CHANGED. It used to be a hundred and ten, read off two short psalm frames and left deliberately short of what those frames showed. Two things were wrong with it. The card sat at the middle of the frame while the passage and the translation held the foot, so it could only grow as far downwards as the passage line and had to leave the same room unused above - a third of the frame doing nothing. And the short reading was carried into the shrinking as well as into the threshold, so a long card was made smaller than it needed to be by the same margin, compounded: the genealogy came out at forty one where fifty was there for the taking.";
  "★ IT IS THE COUNT AT WHICH A CARD STILL STANDS WITHOUT BEING MADE SMALLER, AND ALSO THE COUNT THE SHRINKING SCALES AWAY FROM. Those are one number on purpose. Two numbers would let a card be judged to fit by one of them and sized by the other, and the seam between them would be invisible until a card landed in it.";
  "★ IT ASSUMES THE CARD IS CENTRED IN THE ROOM ABOVE THE PASSAGE LINE AND NOT IN THE FRAME. That is where the writer puts it, and it is worked out there from the sizes at the foot rather than stated, so this number and that placement have to move together. Read against a card centred in the frame it is too large by about a quarter, which is the ratio of the two rooms.";
  arguments_assert(arguments, 0);
  let characters_max = 165;
  return characters_max;
}
