import { arguments_assert } from "./arguments_assert.mjs";
export function lyric_video_letter_widths() {
  "How wide each letter is drawn in the typeface a lyric video uses, given as thousandths of the lettering size.";
  "★ THESE WERE MEASURED OFF RENDERED FRAMES, NOT TAKEN FROM THE FONT FILE. Each letter was drawn twice inside the same pair of bookend letters, once alone and once four times over, and the width of the drawn ink measured both times; the difference divided by three is the room one of that letter takes up, and the bookends and the black rim around every letter fall out of the subtraction because they are the same in both. So no font library is needed to read this, and nothing here has to agree with a table somebody else wrote.";
  "★ THEY ARE THOUSANDTHS OF THE LETTERING SIZE RATHER THAN PIXELS SO THAT ONE MEASUREMENT SERVES EVERY SIZE. Letters scale with the size they are set at, so a width in pixels would be a width for one video only, and the second video to choose a different size would be measured against the first one's frames without anything going wrong that anybody could see.";
  "★ A LETTER THAT WAS NEVER MEASURED IS COUNTED AS THE WIDEST ONE THERE IS RATHER THAN REFUSED. Bible text reaches beyond this set - a Hebrew letter in a gloss, a bracket nobody expected - and the only two answers to that are to stop, or to answer wide. Answering wide errs towards breaking a screen early, which costs a screen; answering narrow or stopping costs a card that runs off the frame, which is the fault this whole measurement exists to end.";
  "★ THE NUMBERS ARE FOR THE BOLD WEIGHT, BECAUSE THAT IS THE WEIGHT THE WORDS ARE SET IN. Read against the ordinary weight they are all a little too large, which again errs towards breaking early.";
  arguments_assert(arguments, 0);
  let widths = {
    0: 422,
    1: 422,
    2: 422,
    3: 422,
    4: 422,
    5: 422,
    6: 422,
    7: 422,
    8: 422,
    9: 422,
    A: 507,
    B: 493,
    C: 467,
    D: 547,
    E: 409,
    F: 404,
    G: 529,
    H: 560,
    I: 284,
    J: 244,
    K: 489,
    L: 413,
    M: 689,
    N: 600,
    O: 584,
    P: 462,
    Q: 584,
    R: 484,
    S: 404,
    T: 422,
    U: 556,
    V: 478,
    W: 711,
    X: 493,
    Y: 458,
    Z: 422,
    a: 444,
    b: 462,
    c: 378,
    d: 462,
    e: 436,
    f: 284,
    g: 462,
    h: 480,
    i: 224,
    j: 224,
    k: 453,
    l: 224,
    m: 720,
    n: 480,
    o: 453,
    p: 462,
    q: 462,
    r: 333,
    s: 364,
    t: 316,
    u: 480,
    v: 418,
    w: 627,
    x: 424,
    y: 418,
    z: 356,
    " ": 191,
    "!": 213,
    "(": 249,
    ")": 249,
    ",": 211,
    "-": 240,
    ".": 211,
    ":": 211,
    ";": 211,
    "?": 351,
    "'": 196,
    '"': 347,
    "‘": 158,
    "’": 158,
    "“": 329,
    "”": 329,
    "—": 733,
  };
  return widths;
}
