import { fn_name } from "./fn_name.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
export function permission_rules_other() {
  "the allow rules that grant something other than running a function on Claude's seam - kept as written, since nothing generates them";
  let combined = text_combine_multiple([
    "Bash(pkill -f ai.mjs ",
    fn_name("qa_gate_run"),
    ")",
  ]);
  let combined2 = text_combine_multiple([
    "Bash(pkill -f ai.mjs ",
    fn_name("examples_gate_run"),
    ")",
  ]);
  let texts = [
    "Bash(find:*)",
    "Bash(grep:*)",
    "Bash(cat:*)",
    "Bash(cp:*)",
    "Bash(cut:*)",
    "Bash(cd:*)",
    "Bash(date:*)",
    "Bash(diff:*)",
    "Bash(echo:*)",
    "Bash(printf:*)",
    "Bash(seq:*)",
    "Bash(head:*)",
    "Bash(tail:*)",
    "Bash(wc:*)",
    "Bash(which:*)",
    "Bash(readlink:*)",
    "Bash(realpath:*)",
    "Bash(pwd:*)",
    "Bash([:*)",
    "Bash(test:*)",
    "Bash(df:*)",
    "Bash(du:*)",
    "Bash(stat:*)",
    "Bash(strings:*)",
    "Bash(ps:*)",
    "Bash(pgrep:*)",
    "Bash(uptime:*)",
    "Bash(free:*)",
    "Bash(nproc:*)",
    "Bash(sleep:*)",
    "Bash(git cat-file:*)",
    "Bash(git check-ignore:*)",
    "Bash(git diff:*)",
    "Bash(git log:*)",
    "Bash(git ls-files:*)",
    "Bash(git ls-remote:*)",
    "Bash(git merge-base:*)",
    "Bash(git mv:*)",
    "Bash(git rev-parse:*)",
    "Bash(git show:*)",
    "Bash(git status:*)",
    "Bash(git stash list)",
    "Bash(git branch -a)",
    "Bash(git reflog)",
    "Bash(ls:*)",
    "Bash(sort:*)",
    "Bash(uniq:*)",
    "Bash(tr:*)",
    "Bash(paste:*)",
    "Bash(md5sum:*)",
    "Bash(ffprobe:*)",
    "Bash(node --check:*)",
    "Bash(pkill -f vite --config scripts/vite.config.mjs)",
    combined,
    combined2,
    "mcp__claude-in-chrome__list_connected_browsers",
    "mcp__claude-in-chrome__tabs_context_mcp",
    "mcp__claude-in-chrome__read_page",
    "mcp__claude-in-chrome__get_page_text",
    "mcp__claude-in-chrome__find",
    "mcp__claude-in-chrome__read_console_messages",
    "mcp__claude-in-chrome__read_network_requests",
    "Edit(/tmp/claude-1000/-home-j-repos-love/**)",
    "Read(/tmp/claude-1000/-home-j-repos-love/**)",
    "Write(/tmp/claude-1000/-home-j-repos-love/**)",
    "Write(/home/j/repos/love/scripts/temp/**)",
    "Edit(/home/j/repos/love/scripts/temp/**)",
    "Bash(mkdir /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(mkdir -p /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(rm /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(mv /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(rm -f public/dev/sandbox.js public/dev/calendar.js)",
    "Bash(rm -f public/dev/sandbox.js)",
    "Bash(rm -f public/dev/calendar.js)",
    "Edit(.claude/hooks/**)",
    "Edit(.claude/hooks/bash-command-guard.py)",
    "Edit(.claude/hooks/claude_edit_claim.mjs)",
    "Edit(.claude/hooks/memory_write_allow.mjs)",
    "Edit(.claude/settings.json)",
    "Edit(.claude/settings.local.json)",
  ];
  return texts;
}
