import { fn_name } from "./fn_name.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
export function permission_rules_other() {
  "the allow rules that grant something other than running a function on Claude's seam - kept as written, since nothing generates them";
  "no rule here may edit a hook file either, and that was the wider hole of the two. A hook runs before the permission engine, and its allow skips the engine rather than adding to it, so a standing approval to edit the hook covering the write tools reaches the rules file as well - and that hook abstains everywhere outside the memory folder and does not guard itself. Two such rules stood here; one named a file nothing currently runs, which is a smaller thing only for as long as nobody registers it.";
  "no rule here may edit a settings file. Two once did, and a standing approval to edit the file that decides what is approved without asking is the one grant that can widen itself: any rule at all can be added to it, and a rule granting a shell outright answers to nothing on the deny floor, which names particular commands rather than shapes. Two gates would have caught it afterwards - the shared file must match what this generates, and the local one is watched against a record - but both are a reading taken later, and nothing at all stood in the way at the moment of the edit. The list is generated on purpose so that a new approval is a named function a human says yes to; a rule that can rewrite the list goes around that, so the way to change what is approved is to change this source and regenerate, which is a visible edit that a standing approval never buys.";
  "no rule here may name the Write tool. the engine matches a file tool against Edit rules alone, and an Edit rule covers every file-editing tool including Write, so a Write rule grants nothing its Edit twin does not already grant and nothing at all without one. Two stood here beside their twins, and the only thing they bought was a warning on every session for every Claude, which reads as a missing permission and is not one - the loudest possible way to say nothing. the reachability audit fails the build on a new one.";
  let f_name = fn_name("qa_gate_run");
  let combined = text_combine_multiple(["Bash(pkill -f ai.mjs ", f_name, ")"]);
  let f_name2 = fn_name("examples_gate_run");
  let combined2 = text_combine_multiple([
    "Bash(pkill -f ai.mjs ",
    f_name2,
    ")",
  ]);
  let texts = [
    "Bash(find:*)",
    "Bash(grep:*)",
    "Bash(cat:*)",
    "Bash(cut:*)",
    "Bash(cd:*)",
    "Bash(date:*)",
    "Bash(diff:*)",
    "Bash(comm:*)",
    "Bash(join:*)",
    "Bash(echo:*)",
    "Bash(printf:*)",
    "Bash(seq:*)",
    "Bash(head:*)",
    "Bash(tail:*)",
    "Bash(wc:*)",
    "Bash(which:*)",
    "Bash(readlink:*)",
    "Bash(realpath:*)",
    "Bash(pwd:*)",
    "Bash([:*)",
    "Bash(test:*)",
    "Bash(df:*)",
    "Bash(du:*)",
    "Bash(stat:*)",
    "Bash(strings:*)",
    "Bash(ps:*)",
    "Bash(pgrep:*)",
    "Bash(uptime:*)",
    "Bash(free:*)",
    "Bash(nproc:*)",
    "Bash(sleep:*)",
    "Bash(git cat-file:*)",
    "Bash(git check-ignore:*)",
    "Bash(git diff:*)",
    "Bash(git grep:*)",
    "Bash(git log:*)",
    "Bash(git rev-list:*)",
    "Bash(git ls-files:*)",
    "Bash(git ls-remote:*)",
    "Bash(git merge-base:*)",
    "Bash(git mv:*)",
    "Bash(git rev-parse:*)",
    "Bash(git show:*)",
    "Bash(git status:*)",
    "Bash(git stash list)",
    "Bash(git branch -a)",
    "Bash(git reflog)",
    "Bash(ls:*)",
    "Bash(sort:*)",
    "Bash(uniq:*)",
    "Bash(tr:*)",
    "Bash(paste:*)",
    "Bash(rev:*)",
    "Bash(md5sum:*)",
    "Bash(sha256sum:*)",
    "Bash(ffprobe:*)",
    "Bash(node --check:*)",
    "Bash(pkill -f vite --config scripts/vite.config.mjs)",
    combined,
    combined2,
    "mcp__claude-in-chrome__list_connected_browsers",
    "mcp__claude-in-chrome__tabs_context_mcp",
    "mcp__claude-in-chrome__read_page",
    "mcp__claude-in-chrome__get_page_text",
    "mcp__claude-in-chrome__find",
    "mcp__claude-in-chrome__read_console_messages",
    "mcp__claude-in-chrome__read_network_requests",
    "Edit(/tmp/claude-1000/-home-j-repos-love/**)",
    "Read(/tmp/claude-1000/-home-j-repos-love/**)",
    "Edit(/home/j/repos/love/scripts/temp/**)",
    "Bash(mkdir /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(mkdir -p /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(rm /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(mv /tmp/claude-1000/-home-j-repos-love/:*)",
    "Bash(rm -f public/dev/sandbox.js public/dev/calendar.js)",
    "Bash(rm -f public/dev/sandbox.js)",
    "Bash(rm -f public/dev/calendar.js)",
  ];
  return texts;
}
