export function python_code_dispatcher_commands() {
  "the python source of the generated mirror of the fn-named dispatcher command list — a plain literal, so the hook needs no file read at all";
  ("a runtime read would fail OPEN: the fold keyed on this set would silently stop taking a fourth word, and every rule naming one function would quietly grant the command for all of them");
  let quoted = list_map(dispatcher_commands_fn_named(), json_to);
  let joined = list_join(quoted, ", ");
  let code = text_combine_multiple([
    "# GENERATED by python_code_dispatcher_commands — do not edit by hand.\n",
    "# Source of truth: js/dispatcher_commands_fn_named.mjs. Regenerate with\n",
    "# `node scripts/r.mjs dispatcher_commands_python_write`; drift fails `q`\n",
    "# via dispatcher_commands_python_assert.\n",
    "DISPATCHER_COMMANDS_FN_NAMED = {",
    joined,
    "}\n",
  ]);
  return code;
}
