export function python_code_mirror(mirror) {
  arguments_assert(arguments, 1);
  ("The python text for one mirrored list — a header saying where it came from and");
  ("how to make it again, then the set itself. The header is part of what the gate");
  ("compares, so an edit by hand to either half shows up as drift.");
  let constant = property_get(mirror, "constant");
  let source = property_get(mirror, "source");
  let names = source();
  let quoted = list_map(names, json_to);
  let joined = list_join(quoted, ", ");
  let writer = fn_name("python_mirrors_write");
  let checker = fn_name("python_mirrors_assert");
  let code = text_combine_multiple([
    "# GENERATED by ",
    python_code_mirror.name,
    " — do not edit by hand.\n",
    "# Source of truth: js/",
    source.name,
    ".mjs. Regenerate with\n",
    "# `node scripts/r.mjs ",
    writer,
    "`; drift fails `q`\n",
    "# via ",
    checker,
    ".\n",
    constant,
    " = {",
    joined,
    "}\n",
  ]);
  return code;
}
