import { dispatcher_scripts } from "./dispatcher_scripts.mjs";
import { json_to } from "./json_to.mjs";
import { list_map } from "./list_map.mjs";
import { list_join } from "./list_join.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
export function python_code_dispatcher_scripts() {
  "the python source of the generated mirror of dispatcher_scripts — a plain literal, so the hook needs no file read at all";
  ("a runtime read would fail OPEN: the deny floor keyed on this set would silently stop denying if the file were missing");
  let quoted = list_map(dispatcher_scripts(), json_to);
  let joined = list_join(quoted, ", ");
  let code = text_combine_multiple([
    "# GENERATED by python_code_dispatcher_scripts — do not edit by hand.\n",
    "# Source of truth: js/dispatcher_scripts.mjs. Regenerate with\n",
    "# `node scripts/r.mjs dispatcher_scripts_python_write`; drift fails `q`\n",
    "# via dispatcher_scripts_python_assert.\n",
    "NODE_DISPATCHER_SCRIPTS = {",
    joined,
    "}\n",
  ]);
  return code;
}
