import { dispatcher_commands_python_write } from "./dispatcher_commands_python_write.mjs";
import { dispatcher_commands_python_assert } from "./dispatcher_commands_python_assert.mjs";
import { dispatcher_commands_fn_named } from "./dispatcher_commands_fn_named.mjs";
import { list_map } from "./list_map.mjs";
import { json_to } from "./json_to.mjs";
import { list_join } from "./list_join.mjs";
import { text_combine_multiple } from "./text_combine_multiple.mjs";
export function python_code_dispatcher_commands() {
  "the python source of the generated mirror of the fn-named dispatcher command list — a plain literal, so the hook needs no file read at all";
  "a runtime read would fail OPEN: the fold keyed on this set would silently stop taking a fourth word, and every rule naming one function would quietly grant the command for all of them";
  let list = dispatcher_commands_fn_named();
  let quoted = list_map(list, json_to);
  let joined = list_join(quoted, ", ");
  let code = text_combine_multiple([
    text_combine_multiple([
      "# GENERATED by ",
      python_code_dispatcher_commands.name,
      " — do not edit by hand.\n",
    ]),
    text_combine_multiple([
      "# Source of truth: js/",
      dispatcher_commands_fn_named.name,
      ".mjs. Regenerate with\n",
    ]),
    text_combine_multiple([
      "# `node scripts/r.mjs ",
      dispatcher_commands_python_write.name,
      "`; drift fails `q`\n",
    ]),
    text_combine_multiple([
      "# via ",
      dispatcher_commands_python_assert.name,
      ".\n",
    ]),
    "DISPATCHER_COMMANDS_FN_NAMED = {",
    joined,
    "}\n",
  ]);
  return code;
}
