import { qa_gate_run_start_wanted_generic } from "./qa_gate_run_start_wanted_generic.mjs";
export function qa_gate_run_start_wanted_stale_generic(flight, stale) {
  "Whether a whole-repo judging is worth starting, given what is already going, how full the machine is, and how long it has been since anything at all was judged.";
  "Its neighbour answers the first two and is left exactly as it was, because what it says is right for the asker it was written for: a gate run is slower for every other gate run beside it, and slowest of all on a full machine. This adds the only thing that neighbour could not see, which is TIME. Both of its reasons to refuse are true most of the time on a machine ten of us share, and a rule that is right every minute can still be wrong across an afternoon - measured 2026-08-11, the record held thirty-nine commits judged in its whole life while sixty-three sat unjudged from a single day, and the daemon meant to be judging them had written started: false on every line of its journal.";
  "That is starvation rather than caution. Waiting costs nothing only if the waiting ends, and here it did not: the conditions that close the door are caused by the same ten of us whose work the record exists to serve, so the busier the repo gets the less it is ever judged - which is exactly backwards.";
  "So once the record has gone stale, nothing about how busy the machine is counts as a reason any more. A judging that crawls still finishes, and a judging that never starts never does.";
  "This was first written keeping one refusal absolute - another JUDGING already going - on the reasoning that a second one makes the record no fresher. That reasoning was sound and the signal it was hung on was wrong, which is worth writing down because it looked exactly like caution. A judging never appears in the count it was being read off. It runs in the process that asked for it and spreads its work over shares, and the shares are spawned under the name of the share - so the whole word the counting looks for is borne by one thing only, which is somebody running the gates by hand. Measured while this was being corrected: four of them at once, and not one of them a judging.";
  "So the refusal was keyed to a signal that cannot mean what it was read as meaning, and it was the one refusal that could starve the daemon for ever, since somebody running the gates by hand is the single most ordinary state this repo is ever in. A rule cannot be more careful than its evidence.";
  "What is left is that a stale record wants judging whatever else is happening. The daemon cannot race itself - its loop waits for its own step to end - so the only doubling left is a judging asked for by hand at the same moment, which costs a quarter of an hour of one machine and no correctness at all: the record is read again immediately before it is written, so the later writer adds to the earlier one rather than replacing it.";
  let wanted = qa_gate_run_start_wanted_generic(flight);
  if (wanted) {
    return true;
  }
  return stale;
}
