import { arguments_assert } from "./arguments_assert.mjs";
import { qa_gate_said_plain_leaked } from "./qa_gate_said_plain_leaked.mjs";
import { list_empty_not_is } from "./list_empty_not_is.mjs";
export async function qa_gate_said_plain_is(f_name) {
  arguments_assert(arguments, 1);
  ("Whether one gate, when it fails, spells a function's name somewhere a reader scraping the failure will take as an accusation of something not at fault. Read-only.");
  ("Two things have to be true together. The gate has to do its own throwing - one that hands the whole complaint to a shared runner cannot leak, because whatever it passes along is the runner's to place, and the runner places it under a hint. And it has to spell a name that reaches neither a hint nor the thrown list of offenders.");
  ("The spelling is looked for as a call to the one function that exists to turn a name into a word, because that call is how a gate names something it does not otherwise touch: usually the command that repairs the fault, sometimes the very thing it is checking.");
  ("A name reaching a hint is fine and is the whole point of a hint - the reader drops it before it looks. A name reaching the thrown list of offenders is fine for the opposite reason: that list is the accusation, so a name in it is being accused on purpose.");
  ("IT READ THE HINT SLOT ONLY, AND THAT WAS ENOUGH FOR EVERY GATE THAT SPELLED A NAME WHEN IT WAS WRITTEN. Each of them spelled one to say which command repairs the fault, and a repair command is never at fault. Then a gate arrived that spells the names it is checking - the four doors a translation's text leaves by - and throws the ones that stopped reaching the commercial check as its offenders. Holding back an app that ships a door which no longer asks that question is exactly what the reader should do with those names, so the gate was calling correct behaviour a leak. The words this gate fails with had said so all along: throw the offenders, put the advice and any bystanders under the hint. Only one of those two slots was being read.");
  ("A function's own paragraphs are held alongside the hints and count the same way, because neither is ever said out loud. Prose is not printed and not thrown, so a name spelled in it reaches nobody - and a gate that explains itself by naming what it checks was being called a leak for explaining itself.");
  ("Two ways of reaching a slot both count. The spelling can sit inside one, and it can be kept in a local that a slot is later filled out of - the second is the commoner of the two, because a canonicalized file lifts almost everything into a local first.");
  ("★ THE WHOLE OF THE WALK IS NEXT DOOR AND NOTHING OF IT IS HERE. This one and the one that lists what leaked had the same twenty lines written out twice, and the difference was only whether a leak was answered with true or added to a list. Two copies of a judgment do not break, they drift: the reading was widened once already, from the hint slot alone to the hint slot and the thrown offenders, and had that widening reached only one of the two, the yes and the list of reasons for it would have disagreed with nobody the wiser.");
  ("Nothing found means nothing leaked, so the answer is whether the list next door came back with anything in it. It walks every spelling rather than stopping at the first, which is the price of asking one question in one place, and a gate's body is not long enough for that to be worth a second copy.");
  ("Necessary rather than sufficient, and said plainly here so nobody reads a pass as a promise. A name held in a variable rather than spelled - the function whose body was copied, say - is a leak this cannot see, and one path throwing a record does not stop another path throwing a sentence. A name put in the thrown list that does not belong there is a wrong accusation rather than a leak, and is not this one's question either. It catches the shape that stopped three deployments in a day; it does not catch every shape.");
  let leaked = await qa_gate_said_plain_leaked(f_name);
  let some = list_empty_not_is(leaked);
  return some;
}
