import { fn_name } from "./fn_name.mjs";
export function qa_snapshot_uncommitted_names() {
  "The things a frozen copy still needs that the repo deliberately never commits";
  "The installed packages are far larger than the repo and identical for every commit, so they are shared rather than duplicated";
  "The settings meant for this machine only are absent from any commit by design, and a gate that reads them finds nothing where it expects a file";
  ("The development build very nearly joined this list on the fifteenth of August and did not, and the reason is worth keeping. It is made out of the code beside it and writes a fresh copy of itself into every commit any of us make, so it is the obvious next thing to stop committing - and the moment it stopped being committed, every large file in it became a large file the history carries and the present does not, which is what ",
    fn_name("git_history_heavy_absent_gate_run"),
    " refuses. That gate names paths and not functions, and a red gate naming no function is counted against every app, so the whole of it stopped deploying. It goes back to being committed until the history can be rewritten in the same change");
  ("BOTH HALVES WERE DONE ON THE THIRD OF SEPTEMBER, in one sitting with a force-push allowed on both remotes, and the build has not been committed since. The paragraph above is the record of why it waited, not a description of where things stand.");
  ("So the build joins this list now, which is what the paragraph below always said it would need. It was not added at the time, and the gap is measurable rather than theoretical: from that day on, four gates that read the built files - the two on how big each page may get, the one on chunks left behind, and the one asking whether every served address can still be built - died on a missing folder inside every frozen copy. A gate that dies names no function, a red gate naming no function is counted against every app, and so every app stopped deploying, for exactly the reason the drop was carried out to stop happening.");
  ("What linking it costs, said plainly rather than left to be discovered. The other two names here are surroundings: the same whatever commit is being asked about, and no question in here is about them. This one is not. It is made out of the code under question, so a copy standing on one commit is handed a build made from whatever the working folder happened to hold. A verdict on how big a page is, is then about that build and not about that commit, and it is filed under the commit all the same. That is a real hole. It is also the smaller of the two on offer: a size that is a few minutes out of date beats no answer at all and every app held out of a deploy. Building inside the copy is what would close it properly, and the price of that is a build for every commit judged.");
  ("The built folder is named rather than the folder above it. The one above is committed - the pictures and the served pages are in it - so linking at that level would hide code the gates are here to ask about.");
  let names = ["node_modules", ".claude/settings.local.json", "web/dev"];
  return names;
}
