import { text_frozen } from "./text_frozen.mjs";
import { file_name_json_folder_gitignore } from "./file_name_json_folder_gitignore.mjs";
export function qa_shares_taken_log_path() {
  "Where this machine's own history of what a run of the gates cost is kept - one row per run, local to here and never committed.";
  "★ IT IS DELIBERATELY NOT IN THE SHARED RECORD, AND THAT IS A DECISION ALREADY MADE RATHER THAN A PREFERENCE OF THIS ONE. The function that measures the shares says of its own numbers that they go into what was said and never into what was found, because an answer kept in the record has to be about the code, and how busy this machine was on one afternoon is about neither the code nor anybody who reads the record later. A history of costs is not a verdict about any commit, so putting it beside the verdicts would make the record answer a question it is not about. Kept here it breaks none of that: nothing reads it to decide whether anything may ship, and it does not travel.";
  "★ SO WHAT WAS ADDED IS THE REMEMBERING AND NOT THE MEASURING, WHICH ALREADY EXISTED. Every number in a row was already being worked out and already being printed once, at the end of the run, and then let go. One run's numbers answer nothing on their own, because what a run cost means depends entirely on how busy the machine was while it ran - so a reading with nothing to compare it against is the one shape of this measurement that cannot be interpreted.";
  "★ MEASURED THE DAY THIS WAS WRITTEN, BY GETTING IT WRONG. Two runs were timed at about fifty two minutes each and read as proof that the quarter of an hour this repo says everywhere was simply false. It was not false. Sixteen minutes alone, about two and a half split across a free machine, and fifty three when three runs contend, were all already measured and written down - so the fifty two was the contended case agreeing with the record, and the disagreement was manufactured by comparing two different machines. A wrong note was written into memory on the strength of it. That is what a cost with no history costs.";
  "It is gitignored rather than committed because the reason above cuts both ways. A row is a fact about one machine on one afternoon, so it is worth nothing to anybody standing anywhere else, and committing it would put ten agents' machine weather into a repo that is public.";
  "The name on disk goes through the freezing word on purpose. A bare word here that matches a function name is rewritten by the canonicalizing pass into a reference to that function, and the path would then follow every later rename of it while the file already written stays where it is - so the whole history would be silently left behind and read back as empty. Its neighbour holding the judged verdicts carries the same warning, having been bitten.";
  let name = text_frozen("gate_shares_cost");
  let f_path = file_name_json_folder_gitignore(name);
  return f_path;
}
