import { qa_tree_pointers_assert } from "./qa_tree_pointers_assert.mjs";
import { qa_snapshot_siblings_freeze } from "./qa_snapshot_siblings_freeze.mjs";
import { qa_tree_folder_freeze } from "./qa_tree_folder_freeze.mjs";
import { qa_trees_reap } from "./qa_trees_reap.mjs";
import { qa_tree_repos_folder } from "./qa_tree_repos_folder.mjs";
import { folder_exists_ensure } from "./folder_exists_ensure.mjs";
import { folder_current_absolute } from "./folder_current_absolute.mjs";
import { qa_tree_folder } from "./qa_tree_folder.mjs";
import { qa_tree_names_skipped } from "./qa_tree_names_skipped.mjs";
import { path_join } from "./path_join.mjs";
import { qa_snapshot_link } from "./qa_snapshot_link.mjs";
export async function qa_tree_ensure() {
  "Freezes the working folder exactly as it stands, in memory, and answers where the frozen copy is";
  "Work nobody has committed is included, because that is what the gate is asked about before committing - which is the one thing a copy taken from a commit cannot show";
  "Being frozen is the whole point. Several of us edit this one folder, so questions put to the living folder are put to a folder that changes while they are being answered: a complaint may be nothing but somebody saving a file, and a clean answer may be about a file that was broken a moment after it was read. Neither belongs to any one state of the code, so neither can be checked by asking again";
  "The copying is not itself instant, so a file saved while it was being read could land in pieces - and a file in pieces does not parse, which is a complaint about nobody's work that looks exactly like a complaint about somebody's. That is closed here rather than left to the reader: the moment before the copy starts is noted, and afterwards every file written since is taken across again on its own";
  "Doing the whole folder again instead would never settle, because several of us write here without stopping and a folder held to the standard of one instant never reaches it. One file is a standard that is reached at once, and it is the standard that was actually wanted - not that the copy is a single moment, but that no file in it is half of two";
  "Asking a second time is what makes it a repair rather than a hope. Whatever is still moving after the files were taken across is named out loud, because a copy that could not be settled is worth knowing about and a silent one reads exactly like a clean one";
  "The neighbouring repos are frozen the same way and for the same reason. Asking after every function does not stop at this repo, so a sweep run in here was reading the neighbours as they stood at that instant - and a red that goes quiet the moment it is asked again is the pair of answers this whole arrangement exists to make impossible";
  "Whether the copy actually reaches nothing living is looked at before it is handed over, rather than reasoned about here in words. The neighbours were pointed at for as long as this existed, under a written claim that nothing here asked about them, and the claim being written down is precisely what stopped anybody checking it";
  let repos = qa_tree_repos_folder();
  let report = await qa_trees_reap();
  await folder_exists_ensure(repos);
  await qa_snapshot_siblings_freeze(repos);
  let here = folder_current_absolute();
  let folder = qa_tree_folder();
  let skipped = qa_tree_names_skipped();
  await qa_tree_folder_freeze(here, folder, skipped);
  let live = path_join([here, "node_modules"]);
  let link = path_join([folder, "node_modules"]);
  await qa_snapshot_link(live, link);
  await qa_tree_pointers_assert(repos);
  return folder;
}
