export function song_image_style() {
  "how every drawn picture for this hymn is to look, said once here so that changing the look of all thirty-two is one edit rather than thirty-two";
  "it asks for the church's own art rather than a modern drawing, and that settles the cartoon question by belonging somewhere instead of by taste. A church window is what the faith has actually looked like to most of the people who ever sat under it, and a picture in that manner is legible as sacred to somebody who has never been told what it is.";
  "it names one tradition and not several, which is the whole reason this was rewritten. It used to offer an icon, a mosaic and an illuminated letter together, meaning the thing all three have in common; what was read instead was a menu, and a different member was picked each time. Two pictures came back in two different languages - one fine illuminated line work, one flat silhouette - and both obeyed the sentence, because the sentence permitted both. A clause whose purpose is sameness may name one thing only.";
  "a window rather than a mosaic or an icon, and the reason is what each medium does with black. A mosaic's gold is the ground the figure stands on, so gold-figure-on-black asks it to work inside out. An icon is built around a face, and no faces may be drawn here, so what would be left is the tradition with its subject removed. A window is already what is wanted: black lead is the line, the glass is the shape, and it is made to be looked at lit from behind by somebody sitting in the dark - which is exactly a phone in a dark frame.";
  "it asks for an emblem rather than a photograph, and the reason is sameness again. A generator asked for a photograph answers with a different lens, a different light and a different room every time, so thirty-two of them cut together look like thirty-two different films; a flat symbol is nearly the same instruction twice and comes back nearly the same twice.";
  "no gold, and that is the one rule here that is about meaning rather than about looking. Gold in this film says this is the word of GOD, carried over from the game, which is why the Scripture in the interlude is set in it. A colour only says that while something on the screen goes without it; thirty-two gold emblems would not weaken the meaning slowly, they would spend it, and the interlude would lose the very thing that set it apart. An emblem is a gloss on the word and not the word - it carries a reference, not the text - so wearing the mark of the word would be claiming a standing it does not have.";
  "the glass is coloured because a window's glass is coloured, so the rule above costs nothing to keep. Cobalt, ruby, emerald and violet are what is actually in a church window, they are nowhere near the gold, and being nowhere near it is the point - a colour half a step off the gold would be the worst of the three possible answers, since a difference too small to be meant still reads as a mistake.";
  "no amber and no yellow either, for the same reason and by the same measure. They are the near misses of gold rather than alternatives to it, and a near miss is what the rule above exists to avoid.";
  "legibility no longer rides on the colour, which is what makes dropping the gold affordable. It rides on heavy leading, on a dozen large panes and on a shape that fills its square - all three now asked for above - so a deep blue emblem carries as far across a room as a pale gold one did.";
  "the detail inside the shape is asked for as heavy black leading rather than as fine drawing, and that is a decision about the far end rather than about taste. Fine line work is the first thing a small screen eats; leading is thick by its nature, so in this one medium the interior detail is the part that survives being shrunk instead of the part that disappears.";
  "how many panes there are is said as well as how thick the leading is, because asking only for thick leading does not get it. Three crosses and a lamb were drawn from the same sentence and came back with lead lines of completely different weights - the crosses heavy, the lamb hairline. The subject decided it: a fleece invites fifty small divisions and a cross invites a dozen large ones, and the leading then thins to fit however many were drawn. Thickness is what comes out of the pane count rather than something that can be asked for beside it, so the count is the thing to say.";
  "flat is said twice over, because a drawing came back with a gradient washed across it after being told not to shade, and another grew a pair of brown hooves after being told every pane was one colour. A refusal is obeyed unevenly from one drawing to the next, so the ones that have already been broken once are worth saying positively as well as negatively.";
  "colour is said to follow the thing rather than the pane, and that sentence is here because leaving it out produced the worst picture of the lot. Asking for a dozen panes each one flat colour reads as an instruction to vary the colour pane by pane. A subject that already has parts survives that by luck - three crosses on a hill have a sky, a slope and the crosses themselves, so the panes fall on boundaries that mean something. A lamb has no parts. Its panes are arbitrary cuts across one animal, and colouring each of them separately produced a harlequin: a magenta head, a blue shoulder, a red flank, a purple leg. In a real window the lamb is white glass and the sky behind it is blue, because colour belongs to the thing depicted and the leading is only where two things meet.";
  "the field is held to two plain areas, and the pane count is said to cover the field as well, because saying colour follows the thing did not fix the harlequin so much as move it. The lamb came back one green - the rule worked on the subject - and the sky behind it came back in eight colours at once, because the field was never named as a thing and so had no colour of its own to follow. A window has a restful field and one busy subject; both busy is a window nobody can read across a room.";
  "the field is said as a shape rather than as a number, and that is the general lesson here rather than a detail about fields. It was asked for as two or three broad areas twice, and twice came back as six or eight - a count is a soft thing to a generator, something to round up towards while still feeling obedient, and there is no moment while drawing at which a fourth colour is refused. One flat colour above, one below, one line across is not a count at all: it is a shape, and it is either drawn or it is not. Say what to draw, not how many.";
  "not several shades of the same one is said because that is how the count was got round rather than broken. The field came back as reds - crimson, scarlet, maroon, rose - which is four colours to the eye and one colour to whoever drew it. A rule about how many colours there are needs saying in the reader's terms and not the drawer's.";
  "a thing keeps whatever colour it has in life, because the rule above says only that the symbol differs from the field and leaves what it is to chance. Asked that way it produced a green lamb - obedient and wrong. This is also how real glass works, which is the usual sign that the rule belongs here rather than being invented for the occasion.";
  "the materials are listed one by one rather than left to that rule, because a rule about what things are like in life is only ever obeyed for the things somebody thought to name. A lamb was named and came back white; wood was not, and three wooden crosses came back white too - not by disobedience but by default, white being where a drawing goes when no colour has been asked for. The symbols in this hymn are made of very few materials between them - wood, iron, stone, cloth, water, fire, blood - so naming all of them costs one clause and removes the default from every couplet at once.";
  "an arch and a field of glass behind the symbol, which reverses what this used to ask for. It used to forbid a background outright, and that was right while the picture was one shape floating on black. A window is not one shape floating on black - it is a subject set in a field, held in a frame - and the drawing that discovered this was the best of the set precisely because it broke the old rule and supplied all three unasked. The field is also what gives the symbol something to be a different colour from, so forbidding it and asking colour to follow the thing cannot both be had.";
  "the old way of drawing a thing is asked for wherever there is one, and that is about unity rather than about taste. These emblems are older than the divisions between the churches - a cross, a lamb, a crown, a cup, a trumpet, a burning bush are common property, and somebody who has only ever sat in one kind of building still reads all of them. An invented emblem belongs to whoever invented it, which here would be a machine; an inherited one is already everybody's. Inheriting is also simply better drawing, since a form that has been redrawn for centuries has had every unreadable version discarded already.";
  "one settled way is asked for and not several named ones, and that is the menu lesson again in a place it would be easy to forget it. Naming the Roman, the Eastern and the Reformed manner together to mean the thing all three share would be read as three options and picked from afresh each time, and thirty-two pictures would come back from three different centuries. Where a form really is common to all three, asking for the old one gets it without naming anybody.";
  "no faces is not the same rule as no people, though it has been treated as one. What some of those watching hold is that the LORD should not be drawn; that does not reach Abraham, who is not GOD. What keeps people out anyway is nearer to hand - a drawn face is the thing a generator is worst at and the thing a viewer forgives least, and a window with people in it is a scene rather than an emblem, which the pane count and the flat frontal rule are not built for.";
  "centred and large because the far end of this is a phone held at arm's length, sometimes behind a cracked protector, sometimes by eyes that no longer see small things. A shape that fills its square survives all three; a small shape in a wide margin survives none of them.";
  let style = [
    "as one simple emblem and nothing else",
    "in the manner of a stained glass church window",
    "flat panes of glass held in heavy black lead lines, the leading thick and bold and drawn inside the shape as well as around it",
    "divided into about a dozen large panes and never more, counting the field and the symbol together, each pane broad enough to hold its own, so that no lead line is ever thin",
    "drawn flat and frontal with no perspective, no shading and no gradient",
    "the whole picture shaped as one tall arched church window, standing alone on a pure black ground",
    "the colours of lit church glass - deep cobalt blue, ruby red, emerald green, violet - each one flat and saturated, luminous as glass with daylight behind it",
    "colour follows the thing and never the pane - every pane belonging to one thing is that thing's one colour, and the thing stands in a colour clearly apart from the field of glass behind it",
    "anything that has a colour of its own in life keeps it - a lamb is white glass, a flame is red, water is blue, wood is brown, iron and stone are grey, cloth is white, blood is deep red",
    "the field behind the symbol is exactly two panes of glass - one flat colour above and one flat colour below, parted by a single straight line running right across the window - and each of the two is one single colour and not several shades of the same one",
    "no gold, no amber and no yellow anywhere in the picture",
    "the arch centred and reaching almost to all four edges of the square, the symbol large inside it, bold enough to read on a phone",
    "where the church has long had a settled way of drawing this thing, drawn that way rather than in a new way invented for the occasion",
    "reverent and still, not a cartoon, not a modern logo, not a photograph",
    "nothing at all outside the arch - no border drawn around it, no ornament, no second frame",
    "no people and no faces",
    "no text and no lettering",
  ];
  return style;
}
