export function song_image_review_couplets() {
  "the couplets being put up for review this round, each with one line saying what was changed in it - the review page's whole subject, held apart from the page that draws it so that changing what is under review is an edit to a list and never to a layout";
  "a note travels with each number rather than the number travelling alone, because a picture shown by itself asks the reader to find the difference. What was changed is the one thing the person reviewing cannot see and the one thing whoever changed it already knows, so withholding it spends their attention on a question that was already answered.";
  "the note says the fault that is still there as well as the one that was fixed, and that is the half worth defending. A page that lists only what improved is asking to be agreed with; a reader told the picture is still wrong in a named way can look at the rest of it instead of rediscovering that.";
  "a couplet comes off this list the moment it is accepted, so what is here is only what is still open. Leaving an accepted picture up spends a reader's attention on a question they have already answered, and it hides how much is left.";
  "this list is meant to be short-lived and rewritten every round, which is why it is a list of its own and not a field on the couplet table. A couplet's symbol is permanent and what somebody was asked to look at last Tuesday is not.";
  "AN EMPTY LIST IS THE FINISHED STATE AND NOT A BROKEN ONE, so the page that reads it has to say so in words rather than come up blank. Every couplet that has been drawn so far has been accepted, and the next round begins by putting numbers back here - so emptiness means the reviewing is caught up with the drawing, which is the one state worth telling the reader about plainly.";
  "WHERE THREE DRAWINGS CAME FROM ONE WORDING, THE DIFFERENCES BETWEEN THEM ARE NOT A CHOICE ANYBODY MADE and the note says so, because a reader shown three pictures reasonably assumes three decisions. Naming which faults are the wording and which are the draw is what stops a rewording being spent on something no rewording reaches.";
  "A NOTE THAT HAS BEEN ASKED FOR SEVERAL ROUNDS RUNNING SAYS HOW MANY, because the count is the whole argument for changing something other than the words. One failure is a draw; five is the wording being asked to do a thing the picture as composed cannot do, and a reader who is not told the count will reasonably read the fifth failure as the first.";
  "WHERE A ROUND CAME OUT WORSE THAN THE ROUND BEFORE IT, THE NOTE SAYS WHICH EARLIER DRAWING IS STILL THE BEST ONE and where to find it, because the arrows open on the newest and a reader who trusts that order will keep a picture that lost ground. A round that went backwards is ordinary and worth recording plainly; what is not ordinary is letting the ordering hide it.";
  "WHERE A COUNT HAS GOT HIGH ENOUGH TO BE AN ANSWER, THE NOTE SAYS SO OUTRIGHT AND STOPS PROPOSING WORDINGS. Seven drawings of one wording that all fail the same way is not seven unlucky draws; it is the wording having been asked in seven ways and reaching it in none, and a note that keeps offering an eighth spends the reader on a question already settled.";
  "WHERE TWO DRAWINGS EACH HOLD HALF OF WHAT IS WANTED AND NO DRAWING HOLDS BOTH, THE NOTE NAMES BOTH AND PUTS THE CHOICE BETWEEN THEM. That is a different thing from a round going backwards, and it wants saying differently: nothing was lost, the two halves have simply turned out to cost each other, and the reader is the only one who can say which half the picture is for. A note that names only the better-looking of the two hides that a trade was made at all.";
  "WHERE A COUNT SAID THE WORDINGS WERE SPENT AND THE NEXT ROUND SUCCEEDED, THE NOTE SAYS WHAT WAS CHANGED THAT WAS NOT A WORDING. Couplet 24 was declared settled after every rewording had failed to make the stone big enough, and it came right in the very next batch - because what changed was not the words but what the picture is of. A count being high is good evidence that no rewording will reach it and no evidence at all that nothing will, and a note that lets the first be read as the second retires a couplet that was one composition away.";
  let couplets = [
    {
      n: 24,
      note: "Three back is the one. The tomb is now drawn shut with the light bursting out around the stone rather than open with the stone standing beside it, which is your idea and not a rewording, and it settled both of the two faults that fifteen wordings had failed to reach: the stone covers the entrance because it is drawn covering it rather than described as being big enough to, and the light comes from the stone because there is nowhere else it could be coming from. In that one the rock face is one smooth mass, the black of the mouth shows past the stone at both edges, the rays run right round it in all eight colours, and the white border and the flat brown ground are both intact. The two after it are the same wording drawn again, not a new attempt: one lost the white border to a crop and one lost the black at the stone's edges. The fault left in all three is that the stone is the same grey as the rock it sits against, so it reads as part of the rock until you find the black line round it - say the word and it can be drawn in white glass instead, which is what this style does with a thing that has no colour of its own to keep it apart.",
    },
  ];
  return couplets;
}
