export function song_image_couplets() {
  "the 36 couplets of the hymn 'the FATHER's SON' in order, each with the symbol chosen for it; four verses of nine, and every ninth couplet repeats the eighth, so same_as points a repeat at the couplet whose image it shares";
  "a symbol says what the thing is and never where it is, because the picture already has a where. The window supplies a field above and a field below; a symbol that also names a hill or a horizon or a stretch of ground is asking for the same thing twice, and what came back was three overlapping hills in three colours - which is also depth, the one thing the look forbids outright. Three crosses on a hill, distant became three crosses, and the distant went with it: a symbol asked to be far away cannot also be large enough to read on a phone.";
  "a symbol names one thing and never a choice between two. Scales with the beam broken or one pan forced down reads as a menu and gets picked from afresh every time, so the same couplet came back as two different objects; and here the table settles it without anyone having to have a preference, because a later couplet asks for those same scales upright and level, and scales that survive to be levelled are scales whose beam was never broken. The serpent went the same way - the verse behind it is about the serpent's head, so the broken chains beside it were never a real alternative.";
  "a symbol names the thing and never the material it is made of, because the look already decides every material and one of them is spoken for. A royal crown of gold asked for the one colour the whole film keeps back for the word of GOD; a royal crown asks for a crown, and the look gives it glass. Nothing was lost - a crown is a crown to anybody alive whether it is gold or ruby, which is most of why the crown is a good symbol in the first place.";
  "the lamb carries a cross on a staff, which is the church's own answer to a question this hymn asks: how a picture says that this lamb is CHRIST, when no face may be drawn. It is very old and it is everywhere in glass, and it costs one more shape rather than the fourteen that the seven eyes and seven horns of the lamb in Revelation would cost - a count no generator obeys, in features too small for a phone. The staff is asked for slender and bare on purpose, since the banner that often hangs from it is where lettering gets in.";
  "the burning bush stays and no Trinity symbol joins it, and the reason is what the couplet actually claims. The great I AM, the FATHER's SON says that this one, the SON, is that One who spoke from the bush - an identity, not an arithmetic. A Trinity symbol says GOD is three in one, which is true and is not what these two lines say, and putting it here would generalise away the very claim the hymn has been building towards since its title.";
  "the bush also comes off better than any of the Trinity symbols on the rules already in force. The shield of faith is made of lettering - take the words off and it is three circles and a triangle saying nothing. The triangle with an eye in it now reads to most people as a banknote. Three angels at a table is the Eastern answer and it is three faces. The triquetra alone survives, and it is a fine shape that has nothing to do with Exodus 3.";
  "and the bush is the nearest thing to a picture of the Trinity that these constraints permit anyway. It is a theophany read as GOD present and not consuming, in the East and the West alike; it is where I AM comes from; it is flame, which is already how the SPIRIT is drawn. One shape, no faces, no lettering, nothing counted. If a Trinity symbol is wanted in this film it wants a couplet that claims three in one, and there may not be one.";
  "the ram stands where Abraham and the angel stood, and it is one thing rather than a scene of four. The oldest way the church drew Genesis 22 is Abraham, Isaac bound on the wood, the ram, and a hand reaching from a cloud - which is also two faces and more panes than the window has. The ram alone keeps the substitution, keeps the covenant that GOD provides, and needs nobody drawn.";
  "the thorns are why the ram wins rather than merely why it is acceptable. A ram held by its horns in thorns rhymes with the crown of thorns four couplets earlier, so a viewer who has never read Genesis 22 still sees a creature caught in thorns in somebody's place - most of the meaning, from a shape the film has already taught. The cost is honest: a ram needs the chapter in a way a crown does not. Every emblem for this couplet does, since the chapter is the whole point, and this is the only one that leaves a reader without it something rather than nothing.";
  "a symbol may not point at another couplet either. The same scales was written for a human reader who has just seen the first pair; whatever draws this sees one line and has no memory of any other, so the same names nothing and the word is simply lost.";
  let couplets = [
    {
      n: 1,
      verse: 1,
      first: "falsely accused",
      second: "unjustly tried",
      symbol: "Scales with one pan forced down",
      ref: "",
      same_as: 0,
    },
    {
      n: 2,
      verse: 1,
      first: "though innocent",
      second: "condemned to die",
      symbol: "Pilate's basin, water poured",
      ref: "Matthew 27:24",
      same_as: 0,
    },
    {
      n: 3,
      verse: 1,
      first: "reviled and mocked",
      second: "beaten and scorned",
      symbol: "The whip",
      ref: "",
      same_as: 0,
    },
    {
      n: 4,
      verse: 1,
      first: "the KING of kings",
      second: "was crowned with thorns",
      symbol: "Crown of thorns",
      ref: "",
      same_as: 0,
    },
    {
      n: 5,
      verse: 1,
      first: "HIS hands HIS feet",
      second: "nailed to the tree",
      symbol: "Three iron nails",
      ref: "",
      same_as: 0,
    },
    {
      n: 6,
      verse: 1,
      first: "CHRIST crucified",
      second: "to pardon me",
      symbol: "A single bare cross",
      ref: "",
      same_as: 0,
    },
    {
      n: 7,
      verse: 1,
      first: "the LOVE of GOD",
      second: "for all to see",
      symbol: "Three crosses",
      ref: "",
      same_as: 0,
    },
    {
      n: 8,
      verse: 1,
      first: "my debt HE paid",
      second: "through suffering",
      symbol: "Document nailed into wood",
      ref: "Colossians 2:14",
      same_as: 0,
    },
    {
      n: 9,
      verse: 1,
      first: "my debt HE paid",
      second: "through suffering",
      symbol: "Document nailed into wood",
      ref: "Colossians 2:14",
      same_as: 8,
    },
    {
      n: 10,
      verse: 2,
      first: "forsaken by",
      second: "almighty GOD",
      symbol: "The sun blackened",
      ref: "Matthew 27:45",
      same_as: 0,
    },
    {
      n: 11,
      verse: 2,
      first: "the FATHER gave",
      second: "HIS only SON",
      symbol: "A ram caught by its horns in a thicket of thorns",
      ref: "Genesis 22",
      same_as: 0,
    },
    {
      n: 12,
      verse: 2,
      first: "cursed on a cross",
      second: "HE drank the cup",
      symbol: "A cup",
      ref: "Matthew 26:39",
      same_as: 0,
    },
    {
      n: 13,
      verse: 2,
      first: "in agony",
      second: "'til all was done",
      symbol: "An olive press",
      ref: "Gethsemane means oil press",
      same_as: 0,
    },
    {
      n: 14,
      verse: 2,
      first: "HE breathed HIS last",
      second: "and then HE died",
      symbol: "The temple veil torn in two",
      ref: "Matthew 27:51",
      same_as: 0,
    },
    {
      n: 15,
      verse: 2,
      first: "the wrath of GOD",
      second: "was satisfied",
      symbol: "A sword returning to its sheath",
      ref: "Zechariah 13:7",
      same_as: 0,
    },
    {
      n: 16,
      verse: 2,
      first: "the curse of sin",
      second: "has been undone",
      symbol: "A serpent with its head crushed",
      ref: "Genesis 3:15",
      same_as: 0,
    },
    {
      n: 17,
      verse: 2,
      first: "HE paid the price",
      second: "with HIS own blood",
      symbol: "A lamb bearing a cross on a slender staff",
      ref: "Exodus 12, John 1:29",
      same_as: 0,
    },
    {
      n: 18,
      verse: 2,
      first: "HE paid the price",
      second: "with HIS own blood",
      symbol: "A lamb bearing a cross on a slender staff",
      ref: "Exodus 12, John 1:29",
      same_as: 17,
    },
    {
      n: 19,
      verse: 3,
      first: "HIS body laid",
      second: "inside a tomb",
      symbol: "Folded linen cloths with spice jars",
      ref: "John 19:39-40",
      same_as: 0,
    },
    {
      n: 20,
      verse: 3,
      first: "hewn in the rock",
      second: "it was brand new",
      symbol: "A rock-cut tomb mouth, fresh chisel marks",
      ref: "",
      same_as: 0,
    },
    {
      n: 21,
      verse: 3,
      first: "a stone was rolled",
      second: "to seal the grave",
      symbol: "The rolling stone, closed",
      ref: "",
      same_as: 0,
    },
    {
      n: 22,
      verse: 3,
      first: "then pilate put",
      second: "the guard in place",
      symbol: "A wax seal and a Roman helmet",
      ref: "Matthew 27:66",
      same_as: 0,
    },
    {
      n: 23,
      verse: 3,
      first: "but on the third",
      second: "near dawn's first light",
      symbol: "First light on the horizon",
      ref: "",
      same_as: 0,
    },
    {
      n: 24,
      verse: 3,
      first: "the SON of GOD",
      second: "was raised to life",
      symbol: "The tomb open, stone rolled away",
      ref: "",
      same_as: 0,
    },
    {
      n: 25,
      verse: 3,
      first: "WHO conquered death",
      second: "now glorified",
      symbol: "A royal crown",
      ref: "",
      same_as: 0,
    },
    {
      n: 26,
      verse: 3,
      first: "all glory to",
      second: "the risen CHRIST",
      symbol: "Light breaking outward",
      ref: "",
      same_as: 0,
    },
    {
      n: 27,
      verse: 3,
      first: "all glory to",
      second: "the risen CHRIST",
      symbol: "Light breaking outward",
      ref: "",
      same_as: 26,
    },
    {
      n: 28,
      verse: 4,
      first: "HE will return",
      second: "to judge the earth",
      symbol: "A trumpet",
      ref: "",
      same_as: 0,
    },
    {
      n: 29,
      verse: 4,
      first: "we will receive",
      second: "what we have earned",
      symbol: "Scales, upright and level",
      ref: "",
      same_as: 0,
    },
    {
      n: 30,
      verse: 4,
      first: "we live our lives",
      second: "in godly fear",
      symbol: "A pair of sandals set down",
      ref: "Exodus 3:5",
      same_as: 0,
    },
    {
      n: 31,
      verse: 4,
      first: "HE's coming soon",
      second: "the day draws near",
      symbol: "A fig tree branch in leaf",
      ref: "Matthew 24:32",
      same_as: 0,
    },
    {
      n: 32,
      verse: 4,
      first: "with no more sorrow",
      second: "no more pain",
      symbol: "River of life, trees on both banks",
      ref: "Revelation 22:1-2",
      same_as: 0,
    },
    {
      n: 33,
      verse: 4,
      first: "for every tear",
      second: "HE'll wipe away",
      symbol: "A single drop",
      ref: "Revelation 21:4",
      same_as: 0,
    },
    {
      n: 34,
      verse: 4,
      first: "our GOD will reign",
      second: "in perfect LOVE",
      symbol: "A throne with a sceptre",
      ref: "Psalm 45:6 quoted to the Son in Hebrews 1:8",
      same_as: 0,
    },
    {
      n: 35,
      verse: 4,
      first: "the great I AM",
      second: "the FATHER's SON",
      symbol: "The burning bush, flame not consuming",
      ref: "Exodus 3:14",
      same_as: 0,
    },
    {
      n: 36,
      verse: 4,
      first: "the great I AM",
      second: "the FATHER's SON",
      symbol: "The burning bush, flame not consuming",
      ref: "Exodus 3:14",
      same_as: 35,
    },
  ];
  return couplets;
}
