export function song_image_tomb_rock() {
  "the one wording for the tomb itself, used by every couplet in the hymn that shows it, so that the tomb is the same tomb in all of them";
  "THREE COUPLETS SHOW THIS TOMB AND EACH ONE USED TO DESCRIBE IT IN ITS OWN WORDS, so they agreed only by luck and they did not agree. One came back as a rounded hillside with a built masonry arch, keystones and jambs and all; the next as an angular pointed crag; the third as three leaning slabs standing up like a dolmen with no mass of rock anywhere in it. Sung one after another they read as three different graves, which is a thing the hymn cannot say.";
  "ONE UNBROKEN MASS AND NEVER ANYTHING BUILT is the whole load-bearing clause, and it is spelled out at length rather than left to hewn. Hewn in the rock was the wording that produced the masonry arch: the drawing knows what a tomb looks like and reaches for the built one unless it is told, in the words it will not mistake, that there are no blocks and no courses and no slabs. Saying what it must not be is what saying what it must be could not do.";
  "IT ENDS ON THE OPENING AND THE NEGATIVES SIT IN THE MIDDLE, because every couplet using it goes on to say something about that opening - standing empty, covered by the stone, standing wide open and shining - and whatever this ends on is what those words attach to. Ending on the list of things the stone is not put two couplets into the drawing as slabs standing clear and empty, which is a sentence about the wrong thing and is not what either couplet meant.";
  "IT WAS ONCE MADE A DOORWAY AND THAT WAS WRONG, and the record is kept because the reasoning was good and the result was still worse. The argument was that a mass of rock is a scene and a scene leaves nowhere for the three flat sheets the style is built on, so a plain framed doorway would be the same tomb said as an emblem. The drawings obeyed it exactly and came back as clean grey door frames nobody would read as a grave, one of them with a violet pane where the mouth should be. A tomb is recognised by a dark hole in rock, and a crowded field is a smaller fault than the symbol not being the thing it is named for. So the mass came back, and the mouth is now said to be black outright, which is how the church has always drawn it.";
  "IT IS KEPT SHORT ON PURPOSE, and that was learned by making it long. Spelled out at full length it ran to three lines and the drawing came back photographic - mottled glass, shading, a cast shadow, and in one case the whole field replaced by red tracery with candles in it. The symbol and the style share one prompt, so every word added here is weight taken off the style, and a symbol described three times as carefully as the others is a symbol that stops looking like them. What is left is only what could not be dropped: the mass, the cut mouth, and the four words that stop it being built. THE PHOTOGRAPHIC DRAWING CAME STRAIGHT BACK THE DAY THIS WAS MADE LONG AGAIN, and the way it grew is worth knowing because it did not feel like lengthening: the opening was drawing too large, so the scale was said as three clauses of proportion, each one true and each one needed for the fault it was aimed at. The clause doubled and the next drawing was mottled photographic rock. A fault fixed by adding words is paid for by the style, so the fix for a wrong size is a shorter way to say the size, never an extra sentence saying it more carefully.";
  "THE FOOT OF THE OPENING IS SAID TO STAND ON THE GROUND BECAUSE OF THE COUPLET THAT SEALS IT. Fourteen drawings of the stone rolled across the mouth all came back with the stone sitting low and the black mouth still open above it, and the cause was geometry rather than wording: that couplet stands the stone on the ground, this one left the mouth free to sit high in the rock face, and a stone on the ground cannot reach a mouth that starts above it. Putting the mouth on the ground is also right for the couplet that shows it standing empty, since a grave is walked into.";
  "IT NAMES NO PERSON, AND THAT IS A TRAP THIS WORDING FELL INTO ONCE. The scale of the opening was said as a doorway for one person to stoop through, which is a good way to fix a size and a bad way to say it here: the shared style ends by forbidding people and faces, and an exception in that style is keyed on a word, so a symbol naming a person is either drawing one or cancelling the clause that forbids one. Say the scale against the rock itself - a small low doorway in a great cliff - and nothing has to be forbidden twice.";
  let r =
    "The flat upright face of one great cliff of plain grey rock filling the whole window, one unbroken face and never blocks, bricks, courses or slabs, and never a peak or a summit, with one small round topped opening cut low into the middle of it, that opening a plain hole in the rock with nothing built around it, no arch, no jambs and no stonework of any kind at its edge, broad rock standing on both sides of it and high above it, and the foot of the opening standing down on the ground so that it reaches right down to it";
  return r;
}
