import { song_image_color_text } from "./song_image_color_text.mjs";
import { song_image_color_text_quiet } from "./song_image_color_text_quiet.mjs";
import { html_style_margin_top } from "./html_style_margin_top.mjs";
import { html_style_font_size } from "./html_style_font_size.mjs";
import { html_style_padding } from "./html_style_padding.mjs";
import { html_style_line_height } from "./html_style_line_height.mjs";
import { html_border_radius } from "./html_border_radius.mjs";
import { song_image_nav_column_grid_words } from "./song_image_nav_column_grid_words.mjs";
import { song_image_prompt } from "./song_image_prompt.mjs";
import { html_div } from "./html_div.mjs";
import { html_style_set } from "./html_style_set.mjs";
import { html_text_set } from "./html_text_set.mjs";
export function song_image_nav_column(parent, state, on_change) {
  "the left column: one numbered button per couplet, grouped by verse, with the couplet now open shown in the video's own words underneath; a couplet already decided is marked, so what is left to do is readable at a glance";
  let column = html_div(parent);
  html_style_set(column, "width", "250px");
  let current = song_image_nav_column_grid_words(column, state, on_change);
  let symbol = html_div(column);
  html_style_margin_top(symbol, "14px");
  html_style_font_size(symbol, "14px");
  html_style_set(symbol, "color", song_image_color_text());
  html_text_set(symbol, current.symbol);
  let reference = html_div(column);
  html_style_margin_top(reference, "6px");
  html_style_font_size(reference, "13px");
  html_style_set(reference, "color", song_image_color_text_quiet());
  html_text_set(reference, current.ref);
  let prompt = html_div(column);
  html_style_margin_top(prompt, "16px");
  html_style_padding(prompt, "8px");
  html_style_font_size(prompt, "11px");
  html_style_line_height(prompt, "1.45");
  html_style_set(prompt, "color", "#7ec97e");
  html_style_set(prompt, "border", "1px solid #222222");
  html_border_radius(prompt, "6px");
  html_style_set(prompt, "user-select", "all");
  let text = song_image_prompt(current);
  html_text_set(prompt, text);
}
