export function song_image_couplets() {
  "the 36 couplets of the hymn 'the FATHER's SON' in order, each with the symbol chosen for it; four verses of nine, and every ninth couplet repeats the eighth, so same_as points a repeat at the couplet whose image it shares";
  let couplets = [
    { n: 1, verse: 1, first: "falsely accused", second: "unjustly tried", symbol: "Scales, beam broken or one pan forced down", ref: "", same_as: 0 },
    { n: 2, verse: 1, first: "though innocent", second: "condemned to die", symbol: "Pilate's basin, water poured", ref: "Matthew 27:24", same_as: 0 },
    { n: 3, verse: 1, first: "reviled and mocked", second: "beaten and scorned", symbol: "The whip", ref: "", same_as: 0 },
    { n: 4, verse: 1, first: "the KING of kings", second: "was crowned with thorns", symbol: "Crown of thorns", ref: "", same_as: 0 },
    { n: 5, verse: 1, first: "HIS hands HIS feet", second: "nailed to the tree", symbol: "Three iron nails", ref: "", same_as: 0 },
    { n: 6, verse: 1, first: "CHRIST crucified", second: "to pardon me", symbol: "A single bare cross", ref: "", same_as: 0 },
    { n: 7, verse: 1, first: "the LOVE of GOD", second: "for all to see", symbol: "Three crosses on a hill, distant", ref: "", same_as: 0 },
    { n: 8, verse: 1, first: "my debt HE paid", second: "through suffering", symbol: "Document nailed into wood", ref: "Colossians 2:14", same_as: 0 },
    { n: 9, verse: 1, first: "my debt HE paid", second: "through suffering", symbol: "Document nailed into wood", ref: "Colossians 2:14", same_as: 8 },
    { n: 10, verse: 2, first: "forsaken by", second: "almighty GOD", symbol: "The sun blackened, darkness over the land", ref: "Matthew 27:45", same_as: 0 },
    { n: 11, verse: 2, first: "the FATHER gave", second: "HIS only SON", symbol: "Abraham, the angel staying his hand", ref: "Genesis 22", same_as: 0 },
    { n: 12, verse: 2, first: "cursed on a cross", second: "HE drank the cup", symbol: "A cup", ref: "Matthew 26:39", same_as: 0 },
    { n: 13, verse: 2, first: "in agony", second: "'til all was done", symbol: "An olive press", ref: "Gethsemane means oil press", same_as: 0 },
    { n: 14, verse: 2, first: "HE breathed HIS last", second: "and then HE died", symbol: "The temple veil torn in two", ref: "Matthew 27:51", same_as: 0 },
    { n: 15, verse: 2, first: "the wrath of GOD", second: "was satisfied", symbol: "A sword returning to its sheath", ref: "Zechariah 13:7", same_as: 0 },
    { n: 16, verse: 2, first: "the curse of sin", second: "has been undone", symbol: "Serpent with its head crushed, or broken chains", ref: "Genesis 3:15", same_as: 0 },
    { n: 17, verse: 2, first: "HE paid the price", second: "with HIS own blood", symbol: "Blood on the doorposts", ref: "Exodus 12", same_as: 0 },
    { n: 18, verse: 2, first: "HE paid the price", second: "with HIS own blood", symbol: "Blood on the doorposts", ref: "Exodus 12", same_as: 17 },
    { n: 19, verse: 3, first: "HIS body laid", second: "inside a tomb", symbol: "Folded linen cloths with spice jars", ref: "John 19:39-40", same_as: 0 },
    { n: 20, verse: 3, first: "hewn in the rock", second: "it was brand new", symbol: "A rock-cut tomb mouth, fresh chisel marks", ref: "", same_as: 0 },
    { n: 21, verse: 3, first: "a stone was rolled", second: "to seal the grave", symbol: "The rolling stone, closed", ref: "", same_as: 0 },
    { n: 22, verse: 3, first: "then pilate put", second: "the guard in place", symbol: "A wax seal and a Roman helmet", ref: "Matthew 27:66", same_as: 0 },
    { n: 23, verse: 3, first: "but on the third", second: "near dawn's first light", symbol: "First light on the horizon", ref: "", same_as: 0 },
    { n: 24, verse: 3, first: "the SON of GOD", second: "was raised to life", symbol: "The tomb open, stone rolled away", ref: "", same_as: 0 },
    { n: 25, verse: 3, first: "WHO conquered death", second: "now glorified", symbol: "A royal crown of gold", ref: "", same_as: 0 },
    { n: 26, verse: 3, first: "all glory to", second: "the risen CHRIST", symbol: "Light breaking outward", ref: "", same_as: 0 },
    { n: 27, verse: 3, first: "all glory to", second: "the risen CHRIST", symbol: "Light breaking outward", ref: "", same_as: 26 },
    { n: 28, verse: 4, first: "HE will return", second: "to judge the earth", symbol: "A trumpet", ref: "", same_as: 0 },
    { n: 29, verse: 4, first: "we will receive", second: "what we have earned", symbol: "The same scales, upright and level", ref: "", same_as: 0 },
    { n: 30, verse: 4, first: "we live our lives", second: "in godly fear", symbol: "A kneeling silhouette", ref: "", same_as: 0 },
    { n: 31, verse: 4, first: "HE's coming soon", second: "the day draws near", symbol: "A fig tree branch in leaf", ref: "Matthew 24:32", same_as: 0 },
    { n: 32, verse: 4, first: "with no more sorrow", second: "no more pain", symbol: "River of life, trees on both banks", ref: "Revelation 22:1-2", same_as: 0 },
    { n: 33, verse: 4, first: "for every tear", second: "HE'll wipe away", symbol: "A single drop", ref: "Revelation 21:4", same_as: 0 },
    { n: 34, verse: 4, first: "our GOD will reign", second: "in perfect LOVE", symbol: "A throne with a sceptre", ref: "Psalm 45:6 quoted to the Son in Hebrews 1:8", same_as: 0 },
    { n: 35, verse: 4, first: "the great I AM", second: "the FATHER's SON", symbol: "The burning bush, flame not consuming", ref: "Exodus 3:14", same_as: 0 },
    { n: 36, verse: 4, first: "the great I AM", second: "the FATHER's SON", symbol: "The burning bush, flame not consuming", ref: "Exodus 3:14", same_as: 35 },
  ];
  return couplets;
}
