import { song_image_couplet_get } from "./song_image_couplet_get.mjs";
import { song_image_couplet_gloss } from "./song_image_couplet_gloss.mjs";
import { song_image_couplet_key } from "./song_image_couplet_key.mjs";
import { song_image_row_picture_columns } from "./song_image_row_picture_columns.mjs";
import { song_image_text_quiet_line } from "./song_image_text_quiet_line.mjs";
import { html_text_set } from "./html_text_set.mjs";
import { song_image_couplet_lines } from "./song_image_couplet_lines.mjs";
import { html_style_margin_top } from "./html_style_margin_top.mjs";
import { html_style_line_height } from "./html_style_line_height.mjs";
import { song_image_review_notes } from "./song_image_review_notes.mjs";
export function song_image_review_row(parent, asked) {
  "one couplet on the review page: its picture beside the two lines it is sung to, one line saying what was changed in it, and the notes already filed against it with a box to file another";
  "it is the audit page's band, not a second one that looks like it. Both pages set a drawing beside a column of writing and both are asking a question the reader answers by looking from one to the other, so the rule, the gap and the picture's width are held in one place and neither page can drift from the other.";
  "what was changed is written above the notes and not below them, because it is the reason the picture is on this page at all. A reader who has just been told what to look for looks for it; one who reads it after the notes has already formed an opinion the sentence then argues with.";
  "the picture is borrowed from the audit page outright, so every attempt ever drawn for the couplet is reachable from here by the arrows and any of them can be kept on the spot. Showing only the kept one would make this a page for approving rather than for choosing, and the alternative is usually the whole of what somebody wants to say.";
  let couplet = song_image_couplet_get(asked.n);
  let gloss = song_image_couplet_gloss(asked.n);
  let drawn = song_image_couplet_key(asked.n);
  let columns = song_image_row_picture_columns(parent, drawn, gloss.kept);
  let head = song_image_text_quiet_line(columns.right);
  let numbers = "verse " + couplet.verse + " · couplet " + asked.n;
  html_text_set(head, numbers);
  song_image_couplet_lines(columns.right, couplet);
  let said = song_image_text_quiet_line(columns.right);
  html_style_margin_top(said, "10px");
  html_style_line_height(said, "1.5");
  html_text_set(said, asked.note);
  song_image_review_notes(columns.right, drawn);
  let r = columns.row;
  return r;
}
