export function song_image_review_couplets() {
  "the couplets being put up for review this round, each with one line saying what was changed in it - the review page's whole subject, held apart from the page that draws it so that changing what is under review is an edit to a list and never to a layout";
  "a note travels with each number rather than the number travelling alone, because a picture shown by itself asks the reader to find the difference. What was changed is the one thing the person reviewing cannot see and the one thing whoever changed it already knows, so withholding it spends their attention on a question that was already answered.";
  "the note says the fault that is still there as well as the one that was fixed, and that is the half worth defending. A page that lists only what improved is asking to be agreed with; a reader told the picture is still wrong in a named way can look at the rest of it instead of rediscovering that.";
  "a couplet comes off this list the moment it is accepted, so what is here is only what is still open. Leaving an accepted picture up spends a reader's attention on a question they have already answered, and it hides how much is left.";
  "this list is meant to be short-lived and rewritten every round, which is why it is a list of its own and not a field on the couplet table. A couplet's symbol is permanent and what somebody was asked to look at last Tuesday is not.";
  "AN EMPTY LIST IS THE FINISHED STATE AND NOT A BROKEN ONE, so the page that reads it has to say so in words rather than come up blank. Every couplet that has been drawn so far has been accepted, and the next round begins by putting numbers back here - so emptiness means the reviewing is caught up with the drawing, which is the one state worth telling the reader about plainly.";
  "WHERE THREE DRAWINGS CAME FROM ONE WORDING, THE DIFFERENCES BETWEEN THEM ARE NOT A CHOICE ANYBODY MADE and the note says so, because a reader shown three pictures reasonably assumes three decisions. Naming which faults are the wording and which are the draw is what stops a rewording being spent on something no rewording reaches.";
  "A NOTE THAT HAS BEEN ASKED FOR SEVERAL ROUNDS RUNNING SAYS HOW MANY, because the count is the whole argument for changing something other than the words. One failure is a draw; five is the wording being asked to do a thing the picture as composed cannot do, and a reader who is not told the count will reasonably read the fifth failure as the first.";
  let couplets = [
    {
      n: 24,
      note: "three new drawings, the last three under the arrows. ONE of your three notes came back answered and it is the new one: there is now a thick heavy band of black all the way round the white inside the tomb, in all three, boldest in the first of them. That is the first new thing to land on this couplet in five rounds. The stone is still smaller than the mouth - fifth round of asking - and in the second and third it has come back as a ball rather than a flat circle, which the wording refuses by name. The rays are still a fan of wedges in the field behind the rock rather than light coming out of the white, and one thing is worth knowing before you judge that: the shared style wording was changed this round so that a symbol may have rays of its own, and it made no difference at all, so the rule was never what was stopping it. What is stopping both of them looks like the same thing, and it is not a wording fault. The rock is asked for filling almost the whole width of the window and rising almost to the top of the glass, so a stone big enough to cover the mouth would have to be nearly the size of the rock itself, and light coming out of the mouth has nowhere to go but the sky behind the rock. If that reading is right, the change that reaches both is to make the rock a low mound and let the open mouth and its light be the subject of the window - which is a change to what the picture is of, and yours rather than mine.",
    },
  ];
  return couplets;
}
