export function song_image_tomb_rock() {
  "the one wording for the tomb itself, used by every couplet in the hymn that shows it, so that the tomb is the same tomb in all of them";
  "THREE COUPLETS SHOW THIS TOMB AND EACH ONE USED TO DESCRIBE IT IN ITS OWN WORDS, so they agreed only by luck and they did not agree. One came back as a rounded hillside with a built masonry arch, keystones and jambs and all; the next as an angular pointed crag; the third as three leaning slabs standing up like a dolmen with no mass of rock anywhere in it. Sung one after another they read as three different graves, which is a thing the hymn cannot say.";
  "ONE UNBROKEN MASS AND NEVER ANYTHING BUILT is the whole load-bearing clause, and it is spelled out at length rather than left to hewn. Hewn in the rock was the wording that produced the masonry arch: the drawing knows what a tomb looks like and reaches for the built one unless it is told, in the words it will not mistake, that there are no blocks and no courses and no slabs. Saying what it must not be is what saying what it must be could not do.";
  "IT ENDS ON THE OPENING AND THE NEGATIVES SIT IN THE MIDDLE, because every couplet using it goes on to say something about that opening - standing empty, covered by the stone, standing wide open and shining - and whatever this ends on is what those words attach to. Ending on the list of things the stone is not put two couplets into the drawing as slabs standing clear and empty, which is a sentence about the wrong thing and is not what either couplet meant.";
  "IT IS A DOORWAY AND NO LONGER A MASS OF ROCK, because a mass of rock is a scene and a scene has nowhere to put the field. The style gives every window three flat sheets with the symbol standing in front of them, and a great cut face of rock filling the window from side to side leaves no room for any of the three, so the drawing quietly dropped them and came back as a grey landscape with pale corners - a fault no wording of the style could reach, because the symbol and the style were asking for two different pictures and the drawing can only obey one. A doorway is the same tomb said as an emblem: one object with an outline, standing in front of a field that still shows on both sides of it.";
  "IT IS KEPT SHORT ON PURPOSE, and that was learned by making it long. Spelled out at full length it ran to three lines and the drawing came back photographic - mottled glass, shading, a cast shadow, and in one case the whole field replaced by red tracery with candles in it. The symbol and the style share one prompt, so every word added here is weight taken off the style, and a symbol described three times as carefully as the others is a symbol that stops looking like them. What is left is only what could not be dropped: the mass, the cut mouth, and the four words that stop it being built.";
  let r =
    "One tomb doorway of plain grey stone standing alone and drawn very large, one thick square frame of flat grey stone and never blocks, bricks, courses or slabs, cut through the middle by one tall round topped opening";
  return r;
}
