export function song_image_style() {
  "how every drawn picture for this hymn is to look, said once here so that changing the look of all thirty-two is one edit rather than thirty-two";
  "it asks for the church's own art rather than a modern drawing, and that settles the cartoon question by belonging somewhere instead of by taste. A church window is what the faith has actually looked like to most of the people who ever sat under it, and a picture in that manner is legible as sacred to somebody who has never been told what it is.";
  "it names one tradition and not several, which is the whole reason this was rewritten. It used to offer an icon, a mosaic and an illuminated letter together, meaning the thing all three have in common; what was read instead was a menu, and a different member was picked each time. Two pictures came back in two different languages - one fine illuminated line work, one flat silhouette - and both obeyed the sentence, because the sentence permitted both. A clause whose purpose is sameness may name one thing only.";
  "a window rather than a mosaic or an icon, and the reason is what each medium does with black. A mosaic's gold is the ground the figure stands on, so gold-figure-on-black asks it to work inside out. An icon is built around a face, and no faces may be drawn here, so what would be left is the tradition with its subject removed. A window is already what is wanted: black lead is the line, the glass is the shape, and it is made to be looked at lit from behind by somebody sitting in the dark - which is exactly a phone in a dark frame.";
  "it asks for an emblem rather than a photograph, and the reason is sameness again. A generator asked for a photograph answers with a different lens, a different light and a different room every time, so thirty-two of them cut together look like thirty-two different films; a flat symbol is nearly the same instruction twice and comes back nearly the same twice.";
  "no gold, and that is the one rule here that is about meaning rather than about looking. Gold in this film says this is the word of GOD, carried over from the game, which is why the Scripture in the interlude is set in it. A colour only says that while something on the screen goes without it; thirty-two gold emblems would not weaken the meaning slowly, they would spend it, and the interlude would lose the very thing that set it apart. An emblem is a gloss on the word and not the word - it carries a reference, not the text - so wearing the mark of the word would be claiming a standing it does not have.";
  "the glass is coloured because a window's glass is coloured, so the rule above costs nothing to keep. Cobalt, ruby, emerald and violet are what is actually in a church window, they are nowhere near the gold, and being nowhere near it is the point - a colour half a step off the gold would be the worst of the three possible answers, since a difference too small to be meant still reads as a mistake.";
  "no amber and no yellow either, for the same reason and by the same measure. They are the near misses of gold rather than alternatives to it, and a near miss is what the rule above exists to avoid.";
  "legibility no longer rides on the colour, which is what makes dropping the gold affordable. It rides on heavy leading, on a dozen large panes and on a shape that fills its square - all three now asked for above - so a deep blue emblem carries as far across a room as a pale gold one did.";
  "the detail inside the shape is asked for as heavy black leading rather than as fine drawing, and that is a decision about the far end rather than about taste. Fine line work is the first thing a small screen eats; leading is thick by its nature, so in this one medium the interior detail is the part that survives being shrunk instead of the part that disappears.";
  "how many panes there are is said as well as how thick the leading is, because asking only for thick leading does not get it. Three crosses and a lamb were drawn from the same sentence and came back with lead lines of completely different weights - the crosses heavy, the lamb hairline. The subject decided it: a fleece invites fifty small divisions and a cross invites a dozen large ones, and the leading then thins to fit however many were drawn. Thickness is what comes out of the pane count rather than something that can be asked for beside it, so the count is the thing to say.";
  "flat is said twice over, because a drawing came back with a gradient washed across it after being told not to shade, and another grew a pair of brown hooves after being told every pane was one colour. A refusal is obeyed unevenly from one drawing to the next, so the ones that have already been broken once are worth saying positively as well as negatively.";
  "colour is said to follow the thing rather than the pane, and that sentence is here because leaving it out produced the worst picture of the lot. Asking for a dozen panes each one flat colour reads as an instruction to vary the colour pane by pane. A subject that already has parts survives that by luck - three crosses on a hill have a sky, a slope and the crosses themselves, so the panes fall on boundaries that mean something. A lamb has no parts. Its panes are arbitrary cuts across one animal, and colouring each of them separately produced a harlequin: a magenta head, a blue shoulder, a red flank, a purple leg. In a real window the lamb is white glass and the sky behind it is blue, because colour belongs to the thing depicted and the leading is only where two things meet.";
  "the field is held to two plain areas, and the pane count is said to cover the field as well, because saying colour follows the thing did not fix the harlequin so much as move it. The lamb came back one green - the rule worked on the subject - and the sky behind it came back in eight colours at once, because the field was never named as a thing and so had no colour of its own to follow. A window has a restful field and one busy subject; both busy is a window nobody can read across a room.";
  "the field is said as a shape rather than as a number, and that is the general lesson here rather than a detail about fields. It was asked for as two or three broad areas twice, and twice came back as six or eight - a count is a soft thing to a generator, something to round up towards while still feeling obedient, and there is no moment while drawing at which a fourth colour is refused. One flat colour above, one below, one line across is not a count at all: it is a shape, and it is either drawn or it is not. Say what to draw, not how many.";
  "not several shades of the same one is said because that is how the count was got round rather than broken. The field came back as reds - crimson, scarlet, maroon, rose - which is four colours to the eye and one colour to whoever drew it. A rule about how many colours there are needs saying in the reader's terms and not the drawer's.";
  "what replaces gold is said outright, because the two rules above were quietly fighting the one below them. A thing keeps the colour it has in life, and the church's settled way of drawing a thing is the way to draw it - and a cup in life is gold, and the church's settled cup is a gold chalice. So a rule about materials and a rule about inheritance both pointed straight at the one colour that is spent elsewhere, and a chalice came back gold, rim and bowl and foot. A refusal that leaves a hole gets filled by whatever else was asked for; naming ruby as the substitute closes the hole rather than defending it.";
  "the head of the arch is given its own colour, and that is not a fourth loosening of this rule but an admission that it could not be obeyed. A tall arched window has a lunette at the top - a fan of panes above the springing line - and that lunette is part of the architecture rather than part of the field. Asking for a field of exactly two panes in an arched window asks for something no window has, so what came back was two fields and a lunette, over and over, which was obedience misread as failure. Three regions named is the shape that was actually being drawn all along.";
  "a thing keeps whatever colour it has in life, because the rule above says only that the symbol differs from the field and leaves what it is to chance. Asked that way it produced a green lamb - obedient and wrong. This is also how real glass works, which is the usual sign that the rule belongs here rather than being invented for the occasion.";
  "the materials are listed one by one rather than left to that rule, because a rule about what things are like in life is only ever obeyed for the things somebody thought to name. A lamb was named and came back white; wood was not, and three wooden crosses came back white too - not by disobedience but by default, white being where a drawing goes when no colour has been asked for. The symbols in this hymn are made of very few materials between them - wood, iron, stone, cloth, water, fire, blood - so naming all of them costs one clause and removes the default from every couplet at once.";
  "the black ground is said first and by itself, and that is a decision about the length of this list rather than about black. It used to arrive halfway down, tucked onto the end of the clause describing the arch, and it survived there until the list grew to seventeen clauses - at which point a picture came back on plain white, with the field rule newly obeyed and the background silently dropped. Nothing contradicted it; there was simply too much else being asked for. So the clauses are no longer all worth the same: what everything else is drawn on has to be settled before there is anything to draw, and it goes where it cannot be crowded out.";
  "that white picture is also the general warning this file needs, since every entry here was added the same way. Each new clause is bought with attention taken from the ones already present, so a rule that fixes what it names can still make the picture worse overall, and it will do it silently - the field was repaired and the background lost in the same drawing. Adding a clause was free while the list was short and it is not free now. The next few repairs want to be rewordings and mergings rather than additions.";
  "the field is told what not to be broken into as well as what to be, and the thing named is radiance, because that is what it kept coming back as. Asked for one colour above and one below, a chalice came back standing in a fan of coloured wedges spreading out from it in every direction - roughly fifteen field panes and no straight line anywhere. That is not carelessness: a subject standing in a burst of light is one of the commonest things a real window does, so the plain field is competing against a strong inherited habit rather than against nothing, and a rule with nothing on the other side of it loses. Naming the wedges and the rays and the halo is what gives the refusal something to hold on to.";
  "the border round the arch is now asked for rather than refused, and that is a surrender that improves the picture. It was forbidden three times in three different words - no ornament outside the arch, then no ring of small panes inside it, then no band of any colour on either side - and it came back all three times, as a white ring, then a coloured band, then columns of small squares down both flanks. Three refusals is enough evidence: a real window has border glass, so the refusal leaves a hole in something the drawing knows how to build, and it gets filled by whatever is nearest.";
  "so what was actually wrong with it is named instead, which was never the border itself. What spoiled those pictures was that the border came back as a row of separate small panes in four or five colours - which is a dozen extra panes in a picture allowed a dozen altogether, and colours arriving from nowhere. One unbroken band of one flat colour costs a single pane, cannot introduce a colour, and is what a plain window actually has. The fight was over the ornament and the cost, and both are settled by specifying it.";
  "this is now the third time the same remedy has worked, so it is the rule of this file rather than three coincidences: say what to draw. The black ground came back the moment it was asked for positively, the field settled the moment the radiating wedges were named as a thing rather than left as an absence, and the border stops being confetti the moment it is given a shape. A refusal names a thing without saying what stands in its place, and something always stands in its place.";
  "horn and hoof are named alongside the rest because leaving them out cost the gold rule a picture. A lamb was drawn with amber horns and cream hooves, and neither was disobedience: horn and hoof really are that colour in life, so the rule that a thing keeps its colour pointed straight at the one colour spent elsewhere, exactly as it did with the gold chalice. Any material this hymn's symbols are made of and nobody has named is a hole the default fills, and the default for horn is amber - so naming it is the fix and forbidding it again would not have been.";
  "the ground outside the arch is now said as something to draw rather than only as something to leave alone, and that is the flat-is-said-twice lesson reaching a second clause. Nothing at all outside the arch was already there and a decorative border came back outside the arch anyway. A refusal names a thing and thereby puts it in mind; bare black glass to all four edges asks for the emptiness positively, which is a thing that can be drawn.";
  "an arch and a field of glass behind the symbol, which reverses what this used to ask for. It used to forbid a background outright, and that was right while the picture was one shape floating on black. A window is not one shape floating on black - it is a subject set in a field, held in a frame - and the drawing that discovered this was the best of the set precisely because it broke the old rule and supplied all three unasked. The field is also what gives the symbol something to be a different colour from, so forbidding it and asking colour to follow the thing cannot both be had.";
  "the old way of drawing a thing is asked for wherever there is one, and that is about unity rather than about taste. These emblems are older than the divisions between the churches - a cross, a lamb, a crown, a cup, a trumpet, a burning bush are common property, and somebody who has only ever sat in one kind of building still reads all of them. An invented emblem belongs to whoever invented it, which here would be a machine; an inherited one is already everybody's. Inheriting is also simply better drawing, since a form that has been redrawn for centuries has had every unreadable version discarded already.";
  "one settled way is asked for and not several named ones, and that is the menu lesson again in a place it would be easy to forget it. Naming the Roman, the Eastern and the Reformed manner together to mean the thing all three share would be read as three options and picked from afresh each time, and thirty-two pictures would come back from three different centuries. Where a form really is common to all three, asking for the old one gets it without naming anybody.";
  "no faces is not the same rule as no people, though it has been treated as one. What some of those watching hold is that the LORD should not be drawn; that does not reach Abraham, who is not GOD. What keeps people out anyway is nearer to hand - a drawn face is the thing a generator is worst at and the thing a viewer forgives least, and a window with people in it is a scene rather than an emblem, which the pane count and the flat frontal rule are not built for.";
  "the clauses were merged rather than added to, and the count matters more than the wording of any one of them. Eighteen separate asks had become long enough that the ones in the middle were being dropped - a picture came back on white while obeying a field rule added minutes earlier - so the same rules are now said in nine clauses instead, with the redundant one about the ground outside the arch removed entirely and the pairs that were always about one subject joined up: flatness with the refusal of photography, leading with the pane count, the arch with its size and its border, colour-follows-the-thing with the list of what things are. Nothing here was given up. It is said in fewer places, which is what the drawing was running out of room for.";
  "centred and large because the far end of this is a phone held at arm's length, sometimes behind a cracked protector, sometimes by eyes that no longer see small things. A shape that fills its square survives all three; a small shape in a wide margin survives none of them.";
  let style = [
    "on a pure solid black background, the black filling the whole square right out to all four edges and lying behind everything else in the picture",
    "as one simple emblem and nothing else, reverent and still, drawn perfectly flat and frontal - no perspective, no shading, no gradient, no texture, no highlight, not a photograph and not a modern logo",
    "in the manner of a stained glass church window, flat panes of glass held in heavy black lead lines, the leading thick and bold and drawn inside the shape as well as around it, the whole divided into about a dozen large panes and never more, counting the field and the symbol together, each pane broad enough to hold its own so that no lead line is ever thin",
    "the whole picture shaped as one tall arched church window standing alone on that black ground, centred and reaching almost to all four edges of the square, the symbol large inside it and bold enough to read on a phone, the arch edged by one plain unbroken band of a single flat colour and never by a row of separate small panes",
    "the colours of lit church glass - deep cobalt blue, ruby red, emerald green, violet - each one flat and saturated, luminous as glass with daylight behind it",
    "colour follows the thing and never the pane - every pane belonging to one thing is that thing's one colour, the thing stands in a colour clearly apart from the field behind it, and anything that has a colour of its own in life keeps it: a lamb is white glass, a flame is red, water is blue, wood is brown, iron and stone are grey, cloth is white, blood is deep red, horn and hoof are white glass like the fleece",
    "the head of the arch is one single colour all the way across, and below it the field behind the symbol is one flat colour above and one flat colour below, parted by a single straight line running right across the window - three colours in all behind the symbol, each one single and not several shades of the same one, the field lying quiet and unbroken behind the symbol and never cut into wedges, rays, spokes, petals or a halo spreading outwards from it",
    "no gold, no amber and no yellow anywhere in the picture, not as a rim, an edge, a lining or a highlight either, and anything that would be gold or amber or cream in life - a cup, a crown, a lampstand, a trumpet, a horn, a hoof - is drawn in ruby or white glass instead",
    "where the church has long had a settled way of drawing this thing, drawn that way rather than in a new way invented for the occasion",
    "no people, no faces, no text and no lettering anywhere",
  ];
  return style;
}
