export function song_image_review_couplets() {
  "the couplets being put up for review this round, each with one line saying what was changed in it - the review page's whole subject, held apart from the page that draws it so that changing what is under review is an edit to a list and never to a layout";
  "a note travels with each number rather than the number travelling alone, because a picture shown by itself asks the reader to find the difference. What was changed is the one thing the person reviewing cannot see and the one thing whoever changed it already knows, so withholding it spends their attention on a question that was already answered.";
  "the note says the fault that is still there as well as the one that was fixed, and that is the half worth defending. A page that lists only what improved is asking to be agreed with; a reader told the picture is still wrong in a named way can look at the rest of it instead of rediscovering that.";
  "a couplet comes off this list the moment it is accepted, so what is here is only what is still open. Leaving an accepted picture up spends a reader's attention on a question they have already answered, and it hides how much is left.";
  "this list is meant to be short-lived and rewritten every round, which is why it is a list of its own and not a field on the couplet table. A couplet's symbol is permanent and what somebody was asked to look at last Tuesday is not.";
  "AN EMPTY LIST IS THE FINISHED STATE AND NOT A BROKEN ONE, so the page that reads it has to say so in words rather than come up blank. Every couplet that has been drawn so far has been accepted, and the next round begins by putting numbers back here - so emptiness means the reviewing is caught up with the drawing, which is the one state worth telling the reader about plainly.";
  "WHERE THREE DRAWINGS CAME FROM ONE WORDING, THE DIFFERENCES BETWEEN THEM ARE NOT A CHOICE ANYBODY MADE and the note says so, because a reader shown three pictures reasonably assumes three decisions. Naming which faults are the wording and which are the draw is what stops a rewording being spent on something no rewording reaches.";
  "A NOTE THAT HAS BEEN ASKED FOR SEVERAL ROUNDS RUNNING SAYS HOW MANY, because the count is the whole argument for changing something other than the words. One failure is a draw; five is the wording being asked to do a thing the picture as composed cannot do, and a reader who is not told the count will reasonably read the fifth failure as the first.";
  "WHERE A ROUND CAME OUT WORSE THAN THE ROUND BEFORE IT, THE NOTE SAYS WHICH EARLIER DRAWING IS STILL THE BEST ONE and where to find it, because the arrows open on the newest and a reader who trusts that order will keep a picture that lost ground. A round that went backwards is ordinary and worth recording plainly; what is not ordinary is letting the ordering hide it.";
  "WHERE A COUNT HAS GOT HIGH ENOUGH TO BE AN ANSWER, THE NOTE SAYS SO OUTRIGHT AND STOPS PROPOSING WORDINGS. Seven drawings of one wording that all fail the same way is not seven unlucky draws; it is the wording having been asked in seven ways and reaching it in none, and a note that keeps offering an eighth spends the reader on a question already settled.";
  "WHERE TWO DRAWINGS EACH HOLD HALF OF WHAT IS WANTED AND NO DRAWING HOLDS BOTH, THE NOTE NAMES BOTH AND PUTS THE CHOICE BETWEEN THEM. That is a different thing from a round going backwards, and it wants saying differently: nothing was lost, the two halves have simply turned out to cost each other, and the reader is the only one who can say which half the picture is for. A note that names only the better-looking of the two hides that a trade was made at all.";
  "WHERE A COUNT SAID THE WORDINGS WERE SPENT AND THE NEXT ROUND SUCCEEDED, THE NOTE SAYS WHAT WAS CHANGED THAT WAS NOT A WORDING. Couplet 24 was declared settled after every rewording had failed to make the stone big enough, and it came right in the very next batch - because what changed was not the words but what the picture is of. A count being high is good evidence that no rewording will reach it and no evidence at all that nothing will, and a note that lets the first be read as the second retires a couplet that was one composition away.";
  "WHERE A FAULT WAS FIXED BY NAMING A COLOUR, THE NOTE SAYS THAT SIX DRAWINGS ALL HELD THE FIX, because that is what tells a reader the remaining faults are not the wording. A change that lands in every single draw is a change the style obeys outright, and once one is found the rest of the round is only waiting for a draw that happens to get the border right as well - which is a thing to wait for and never a thing to reword.";
  let couplets = [
    {
      n: 2,
      note: "you asked for closer to a side view and this is one: a flat grey basin on a short foot with a flat band of blue water lying across the rim, drawn straight on with no depth in it. The from-above wording that came before is gone, and going back to a side view cost nothing - the field came out clean on the first try, cobalt over emerald over deep crimson with the white glass only round the outer edge. The white bar across the middle is gone too, and it was never the design whatever was said here before: it was one of the two dividing lines drawn as a bar of white stone instead of a thin black lead line, and the style now forbids that in every picture. Nothing is named as still wrong in this one - if it is right, say so and it comes off the list.",
    },
    {
      n: 11,
      note: "the ram now wears the yellow halo you asked for twice, and it is a plain circle with nothing inside it. That is deliberate rather than a shortcut: a cross inside the halo is the church's mark for the Persons of the Trinity, and a plain circle is its mark for someone God has set apart. The ram of Genesis 22 is the substitute God provided in Isaac's place - a picture of CHRIST and not CHRIST - so the plain circle is the true one, and it is also what tells this window apart from the lamb in couplet 18. Now the trade, and it is a real one: this drawing has the right field and no ring of thorn round the horns, while an earlier one had the ring of thorn and its field went to pale blue and violet. Three drawings since have each given one or the other and none has given both. If the crown matters more than the field, say so and the field can be fought for afterwards.",
    },
    {
      n: 18,
      note: "you asked whether it should just be a yellow halo. It should, and it now is: the red cross bars are out of the halo and the cross has moved to the top of the staff, which is the way the church has drawn this lamb for centuries. The reason is not tidiness - across four rounds not one drawing has ever held a cross in the halo and a cross on the staff at the same time, so asking for both was asking for a picture that has never once come back. The picture shown is still attempt 19, because the two drawings made since lost the staff altogether while getting the halo right. This is the sixth round on this one window, which is enough to say the fault is not the words: a lamb, a halo, a cross-topped staff and a hoof closed round that staff is more than one drawing will hold. So the question is yours - shall the staff go, and the lamb stand instead on the sealed scroll of Revelation 5, which is the verse this couplet already names?",
    },
  ];
  return couplets;
}
