export function sword_book_codes() {
  "The name a Sword module calls each book by, said against the name this repo calls the same book by.";
  "Two spellings of the same sixty-six books. A Sword module writes them the way the OSIS scheme does - Gen, Exod, Song, Matt, Phlm - and everything else here writes them the way eBible does - GEN, EXO, SNG, MAT, PHM. Neither spelling can be worked out from the other; Song and SNG share three letters and Nah and NAM share two, so the pairing is said rather than derived.";
  "THE PAIRING IS WRITTEN OUT RATHER THAN LINED UP SIDE BY SIDE. Both lists happen to run in the same order today, so pairing the first with the first would work and would go on working until one list gained a book the other did not have - at which point every book after it would be filed under its neighbour's name and every verse would land in the wrong place, with nothing anywhere to complain about it. Saying each pair once costs sixty-six lines and cannot come apart.";
  let codes = {
    Gen: "GEN",
    Exod: "EXO",
    Lev: "LEV",
    Num: "NUM",
    Deut: "DEU",
    Josh: "JOS",
    Judg: "JDG",
    Ruth: "RUT",
    "1Sam": "1SA",
    "2Sam": "2SA",
    "1Kgs": "1KI",
    "2Kgs": "2KI",
    "1Chr": "1CH",
    "2Chr": "2CH",
    Ezra: "EZR",
    Neh: "NEH",
    Esth: "EST",
    Job: "JOB",
    Ps: "PSA",
    Prov: "PRO",
    Eccl: "ECC",
    Song: "SNG",
    Isa: "ISA",
    Jer: "JER",
    Lam: "LAM",
    Ezek: "EZK",
    Dan: "DAN",
    Hos: "HOS",
    Joel: "JOL",
    Amos: "AMO",
    Obad: "OBA",
    Jonah: "JON",
    Mic: "MIC",
    Nah: "NAM",
    Hab: "HAB",
    Zeph: "ZEP",
    Hag: "HAG",
    Zech: "ZEC",
    Mal: "MAL",
    Matt: "MAT",
    Mark: "MRK",
    Luke: "LUK",
    John: "JHN",
    Acts: "ACT",
    Rom: "ROM",
    "1Cor": "1CO",
    "2Cor": "2CO",
    Gal: "GAL",
    Eph: "EPH",
    Phil: "PHP",
    Col: "COL",
    "1Thess": "1TH",
    "2Thess": "2TH",
    "1Tim": "1TI",
    "2Tim": "2TI",
    Titus: "TIT",
    Phlm: "PHM",
    Heb: "HEB",
    Jas: "JAS",
    "1Pet": "1PE",
    "2Pet": "2PE",
    "1John": "1JN",
    "2John": "2JN",
    "3John": "3JN",
    Jude: "JUD",
    Rev: "REV",
  };
  return codes;
}
