import { arguments_assert } from "./arguments_assert.mjs";
import { text_word_regex_plain_assert } from "./text_word_regex_plain_assert.mjs";
export function text_word_start_regex(word) {
  "$plain word";
  arguments_assert(arguments, 1);
  ("One word, written as the pattern that finds it where it begins a word and lets it run on to whatever ending follows - the rule by which a word is judged to be really there rather than sitting as letters inside an innocent longer one.");
  ("★ THIS IS WRITTEN ONCE BECAUSE TWO DIFFERENT JOBS HAVE TO AGREE ABOUT IT EXACTLY. One of them takes a word out of everything a repository has ever held; the other decides which forgotten files a purge should drop, by asking whether their names hold the word. If those two read the same word by two rules, the purge takes a file's contents out and leaves its name, or takes a name out that the contents were allowed to keep - and neither mistake announces itself. Spelled here, the two cannot drift, because there is nothing for them to drift apart from.");
  ("★ WHETHER A CAPITAL LETTER COUNTS IS NOT DECIDED HERE, AND TRYING TO DECIDE IT HERE BREAKS TWO OF THE THREE READERS. It belongs in the answer - the words worth taking out of a past are names, and a name is capitalised wherever it stands in an ordinary sentence - and every reader of this pattern is told to set the letter aside. But each has to be told in its own words. Written into the pattern, the mark that says so is taken by the tool that rewrites the past, refused outright by the reading that counts what a purge left behind, and cannot be built at all by this language's own matcher. All three were tried: one worked, one stopped with a complaint about the pattern, one would not compile. So the instruction lives at each of the three readers, and what must not differ between them is that every one of them carries it.");
  ("The mark at the start is the whole of the safety. The words worth taking out are short, and a short word is a run of letters in the middle of many innocent ones: one of them sat inside the name of a drawing function in three files that had nothing to do with it, and a plain sweep would have rewritten those in every commit since they were written, quietly, with no way back. A letter standing in front of the word takes the match away.");
  ("That mark is also what makes setting the letter aside safe rather than reckless. The fear worth having about ignoring capitals is that a word starts matching inside other words; it does not, because the mark still stands between a letter and something that is not one. Measured on a throwaway: with the letter set aside the word went wherever it began a word, and the one sitting inside a longer word stayed exactly where it was.");
  ("Past the start the name is allowed to run on, because the names worth taking out come in families sharing a beginning - one beginning here had eleven endings - and marking the far end too would mean writing every ending down, where the one that gets forgotten is the one nobody will look for again.");
  ("What a word may be made of is asked elsewhere, because the pattern that asks for several words at once has to refuse exactly the same things. Two spellings of that refusal could drift apart, and the looser of them would take a bracket or a bar and ask for something other than what it was handed.");
  text_word_regex_plain_assert(word);
  let pattern = "\\b" + word + "\\w*";
  return pattern;
}
