import { arguments_assert } from "./arguments_assert.mjs";
export function urdu_roman_spellings_most() {
  "How many of a word's Latin spellings get looked for, counting from the one most people gave it.";
  "There has to be a number because the spellings of the pieces are multiplied together. A word cut into three pieces with every spelling of each kept would be looked for hundreds of ways, and the whole reading is already a scan of a whole Bible for every one of them.";
  "More than one because one would be a guess wearing a list's clothes, and the list exists precisely because there is no single right spelling. Fewer than all because the tail of the list is where the spellings one person typed once live, and a spelling one person typed once is not evidence about how a Bible is printed.";
  "★ FIVE IS WHERE THE ANSWERS STOP ARRIVING, AND THAT WAS MEASURED RATHER THAN CHOSEN. Counted over all three hundred and twenty-eight rulings, three leaves a hundred and twenty-five of them with nothing said either way; five leaves ninety-nine, so twenty-six words come out of silence for twice the looking. Eight leaves ninety-five and twelve leaves ninety-three, which is four more words and then two more for another half again of the work. The number was three before this was counted, and three was costing a word its whole answer: the word for you will take was contradicted fifty-four times over by a spelling that sat fourth in its list, and at three that spelling was never looked for, so the reading came back silent and silence reads as a control having no opinion.";
  "★ THE FOUR WORDS EIGHT WOULD BUY WERE READ ONE BY ONE AFTERWARDS, AND THEY DO NOT CARRY THEIR PRICE. Counting how many words stop being silent cannot tell an answer apart from a wrong answer, so the four were looked at instead of counted. One is a real confirmation on a word appearing thirty-eight times. One is a real objection on a word appearing three times. One is a spelling that has nothing to do with its word, landing on a word appearing once. The fourth is the run-together spelling the Latin alphabet always writes for a future ending, which is not the printing having an opinion about spacing at all, so at eight that word would stop being silent and start being wrong. Two answers and two mistakes is not what half again the work should buy.";
  "It is the same number for the joined-up spelling and for the spaced one, so that neither side of the comparison is looked for more thoroughly than the other. Two different numbers here would put a thumb on the scale of whichever got the larger one, and the thing being weighed is exactly which of the two the printing prefers.";
  "★ RAISING IT MAKES A DIFFERENT MISTAKE MORE LIKELY, AND THAT MISTAKE IS NOT CAUGHT HERE. A word cut into pieces can spell an ordinary phrase that has nothing to do with it - the word for bronze comes apart into from the ear - and every extra spelling looked for is another chance of landing on one. Those show up as a contradiction carrying a handful of occurrences against a word that appears in the hundreds, and telling them apart is a job for whatever reads the counts, not for this number.";
  arguments_assert(arguments, 0);
  let most = 5;
  return most;
}
