export function webpack_config_node_builtins_names() {
  let names = [
    "fs",
    "fs/promises",
    "path",
    "child_process",
    "readline",
    "url",
    "stream",
    "stream/promises",
    "util",
    "os",
    "querystring",
    "assert",
    "crypto",
    "http",
    "https",
    "http2",
    "net",
    "tls",
    "tty",
    "zlib",
    "dns",
    "dgram",
    "module",
    "worker_threads",
    "perf_hooks",
    "buffer",
    "events",
    "process",
    "timers",
    "timers/promises",
    "vm",
    "v8",
    "inspector",
  ];
  return names;
}
