export function word_picture_wordings() {
  "What to draw for each taught word that can be shown as a picture, keyed by the same base form the gloss list spells.";
  "NOT EVERY TAUGHT WORD IS IN HERE, AND THE ONES LEFT OUT WERE LEFT OUT ON PURPOSE. A picture is worth drawing when the word names a thing you could point at or a piece of work you could watch somebody do. TRUTH and JOY and GUILT name none of those, and a picture of one is a picture of some particular scene the word merely turned up in - which teaches the scene and not the word. DARKNESS would come back as a black rectangle. DEATH would come back as a grave, which says nothing the sentence did not already say and makes a hard thing harder to look at for no gain.";
  "GOD AND JESUS ARE NOT IN HERE AND MUST NEVER BE. A drawn face of God is a claim about what God is like, made by a machine, shown to a child as though somebody had checked it - and that whole class of thing is exactly what the human's reading is reserved for. RAISE and ROSE are out for the same reason: the only scene either one names is His.";
  "THE CROSS IS IN, AND IT IS BARE. Its gloss says two long pieces of wood, and two long pieces of wood is what gets drawn - nobody on it, nobody near it. That is the word the child tapped.";
  "A WORD THAT NAMES WORK IS DRAWN AS A STRIP OF PANELS, because the work is what the word means and one frozen moment out of it shows a person standing near some wool. The panels run left to right in the order the work is done, which is the order the sentence under them reads in.";
  "KEEPING GOD OUT OF THE LIST IS NOT THE SAME AS KEEPING HIM OUT OF THE PICTURES, and the first attempt at FELLOWSHIP proved it. Asked for people sharing bread by lamplight, the machine composed the Last Supper - a bearded figure at the centre, lit brightest, facing out, with the others turned toward him - because that is the picture the world has of that scene. The word never named Him and the picture showed Him anyway. So a wording for a scene the gospels also contain has to say what it is not: no central figure, nobody facing the viewer, nobody set apart.";
  "A PICTURE CAN BE A GOOD PICTURE AND STILL NOT SAY THE WORD, and that is the failure the second attempts were for. The first DYER was a dyer standing in a room full of colour, which teaches the room; a dyer is a person doing the dyeing, so the wording now has the wool in the air and the water running off it. The first OFFER was two hands holding bread, which teaches bread; offering is done toward somebody, so the second person is now in the frame - still not reaching, because an offer that has been taken is a different word. The first WEAVE was pale thread crossing pale thread, so the crossing, which is the whole of what the word means, could not be seen; the crossing thread is now a different colour from the standing ones. The common fault is a wording that names the setting the word lives in and leaves out the thing the word actually is.";
  "THE WORDING SAYS NO LETTERING. A drawing machine asked for wool and a pot will cheerfully write WOOL across the top of it, in a spelling nobody checked, in a language the reader may not have - and this picture exists for a child who is stuck on one word already.";
  let r = {
    cross:
      "A bare wooden cross standing alone on a low hill against a wide pale sky. Two rough dark beams, one laid across the other and bound at the crossing with rope. Nobody on it and nobody near it. Warm daylight, quiet, painted plainly. No lettering anywhere in the picture, and no painted signature in any corner.",
    dye: "A strip of three panels side by side, left to right, in a first-century workshop. First panel: a bundle of plain undyed wool, pale and clean, held in two hands. Second panel: the same wool pushed down into a wide clay pot of dark water, the water almost black. Third panel: the wool lifted out and hung on a line to dry, now deep dark all through. Warm daylight, plain earthy colours. No lettering anywhere in the picture.",
    dyer: "A dyer in the middle of the work in a small first-century workshop, standing over a wide clay pot of dark water and lifting a heavy skein of newly dyed wool out of it with both hands, the dark water still running off it back into the pot. Both arms are stained dark past the wrist and the stain is plain to see. Lengths of dyed cloth hang on lines behind them. Seen close enough that the hands and the dripping wool fill much of the picture. Calm and unhurried, the look of somebody who does this every day. Warm daylight, plain earthy colours. No lettering anywhere in the picture.",
    weave:
      "A strip of three panels side by side, left to right, in a first-century workshop, all three showing the same upright wooden loom. The standing threads are pale cream and the crossing thread is deep red, so that every place one passes over the other can be seen at a glance. First panel: the pale threads alone, stretched tight and parallel, nothing crossing them yet. Second panel: a hand drawing one thick red thread across, clearly over one pale thread and under the next, halfway along. Third panel: the lower part of the same loom filled with finished cloth, banded through with the red crossing threads, the pale threads still bare above it. Warm daylight, plain earthy colours. No lettering anywhere in the picture.",
    offer:
      "Two people seen from the side in a plain first-century street, both in frame. One holds a small round loaf of bread out on two open hands toward the other, arms extended. The other is looking at the loaf with their own hands still down at their sides, not reaching for it: the bread is held out and has not been taken. Neither of them is at the middle of the picture and neither is facing the viewer. First-century clothing, plain background, warm daylight. No lettering anywhere in the picture.",
    pray: "One person kneeling alone in a small plain room in a first-century stone house, wearing a plain woven tunic, head bowed and hands open and empty in front of them, a small clay oil lamp burning on the floor beside them. Nobody else there, and nothing above them but the quiet room. Warm lamplight, soft shadows. No modern clothing and nothing modern in the room. No lettering anywhere in the picture.",
    fellowship:
      "Five people of different ages sitting close together on the floor around a small round table in a plain first-century house, sharing bread and a jug by lamplight, leaning in and talking to each other. They are grouped off to one side of the picture and nobody sits at the middle of it. Everyone is turned toward somebody; nobody is sitting apart. This is an ordinary evening meal among neighbours and is not the Last Supper: nobody is set apart from the others, nobody is facing the viewer, and there is no central figure. First-century clothing, warm lamplight, plain room. No lettering anywhere in the picture.",
  };
  return r;
}
