export function youtube_signed_in_script() {
  "The small piece of javascript that, pasted into a youtube page somebody is already signed in on, gives that page the four things a playlist change needs: proof of who is asking, a way to write words under a playlist, a way to put a song into one, and a way to send a song already in one to the end.";
  "The signing-in is the part no reader here can do, and it is deliberately left where it already is rather than copied into this repo. Nothing about anybody's account is written down; the page proves who it is from the cookie it already has.";
  "It is kept as words rather than as a file to be loaded because the page refuses to fetch anything from elsewhere, so the only way in is to be pasted, and a paste that has to be typed out fresh each time is a paste that drifts.";
  let lines = [
    "window.sapisid_hash = async function () {",
    "  const cookie = document.cookie.split('; ').find(c => c.startsWith('SAPISID=') || c.startsWith('__Secure-3PAPISID='));",
    "  const value = cookie.split('=').slice(1).join('=');",
    "  const origin = 'https://www.youtube.com';",
    "  const ts = Math.floor(Date.now() / 1000);",
    "  const bytes = new TextEncoder().encode(ts + ' ' + value + ' ' + origin);",
    "  const digest = await crypto.subtle.digest('SHA-1', bytes);",
    "  const hex = [...new Uint8Array(digest)].map(b => b.toString(16).padStart(2, '0')).join('');",
    "  return 'SAPISIDHASH ' + ts + '_' + hex;",
    "};",
    "window.playlist_edit = async function (playlist_id, actions) {",
    "  const cfg = window.ytcfg.data_;",
    "  const res = await fetch('/youtubei/v1/browse/edit_playlist?key=' + cfg.INNERTUBE_API_KEY, {",
    "    method: 'POST', credentials: 'include',",
    "    headers: {",
    "      'Content-Type': 'application/json',",
    "      'Authorization': await window.sapisid_hash(),",
    "      'X-Origin': 'https://www.youtube.com',",
    "      'X-Goog-AuthUser': '0',",
    "      'X-Goog-PageId': cfg.DELEGATED_SESSION_ID || '',",
    "    },",
    "    body: JSON.stringify({ context: cfg.INNERTUBE_CONTEXT, playlistId: playlist_id, actions: actions }),",
    "  });",
    "  const json = await res.json();",
    "  return json.status || (json.error ? json.error.message : 'unknown');",
    "};",
    "window.playlist_description_set = async function (playlist_id, description) {",
    "  return await window.playlist_edit(playlist_id, [{ action: 'ACTION_SET_PLAYLIST_DESCRIPTION', playlistDescription: description }]);",
    "};",
    "window.playlist_videos_add = async function (playlist_id, video_ids) {",
    "  const actions = video_ids.map(id => ({ action: 'ACTION_ADD_VIDEO', addedVideoId: id }));",
    "  return await window.playlist_edit(playlist_id, actions);",
    "};",
    "window.playlist_video_move_to_end = async function (playlist_id, video_id) {",
    "  const gone = await window.playlist_edit(playlist_id, [{ action: 'ACTION_REMOVE_VIDEO_BY_VIDEO_ID', removedVideoId: video_id }]);",
    "  if (gone !== 'STATUS_SUCCEEDED') { return 'left where it was: ' + gone; }",
    "  const back = await window.playlist_videos_add(playlist_id, [video_id]);",
    "  if (back !== 'STATUS_SUCCEEDED') { return 'TAKEN OUT AND NOT PUT BACK, ' + video_id + ': ' + back; }",
    "  return 'moved';",
    "};",
    "window.psalm_order_apply = async function () {",
    "  const out = {};",
    "  for (const item of window.psalm_order) {",
    "    const answers = [];",
    "    for (const video_id of item.move_to_end) {",
    "      answers.push(await window.playlist_video_move_to_end(item.playlist_id, video_id));",
    "    }",
    "    out[item.chapter] = answers.join(' ');",
    "  }",
    "  return JSON.stringify(out);",
    "};",
    "window.psalm_descriptions_apply = async function () {",
    "  const out = {};",
    "  for (const item of window.psalm_batch) {",
    "    out[item.chapter] = await window.playlist_description_set(item.playlist_id, item.description);",
    "  }",
    "  return JSON.stringify(out);",
    "};",
    "window.psalm_plan_apply = async function () {",
    "  const out = {};",
    "  for (const item of window.psalm_plan) {",
    "    if (item.playlist_id === null) { out[item.chapter] = 'no playlist yet'; continue; }",
    "    if (item.add.length === 0) { out[item.chapter] = 'nothing to add'; continue; }",
    "    out[item.chapter] = await window.playlist_videos_add(item.playlist_id, item.add);",
    "  }",
    "  return JSON.stringify(out);",
    "};",
  ];
  let script = lines.join("\n");
  return script;
}
