# GENERATED by python_code_mirror — do not edit by hand.
# Source of truth: js/dispatcher_scripts_claude.mjs. Regenerate with
# `node scripts/r.mjs python_mirrors_write`; drift fails `q`
# via python_mirrors_assert.
AI_DISPATCHER_SCRIPTS = {"scripts/ai.mjs", "scripts/aig.mjs"}
