# GENERATED by python_code_dispatcher_scripts — do not edit by hand.
# Source of truth: js/dispatcher_scripts.mjs. Regenerate with
# `node scripts/r.mjs dispatcher_scripts_python_write`; drift fails `q`
# via dispatcher_scripts_python_assert.
NODE_DISPATCHER_SCRIPTS = {"scripts/r.mjs", "scripts/rl.mjs", "scripts/ai.mjs", "scripts/g.mjs"}
