# GENERATED by python_code_dispatcher_commands — do not edit by hand.
# Source of truth: js/dispatcher_commands_fn_named.mjs. Regenerate with
# `node scripts/r.mjs dispatcher_commands_python_write`; drift fails `q`
# via dispatcher_commands_python_assert.
DISPATCHER_COMMANDS_FN_NAMED = {"ai_git_command_args"}
