# GENERATED by python_code_mirror — do not edit by hand.
# Source of truth: js/functions_input_taken_away.mjs. Regenerate with
# `node scripts/r.mjs python_mirrors_write`; drift fails `q`
# via python_mirrors_assert.
FUNCTIONS_INPUT_TAKEN_AWAY = {"app_ceb_bible_gloss_write_chapter_file", "app_en_learn_bible_gloss_urdu_write_chapter_file"}
