# GENERATED by python_code_mirror — do not edit by hand.
# Source of truth: js/memory_folder_spellings.mjs. Regenerate with
# `node scripts/r.mjs python_mirrors_write`; drift fails `q`
# via python_mirrors_assert.
MEMORY_FOLDER_SPELLINGS = {"/home/j/.claude/projects/-home-j-a-repos-love/memory", "/home/j/a/backup/love/claude_memory/memory"}
